import type { SeedProblem } from './types';

// 5.F units 12–16 (nums 111–160) — continues the Gr-5 Foundations course.
// 12: fraction word problems & estimation · 13: numerical expressions &
// order of operations · 14: patterns, rules & relationships · 15: volume,
// measurement conversion & data · 16: 2-D figures & the coordinate plane.
// Every answer is recomputed inside the explanation steps; difficulty-3
// problems carry a 4-step hint series and a "⚠️ The trap here" write-up.
// No diagrams: every figure or data set is described fully in words.

export const problems5Fu12: SeedProblem[] = [
  // ============ UNIT 12 — Fraction word problems & estimation ============
  {
    domain: '5.F', num: 111, unit: 12, order: 1, slug: 'granola-oats-three-batches',
    standard: '5.NF.B.6', difficulty: 1,
    prompt: 'Maya makes granola. One batch uses $\\frac{2}{3}$ cup of oats. How many cups of oats does she need for $3$ batches?',
    answerType: 'numeric', primaryAnswer: '2', alternativeAnswers: ['2 cups', '6/3'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Three batches means $\\frac{2}{3}$ added three times — or $3 \\times \\frac{2}{3}$.' },
      { level: 'guide', text: 'Multiply the top number by $3$ and leave the bottom alone: $3 \\times \\frac{2}{3} = \\frac{6}{3}$.' },
      { level: 'reveal', text: '$\\frac{6}{3} = 2$, so Maya needs $2$ cups.' },
    ],
    explanation: [
      'Three batches each use $\\frac{2}{3}$ cup, so the total is $3 \\times \\frac{2}{3}$.',
      'When you multiply a fraction by a whole number, the whole number multiplies the numerator: $3 \\times \\frac{2}{3} = \\frac{6}{3}$.',
      '$\\frac{6}{3}$ means $6 \\div 3$, which is $2$.',
      'Maya needs $2$ cups of oats.',
    ],
    alternativeExplanations: [
      { title: 'Just add them up', steps: ['$\\frac{2}{3} + \\frac{2}{3} + \\frac{2}{3} = \\frac{6}{3}$.', 'Three thirds make one whole, so six thirds make $2$ wholes.'] },
    ],
    tags: ['fractions', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 112, unit: 12, order: 2, slug: 'allowance-two-fifths-savings',
    standard: '5.NF.B.6', difficulty: 1,
    prompt: 'Jordan gets a $\\$15$ allowance each week and puts $\\frac{2}{5}$ of it into savings. How many dollars go into savings each week?',
    answerType: 'numeric', primaryAnswer: '6', alternativeAnswers: ['\\$6', '$6'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Split the $\\$15$ into $5$ equal parts first — that tells you what one fifth is worth.' },
      { level: 'guide', text: '$15 \\div 5 = 3$, so one fifth is $\\$3$. You need two of those fifths.' },
      { level: 'reveal', text: '$2 \\times 3 = 6$, so $\\$6$ goes into savings.' },
    ],
    explanation: [
      '"$\\frac{2}{5}$ of $\\$15$" means $\\frac{2}{5} \\times 15$.',
      'Split $\\$15$ into $5$ equal fifths: $15 \\div 5 = 3$, so each fifth is $\\$3$.',
      'Two of those fifths is $2 \\times 3 = 6$.',
      'Jordan saves $\\$6$ every week.',
    ],
    alternativeExplanations: [
      { title: 'Multiply straight across', steps: ['$\\frac{2}{5} \\times \\frac{15}{1} = \\frac{30}{5}$.', '$30 \\div 5 = 6$, the same $\\$6$.'] },
    ],
    tags: ['MAP-practice', 'fractions', 'money'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 113, unit: 12, order: 3, slug: 'benchmark-estimate-granola-bars',
    standard: '5.NF.A.2', difficulty: 1,
    prompt: 'Ella ate $\\frac{5}{8}$ of a granola bar in the morning and $\\frac{1}{3}$ of another one at lunch. Without adding exactly, about how much granola bar did she eat in all?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'about 0 bars', correct: false },
      { id: 'B', label: 'about 1/2 of a bar', correct: false },
      { id: 'C', label: 'about 1 whole bar', correct: true },
      { id: 'D', label: 'about 2 bars', correct: false },
    ],
    primaryAnswer: 'C', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Round each fraction to the nearest friendly number: $0$, $\\frac{1}{2}$, or $1$.' },
      { level: 'guide', text: '$\\frac{5}{8}$ is a little more than $\\frac{1}{2}$, and $\\frac{1}{3}$ is a little less than $\\frac{1}{2}$.' },
      { level: 'reveal', text: 'About $\\frac{1}{2} + \\frac{1}{2} = 1$ whole bar.' },
    ],
    explanation: [
      'Compare each fraction to the benchmarks $0$, $\\frac{1}{2}$, and $1$.',
      '$\\frac{5}{8}$ is just past half (half of $8$ is $4$, and $5 > 4$), and $\\frac{1}{3}$ is just under half.',
      'So the sum is about $\\frac{1}{2} + \\frac{1}{2} = 1$ whole granola bar.',
      'The exact answer, $\\frac{23}{24}$, really is just under $1$ — the estimate was right.',
    ],
    alternativeExplanations: [
      { title: 'Why not 2?', steps: ['Each piece is less than one whole bar, so the total has to be less than $2$.', 'And both pieces are around half, so $\\frac{1}{2}$ alone is too small — $1$ is the best fit.'] },
    ],
    tags: ['MAP-practice', 'estimation', 'benchmarks'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 114, unit: 12, order: 4, slug: 'mural-paint-scaling-smaller',
    standard: '5.NF.B.6', difficulty: 1,
    prompt: 'Painting the WHOLE mural wall takes $6$ quarts of blue paint. Rosa only paints $\\frac{3}{4}$ of the wall. Without multiplying, decide how much paint she uses.',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'more than 6 quarts', correct: false },
      { id: 'B', label: 'exactly 6 quarts', correct: false },
      { id: 'C', label: 'less than 6 quarts', correct: true },
      { id: 'D', label: 'there is no way to tell', correct: false },
    ],
    primaryAnswer: 'C', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Is $\\frac{3}{4}$ bigger or smaller than one whole?' },
      { level: 'guide', text: 'Multiplying by a number less than $1$ always shrinks the amount you started with.' },
      { level: 'reveal', text: '$\\frac{3}{4}$ is less than $1$, so the paint needed is less than $6$ quarts.' },
    ],
    explanation: [
      'Rosa paints only part of the wall, so she cannot need as much paint as the whole wall takes.',
      'In math language: $\\frac{3}{4} \\times 6$ scales $6$ DOWN because $\\frac{3}{4} < 1$.',
      'So the answer must be less than $6$ quarts.',
      'Checking it: $\\frac{3}{4} \\times 6 = \\frac{18}{4} = 4\\frac{1}{2}$ quarts — less than $6$, just as predicted.',
    ],
    alternativeExplanations: [
      { title: 'The size-of-the-answer rule', steps: ['Multiplying by a fraction less than $1$ makes the answer smaller.', 'Multiplying by exactly $1$ keeps it the same.', 'Multiplying by a number greater than $1$ makes it bigger.'] },
    ],
    tags: ['MAP-practice', 'scaling', 'reasoning'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 115, unit: 12, order: 5, slug: 'brownie-pan-half-of-two-thirds',
    standard: '5.NF.B.6', difficulty: 2,
    prompt: 'After dinner, $\\frac{2}{3}$ of a pan of brownies is left. Sam eats $\\frac{1}{2}$ of what is left. What fraction of the WHOLE pan did Sam eat?',
    answerType: 'fraction', primaryAnswer: '1/3', alternativeAnswers: ['2/6'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The word "of" here means multiply: $\\frac{1}{2}$ of $\\frac{2}{3}$.' },
      { level: 'guide', text: 'Multiply straight across: $\\frac{1}{2} \\times \\frac{2}{3} = \\frac{1 \\times 2}{2 \\times 3}$.' },
      { level: 'reveal', text: '$\\frac{2}{6} = \\frac{1}{3}$ of the whole pan.' },
    ],
    explanation: [
      'Sam eats half of the leftovers, so the question is $\\frac{1}{2} \\times \\frac{2}{3}$.',
      'Multiply the numerators and the denominators: $\\frac{1 \\times 2}{2 \\times 3} = \\frac{2}{6}$.',
      '$\\frac{2}{6}$ simplifies to $\\frac{1}{3}$.',
      'Sam ate $\\frac{1}{3}$ of the whole pan.',
    ],
    alternativeExplanations: [
      { title: 'Picture the pan', steps: ['Cut the pan into $3$ equal strips; $2$ strips are left.', 'Half of $2$ strips is $1$ strip.', 'One strip out of the original $3$ is $\\frac{1}{3}$ of the pan.'] },
    ],
    tags: ['fractions', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: '5.F', num: 116, unit: 12, order: 6, slug: 'bookmark-ribbon-mixed-number',
    standard: '5.NF.B.6', difficulty: 2,
    prompt: 'Each bookmark uses $1\\frac{1}{4}$ feet of ribbon. How much ribbon do $6$ bookmarks use? (Answer as a mixed number.)',
    answerType: 'fraction', primaryAnswer: '7 1/2', alternativeAnswers: ['15/2', '7.5'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Turn the mixed number into an improper fraction first: $1\\frac{1}{4} = \\frac{5}{4}$.' },
      { level: 'guide', text: 'Now find $6 \\times \\frac{5}{4} = \\frac{30}{4}$.' },
      { level: 'reveal', text: '$\\frac{30}{4} = 7\\frac{2}{4} = 7\\frac{1}{2}$ feet.' },
    ],
    explanation: [
      'Rewrite the mixed number: $1\\frac{1}{4} = \\frac{4}{4} + \\frac{1}{4} = \\frac{5}{4}$.',
      'Six bookmarks need $6 \\times \\frac{5}{4} = \\frac{30}{4}$ feet.',
      '$30 \\div 4 = 7$ with $2$ left over, so $\\frac{30}{4} = 7\\frac{2}{4} = 7\\frac{1}{2}$.',
      'The six bookmarks use $7\\frac{1}{2}$ feet of ribbon.',
    ],
    alternativeExplanations: [
      { title: 'Split the mixed number', steps: ['$6 \\times 1 = 6$ feet from the whole parts.', '$6 \\times \\frac{1}{4} = \\frac{6}{4} = 1\\frac{1}{2}$ feet from the quarter parts.', '$6 + 1\\frac{1}{2} = 7\\frac{1}{2}$ feet.'] },
    ],
    tags: ['fractions', 'mixed-numbers'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 117, unit: 12, order: 7, slug: 'is-this-answer-reasonable-fraction',
    standard: '5.NF.A.2', difficulty: 2,
    prompt: 'Ben says that $\\frac{7}{8} \\times 24 = 27$. Without multiplying it out, what do you know about his answer?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'It is reasonable.', correct: false },
      { id: 'B', label: 'It is too big — the answer must be less than 24.', correct: true },
      { id: 'C', label: 'It is too small — the answer must be more than 24.', correct: false },
      { id: 'D', label: 'You cannot tell without multiplying.', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Is $\\frac{7}{8}$ less than $1$ or more than $1$?' },
      { level: 'guide', text: 'Taking $\\frac{7}{8}$ of something means taking almost all of it — but never more than all of it.' },
      { level: 'reveal', text: 'The answer has to be under $24$, so $27$ is too big. (It is really $21$.)' },
    ],
    explanation: [
      '$\\frac{7}{8}$ is less than $1$, so $\\frac{7}{8} \\times 24$ must be less than $24$.',
      'Ben\'s answer of $27$ is bigger than $24$, so it cannot be right.',
      'The true value: one eighth of $24$ is $24 \\div 8 = 3$, and $7 \\times 3 = 21$.',
      '$21$ is just under $24$, which fits the estimate perfectly.',
    ],
    alternativeExplanations: [
      { title: 'Estimate with a benchmark', steps: ['$\\frac{7}{8}$ is close to $1$, so the answer should be close to but below $24$.', 'Something like $21$ fits; $27$ does not.'] },
    ],
    tags: ['MAP-practice', 'estimation', 'reasoning'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 118, unit: 12, order: 8, slug: 'field-trip-lunch-three-eighths',
    standard: '5.NF.B.6', difficulty: 2,
    prompt: 'There are $40$ students on the field trip. $\\frac{3}{8}$ of them brought lunch from home. How many students did NOT bring lunch from home?',
    answerType: 'numeric', primaryAnswer: '25', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two steps: first find how many DID bring lunch, then subtract from $40$.' },
      { level: 'guide', text: 'One eighth of $40$ is $40 \\div 8 = 5$, so $\\frac{3}{8}$ of $40$ is $3 \\times 5 = 15$.' },
      { level: 'reveal', text: '$40 - 15 = 25$ students did not bring lunch.' },
    ],
    explanation: [
      'Step 1 — how many brought lunch: $\\frac{3}{8} \\times 40$. One eighth of $40$ is $40 \\div 8 = 5$, so three eighths is $3 \\times 5 = 15$ students.',
      'Step 2 — the rest: $40 - 15 = 25$ students did not bring lunch from home.',
      'So $25$ students will need a school lunch.',
    ],
    alternativeExplanations: [
      { title: 'Use the other fraction', steps: ['If $\\frac{3}{8}$ brought lunch, then $\\frac{5}{8}$ did not.', '$\\frac{5}{8} \\times 40 = 5 \\times 5 = 25$ — the same $25$ students.'] },
    ],
    tags: ['MAP-practice', 'fractions', 'multi-step', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 119, unit: 12, order: 9, slug: 'garden-bed-area-mixed-fraction',
    standard: '5.NF.B.6', difficulty: 3,
    prompt: 'A rectangular garden bed is $4\\frac{1}{2}$ feet long and $\\frac{2}{3}$ foot wide. What is its area, in square feet?',
    answerType: 'numeric', primaryAnswer: '3', alternativeAnswers: ['3 sq ft', '18/6'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a bed $3$ ft by $\\frac{2}{3}$ ft first. Area $= 3 \\times \\frac{2}{3} = \\frac{6}{3} = 2$ square feet. Same moves work with a mixed number — you just have to change it to an improper fraction first.' },
      { level: 'nudge', text: 'Area of a rectangle is length $\\times$ width, even when both are fractions.' },
      { level: 'guide', text: 'Rewrite $4\\frac{1}{2}$ as $\\frac{9}{2}$, then multiply $\\frac{9}{2} \\times \\frac{2}{3}$ straight across.' },
      { level: 'reveal', text: '$\\frac{9 \\times 2}{2 \\times 3} = \\frac{18}{6} = 3$ square feet.' },
    ],
    explanation: [
      'Area $=$ length $\\times$ width, so this is $4\\frac{1}{2} \\times \\frac{2}{3}$.',
      'Change the mixed number to an improper fraction: $4\\frac{1}{2} = \\frac{8}{2} + \\frac{1}{2} = \\frac{9}{2}$.',
      'Multiply straight across: $\\frac{9}{2} \\times \\frac{2}{3} = \\frac{18}{6}$.',
      '$18 \\div 6 = 3$, so the garden bed covers $3$ square feet.',
    ],
    alternativeExplanations: [
      { title: 'Break the length apart', steps: ['$4 \\times \\frac{2}{3} = \\frac{8}{3} = 2\\frac{2}{3}$.', '$\\frac{1}{2} \\times \\frac{2}{3} = \\frac{2}{6} = \\frac{1}{3}$.', '$2\\frac{2}{3} + \\frac{1}{3} = 3$ square feet.'] },
      { title: '⚠️ The trap here', steps: ['The most common wrong answer is $2\\frac{2}{3}$ — that comes from multiplying only the whole number, $4 \\times \\frac{2}{3}$, and forgetting the extra $\\frac{1}{2}$ foot of length.', 'Escape it by turning the mixed number into ONE improper fraction, $\\frac{9}{2}$, before you multiply — then there is no leftover piece to forget.', 'Quick sanity check: $\\frac{2}{3}$ of about $4\\frac{1}{2}$ should be about $3$, and $3$ is what you get.'] },
    ],
    tags: ['MAP-practice', 'fractions', 'area', 'multi-step'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 120, unit: 12, order: 10, slug: 'video-game-score-three-quarters-bonus',
    standard: '5.NF.B.6', difficulty: 3,
    prompt: 'Leo scored $240$ points in a video game. Mia scored $\\frac{3}{4}$ as many points as Leo, and then earned $35$ bonus points. How many points does Mia have in all?',
    answerType: 'numeric', primaryAnswer: '215', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Pretend Leo scored $40$. Then $\\frac{3}{4}$ of $40$ is $40 \\div 4 = 10$, and $3 \\times 10 = 30$; add a $5$-point bonus and Mia has $35$. Use those same two steps with the real numbers.' },
      { level: 'nudge', text: 'Do the fraction first, then add the bonus — the bonus is NOT part of the $\\frac{3}{4}$.' },
      { level: 'guide', text: '$240 \\div 4 = 60$, so $\\frac{3}{4}$ of $240$ is $3 \\times 60$.' },
      { level: 'reveal', text: '$3 \\times 60 = 180$, and $180 + 35 = 215$ points.' },
    ],
    explanation: [
      'Step 1 — Mia\'s game points: $\\frac{3}{4} \\times 240$. One fourth of $240$ is $240 \\div 4 = 60$, so three fourths is $3 \\times 60 = 180$.',
      'Step 2 — add the bonus, which she earns on top: $180 + 35 = 215$.',
      'Mia finishes with $215$ points.',
      'That is sensible: $215$ is less than Leo\'s $240$, which it should be, since her game score was only three fourths of his.',
    ],
    alternativeExplanations: [
      { title: 'Take away the missing fourth', steps: ['$\\frac{3}{4}$ of $240$ is all of $240$ minus one fourth of it.', '$240 \\div 4 = 60$, so $240 - 60 = 180$.', '$180 + 35 = 215$ points.'] },
      { title: '⚠️ The trap here', steps: ['The usual wrong answer is $180$ — the right fraction work, but the $35$ bonus points never get added.', 'Another trap is adding first: $240 + 35 = 275$, then $\\frac{3}{4}$ of that, which wrongly shrinks the bonus too.', 'Escape both by underlining the two steps in the question before you compute: "scored $\\frac{3}{4}$ as many" happens first, "and then earned $35$ bonus" happens second.'] },
    ],
    tags: ['MAP-practice', 'fractions', 'multi-step', 'word-problem'], estimatedSeconds: 75,
  },

  // ============ UNIT 13 — Numerical expressions & order of operations ============
  {
    domain: '5.F', num: 121, unit: 13, order: 1, slug: 'evaluate-five-times-sum',
    standard: '5.OA.A.1', difficulty: 1,
    prompt: 'Evaluate: $5 \\times (7 + 3)$',
    answerType: 'numeric', primaryAnswer: '50', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Parentheses go first, always.' },
      { level: 'guide', text: '$7 + 3 = 10$, so the expression becomes $5 \\times 10$.' },
      { level: 'reveal', text: '$5 \\times 10 = 50$.' },
    ],
    explanation: [
      'Parentheses tell you which part to do first: $7 + 3 = 10$.',
      'Now the expression is $5 \\times 10$.',
      '$5 \\times 10 = 50$.',
    ],
    alternativeExplanations: [
      { title: 'Spread the 5 out', steps: ['$5 \\times (7 + 3) = 5 \\times 7 + 5 \\times 3$.', '$35 + 15 = 50$ — same answer.'] },
    ],
    tags: ['order-of-operations'], estimatedSeconds: 30,
  },
  {
    domain: '5.F', num: 122, unit: 13, order: 2, slug: 'evaluate-difference-divided',
    standard: '5.OA.A.1', difficulty: 1,
    prompt: 'Evaluate: $(36 - 12) \\div 4$',
    answerType: 'numeric', primaryAnswer: '6', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Handle what is inside the parentheses before you divide.' },
      { level: 'guide', text: '$36 - 12 = 24$, so now you need $24 \\div 4$.' },
      { level: 'reveal', text: '$24 \\div 4 = 6$.' },
    ],
    explanation: [
      'Do the parentheses first: $36 - 12 = 24$.',
      'That leaves $24 \\div 4$.',
      '$24 \\div 4 = 6$.',
    ],
    alternativeExplanations: [
      { title: 'A picture for it', steps: ['Imagine $36$ trading cards, $12$ given away, and the rest split among $4$ friends.', '$24$ cards split $4$ ways gives each friend $6$ cards.'] },
    ],
    tags: ['order-of-operations'], estimatedSeconds: 30,
  },
  {
    domain: '5.F', num: 123, unit: 13, order: 3, slug: 'write-three-times-sum-expression',
    standard: '5.OA.A.2', difficulty: 1,
    prompt: 'Write an expression for "three times the sum of $8$ and $5$." Do NOT work out the answer — just write the expression.',
    answerType: 'expression', primaryAnswer: '3 × (8 + 5)',
    alternativeAnswers: ['3*(8+5)', '3 * (8 + 5)', '3(8+5)', '(8+5)*3', '(8 + 5) × 3', '3 x (8 + 5)'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The word "sum" means addition, so $8$ and $5$ get added.' },
      { level: 'guide', text: 'The whole sum gets tripled, so wrap the addition in parentheses before multiplying.' },
      { level: 'reveal', text: '$3 \\times (8 + 5)$.' },
    ],
    explanation: [
      '"The sum of $8$ and $5$" is the piece $8 + 5$.',
      '"Three times" that whole sum means the addition must happen first, so it needs parentheses: $3 \\times (8 + 5)$.',
      'Without the parentheses, $3 \\times 8 + 5$ would only triple the $8$ — a different expression.',
      'The question asked only for the expression, so $3 \\times (8 + 5)$ is the finished answer.',
    ],
    alternativeExplanations: [
      { title: 'Check the meaning', steps: ['$8 + 5 = 13$, and three times $13$ is $39$.', '$3 \\times 8 + 5 = 29$, which is not "three times the sum" — proof that the parentheses matter.'] },
    ],
    tags: ['expressions', 'writing-expressions'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 124, unit: 13, order: 4, slug: 'compare-expression-without-computing',
    standard: '5.OA.A.2', difficulty: 1,
    prompt: 'Without doing any arithmetic, how does $3 \\times (245 + 17)$ compare with $245 + 17$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'It is 3 more.', correct: false },
      { id: 'B', label: 'It is 3 times as big.', correct: true },
      { id: 'C', label: 'It is exactly the same.', correct: false },
      { id: 'D', label: 'It is 3 less.', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Both expressions contain the same piece, $245 + 17$. What is being done to that piece?' },
      { level: 'guide', text: 'The parentheses keep $245 + 17$ together as one chunk, and the $3$ multiplies that whole chunk.' },
      { level: 'reveal', text: 'Multiplying by $3$ makes it $3$ times as big.' },
    ],
    explanation: [
      'Think of $245 + 17$ as one bundle, kept together by the parentheses.',
      'The $3$ outside multiplies that entire bundle, so you have three copies of it.',
      'That makes the first expression $3$ times as big as the second.',
      'You never needed the actual total to see it — but if you check, $245 + 17 = 262$ and $3 \\times 262 = 786$, which is indeed $3$ times $262$.',
    ],
    alternativeExplanations: [
      { title: 'Think in snack packs', steps: ['If one lunch bag holds $245$ crackers and $17$ grapes, that is one bundle.', 'Three bundles is $3 \\times$ one bundle — three times as much, not three more items.'] },
    ],
    tags: ['MAP-practice', 'expressions', 'reasoning'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 125, unit: 13, order: 5, slug: 'brackets-four-times-difference',
    standard: '5.OA.A.1', difficulty: 2,
    prompt: 'Evaluate: $[4 \\times (9 - 5)] + 12$',
    answerType: 'numeric', primaryAnswer: '28', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Work from the inside out — the roundest, innermost parentheses first.' },
      { level: 'guide', text: '$9 - 5 = 4$, so the brackets hold $[4 \\times 4]$.' },
      { level: 'reveal', text: '$4 \\times 4 = 16$, and $16 + 12 = 28$.' },
    ],
    explanation: [
      'Start inside the parentheses: $9 - 5 = 4$.',
      'Now the brackets say $[4 \\times 4] = 16$.',
      'Finally add what is outside: $16 + 12 = 28$.',
    ],
    alternativeExplanations: [
      { title: 'Peel it like an onion', steps: ['Innermost layer: $(9 - 5) = 4$.', 'Next layer: $[4 \\times 4] = 16$.', 'Outer layer: $16 + 12 = 28$.'] },
    ],
    tags: ['MAP-practice', 'order-of-operations', 'brackets'], estimatedSeconds: 50,
  },
  {
    domain: '5.F', num: 126, unit: 13, order: 6, slug: 'supply-packs-expression-value',
    standard: '5.OA.A.1', difficulty: 2,
    prompt: 'A teacher buys $4$ supply packs. Each pack holds $6$ markers and $3$ pencils. The expression $4 \\times (6 + 3)$ gives the total number of items. What is its value?',
    answerType: 'numeric', primaryAnswer: '36', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'How many items are in ONE pack? That is the parentheses part.' },
      { level: 'guide', text: '$6 + 3 = 9$ items per pack, and there are $4$ packs.' },
      { level: 'reveal', text: '$4 \\times 9 = 36$ items.' },
    ],
    explanation: [
      'The parentheses count one pack: $6 + 3 = 9$ items.',
      'There are $4$ identical packs, so the total is $4 \\times 9 = 36$ items.',
      'The parentheses are what make the $3$ pencils get counted in every pack, not just once.',
    ],
    alternativeExplanations: [
      { title: 'Count each kind separately', steps: ['Markers: $4 \\times 6 = 24$.', 'Pencils: $4 \\times 3 = 12$.', '$24 + 12 = 36$ items — the same total.'] },
    ],
    tags: ['MAP-practice', 'order-of-operations', 'word-problem'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 127, unit: 13, order: 7, slug: 'write-subtract-then-multiply-expression',
    standard: '5.OA.A.2', difficulty: 2,
    prompt: 'Write an expression for: "subtract $9$ from $40$, then multiply the result by $5$." Do not evaluate it.',
    answerType: 'expression', primaryAnswer: '(40 - 9) × 5',
    alternativeAnswers: ['(40-9)*5', '(40 - 9) * 5', '5*(40-9)', '5 × (40 - 9)', '(40 - 9) x 5', '5(40-9)'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Subtract $9$ from $40$" means $40$ comes first: $40 - 9$.' },
      { level: 'guide', text: 'That subtraction has to happen before the multiplying, so it needs parentheses.' },
      { level: 'reveal', text: '$(40 - 9) \\times 5$.' },
    ],
    explanation: [
      '"Subtract $9$ from $40$" is $40 - 9$ — the number you subtract FROM is written first.',
      '"Then multiply the result by $5$" means the whole subtraction gets multiplied, so wrap it: $(40 - 9) \\times 5$.',
      'Without parentheses, $40 - 9 \\times 5$ would multiply only the $9$, which is a different instruction.',
      'The answer is the expression $(40 - 9) \\times 5$ — no need to compute it.',
    ],
    alternativeExplanations: [
      { title: 'Why order matters', steps: ['$(40 - 9) \\times 5 = 31 \\times 5 = 155$.', '$40 - 9 \\times 5 = 40 - 45$, which is not even a whole-number answer a 5th grader would want.', 'The parentheses protect the step you meant to do first.'] },
    ],
    tags: ['expressions', 'writing-expressions'], estimatedSeconds: 50,
  },
  {
    domain: '5.F', num: 128, unit: 13, order: 8, slug: 'place-the-parentheses-56',
    standard: '5.OA.A.1', difficulty: 2,
    prompt: 'Where should parentheses go so that $24 - 6 \\times 3 + 2$ equals $56$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '(24 − 6) × 3 + 2', correct: true },
      { id: 'B', label: '24 − (6 × 3) + 2', correct: false },
      { id: 'C', label: '24 − 6 × (3 + 2)', correct: false },
      { id: 'D', label: '(24 − 6) × (3 + 2)', correct: false },
    ],
    primaryAnswer: 'A', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$56$ is much bigger than $24$, so the multiplying must act on a big chunk.' },
      { level: 'guide', text: 'Try making $24 - 6$ happen first: that gives $18$, and $18 \\times 3$ is already close to $56$.' },
      { level: 'reveal', text: '$(24 - 6) \\times 3 + 2 = 18 \\times 3 + 2 = 54 + 2 = 56$.' },
    ],
    explanation: [
      'Test choice A: $(24 - 6) = 18$, then $18 \\times 3 = 54$, then $54 + 2 = 56$. That works.',
      'Choice B gives $24 - 18 + 2 = 8$, and choice D gives $18 \\times 5 = 90$ — both miss.',
      'Choice C would need $6 \\times 5 = 30$ subtracted from $24$, which goes below zero.',
      'So the parentheses belong around $24 - 6$.',
    ],
    alternativeExplanations: [
      { title: 'Estimate before testing', steps: ['To reach $56$ you need roughly $18 \\times 3$.', 'The only way to get $18$ out of these numbers is $24 - 6$, so start there.'] },
    ],
    tags: ['MAP-practice', 'order-of-operations', 'reasoning'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 129, unit: 13, order: 9, slug: 'nested-brackets-three-times',
    standard: '5.OA.A.1', difficulty: 3,
    prompt: 'Evaluate: $3 \\times [20 - (4 + 2 \\times 3)]$',
    answerType: 'numeric', primaryAnswer: '30', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up on $2 \\times [10 - (1 + 2 \\times 2)]$. Inside: $2 \\times 2 = 4$, then $1 + 4 = 5$, then $10 - 5 = 5$, then $2 \\times 5 = 10$. The big problem uses exactly that order.' },
      { level: 'nudge', text: 'Go from the innermost parentheses outward, and inside them, multiply before you add.' },
      { level: 'guide', text: 'Inside the parentheses: $2 \\times 3 = 6$, then $4 + 6 = 10$.' },
      { level: 'reveal', text: '$20 - 10 = 10$, and $3 \\times 10 = 30$.' },
    ],
    explanation: [
      'Innermost first: inside $(4 + 2 \\times 3)$, multiplication beats addition, so $2 \\times 3 = 6$ and then $4 + 6 = 10$.',
      'Now the brackets read $[20 - 10] = 10$.',
      'Finally, $3 \\times 10 = 30$.',
      'The expression equals $30$.',
    ],
    alternativeExplanations: [
      { title: 'Rewrite at every step', steps: ['$3 \\times [20 - (4 + 2 \\times 3)]$', '$= 3 \\times [20 - (4 + 6)]$', '$= 3 \\times [20 - 10] = 3 \\times 10 = 30$.'] },
      { title: '⚠️ The trap here', steps: ['The classic wrong answer is $6$: it comes from adding $4 + 2 = 6$ first, then $6 \\times 3 = 18$, then $20 - 18 = 2$ and $3 \\times 2 = 6$.', 'The problem is that left-to-right does not win inside parentheses — multiplication still goes before addition.', 'Escape it by circling $2 \\times 3$ before you touch the $4$, so the multiplication is finished first every time.'] },
    ],
    tags: ['order-of-operations', 'brackets', 'multi-step'], estimatedSeconds: 70,
  },
  {
    domain: '5.F', num: 130, unit: 13, order: 10, slug: 'two-brackets-multiplied',
    standard: '5.OA.A.1', difficulty: 3,
    prompt: 'Evaluate: $[(18 + 6) \\div 3] \\times [15 - (2 \\times 4)]$',
    answerType: 'numeric', primaryAnswer: '56', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up on $[(4 + 2) \\div 3] \\times [10 - (2 \\times 3)]$. Left bracket: $6 \\div 3 = 2$. Right bracket: $10 - 6 = 4$. Then $2 \\times 4 = 8$. Same two-bracket plan below.' },
      { level: 'nudge', text: 'Treat the two brackets as two separate mini-problems, then multiply your two results.' },
      { level: 'guide', text: 'Left bracket: $18 + 6 = 24$, then $24 \\div 3$. Right bracket: $2 \\times 4 = 8$, then $15 - 8$.' },
      { level: 'reveal', text: 'Left is $8$, right is $7$, and $8 \\times 7 = 56$.' },
    ],
    explanation: [
      'Left bracket: the parentheses go first, $18 + 6 = 24$, then $24 \\div 3 = 8$.',
      'Right bracket: the parentheses go first, $2 \\times 4 = 8$, then $15 - 8 = 7$.',
      'Now multiply the two finished brackets: $8 \\times 7 = 56$.',
      'The expression equals $56$.',
    ],
    alternativeExplanations: [
      { title: 'Write it as a shrinking line', steps: ['$[(18 + 6) \\div 3] \\times [15 - (2 \\times 4)]$', '$= [24 \\div 3] \\times [15 - 8]$', '$= 8 \\times 7 = 56$.'] },
      { title: '⚠️ The trap here', steps: ['A very common wrong answer is $140$: that comes from reading the left bracket as $18 + 6 \\div 3 = 18 + 2 = 20$, then $20 \\times 7$.', 'The inner parentheses around $18 + 6$ are exactly what stops that — they say add first, divide second.', 'Escape it by copying the expression and physically crossing out each pair of parentheses as you finish it, so you never skip one.'] },
    ],
    tags: ['MAP-practice', 'order-of-operations', 'brackets', 'multi-step'], estimatedSeconds: 75,
  },

  // ============ UNIT 14 — Patterns, rules & relationships ============
  {
    domain: '5.F', num: 131, unit: 14, order: 1, slug: 'add-three-rule-sixth-term',
    standard: '5.OA.B.3', difficulty: 1,
    prompt: 'Start at $0$ and follow the rule "add $3$": $0, 3, 6, 9, \\dots$ What is the $6$th number in this pattern?',
    answerType: 'numeric', primaryAnswer: '15', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Keep listing and count the numbers as you go — $0$ counts as the 1st one.' },
      { level: 'guide', text: 'After $9$ comes $12$, then the next one.' },
      { level: 'reveal', text: '$0, 3, 6, 9, 12, 15$ — the 6th number is $15$.' },
    ],
    explanation: [
      'Write the pattern out, counting positions: 1st $= 0$, 2nd $= 3$, 3rd $= 6$, 4th $= 9$, 5th $= 12$, 6th $= 15$.',
      'Each step adds $3$, and going from the 1st to the 6th number takes $5$ steps.',
      'That matches the arithmetic: $0 + 5 \\times 3 = 15$.',
    ],
    alternativeExplanations: [
      { title: 'Skip counting', steps: ['Skip-count by $3$ on your fingers: $0, 3, 6, 9, 12, 15$.', 'The sixth finger lands on $15$.'] },
    ],
    tags: ['patterns'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 132, unit: 14, order: 2, slug: 'list-five-terms-add-five',
    standard: '5.OA.B.3', difficulty: 1,
    prompt: 'Follow the rule "add $5$" starting at $0$. Write the first FIVE numbers in order, separated by commas.',
    answerType: 'short-text', primaryAnswer: '0, 5, 10, 15, 20',
    alternativeAnswers: ['0,5,10,15,20', '0 5 10 15 20'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The first number is the starting number itself — you do not add yet.' },
      { level: 'guide', text: 'After $0$ comes $0 + 5 = 5$, then $5 + 5 = 10$…' },
      { level: 'reveal', text: '$0, 5, 10, 15, 20$.' },
    ],
    explanation: [
      'Start with $0$ — that is the first number in the pattern.',
      'Apply the rule again and again: $0 + 5 = 5$, $5 + 5 = 10$, $10 + 5 = 15$, $15 + 5 = 20$.',
      'The first five numbers are $0, 5, 10, 15, 20$.',
    ],
    alternativeExplanations: [
      { title: 'It is your nickel count', steps: ['Counting nickels gives $5, 10, 15, 20$ cents.', 'Starting from an empty hand adds the $0$ at the front.'] },
    ],
    tags: ['patterns'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 133, unit: 14, order: 3, slug: 'pattern-b-double-pattern-a',
    standard: '5.OA.B.3', difficulty: 1,
    prompt: 'Pattern A starts at $0$ and adds $2$ each time: $0, 2, 4, 6, \\dots$ Pattern B starts at $0$ and adds $4$ each time: $0, 4, 8, 12, \\dots$ Each number in Pattern B is ___ the matching number in Pattern A.',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '2 more than', correct: false },
      { id: 'B', label: '2 times', correct: true },
      { id: 'C', label: '4 times', correct: false },
      { id: 'D', label: 'half of', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Line the patterns up in pairs: $2$ with $4$, $4$ with $8$, $6$ with $12$.' },
      { level: 'guide', text: 'Ask "what do I multiply $2$ by to get $4$?" and check that the same thing works for $4$ and $8$.' },
      { level: 'reveal', text: 'Every B number is $2$ times the matching A number.' },
    ],
    explanation: [
      'Match the numbers by position: $(0,0)$, $(2,4)$, $(4,8)$, $(6,12)$.',
      '$2 \\times 2 = 4$, $2 \\times 4 = 8$, and $2 \\times 6 = 12$ — doubling works every single time.',
      '"$2$ more than" only works for the first pair or two, so it is not the real relationship.',
      'Pattern B is always $2$ times Pattern A.',
    ],
    alternativeExplanations: [
      { title: 'Look at the rules', steps: ['B adds $4$ each step while A adds $2$ each step.', 'B is growing twice as fast from the same start, so it stays exactly double.'] },
    ],
    tags: ['patterns', 'relationships'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 134, unit: 14, order: 4, slug: 'ordered-pair-from-third-terms',
    standard: '5.OA.B.3', difficulty: 1,
    prompt: 'Pattern A (add $2$ from $0$): $0, 2, 4, 6, 8$. Pattern B (add $6$ from $0$): $0, 6, 12, 18, 24$. Make an ordered pair from the 3rd number in each pattern, with Pattern A first. Write it like $(x, y)$.',
    answerType: 'short-text', primaryAnswer: '(4, 12)', alternativeAnswers: ['(4,12)', '4,12'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count to the 3rd number in each list — remember the $0$ is the 1st one.' },
      { level: 'guide', text: 'Pattern A: $0, 2, 4$ — the 3rd is $4$. Pattern B: $0, 6, 12$ — the 3rd is $12$.' },
      { level: 'reveal', text: 'Pattern A first, so the pair is $(4, 12)$.' },
    ],
    explanation: [
      'Count positions in Pattern A: 1st $= 0$, 2nd $= 2$, 3rd $= 4$.',
      'Count positions in Pattern B: 1st $= 0$, 2nd $= 6$, 3rd $= 12$.',
      'The problem says Pattern A goes first, so the $x$-coordinate is $4$ and the $y$-coordinate is $12$.',
      'The ordered pair is $(4, 12)$.',
    ],
    alternativeExplanations: [
      { title: 'Order matters', steps: ['$(4, 12)$ means go $4$ right and $12$ up.', '$(12, 4)$ would land somewhere completely different, so keeping A first matters.'] },
    ],
    tags: ['patterns', 'ordered-pairs'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 135, unit: 14, order: 5, slug: 'ana-ben-weekly-savings-gap',
    standard: '5.OA.B.3', difficulty: 2,
    prompt: 'Ana saves $\\$4$ every week and Ben saves $\\$6$ every week. Both start at $\\$0$. After $5$ weeks, how many more dollars does Ben have than Ana?',
    answerType: 'numeric', primaryAnswer: '10', alternativeAnswers: ['\\$10', '$10'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Build both money patterns week by week, then compare week $5$.' },
      { level: 'guide', text: 'Ana: $4, 8, 12, 16, 20$. Ben: $6, 12, 18, 24, 30$.' },
      { level: 'reveal', text: '$30 - 20 = 10$ dollars more for Ben.' },
    ],
    explanation: [
      'Ana\'s pattern is $4, 8, 12, 16, 20$, so after $5$ weeks she has $5 \\times 4 = \\$20$.',
      'Ben\'s pattern is $6, 12, 18, 24, 30$, so after $5$ weeks he has $5 \\times 6 = \\$30$.',
      '$30 - 20 = 10$, so Ben has $\\$10$ more than Ana.',
    ],
    alternativeExplanations: [
      { title: 'Track the gap instead', steps: ['Ben pulls ahead by $\\$2$ every single week.', 'After $5$ weeks the gap is $5 \\times 2 = \\$10$.'] },
    ],
    tags: ['MAP-practice', 'patterns', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 136, unit: 14, order: 6, slug: 'pattern-y-times-pattern-x',
    standard: '5.OA.B.3', difficulty: 2,
    prompt: 'Pattern X: $3, 6, 9, 12$. Pattern Y: $9, 18, 27, 36$. Each number in Pattern Y is how many times the matching number in Pattern X?',
    answerType: 'numeric', primaryAnswer: '3', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Pair them up: $3$ with $9$, $6$ with $18$, $9$ with $27$.' },
      { level: 'guide', text: 'Divide a Y number by its X partner: $9 \\div 3$.' },
      { level: 'reveal', text: 'Every pair gives $3$, so Y is always $3$ times X.' },
    ],
    explanation: [
      'Match the terms by position and divide: $9 \\div 3 = 3$, $18 \\div 6 = 3$, $27 \\div 9 = 3$, $36 \\div 12 = 3$.',
      'The same number, $3$, comes out every time, which means the relationship holds for the whole pattern.',
      'Each number in Pattern Y is $3$ times the matching number in Pattern X.',
    ],
    alternativeExplanations: [
      { title: 'Compare the step sizes', steps: ['X grows by $3$ each step; Y grows by $9$ each step.', '$9$ is $3$ times $3$, and both start in step, so Y stays $3$ times X.'] },
    ],
    tags: ['MAP-practice', 'patterns', 'relationships'], estimatedSeconds: 50,
  },
  {
    domain: '5.F', num: 137, unit: 14, order: 7, slug: 'sixth-ordered-pair-from-rules',
    standard: '5.OA.B.3', difficulty: 2,
    prompt: 'Rule 1: start at $0$, add $1$ each time ($0, 1, 2, 3, \\dots$). Rule 2: start at $0$, add $3$ each time ($0, 3, 6, 9, \\dots$). The numbers are paired up in order and plotted as $(x, y)$. What is the 6th ordered pair? Write it like $(x, y)$.',
    answerType: 'short-text', primaryAnswer: '(5, 15)', alternativeAnswers: ['(5,15)', '5,15'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Write both lists out to six numbers, starting the count at $0$.' },
      { level: 'guide', text: 'Rule 1: $0, 1, 2, 3, 4, 5$. Rule 2: $0, 3, 6, 9, 12, 15$.' },
      { level: 'reveal', text: 'The 6th pair is $(5, 15)$.' },
    ],
    explanation: [
      'Rule 1 gives $0, 1, 2, 3, 4, 5$ — the 6th number is $5$.',
      'Rule 2 gives $0, 3, 6, 9, 12, 15$ — the 6th number is $15$.',
      'Pairing the 6th numbers together gives $(5, 15)$.',
      'That fits the pattern: every $y$-value is $3$ times its $x$-value, and $3 \\times 5 = 15$.',
    ],
    alternativeExplanations: [
      { title: 'Use the relationship', steps: ['Each $y$ is $3$ times its $x$ because Rule 2 adds $3$ for every $1$ Rule 1 adds.', 'The 6th $x$ is $5$, so $y = 3 \\times 5 = 15$, giving $(5, 15)$.'] },
    ],
    tags: ['patterns', 'ordered-pairs'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 138, unit: 14, order: 8, slug: 'sticker-chart-week-ten',
    standard: '5.OA.B.3', difficulty: 2,
    prompt: 'A sticker chart has $5$ stickers in week $1$ and gains $7$ more stickers every week: $5, 12, 19, \\dots$ How many stickers are on the chart in week $10$?',
    answerType: 'numeric', primaryAnswer: '68', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'From week $1$ to week $10$ is $9$ weeks of adding, not $10$.' },
      { level: 'guide', text: '$9$ weeks of growth is $9 \\times 7 = 63$ stickers added.' },
      { level: 'reveal', text: '$5 + 63 = 68$ stickers.' },
    ],
    explanation: [
      'Week $1$ already has $5$ stickers, so the adding starts after that.',
      'Getting from week $1$ to week $10$ takes $9$ steps: $9 \\times 7 = 63$ stickers added.',
      '$5 + 63 = 68$ stickers in week $10$.',
      'Spot-check with the list: $5, 12, 19, 26, 33, 40, 47, 54, 61, 68$ — the 10th entry is indeed $68$.',
    ],
    alternativeExplanations: [
      { title: 'Just keep counting', steps: ['Write the weeks out: $5, 12, 19, 26, 33, 40, 47, 54, 61, 68$.', 'Count the entries — the tenth one is $68$.'] },
    ],
    tags: ['MAP-practice', 'patterns', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 139, unit: 14, order: 9, slug: 'block-towers-day-seven-gap',
    standard: '5.OA.B.3', difficulty: 3,
    prompt: 'Tower A has $2$ blocks on day $1$ and grows by $3$ blocks each day. Tower B has $4$ blocks on day $1$ and grows by $6$ blocks each day. On day $7$, how many MORE blocks does Tower B have than Tower A?',
    answerType: 'numeric', primaryAnswer: '20', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Find day $3$ first. Tower A: $2, 5, 8$. Tower B: $4, 10, 16$. The gap is $16 - 8 = 8$. Day $7$ works exactly the same way, just with more steps.' },
      { level: 'nudge', text: 'Day $1$ is the starting day, so getting to day $7$ takes $6$ days of growing.' },
      { level: 'guide', text: 'Tower A: $2 + 6 \\times 3$. Tower B: $4 + 6 \\times 6$.' },
      { level: 'reveal', text: 'Tower A has $2 + 18 = 20$; Tower B has $4 + 36 = 40$; the gap is $40 - 20 = 20$ blocks.' },
    ],
    explanation: [
      'Day $1$ is the start, so reaching day $7$ means the towers grow $6$ times, not $7$.',
      'Tower A on day $7$: $2 + 6 \\times 3 = 2 + 18 = 20$ blocks.',
      'Tower B on day $7$: $4 + 6 \\times 6 = 4 + 36 = 40$ blocks.',
      '$40 - 20 = 20$, so Tower B has $20$ more blocks.',
    ],
    alternativeExplanations: [
      { title: 'Write both patterns out', steps: ['Tower A: $2, 5, 8, 11, 14, 17, 20$.', 'Tower B: $4, 10, 16, 22, 28, 34, 40$.', 'On the seventh entry, $40 - 20 = 20$ blocks apart.'] },
      { title: '⚠️ The trap here', steps: ['The most common wrong answer is $23$: it comes from adding the daily growth $7$ times ($2 + 7 \\times 3 = 23$ and $4 + 7 \\times 6 = 46$, gap $23$).', 'But day $1$ is the starting pile — no blocks have been added yet on day $1$.', 'Escape it by writing the first three days out by hand before you multiply; you will see the number of ADDITIONS is always one less than the day number.'] },
    ],
    tags: ['patterns', 'multi-step', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 140, unit: 14, order: 10, slug: 'plot-pair-with-x-of-eight',
    standard: '5.OA.B.3', difficulty: 3,
    prompt: 'Pattern A (add $2$ from $0$): $0, 2, 4, 6, 8, 10$. Pattern B (add $6$ from $0$): $0, 6, 12, 18, 24, 30$. Matching terms are written as ordered pairs $(A, B)$ and plotted. Which ordered pair has an $x$-coordinate of $8$? Write it like $(x, y)$.',
    answerType: 'short-text', primaryAnswer: '(8, 24)', alternativeAnswers: ['(8,24)', '8,24'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Find the pair with $x = 4$ first. In Pattern A, $4$ is the 3rd number; the 3rd number of Pattern B is $12$, so that pair is $(4, 12)$. Do the same hunt for $x = 8$.' },
      { level: 'nudge', text: 'The $x$-coordinates come from Pattern A, so find where $8$ sits in Pattern A.' },
      { level: 'guide', text: '$8$ is the 5th number in Pattern A. What is the 5th number in Pattern B?' },
      { level: 'reveal', text: 'The 5th number of Pattern B is $24$, so the pair is $(8, 24)$.' },
    ],
    explanation: [
      'The first coordinate comes from Pattern A, so locate $8$ there: $0, 2, 4, 6, 8$ — it is the 5th number.',
      'Take the 5th number of Pattern B: $0, 6, 12, 18, 24$ — that is $24$.',
      'Matching terms pair up, so the ordered pair is $(8, 24)$.',
      'It also fits the relationship: every B term is $3$ times its A term, and $3 \\times 8 = 24$.',
    ],
    alternativeExplanations: [
      { title: 'Use the times-3 rule', steps: ['Pattern B adds $6$ for every $2$ Pattern A adds, so B is always $3$ times A.', '$3 \\times 8 = 24$, giving the pair $(8, 24)$.'] },
      { title: '⚠️ The trap here', steps: ['A frequent wrong answer is $(24, 8)$ — the right two numbers written backwards.', 'The $x$-coordinate always comes first, and the problem said the pairs are written as $(A, B)$, so the Pattern A number leads.', 'Escape it by saying it out loud as you write: "over first, then up" — over $8$, up $24$.'] },
    ],
    tags: ['MAP-practice', 'patterns', 'ordered-pairs', 'multi-step'], estimatedSeconds: 70,
  },

  // ============ UNIT 15 — Volume, measurement conversion & data ============
  {
    domain: '5.F', num: 141, unit: 15, order: 1, slug: 'block-box-volume-6-3-2',
    standard: '5.MD.C.5', difficulty: 1,
    prompt: 'A box of building blocks is $6$ inches long, $3$ inches wide, and $2$ inches tall. What is its volume, in cubic inches?',
    answerType: 'numeric', primaryAnswer: '36', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Volume of a box is length $\\times$ width $\\times$ height.' },
      { level: 'guide', text: '$6 \\times 3 = 18$ cubes cover the bottom layer.' },
      { level: 'reveal', text: 'There are $2$ layers, so $18 \\times 2 = 36$ cubic inches.' },
    ],
    explanation: [
      'Use $V = l \\times w \\times h$ with $l = 6$, $w = 3$, and $h = 2$.',
      'The bottom layer holds $6 \\times 3 = 18$ unit cubes.',
      'The box is $2$ layers tall, so $18 \\times 2 = 36$ cubic inches.',
    ],
    alternativeExplanations: [
      { title: 'Multiply in any order', steps: ['$3 \\times 2 = 6$, then $6 \\times 6 = 36$.', 'Volume comes out the same no matter which two sides you multiply first.'] },
    ],
    tags: ['volume'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 142, unit: 15, order: 2, slug: 'liters-to-milliliters-jug',
    standard: '5.MD.A.1', difficulty: 1,
    prompt: 'A water jug holds $2.5$ liters. How many milliliters is that?',
    answerType: 'numeric', primaryAnswer: '2500', alternativeAnswers: ['2,500'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Milli" means one thousandth — there are $1000$ mL in $1$ L.' },
      { level: 'guide', text: 'Multiply: $2.5 \\times 1000$.' },
      { level: 'reveal', text: '$2.5 \\times 1000 = 2500$ mL.' },
    ],
    explanation: [
      'One liter is $1000$ milliliters, and milliliters are smaller units, so the number gets bigger.',
      '$2.5 \\times 1000 = 2500$.',
      'The jug holds $2500$ milliliters.',
    ],
    alternativeExplanations: [
      { title: 'Split the 2.5', steps: ['$2$ L is $2000$ mL.', '$0.5$ L is half of $1000$, which is $500$ mL.', '$2000 + 500 = 2500$ mL.'] },
    ],
    tags: ['measurement', 'conversion'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 143, unit: 15, order: 3, slug: 'bookshelf-feet-to-inches',
    standard: '5.MD.A.1', difficulty: 1,
    prompt: 'A bookshelf is $7$ feet tall. How many inches tall is it?',
    answerType: 'numeric', primaryAnswer: '84', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Each foot is $12$ inches long.' },
      { level: 'guide', text: 'Multiply: $7 \\times 12$.' },
      { level: 'reveal', text: '$7 \\times 12 = 84$ inches.' },
    ],
    explanation: [
      'There are $12$ inches in every foot, and you are trading feet for smaller units, so multiply.',
      '$7 \\times 12 = 84$.',
      'The bookshelf is $84$ inches tall.',
    ],
    alternativeExplanations: [
      { title: 'Break the 12 apart', steps: ['$7 \\times 10 = 70$.', '$7 \\times 2 = 14$.', '$70 + 14 = 84$ inches.'] },
    ],
    tags: ['measurement', 'conversion'], estimatedSeconds: 30,
  },
  {
    domain: '5.F', num: 144, unit: 15, order: 4, slug: 'water-bottle-line-plot-count',
    standard: '5.MD.B.2', difficulty: 1,
    prompt: 'A class measured how much water was left in each bottle and made a line plot. The line plot shows: $\\frac{1}{4}$ cup appears $3$ times, $\\frac{1}{2}$ cup appears $4$ times, $\\frac{3}{4}$ cup appears $2$ times, and $1$ cup appears $1$ time. How many bottles were measured in all?',
    answerType: 'numeric', primaryAnswer: '10', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Each X on a line plot stands for one bottle.' },
      { level: 'guide', text: 'Add up how many times each amount appears: $3 + 4 + 2 + 1$.' },
      { level: 'reveal', text: '$3 + 4 + 2 + 1 = 10$ bottles.' },
    ],
    explanation: [
      'On a line plot, every mark is one measurement — here, one bottle.',
      'Add the counts, not the fractions: $3 + 4 + 2 + 1 = 10$.',
      'So $10$ bottles were measured.',
    ],
    alternativeExplanations: [
      { title: 'Why not add the fractions?', steps: ['Adding the fractions would tell you the total amount of WATER.', 'Counting the marks tells you the number of BOTTLES, which is what the question asked for.'] },
    ],
    tags: ['line-plot', 'data'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 145, unit: 15, order: 5, slug: 'shoebox-missing-height',
    standard: '5.MD.C.5', difficulty: 2,
    prompt: 'A shoebox has a volume of $120$ cubic inches. Its base is $5$ inches by $6$ inches. How tall is the box, in inches?',
    answerType: 'numeric', primaryAnswer: '4', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the area of the base first — that is how many cubes fit in one layer.' },
      { level: 'guide', text: '$5 \\times 6 = 30$ cubes per layer. How many layers of $30$ make $120$?' },
      { level: 'reveal', text: '$120 \\div 30 = 4$ inches tall.' },
    ],
    explanation: [
      'The bottom layer holds $5 \\times 6 = 30$ cubic inches.',
      'Volume is layers $\\times$ layer size, so $120 \\div 30 = 4$ layers.',
      'The box is $4$ inches tall.',
      'Check it: $5 \\times 6 \\times 4 = 120$ cubic inches ✓',
    ],
    alternativeExplanations: [
      { title: 'Work the formula backwards', steps: ['$V = l \\times w \\times h$ becomes $120 = 5 \\times 6 \\times h$.', '$120 = 30 \\times h$, so $h = 120 \\div 30 = 4$.'] },
    ],
    tags: ['MAP-practice', 'volume', 'multi-step'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 146, unit: 15, order: 6, slug: 'ribbon-line-plot-total-length',
    standard: '5.MD.B.2', difficulty: 2,
    prompt: 'Ms. Ruiz measured her leftover ribbon pieces and made a line plot. The line plot shows: $\\frac{1}{4}$ ft appears $2$ times, $\\frac{1}{2}$ ft appears $3$ times, and $\\frac{3}{4}$ ft appears $1$ time. What is the total length of ribbon, in feet? (Answer as a mixed number.)',
    answerType: 'fraction', primaryAnswer: '2 3/4', alternativeAnswers: ['11/4', '2.75'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Handle one column at a time: how much ribbon do the two $\\frac{1}{4}$-ft pieces make together?' },
      { level: 'guide', text: 'Quarters: $2 \\times \\frac{1}{4} = \\frac{1}{2}$. Halves: $3 \\times \\frac{1}{2} = 1\\frac{1}{2}$. Plus one $\\frac{3}{4}$.' },
      { level: 'reveal', text: '$\\frac{1}{2} + 1\\frac{1}{2} + \\frac{3}{4} = 2\\frac{3}{4}$ feet.' },
    ],
    explanation: [
      'The $\\frac{1}{4}$-ft column: $2 \\times \\frac{1}{4} = \\frac{2}{4} = \\frac{1}{2}$ ft.',
      'The $\\frac{1}{2}$-ft column: $3 \\times \\frac{1}{2} = \\frac{3}{2} = 1\\frac{1}{2}$ ft.',
      'The $\\frac{3}{4}$-ft column: just $\\frac{3}{4}$ ft.',
      'Add them in fourths: $\\frac{2}{4} + \\frac{6}{4} + \\frac{3}{4} = \\frac{11}{4} = 2\\frac{3}{4}$ feet.',
    ],
    alternativeExplanations: [
      { title: 'Count everything in fourths', steps: ['$\\frac{1}{4}$ twice is $\\frac{2}{4}$; $\\frac{1}{2}$ is $\\frac{2}{4}$, so three of them is $\\frac{6}{4}$; and $\\frac{3}{4}$ is $\\frac{3}{4}$.', '$\\frac{2 + 6 + 3}{4} = \\frac{11}{4}$.', '$11 \\div 4 = 2$ remainder $3$, so $2\\frac{3}{4}$ feet.'] },
    ],
    tags: ['MAP-practice', 'line-plot', 'fractions', 'data'], estimatedSeconds: 70,
  },
  {
    domain: '5.F', num: 147, unit: 15, order: 7, slug: 'baker-flour-grams-to-kilograms',
    standard: '5.MD.A.1', difficulty: 2,
    prompt: 'A baker uses $250$ grams of flour for each loaf of bread and bakes $6$ loaves. How many kilograms of flour is that in all?',
    answerType: 'numeric', primaryAnswer: '1.5', alternativeAnswers: ['1 1/2', '3/2'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two steps: find the total grams first, then trade grams for kilograms.' },
      { level: 'guide', text: '$6 \\times 250 = 1500$ grams. There are $1000$ grams in a kilogram.' },
      { level: 'reveal', text: '$1500 \\div 1000 = 1.5$ kilograms.' },
    ],
    explanation: [
      'Step 1 — total grams: $6 \\times 250 = 1500$ grams.',
      'Step 2 — convert: $1$ kilogram is $1000$ grams, and kilograms are the bigger unit, so divide.',
      '$1500 \\div 1000 = 1.5$ kilograms of flour.',
    ],
    alternativeExplanations: [
      { title: 'Think in quarter-kilos', steps: ['$250$ g is $\\frac{1}{4}$ kg.', 'Six quarter-kilos is $\\frac{6}{4} = 1\\frac{1}{2}$ kg.', 'Same answer: $1.5$ kilograms.'] },
    ],
    tags: ['MAP-practice', 'measurement', 'conversion', 'multi-step'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 148, unit: 15, order: 8, slug: 'stacked-block-towers-volume',
    standard: '5.MD.C.5', difficulty: 2,
    prompt: 'A play structure is built from two rectangular block towers stacked together. The bottom part is $6$ cm long, $2$ cm wide, and $3$ cm tall. The top part sits on it and is $2$ cm long, $2$ cm wide, and $3$ cm tall. What is the total volume, in cubic centimeters?',
    answerType: 'numeric', primaryAnswer: '48', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the volume of each box on its own, then put the two volumes together.' },
      { level: 'guide', text: 'Bottom: $6 \\times 2 \\times 3$. Top: $2 \\times 2 \\times 3$.' },
      { level: 'reveal', text: '$36 + 12 = 48$ cubic centimeters.' },
    ],
    explanation: [
      'Bottom part: $6 \\times 2 \\times 3 = 36$ cubic centimeters.',
      'Top part: $2 \\times 2 \\times 3 = 12$ cubic centimeters.',
      'Because the two parts do not overlap, add them: $36 + 12 = 48$ cubic centimeters.',
    ],
    alternativeExplanations: [
      { title: 'Count layers', steps: ['The bottom has $3$ layers of $12$ cubes: $36$.', 'The top has $3$ layers of $4$ cubes: $12$.', '$36 + 12 = 48$ cubes in all.'] },
    ],
    tags: ['MAP-practice', 'volume', 'composite-solids'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 149, unit: 15, order: 9, slug: 'fish-tank-three-quarters-full',
    standard: '5.MD.C.5', difficulty: 3,
    prompt: 'A fish tank is $20$ cm long, $10$ cm wide, and $12$ cm tall. Dani fills it $\\frac{3}{4}$ of the way to the top with water. How many cubic centimeters of water is that?',
    answerType: 'numeric', primaryAnswer: '1800', alternativeAnswers: ['1,800'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a tiny tank $2 \\times 2 \\times 4$: its volume is $16$, and $\\frac{3}{4}$ of $16$ is $16 \\div 4 = 4$, then $3 \\times 4 = 12$. The big tank uses those same two moves.' },
      { level: 'nudge', text: 'Two steps: find the FULL volume of the tank, then take $\\frac{3}{4}$ of it.' },
      { level: 'guide', text: 'Full tank: $20 \\times 10 \\times 12 = 2400$ cubic cm. Now find $\\frac{3}{4}$ of $2400$.' },
      { level: 'reveal', text: '$2400 \\div 4 = 600$, and $3 \\times 600 = 1800$ cubic centimeters.' },
    ],
    explanation: [
      'Step 1 — the whole tank: $20 \\times 10 = 200$ for the bottom layer, and $200 \\times 12 = 2400$ cubic centimeters full.',
      'Step 2 — three fourths of that: $2400 \\div 4 = 600$, so $3 \\times 600 = 1800$.',
      'Dani pours in $1800$ cubic centimeters of water.',
      'That is sensible: $1800$ is less than the full $2400$, because the tank is not filled to the top.',
    ],
    alternativeExplanations: [
      { title: 'Shrink the height instead', steps: ['The water only reaches $\\frac{3}{4}$ of the $12$ cm height: $\\frac{3}{4} \\times 12 = 9$ cm deep.', '$20 \\times 10 \\times 9 = 1800$ cubic centimeters — the same answer.'] },
      { title: '⚠️ The trap here', steps: ['The most common wrong answer is $2400$ — the full volume, with the $\\frac{3}{4}$ never used at all.', 'Another slip is dividing by $3$ instead of by $4$, which gives $800 \\times 3 = 2400$ again.', 'Escape both by asking "should my answer be less than a full tank?" before you write it — if it is not smaller than $2400$, something went wrong.'] },
    ],
    tags: ['MAP-practice', 'volume', 'fractions', 'multi-step'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 150, unit: 15, order: 10, slug: 'juice-line-plot-share-equally',
    standard: '5.MD.B.2', difficulty: 3,
    prompt: 'Six friends each measured the juice in their cup and made a line plot. The line plot shows: $\\frac{1}{8}$ cup appears $2$ times, $\\frac{1}{4}$ cup appears $3$ times, and $\\frac{1}{2}$ cup appears $1$ time. If all the juice were poured together and then shared equally among the $6$ cups, how much juice would be in each cup?',
    answerType: 'fraction', primaryAnswer: '1/4', alternativeAnswers: ['0.25', '2/8'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Say just $2$ cups held $\\frac{1}{4}$ and $\\frac{3}{4}$. Together that is $1$ cup, and $1 \\div 2 = \\frac{1}{2}$ cup each. Total first, then share — same plan below.' },
      { level: 'nudge', text: 'Step 1 is the TOTAL juice; step 2 is splitting that total among $6$ cups.' },
      { level: 'guide', text: 'In eighths: $2 \\times \\frac{1}{8} = \\frac{2}{8}$, $3 \\times \\frac{1}{4} = \\frac{6}{8}$, and $\\frac{1}{2} = \\frac{4}{8}$.' },
      { level: 'reveal', text: '$\\frac{2 + 6 + 4}{8} = \\frac{12}{8} = 1\\frac{1}{2}$ cups total, and $1\\frac{1}{2} \\div 6 = \\frac{1}{4}$ cup each.' },
    ],
    explanation: [
      'Rewrite everything in eighths: the two $\\frac{1}{8}$ cups give $\\frac{2}{8}$, the three $\\frac{1}{4}$ cups give $\\frac{6}{8}$, and the single $\\frac{1}{2}$ cup gives $\\frac{4}{8}$.',
      'Total juice: $\\frac{2}{8} + \\frac{6}{8} + \\frac{4}{8} = \\frac{12}{8} = 1\\frac{1}{2}$ cups.',
      'Share it among the $6$ cups: $1\\frac{1}{2} \\div 6 = \\frac{3}{2} \\div 6 = \\frac{3}{12} = \\frac{1}{4}$.',
      'Each cup would hold $\\frac{1}{4}$ cup of juice.',
    ],
    alternativeExplanations: [
      { title: 'Use twelfths of a cup… or just check it', steps: ['If every cup ends with $\\frac{1}{4}$, then $6 \\times \\frac{1}{4} = \\frac{6}{4} = 1\\frac{1}{2}$ cups.', 'That matches the total we found, so $\\frac{1}{4}$ cup each is right.'] },
      { title: '⚠️ The trap here', steps: ['A very common wrong answer is $\\frac{1}{2}$ cup, from dividing the total by $3$ — the number of different labels on the line plot — instead of by $6$.', 'The line plot has $3$ labels but $2 + 3 + 1 = 6$ marks, and it is the MARKS that count the cups.', 'Escape it by counting the X marks first and writing that number down before you divide.'] },
    ],
    tags: ['MAP-practice', 'line-plot', 'fractions', 'multi-step'], estimatedSeconds: 75,
  },

  // ============ UNIT 16 — 2-D figures & the coordinate plane ============
  {
    domain: '5.F', num: 151, unit: 16, order: 1, slug: 'classify-right-isosceles-triangle',
    standard: '5.G.B.4', difficulty: 1,
    prompt: 'A triangle has angles measuring $90^\\circ$, $45^\\circ$, and $45^\\circ$. Which name fits it BEST?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'right scalene triangle', correct: false },
      { id: 'B', label: 'right isosceles triangle', correct: true },
      { id: 'C', label: 'equilateral triangle', correct: false },
      { id: 'D', label: 'obtuse triangle', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'One angle is exactly $90^\\circ$ — what do we call a triangle with a square corner?' },
      { level: 'guide', text: 'Two of the angles are equal ($45^\\circ$ and $45^\\circ$), which means two sides are equal too.' },
      { level: 'reveal', text: 'Right corner plus two equal angles makes it a right isosceles triangle.' },
    ],
    explanation: [
      'A $90^\\circ$ angle is a right angle, so this is a right triangle.',
      'Two angles are the same size ($45^\\circ$ and $45^\\circ$), and equal angles sit across from equal sides, so two sides match — that is isosceles.',
      'Scalene would mean no equal sides, and equilateral would need three $60^\\circ$ angles, so neither fits.',
      'The best name is a right isosceles triangle.',
    ],
    alternativeExplanations: [
      { title: 'Check the angle sum', steps: ['$90 + 45 + 45 = 180^\\circ$, so these angles really can form a triangle.', 'Nothing is over $90^\\circ$, so it is not obtuse.'] },
    ],
    tags: ['geometry', 'triangles'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 152, unit: 16, order: 2, slug: 'library-point-on-x-axis',
    standard: '5.G.A.1', difficulty: 1,
    prompt: 'On a map grid, you start at the origin $(0,0)$, walk $6$ units right, and do not go up at all. That is where the library is. What are the library\'s coordinates? Write it like $(x, y)$.',
    answerType: 'short-text', primaryAnswer: '(6, 0)', alternativeAnswers: ['(6,0)', '6,0'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The first number is the sideways move; the second is the up move.' },
      { level: 'guide', text: 'You moved $6$ right, so $x = 6$. You never moved up, so $y = 0$.' },
      { level: 'reveal', text: 'The library is at $(6, 0)$.' },
    ],
    explanation: [
      'Coordinates are written $(x, y)$: over first, then up.',
      'Walking $6$ units right makes $x = 6$.',
      'Not going up at all makes $y = 0$.',
      'So the library sits at $(6, 0)$ — right on the $x$-axis.',
    ],
    alternativeExplanations: [
      { title: 'Zero is a real coordinate', steps: ['A $y$-coordinate of $0$ does not mean the point is missing.', 'It means the point is sitting right on the horizontal axis.'] },
    ],
    tags: ['coordinate-plane'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 153, unit: 16, order: 3, slug: 'every-square-is-a-rectangle',
    standard: '5.G.B.3', difficulty: 1,
    prompt: 'Which sentence is true about every square?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Every square is also a rectangle.', correct: true },
      { id: 'B', label: 'Every rectangle is also a square.', correct: false },
      { id: 'C', label: 'A square is not a quadrilateral.', correct: false },
      { id: 'D', label: 'Squares have no right angles.', correct: false },
    ],
    primaryAnswer: 'A', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A rectangle is a four-sided shape with four right angles. Does a square have those?' },
      { level: 'guide', text: 'A square has four right angles AND four equal sides — it meets the rectangle rules and then some.' },
      { level: 'reveal', text: 'Every square is a rectangle, but a long skinny rectangle is not a square.' },
    ],
    explanation: [
      'A rectangle is any quadrilateral with four right angles.',
      'A square has four right angles, so it passes that test — every square is a rectangle.',
      'It does not work backwards: a $3$ by $8$ rectangle has four right angles but its sides are not all equal, so it is not a square.',
      'Choices C and D are simply false: squares are four-sided and full of right angles.',
    ],
    alternativeExplanations: [
      { title: 'Think of nested boxes', steps: ['Quadrilaterals is the biggest box; rectangles sit inside it; squares sit inside rectangles.', 'Being in a smaller box means you are also in every bigger one.'] },
    ],
    tags: ['geometry', 'quadrilaterals', 'hierarchy'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 154, unit: 16, order: 4, slug: 'read-walking-graph-point',
    standard: '5.G.A.2', difficulty: 1,
    prompt: 'On a graph, the $x$-axis shows hours walked and the $y$-axis shows miles walked. One plotted point is $(3, 12)$. How many miles had been walked after $3$ hours?',
    answerType: 'numeric', primaryAnswer: '12', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Which number in the pair matches the $y$-axis?' },
      { level: 'guide', text: 'In $(3, 12)$, the $3$ is hours and the $12$ is miles.' },
      { level: 'reveal', text: '$12$ miles.' },
    ],
    explanation: [
      'An ordered pair is always $(x, y)$, so in $(3, 12)$ the $x$-value is $3$ and the $y$-value is $12$.',
      'The $x$-axis is labeled hours, so $3$ means $3$ hours.',
      'The $y$-axis is labeled miles, so $12$ means $12$ miles had been walked.',
    ],
    alternativeExplanations: [
      { title: 'Read it like a sentence', steps: ['The point says: "at $3$ hours, the distance was $12$ miles."', 'The axis labels tell you which number means what.'] },
    ],
    tags: ['coordinate-plane', 'graph-reading'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 155, unit: 16, order: 5, slug: 'rhombus-parallelogram-true-statement',
    standard: '5.G.B.3', difficulty: 2,
    prompt: 'Which statement is TRUE?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'All parallelograms are rhombuses.', correct: false },
      { id: 'B', label: 'All rhombuses are parallelograms.', correct: true },
      { id: 'C', label: 'All trapezoids are rectangles.', correct: false },
      { id: 'D', label: 'All quadrilaterals are parallelograms.', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A parallelogram just needs both pairs of opposite sides parallel. A rhombus needs that PLUS four equal sides.' },
      { level: 'guide', text: 'The shape with the extra rule always belongs to the bigger group, not the other way around.' },
      { level: 'reveal', text: 'Rhombuses have the extra rule, so all rhombuses are parallelograms.' },
    ],
    explanation: [
      'A rhombus has both pairs of opposite sides parallel AND four equal sides, so it satisfies every parallelogram rule — statement B is true.',
      'Statement A fails because a long parallelogram can have unequal sides, so it is not a rhombus.',
      'Statement C fails because a trapezoid needs only one pair of parallel sides and need not have right angles.',
      'Statement D fails because a kite is a quadrilateral with no parallel sides at all.',
    ],
    alternativeExplanations: [
      { title: 'One counterexample is enough', steps: ['To knock out "all parallelograms are rhombuses," just picture a slanted $2$-by-$5$ parallelogram.', 'Its sides are not equal, so it is not a rhombus — statement A is dead.'] },
    ],
    tags: ['MAP-practice', 'geometry', 'quadrilaterals', 'hierarchy'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 156, unit: 16, order: 6, slug: 'tent-stakes-vertical-distance',
    standard: '5.G.A.2', difficulty: 2,
    prompt: 'Two tent stakes on a park grid are at $(2, 3)$ and $(2, 9)$. Each unit is $1$ meter. How many meters apart are the stakes?',
    answerType: 'numeric', primaryAnswer: '6', alternativeAnswers: ['6 m'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Both points have the same $x$-value, so they sit straight up and down from each other.' },
      { level: 'guide', text: 'Only the $y$-values differ: $3$ and $9$. Subtract them.' },
      { level: 'reveal', text: '$9 - 3 = 6$ meters apart.' },
    ],
    explanation: [
      'Both stakes have $x = 2$, so they are on the same vertical line — no sideways distance at all.',
      'The distance is the gap between the $y$-values: $9 - 3 = 6$.',
      'Each unit is a meter, so the stakes are $6$ meters apart.',
    ],
    alternativeExplanations: [
      { title: 'Count the hops', steps: ['Start at $(2,3)$ and hop up one unit at a time: $4, 5, 6, 7, 8, 9$.', 'That is $6$ hops, which is $6$ meters.'] },
    ],
    tags: ['MAP-practice', 'coordinate-plane', 'distance'], estimatedSeconds: 50,
  },
  {
    domain: '5.F', num: 157, unit: 16, order: 7, slug: 'one-pair-parallel-sides-shape',
    standard: '5.G.B.4', difficulty: 2,
    prompt: 'A quadrilateral has exactly ONE pair of parallel sides. What is the shape called?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'trapezoid', correct: true },
      { id: 'B', label: 'parallelogram', correct: false },
      { id: 'C', label: 'rhombus', correct: false },
      { id: 'D', label: 'rectangle', correct: false },
    ],
    primaryAnswer: 'A', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The word "exactly one" is doing a lot of work here — some shapes have two pairs.' },
      { level: 'guide', text: 'Parallelograms, rhombuses, and rectangles all have TWO pairs of parallel sides.' },
      { level: 'reveal', text: 'With exactly one pair, the shape is a trapezoid.' },
    ],
    explanation: [
      'Parallelograms, rhombuses, and rectangles all require two pairs of parallel sides, so none of them can have exactly one.',
      'A trapezoid is the quadrilateral defined by having a pair of parallel sides while the other two sides are not parallel.',
      'So the shape is a trapezoid.',
    ],
    alternativeExplanations: [
      { title: 'Picture a lampshade', steps: ['A lampshade outline has a short flat top and a longer flat bottom that are parallel.', 'Its slanted sides lean toward each other, so they are not parallel — a trapezoid.'] },
    ],
    tags: ['geometry', 'quadrilaterals'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 158, unit: 16, order: 8, slug: 'fourth-corner-of-rectangle',
    standard: '5.G.A.2', difficulty: 2,
    prompt: 'Three corners of a rectangle are at $(1, 2)$, $(7, 2)$, and $(7, 6)$. Where is the fourth corner? Write it like $(x, y)$.',
    answerType: 'short-text', primaryAnswer: '(1, 6)', alternativeAnswers: ['(1,6)', '1,6'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'In a rectangle, corners come in matching pairs: two share an $x$-value, two share a $y$-value.' },
      { level: 'guide', text: '$(1,2)$ and $(7,2)$ form the bottom edge. The missing corner sits directly above $(1,2)$.' },
      { level: 'reveal', text: 'It has the same $x$ as $(1,2)$ and the same $y$ as $(7,6)$: $(1, 6)$.' },
    ],
    explanation: [
      'The points $(1,2)$ and $(7,2)$ share $y = 2$, so they are the two bottom corners.',
      '$(7,6)$ is directly above $(7,2)$, so it is the top-right corner and the rectangle is $4$ units tall.',
      'The missing top-left corner must line up above $(1,2)$ and across from $(7,6)$: $x = 1$ and $y = 6$.',
      'The fourth corner is $(1, 6)$.',
    ],
    alternativeExplanations: [
      { title: 'Match the side lengths', steps: ['The bottom edge runs from $x = 1$ to $x = 7$, a width of $6$.', 'The top edge must have the same width and sit at $y = 6$, so it runs from $(1,6)$ to $(7,6)$.'] },
    ],
    tags: ['MAP-practice', 'coordinate-plane', 'geometry'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 159, unit: 16, order: 9, slug: 'garden-fence-from-coordinates',
    standard: '5.G.A.2', difficulty: 3,
    prompt: 'A rectangular garden has corners at $(2, 1)$, $(8, 1)$, $(8, 5)$, and $(2, 5)$ on a grid where each unit is $1$ meter. How many meters of fence are needed to go all the way around it?',
    answerType: 'numeric', primaryAnswer: '20', alternativeAnswers: ['20 m'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a tiny garden at $(0,0)$, $(3,0)$, $(3,2)$, $(0,2)$. Width $= 3 - 0 = 3$, height $= 2 - 0 = 2$, so the fence is $3 + 2 + 3 + 2 = 10$. Same steps, bigger numbers below.' },
      { level: 'nudge', text: 'Find the width and the height first by subtracting matching coordinates.' },
      { level: 'guide', text: 'Width: $8 - 2 = 6$ meters. Height: $5 - 1 = 4$ meters.' },
      { level: 'reveal', text: 'Fence $= 6 + 4 + 6 + 4 = 20$ meters.' },
    ],
    explanation: [
      'The bottom edge runs from $(2,1)$ to $(8,1)$, so the width is $8 - 2 = 6$ meters.',
      'The right edge runs from $(8,1)$ to $(8,5)$, so the height is $5 - 1 = 4$ meters.',
      'A rectangle has two widths and two heights, so the fence is $6 + 6 + 4 + 4 = 20$ meters.',
      'Dani would need $20$ meters of fencing.',
    ],
    alternativeExplanations: [
      { title: 'Use the perimeter formula', steps: ['$P = 2 \\times (\\text{width} + \\text{height})$.', '$2 \\times (6 + 4) = 2 \\times 10 = 20$ meters.'] },
      { title: '⚠️ The trap here', steps: ['A common wrong answer is $24$: it comes from counting grid LINES instead of gaps — thinking the side from $x = 2$ to $x = 8$ is $7$ units because you count $2,3,4,5,6,7,8$.', 'Fence length measures the spaces between the lines, not the lines themselves, so you subtract: $8 - 2 = 6$.', 'Escape it by drawing the two end points and counting the hops from one to the other, the way you would count steps on a sidewalk.'] },
    ],
    tags: ['MAP-practice', 'coordinate-plane', 'perimeter', 'multi-step'], estimatedSeconds: 70,
  },
  {
    domain: '5.F', num: 160, unit: 16, order: 10, slug: 'always-true-quadrilateral-statement',
    standard: '5.G.B.3', difficulty: 3,
    prompt: 'Which statement is ALWAYS true?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Every rectangle is a square.', correct: false },
      { id: 'B', label: 'Every square is a rhombus.', correct: true },
      { id: 'C', label: 'Every parallelogram is a rectangle.', correct: false },
      { id: 'D', label: 'Every trapezoid is a parallelogram.', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up with a smaller version: is every square a rectangle? A rectangle needs four right angles; a square has them, so yes. Use that same "does it meet the rules?" test on each choice below.' },
      { level: 'nudge', text: 'For each statement, try to invent ONE shape that breaks it. If you can, the statement is not always true.' },
      { level: 'guide', text: 'A rhombus is a quadrilateral with four equal sides. Does a square have four equal sides?' },
      { level: 'reveal', text: 'Yes — a square has four equal sides, so every square is a rhombus. Statement B is always true.' },
    ],
    explanation: [
      'A rhombus is defined as a quadrilateral with four equal sides. A square has four equal sides, so every square qualifies — B is always true.',
      'Statement A breaks with a $3$-by-$8$ rectangle: four right angles, but the sides are not all equal, so it is not a square.',
      'Statement C breaks with a slanted parallelogram, which has no right angles at all.',
      'Statement D breaks because a trapezoid has only one pair of parallel sides, while a parallelogram needs two.',
    ],
    alternativeExplanations: [
      { title: 'Squares are the overachievers', steps: ['A square has four right angles (rectangle rule) and four equal sides (rhombus rule).', 'Meeting extra rules means a square belongs to several families at once — rectangle, rhombus, parallelogram, quadrilateral.'] },
      { title: '⚠️ The trap here', steps: ['The most-chosen wrong answer is A, "every rectangle is a square," because squares and rectangles feel like the same thing.', 'The direction matters: the shape with MORE rules (square) lives inside the group with fewer rules (rectangle), never the other way around.', 'Escape it by testing with a real object — a door is a rectangle but definitely not a square, which kills statement A instantly.'] },
    ],
    tags: ['MAP-practice', 'geometry', 'quadrilaterals', 'hierarchy'], estimatedSeconds: 70,
  },
];
