import type { SeedProblem } from './types';

// 5.F — Gr-5 Foundations, Units 7-11 (nums 61-110). Continues 5.F.ts (units 1-6,
// nums 1-60): multi-digit multiplication & division, powers of ten, adding &
// subtracting decimals, multiplying & dividing decimals, fractions as division.
// Every answer is recomputed inside the explanation steps; difficulty-3 problems
// carry a 4-step hint series that opens with a worked simpler case, plus a
// "⚠️ The trap here" alternative explanation naming the likely wrong answer.

export const problems5Fu07: SeedProblem[] = [
  // ============ UNIT 7 — Multi-digit multiplication & division ============
  {
    domain: '5.F', num: 61, unit: 7, order: 1, slug: 'mult-142x20',
    standard: '5.NBT.B.5', difficulty: 1,
    prompt: 'Multiply: $142 \\times 20$',
    answerType: 'numeric', primaryAnswer: '2840', alternativeAnswers: ['2,840'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A $20$ is just $2 \\times 10$, so multiply by $2$ first and then tack on a zero.' },
      { level: 'guide', text: '$142 \\times 2 = 284$. Now multiply that by $10$.' },
      { level: 'reveal', text: '$284 \\times 10 = 2840$.' },
    ],
    explanation: [
      'Break the $20$ apart: $20 = 2 \\times 10$.',
      'First multiply by $2$: $142 \\times 2 = 284$.',
      'Then multiply by $10$, which shifts every digit one place left: $284 \\times 10 = 2840$.',
      'So $142 \\times 20 = 2840$.',
    ],
    alternativeExplanations: [
      { title: 'Place-value split', steps: ['$142 = 100 + 40 + 2$.', '$100 \\times 20 = 2000$, $40 \\times 20 = 800$, $2 \\times 20 = 40$.', '$2000 + 800 + 40 = 2840$ ✓'] },
    ],
    tags: ['multiplication', 'multi-digit'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 62, unit: 7, order: 2, slug: 'mult-203x12',
    standard: '5.NBT.B.5', difficulty: 1,
    prompt: 'Multiply: $203 \\times 12$',
    answerType: 'numeric', primaryAnswer: '2436', alternativeAnswers: ['2,436'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Split the $12$ into $10 + 2$ — both are easy to multiply by.' },
      { level: 'guide', text: '$203 \\times 10 = 2030$ and $203 \\times 2 = 406$. Add the two pieces.' },
      { level: 'reveal', text: '$2030 + 406 = 2436$.' },
    ],
    explanation: [
      'Split the second factor: $12 = 10 + 2$.',
      '$203 \\times 10 = 2030$.',
      '$203 \\times 2 = 406$.',
      'Add the partial products: $2030 + 406 = 2436$.',
    ],
    alternativeExplanations: [
      { title: 'Watch the zero', steps: ['The $0$ in the tens place of $203$ is not a mistake — it means zero tens.', 'In the standard algorithm you still write a $0$ in that column so the other digits stay lined up.'] },
    ],
    tags: ['multiplication', 'multi-digit'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 63, unit: 7, order: 3, slug: 'divide-960-40',
    standard: '5.NBT.B.6', difficulty: 1,
    prompt: 'Divide: $960 \\div 40$',
    answerType: 'numeric', primaryAnswer: '24', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Both numbers end in a zero — you can cross one zero off each.' },
      { level: 'guide', text: '$960 \\div 40$ is the same as $96 \\div 4$.' },
      { level: 'reveal', text: '$96 \\div 4 = 24$.' },
    ],
    explanation: [
      'Dividing both numbers by $10$ does not change the answer, so $960 \\div 40 = 96 \\div 4$.',
      '$96 \\div 4 = 24$ because $4 \\times 24 = 96$.',
      'Check the original: $40 \\times 24 = 960$ ✓, so the quotient is $24$.',
    ],
    alternativeExplanations: [
      { title: 'Count up in groups', steps: ['$40 \\times 20 = 800$, leaving $960 - 800 = 160$.', '$40 \\times 4 = 160$, leaving $0$.', 'So the answer is $20 + 4 = 24$.'] },
    ],
    tags: ['division', 'multi-digit'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 64, unit: 7, order: 4, slug: 'estimate-quotient-5812-29-mc',
    standard: '5.NBT.B.6', difficulty: 1,
    prompt: 'Without dividing exactly, which is the **best estimate** for $5{,}812 \\div 29$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '20', correct: false },
      { id: 'B', label: '200', correct: true },
      { id: 'C', label: '2,000', correct: false },
      { id: 'D', label: '20,000', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Round $29$ to a friendlier number first. What is it closest to?' },
      { level: 'guide', text: '$29$ is about $30$, and $5{,}812$ is about $6{,}000$. So think $6{,}000 \\div 30$.' },
      { level: 'reveal', text: '$6{,}000 \\div 30 = 200$, so choose B.' },
    ],
    explanation: [
      'Round both numbers to something easy: $5{,}812 \\approx 6{,}000$ and $29 \\approx 30$.',
      '$6{,}000 \\div 30 = 200$, because $30 \\times 200 = 6{,}000$.',
      'So the quotient is close to $200$ — answer B.',
    ],
    alternativeExplanations: [
      { title: 'Size-check the other options', steps: ['$29 \\times 20 = 580$ — way too small.', '$29 \\times 2{,}000 = 58{,}000$ — way too big.', 'Only $200$ lands near $5{,}812$.'] },
    ],
    tags: ['MAP-practice', 'estimation', 'division'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 65, unit: 7, order: 5, slug: 'mult-367x24',
    standard: '5.NBT.B.5', difficulty: 2,
    prompt: 'Multiply: $367 \\times 24$',
    answerType: 'numeric', primaryAnswer: '8808', alternativeAnswers: ['8,808'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The standard algorithm does this in two rows: one for the ones digit, one for the tens digit.' },
      { level: 'guide', text: 'Row 1: $367 \\times 4$. Row 2: $367 \\times 20$. Then add the rows.' },
      { level: 'reveal', text: '$367 \\times 4 = 1468$ and $367 \\times 20 = 7340$, so $1468 + 7340 = 8808$.' },
    ],
    explanation: [
      'Split $24$ into $20 + 4$ — that is exactly what the two rows of the standard algorithm are doing.',
      '$367 \\times 4 = 1468$.',
      '$367 \\times 20 = 7340$.',
      'Add the partial products: $1468 + 7340 = 8808$.',
    ],
    alternativeExplanations: [
      { title: 'Estimate to check', steps: ['$367$ is close to $370$ and $24$ is close to $25$.', '$370 \\times 25 = 9{,}250$.', '$8{,}808$ sits just under that, so the answer is reasonable ✓'] },
    ],
    tags: ['MAP-practice', 'multiplication', 'standard-algorithm'], estimatedSeconds: 70,
  },
  {
    domain: '5.F', num: 66, unit: 7, order: 6, slug: 'divide-4368-24',
    standard: '5.NBT.B.6', difficulty: 2,
    prompt: 'Divide: $4{,}368 \\div 24$',
    answerType: 'numeric', primaryAnswer: '182', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Build the answer in chunks. How many hundreds of $24$s fit inside $4{,}368$?' },
      { level: 'guide', text: '$24 \\times 100 = 2400$, so at least $100$ fit. Try $24 \\times 180$ next.' },
      { level: 'reveal', text: '$24 \\times 180 = 4320$, leaving $48$, and $48 \\div 24 = 2$. So $180 + 2 = 182$.' },
    ],
    explanation: [
      'Take a big bite first: $24 \\times 180 = 4{,}320$.',
      'Subtract: $4{,}368 - 4{,}320 = 48$.',
      '$48 \\div 24 = 2$, with nothing left over.',
      'So $4{,}368 \\div 24 = 180 + 2 = 182$.',
    ],
    alternativeExplanations: [
      { title: 'Check by multiplying back', steps: ['$182 \\times 24 = 182 \\times 20 + 182 \\times 4$.', '$3{,}640 + 728 = 4{,}368$ ✓'] },
    ],
    tags: ['division', 'standard-algorithm'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 67, unit: 7, order: 7, slug: 'field-trip-vans-remainder',
    standard: '5.NBT.B.6', difficulty: 2,
    prompt: 'A field trip has $138$ students. Each van holds $12$ students. How many vans are needed so that **everyone** gets a ride?',
    answerType: 'numeric', primaryAnswer: '12', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Start with $138 \\div 12$ — but read the question again before you write the final answer.' },
      { level: 'guide', text: '$12 \\times 11 = 132$, so $11$ full vans carry $132$ students. That leaves $6$ students standing on the sidewalk.' },
      { level: 'reveal', text: 'Those last $6$ students still need a ride, so add one more van: $11 + 1 = 12$ vans.' },
    ],
    explanation: [
      'Divide: $138 \\div 12$. Since $12 \\times 11 = 132$, the quotient is $11$ with a remainder of $138 - 132 = 6$.',
      'Eleven vans are completely full, and $6$ students are still waiting.',
      'You cannot leave those $6$ behind, so one more van rolls out: $11 + 1 = 12$ vans.',
      'When the remainder means "leftover people who still need a spot," you round the quotient **up**.',
    ],
    alternativeExplanations: [
      { title: 'Check it', steps: ['$12$ vans $\\times$ $12$ seats $= 144$ seats.', '$144$ seats is enough for $138$ students, with $6$ seats empty ✓'] },
    ],
    tags: ['MAP-practice', 'division', 'remainders', 'word-problem'], estimatedSeconds: 65,
  },
  {
    domain: '5.F', num: 68, unit: 7, order: 8, slug: 'mult-458x36',
    standard: '5.NBT.B.5', difficulty: 2,
    prompt: 'Multiply: $458 \\times 36$',
    answerType: 'numeric', primaryAnswer: '16488', alternativeAnswers: ['16,488'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two partial products again: one for the $6$ ones, one for the $3$ tens.' },
      { level: 'guide', text: '$458 \\times 6 = 2748$. Now find $458 \\times 30$.' },
      { level: 'reveal', text: '$458 \\times 30 = 13{,}740$, and $13{,}740 + 2{,}748 = 16{,}488$.' },
    ],
    explanation: [
      'Split $36$ into $30 + 6$.',
      '$458 \\times 6 = 2{,}748$.',
      '$458 \\times 30 = 13{,}740$.',
      'Add them: $13{,}740 + 2{,}748 = 16{,}488$.',
    ],
    alternativeExplanations: [
      { title: 'Estimate to check', steps: ['$458 \\approx 450$ and $36 \\approx 40$.', '$450 \\times 40 = 18{,}000$.', '$16{,}488$ is close to that, so the answer is in the right neighborhood ✓'] },
    ],
    tags: ['multiplication', 'standard-algorithm'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 69, unit: 7, order: 9, slug: 'block-wall-layers',
    standard: '5.NBT.B.5', difficulty: 3,
    prompt: 'You are building a block wall in a game. Each layer takes $128$ blocks, and the wall is $24$ layers tall. You have already placed $500$ blocks. How many more blocks do you still need?',
    answerType: 'numeric', primaryAnswer: '2572', alternativeAnswers: ['2,572'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Suppose each layer took $10$ blocks and the wall were $3$ layers tall: that is $10 \\times 3 = 30$ blocks total. If you had already placed $12$, you would still need $30 - 12 = 18$. Multiply first, then subtract — same two steps here.' },
      { level: 'nudge', text: 'Two steps: find the blocks the whole wall needs, then take away the ones already placed.' },
      { level: 'guide', text: 'Total blocks $= 128 \\times 24$. Try $128 \\times 20$ plus $128 \\times 4$.' },
      { level: 'reveal', text: '$2560 + 512 = 3072$ blocks total, and $3072 - 500 = 2572$ blocks still needed.' },
    ],
    explanation: [
      'Step 1 — the whole wall: $128 \\times 24$. Split it as $128 \\times 20 = 2{,}560$ and $128 \\times 4 = 512$.',
      'Add the partial products: $2{,}560 + 512 = 3{,}072$ blocks for the finished wall.',
      'Step 2 — subtract what is already up: $3{,}072 - 500 = 2{,}572$.',
      'So you still need $2{,}572$ blocks.',
    ],
    alternativeExplanations: [
      { title: 'Estimate first', steps: ['$128 \\times 24$ is roughly $130 \\times 25 = 3{,}250$.', '$3{,}250 - 500 = 2{,}750$, so an answer near $2{,}572$ makes sense ✓'] },
      { title: '⚠️ The trap here', steps: ['The classic slip is answering $3{,}072$ — the total for the wall — and forgetting the $500$ blocks already placed.', 'Another slip is subtracting first: $128 - 500$ does not even make sense here.', 'Reread the last sentence: it asks how many **more** you need, so the subtraction has to come after the multiplication: $3{,}072 - 500 = 2{,}572$.'] },
    ],
    tags: ['MAP-practice', 'multi-step', 'word-problem', 'multiplication'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 70, unit: 7, order: 10, slug: 'cookie-boxes-leftover',
    standard: '5.NBT.B.6', difficulty: 3,
    prompt: 'A bake sale has $1{,}250$ cookies. They go into boxes that hold $18$ cookies each. After filling as many **full boxes** as possible, how many cookies are left over?',
    answerType: 'numeric', primaryAnswer: '8', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try $17$ cookies in boxes of $5$: $5 \\times 3 = 15$, so you fill $3$ boxes and $17 - 15 = 2$ cookies are left over. The leftover is the **remainder**, not the quotient. Same move with the big numbers.' },
      { level: 'nudge', text: 'Divide $1{,}250$ by $18$ — the number you want is what is left at the end, not the number of boxes.' },
      { level: 'guide', text: '$18 \\times 60 = 1080$, so try going higher: what is $18 \\times 69$?' },
      { level: 'reveal', text: '$18 \\times 69 = 1242$, and $1250 - 1242 = 8$ cookies left over.' },
    ],
    explanation: [
      'Take a big chunk: $18 \\times 60 = 1{,}080$, leaving $1{,}250 - 1{,}080 = 170$.',
      '$18 \\times 9 = 162$, which fits inside $170$ and leaves $170 - 162 = 8$.',
      'So $1{,}250 \\div 18 = 69$ boxes with a remainder of $8$.',
      'The question asks for the leftovers, so the answer is $8$ cookies.',
    ],
    alternativeExplanations: [
      { title: 'Check by multiplying back', steps: ['$69 \\times 18 = 69 \\times 20 - 69 \\times 2 = 1{,}380 - 138 = 1{,}242$.', '$1{,}242 + 8 = 1{,}250$ ✓ — quotient times divisor plus remainder gives the original number.'] },
      { title: '⚠️ The trap here', steps: ['Most students answer $69$ — that is the number of boxes, not the cookies left over.', 'The remainder is what could not fill another box.', 'Read the last line of the story before writing your answer: "how many cookies are left over" means the remainder, $8$.'] },
    ],
    tags: ['MAP-practice', 'division', 'remainders', 'word-problem'], estimatedSeconds: 75,
  },

  // ============ UNIT 8 — Powers of ten and exponents ============
  {
    domain: '5.F', num: 71, unit: 8, order: 1, slug: 'ten-to-the-fifth',
    standard: '5.NBT.A.2', difficulty: 1,
    prompt: 'What is $10^5$ written as a regular number?',
    answerType: 'numeric', primaryAnswer: '100000', alternativeAnswers: ['100,000'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The little raised number tells you how many $10$s get multiplied together.' },
      { level: 'guide', text: '$10^5 = 10 \\times 10 \\times 10 \\times 10 \\times 10$ — that is five zeros after the $1$.' },
      { level: 'reveal', text: '$10^5 = 100{,}000$.' },
    ],
    explanation: [
      'The exponent $5$ means five factors of $10$: $10 \\times 10 \\times 10 \\times 10 \\times 10$.',
      'Each $\\times 10$ tacks on one zero, starting from $1$.',
      'Five zeros gives $100{,}000$, which we read as one hundred thousand.',
    ],
    alternativeExplanations: [
      { title: 'Build it up', steps: ['$10^1 = 10$, $10^2 = 100$, $10^3 = 1{,}000$.', 'Each step multiplies by $10$ again: $10^4 = 10{,}000$ and $10^5 = 100{,}000$ ✓'] },
    ],
    tags: ['powers-of-ten', 'exponents'], estimatedSeconds: 30,
  },
  {
    domain: '5.F', num: 72, unit: 8, order: 2, slug: 'times-one-hundred-36',
    standard: '5.NBT.A.2', difficulty: 1,
    prompt: 'What is $3.6 \\times 100$?',
    answerType: 'numeric', primaryAnswer: '360', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiplying by $100$ makes a number $100$ times bigger, so the decimal point moves to the right.' },
      { level: 'guide', text: '$100$ has two zeros, so slide the point two places right: $3.6 \\to 36. \\to 360.$' },
      { level: 'reveal', text: '$3.6 \\times 100 = 360$.' },
    ],
    explanation: [
      '$100 = 10^2$, so multiplying by it shifts the decimal point two places to the right.',
      'Starting at $3.6$, one shift gives $36$ and a second shift gives $360$ — you fill the empty spot with a zero.',
      'So $3.6 \\times 100 = 360$.',
    ],
    alternativeExplanations: [
      { title: 'Sanity check', steps: ['$3 \\times 100 = 300$ and $4 \\times 100 = 400$.', '$3.6$ is between $3$ and $4$, so its answer should be between $300$ and $400$ — and $360$ is ✓'] },
    ],
    tags: ['powers-of-ten', 'decimals'], estimatedSeconds: 30,
  },
  {
    domain: '5.F', num: 73, unit: 8, order: 3, slug: 'divide-4500-by-1000',
    standard: '5.NBT.A.2', difficulty: 1,
    prompt: 'What is $4{,}500 \\div 1{,}000$?',
    answerType: 'numeric', primaryAnswer: '4.5', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Dividing makes the number smaller, so the decimal point slides to the **left**.' },
      { level: 'guide', text: '$1{,}000$ has three zeros, so move the point three places left from $4500.$' },
      { level: 'reveal', text: '$4500. \\to 450. \\to 45. \\to 4.5$, so the answer is $4.5$.' },
    ],
    explanation: [
      '$1{,}000 = 10^3$, so dividing by it shifts the decimal point three places to the left.',
      'Start at $4500.$ — one shift gives $450$, two gives $45$, three gives $4.5$.',
      'So $4{,}500 \\div 1{,}000 = 4.5$.',
    ],
    alternativeExplanations: [
      { title: 'Check by multiplying back', steps: ['$4.5 \\times 1{,}000$ shifts the point three places right.', '$4.5 \\to 45 \\to 450 \\to 4{,}500$ ✓'] },
    ],
    tags: ['powers-of-ten', 'decimals'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 74, unit: 8, order: 4, slug: 'sixty-two-times-ten-fourth-mc',
    standard: '5.NBT.A.2', difficulty: 1,
    prompt: 'What is $62 \\times 10^4$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '6,200', correct: false },
      { id: 'B', label: '62,000', correct: false },
      { id: 'C', label: '620,000', correct: true },
      { id: 'D', label: '6,200,000', correct: false },
    ],
    primaryAnswer: 'C', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First figure out what $10^4$ is on its own.' },
      { level: 'guide', text: '$10^4 = 10{,}000$, which has four zeros. Multiplying $62$ by it tacks four zeros onto $62$.' },
      { level: 'reveal', text: '$62$ with four zeros is $620{,}000$ — choose C.' },
    ],
    explanation: [
      '$10^4 = 10 \\times 10 \\times 10 \\times 10 = 10{,}000$.',
      'Multiplying by $10{,}000$ adds four zeros to the end of $62$.',
      '$62 \\to 620 \\to 6{,}200 \\to 62{,}000 \\to 620{,}000$, so the answer is $620{,}000$ (C).',
    ],
    alternativeExplanations: [
      { title: 'Why the other choices are off', steps: ['$6{,}200$ came from only two shifts, and $62{,}000$ from three.', '$6{,}200{,}000$ came from five.', 'The exponent $4$ tells you exactly four shifts.'] },
    ],
    tags: ['MAP-practice', 'powers-of-ten', 'exponents'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 75, unit: 8, order: 5, slug: 'write-100000-as-power',
    standard: '5.NBT.A.2', difficulty: 2,
    prompt: 'Write $100{,}000$ using exponent notation with a base of $10$.',
    answerType: 'expression', primaryAnswer: '10^5', alternativeAnswers: ['10^{5}'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count the zeros in $100{,}000$.' },
      { level: 'guide', text: 'The number of zeros becomes the exponent on the $10$.' },
      { level: 'reveal', text: 'There are five zeros, so $100{,}000 = 10^5$.' },
    ],
    explanation: [
      '$100{,}000$ is $1$ followed by five zeros.',
      'Each zero comes from one factor of $10$: $10 \\times 10 \\times 10 \\times 10 \\times 10$.',
      'Five factors of $10$ is written $10^5$, so $100{,}000 = 10^5$.',
    ],
    alternativeExplanations: [
      { title: 'Say it out loud', steps: ['$100{,}000$ is "one hundred thousand."', 'Hundred is $10^2$ and thousand is $10^3$, and $2 + 3 = 5$ factors of ten in all ✓'] },
    ],
    tags: ['powers-of-ten', 'exponents'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 76, unit: 8, order: 6, slug: 'shift-right-0047',
    standard: '5.NBT.A.2', difficulty: 2,
    prompt: 'What is $0.047 \\times 10^3$?',
    answerType: 'numeric', primaryAnswer: '47', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$10^3$ is $1{,}000$, so the number gets a thousand times bigger.' },
      { level: 'guide', text: 'Slide the decimal point three places to the right: $0.047 \\to 0.47 \\to 4.7 \\to ?$' },
      { level: 'reveal', text: 'The third shift gives $47$.' },
    ],
    explanation: [
      '$10^3 = 1{,}000$, and multiplying by it moves the decimal point three places right.',
      'Shift one: $0.047 \\to 0.47$. Shift two: $0.47 \\to 4.7$. Shift three: $4.7 \\to 47$.',
      'So $0.047 \\times 10^3 = 47$.',
    ],
    alternativeExplanations: [
      { title: 'Fraction view', steps: ['$0.047 = \\frac{47}{1000}$.', 'Multiplying by $1{,}000$ cancels the denominator: $\\frac{47}{1000} \\times 1000 = 47$ ✓'] },
    ],
    tags: ['MAP-practice', 'powers-of-ten', 'decimals'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 77, unit: 8, order: 7, slug: 'divide-85-by-ten-squared',
    standard: '5.NBT.A.2', difficulty: 2,
    prompt: 'What is $85 \\div 10^2$?',
    answerType: 'numeric', primaryAnswer: '0.85', alternativeAnswers: ['.85'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$10^2 = 100$, and dividing shrinks the number.' },
      { level: 'guide', text: 'Move the decimal point two places left. Remember $85$ is really $85.$' },
      { level: 'reveal', text: '$85. \\to 8.5 \\to 0.85$.' },
    ],
    explanation: [
      '$10^2 = 100$, so dividing by it shifts the decimal point two places to the left.',
      'Write $85$ as $85.0$ so you can see the point, then shift: $8.5$, then $0.85$.',
      'So $85 \\div 10^2 = 0.85$.',
    ],
    alternativeExplanations: [
      { title: 'Money check', steps: ['Think of $85$ pennies.', 'A penny is $\\frac{1}{100}$ of a dollar, so $85$ pennies is $\\$0.85$ ✓'] },
    ],
    tags: ['MAP-practice', 'powers-of-ten', 'decimals'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 78, unit: 8, order: 8, slug: 'block-chunks-powers',
    standard: '5.NBT.A.2', difficulty: 2,
    prompt: 'A game world is made of $10^2$ chunks, and every chunk holds $10^3$ blocks. How many blocks are in the whole world?',
    answerType: 'numeric', primaryAnswer: '100000', alternativeAnswers: ['100,000'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Turn each power of ten into a regular number first.' },
      { level: 'guide', text: '$10^2 = 100$ chunks and $10^3 = 1{,}000$ blocks each. Now multiply.' },
      { level: 'reveal', text: '$100 \\times 1{,}000 = 100{,}000$ blocks.' },
    ],
    explanation: [
      '$10^2 = 100$ and $10^3 = 1{,}000$.',
      'Total blocks $= 100 \\times 1{,}000$. Multiplying by $1{,}000$ adds three zeros to $100$.',
      '$100 \\times 1{,}000 = 100{,}000$ blocks in the world.',
      'Notice the shortcut: two zeros plus three zeros gives five zeros, which is $10^5$.',
    ],
    alternativeExplanations: [
      { title: 'Add the exponents', steps: ['$10^2 \\times 10^3$ means $(10 \\times 10) \\times (10 \\times 10 \\times 10)$.', 'That is five tens multiplied together, so $10^5 = 100{,}000$ ✓'] },
    ],
    tags: ['MAP-practice', 'powers-of-ten', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: '5.F', num: 79, unit: 8, order: 9, slug: 'ticket-sale-power-ten',
    standard: '5.NBT.A.2', difficulty: 3,
    prompt: 'A school play sold $10^3$ tickets at $\\$8$ each. Putting on the play cost the school $\\$1{,}500$. How many dollars does the school have left after paying the costs?',
    answerType: 'numeric', primaryAnswer: '6500', alternativeAnswers: ['6,500', '$6,500'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller numbers first: $10^1 = 10$ tickets at $\\$8$ is $\\$80$, and if costs were $\\$30$ you would have $80 - 30 = \\$50$ left. Turn the power of ten into a plain number, multiply, then subtract — exactly the same three moves.' },
      { level: 'nudge', text: 'First rewrite $10^3$ as a regular number, then find the money taken in, then subtract the costs.' },
      { level: 'guide', text: '$10^3 = 1{,}000$ tickets. Money taken in is $1{,}000 \\times 8$.' },
      { level: 'reveal', text: '$1{,}000 \\times 8 = 8{,}000$, and $8{,}000 - 1{,}500 = 6{,}500$ dollars left.' },
    ],
    explanation: [
      'Step 1 — how many tickets: $10^3 = 1{,}000$.',
      'Step 2 — money taken in: $1{,}000 \\times \\$8 = \\$8{,}000$, because multiplying by $1{,}000$ adds three zeros to the $8$.',
      'Step 3 — pay the costs: $\\$8{,}000 - \\$1{,}500 = \\$6{,}500$.',
      'The school keeps $\\$6{,}500$.',
    ],
    alternativeExplanations: [
      { title: 'Subtract in friendly pieces', steps: ['$\\$8{,}000 - \\$1{,}000 = \\$7{,}000$.', 'Then take off the last $\\$500$: $\\$7{,}000 - \\$500 = \\$6{,}500$ ✓'] },
      { title: '⚠️ The trap here', steps: ['A very common wrong answer is $\\$8{,}000$ — the money taken in, with the costs never subtracted.', 'Another is treating $10^3$ as $30$ (multiplying the base by the exponent), which gives $30 \\times 8 = 240$ and a nonsense total.', '$10^3$ means $10 \\times 10 \\times 10 = 1{,}000$, and the word "left" tells you a subtraction still has to happen: $8{,}000 - 1{,}500 = 6{,}500$.'] },
    ],
    tags: ['MAP-practice', 'powers-of-ten', 'multi-step', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 80, unit: 8, order: 10, slug: 'how-many-times-greater-powers',
    standard: '5.NBT.A.2', difficulty: 3,
    prompt: 'How many times greater is $6.4 \\times 10^5$ than $6.4 \\times 10^2$?',
    answerType: 'numeric', primaryAnswer: '1000', alternativeAnswers: ['1,000'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try it small: $5 \\times 10^2 = 500$ and $5 \\times 10^1 = 50$. Since $500 \\div 50 = 10$, the bigger one is $10$ times greater — and the exponents differ by $1$. The gap in the exponents is what counts.' },
      { level: 'nudge', text: 'Write both numbers out as regular numbers and compare them.' },
      { level: 'guide', text: '$6.4 \\times 10^5 = 640{,}000$ and $6.4 \\times 10^2 = 640$. Now divide the big one by the small one.' },
      { level: 'reveal', text: '$640{,}000 \\div 640 = 1{,}000$.' },
    ],
    explanation: [
      'Write both out: $6.4 \\times 10^5 = 640{,}000$ and $6.4 \\times 10^2 = 640$.',
      'To compare sizes, divide: $640{,}000 \\div 640 = 1{,}000$.',
      'That matches the exponents: the exponent goes up by $5 - 2 = 3$, and three extra factors of ten is $10^3 = 1{,}000$.',
      'So the first number is $1{,}000$ times greater.',
    ],
    alternativeExplanations: [
      { title: 'Count the shifts', steps: ['Going from $640$ to $6{,}400$ to $64{,}000$ to $640{,}000$ takes three shifts.', 'Three shifts means $\\times 10 \\times 10 \\times 10 = 1{,}000$ ✓'] },
      { title: '⚠️ The trap here', steps: ['The tempting wrong answer is $3$, because $5 - 2 = 3$.', 'But the $3$ counts how many **extra tens** there are, not how many times greater the number is.', 'Three extra tens multiply together: $10 \\times 10 \\times 10 = 1{,}000$, so the answer is $1{,}000$, not $3$.'] },
    ],
    tags: ['MAP-practice', 'powers-of-ten', 'exponents', 'comparison'], estimatedSeconds: 70,
  },

  // ============ UNIT 9 — Adding & subtracting decimals ============
  {
    domain: '5.F', num: 81, unit: 9, order: 1, slug: 'add-decimals-34-27',
    standard: '5.NBT.B.7', difficulty: 1,
    prompt: 'Add: $3.4 + 2.7$',
    answerType: 'numeric', primaryAnswer: '6.1', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Stack the numbers so the decimal points are right on top of each other.' },
      { level: 'guide', text: 'Tenths first: $4 + 7 = 11$ tenths, which is $1$ whole and $1$ tenth — so you carry.' },
      { level: 'reveal', text: '$3 + 2 = 5$, plus the carried $1$ is $6$, and $1$ tenth is left: $6.1$.' },
    ],
    explanation: [
      'Line up the decimal points so tenths sit under tenths and ones under ones.',
      'Add the tenths: $4 + 7 = 11$ tenths. That is $1$ whole plus $1$ tenth, so write $1$ and carry the whole.',
      'Add the ones: $3 + 2 + 1 = 6$.',
      'So $3.4 + 2.7 = 6.1$.',
    ],
    alternativeExplanations: [
      { title: 'Estimate to check', steps: ['$3.4$ is about $3$ and $2.7$ is about $3$.', '$3 + 3 = 6$, and $6.1$ is right there ✓'] },
    ],
    tags: ['decimals', 'addition'], estimatedSeconds: 30,
  },
  {
    domain: '5.F', num: 82, unit: 9, order: 2, slug: 'subtract-decimals-86-32',
    standard: '5.NBT.B.7', difficulty: 1,
    prompt: 'Subtract: $8.6 - 3.2$',
    answerType: 'numeric', primaryAnswer: '5.4', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Line up the decimal points, then subtract column by column.' },
      { level: 'guide', text: 'Tenths: $6 - 2 = 4$. Ones: $8 - 3 = ?$' },
      { level: 'reveal', text: '$8 - 3 = 5$, so the answer is $5.4$.' },
    ],
    explanation: [
      'Stack the numbers with the decimal points lined up.',
      'Subtract the tenths: $6 - 2 = 4$ tenths. No regrouping needed.',
      'Subtract the ones: $8 - 3 = 5$.',
      'So $8.6 - 3.2 = 5.4$.',
    ],
    alternativeExplanations: [
      { title: 'Check by adding back', steps: ['$5.4 + 3.2$ should return the starting number.', '$4 + 2 = 6$ tenths and $5 + 3 = 8$ ones, giving $8.6$ ✓'] },
    ],
    tags: ['decimals', 'subtraction'], estimatedSeconds: 30,
  },
  {
    domain: '5.F', num: 83, unit: 9, order: 3, slug: 'snack-money-total',
    standard: '5.NBT.B.7', difficulty: 1,
    prompt: 'At the snack bar you buy a pretzel for $\\$2.75$ and a juice for $\\$1.40$. How much do you spend in all?',
    answerType: 'numeric', primaryAnswer: '4.15', alternativeAnswers: ['$4.15'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"In all" means add. Line up the decimal points like the price tags in a column.' },
      { level: 'guide', text: 'Hundredths: $5 + 0 = 5$. Tenths: $7 + 4 = 11$ tenths, so carry.' },
      { level: 'reveal', text: '$2.75 + 1.40 = 4.15$.' },
    ],
    explanation: [
      'Stack the prices with the decimal points lined up: $2.75$ over $1.40$.',
      'Hundredths: $5 + 0 = 5$. Tenths: $7 + 4 = 11$, so write $1$ and carry $1$ whole dollar.',
      'Dollars: $2 + 1 + 1 = 4$.',
      'The total is $\\$4.15$.',
    ],
    alternativeExplanations: [
      { title: 'Dollars and cents separately', steps: ['Dollars: $\\$2 + \\$1 = \\$3$.', 'Cents: $75¢ + 40¢ = 115¢ = \\$1.15$.', '$\\$3 + \\$1.15 = \\$4.15$ ✓'] },
    ],
    tags: ['MAP-practice', 'decimals', 'money', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 84, unit: 9, order: 4, slug: 'seven-minus-four-tenths-mc',
    standard: '5.NBT.B.7', difficulty: 1,
    prompt: 'What is $7 - 0.4$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '6.6', correct: true },
      { id: 'B', label: '3', correct: false },
      { id: 'C', label: '6.96', correct: false },
      { id: 'D', label: '7.4', correct: false },
    ],
    primaryAnswer: 'A', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Rewrite $7$ as $7.0$ so both numbers have a tenths place.' },
      { level: 'guide', text: 'You cannot take $4$ tenths from $0$ tenths, so borrow: $7.0$ becomes $6$ wholes and $10$ tenths.' },
      { level: 'reveal', text: '$10 - 4 = 6$ tenths, and $6$ wholes are left, giving $6.6$ — choose A.' },
    ],
    explanation: [
      'Write $7$ as $7.0$ so the tenths line up.',
      'There are $0$ tenths on top, so regroup one whole into $10$ tenths: $7.0$ becomes $6$ and $10$ tenths.',
      '$10 - 4 = 6$ tenths, and the whole-number part is $6$.',
      'So $7 - 0.4 = 6.6$, which is choice A.',
    ],
    alternativeExplanations: [
      { title: 'Why the others are wrong', steps: ['$3$ comes from ignoring the decimal and doing $7 - 4$.', '$6.96$ comes from treating $0.4$ as $0.04$.', '$7.4$ comes from adding instead of subtracting.'] },
    ],
    tags: ['decimals', 'subtraction'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 85, unit: 9, order: 5, slug: 'add-three-decimals-supplies',
    standard: '5.NBT.B.7', difficulty: 2,
    prompt: 'Add: $1.25 + 0.8 + 3.06$',
    answerType: 'numeric', primaryAnswer: '5.11', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Give every number the same number of decimal places by writing $0.8$ as $0.80$.' },
      { level: 'guide', text: 'Add two at a time: $1.25 + 0.80 = 2.05$. Now add $3.06$.' },
      { level: 'reveal', text: '$2.05 + 3.06 = 5.11$.' },
    ],
    explanation: [
      'Write $0.8$ as $0.80$ so all three numbers show hundredths — adding a zero on the end never changes a decimal.',
      'Add the first two: $1.25 + 0.80 = 2.05$.',
      'Add the third: $2.05 + 3.06 = 5.11$.',
      'So the sum is $5.11$.',
    ],
    alternativeExplanations: [
      { title: 'Estimate to check', steps: ['Round: about $1 + 1 + 3 = 5$.', '$5.11$ is right next to $5$, so the answer is reasonable ✓'] },
    ],
    tags: ['decimals', 'addition'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 86, unit: 9, order: 6, slug: 'subtract-across-zeros-10',
    standard: '5.NBT.B.7', difficulty: 2,
    prompt: 'Subtract: $10 - 4.37$',
    answerType: 'numeric', primaryAnswer: '5.63', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Rewrite $10$ as $10.00$ so there are hundredths to subtract from.' },
      { level: 'guide', text: 'Try counting up instead of borrowing: from $4.37$, how far to $5$? Then from $5$ to $10$?' },
      { level: 'reveal', text: '$4.37 + 0.63 = 5$ and $5 + 5 = 10$, so the difference is $0.63 + 5 = 5.63$.' },
    ],
    explanation: [
      'Write the problem as $10.00 - 4.37$ so both numbers have hundredths.',
      'Counting up is easier than borrowing across two zeros: from $4.37$ up to $5.00$ is $0.63$.',
      'From $5.00$ up to $10.00$ is $5$ more.',
      'Total distance: $0.63 + 5 = 5.63$, so $10 - 4.37 = 5.63$.',
    ],
    alternativeExplanations: [
      { title: 'Check by adding back', steps: ['$5.63 + 4.37$: hundredths $3 + 7 = 10$, tenths $6 + 3 + 1 = 10$, ones $5 + 4 + 1 = 10$.', 'That rebuilds $10.00$ exactly ✓'] },
    ],
    tags: ['MAP-practice', 'decimals', 'subtraction'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 87, unit: 9, order: 7, slug: 'race-time-difference',
    standard: '5.NBT.B.7', difficulty: 2,
    prompt: 'In a $100$-meter race, Mia finished in $12.45$ seconds and Leo finished in $13.2$ seconds. How many seconds faster was Mia?',
    answerType: 'numeric', primaryAnswer: '0.75', alternativeAnswers: ['.75'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"How much faster" means find the difference between the two times.' },
      { level: 'guide', text: 'Write $13.2$ as $13.20$ so it has hundredths, then subtract $12.45$.' },
      { level: 'reveal', text: '$13.20 - 12.45 = 0.75$ seconds.' },
    ],
    explanation: [
      'The faster runner has the **smaller** time, so subtract: $13.2 - 12.45$.',
      'Write $13.2$ as $13.20$ so both times show hundredths.',
      'Count up from $12.45$: $+0.55$ reaches $13.00$, then $+0.20$ reaches $13.20$, and $0.55 + 0.20 = 0.75$.',
      'Mia was $0.75$ seconds faster.',
    ],
    alternativeExplanations: [
      { title: 'Estimate to check', steps: ['The times are about $12.5$ and $13.2$, a gap of roughly $0.7$ seconds.', '$0.75$ fits that, so the answer makes sense ✓'] },
    ],
    tags: ['MAP-practice', 'decimals', 'measurement', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 88, unit: 9, order: 8, slug: 'estimate-decimal-sum-mc',
    standard: '5.NBT.B.7', difficulty: 2,
    prompt: 'Without adding exactly, $4.87 + 3.95$ is **closest** to which whole number?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '7', correct: false },
      { id: 'B', label: '8', correct: false },
      { id: 'C', label: '9', correct: true },
      { id: 'D', label: '12', correct: false },
    ],
    primaryAnswer: 'C', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Round each number to the nearest whole number first.' },
      { level: 'guide', text: '$4.87$ rounds to $5$ and $3.95$ rounds to $4$.' },
      { level: 'reveal', text: '$5 + 4 = 9$, so choose C.' },
    ],
    explanation: [
      '$4.87$ is past the halfway point $4.5$, so it rounds up to $5$.',
      '$3.95$ is past $3.5$, so it rounds up to $4$.',
      '$5 + 4 = 9$, so the sum is closest to $9$ (choice C).',
      'The exact sum is $8.82$, which really is nearest to $9$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Why not 8?', steps: ['Chopping the decimals off instead of rounding gives $4 + 3 = 7$ — too small.', 'Both numbers are nearly whole, so rounding up on both is the honest estimate: $9$.'] },
    ],
    tags: ['MAP-practice', 'estimation', 'decimals'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 89, unit: 9, order: 9, slug: 'sleepover-snack-change',
    standard: '5.NBT.B.7', difficulty: 3,
    prompt: 'You bring $\\$20$ to the store for a sleepover. You buy popcorn for $\\$4.79$, soda for $\\$3.25$, and candy for $\\$6.50$. How much change do you get back?',
    answerType: 'numeric', primaryAnswer: '5.46', alternativeAnswers: ['$5.46'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a two-item version: with $\\$10$, buying a $\\$2.50$ snack and a $\\$1.25$ drink costs $\\$3.75$, so the change is $10 - 3.75 = \\$6.25$. Add up all the prices first, then subtract from what you brought — same plan with three items.' },
      { level: 'nudge', text: 'Two steps: total what you spent, then subtract that total from $\\$20$.' },
      { level: 'guide', text: '$4.79 + 3.25 = 8.04$. Now add the candy: $8.04 + 6.50 = ?$' },
      { level: 'reveal', text: 'The total is $\\$14.54$, and $\\$20.00 - \\$14.54 = \\$5.46$.' },
    ],
    explanation: [
      'Step 1 — add the prices, keeping the decimal points lined up: $4.79 + 3.25 = 8.04$.',
      'Add the candy: $8.04 + 6.50 = 14.54$, so you spent $\\$14.54$.',
      'Step 2 — subtract from what you brought. Write $\\$20$ as $\\$20.00$ and count up from $14.54$: $+0.46$ reaches $15.00$, then $+5$ reaches $20.00$.',
      '$0.46 + 5 = 5.46$, so your change is $\\$5.46$.',
    ],
    alternativeExplanations: [
      { title: 'Estimate to check', steps: ['The prices are roughly $\\$5 + \\$3 + \\$6.50 = \\$14.50$.', '$\\$20 - \\$14.50 = \\$5.50$, so a change near $\\$5.46$ is right ✓'] },
      { title: '⚠️ The trap here', steps: ['The usual wrong answer is $\\$14.54$ — the amount spent, handed in as if it were the change.', 'A second slip is subtracting only one item, like $20 - 6.50 = 13.50$.', 'Underline the question: it asks what comes **back** to you, so every price has to be added first and then subtracted from $\\$20.00$: $20.00 - 14.54 = \\$5.46$.'] },
    ],
    tags: ['MAP-practice', 'decimals', 'money', 'multi-step', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 90, unit: 9, order: 10, slug: 'puppy-weight-gain',
    standard: '5.NBT.B.7', difficulty: 3,
    prompt: 'A puppy weighed $8.4$ kg at the vet. It gained $1.35$ kg the next month and $0.9$ kg the month after that. What does the puppy weigh now, in kilograms?',
    answerType: 'numeric', primaryAnswer: '10.65', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easier version: $2.5$ kg that gains $0.25$ kg and then $0.1$ kg. Write them all with two decimal places — $2.50 + 0.25 + 0.10 = 2.85$. Giving every number the same number of decimal places is the whole trick.' },
      { level: 'nudge', text: 'Gaining weight means adding. Add all three numbers, keeping the decimal points stacked.' },
      { level: 'guide', text: 'Write them all with two decimal places: $8.40 + 1.35 + 0.90$.' },
      { level: 'reveal', text: '$8.40 + 1.35 = 9.75$, and $9.75 + 0.90 = 10.65$ kg.' },
    ],
    explanation: [
      'Rewrite every number with two decimal places so the columns match: $8.40$, $1.35$, $0.90$.',
      'Add the first two: $8.40 + 1.35 = 9.75$.',
      'Add the third: $9.75 + 0.90 = 10.65$.',
      'The puppy now weighs $10.65$ kg.',
    ],
    alternativeExplanations: [
      { title: 'Add the gains first', steps: ['Total gain: $1.35 + 0.90 = 2.25$ kg.', 'Starting weight plus total gain: $8.40 + 2.25 = 10.65$ kg ✓'] },
      { title: '⚠️ The trap here', steps: ['The classic wrong answer is $9.84$, which happens when $0.9$ gets stacked under the hundredths column as if it were $0.09$.', '$0.9$ is nine **tenths**, not nine hundredths — it belongs in the same column as the $4$ in $8.4$.', 'Writing it as $0.90$ before you add keeps the columns honest and gives $10.65$.'] },
    ],
    tags: ['MAP-practice', 'decimals', 'measurement', 'multi-step'], estimatedSeconds: 70,
  },

  // ============ UNIT 10 — Multiplying & dividing decimals ============
  {
    domain: '5.F', num: 91, unit: 10, order: 1, slug: 'decimal-times-whole-06x7',
    standard: '5.NBT.B.7', difficulty: 1,
    prompt: 'Multiply: $0.6 \\times 7$',
    answerType: 'numeric', primaryAnswer: '4.2', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Ignore the decimal point for a second: what is $6 \\times 7$?' },
      { level: 'guide', text: '$6 \\times 7 = 42$. The factor $0.6$ has one decimal place, so the answer needs one too.' },
      { level: 'reveal', text: 'Put the point one place from the right: $4.2$.' },
    ],
    explanation: [
      'First multiply as if there were no decimal point: $6 \\times 7 = 42$.',
      'Count the decimal places in the factors: $0.6$ has one, $7$ has none, so the product needs one.',
      'Place the point one spot from the right of $42$: $4.2$.',
      'So $0.6 \\times 7 = 4.2$.',
    ],
    alternativeExplanations: [
      { title: 'Does it make sense?', steps: ['$0.6$ is a bit more than half.', 'A bit more than half of $7$ should be a bit more than $3.5$ — and $4.2$ is ✓'] },
    ],
    tags: ['decimals', 'multiplication'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 92, unit: 10, order: 2, slug: 'tenths-times-tenths-03x04',
    standard: '5.NBT.B.7', difficulty: 1,
    prompt: 'Multiply: $0.3 \\times 0.4$',
    answerType: 'numeric', primaryAnswer: '0.12', alternativeAnswers: ['.12'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Start with the whole numbers: $3 \\times 4 = 12$.' },
      { level: 'guide', text: 'Each factor has one decimal place, so the answer needs $1 + 1 = 2$ decimal places.' },
      { level: 'reveal', text: 'Two places in $12$ means $0.12$.' },
    ],
    explanation: [
      'Multiply as whole numbers: $3 \\times 4 = 12$.',
      'Count decimal places: one in $0.3$ plus one in $0.4$ makes two.',
      'Move in two places from the right of $12$, writing a zero in front: $0.12$.',
      'So $0.3 \\times 0.4 = 0.12$.',
    ],
    alternativeExplanations: [
      { title: 'Fraction view', steps: ['$0.3 = \\frac{3}{10}$ and $0.4 = \\frac{4}{10}$.', '$\\frac{3}{10} \\times \\frac{4}{10} = \\frac{12}{100} = 0.12$ ✓ — the hundredths explain the two decimal places.'] },
    ],
    tags: ['decimals', 'multiplication'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 93, unit: 10, order: 3, slug: 'divide-48-by-6-decimal',
    standard: '5.NBT.B.7', difficulty: 1,
    prompt: 'Divide: $4.8 \\div 6$',
    answerType: 'numeric', primaryAnswer: '0.8', alternativeAnswers: ['.8'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Think in tenths: $4.8$ is $48$ tenths.' },
      { level: 'guide', text: '$48$ tenths shared into $6$ equal groups: $48 \\div 6 = 8$ tenths.' },
      { level: 'reveal', text: '$8$ tenths is $0.8$.' },
    ],
    explanation: [
      'Rename the dividend in tenths: $4.8 = 48$ tenths.',
      'Split those tenths into $6$ equal groups: $48 \\div 6 = 8$, so each group has $8$ tenths.',
      '$8$ tenths written as a decimal is $0.8$, so $4.8 \\div 6 = 0.8$.',
    ],
    alternativeExplanations: [
      { title: 'Check by multiplying back', steps: ['$0.8 \\times 6$: $8 \\times 6 = 48$, and one decimal place gives $4.8$ ✓'] },
    ],
    tags: ['decimals', 'division'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 94, unit: 10, order: 4, slug: 'place-the-point-23x15-mc',
    standard: '5.NBT.B.7', difficulty: 1,
    prompt: 'You already know that $23 \\times 15 = 345$. Using that, what is $2.3 \\times 1.5$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '345', correct: false },
      { id: 'B', label: '34.5', correct: false },
      { id: 'C', label: '3.45', correct: true },
      { id: 'D', label: '0.345', correct: false },
    ],
    primaryAnswer: 'C', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The digits stay the same — only the decimal point moves. Count the decimal places in the factors.' },
      { level: 'guide', text: '$2.3$ has one decimal place and $1.5$ has one, so the product needs two.' },
      { level: 'reveal', text: 'Two places in $345$ gives $3.45$ — choose C.' },
    ],
    explanation: [
      'The digits of the product come straight from $23 \\times 15 = 345$.',
      'Count the decimal places in the factors: $1$ in $2.3$ plus $1$ in $1.5$ equals $2$.',
      'Place the point two spots from the right of $345$: $3.45$ (choice C).',
      'It passes the common-sense test too: about $2$ times about $1.5$ should be around $3$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Why the others are wrong', steps: ['$34.5$ uses only one decimal place, and $0.345$ uses three.', '$345$ uses none at all, which would mean multiplying two numbers near $2$ and getting three hundred.'] },
    ],
    tags: ['MAP-practice', 'decimals', 'multiplication', 'estimation'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 95, unit: 10, order: 5, slug: 'movie-tickets-375',
    standard: '5.NBT.B.7', difficulty: 2,
    prompt: 'Six friends each pay $\\$3.75$ for a movie ticket. How much do they pay altogether?',
    answerType: 'numeric', primaryAnswer: '22.5', alternativeAnswers: ['22.50', '$22.50'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Six equal payments means $3.75 \\times 6$.' },
      { level: 'guide', text: 'Multiply the digits first: $375 \\times 6 = 2250$. Now place the decimal point.' },
      { level: 'reveal', text: '$3.75$ has two decimal places, so the answer does too: $\\$22.50$.' },
    ],
    explanation: [
      'Six equal prices means multiply: $\\$3.75 \\times 6$.',
      'Multiply without the point: $375 \\times 6 = 2{,}250$.',
      '$3.75$ has two decimal places, so the product needs two: $22.50$.',
      'Altogether they pay $\\$22.50$.',
    ],
    alternativeExplanations: [
      { title: 'Friendly-number shortcut', steps: ['$\\$3.75$ is $\\$4$ minus $25¢$.', '$6 \\times \\$4 = \\$24$, and $6 \\times 25¢ = \\$1.50$.', '$\\$24 - \\$1.50 = \\$22.50$ ✓'] },
    ],
    tags: ['MAP-practice', 'decimals', 'money', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 96, unit: 10, order: 6, slug: 'decimal-times-decimal-14x25',
    standard: '5.NBT.B.7', difficulty: 2,
    prompt: 'Multiply: $1.4 \\times 2.5$',
    answerType: 'numeric', primaryAnswer: '3.5', alternativeAnswers: ['3.50'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Drop the points and multiply $14 \\times 25$ first.' },
      { level: 'guide', text: '$14 \\times 25 = 350$. Each factor has one decimal place, so the product needs two.' },
      { level: 'reveal', text: 'Two places in $350$ gives $3.50$, which is $3.5$.' },
    ],
    explanation: [
      'Multiply the digits as whole numbers: $14 \\times 25 = 350$.',
      'Count decimal places: one in $1.4$ plus one in $2.5$ makes two.',
      'Place the point two spots from the right: $3.50$, or simply $3.5$.',
      'Estimate check: $1.4$ is close to $1.5$ and $1.5 \\times 2.5 = 3.75$, so $3.5$ is right in range ✓',
    ],
    alternativeExplanations: [
      { title: 'Split the 2.5', steps: ['$1.4 \\times 2 = 2.8$.', '$1.4 \\times 0.5$ is half of $1.4$, which is $0.7$.', '$2.8 + 0.7 = 3.5$ ✓'] },
    ],
    tags: ['decimals', 'multiplication'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 97, unit: 10, order: 7, slug: 'divide-by-decimal-72-08',
    standard: '5.NBT.B.7', difficulty: 2,
    prompt: 'Divide: $7.2 \\div 0.8$',
    answerType: 'numeric', primaryAnswer: '9', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Dividing by a decimal is easier if you first make the divisor a whole number.' },
      { level: 'guide', text: 'Multiply both numbers by $10$: $7.2 \\div 0.8$ becomes $72 \\div 8$.' },
      { level: 'reveal', text: '$72 \\div 8 = 9$.' },
    ],
    explanation: [
      'Scaling both numbers by the same amount does not change a quotient, so multiply each by $10$.',
      '$7.2 \\times 10 = 72$ and $0.8 \\times 10 = 8$, turning the problem into $72 \\div 8$.',
      '$72 \\div 8 = 9$, so $7.2 \\div 0.8 = 9$.',
    ],
    alternativeExplanations: [
      { title: 'Ask "how many fit?"', steps: ['The question is really: how many $0.8$s fit inside $7.2$?', '$0.8 \\times 9 = 7.2$ exactly, so nine of them fit ✓'] },
    ],
    tags: ['decimals', 'division'], estimatedSeconds: 55,
  },
  {
    domain: '5.F', num: 98, unit: 10, order: 8, slug: 'granola-bars-allowance',
    standard: '5.NBT.B.7', difficulty: 2,
    prompt: 'Granola bars cost $\\$0.65$ each. With $\\$5.20$ of allowance money, how many granola bars can you buy?',
    answerType: 'numeric', primaryAnswer: '8', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You are asking how many $\\$0.65$ groups fit inside $\\$5.20$ — that is division.' },
      { level: 'guide', text: 'Multiply both numbers by $100$ to work in cents: $520 \\div 65$.' },
      { level: 'reveal', text: '$65 \\times 8 = 520$, so you can buy $8$ bars.' },
    ],
    explanation: [
      'Set it up as division: $\\$5.20 \\div \\$0.65$.',
      'Working in cents keeps it whole: $520$ cents $\\div$ $65$ cents.',
      '$65 \\times 8 = 520$, so exactly $8$ bars fit with nothing left over.',
      'You can buy $8$ granola bars.',
    ],
    alternativeExplanations: [
      { title: 'Estimate first', steps: ['$\\$0.65$ is close to $\\$0.50$, and $\\$5.20 \\div \\$0.50$ would be about $10$.', 'Since the real bars cost a bit more, the real answer is a bit less than $10$ — and $8$ fits ✓'] },
    ],
    tags: ['MAP-practice', 'decimals', 'division', 'money', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 99, unit: 10, order: 9, slug: 'cookie-sugar-jars',
    standard: '5.NBT.B.7', difficulty: 3,
    prompt: 'One batch of cookies needs $0.75$ cup of sugar. You measure out enough sugar for $4$ batches, then split it evenly into $6$ small jars. How many cups of sugar go in each jar?',
    answerType: 'numeric', primaryAnswer: '0.5', alternativeAnswers: ['.5', '1/2'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try friendlier numbers: $0.5$ cup per batch for $2$ batches is $1$ cup, and splitting $1$ cup into $4$ jars gives $0.25$ cup each. Multiply to find the total, then divide the total by the number of jars — same two steps.' },
      { level: 'nudge', text: 'Two steps: find the total sugar for $4$ batches, then share that total among $6$ jars.' },
      { level: 'guide', text: 'Total sugar $= 0.75 \\times 4$. Then divide that total by $6$.' },
      { level: 'reveal', text: '$0.75 \\times 4 = 3$ cups, and $3 \\div 6 = 0.5$ cup per jar.' },
    ],
    explanation: [
      'Step 1 — total sugar: $0.75 \\times 4$. Since $75 \\times 4 = 300$ and $0.75$ has two decimal places, the product is $3.00 = 3$ cups.',
      'Step 2 — share it out: $3 \\div 6$.',
      'Six jars from $3$ cups means each jar gets half a cup: $3 \\div 6 = 0.5$.',
      'So each jar holds $0.5$ cup of sugar.',
    ],
    alternativeExplanations: [
      { title: 'Fraction view', steps: ['$0.75 = \\frac{3}{4}$, so $4$ batches need $4 \\times \\frac{3}{4} = 3$ cups.', '$3 \\div 6 = \\frac{3}{6} = \\frac{1}{2} = 0.5$ cup ✓'] },
      { title: '⚠️ The trap here', steps: ['A common wrong answer is $3$ — the total sugar — because the sharing step gets skipped.', 'Another is dividing first, $0.75 \\div 6 = 0.125$, which answers a different question (one batch split six ways).', 'Follow the story in order: all $4$ batches are measured out **before** the jars are filled, so multiply first ($3$ cups) and divide second ($3 \\div 6 = 0.5$).'] },
    ],
    tags: ['MAP-practice', 'decimals', 'multi-step', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 100, unit: 10, order: 10, slug: 'ribbon-pieces-stickers',
    standard: '5.NBT.B.7', difficulty: 3,
    prompt: 'A roll of ribbon is $2.4$ meters long. It is cut into pieces that are each $0.3$ meter long, and every piece gets one sticker costing $\\$0.25$. How many dollars do the stickers cost in all?',
    answerType: 'numeric', primaryAnswer: '2', alternativeAnswers: ['2.00', '$2.00'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller numbers: a $1.0$ m ribbon cut into $0.5$ m pieces gives $1.0 \\div 0.5 = 2$ pieces, and at $\\$0.10$ a sticker that is $2 \\times 0.10 = \\$0.20$. Divide to count the pieces, then multiply by the price — same two steps.' },
      { level: 'nudge', text: 'First find how many pieces there are, then pay for one sticker per piece.' },
      { level: 'guide', text: 'Pieces $= 2.4 \\div 0.3$. Multiply both by $10$ to get $24 \\div 3$.' },
      { level: 'reveal', text: '$24 \\div 3 = 8$ pieces, and $8 \\times \\$0.25 = \\$2.00$.' },
    ],
    explanation: [
      'Step 1 — count the pieces: $2.4 \\div 0.3$. Multiply both numbers by $10$ to clear the decimal, giving $24 \\div 3 = 8$ pieces.',
      'Step 2 — pay for the stickers: $8 \\times \\$0.25$.',
      'Four quarters make a dollar, so $8$ quarters make $\\$2.00$.',
      'The stickers cost $\\$2$ in all.',
    ],
    alternativeExplanations: [
      { title: 'Check the pieces', steps: ['$8$ pieces $\\times$ $0.3$ m each $= 2.4$ m, which uses the whole roll exactly ✓'] },
      { title: '⚠️ The trap here', steps: ['The most common wrong answer is $0.8$ pieces, from doing $2.4 \\div 3$ and forgetting to shift the divisor, or from dividing $0.3$ into $2.4$ the wrong way round.', 'Sanity-check the size: pieces smaller than the whole roll must mean **more** than one piece, so the count has to be bigger than $1$.', 'Clear the decimal first — $24 \\div 3 = 8$ pieces — then $8 \\times \\$0.25 = \\$2$.'] },
    ],
    tags: ['MAP-practice', 'decimals', 'division', 'multi-step', 'word-problem'], estimatedSeconds: 75,
  },

  // ============ UNIT 11 — Fractions as division & mixed numbers ============
  {
    domain: '5.F', num: 101, unit: 11, order: 1, slug: 'three-divided-by-four-fraction',
    standard: '5.NF.B.3', difficulty: 1,
    prompt: 'Write $3 \\div 4$ as a fraction.',
    answerType: 'fraction', primaryAnswer: '3/4', alternativeAnswers: ['0.75'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A fraction bar is just another way to write a division sign.' },
      { level: 'guide', text: 'The number being shared goes on top; the number of shares goes on the bottom.' },
      { level: 'reveal', text: '$3 \\div 4 = \\frac{3}{4}$.' },
    ],
    explanation: [
      'A fraction means "top divided by bottom," so any division can be written as a fraction.',
      'Here $3$ is being split into $4$ equal parts, so $3$ is the numerator and $4$ is the denominator.',
      '$3 \\div 4 = \\frac{3}{4}$.',
    ],
    alternativeExplanations: [
      { title: 'Picture it', steps: ['Imagine $3$ granola bars shared by $4$ friends.', 'Cut each bar into $4$ pieces — that is $12$ pieces, and each friend takes $3$ of them.', '$3$ pieces out of the $4$ that make one bar is $\\frac{3}{4}$ of a bar ✓'] },
    ],
    tags: ['fractions', 'division'], estimatedSeconds: 30,
  },
  {
    domain: '5.F', num: 102, unit: 11, order: 2, slug: 'fraction-means-division-mc',
    standard: '5.NF.B.3', difficulty: 1,
    prompt: 'The fraction $\\frac{7}{8}$ means the same as which division?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '8 ÷ 7', correct: false },
      { id: 'B', label: '7 ÷ 8', correct: true },
      { id: 'C', label: '7 × 8', correct: false },
      { id: 'D', label: '8 − 7', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Read the fraction bar out loud as "divided by."' },
      { level: 'guide', text: 'The top number is the one being divided up.' },
      { level: 'reveal', text: '$\\frac{7}{8}$ means $7 \\div 8$ — choose B.' },
    ],
    explanation: [
      'The fraction bar is a division sign: numerator on top gets divided by denominator on the bottom.',
      'So $\\frac{7}{8}$ means $7 \\div 8$, which is choice B.',
      'Check the size: $7 \\div 8$ should be a little less than $1$, and $\\frac{7}{8}$ is indeed just under $1$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Why not 8 ÷ 7?', steps: ['$8 \\div 7$ is bigger than $1$, but $\\frac{7}{8}$ is smaller than $1$.', 'Flipping the order changes the answer, so the top number always goes first.'] },
    ],
    tags: ['fractions', 'division'], estimatedSeconds: 35,
  },
  {
    domain: '5.F', num: 103, unit: 11, order: 3, slug: 'share-two-pizzas-five-kids',
    standard: '5.NF.B.3', difficulty: 1,
    prompt: 'Two pizzas are shared equally among $5$ kids at a sleepover. How much pizza does each kid get?',
    answerType: 'fraction', primaryAnswer: '2/5', alternativeAnswers: ['0.4'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sharing equally is division: $2$ pizzas $\\div$ $5$ kids.' },
      { level: 'guide', text: 'Write that division as a fraction — the pizzas go on top.' },
      { level: 'reveal', text: '$2 \\div 5 = \\frac{2}{5}$ of a pizza each.' },
    ],
    explanation: [
      'Sharing $2$ pizzas equally among $5$ kids means $2 \\div 5$.',
      'A division written as a fraction puts the dividend on top: $2 \\div 5 = \\frac{2}{5}$.',
      'Each kid gets $\\frac{2}{5}$ of a pizza.',
      'Check: $5$ kids $\\times$ $\\frac{2}{5}$ each $= \\frac{10}{5} = 2$ whole pizzas ✓',
    ],
    alternativeExplanations: [
      { title: 'Cut it up', steps: ['Slice each pizza into $5$ equal slices — that is $10$ slices in all.', '$10$ slices shared by $5$ kids is $2$ slices each.', 'Two slices out of the five that make a pizza is $\\frac{2}{5}$ ✓'] },
    ],
    tags: ['MAP-practice', 'fractions', 'division', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 104, unit: 11, order: 4, slug: 'improper-17-fifths-to-mixed',
    standard: '5.NF.B.3', difficulty: 1,
    prompt: 'Write $\\frac{17}{5}$ as a mixed number.',
    answerType: 'fraction', primaryAnswer: '17/5', alternativeAnswers: ['3 2/5', '3.4'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The fraction bar means divide: how many whole $5$s fit inside $17$?' },
      { level: 'guide', text: '$5 \\times 3 = 15$, so $3$ wholes fit and something is left over.' },
      { level: 'reveal', text: '$17 - 15 = 2$ fifths are left, so $\\frac{17}{5} = 3\\frac{2}{5}$.' },
    ],
    explanation: [
      '$\\frac{17}{5}$ means $17 \\div 5$.',
      '$5 \\times 3 = 15$, so three whole groups of five fit inside $17$.',
      'What is left is $17 - 15 = 2$, and those $2$ pieces are still fifths.',
      'So $\\frac{17}{5} = 3\\frac{2}{5}$, which as a decimal is $3.4$.',
    ],
    alternativeExplanations: [
      { title: 'Count up by wholes', steps: ['$\\frac{5}{5} = 1$, $\\frac{10}{5} = 2$, $\\frac{15}{5} = 3$.', 'From $\\frac{15}{5}$ to $\\frac{17}{5}$ is $2$ more fifths, giving $3\\frac{2}{5}$ ✓'] },
    ],
    tags: ['fractions', 'mixed-numbers'], estimatedSeconds: 40,
  },
  {
    domain: '5.F', num: 105, unit: 11, order: 5, slug: 'mixed-four-and-two-thirds-to-improper',
    standard: '5.NF.B.3', difficulty: 2,
    prompt: 'Write $4\\frac{2}{3}$ as an improper fraction.',
    answerType: 'fraction', primaryAnswer: '14/3', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'How many thirds are hiding in each whole?' },
      { level: 'guide', text: 'Each whole is $\\frac{3}{3}$, so $4$ wholes are $4 \\times 3 = 12$ thirds.' },
      { level: 'reveal', text: '$12$ thirds plus the extra $2$ thirds is $\\frac{14}{3}$.' },
    ],
    explanation: [
      'One whole equals $\\frac{3}{3}$, so four wholes equal $4 \\times 3 = 12$ thirds.',
      'The mixed number also carries $\\frac{2}{3}$ extra.',
      'Altogether: $12 + 2 = 14$ thirds, so $4\\frac{2}{3} = \\frac{14}{3}$.',
      'Check: $14 \\div 3 = 4$ remainder $2$, which is $4\\frac{2}{3}$ again ✓',
    ],
    alternativeExplanations: [
      { title: 'The shortcut, and why it works', steps: ['Multiply the whole number by the denominator, then add the numerator: $4 \\times 3 + 2 = 14$.', 'Keep the same denominator: $\\frac{14}{3}$.', 'That is exactly the counting-thirds argument, done in one line ✓'] },
    ],
    tags: ['fractions', 'mixed-numbers'], estimatedSeconds: 45,
  },
  {
    domain: '5.F', num: 106, unit: 11, order: 6, slug: 'share-nine-brownies-four-friends',
    standard: '5.NF.B.3', difficulty: 2,
    prompt: 'Nine brownies are shared equally among $4$ friends. How many brownies does each friend get?',
    answerType: 'fraction', primaryAnswer: '9/4', alternativeAnswers: ['2 1/4', '2.25'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Equal sharing means division: $9 \\div 4$.' },
      { level: 'guide', text: 'Write it as a fraction: $\\frac{9}{4}$. Now see how many wholes that is.' },
      { level: 'reveal', text: '$4 \\times 2 = 8$, leaving $1$ quarter, so each friend gets $\\frac{9}{4} = 2\\frac{1}{4}$ brownies.' },
    ],
    explanation: [
      'Sharing $9$ brownies among $4$ friends is $9 \\div 4 = \\frac{9}{4}$.',
      'To read that as a mixed number, divide: $4$ goes into $9$ twice with $1$ left over.',
      'The leftover $1$ is still one fourth of a brownie, so each friend gets $2\\frac{1}{4}$ brownies.',
      'Check: $4 \\times 2\\frac{1}{4} = 8 + 1 = 9$ brownies ✓',
    ],
    alternativeExplanations: [
      { title: 'Hand them out', steps: ['Give everyone $2$ whole brownies first — that uses $8$.', 'One brownie is left, cut into $4$ equal pieces, one piece each.', 'So each friend has $2$ brownies and $\\frac{1}{4}$ more: $2\\frac{1}{4}$ ✓'] },
    ],
    tags: ['MAP-practice', 'fractions', 'division', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: '5.F', num: 107, unit: 11, order: 7, slug: 'walk-three-fourths-five-eighths',
    standard: '5.NF.A.2', difficulty: 2,
    prompt: 'Ana walked $\\frac{3}{4}$ mile to the park and then $\\frac{5}{8}$ mile to her friend\'s house. How far did she walk in all?',
    answerType: 'fraction', primaryAnswer: '11/8', alternativeAnswers: ['1 3/8', '1.375'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You cannot add fourths and eighths until the pieces are the same size.' },
      { level: 'guide', text: 'Eighths are half the size of fourths: $\\frac{3}{4} = \\frac{6}{8}$.' },
      { level: 'reveal', text: '$\\frac{6}{8} + \\frac{5}{8} = \\frac{11}{8} = 1\\frac{3}{8}$ miles.' },
    ],
    explanation: [
      'Rewrite $\\frac{3}{4}$ with a denominator of $8$: multiply top and bottom by $2$ to get $\\frac{6}{8}$.',
      'Now the pieces match, so add the numerators: $\\frac{6}{8} + \\frac{5}{8} = \\frac{11}{8}$.',
      '$\\frac{8}{8}$ is one whole, so $\\frac{11}{8} = 1\\frac{3}{8}$.',
      'Ana walked $\\frac{11}{8}$ miles, or $1\\frac{3}{8}$ miles.',
    ],
    alternativeExplanations: [
      { title: 'Estimate to check', steps: ['$\\frac{3}{4}$ is a bit less than $1$ and $\\frac{5}{8}$ is a bit more than $\\frac{1}{2}$.', 'The sum should land between $1$ and $1\\frac{1}{2}$ — and $1\\frac{3}{8}$ does ✓'] },
    ],
    tags: ['MAP-practice', 'fractions', 'addition', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: '5.F', num: 108, unit: 11, order: 8, slug: 'estimate-mixed-number-sum-mc',
    standard: '5.NF.A.2', difficulty: 2,
    prompt: 'Without adding exactly, $2\\frac{7}{8} + 1\\frac{1}{12}$ is **closest** to which whole number?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '3', correct: false },
      { id: 'B', label: '4', correct: true },
      { id: 'C', label: '5', correct: false },
      { id: 'D', label: '6', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Round each mixed number to the nearest whole number first.' },
      { level: 'guide', text: '$\\frac{7}{8}$ is nearly a whole, so $2\\frac{7}{8} \\approx 3$. And $\\frac{1}{12}$ is tiny, so $1\\frac{1}{12} \\approx 1$.' },
      { level: 'reveal', text: '$3 + 1 = 4$, so choose B.' },
    ],
    explanation: [
      '$\\frac{7}{8}$ is much closer to $1$ than to $0$, so $2\\frac{7}{8}$ rounds up to $3$.',
      '$\\frac{1}{12}$ is much closer to $0$ than to $1$, so $1\\frac{1}{12}$ rounds down to $1$.',
      '$3 + 1 = 4$, so the sum is closest to $4$ (choice B).',
      'The exact sum is about $3.96$, which really is nearest to $4$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Why not 3?', steps: ['Dropping both fractions gives $2 + 1 = 3$, but that throws away almost a whole from the $\\frac{7}{8}$.', 'Rounding each piece to its nearest whole is the fairer estimate, and it gives $4$.'] },
    ],
    tags: ['MAP-practice', 'estimation', 'fractions', 'mixed-numbers'], estimatedSeconds: 50,
  },
  {
    domain: '5.F', num: 109, unit: 11, order: 9, slug: 'two-tables-sandwich-share',
    standard: '5.NF.B.3', difficulty: 3,
    prompt: 'At a field-trip lunch, Table A shares $3$ sandwiches equally among $4$ kids. Table B shares $5$ sandwiches equally among $6$ kids. How much **more** sandwich does each kid at Table B get than each kid at Table A?',
    answerType: 'fraction', primaryAnswer: '1/12', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easier pair: $1$ sandwich among $2$ kids is $\\frac{1}{2}$ each, and $1$ sandwich among $4$ kids is $\\frac{1}{4}$ each. The difference is $\\frac{1}{2} - \\frac{1}{4} = \\frac{1}{4}$. Turn each sharing into a fraction, then subtract — same plan here.' },
      { level: 'nudge', text: 'Find each kid\'s share as a fraction first, then subtract the smaller share from the larger one.' },
      { level: 'guide', text: 'Table A: $3 \\div 4 = \\frac{3}{4}$. Table B: $5 \\div 6 = \\frac{5}{6}$. Now find a common denominator for $4$ and $6$.' },
      { level: 'reveal', text: 'Twelfths work: $\\frac{5}{6} = \\frac{10}{12}$ and $\\frac{3}{4} = \\frac{9}{12}$, so the difference is $\\frac{1}{12}$.' },
    ],
    explanation: [
      'Each sharing is a division written as a fraction: Table A gets $3 \\div 4 = \\frac{3}{4}$ per kid, and Table B gets $5 \\div 6 = \\frac{5}{6}$ per kid.',
      'To compare and subtract, rewrite both in twelfths: $\\frac{3}{4} = \\frac{9}{12}$ and $\\frac{5}{6} = \\frac{10}{12}$.',
      'Subtract: $\\frac{10}{12} - \\frac{9}{12} = \\frac{1}{12}$.',
      'Each kid at Table B gets $\\frac{1}{12}$ of a sandwich more.',
    ],
    alternativeExplanations: [
      { title: 'Decimal check', steps: ['$\\frac{3}{4} = 0.75$ and $\\frac{5}{6} \\approx 0.833$.', 'The gap is about $0.083$, and $\\frac{1}{12} \\approx 0.083$ ✓'] },
      { title: '⚠️ The trap here', steps: ['The most common wrong answer is $\\frac{2}{2} = 1$ or $\\frac{2}{12}$, from subtracting the sandwiches and the kids separately: $5 - 3 = 2$ and $6 - 4 = 2$.', 'You cannot subtract numerators and denominators like that — $\\frac{5}{6}$ and $\\frac{3}{4}$ are counting different-sized pieces.', 'Make the pieces the same size first ($\\frac{10}{12}$ and $\\frac{9}{12}$), then subtract only the numerators: $\\frac{1}{12}$.'] },
    ],
    tags: ['MAP-practice', 'fractions', 'division', 'multi-step', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: '5.F', num: 110, unit: 11, order: 10, slug: 'granola-share-then-eat-half',
    standard: '5.NF.A.2', difficulty: 3,
    prompt: 'Seven granola bars are shared equally among $4$ friends. Each friend immediately eats $\\frac{1}{2}$ of a bar. How much of a friend\'s share is left?',
    answerType: 'fraction', primaryAnswer: '5/4', alternativeAnswers: ['1 1/4', '1.25'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller numbers: $3$ bars among $2$ friends is $\\frac{3}{2}$ each, and eating $\\frac{1}{2}$ leaves $\\frac{3}{2} - \\frac{1}{2} = \\frac{2}{2} = 1$ bar. Share first as a fraction, then subtract what gets eaten — same two steps.' },
      { level: 'nudge', text: 'Step one is a sharing problem; step two is a subtraction.' },
      { level: 'guide', text: 'Each share is $7 \\div 4 = \\frac{7}{4}$. Now subtract $\\frac{1}{2}$, rewritten in fourths.' },
      { level: 'reveal', text: '$\\frac{1}{2} = \\frac{2}{4}$, so $\\frac{7}{4} - \\frac{2}{4} = \\frac{5}{4} = 1\\frac{1}{4}$ bars.' },
    ],
    explanation: [
      'Step 1 — the share: $7$ bars split among $4$ friends is $7 \\div 4 = \\frac{7}{4}$ of a bar each, which is $1\\frac{3}{4}$.',
      'Step 2 — subtract what is eaten. Rewrite $\\frac{1}{2}$ as $\\frac{2}{4}$ so the pieces match.',
      '$\\frac{7}{4} - \\frac{2}{4} = \\frac{5}{4}$.',
      'So $\\frac{5}{4}$ of a bar, or $1\\frac{1}{4}$ bars, is left of each friend\'s share.',
    ],
    alternativeExplanations: [
      { title: 'Decimal check', steps: ['$\\frac{7}{4} = 1.75$ bars each.', '$1.75 - 0.5 = 1.25$, and $1.25 = \\frac{5}{4}$ ✓'] },
      { title: '⚠️ The trap here', steps: ['A frequent wrong answer is $\\frac{6}{4}$, from subtracting $\\frac{1}{2}$ as if it were $\\frac{1}{4}$ — the denominators get copied instead of converted.', 'Another is $\\frac{7}{4} - \\frac{1}{2} = \\frac{6}{2}$, mixing the pieces up completely.', 'Halves are twice as big as fourths, so $\\frac{1}{2} = \\frac{2}{4}$; subtracting that leaves $\\frac{5}{4}$.'] },
    ],
    tags: ['MAP-practice', 'fractions', 'multi-step', 'word-problem'], estimatedSeconds: 75,
  },
];
