import type { SeedProblem } from './types';

// 6.EE — Expressions & Equations. Adds 52 new (5 to U1, 7 to U2, 10 each to U3-U6).

export const problems6EE: SeedProblem[] = [
  // ---------------- UNIT 1 — Numerical expressions & intro (orders 6-10) ----------------
  {
    domain: '6.EE', num: 9, unit: 1, order: 6, slug: 'exponent-2',
    standard: '6.EE.A.1', difficulty: 1,
    prompt: 'Evaluate $5^2$.',
    answerType: 'numeric', primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$5^2$ means $5$ times $5$.' },
      { level: 'guide', text: '$5 \\times 5 = ?$' },
      { level: 'reveal', text: '$25$.' },
    ],
    explanation: ['$5^2 = 5 \\times 5 = 25$.'],
    tags: ['exponent'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 10, unit: 1, order: 7, slug: 'order-ops',
    standard: '6.EE.A.1', difficulty: 2,
    prompt: 'Evaluate: $3 + 2 \\times 4$.',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiplication before addition (PEMDAS).' },
      { level: 'guide', text: '$2 \\times 4 = 8$, then $3 + 8$.' },
      { level: 'reveal', text: '$11$.' },
    ],
    explanation: ['Order: multiply first.', '$2 \\times 4 = 8$.', '$3 + 8 = 11$.'],
    tags: ['order-of-ops'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 11, unit: 1, order: 8, slug: 'order-ops-parens',
    standard: '6.EE.A.1', difficulty: 2,
    prompt: 'Evaluate: $(6 + 2) \\times 3$.',
    answerType: 'numeric', primaryAnswer: '24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Parentheses first.' },
      { level: 'guide', text: '$6 + 2 = 8$, then $8 \\times 3$.' },
      { level: 'reveal', text: '$24$.' },
    ],
    explanation: ['$(6 + 2) = 8$.', '$8 \\times 3 = 24$.'],
    tags: ['order-of-ops', 'parens'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 12, unit: 1, order: 9, slug: 'expo-3-cube',
    standard: '6.EE.A.1', difficulty: 2,
    prompt: 'Evaluate $2^3$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$2^3 = 2 \\times 2 \\times 2$.' },
      { level: 'guide', text: '$2 \\times 2 = 4$, then $4 \\times 2$.' },
      { level: 'reveal', text: '$4 \\times 2 = 8$.' },
    ],
    explanation: ['$2^3 = 2 \\cdot 2 \\cdot 2 = 8$.'],
    tags: ['exponent'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 13, unit: 1, order: 10, slug: 'order-ops-mix',
    standard: '6.EE.A.1', difficulty: 3,
    prompt: 'Evaluate: $5 + 2^3 - 4$.',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Exponents before addition/subtraction.' },
      { level: 'guide', text: '$2^3 = 8$. Now $5 + 8 - 4$.' },
      { level: 'reveal', text: '$5 + 8 - 4 = 9$.' },
    ],
    explanation: ['$2^3 = 8$.', '$5 + 8 - 4 = 9$.'],
    tags: ['MAP-practice', 'order-of-ops'], estimatedSeconds: 50,
  },

  // ---------------- UNIT 2 — Variables & evaluating (orders 4-10) ----------------
  {
    domain: '6.EE', num: 14, unit: 2, order: 4, slug: 'eval-var-1',
    standard: '6.EE.A.2.c', difficulty: 1,
    prompt: 'If $x = 6$, what is $x + 4$?',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Replace $x$ with $6$.' },
      { level: 'guide', text: '$6 + 4$.' },
      { level: 'reveal', text: '$10$.' },
    ],
    explanation: ['Substitute $x = 6$: $6 + 4 = 10$.'],
    tags: ['evaluate'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 15, unit: 2, order: 5, slug: 'eval-var-mult',
    standard: '6.EE.A.2.c', difficulty: 1,
    prompt: 'If $y = 4$, what is $5y$?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$5y$ means $5$ times $y$.' },
      { level: 'guide', text: '$5 \\times 4$.' },
      { level: 'reveal', text: '$20$.' },
    ],
    explanation: ['$5y = 5 \\times 4 = 20$.'],
    tags: ['evaluate'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 16, unit: 2, order: 6, slug: 'translate-3x',
    standard: '6.EE.A.2.a', difficulty: 2,
    prompt: 'Write an expression for "$5$ more than $3$ times a number $n$".',
    answerType: 'short-text',
    primaryAnswer: '3n+5', alternativeAnswers: ['3n + 5', '5 + 3n', '5+3n', '3*n+5'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"More than" means addition.' },
      { level: 'guide', text: '"$3$ times $n$" is $3n$. Then add $5$.' },
      { level: 'reveal', text: '$3n + 5$.' },
    ],
    explanation: ['"$3$ times $n$" $\\to 3n$.', '"$5$ more than that" $\\to 3n + 5$.'],
    tags: ['CA', 'translate'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 17, unit: 2, order: 7, slug: 'parts-expr',
    standard: '6.EE.A.2.b', difficulty: 2,
    prompt: 'In the expression $7x + 4$, what is the **coefficient** of $x$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The coefficient is the number multiplied by the variable.' },
      { level: 'guide', text: 'In $7x$, what multiplies $x$?' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['Coefficient of $x$ in $7x + 4$ is $7$.'],
    tags: ['vocabulary'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 18, unit: 2, order: 8, slug: 'eval-two-vars',
    standard: '6.EE.A.2.c', difficulty: 2,
    prompt: 'If $a = 3$ and $b = 5$, evaluate $2a + b$.',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Replace $a$ with $3$ and $b$ with $5$.' },
      { level: 'guide', text: '$2(3) + 5 = 6 + 5$.' },
      { level: 'reveal', text: '$11$.' },
    ],
    explanation: ['Substitute: $2(3) + 5 = 6 + 5 = 11$.'],
    tags: ['evaluate'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 19, unit: 2, order: 9, slug: 'expr-from-words',
    standard: '6.EE.A.2.a', difficulty: 2,
    prompt: 'Write an expression for "$x$ decreased by $9$".',
    answerType: 'short-text',
    primaryAnswer: 'x-9', alternativeAnswers: ['x - 9'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Decreased by" means subtraction.' },
      { level: 'guide', text: '$x - 9$.' },
      { level: 'reveal', text: '$x - 9$.' },
    ],
    explanation: ['Decreased by $9$: subtract $9$ from $x$.', '$x - 9$.'],
    tags: ['translate'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 20, unit: 2, order: 10, slug: 'eval-with-exp',
    standard: '6.EE.A.2.c', difficulty: 3,
    prompt: 'If $x = 3$, evaluate $x^2 + 2x$.',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute, then evaluate exponent before multiplication.' },
      { level: 'guide', text: '$3^2 + 2(3) = 9 + 6$.' },
      { level: 'reveal', text: '$9 + 6 = 15$.' },
    ],
    explanation: ['$x^2 = 9$. $2x = 6$.', 'Sum: $15$.'],
    tags: ['MAP-practice', 'evaluate', 'exponent'], estimatedSeconds: 60,
  },

  // ---------------- UNIT 3 — Equivalent expressions (1-10) ----------------
  {
    domain: '6.EE', num: 21, unit: 3, order: 1, slug: 'distribute-2',
    standard: '6.EE.A.3', difficulty: 1,
    prompt: 'Use the distributive property: $3(x + 4)$.',
    answerType: 'short-text',
    primaryAnswer: '3x+12', alternativeAnswers: ['3x + 12', '12+3x'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply $3$ by each term inside.' },
      { level: 'guide', text: '$3 \\cdot x + 3 \\cdot 4$.' },
      { level: 'reveal', text: '$3x + 12$.' },
    ],
    explanation: ['$3(x + 4) = 3x + 12$.'],
    tags: ['distributive'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 22, unit: 3, order: 2, slug: 'combine-like',
    standard: '6.EE.A.3', difficulty: 1,
    prompt: 'Simplify: $4x + 3x$.',
    answerType: 'short-text', primaryAnswer: '7x', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add the coefficients.' },
      { level: 'guide', text: '$4 + 3 = 7$.' },
      { level: 'reveal', text: '$7x$.' },
    ],
    explanation: ['$4x + 3x = (4 + 3)x = 7x$.'],
    tags: ['combine-like'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 23, unit: 3, order: 3, slug: 'distribute-5',
    standard: '6.EE.A.3', difficulty: 2,
    prompt: 'Expand $5(2x + 3)$.',
    answerType: 'short-text',
    primaryAnswer: '10x+15', alternativeAnswers: ['10x + 15'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Distribute $5$ to both terms.' },
      { level: 'guide', text: '$5 \\cdot 2x = 10x$, $5 \\cdot 3 = 15$.' },
      { level: 'reveal', text: '$10x + 15$.' },
    ],
    explanation: ['$5(2x + 3) = 10x + 15$.'],
    tags: ['distributive'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 24, unit: 3, order: 4, slug: 'combine-and-constant',
    standard: '6.EE.A.3', difficulty: 2,
    prompt: 'Simplify: $2x + 5 + 3x + 4$.',
    answerType: 'short-text',
    primaryAnswer: '5x+9', alternativeAnswers: ['5x + 9'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Combine $x$-terms; combine constants.' },
      { level: 'guide', text: '$2x + 3x = 5x$, $5 + 4 = 9$.' },
      { level: 'reveal', text: '$5x + 9$.' },
    ],
    explanation: ['$x$-terms: $2x + 3x = 5x$.', 'Constants: $5 + 4 = 9$.', '$5x + 9$.'],
    tags: ['CA', 'combine-like'], estimatedSeconds: 50,
  },
  {
    domain: '6.EE', num: 25, unit: 3, order: 5, slug: 'verify-equiv',
    standard: '6.EE.A.4', difficulty: 2,
    prompt: 'Is $2(x + 3)$ equivalent to $2x + 6$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Yes', correct: true },
      { id: 'B', label: 'No', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Apply the distributive property.' },
      { level: 'guide', text: '$2(x + 3) = 2x + 6$.' },
      { level: 'reveal', text: 'They match. Yes.' },
    ],
    explanation: ['$2(x + 3) = 2x + 6$.', 'They are equivalent.'],
    tags: ['equivalent'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 26, unit: 3, order: 6, slug: 'factor-out',
    standard: '6.EE.A.3', difficulty: 3,
    prompt: 'Factor $6x + 9$ using the GCF.',
    answerType: 'short-text',
    primaryAnswer: '3(2x+3)', alternativeAnswers: ['3(2x + 3)', '3 (2x+3)'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'GCF of $6$ and $9$.' },
      { level: 'guide', text: 'GCF is $3$. Divide each: $6x/3 = 2x$, $9/3 = 3$.' },
      { level: 'reveal', text: '$3(2x + 3)$.' },
    ],
    explanation: ['GCF$(6, 9) = 3$.', 'Factor: $3 \\cdot 2x + 3 \\cdot 3 = 3(2x + 3)$.'],
    tags: ['CA', 'factor'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 27, unit: 3, order: 7, slug: 'distribute-neg',
    standard: '6.EE.A.3', difficulty: 2,
    prompt: 'Expand $4(x + 7)$.',
    answerType: 'short-text',
    primaryAnswer: '4x+28', alternativeAnswers: ['4x + 28'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply $4$ by each.' },
      { level: 'guide', text: '$4x + 4 \\cdot 7$.' },
      { level: 'reveal', text: '$4x + 28$.' },
    ],
    explanation: ['$4(x + 7) = 4x + 28$.'],
    tags: ['distributive'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 28, unit: 3, order: 8, slug: 'simplify-multi',
    standard: '6.EE.A.3', difficulty: 3,
    prompt: 'Simplify: $3x + 2(x + 4)$.',
    answerType: 'short-text',
    primaryAnswer: '5x+8', alternativeAnswers: ['5x + 8'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Distribute first, then combine.' },
      { level: 'guide', text: '$3x + 2x + 8$.' },
      { level: 'reveal', text: '$5x + 8$.' },
    ],
    explanation: ['$2(x + 4) = 2x + 8$.', '$3x + 2x + 8 = 5x + 8$.'],
    tags: ['MAP-practice', 'simplify'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 29, unit: 3, order: 9, slug: 'mc-equiv-test',
    standard: '6.EE.A.4', difficulty: 2,
    prompt: 'Which is equivalent to $3(x + 2)$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$3x + 2$', correct: false },
      { id: 'B', label: '$x + 6$', correct: false },
      { id: 'C', label: '$3x + 6$', correct: true },
      { id: 'D', label: '$3x + 5$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Distribute the $3$.' },
      { level: 'guide', text: '$3 \\cdot x + 3 \\cdot 2 = ?$' },
      { level: 'reveal', text: '$3x + 6$.' },
    ],
    explanation: ['$3(x + 2) = 3x + 6$.'],
    tags: ['distributive', 'equivalent'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 30, unit: 3, order: 10, slug: 'combine-mix',
    standard: '6.EE.A.3', difficulty: 3,
    prompt: 'Simplify: $5y - 2y + 3$.',
    answerType: 'short-text',
    primaryAnswer: '3y+3', alternativeAnswers: ['3y + 3'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Combine $y$-terms.' },
      { level: 'guide', text: '$5y - 2y = 3y$.' },
      { level: 'reveal', text: '$3y + 3$.' },
    ],
    explanation: ['$5y - 2y = 3y$.', 'Constant: $+3$.', '$3y + 3$.'],
    tags: ['combine-like'], estimatedSeconds: 45,
  },

  // ---------------- UNIT 4 — One-step equations (1-10) ----------------
  {
    domain: '6.EE', num: 31, unit: 4, order: 1, slug: 'solve-add',
    standard: '6.EE.B.7', difficulty: 1,
    prompt: 'Solve: $x + 5 = 12$.',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Subtract $5$ from both sides.' },
      { level: 'guide', text: '$x = 12 - 5$.' },
      { level: 'reveal', text: '$x = 7$.' },
    ],
    explanation: ['$x + 5 = 12 \\Rightarrow x = 12 - 5 = 7$.'],
    tags: ['solve'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 32, unit: 4, order: 2, slug: 'solve-sub',
    standard: '6.EE.B.7', difficulty: 1,
    prompt: 'Solve: $x - 4 = 9$.',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add $4$ to both sides.' },
      { level: 'guide', text: '$x = 9 + 4$.' },
      { level: 'reveal', text: '$x = 13$.' },
    ],
    explanation: ['$x - 4 = 9 \\Rightarrow x = 13$.'],
    tags: ['solve'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 33, unit: 4, order: 3, slug: 'solve-mult',
    standard: '6.EE.B.7', difficulty: 1,
    prompt: 'Solve: $3x = 24$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide both sides by $3$.' },
      { level: 'guide', text: '$x = 24 / 3$.' },
      { level: 'reveal', text: '$x = 8$.' },
    ],
    explanation: ['$3x = 24 \\Rightarrow x = 8$.'],
    tags: ['solve'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 34, unit: 4, order: 4, slug: 'solve-div',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $\\frac{x}{4} = 5$.',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply both sides by $4$.' },
      { level: 'guide', text: '$x = 5 \\times 4$.' },
      { level: 'reveal', text: '$x = 20$.' },
    ],
    explanation: ['$\\frac{x}{4} = 5 \\Rightarrow x = 20$.'],
    tags: ['solve'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 35, unit: 4, order: 5, slug: 'solve-mc',
    standard: '6.EE.B.5', difficulty: 1,
    prompt: 'Which value makes $x + 6 = 10$ true?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$2$', correct: false },
      { id: 'B', label: '$4$', correct: true },
      { id: 'C', label: '$6$', correct: false },
      { id: 'D', label: '$16$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Try each. Which one makes left side equal $10$?' },
      { level: 'guide', text: '$4 + 6 = 10$. ✓' },
      { level: 'reveal', text: 'B.' },
    ],
    explanation: ['Substitute each into $x + 6 = 10$.', '$4 + 6 = 10$ ✓.'],
    tags: ['check-solution'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 36, unit: 4, order: 6, slug: 'word-equation',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Mia has some marbles. Tom gives her $7$ more and now she has $20$. How many did she have before?',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Let $x$ = before. $x + 7 = 20$.' },
      { level: 'guide', text: 'Solve: $x = 20 - 7$.' },
      { level: 'reveal', text: '$x = 13$.' },
    ],
    explanation: ['Set up: $x + 7 = 20$.', '$x = 13$ marbles.'],
    tags: ['CA', 'word', 'solve'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 37, unit: 4, order: 7, slug: 'solve-decimal',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $0.5x = 4$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide both sides by $0.5$.' },
      { level: 'guide', text: '$x = 4 / 0.5$.' },
      { level: 'reveal', text: '$x = 8$.' },
    ],
    explanation: ['$0.5x = 4 \\Rightarrow x = 8$.'],
    tags: ['solve', 'decimal'], estimatedSeconds: 50,
  },
  {
    domain: '6.EE', num: 38, unit: 4, order: 8, slug: 'solve-fraction-coef',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'Solve: $\\frac{2}{3} x = 10$.',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply both sides by $\\frac{3}{2}$.' },
      { level: 'guide', text: '$x = 10 \\cdot \\frac{3}{2}$.' },
      { level: 'reveal', text: '$x = 15$.' },
    ],
    explanation: ['$\\frac{2}{3} x = 10$.', 'Multiply both sides by $\\frac{3}{2}$: $x = 15$.'],
    tags: ['MAP-practice', 'solve', 'fraction'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 39, unit: 4, order: 9, slug: 'word-divide',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'A box of cookies is shared equally by $5$ friends, each getting $4$ cookies. How many cookies in the box?',
    answerType: 'numeric', primaryAnswer: '20', alternativeAnswers: ['20 cookies'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Let $x$ = total. $\\frac{x}{5} = 4$.' },
      { level: 'guide', text: '$x = 4 \\cdot 5$.' },
      { level: 'reveal', text: '$x = 20$.' },
    ],
    explanation: ['Total $= 5 \\times 4 = 20$.'],
    tags: ['word', 'solve'], estimatedSeconds: 55,
  },
  {
    domain: '6.EE', num: 40, unit: 4, order: 10, slug: 'solve-zero',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $x + 12 = 12$.',
    answerType: 'numeric', primaryAnswer: '0', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Subtract $12$ from both sides.' },
      { level: 'guide', text: '$x = 12 - 12$.' },
      { level: 'reveal', text: '$x = 0$.' },
    ],
    explanation: ['$x + 12 = 12 \\Rightarrow x = 0$.'],
    tags: ['solve'], estimatedSeconds: 30,
  },

  // ---------------- UNIT 5 — Inequalities (1-10) ----------------
  {
    domain: '6.EE', num: 41, unit: 5, order: 1, slug: 'ineq-graph',
    standard: '6.EE.B.8', difficulty: 1,
    prompt: 'On a number line, $x > 3$ has an open or closed circle at $3$?',
    answerType: 'short-text',
    primaryAnswer: 'open', alternativeAnswers: ['open circle'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$>$ is strict (not equal).' },
      { level: 'guide', text: 'Open circle = strict inequality.' },
      { level: 'reveal', text: 'Open.' },
    ],
    explanation: ['$>$ excludes $3$.', 'Open circle at $3$.'],
    tags: ['inequality'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 42, unit: 5, order: 2, slug: 'ineq-closed',
    standard: '6.EE.B.8', difficulty: 1,
    prompt: 'For $x \\geq 5$, is the circle at $5$ open or closed?',
    answerType: 'short-text',
    primaryAnswer: 'closed', alternativeAnswers: ['closed circle', 'solid'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$\\geq$ includes equality.' },
      { level: 'guide', text: 'Closed (filled) circle when "or equal to".' },
      { level: 'reveal', text: 'Closed.' },
    ],
    explanation: ['$\\geq$ includes $5$.', 'Closed (solid) circle at $5$.'],
    tags: ['inequality'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 43, unit: 5, order: 3, slug: 'ineq-write',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'Write an inequality: "$x$ is at most $7$".',
    answerType: 'short-text',
    primaryAnswer: 'x≤7', alternativeAnswers: ['x <= 7', 'x ≤ 7'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"At most" means "less than or equal to".' },
      { level: 'guide', text: '$x$ ≤ ?' },
      { level: 'reveal', text: '$x \\leq 7$.' },
    ],
    explanation: ['"At most $7$" means $x$ can be up to $7$ — i.e., $x \\leq 7$.'],
    tags: ['inequality', 'translate'], estimatedSeconds: 50,
  },
  {
    domain: '6.EE', num: 44, unit: 5, order: 4, slug: 'ineq-at-least',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'Write an inequality: "$y$ is at least $10$".',
    answerType: 'short-text',
    primaryAnswer: 'y≥10', alternativeAnswers: ['y >= 10', 'y ≥ 10'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"At least" means "greater than or equal to".' },
      { level: 'guide', text: '$y$ ≥ ?' },
      { level: 'reveal', text: '$y \\geq 10$.' },
    ],
    explanation: ['"At least $10$" means $y \\geq 10$.'],
    tags: ['inequality', 'translate'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 45, unit: 5, order: 5, slug: 'ineq-check',
    standard: '6.EE.B.5', difficulty: 2,
    prompt: 'Is $x = 4$ a solution to $x > 4$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Yes', correct: false },
      { id: 'B', label: 'No', correct: true },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '$>$ means strictly greater (not equal).' },
      { level: 'guide', text: 'Is $4 > 4$ true?' },
      { level: 'reveal', text: 'No — they\'re equal, not greater.' },
    ],
    explanation: ['$x > 4$ excludes $4$.', '$4$ is not a solution.'],
    tags: ['inequality', 'check'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 46, unit: 5, order: 6, slug: 'ineq-word',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'A roller coaster has a height requirement of $48$ inches. Write an inequality showing acceptable heights $h$.',
    answerType: 'short-text',
    primaryAnswer: 'h≥48', alternativeAnswers: ['h >= 48', 'h ≥ 48'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"At least $48$" — riders need $h \\geq 48$.' },
      { level: 'guide', text: '$h \\geq ?$' },
      { level: 'reveal', text: '$h \\geq 48$.' },
    ],
    explanation: ['Riders must be at least $48$ inches: $h \\geq 48$.'],
    tags: ['CA', 'inequality', 'word'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 47, unit: 5, order: 7, slug: 'ineq-pick-soln',
    standard: '6.EE.B.5', difficulty: 2,
    prompt: 'Which is a solution to $x \\leq 3$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$5$', correct: false },
      { id: 'B', label: '$4$', correct: false },
      { id: 'C', label: '$3$', correct: true },
      { id: 'D', label: '$7$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '$x \\leq 3$ means $x$ can be $3$ or less.' },
      { level: 'guide', text: 'Is $3 \\leq 3$ true? Yes.' },
      { level: 'reveal', text: 'C.' },
    ],
    explanation: ['$x \\leq 3$ allows values $\\leq 3$.', '$3 \\leq 3$ ✓. Answer: C.'],
    tags: ['inequality', 'check'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 48, unit: 5, order: 8, slug: 'ineq-direction',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'On a number line for $x < -2$, the arrow points which direction?',
    answerType: 'short-text',
    primaryAnswer: 'left', alternativeAnswers: ['Left', 'negative direction'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$<$ means smaller — to the left.' },
      { level: 'guide', text: 'From $-2$, smaller values are to the left.' },
      { level: 'reveal', text: 'Left.' },
    ],
    explanation: ['$x < -2$ → values smaller than $-2$, which are to the left.'],
    tags: ['inequality'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 49, unit: 5, order: 9, slug: 'ineq-write-less',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'A bus can hold less than $30$ riders. Write an inequality for the number $n$ of riders.',
    answerType: 'short-text',
    primaryAnswer: 'n<30', alternativeAnswers: ['n < 30'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Less than" means $<$.' },
      { level: 'guide', text: '$n < 30$.' },
      { level: 'reveal', text: '$n < 30$.' },
    ],
    explanation: ['"Less than $30$" → $n < 30$.'],
    tags: ['MAP-practice', 'inequality', 'translate'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 50, unit: 5, order: 10, slug: 'ineq-multiple',
    standard: '6.EE.B.5', difficulty: 3,
    prompt: 'How many of these are solutions to $x \\geq 5$: $\\{2, 5, 6, 4, 9\\}$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count values that are $\\geq 5$.' },
      { level: 'guide', text: '$5, 6, 9$ all satisfy.' },
      { level: 'reveal', text: '$3$ solutions.' },
    ],
    explanation: ['$5 \\geq 5$ ✓; $6 \\geq 5$ ✓; $9 \\geq 5$ ✓.', 'Total: $3$.'],
    tags: ['inequality'], estimatedSeconds: 55,
  },

  // ---------------- UNIT 6 — Two variables / Mixed (1-10) ----------------
  {
    domain: '6.EE', num: 51, unit: 6, order: 1, slug: 'two-var-table',
    standard: '6.EE.C.9', difficulty: 1,
    prompt: 'If $y = 2x$, what is $y$ when $x = 5$?',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $x = 5$.' },
      { level: 'guide', text: '$y = 2 \\cdot 5$.' },
      { level: 'reveal', text: '$y = 10$.' },
    ],
    explanation: ['$y = 2x = 2(5) = 10$.'],
    tags: ['two-vars'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 52, unit: 6, order: 2, slug: 'two-var-x',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'If $y = x + 7$ and $y = 12$, what is $x$?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$x + 7 = 12$.' },
      { level: 'guide', text: '$x = 12 - 7$.' },
      { level: 'reveal', text: '$x = 5$.' },
    ],
    explanation: ['$x + 7 = 12 \\Rightarrow x = 5$.'],
    tags: ['two-vars'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 53, unit: 6, order: 3, slug: 'indep-dep',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'A cab charges \\$$3$ plus \\$$2$ per mile. Write the cost $c$ as a function of miles $m$.',
    answerType: 'short-text',
    primaryAnswer: 'c=2m+3', alternativeAnswers: ['c = 2m + 3', 'c=3+2m'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Start fee plus per-mile rate.' },
      { level: 'guide', text: '$c = 2m + 3$.' },
      { level: 'reveal', text: '$c = 2m + 3$.' },
    ],
    explanation: ['Base fee $3$ + per mile $2$ × $m$ miles.', '$c = 2m + 3$.'],
    tags: ['CA', 'two-vars', 'word'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 54, unit: 6, order: 4, slug: 'two-var-substitute',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'If $y = 3x + 1$, what is $y$ when $x = 4$?',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute and compute.' },
      { level: 'guide', text: '$y = 3(4) + 1$.' },
      { level: 'reveal', text: '$y = 12 + 1 = 13$.' },
    ],
    explanation: ['$y = 3(4) + 1 = 13$.'],
    tags: ['two-vars'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 55, unit: 6, order: 5, slug: 'mix-distribute',
    standard: '6.EE.A.3', difficulty: 2,
    prompt: 'Expand $2(3x - 4)$.',
    answerType: 'short-text',
    primaryAnswer: '6x-8', alternativeAnswers: ['6x - 8'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply $2$ by each term.' },
      { level: 'guide', text: '$2 \\cdot 3x - 2 \\cdot 4$.' },
      { level: 'reveal', text: '$6x - 8$.' },
    ],
    explanation: ['$2(3x - 4) = 6x - 8$.'],
    tags: ['distributive'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 56, unit: 6, order: 6, slug: 'mix-solve-word',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'Tickets cost $4$ each. With \\$$24$, you bought some tickets. How many?',
    answerType: 'numeric', primaryAnswer: '6', alternativeAnswers: ['6 tickets'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set up: $4t = 24$.' },
      { level: 'guide', text: '$t = 24 / 4$.' },
      { level: 'reveal', text: '$t = 6$.' },
    ],
    explanation: ['$4t = 24 \\Rightarrow t = 6$ tickets.'],
    tags: ['MAP-practice', 'solve', 'word'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 57, unit: 6, order: 7, slug: 'mix-pattern',
    standard: '6.EE.C.9', difficulty: 3,
    prompt: 'A pattern: $1 \\to 5$, $2 \\to 9$, $3 \\to 13$. What is the rule (as $y = $ expression)?',
    answerType: 'short-text',
    primaryAnswer: 'y=4x+1', alternativeAnswers: ['y = 4x + 1'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The output goes up by $4$ each time. What\'s the constant?' },
      { level: 'guide', text: 'When $x = 0$, $y$ would be $1$. So $y = 4x + 1$.' },
      { level: 'reveal', text: '$y = 4x + 1$.' },
    ],
    explanation: ['Rate of change: $4$.', 'When $x = 1$: $4(1) + 1 = 5$ ✓.', 'Rule: $y = 4x + 1$.'],
    tags: ['CA', 'two-vars', 'pattern'], estimatedSeconds: 90,
  },
  {
    domain: '6.EE', num: 58, unit: 6, order: 8, slug: 'mix-expression',
    standard: '6.EE.A.2.c', difficulty: 2,
    prompt: 'Evaluate $a^2 + b$ when $a = 4, b = 5$.',
    answerType: 'numeric', primaryAnswer: '21', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Compute exponent first.' },
      { level: 'guide', text: '$4^2 + 5 = 16 + 5$.' },
      { level: 'reveal', text: '$21$.' },
    ],
    explanation: ['$4^2 = 16$. $16 + 5 = 21$.'],
    tags: ['evaluate'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 59, unit: 6, order: 9, slug: 'mix-write-equation',
    standard: '6.EE.B.6', difficulty: 2,
    prompt: 'Write an equation: "A number $n$ plus $13$ equals $20$".',
    answerType: 'short-text',
    primaryAnswer: 'n+13=20', alternativeAnswers: ['n + 13 = 20', '13+n=20'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Translate word for word.' },
      { level: 'guide', text: '$n + 13 = 20$.' },
      { level: 'reveal', text: '$n + 13 = 20$.' },
    ],
    explanation: ['$n$ plus $13$ equals $20$: $n + 13 = 20$.'],
    tags: ['translate'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 60, unit: 6, order: 10, slug: 'mix-two-step',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'Solve: $2x + 3 = 11$.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Subtract $3$ first.' },
      { level: 'guide', text: '$2x = 8$. Now divide by $2$.' },
      { level: 'reveal', text: '$x = 4$.' },
    ],
    explanation: ['$2x + 3 = 11$.', '$2x = 8$.', '$x = 4$.'],
    tags: ['CA', 'solve'], estimatedSeconds: 60,
  },

  // ============================================================
  // UNIT 7 — Parts of expressions & evaluating II (6.EE.A.2.a/b/c)
  // ============================================================
  {
    domain: '6.EE', num: 61, unit: 7, order: 1, slug: 'coef-of-4y',
    standard: '6.EE.A.2.b', difficulty: 1,
    prompt: 'What is the **coefficient** of $y$ in the term $4y$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The coefficient is the number multiplied by the variable.' },
      { level: 'guide', text: 'In $4y$, the number in front of $y$ is the coefficient.' },
      { level: 'reveal', text: '$4$.' },
    ],
    explanation: ['$4y$ means $4 \\times y$.', 'The coefficient is $4$.'],
    tags: ['expression', 'parts'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 62, unit: 7, order: 2, slug: 'constant-of-7-3x',
    standard: '6.EE.A.2.b', difficulty: 1,
    prompt: 'What is the **constant term** in the expression $7 + 3x$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A constant has no variable.' },
      { level: 'guide', text: 'In $7 + 3x$, $3x$ has $x$; $7$ does not.' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['A constant term contains no variable.', 'In $7 + 3x$, the constant is $7$.'],
    tags: ['expression', 'parts'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 63, unit: 7, order: 3, slug: 'variable-in-5a-2',
    standard: '6.EE.A.2.b', difficulty: 2,
    prompt: 'What is the **variable** in $5a + 2$?',
    answerType: 'short-text', primaryAnswer: 'a',
    alternativeAnswers: ['A'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'A variable is a letter standing for a number.' },
      { level: 'guide', text: 'Which letter appears in $5a + 2$?' },
      { level: 'reveal', text: '$a$.' },
    ],
    explanation: ['The variable is the letter that represents an unknown.', 'In $5a + 2$, the variable is $a$.'],
    tags: ['expression', 'parts'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 64, unit: 7, order: 4, slug: 'count-terms',
    standard: '6.EE.A.2.b', difficulty: 2,
    prompt: 'How many **terms** are in $3x + 5 - 2y$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Terms are separated by $+$ or $-$ signs.' },
      { level: 'guide', text: 'Identify each piece: $3x$, $5$, $-2y$.' },
      { level: 'reveal', text: '$3$ terms.' },
    ],
    explanation: ['Terms in $3x + 5 - 2y$: $3x$, $5$, and $-2y$.', 'Count: $3$.'],
    tags: ['expression', 'parts'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 65, unit: 7, order: 5, slug: 'eval-3a-2-at-4',
    standard: '6.EE.A.2.c', difficulty: 2,
    prompt: 'Evaluate $3a + 2$ when $a = 4$.',
    answerType: 'numeric', primaryAnswer: '14', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $4$ in place of $a$.' },
      { level: 'guide', text: '$3(4) + 2$.' },
      { level: 'reveal', text: '$12 + 2 = 14$.' },
    ],
    explanation: ['$3a + 2$ with $a = 4$: $3(4) + 2$.', '$12 + 2 = 14$.'],
    tags: ['evaluate'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 66, unit: 7, order: 6, slug: 'eval-5x-7-at-3',
    standard: '6.EE.A.2.c', difficulty: 2,
    prompt: 'Evaluate $5x - 7$ when $x = 3$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $3$ for $x$, then compute.' },
      { level: 'guide', text: '$5(3) - 7$.' },
      { level: 'reveal', text: '$15 - 7 = 8$.' },
    ],
    explanation: ['$5x - 7$ with $x = 3$: $5(3) - 7 = 15 - 7 = 8$.'],
    tags: ['evaluate'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 67, unit: 7, order: 7, slug: 'eval-4-b-1-at-5',
    standard: '6.EE.A.2.c', difficulty: 2,
    prompt: 'Evaluate $4(b + 1)$ when $b = 5$.',
    answerType: 'numeric', primaryAnswer: '24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Parentheses first, then multiply.' },
      { level: 'guide', text: '$4(5 + 1) = 4 \\cdot 6$.' },
      { level: 'reveal', text: '$24$.' },
    ],
    explanation: ['$4(b + 1)$ with $b = 5$: $4(5 + 1) = 4 \\cdot 6 = 24$.'],
    alternativeExplanations: [
      { title: 'Distribute first', steps: ['$4(b + 1) = 4b + 4$.', 'With $b = 5$: $4(5) + 4 = 20 + 4 = 24$.'] },
    ],
    tags: ['evaluate', 'order-of-ops'], estimatedSeconds: 55,
  },
  {
    domain: '6.EE', num: 68, unit: 7, order: 8, slug: 'eval-xsq-1-at-4',
    standard: '6.EE.A.2.c', difficulty: 3,
    prompt: 'Evaluate $x^2 + 1$ when $x = 4$.',
    answerType: 'numeric', primaryAnswer: '17', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Square first, then add.' },
      { level: 'guide', text: '$4^2 = 16$, then $16 + 1$.' },
      { level: 'reveal', text: '$17$.' },
    ],
    explanation: ['$x^2 + 1$ with $x = 4$.', '$4^2 = 16$.', '$16 + 1 = 17$.'],
    tags: ['MAP-practice', 'evaluate', 'exponent'], estimatedSeconds: 55,
  },
  {
    domain: '6.EE', num: 69, unit: 7, order: 9, slug: 'eval-two-vars',
    standard: '6.EE.A.2.c', difficulty: 3,
    prompt: 'Evaluate $2x + y$ when $x = 3$ and $y = 7$.',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute both values.' },
      { level: 'guide', text: '$2(3) + 7$.' },
      { level: 'reveal', text: '$6 + 7 = 13$.' },
    ],
    explanation: ['$2x + y$ with $x = 3, y = 7$: $2(3) + 7 = 6 + 7 = 13$.'],
    tags: ['MAP-practice', 'evaluate', 'two-vars'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 70, unit: 7, order: 10, slug: 'eval-frac-expr',
    standard: '6.EE.A.2.c', difficulty: 3,
    prompt: 'Evaluate $\\dfrac{x + 5}{2}$ when $x = 7$.',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Compute the numerator first, then divide.' },
      { level: 'guide', text: 'Numerator: $7 + 5 = 12$. Then $12 \\div 2$.' },
      { level: 'reveal', text: '$6$.' },
    ],
    explanation: ['$x + 5 = 7 + 5 = 12$.', '$\\dfrac{12}{2} = 6$.'],
    tags: ['MAP-practice', 'evaluate', 'fraction'], estimatedSeconds: 65,
  },

  // ============================================================
  // UNIT 8 — Equivalence & checking solutions (6.EE.A.4, B.5)
  // ============================================================
  {
    domain: '6.EE', num: 71, unit: 8, order: 1, slug: 'equiv-2x6-2-x3',
    standard: '6.EE.A.4', difficulty: 1,
    prompt: 'Are $2x + 6$ and $2(x + 3)$ equivalent expressions? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'yes',
    alternativeAnswers: ['Yes', 'y'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Distribute and compare.' },
      { level: 'guide', text: '$2(x + 3) = 2 \\cdot x + 2 \\cdot 3 = 2x + 6$.' },
      { level: 'reveal', text: 'Same expression, so **yes**.' },
    ],
    explanation: ['Distribute: $2(x + 3) = 2x + 6$.', 'Both expressions equal $2x + 6$ → equivalent.'],
    tags: ['equivalent', 'distribute'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 72, unit: 8, order: 2, slug: 'check-x4-in-x5-9',
    standard: '6.EE.B.5', difficulty: 1,
    prompt: 'Is $x = 4$ a solution to $x + 5 = 9$? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'yes',
    alternativeAnswers: ['Yes', 'y'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Substitute $4$ for $x$ and check.' },
      { level: 'guide', text: '$4 + 5 = 9$. Is this true?' },
      { level: 'reveal', text: 'True → yes.' },
    ],
    explanation: ['Substitute $x = 4$: $4 + 5 = 9$. ✓', 'Yes — $x = 4$ is a solution.'],
    tags: ['check-solution'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 73, unit: 8, order: 3, slug: 'check-x3-in-2x-6',
    standard: '6.EE.B.5', difficulty: 2,
    prompt: 'Is $x = 3$ a solution to $2x = 6$? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'yes',
    alternativeAnswers: ['Yes', 'y'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Substitute and check.' },
      { level: 'guide', text: '$2(3) = 6$.' },
      { level: 'reveal', text: 'True → yes.' },
    ],
    explanation: ['Substitute $x = 3$: $2(3) = 6$. ✓', 'Yes.'],
    tags: ['check-solution'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 74, unit: 8, order: 4, slug: 'equiv-3x12-3-x4',
    standard: '6.EE.A.4', difficulty: 2,
    prompt: 'Are $3x + 12$ and $3(x + 4)$ equivalent? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'yes',
    alternativeAnswers: ['Yes', 'y'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Distribute the right side.' },
      { level: 'guide', text: '$3(x + 4) = 3x + 12$.' },
      { level: 'reveal', text: 'Yes — they\'re equal.' },
    ],
    explanation: ['$3(x + 4) = 3 \\cdot x + 3 \\cdot 4 = 3x + 12$.', 'Equivalent.'],
    alternativeExplanations: [
      { title: 'Test with a value', steps: ['Pick $x = 2$: $3(2) + 12 = 18$ and $3(2 + 4) = 3 \\cdot 6 = 18$. Match.', 'Try another, $x = 0$: both give $12$.'] },
    ],
    tags: ['equivalent', 'distribute'], estimatedSeconds: 50,
  },
  {
    domain: '6.EE', num: 75, unit: 8, order: 5, slug: 'equiv-5x-10-5-x-2',
    standard: '6.EE.A.4', difficulty: 2,
    prompt: 'Are $5x - 10$ and $5(x - 2)$ equivalent? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'yes',
    alternativeAnswers: ['Yes', 'y'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Distribute: $5(x - 2)$.' },
      { level: 'guide', text: '$5 \\cdot x - 5 \\cdot 2 = 5x - 10$.' },
      { level: 'reveal', text: 'Yes.' },
    ],
    explanation: ['$5(x - 2) = 5x - 10$.', 'Equivalent.'],
    tags: ['equivalent', 'distribute'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 76, unit: 8, order: 6, slug: 'check-x5-in-3x-4-11',
    standard: '6.EE.B.5', difficulty: 2,
    prompt: 'Is $x = 5$ a solution to $3x - 4 = 11$? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'yes',
    alternativeAnswers: ['Yes', 'y'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Substitute and simplify the left side.' },
      { level: 'guide', text: '$3(5) - 4 = 15 - 4 = 11$.' },
      { level: 'reveal', text: 'Matches $11$ → yes.' },
    ],
    explanation: ['$3(5) - 4 = 15 - 4 = 11$. ✓', 'Yes.'],
    tags: ['check-solution'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 77, unit: 8, order: 7, slug: 'check-y2-in-4y-1-10',
    standard: '6.EE.B.5', difficulty: 2,
    prompt: 'Is $y = 2$ a solution to $4y + 1 = 10$? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'no',
    alternativeAnswers: ['No', 'n'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Substitute and check the left side.' },
      { level: 'guide', text: '$4(2) + 1 = 8 + 1 = 9 \\ne 10$.' },
      { level: 'reveal', text: '$9 \\ne 10$ → no.' },
    ],
    explanation: ['$4(2) + 1 = 9$.', '$9 \\ne 10$ → not a solution.'],
    alternativeExplanations: [
      { title: 'Solve for $y$ instead', steps: ['$4y + 1 = 10 \\to 4y = 9 \\to y = 9/4 = 2.25$.', 'The true solution is $2.25$, not $2$. So $y = 2$ is not a solution.'] },
    ],
    tags: ['check-solution'], estimatedSeconds: 55,
  },
  {
    domain: '6.EE', num: 78, unit: 8, order: 8, slug: 'combine-4x-3-2x',
    standard: '6.EE.A.4', difficulty: 3,
    prompt: 'Combine like terms: $4x + 3 + 2x$.',
    answerType: 'short-text', primaryAnswer: '6x+3',
    alternativeAnswers: ['6x + 3', '3 + 6x'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Group the $x$ terms together.' },
      { level: 'guide', text: '$4x + 2x = 6x$.' },
      { level: 'reveal', text: '$6x + 3$.' },
    ],
    explanation: ['Like terms: $4x$ and $2x$ → $6x$.', 'Constant: $3$.', 'Result: $6x + 3$.'],
    tags: ['MAP-practice', 'combine-like-terms'], estimatedSeconds: 55,
  },
  {
    domain: '6.EE', num: 79, unit: 8, order: 9, slug: 'combine-7y-2-3y-5',
    standard: '6.EE.A.4', difficulty: 3,
    prompt: 'Combine like terms: $7y - 2 + 3y + 5$.',
    answerType: 'short-text', primaryAnswer: '10y+3',
    alternativeAnswers: ['10y + 3', '3 + 10y'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Combine $y$ terms, then combine numbers.' },
      { level: 'guide', text: '$7y + 3y = 10y$ and $-2 + 5 = 3$.' },
      { level: 'reveal', text: '$10y + 3$.' },
    ],
    explanation: ['$y$ terms: $7y + 3y = 10y$.', 'Constants: $-2 + 5 = 3$.', 'Result: $10y + 3$.'],
    alternativeExplanations: [
      { title: 'Rearrange first', steps: ['$7y - 2 + 3y + 5 = 7y + 3y - 2 + 5$.', '$10y + 3$.'] },
    ],
    tags: ['MAP-practice', 'combine-like-terms'], estimatedSeconds: 65,
  },
  {
    domain: '6.EE', num: 80, unit: 8, order: 10, slug: 'equiv-6-2x-5',
    standard: '6.EE.A.4', difficulty: 3,
    prompt: 'Which expression is equivalent to $6(2x + 5)$?',
    answerType: 'multiple-choice', primaryAnswer: 'B',
    choices: [
      { id: 'A', label: '$12x + 5$', correct: false },
      { id: 'B', label: '$12x + 30$', correct: true },
      { id: 'C', label: '$8x + 11$', correct: false },
      { id: 'D', label: '$6x + 30$', correct: false },
    ],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Use the distributive property.' },
      { level: 'guide', text: '$6 \\cdot 2x + 6 \\cdot 5$.' },
      { level: 'reveal', text: '$12x + 30$.' },
    ],
    explanation: ['$6(2x + 5) = 6 \\cdot 2x + 6 \\cdot 5 = 12x + 30$.'],
    alternativeExplanations: [
      { title: 'Test with $x = 1$', steps: ['$6(2 + 5) = 6 \\cdot 7 = 42$.', 'A: $17$. B: $42$ ✓. C: $19$. D: $36$.'] },
    ],
    tags: ['MAP-practice', 'distribute'], estimatedSeconds: 70,
  },

  // ============================================================
  // UNIT 9 — Equations & inequalities from stories (6.EE.B.6/7/8)
  // ============================================================
  {
    domain: '6.EE', num: 81, unit: 9, order: 1, slug: 'expr-25w',
    standard: '6.EE.B.6', difficulty: 1,
    prompt: 'Marcos saves \\$$25$ each week for $w$ weeks. Write an expression for his total savings (in dollars).',
    answerType: 'short-text', primaryAnswer: '25w',
    alternativeAnswers: ['25*w', '25 w', '25·w'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Total = dollars per week $\\times$ weeks.' },
      { level: 'guide', text: '$25 \\cdot w$.' },
      { level: 'reveal', text: '$25w$.' },
    ],
    explanation: ['Saving $25$ per week for $w$ weeks = $25 \\cdot w = 25w$ dollars.'],
    tags: ['expression', 'word'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 82, unit: 9, order: 2, slug: 'eq-n-6-14',
    standard: '6.EE.B.7', difficulty: 1,
    prompt: 'Write an equation for "A number plus $6$ equals $14$" using $n$ as the variable.',
    answerType: 'short-text', primaryAnswer: 'n+6=14',
    alternativeAnswers: ['n + 6 = 14', '6+n=14'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '"Plus" means $+$; "equals" means $=$.' },
      { level: 'guide', text: 'Write: number + 6 = 14.' },
      { level: 'reveal', text: '$n + 6 = 14$.' },
    ],
    explanation: ['"A number $n$ plus $6$" → $n + 6$.', '"Equals $14$" → $= 14$.', '$n + 6 = 14$.'],
    tags: ['equation', 'word'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 83, unit: 9, order: 3, slug: 'solve-x-5-12',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $x - 5 = 12$.',
    answerType: 'numeric', primaryAnswer: '17', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add $5$ to both sides.' },
      { level: 'guide', text: '$x = 12 + 5$.' },
      { level: 'reveal', text: '$17$.' },
    ],
    explanation: ['$x - 5 = 12$. Add $5$: $x = 17$.'],
    alternativeExplanations: [
      { title: 'Test the answer', steps: ['Check: $17 - 5 = 12$. ✓'] },
    ],
    tags: ['solve', 'one-step'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 84, unit: 9, order: 4, slug: 'solve-6x-48',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $6x = 48$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide both sides by $6$.' },
      { level: 'guide', text: '$x = 48 \\div 6$.' },
      { level: 'reveal', text: '$8$.' },
    ],
    explanation: ['$6x = 48$.', '$x = 48 \\div 6 = 8$.'],
    tags: ['solve', 'one-step'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 85, unit: 9, order: 5, slug: 'solve-x-over-4-9',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $\\dfrac{x}{4} = 9$.',
    answerType: 'numeric', primaryAnswer: '36', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply both sides by $4$.' },
      { level: 'guide', text: '$x = 9 \\cdot 4$.' },
      { level: 'reveal', text: '$36$.' },
    ],
    explanation: ['$\\dfrac{x}{4} = 9$. Multiply both sides by $4$: $x = 36$.'],
    alternativeExplanations: [
      { title: 'Check by dividing', steps: ['$36 \\div 4 = 9$. ✓'] },
    ],
    tags: ['solve', 'one-step'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 86, unit: 9, order: 6, slug: 'eq-twice-18',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Write an equation for "Twice a number is $18$" using $n$.',
    answerType: 'short-text', primaryAnswer: '2n=18',
    alternativeAnswers: ['2*n=18', '2 n = 18', '2 \\cdot n = 18'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '"Twice" means $\\times 2$.' },
      { level: 'guide', text: '$2n = 18$.' },
      { level: 'reveal', text: '$2n = 18$.' },
    ],
    explanation: ['"Twice $n$" → $2n$.', '"Is $18$" → $= 18$.', '$2n = 18$.'],
    tags: ['equation', 'word'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 87, unit: 9, order: 7, slug: 'ineq-more-than-5',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'Write an inequality for "$x$ is more than $5$".',
    answerType: 'short-text', primaryAnswer: 'x>5',
    alternativeAnswers: ['x > 5'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '"More than" means greater than.' },
      { level: 'guide', text: 'Use the symbol $>$.' },
      { level: 'reveal', text: '$x > 5$.' },
    ],
    explanation: ['"More than" → greater than → $>$.', '$x > 5$.'],
    tags: ['inequality', 'word'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 88, unit: 9, order: 8, slug: 'word-books-60',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'A book costs \\$$12$. With \\$$60$, how many books can you buy if you spend all the money?',
    answerType: 'numeric', primaryAnswer: '5',
    alternativeAnswers: ['5 books'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set up an equation: cost per book $\\times$ books $=$ total.' },
      { level: 'guide', text: '$12b = 60$, so $b = 60 \\div 12$.' },
      { level: 'reveal', text: '$60 \\div 12 = 5$.' },
    ],
    explanation: ['Let $b$ = number of books.', '$12b = 60$.', '$b = 60 \\div 12 = 5$ books.'],
    alternativeExplanations: [
      { title: 'Repeated subtraction', steps: ['$60 - 12 = 48$; one book bought.', '$48 - 12 = 36$; two.', '$36 - 12 = 24$; three.', '$24 - 12 = 12$; four.', '$12 - 12 = 0$; five.'] },
    ],
    tags: ['MAP-practice', 'word', 'equation'], estimatedSeconds: 75,
  },
  {
    domain: '6.EE', num: 89, unit: 9, order: 9, slug: 'solve-y-12-5',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'Solve: $y - 12 = 5$.',
    answerType: 'numeric', primaryAnswer: '17', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add $12$ to both sides.' },
      { level: 'guide', text: '$y = 5 + 12$.' },
      { level: 'reveal', text: '$17$.' },
    ],
    explanation: ['$y - 12 = 5$.', '$y = 5 + 12 = 17$.'],
    tags: ['MAP-practice', 'solve'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 90, unit: 9, order: 10, slug: 'word-cans-500',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'A school has $245$ cans and needs $500$. They will collect $c$ more cans to reach the goal. Write the equation and solve for $c$.',
    answerType: 'numeric', primaryAnswer: '255',
    alternativeAnswers: ['255 cans'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Current $+$ collected $=$ goal.' },
      { level: 'guide', text: '$245 + c = 500$. Subtract $245$.' },
      { level: 'reveal', text: '$c = 500 - 245 = 255$.' },
    ],
    explanation: ['Set up: $245 + c = 500$.', 'Subtract $245$ from both sides: $c = 255$.'],
    alternativeExplanations: [
      { title: 'Count up', steps: ['From $245$ to $500$: $245 + 5 = 250$; $250 + 250 = 500$.', '$5 + 250 = 255$ cans.'] },
    ],
    tags: ['MAP-practice', 'equation', 'word'], estimatedSeconds: 85,
  },

  // ============================================================
  // UNIT 10 — Two-variable relationships & challenge (6.EE.C.9 + mix)
  // ============================================================
  {
    domain: '6.EE', num: 91, unit: 10, order: 1, slug: '2v-y-4x-at-6',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'For $y = 4x$, find $y$ when $x = 6$.',
    answerType: 'numeric', primaryAnswer: '24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $6$ for $x$.' },
      { level: 'guide', text: '$y = 4 \\cdot 6$.' },
      { level: 'reveal', text: '$24$.' },
    ],
    explanation: ['$y = 4x$ with $x = 6$: $y = 24$.'],
    tags: ['two-vars'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 92, unit: 10, order: 2, slug: '2v-table-y-x-3',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'Fill in the table for $y = x + 3$ when $x = 1, 2, 3, 4$. List the $y$-values (comma-separated).',
    answerType: 'short-text', primaryAnswer: '4, 5, 6, 7',
    alternativeAnswers: ['4,5,6,7'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Plug each $x$ into $x + 3$.' },
      { level: 'guide', text: '$1+3, 2+3, 3+3, 4+3$.' },
      { level: 'reveal', text: '$4, 5, 6, 7$.' },
    ],
    explanation: ['$x = 1 \\to y = 4$.', '$x = 2 \\to y = 5$.', '$x = 3 \\to y = 6$.', '$x = 4 \\to y = 7$.'],
    tags: ['two-vars', 'table'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 93, unit: 10, order: 3, slug: '2v-y-2x-1-at-5',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'For $y = 2x + 1$, find $y$ when $x = 5$.',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $5$ and follow order of operations.' },
      { level: 'guide', text: '$2(5) + 1 = 10 + 1$.' },
      { level: 'reveal', text: '$11$.' },
    ],
    explanation: ['$y = 2x + 1$. Plug $x = 5$: $y = 2(5) + 1 = 11$.'],
    tags: ['two-vars', 'evaluate'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 94, unit: 10, order: 4, slug: '2v-c-12n',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'A movie ticket costs \\$$12$. The total cost $c = 12n$ for $n$ tickets. Find $c$ when $n = 7$.',
    answerType: 'numeric', primaryAnswer: '84',
    alternativeAnswers: ['$84'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply $12$ by $7$.' },
      { level: 'guide', text: '$12 \\times 7$.' },
      { level: 'reveal', text: '$84$.' },
    ],
    explanation: ['$c = 12n$ with $n = 7$: $c = 12 \\cdot 7 = 84$.', 'Cost: \\$$84$.'],
    tags: ['two-vars', 'word'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 95, unit: 10, order: 5, slug: '2v-y-3x-y-27',
    standard: '6.EE.C.9', difficulty: 3,
    prompt: 'For $y = 3x$, find $x$ when $y = 27$.',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You\'re solving $3x = 27$.' },
      { level: 'guide', text: 'Divide both sides by $3$.' },
      { level: 'reveal', text: '$x = 27 \\div 3 = 9$.' },
    ],
    explanation: ['Set $y = 27$: $27 = 3x$.', 'Divide: $x = 9$.'],
    tags: ['MAP-practice', 'two-vars', 'solve'], estimatedSeconds: 55,
  },
  {
    domain: '6.EE', num: 96, unit: 10, order: 6, slug: '2v-d-60t-25hr',
    standard: '6.EE.C.9', difficulty: 3,
    prompt: 'A car drives $d = 60t$ miles in $t$ hours. How far does it go in $2.5$ hours?',
    answerType: 'numeric', primaryAnswer: '150',
    alternativeAnswers: ['150 mi', '150 miles'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $t = 2.5$.' },
      { level: 'guide', text: '$d = 60 \\cdot 2.5$.' },
      { level: 'reveal', text: '$150$.' },
    ],
    explanation: ['$d = 60(2.5) = 150$ miles.'],
    alternativeExplanations: [
      { title: 'Break $2.5$ into $2 + 0.5$', steps: ['$60 \\cdot 2 = 120$.', '$60 \\cdot 0.5 = 30$.', '$120 + 30 = 150$.'] },
    ],
    tags: ['MAP-practice', 'two-vars', 'word'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 97, unit: 10, order: 7, slug: 'dist-4-2x-5',
    standard: '6.EE.A.3', difficulty: 3,
    prompt: 'Distribute: $4(2x + 5)$.',
    answerType: 'short-text', primaryAnswer: '8x+20',
    alternativeAnswers: ['8x + 20'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Multiply $4$ by each term inside.' },
      { level: 'guide', text: '$4 \\cdot 2x + 4 \\cdot 5$.' },
      { level: 'reveal', text: '$8x + 20$.' },
    ],
    explanation: ['$4(2x + 5) = 4 \\cdot 2x + 4 \\cdot 5 = 8x + 20$.'],
    tags: ['MAP-practice', 'distribute'], estimatedSeconds: 50,
  },
  {
    domain: '6.EE', num: 98, unit: 10, order: 8, slug: 'simplify-3x-2-x',
    standard: '6.EE.A.4', difficulty: 3,
    prompt: 'Simplify: $3(x + 2) - x$.',
    answerType: 'short-text', primaryAnswer: '2x+6',
    alternativeAnswers: ['2x + 6'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Distribute first, then combine.' },
      { level: 'guide', text: '$3(x + 2) = 3x + 6$. Then $3x + 6 - x$.' },
      { level: 'reveal', text: '$2x + 6$.' },
    ],
    explanation: ['Distribute: $3(x + 2) = 3x + 6$.', 'Combine: $3x + 6 - x = 2x + 6$.'],
    tags: ['MAP-practice', 'simplify'], estimatedSeconds: 65,
  },
  {
    domain: '6.EE', num: 99, unit: 10, order: 9, slug: 'word-pizza-share',
    standard: '6.EE.B.6', difficulty: 3,
    prompt: '$p$ friends share a pizza equally. Each gets $\\dfrac{1}{8}$ of the pizza. How many friends?',
    answerType: 'numeric', primaryAnswer: '8',
    alternativeAnswers: ['8 friends'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Each share is $1$ divided by how many friends.' },
      { level: 'guide', text: '$\\dfrac{1}{p} = \\dfrac{1}{8}$.' },
      { level: 'reveal', text: '$p = 8$.' },
    ],
    explanation: ['Each friend\'s share is $\\dfrac{1}{p}$. Set $\\dfrac{1}{p} = \\dfrac{1}{8}$.', '$p = 8$.'],
    alternativeExplanations: [
      { title: 'Eighths fit into a whole', steps: ['A whole pizza has $8$ eighths.', 'So $8$ friends each get one eighth.'] },
    ],
    tags: ['MAP-practice', 'fraction', 'word'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 100, unit: 10, order: 10, slug: '2v-y-5x-2-at-4',
    standard: '6.EE.C.9', difficulty: 3,
    prompt: 'For $y = 5x + 2$, find $y$ when $x = 4$.',
    answerType: 'numeric', primaryAnswer: '22', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $4$ for $x$.' },
      { level: 'guide', text: '$5(4) + 2$.' },
      { level: 'reveal', text: '$20 + 2 = 22$.' },
    ],
    explanation: ['$y = 5x + 2$ with $x = 4$: $5(4) + 2 = 22$.'],
    alternativeExplanations: [
      { title: 'Check the table', steps: ['$x = 0 \\to y = 2$.', 'Each $+1$ in $x$ adds $5$ to $y$.', 'From $0$ to $4$ is $4 \\cdot 5 = 20$. $y = 2 + 20 = 22$.'] },
    ],
    tags: ['MAP-practice', 'two-vars', 'evaluate'], estimatedSeconds: 60,
  },
];
