import type { SeedProblem } from './types';

// 6.EE — Expressions & Equations. Adds 52 new (5 to U1, 7 to U2, 10 each to U3-U6).

export const problems6EE: SeedProblem[] = [
  // ---------------- UNIT 1 — Numerical expressions & intro (orders 6-10) ----------------
  {
    domain: '6.EE', num: 9, unit: 1, order: 6, slug: 'exponent-2',
    standard: '6.EE.A.1', difficulty: 1,
    prompt: 'Evaluate $5^2$.',
    answerType: 'numeric', primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$5^2$ means $5$ times $5$.' },
      { level: 'guide', text: '$5 \\times 5 = ?$' },
      { level: 'reveal', text: '$25$.' },
    ],
    explanation: ['$5^2 = 5 \\times 5 = 25$.'],
    tags: ['exponent'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 10, unit: 1, order: 7, slug: 'order-ops',
    standard: '6.EE.A.1', difficulty: 2,
    prompt: 'Evaluate: $3 + 2 \\times 4$.',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiplication before addition (PEMDAS).' },
      { level: 'guide', text: '$2 \\times 4 = 8$, then $3 + 8$.' },
      { level: 'reveal', text: '$11$.' },
    ],
    explanation: ['Order: multiply first.', '$2 \\times 4 = 8$.', '$3 + 8 = 11$.'],
    tags: ['order-of-ops'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 11, unit: 1, order: 8, slug: 'order-ops-parens',
    standard: '6.EE.A.1', difficulty: 2,
    prompt: 'Evaluate: $(6 + 2) \\times 3$.',
    answerType: 'numeric', primaryAnswer: '24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Parentheses first.' },
      { level: 'guide', text: '$6 + 2 = 8$, then $8 \\times 3$.' },
      { level: 'reveal', text: '$24$.' },
    ],
    explanation: ['$(6 + 2) = 8$.', '$8 \\times 3 = 24$.'],
    tags: ['order-of-ops', 'parens'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 12, unit: 1, order: 9, slug: 'expo-3-cube',
    standard: '6.EE.A.1', difficulty: 2,
    prompt: 'Evaluate $2^3$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$2^3 = 2 \\times 2 \\times 2$.' },
      { level: 'guide', text: '$2 \\times 2 = 4$, then $4 \\times 2$.' },
      { level: 'reveal', text: '$4 \\times 2 = 8$.' },
    ],
    explanation: ['$2^3 = 2 \\cdot 2 \\cdot 2 = 8$.'],
    tags: ['exponent'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 13, unit: 1, order: 10, slug: 'order-ops-mix',
    standard: '6.EE.A.1', difficulty: 3,
    prompt: 'Evaluate: $5 + 2^3 - 4$.',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Exponents before addition/subtraction.' },
      { level: 'guide', text: '$2^3 = 8$. Now $5 + 8 - 4$.' },
      { level: 'reveal', text: '$5 + 8 - 4 = 9$.' },
    ],
    explanation: ['$2^3 = 8$.', '$5 + 8 - 4 = 9$.'],
    tags: ['MAP-practice', 'order-of-ops'], estimatedSeconds: 50,
  },

  // ---------------- UNIT 2 — Variables & evaluating (orders 4-10) ----------------
  {
    domain: '6.EE', num: 14, unit: 2, order: 4, slug: 'eval-var-1',
    standard: '6.EE.A.2.c', difficulty: 1,
    prompt: 'If $x = 6$, what is $x + 4$?',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Replace $x$ with $6$.' },
      { level: 'guide', text: '$6 + 4$.' },
      { level: 'reveal', text: '$10$.' },
    ],
    explanation: ['Substitute $x = 6$: $6 + 4 = 10$.'],
    tags: ['evaluate'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 15, unit: 2, order: 5, slug: 'eval-var-mult',
    standard: '6.EE.A.2.c', difficulty: 1,
    prompt: 'If $y = 4$, what is $5y$?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$5y$ means $5$ times $y$.' },
      { level: 'guide', text: '$5 \\times 4$.' },
      { level: 'reveal', text: '$20$.' },
    ],
    explanation: ['$5y = 5 \\times 4 = 20$.'],
    tags: ['evaluate'], estimatedSeconds: 25,
  },
  {
    domain: '6.EE', num: 16, unit: 2, order: 6, slug: 'translate-3x',
    standard: '6.EE.A.2.a', difficulty: 2,
    prompt: 'Write an expression for "$5$ more than $3$ times a number $n$".',
    answerType: 'short-text',
    primaryAnswer: '3n+5', alternativeAnswers: ['3n + 5', '5 + 3n', '5+3n', '3*n+5'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"More than" means addition.' },
      { level: 'guide', text: '"$3$ times $n$" is $3n$. Then add $5$.' },
      { level: 'reveal', text: '$3n + 5$.' },
    ],
    explanation: ['"$3$ times $n$" $\\to 3n$.', '"$5$ more than that" $\\to 3n + 5$.'],
    tags: ['CA', 'translate'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 17, unit: 2, order: 7, slug: 'parts-expr',
    standard: '6.EE.A.2.b', difficulty: 2,
    prompt: 'In the expression $7x + 4$, what is the **coefficient** of $x$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The coefficient is the number multiplied by the variable.' },
      { level: 'guide', text: 'In $7x$, what multiplies $x$?' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['Coefficient of $x$ in $7x + 4$ is $7$.'],
    tags: ['vocabulary'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 18, unit: 2, order: 8, slug: 'eval-two-vars',
    standard: '6.EE.A.2.c', difficulty: 2,
    prompt: 'If $a = 3$ and $b = 5$, evaluate $2a + b$.',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Replace $a$ with $3$ and $b$ with $5$.' },
      { level: 'guide', text: '$2(3) + 5 = 6 + 5$.' },
      { level: 'reveal', text: '$11$.' },
    ],
    explanation: ['Substitute: $2(3) + 5 = 6 + 5 = 11$.'],
    tags: ['evaluate'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 19, unit: 2, order: 9, slug: 'expr-from-words',
    standard: '6.EE.A.2.a', difficulty: 2,
    prompt: 'Write an expression for "$x$ decreased by $9$".',
    answerType: 'short-text',
    primaryAnswer: 'x-9', alternativeAnswers: ['x - 9'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Decreased by" means subtraction.' },
      { level: 'guide', text: '$x - 9$.' },
      { level: 'reveal', text: '$x - 9$.' },
    ],
    explanation: ['Decreased by $9$: subtract $9$ from $x$.', '$x - 9$.'],
    tags: ['translate'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 20, unit: 2, order: 10, slug: 'eval-with-exp',
    standard: '6.EE.A.2.c', difficulty: 3,
    prompt: 'If $x = 3$, evaluate $x^2 + 2x$.',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute, then evaluate exponent before multiplication.' },
      { level: 'guide', text: '$3^2 + 2(3) = 9 + 6$.' },
      { level: 'reveal', text: '$9 + 6 = 15$.' },
    ],
    explanation: ['$x^2 = 9$. $2x = 6$.', 'Sum: $15$.'],
    tags: ['MAP-practice', 'evaluate', 'exponent'], estimatedSeconds: 60,
  },

  // ---------------- UNIT 3 — Equivalent expressions (1-10) ----------------
  {
    domain: '6.EE', num: 21, unit: 3, order: 1, slug: 'distribute-2',
    standard: '6.EE.A.3', difficulty: 1,
    prompt: 'Use the distributive property: $3(x + 4)$.',
    answerType: 'short-text',
    primaryAnswer: '3x+12', alternativeAnswers: ['3x + 12', '12+3x'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply $3$ by each term inside.' },
      { level: 'guide', text: '$3 \\cdot x + 3 \\cdot 4$.' },
      { level: 'reveal', text: '$3x + 12$.' },
    ],
    explanation: ['$3(x + 4) = 3x + 12$.'],
    tags: ['distributive'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 22, unit: 3, order: 2, slug: 'combine-like',
    standard: '6.EE.A.3', difficulty: 1,
    prompt: 'Simplify: $4x + 3x$.',
    answerType: 'short-text', primaryAnswer: '7x', alternativeAnswers: [],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add the coefficients.' },
      { level: 'guide', text: '$4 + 3 = 7$.' },
      { level: 'reveal', text: '$7x$.' },
    ],
    explanation: ['$4x + 3x = (4 + 3)x = 7x$.'],
    tags: ['combine-like'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 23, unit: 3, order: 3, slug: 'distribute-5',
    standard: '6.EE.A.3', difficulty: 2,
    prompt: 'Expand $5(2x + 3)$.',
    answerType: 'short-text',
    primaryAnswer: '10x+15', alternativeAnswers: ['10x + 15'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Distribute $5$ to both terms.' },
      { level: 'guide', text: '$5 \\cdot 2x = 10x$, $5 \\cdot 3 = 15$.' },
      { level: 'reveal', text: '$10x + 15$.' },
    ],
    explanation: ['$5(2x + 3) = 10x + 15$.'],
    tags: ['distributive'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 24, unit: 3, order: 4, slug: 'combine-and-constant',
    standard: '6.EE.A.3', difficulty: 2,
    prompt: 'Simplify: $2x + 5 + 3x + 4$.',
    answerType: 'short-text',
    primaryAnswer: '5x+9', alternativeAnswers: ['5x + 9'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Combine $x$-terms; combine constants.' },
      { level: 'guide', text: '$2x + 3x = 5x$, $5 + 4 = 9$.' },
      { level: 'reveal', text: '$5x + 9$.' },
    ],
    explanation: ['$x$-terms: $2x + 3x = 5x$.', 'Constants: $5 + 4 = 9$.', '$5x + 9$.'],
    tags: ['CA', 'combine-like'], estimatedSeconds: 50,
  },
  {
    domain: '6.EE', num: 25, unit: 3, order: 5, slug: 'verify-equiv',
    standard: '6.EE.A.4', difficulty: 2,
    prompt: 'Is $2(x + 3)$ equivalent to $2x + 6$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Yes', correct: true },
      { id: 'B', label: 'No', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Apply the distributive property.' },
      { level: 'guide', text: '$2(x + 3) = 2x + 6$.' },
      { level: 'reveal', text: 'They match. Yes.' },
    ],
    explanation: ['$2(x + 3) = 2x + 6$.', 'They are equivalent.'],
    tags: ['equivalent'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 26, unit: 3, order: 6, slug: 'factor-out',
    standard: '6.EE.A.3', difficulty: 3,
    prompt: 'Factor $6x + 9$ using the GCF.',
    answerType: 'short-text',
    primaryAnswer: '3(2x+3)', alternativeAnswers: ['3(2x + 3)', '3 (2x+3)'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'GCF of $6$ and $9$.' },
      { level: 'guide', text: 'GCF is $3$. Divide each: $6x/3 = 2x$, $9/3 = 3$.' },
      { level: 'reveal', text: '$3(2x + 3)$.' },
    ],
    explanation: ['GCF$(6, 9) = 3$.', 'Factor: $3 \\cdot 2x + 3 \\cdot 3 = 3(2x + 3)$.'],
    tags: ['CA', 'factor'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 27, unit: 3, order: 7, slug: 'distribute-neg',
    standard: '6.EE.A.3', difficulty: 2,
    prompt: 'Expand $4(x + 7)$.',
    answerType: 'short-text',
    primaryAnswer: '4x+28', alternativeAnswers: ['4x + 28'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply $4$ by each.' },
      { level: 'guide', text: '$4x + 4 \\cdot 7$.' },
      { level: 'reveal', text: '$4x + 28$.' },
    ],
    explanation: ['$4(x + 7) = 4x + 28$.'],
    tags: ['distributive'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 28, unit: 3, order: 8, slug: 'simplify-multi',
    standard: '6.EE.A.3', difficulty: 3,
    prompt: 'Simplify: $3x + 2(x + 4)$.',
    answerType: 'short-text',
    primaryAnswer: '5x+8', alternativeAnswers: ['5x + 8'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Distribute first, then combine.' },
      { level: 'guide', text: '$3x + 2x + 8$.' },
      { level: 'reveal', text: '$5x + 8$.' },
    ],
    explanation: ['$2(x + 4) = 2x + 8$.', '$3x + 2x + 8 = 5x + 8$.'],
    tags: ['MAP-practice', 'simplify'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 29, unit: 3, order: 9, slug: 'mc-equiv-test',
    standard: '6.EE.A.4', difficulty: 2,
    prompt: 'Which is equivalent to $3(x + 2)$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$3x + 2$', correct: false },
      { id: 'B', label: '$x + 6$', correct: false },
      { id: 'C', label: '$3x + 6$', correct: true },
      { id: 'D', label: '$3x + 5$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Distribute the $3$.' },
      { level: 'guide', text: '$3 \\cdot x + 3 \\cdot 2 = ?$' },
      { level: 'reveal', text: '$3x + 6$.' },
    ],
    explanation: ['$3(x + 2) = 3x + 6$.'],
    tags: ['distributive', 'equivalent'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 30, unit: 3, order: 10, slug: 'combine-mix',
    standard: '6.EE.A.3', difficulty: 3,
    prompt: 'Simplify: $5y - 2y + 3$.',
    answerType: 'short-text',
    primaryAnswer: '3y+3', alternativeAnswers: ['3y + 3'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Combine $y$-terms.' },
      { level: 'guide', text: '$5y - 2y = 3y$.' },
      { level: 'reveal', text: '$3y + 3$.' },
    ],
    explanation: ['$5y - 2y = 3y$.', 'Constant: $+3$.', '$3y + 3$.'],
    tags: ['combine-like'], estimatedSeconds: 45,
  },

  // ---------------- UNIT 4 — One-step equations (1-10) ----------------
  {
    domain: '6.EE', num: 31, unit: 4, order: 1, slug: 'solve-add',
    standard: '6.EE.B.7', difficulty: 1,
    prompt: 'Solve: $x + 5 = 12$.',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Subtract $5$ from both sides.' },
      { level: 'guide', text: '$x = 12 - 5$.' },
      { level: 'reveal', text: '$x = 7$.' },
    ],
    explanation: ['$x + 5 = 12 \\Rightarrow x = 12 - 5 = 7$.'],
    tags: ['solve'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 32, unit: 4, order: 2, slug: 'solve-sub',
    standard: '6.EE.B.7', difficulty: 1,
    prompt: 'Solve: $x - 4 = 9$.',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add $4$ to both sides.' },
      { level: 'guide', text: '$x = 9 + 4$.' },
      { level: 'reveal', text: '$x = 13$.' },
    ],
    explanation: ['$x - 4 = 9 \\Rightarrow x = 13$.'],
    tags: ['solve'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 33, unit: 4, order: 3, slug: 'solve-mult',
    standard: '6.EE.B.7', difficulty: 1,
    prompt: 'Solve: $3x = 24$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide both sides by $3$.' },
      { level: 'guide', text: '$x = 24 / 3$.' },
      { level: 'reveal', text: '$x = 8$.' },
    ],
    explanation: ['$3x = 24 \\Rightarrow x = 8$.'],
    tags: ['solve'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 34, unit: 4, order: 4, slug: 'solve-div',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $\\frac{x}{4} = 5$.',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply both sides by $4$.' },
      { level: 'guide', text: '$x = 5 \\times 4$.' },
      { level: 'reveal', text: '$x = 20$.' },
    ],
    explanation: ['$\\frac{x}{4} = 5 \\Rightarrow x = 20$.'],
    tags: ['solve'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 35, unit: 4, order: 5, slug: 'solve-mc',
    standard: '6.EE.B.5', difficulty: 1,
    prompt: 'Which value makes $x + 6 = 10$ true?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$2$', correct: false },
      { id: 'B', label: '$4$', correct: true },
      { id: 'C', label: '$6$', correct: false },
      { id: 'D', label: '$16$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Try each. Which one makes left side equal $10$?' },
      { level: 'guide', text: '$4 + 6 = 10$. ✓' },
      { level: 'reveal', text: 'B.' },
    ],
    explanation: ['Substitute each into $x + 6 = 10$.', '$4 + 6 = 10$ ✓.'],
    tags: ['check-solution'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 36, unit: 4, order: 6, slug: 'word-equation',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Mia has some marbles. Tom gives her $7$ more and now she has $20$. How many did she have before?',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Let $x$ = before. $x + 7 = 20$.' },
      { level: 'guide', text: 'Solve: $x = 20 - 7$.' },
      { level: 'reveal', text: '$x = 13$.' },
    ],
    explanation: ['Set up: $x + 7 = 20$.', '$x = 13$ marbles.'],
    tags: ['CA', 'word', 'solve'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 37, unit: 4, order: 7, slug: 'solve-decimal',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $0.5x = 4$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide both sides by $0.5$.' },
      { level: 'guide', text: '$x = 4 / 0.5$.' },
      { level: 'reveal', text: '$x = 8$.' },
    ],
    explanation: ['$0.5x = 4 \\Rightarrow x = 8$.'],
    tags: ['solve', 'decimal'], estimatedSeconds: 50,
  },
  {
    domain: '6.EE', num: 38, unit: 4, order: 8, slug: 'solve-fraction-coef',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'Solve: $\\frac{2}{3} x = 10$.',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply both sides by $\\frac{3}{2}$.' },
      { level: 'guide', text: '$x = 10 \\cdot \\frac{3}{2}$.' },
      { level: 'reveal', text: '$x = 15$.' },
    ],
    explanation: ['$\\frac{2}{3} x = 10$.', 'Multiply both sides by $\\frac{3}{2}$: $x = 15$.'],
    tags: ['MAP-practice', 'solve', 'fraction'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 39, unit: 4, order: 9, slug: 'word-divide',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'A box of cookies is shared equally by $5$ friends, each getting $4$ cookies. How many cookies in the box?',
    answerType: 'numeric', primaryAnswer: '20', alternativeAnswers: ['20 cookies'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Let $x$ = total. $\\frac{x}{5} = 4$.' },
      { level: 'guide', text: '$x = 4 \\cdot 5$.' },
      { level: 'reveal', text: '$x = 20$.' },
    ],
    explanation: ['Total $= 5 \\times 4 = 20$.'],
    tags: ['word', 'solve'], estimatedSeconds: 55,
  },
  {
    domain: '6.EE', num: 40, unit: 4, order: 10, slug: 'solve-zero',
    standard: '6.EE.B.7', difficulty: 2,
    prompt: 'Solve: $x + 12 = 12$.',
    answerType: 'numeric', primaryAnswer: '0', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Subtract $12$ from both sides.' },
      { level: 'guide', text: '$x = 12 - 12$.' },
      { level: 'reveal', text: '$x = 0$.' },
    ],
    explanation: ['$x + 12 = 12 \\Rightarrow x = 0$.'],
    tags: ['solve'], estimatedSeconds: 30,
  },

  // ---------------- UNIT 5 — Inequalities (1-10) ----------------
  {
    domain: '6.EE', num: 41, unit: 5, order: 1, slug: 'ineq-graph',
    standard: '6.EE.B.8', difficulty: 1,
    prompt: 'On a number line, $x > 3$ has an open or closed circle at $3$?',
    answerType: 'short-text',
    primaryAnswer: 'open', alternativeAnswers: ['open circle'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$>$ is strict (not equal).' },
      { level: 'guide', text: 'Open circle = strict inequality.' },
      { level: 'reveal', text: 'Open.' },
    ],
    explanation: ['$>$ excludes $3$.', 'Open circle at $3$.'],
    tags: ['inequality'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 42, unit: 5, order: 2, slug: 'ineq-closed',
    standard: '6.EE.B.8', difficulty: 1,
    prompt: 'For $x \\geq 5$, is the circle at $5$ open or closed?',
    answerType: 'short-text',
    primaryAnswer: 'closed', alternativeAnswers: ['closed circle', 'solid'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$\\geq$ includes equality.' },
      { level: 'guide', text: 'Closed (filled) circle when "or equal to".' },
      { level: 'reveal', text: 'Closed.' },
    ],
    explanation: ['$\\geq$ includes $5$.', 'Closed (solid) circle at $5$.'],
    tags: ['inequality'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 43, unit: 5, order: 3, slug: 'ineq-write',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'Write an inequality: "$x$ is at most $7$".',
    answerType: 'short-text',
    primaryAnswer: 'x≤7', alternativeAnswers: ['x <= 7', 'x ≤ 7'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"At most" means "less than or equal to".' },
      { level: 'guide', text: '$x$ ≤ ?' },
      { level: 'reveal', text: '$x \\leq 7$.' },
    ],
    explanation: ['"At most $7$" means $x$ can be up to $7$ — i.e., $x \\leq 7$.'],
    tags: ['inequality', 'translate'], estimatedSeconds: 50,
  },
  {
    domain: '6.EE', num: 44, unit: 5, order: 4, slug: 'ineq-at-least',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'Write an inequality: "$y$ is at least $10$".',
    answerType: 'short-text',
    primaryAnswer: 'y≥10', alternativeAnswers: ['y >= 10', 'y ≥ 10'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"At least" means "greater than or equal to".' },
      { level: 'guide', text: '$y$ ≥ ?' },
      { level: 'reveal', text: '$y \\geq 10$.' },
    ],
    explanation: ['"At least $10$" means $y \\geq 10$.'],
    tags: ['inequality', 'translate'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 45, unit: 5, order: 5, slug: 'ineq-check',
    standard: '6.EE.B.5', difficulty: 2,
    prompt: 'Is $x = 4$ a solution to $x > 4$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Yes', correct: false },
      { id: 'B', label: 'No', correct: true },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '$>$ means strictly greater (not equal).' },
      { level: 'guide', text: 'Is $4 > 4$ true?' },
      { level: 'reveal', text: 'No — they\'re equal, not greater.' },
    ],
    explanation: ['$x > 4$ excludes $4$.', '$4$ is not a solution.'],
    tags: ['inequality', 'check'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 46, unit: 5, order: 6, slug: 'ineq-word',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'A roller coaster has a height requirement of $48$ inches. Write an inequality showing acceptable heights $h$.',
    answerType: 'short-text',
    primaryAnswer: 'h≥48', alternativeAnswers: ['h >= 48', 'h ≥ 48'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"At least $48$" — riders need $h \\geq 48$.' },
      { level: 'guide', text: '$h \\geq ?$' },
      { level: 'reveal', text: '$h \\geq 48$.' },
    ],
    explanation: ['Riders must be at least $48$ inches: $h \\geq 48$.'],
    tags: ['CA', 'inequality', 'word'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 47, unit: 5, order: 7, slug: 'ineq-pick-soln',
    standard: '6.EE.B.5', difficulty: 2,
    prompt: 'Which is a solution to $x \\leq 3$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$5$', correct: false },
      { id: 'B', label: '$4$', correct: false },
      { id: 'C', label: '$3$', correct: true },
      { id: 'D', label: '$7$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '$x \\leq 3$ means $x$ can be $3$ or less.' },
      { level: 'guide', text: 'Is $3 \\leq 3$ true? Yes.' },
      { level: 'reveal', text: 'C.' },
    ],
    explanation: ['$x \\leq 3$ allows values $\\leq 3$.', '$3 \\leq 3$ ✓. Answer: C.'],
    tags: ['inequality', 'check'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 48, unit: 5, order: 8, slug: 'ineq-direction',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'On a number line for $x < -2$, the arrow points which direction?',
    answerType: 'short-text',
    primaryAnswer: 'left', alternativeAnswers: ['Left', 'negative direction'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$<$ means smaller — to the left.' },
      { level: 'guide', text: 'From $-2$, smaller values are to the left.' },
      { level: 'reveal', text: 'Left.' },
    ],
    explanation: ['$x < -2$ → values smaller than $-2$, which are to the left.'],
    tags: ['inequality'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 49, unit: 5, order: 9, slug: 'ineq-write-less',
    standard: '6.EE.B.8', difficulty: 2,
    prompt: 'A bus can hold less than $30$ riders. Write an inequality for the number $n$ of riders.',
    answerType: 'short-text',
    primaryAnswer: 'n<30', alternativeAnswers: ['n < 30'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Less than" means $<$.' },
      { level: 'guide', text: '$n < 30$.' },
      { level: 'reveal', text: '$n < 30$.' },
    ],
    explanation: ['"Less than $30$" → $n < 30$.'],
    tags: ['MAP-practice', 'inequality', 'translate'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 50, unit: 5, order: 10, slug: 'ineq-multiple',
    standard: '6.EE.B.5', difficulty: 3,
    prompt: 'How many of these are solutions to $x \\geq 5$: $\\{2, 5, 6, 4, 9\\}$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count values that are $\\geq 5$.' },
      { level: 'guide', text: '$5, 6, 9$ all satisfy.' },
      { level: 'reveal', text: '$3$ solutions.' },
    ],
    explanation: ['$5 \\geq 5$ ✓; $6 \\geq 5$ ✓; $9 \\geq 5$ ✓.', 'Total: $3$.'],
    tags: ['inequality'], estimatedSeconds: 55,
  },

  // ---------------- UNIT 6 — Two variables / Mixed (1-10) ----------------
  {
    domain: '6.EE', num: 51, unit: 6, order: 1, slug: 'two-var-table',
    standard: '6.EE.C.9', difficulty: 1,
    prompt: 'If $y = 2x$, what is $y$ when $x = 5$?',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $x = 5$.' },
      { level: 'guide', text: '$y = 2 \\cdot 5$.' },
      { level: 'reveal', text: '$y = 10$.' },
    ],
    explanation: ['$y = 2x = 2(5) = 10$.'],
    tags: ['two-vars'], estimatedSeconds: 30,
  },
  {
    domain: '6.EE', num: 52, unit: 6, order: 2, slug: 'two-var-x',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'If $y = x + 7$ and $y = 12$, what is $x$?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$x + 7 = 12$.' },
      { level: 'guide', text: '$x = 12 - 7$.' },
      { level: 'reveal', text: '$x = 5$.' },
    ],
    explanation: ['$x + 7 = 12 \\Rightarrow x = 5$.'],
    tags: ['two-vars'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 53, unit: 6, order: 3, slug: 'indep-dep',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'A cab charges \\$$3$ plus \\$$2$ per mile. Write the cost $c$ as a function of miles $m$.',
    answerType: 'short-text',
    primaryAnswer: 'c=2m+3', alternativeAnswers: ['c = 2m + 3', 'c=3+2m'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Start fee plus per-mile rate.' },
      { level: 'guide', text: '$c = 2m + 3$.' },
      { level: 'reveal', text: '$c = 2m + 3$.' },
    ],
    explanation: ['Base fee $3$ + per mile $2$ × $m$ miles.', '$c = 2m + 3$.'],
    tags: ['CA', 'two-vars', 'word'], estimatedSeconds: 70,
  },
  {
    domain: '6.EE', num: 54, unit: 6, order: 4, slug: 'two-var-substitute',
    standard: '6.EE.C.9', difficulty: 2,
    prompt: 'If $y = 3x + 1$, what is $y$ when $x = 4$?',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute and compute.' },
      { level: 'guide', text: '$y = 3(4) + 1$.' },
      { level: 'reveal', text: '$y = 12 + 1 = 13$.' },
    ],
    explanation: ['$y = 3(4) + 1 = 13$.'],
    tags: ['two-vars'], estimatedSeconds: 35,
  },
  {
    domain: '6.EE', num: 55, unit: 6, order: 5, slug: 'mix-distribute',
    standard: '6.EE.A.3', difficulty: 2,
    prompt: 'Expand $2(3x - 4)$.',
    answerType: 'short-text',
    primaryAnswer: '6x-8', alternativeAnswers: ['6x - 8'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply $2$ by each term.' },
      { level: 'guide', text: '$2 \\cdot 3x - 2 \\cdot 4$.' },
      { level: 'reveal', text: '$6x - 8$.' },
    ],
    explanation: ['$2(3x - 4) = 6x - 8$.'],
    tags: ['distributive'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 56, unit: 6, order: 6, slug: 'mix-solve-word',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'Tickets cost $4$ each. With \\$$24$, you bought some tickets. How many?',
    answerType: 'numeric', primaryAnswer: '6', alternativeAnswers: ['6 tickets'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set up: $4t = 24$.' },
      { level: 'guide', text: '$t = 24 / 4$.' },
      { level: 'reveal', text: '$t = 6$.' },
    ],
    explanation: ['$4t = 24 \\Rightarrow t = 6$ tickets.'],
    tags: ['MAP-practice', 'solve', 'word'], estimatedSeconds: 60,
  },
  {
    domain: '6.EE', num: 57, unit: 6, order: 7, slug: 'mix-pattern',
    standard: '6.EE.C.9', difficulty: 3,
    prompt: 'A pattern: $1 \\to 5$, $2 \\to 9$, $3 \\to 13$. What is the rule (as $y = $ expression)?',
    answerType: 'short-text',
    primaryAnswer: 'y=4x+1', alternativeAnswers: ['y = 4x + 1'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The output goes up by $4$ each time. What\'s the constant?' },
      { level: 'guide', text: 'When $x = 0$, $y$ would be $1$. So $y = 4x + 1$.' },
      { level: 'reveal', text: '$y = 4x + 1$.' },
    ],
    explanation: ['Rate of change: $4$.', 'When $x = 1$: $4(1) + 1 = 5$ ✓.', 'Rule: $y = 4x + 1$.'],
    tags: ['CA', 'two-vars', 'pattern'], estimatedSeconds: 90,
  },
  {
    domain: '6.EE', num: 58, unit: 6, order: 8, slug: 'mix-expression',
    standard: '6.EE.A.2.c', difficulty: 2,
    prompt: 'Evaluate $a^2 + b$ when $a = 4, b = 5$.',
    answerType: 'numeric', primaryAnswer: '21', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Compute exponent first.' },
      { level: 'guide', text: '$4^2 + 5 = 16 + 5$.' },
      { level: 'reveal', text: '$21$.' },
    ],
    explanation: ['$4^2 = 16$. $16 + 5 = 21$.'],
    tags: ['evaluate'], estimatedSeconds: 45,
  },
  {
    domain: '6.EE', num: 59, unit: 6, order: 9, slug: 'mix-write-equation',
    standard: '6.EE.B.6', difficulty: 2,
    prompt: 'Write an equation: "A number $n$ plus $13$ equals $20$".',
    answerType: 'short-text',
    primaryAnswer: 'n+13=20', alternativeAnswers: ['n + 13 = 20', '13+n=20'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Translate word for word.' },
      { level: 'guide', text: '$n + 13 = 20$.' },
      { level: 'reveal', text: '$n + 13 = 20$.' },
    ],
    explanation: ['$n$ plus $13$ equals $20$: $n + 13 = 20$.'],
    tags: ['translate'], estimatedSeconds: 40,
  },
  {
    domain: '6.EE', num: 60, unit: 6, order: 10, slug: 'mix-two-step',
    standard: '6.EE.B.7', difficulty: 3,
    prompt: 'Solve: $2x + 3 = 11$.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Subtract $3$ first.' },
      { level: 'guide', text: '$2x = 8$. Now divide by $2$.' },
      { level: 'reveal', text: '$x = 4$.' },
    ],
    explanation: ['$2x + 3 = 11$.', '$2x = 8$.', '$x = 4$.'],
    tags: ['CA', 'solve'], estimatedSeconds: 60,
  },
];
