import type { SeedProblem } from './types';

// 6.G — Geometry. Adds 53 new (6 to U1, 7 to U2, 10 each to U3-U6).

export const problems6G: SeedProblem[] = [
  // ---------------- UNIT 1 — Area of polygons (orders 5-10) ----------------
  {
    domain: '6.G', num: 8, unit: 1, order: 5, slug: 'square-area',
    standard: '6.G.A.1', difficulty: 1,
    prompt: 'What is the area of a square with side $7$ cm?',
    answerType: 'numeric', primaryAnswer: '49', alternativeAnswers: ['49 sq cm', '49 cm²'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Area of square $= s^2$.' },
      { level: 'guide', text: '$7 \\times 7$.' },
      { level: 'reveal', text: '$49$.' },
    ],
    explanation: ['$A = s^2 = 7^2 = 49$ sq cm.'],
    tags: ['area', 'square'], estimatedSeconds: 30,
  },
  {
    domain: '6.G', num: 9, unit: 1, order: 6, slug: 'rect-area-3-7',
    standard: '6.G.A.1', difficulty: 1,
    prompt: 'A rectangle has length $7$ and width $3$. What is its area?',
    answerType: 'numeric', primaryAnswer: '21', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$A = l \\times w$.' },
      { level: 'guide', text: '$7 \\times 3$.' },
      { level: 'reveal', text: '$21$.' },
    ],
    explanation: ['$A = l \\times w = 7 \\times 3 = 21$.'],
    tags: ['area', 'rectangle'], estimatedSeconds: 30,
  },
  {
    domain: '6.G', num: 10, unit: 1, order: 7, slug: 'tri-area-10-6',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A triangle has base $10$ and height $6$. Find its area.',
    answerType: 'numeric', primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Triangle area $= \\frac{1}{2} \\cdot b \\cdot h$.' },
      { level: 'guide', text: '$\\frac{1}{2} \\cdot 10 \\cdot 6$.' },
      { level: 'reveal', text: '$30$.' },
    ],
    explanation: ['$A = \\frac{1}{2}(10)(6) = 30$.'],
    tags: ['area', 'triangle'], estimatedSeconds: 40,
  },
  {
    domain: '6.G', num: 11, unit: 1, order: 8, slug: 'parallelogram-area-2',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A parallelogram has base $9$ and height $4$. Find its area.',
    answerType: 'numeric', primaryAnswer: '36', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Parallelogram area $= b \\cdot h$.' },
      { level: 'guide', text: '$9 \\times 4$.' },
      { level: 'reveal', text: '$36$.' },
    ],
    explanation: ['$A = bh = 9 \\times 4 = 36$.'],
    tags: ['area', 'parallelogram'], estimatedSeconds: 35,
  },
  {
    domain: '6.G', num: 12, unit: 1, order: 9, slug: 'trapezoid-area',
    standard: '6.G.A.1', difficulty: 3,
    prompt: 'A trapezoid has parallel sides $6$ and $10$, height $4$. Find its area.',
    answerType: 'numeric', primaryAnswer: '32', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Trapezoid area $= \\frac{1}{2}(b_1 + b_2) h$.' },
      { level: 'guide', text: '$\\frac{1}{2}(6 + 10)(4) = \\frac{1}{2}(16)(4)$.' },
      { level: 'reveal', text: '$\\frac{1}{2} \\cdot 64 = 32$.' },
    ],
    explanation: ['$A = \\frac{1}{2}(b_1 + b_2)h = \\frac{1}{2}(16)(4) = 32$.'],
    tags: ['MAP-practice', 'area', 'trapezoid'], estimatedSeconds: 70,
  },
  {
    domain: '6.G', num: 13, unit: 1, order: 10, slug: 'tri-area-12-5',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A triangle has base $12$ ft and height $5$ ft. What is its area?',
    answerType: 'numeric', primaryAnswer: '30', alternativeAnswers: ['30 sq ft'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$\\frac{1}{2} b h$.' },
      { level: 'guide', text: '$\\frac{1}{2}(12)(5) = ?$' },
      { level: 'reveal', text: '$30$.' },
    ],
    explanation: ['$A = \\frac{1}{2}(12)(5) = 30$ sq ft.'],
    tags: ['area', 'triangle'], estimatedSeconds: 35,
  },

  // ---------------- UNIT 2 — Polygons on coord plane (orders 4-10) ----------------
  {
    domain: '6.G', num: 14, unit: 2, order: 4, slug: 'coord-side',
    standard: '6.G.A.3', difficulty: 1,
    prompt: 'Find the length of the side from $(2, 1)$ to $(2, 7)$.',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Same $x$, vertical line.' },
      { level: 'guide', text: '$|7 - 1| = ?$' },
      { level: 'reveal', text: '$6$.' },
    ],
    explanation: ['Same $x$ → vertical side.', 'Length $= |7 - 1| = 6$.'],
    tags: ['coord', 'side'], estimatedSeconds: 35,
  },
  {
    domain: '6.G', num: 15, unit: 2, order: 5, slug: 'coord-perim',
    standard: '6.G.A.3', difficulty: 2,
    prompt: 'A rectangle has corners at $(0, 0), (5, 0), (5, 3), (0, 3)$. Find its **perimeter**.',
    answerType: 'numeric', primaryAnswer: '16', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Length $= 5$, width $= 3$.' },
      { level: 'guide', text: 'Perimeter $= 2(l + w) = 2(5 + 3)$.' },
      { level: 'reveal', text: '$2(8) = 16$.' },
    ],
    explanation: ['$P = 2(5 + 3) = 16$.'],
    tags: ['coord', 'perimeter'], estimatedSeconds: 50,
  },
  {
    domain: '6.G', num: 16, unit: 2, order: 6, slug: 'coord-area',
    standard: '6.G.A.3', difficulty: 2,
    prompt: 'A rectangle has corners $(1, 1), (1, 5), (4, 1), (4, 5)$. What is its area?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Width $= |4 - 1| = 3$, height $= |5 - 1| = 4$.' },
      { level: 'guide', text: '$A = w \\cdot h = 3 \\cdot 4$.' },
      { level: 'reveal', text: '$12$.' },
    ],
    explanation: ['Width $3$, height $4$.', '$A = 12$.'],
    tags: ['coord', 'area'], estimatedSeconds: 50,
  },
  {
    domain: '6.G', num: 17, unit: 2, order: 7, slug: 'coord-triangle',
    standard: '6.G.A.3', difficulty: 3,
    prompt: 'A right triangle has vertices at $(0, 0), (6, 0), (0, 4)$. Find its area.',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Legs along the axes are base and height.' },
      { level: 'guide', text: 'Base $= 6$, height $= 4$. Area $= \\frac{1}{2}(6)(4)$.' },
      { level: 'reveal', text: '$12$.' },
    ],
    explanation: ['Base $6$, height $4$.', '$A = \\frac{1}{2}(6)(4) = 12$.'],
    tags: ['CA', 'coord', 'triangle'], estimatedSeconds: 70,
  },
  {
    domain: '6.G', num: 18, unit: 2, order: 8, slug: 'coord-square',
    standard: '6.G.A.3', difficulty: 2,
    prompt: 'A square has vertices at $(-2, -2), (-2, 4), (4, -2), (4, 4)$. What is its side length?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Distance from $-2$ to $4$.' },
      { level: 'guide', text: '$|4 - (-2)| = 6$.' },
      { level: 'reveal', text: '$6$.' },
    ],
    explanation: ['Side $= |4 - (-2)| = 6$.'],
    tags: ['coord', 'square'], estimatedSeconds: 50,
  },
  {
    domain: '6.G', num: 19, unit: 2, order: 9, slug: 'coord-rect-mc',
    standard: '6.G.A.3', difficulty: 2,
    prompt: 'Which two vertices form one side of a rectangle aligned with the axes?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$(1, 2)$ and $(3, 5)$', correct: false },
      { id: 'B', label: '$(1, 2)$ and $(1, 5)$', correct: true },
      { id: 'C', label: '$(1, 2)$ and $(4, 5)$', correct: false },
      { id: 'D', label: '$(0, 0)$ and $(1, 1)$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'A vertical side has matching $x$ values.' },
      { level: 'guide', text: 'Both have $x = 1$.' },
      { level: 'reveal', text: 'B.' },
    ],
    explanation: ['Same $x$ means vertical side.', '$(1, 2)$ and $(1, 5)$ both have $x = 1$.'],
    tags: ['coord'], estimatedSeconds: 50,
  },
  {
    domain: '6.G', num: 20, unit: 2, order: 10, slug: 'coord-area-mixed',
    standard: '6.G.A.3', difficulty: 3,
    prompt: 'A rectangle has corners $(-3, -2), (5, -2), (5, 4), (-3, 4)$. Find its area.',
    answerType: 'numeric', primaryAnswer: '48', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Width: $|5 - (-3)| = 8$. Height: $|4 - (-2)| = 6$.' },
      { level: 'guide', text: '$A = 8 \\times 6$.' },
      { level: 'reveal', text: '$48$.' },
    ],
    explanation: ['Width $8$, height $6$.', '$A = 48$.'],
    tags: ['MAP-practice', 'coord', 'area'], estimatedSeconds: 70,
  },

  // ---------------- UNIT 3 — Volume of prisms (1-10) ----------------
  {
    domain: '6.G', num: 21, unit: 3, order: 1, slug: 'vol-rect-prism',
    standard: '6.G.A.2', difficulty: 1,
    prompt: 'A rectangular prism is $3 \\times 4 \\times 5$. Find its volume.',
    answerType: 'numeric', primaryAnswer: '60', alternativeAnswers: ['60 cubic units'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$V = l \\cdot w \\cdot h$.' },
      { level: 'guide', text: '$3 \\times 4 \\times 5$.' },
      { level: 'reveal', text: '$60$.' },
    ],
    explanation: ['$V = 3 \\cdot 4 \\cdot 5 = 60$.'],
    tags: ['volume', 'prism'], estimatedSeconds: 35,
  },
  {
    domain: '6.G', num: 22, unit: 3, order: 2, slug: 'vol-cube',
    standard: '6.G.A.2', difficulty: 1,
    prompt: 'Find the volume of a cube with side $4$.',
    answerType: 'numeric', primaryAnswer: '64', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$V = s^3$.' },
      { level: 'guide', text: '$4 \\times 4 \\times 4$.' },
      { level: 'reveal', text: '$4 \\cdot 16 = 64$.' },
    ],
    explanation: ['$V = s^3 = 4^3 = 64$.'],
    tags: ['volume', 'cube'], estimatedSeconds: 35,
  },
  {
    domain: '6.G', num: 23, unit: 3, order: 3, slug: 'vol-find-h',
    standard: '6.G.A.2', difficulty: 2,
    prompt: 'A box has $V = 120$, length $5$, width $4$. Find the height.',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$V = l w h$.' },
      { level: 'guide', text: '$h = V / (l w) = 120 / 20$.' },
      { level: 'reveal', text: '$h = 6$.' },
    ],
    explanation: ['$h = 120 / (5 \\cdot 4) = 6$.'],
    tags: ['volume'], estimatedSeconds: 55,
  },
  {
    domain: '6.G', num: 24, unit: 3, order: 4, slug: 'vol-cm3',
    standard: '6.G.A.2', difficulty: 1,
    prompt: 'A box is $2$ cm × $3$ cm × $4$ cm. Volume in cubic centimeters?',
    answerType: 'numeric', primaryAnswer: '24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply all three.' },
      { level: 'guide', text: '$2 \\times 3 \\times 4$.' },
      { level: 'reveal', text: '$24$.' },
    ],
    explanation: ['$V = 24$ cm³.'],
    tags: ['volume'], estimatedSeconds: 30,
  },
  {
    domain: '6.G', num: 25, unit: 3, order: 5, slug: 'vol-fraction-edges',
    standard: '6.G.A.2', difficulty: 3,
    prompt: 'A prism is $\\frac{1}{2} \\times \\frac{3}{4} \\times 2$. Find its volume.',
    answerType: 'fraction', primaryAnswer: '3/4', alternativeAnswers: ['0.75'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply the three.' },
      { level: 'guide', text: '$\\frac{1}{2} \\cdot \\frac{3}{4} = \\frac{3}{8}$, then $\\times 2$.' },
      { level: 'reveal', text: '$\\frac{3}{8} \\cdot 2 = \\frac{6}{8} = \\frac{3}{4}$.' },
    ],
    explanation: ['$V = \\frac{1}{2} \\cdot \\frac{3}{4} \\cdot 2 = \\frac{6}{8} = \\frac{3}{4}$.'],
    tags: ['CA', 'volume', 'fraction'], estimatedSeconds: 80,
  },
  {
    domain: '6.G', num: 26, unit: 3, order: 6, slug: 'vol-find-l',
    standard: '6.G.A.2', difficulty: 2,
    prompt: 'A box has $V = 72$, width $3$, height $4$. Find the length.',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$l = V / (w h)$.' },
      { level: 'guide', text: '$l = 72 / 12$.' },
      { level: 'reveal', text: '$l = 6$.' },
    ],
    explanation: ['$l = 72 / (3 \\cdot 4) = 6$.'],
    tags: ['volume'], estimatedSeconds: 50,
  },
  {
    domain: '6.G', num: 27, unit: 3, order: 7, slug: 'vol-words',
    standard: '6.G.A.2', difficulty: 2,
    prompt: 'An aquarium is $40$ cm long, $20$ cm wide, $30$ cm tall. Find its volume in cm³.',
    answerType: 'numeric', primaryAnswer: '24000', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply length × width × height.' },
      { level: 'guide', text: '$40 \\times 20 = 800$. $800 \\times 30 = ?$' },
      { level: 'reveal', text: '$24{,}000$.' },
    ],
    explanation: ['$V = 40 \\times 20 \\times 30 = 24{,}000$ cm³.'],
    tags: ['volume', 'word'], estimatedSeconds: 60,
  },
  {
    domain: '6.G', num: 28, unit: 3, order: 8, slug: 'vol-cube-unknown',
    standard: '6.G.A.2', difficulty: 3,
    prompt: 'A cube has volume $125$. Find the length of one edge.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$V = s^3$. Find cube root.' },
      { level: 'guide', text: 'What number cubed is $125$?' },
      { level: 'reveal', text: '$5^3 = 125$, so $s = 5$.' },
    ],
    explanation: ['$s^3 = 125 \\Rightarrow s = 5$.'],
    tags: ['volume', 'cube'], estimatedSeconds: 60,
  },
  {
    domain: '6.G', num: 29, unit: 3, order: 9, slug: 'vol-fill-water',
    standard: '6.G.A.2', difficulty: 3,
    prompt: 'A tank is $5$ ft × $3$ ft × $2$ ft. How many cubic feet of water to fill it?',
    answerType: 'numeric', primaryAnswer: '30', alternativeAnswers: ['30 cubic feet'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$V = lwh$.' },
      { level: 'guide', text: '$5 \\times 3 \\times 2$.' },
      { level: 'reveal', text: '$30$.' },
    ],
    explanation: ['$V = 5 \\cdot 3 \\cdot 2 = 30$ ft³.'],
    tags: ['MAP-practice', 'volume', 'word'], estimatedSeconds: 60,
  },
  {
    domain: '6.G', num: 30, unit: 3, order: 10, slug: 'vol-unit-cubes',
    standard: '6.G.A.2', difficulty: 2,
    prompt: 'A box is built from $\\frac{1}{3}$-inch unit cubes. The box is $3$ unit cubes × $4$ unit cubes × $2$ unit cubes. What is the total volume in cubic inches?',
    answerType: 'fraction',
    primaryAnswer: '8/9', alternativeAnswers: ['8/9 in³'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Total unit cubes: $3 \\times 4 \\times 2 = 24$.' },
      { level: 'guide', text: 'Each unit cube has volume $(\\frac{1}{3})^3 = \\frac{1}{27}$.' },
      { level: 'reveal', text: 'Total: $24 \\times \\frac{1}{27} = \\frac{24}{27} = \\frac{8}{9}$.' },
    ],
    explanation: ['$24$ unit cubes × $\\frac{1}{27}$ in³ each $= \\frac{24}{27} = \\frac{8}{9}$ in³.'],
    tags: ['CA', 'volume', 'fraction'], estimatedSeconds: 90,
  },

  // ---------------- UNIT 4 — Surface area & nets (1-10) ----------------
  {
    domain: '6.G', num: 31, unit: 4, order: 1, slug: 'sa-cube-2',
    standard: '6.G.A.4', difficulty: 1,
    prompt: 'Find the surface area of a cube with side $2$.',
    answerType: 'numeric', primaryAnswer: '24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A cube has $6$ identical square faces.' },
      { level: 'guide', text: 'Each face: $2 \\times 2 = 4$. Total: $6 \\times 4$.' },
      { level: 'reveal', text: '$24$.' },
    ],
    explanation: ['$6$ faces of $4$: $6 \\times 4 = 24$.'],
    tags: ['surface-area', 'cube'], estimatedSeconds: 40,
  },
  {
    domain: '6.G', num: 32, unit: 4, order: 2, slug: 'sa-cube-5',
    standard: '6.G.A.4', difficulty: 2,
    prompt: 'Find the surface area of a cube with side $5$.',
    answerType: 'numeric', primaryAnswer: '150', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$6s^2$.' },
      { level: 'guide', text: '$6 \\times 25$.' },
      { level: 'reveal', text: '$150$.' },
    ],
    explanation: ['$6 \\times 5^2 = 6 \\times 25 = 150$.'],
    tags: ['surface-area', 'cube'], estimatedSeconds: 40,
  },
  {
    domain: '6.G', num: 33, unit: 4, order: 3, slug: 'sa-rect-prism',
    standard: '6.G.A.4', difficulty: 2,
    prompt: 'A rectangular prism is $4 \\times 3 \\times 2$. Find its surface area.',
    answerType: 'numeric', primaryAnswer: '52', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$SA = 2(lw + lh + wh)$.' },
      { level: 'guide', text: '$2(12 + 8 + 6) = 2(26)$.' },
      { level: 'reveal', text: '$52$.' },
    ],
    explanation: ['$lw = 12$, $lh = 8$, $wh = 6$.', '$SA = 2(12 + 8 + 6) = 52$.'],
    tags: ['surface-area', 'prism'], estimatedSeconds: 70,
  },
  {
    domain: '6.G', num: 34, unit: 4, order: 4, slug: 'sa-faces-count',
    standard: '6.G.A.4', difficulty: 1,
    prompt: 'How many faces does a rectangular prism have?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Think of a box.' },
      { level: 'guide', text: 'Top, bottom, $4$ sides.' },
      { level: 'reveal', text: '$6$.' },
    ],
    explanation: ['$1$ top + $1$ bottom + $4$ sides $= 6$ faces.'],
    tags: ['surface-area', 'faces'], estimatedSeconds: 30,
  },
  {
    domain: '6.G', num: 35, unit: 4, order: 5, slug: 'net-cube',
    standard: '6.G.A.4', difficulty: 2,
    prompt: 'A net of a cube has how many squares?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Same as the number of faces.' },
      { level: 'guide', text: 'Cube has $6$ faces.' },
      { level: 'reveal', text: '$6$ squares.' },
    ],
    explanation: ['A cube net unfolds into $6$ square faces.'],
    tags: ['net'], estimatedSeconds: 30,
  },
  {
    domain: '6.G', num: 36, unit: 4, order: 6, slug: 'sa-prism-6-4-3',
    standard: '6.G.A.4', difficulty: 2,
    prompt: 'A box is $6 \\times 4 \\times 3$ cm. What is its surface area in cm²?',
    answerType: 'numeric', primaryAnswer: '108', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Three pairs of identical faces.' },
      { level: 'guide', text: '$2(6 \\cdot 4) + 2(6 \\cdot 3) + 2(4 \\cdot 3)$.' },
      { level: 'reveal', text: '$48 + 36 + 24 = 108$.' },
    ],
    explanation: ['$2(24) + 2(18) + 2(12) = 48 + 36 + 24 = 108$.'],
    tags: ['MAP-practice', 'surface-area'], estimatedSeconds: 75,
  },
  {
    domain: '6.G', num: 37, unit: 4, order: 7, slug: 'wrap-gift',
    standard: '6.G.A.4', difficulty: 3,
    prompt: 'You want to wrap a $3 \\times 3 \\times 3$ cube. How much paper (in cm²) do you need?',
    answerType: 'numeric', primaryAnswer: '54', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Wrapping covers the surface — $6s^2$.' },
      { level: 'guide', text: '$6 \\times 9 = ?$' },
      { level: 'reveal', text: '$54$.' },
    ],
    explanation: ['$SA = 6s^2 = 6(9) = 54$.'],
    tags: ['CA', 'surface-area', 'word'], estimatedSeconds: 55,
  },
  {
    domain: '6.G', num: 38, unit: 4, order: 8, slug: 'sa-doubling',
    standard: '6.G.A.4', difficulty: 3,
    prompt: 'A cube has SA $= 24$. What is the side length?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$6s^2 = 24$.' },
      { level: 'guide', text: '$s^2 = 4$.' },
      { level: 'reveal', text: '$s = 2$.' },
    ],
    explanation: ['$6s^2 = 24 \\Rightarrow s^2 = 4 \\Rightarrow s = 2$.'],
    tags: ['surface-area', 'cube'], estimatedSeconds: 60,
  },
  {
    domain: '6.G', num: 39, unit: 4, order: 9, slug: 'sa-tri-prism',
    standard: '6.G.A.4', difficulty: 3,
    prompt: 'A rectangular prism has $l = 10, w = 5, h = 2$. Find SA.',
    answerType: 'numeric', primaryAnswer: '160', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$SA = 2(lw + lh + wh)$.' },
      { level: 'guide', text: '$2(50 + 20 + 10) = 2(80)$.' },
      { level: 'reveal', text: '$160$.' },
    ],
    explanation: ['$lw = 50, lh = 20, wh = 10$.', '$SA = 2(80) = 160$.'],
    tags: ['surface-area'], estimatedSeconds: 75,
  },
  {
    domain: '6.G', num: 40, unit: 4, order: 10, slug: 'sa-faces-area',
    standard: '6.G.A.4', difficulty: 3,
    prompt: 'A cube has each face with area $9$ cm². What is the total SA?',
    answerType: 'numeric', primaryAnswer: '54', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$6$ faces, each $9$ cm².' },
      { level: 'guide', text: '$6 \\times 9$.' },
      { level: 'reveal', text: '$54$.' },
    ],
    explanation: ['Total SA $= 6 \\times 9 = 54$ cm².'],
    tags: ['surface-area'], estimatedSeconds: 40,
  },

  // ---------------- UNIT 5 — Composite figures (1-10) ----------------
  {
    domain: '6.G', num: 41, unit: 5, order: 1, slug: 'comp-l-shape',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'An L-shape is made of two rectangles: $4 \\times 3$ and $2 \\times 5$. What is the total area?',
    answerType: 'numeric', primaryAnswer: '22', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add the two areas.' },
      { level: 'guide', text: '$4 \\times 3 = 12$, $2 \\times 5 = 10$.' },
      { level: 'reveal', text: '$12 + 10 = 22$.' },
    ],
    explanation: ['Decompose: $12 + 10 = 22$.'],
    tags: ['composite', 'area'], estimatedSeconds: 60,
  },
  {
    domain: '6.G', num: 42, unit: 5, order: 2, slug: 'comp-tri-rect',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A shape combines a rectangle ($6 \\times 4$) with a triangle on top (base $6$, height $3$). What is the total area?',
    answerType: 'numeric', primaryAnswer: '33', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Rectangle area + triangle area.' },
      { level: 'guide', text: '$24 + \\frac{1}{2}(6)(3) = 24 + 9$.' },
      { level: 'reveal', text: '$33$.' },
    ],
    explanation: ['$A_{rect} = 24$; $A_{tri} = 9$.', 'Total: $33$.'],
    tags: ['CA', 'composite', 'area'], estimatedSeconds: 75,
  },
  {
    domain: '6.G', num: 43, unit: 5, order: 3, slug: 'comp-subtract',
    standard: '6.G.A.1', difficulty: 3,
    prompt: 'A large rectangle is $10 \\times 8$. A $2 \\times 3$ rectangle is cut out. Find the remaining area.',
    answerType: 'numeric', primaryAnswer: '74', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Total minus cut-out.' },
      { level: 'guide', text: '$80 - 6$.' },
      { level: 'reveal', text: '$74$.' },
    ],
    explanation: ['$80 - 6 = 74$.'],
    tags: ['MAP-practice', 'composite', 'area'], estimatedSeconds: 60,
  },
  {
    domain: '6.G', num: 44, unit: 5, order: 4, slug: 'comp-house',
    standard: '6.G.A.1', difficulty: 3,
    prompt: 'A house shape: rectangle $8 \\times 5$ + triangular roof (base $8$, height $4$). Total area?',
    answerType: 'numeric', primaryAnswer: '56', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Rectangle + triangle.' },
      { level: 'guide', text: '$40 + \\frac{1}{2}(8)(4) = 40 + 16$.' },
      { level: 'reveal', text: '$56$.' },
    ],
    explanation: ['$A_{rect} = 40, A_{tri} = 16$.', 'Total: $56$.'],
    tags: ['composite', 'word'], estimatedSeconds: 80,
  },
  {
    domain: '6.G', num: 45, unit: 5, order: 5, slug: 'comp-park',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A park has a rectangular play area $20 \\times 15$ and a square sandbox $5 \\times 5$ next to it. Find the combined area.',
    answerType: 'numeric', primaryAnswer: '325', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$300 + 25$.' },
      { level: 'guide', text: 'Rectangle: $300$. Square: $25$.' },
      { level: 'reveal', text: '$325$.' },
    ],
    explanation: ['$20 \\times 15 = 300$. $5 \\times 5 = 25$.', 'Total: $325$.'],
    tags: ['composite', 'word'], estimatedSeconds: 55,
  },
  {
    domain: '6.G', num: 46, unit: 5, order: 6, slug: 'comp-floor',
    standard: '6.G.A.1', difficulty: 3,
    prompt: 'A floor plan is an "L": $10 \\times 6$ minus a corner cut of $3 \\times 2$. Find the area.',
    answerType: 'numeric', primaryAnswer: '54', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$60 - 6$.' },
      { level: 'guide', text: '$10 \\times 6 = 60$, cut: $3 \\times 2 = 6$.' },
      { level: 'reveal', text: '$54$.' },
    ],
    explanation: ['$60 - 6 = 54$.'],
    tags: ['composite', 'area'], estimatedSeconds: 70,
  },
  {
    domain: '6.G', num: 47, unit: 5, order: 7, slug: 'comp-perim',
    standard: '6.G.A.1', difficulty: 3,
    prompt: 'An L-shape has outer dimensions $6 \\times 4$. The inner cut is $2 \\times 2$. Find the perimeter.',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Trace around the entire boundary.' },
      { level: 'guide', text: 'Sides: $6 + 4 + (6-2) + 2 + 2 + 2 = 20$.' },
      { level: 'reveal', text: '$20$.' },
    ],
    explanation: ['Outer L-shape perimeter sums to $20$ when you walk along all edges.'],
    tags: ['composite', 'perimeter'], estimatedSeconds: 90,
  },
  {
    domain: '6.G', num: 48, unit: 5, order: 8, slug: 'comp-tri-area',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A composite figure has $2$ triangles each with base $4$ and height $3$. What is the total area?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'One triangle: $\\frac{1}{2}(4)(3) = 6$.' },
      { level: 'guide', text: 'Two of them.' },
      { level: 'reveal', text: '$2 \\times 6 = 12$.' },
    ],
    explanation: ['Each: $\\frac{1}{2}(4)(3) = 6$.', 'Two: $12$.'],
    tags: ['composite'], estimatedSeconds: 55,
  },
  {
    domain: '6.G', num: 49, unit: 5, order: 9, slug: 'comp-rect-plus-tri',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A shape combines a $5 \\times 4$ rectangle with a triangle (base $5$, height $2$). Find the total area.',
    answerType: 'numeric', primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add the areas.' },
      { level: 'guide', text: '$20 + 5$.' },
      { level: 'reveal', text: '$25$.' },
    ],
    explanation: ['$20 + 5 = 25$.'],
    tags: ['composite'], estimatedSeconds: 50,
  },
  {
    domain: '6.G', num: 50, unit: 5, order: 10, slug: 'comp-pool',
    standard: '6.G.A.1', difficulty: 3,
    prompt: 'A backyard is $20 \\times 30$ ft. The rectangular pool is $5 \\times 10$ ft. Find the **non-pool** area.',
    answerType: 'numeric', primaryAnswer: '550', alternativeAnswers: ['550 sq ft'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Total minus pool.' },
      { level: 'guide', text: '$600 - 50$.' },
      { level: 'reveal', text: '$550$.' },
    ],
    explanation: ['$600 - 50 = 550$ sq ft.'],
    tags: ['CA', 'composite', 'word'], estimatedSeconds: 75,
  },

  // ---------------- UNIT 6 — Mixed application (1-10) ----------------
  {
    domain: '6.G', num: 51, unit: 6, order: 1, slug: 'mix-room-area',
    standard: '6.G.A.1', difficulty: 1,
    prompt: 'A room is $12 \\times 10$ ft. Find its area.',
    answerType: 'numeric', primaryAnswer: '120', alternativeAnswers: ['120 sq ft'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$A = l \\times w$.' },
      { level: 'guide', text: '$12 \\times 10$.' },
      { level: 'reveal', text: '$120$.' },
    ],
    explanation: ['$A = 12 \\times 10 = 120$ sq ft.'],
    tags: ['area', 'word'], estimatedSeconds: 30,
  },
  {
    domain: '6.G', num: 52, unit: 6, order: 2, slug: 'mix-vol-tank',
    standard: '6.G.A.2', difficulty: 2,
    prompt: 'A water tank is $4$ ft × $5$ ft × $3$ ft. Find its volume in ft³.',
    answerType: 'numeric', primaryAnswer: '60', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply all three.' },
      { level: 'guide', text: '$4 \\times 5 \\times 3$.' },
      { level: 'reveal', text: '$60$.' },
    ],
    explanation: ['$V = 60$ ft³.'],
    tags: ['volume', 'word'], estimatedSeconds: 40,
  },
  {
    domain: '6.G', num: 53, unit: 6, order: 3, slug: 'mix-grid-rect',
    standard: '6.G.A.3', difficulty: 2,
    prompt: 'A rectangle has corners $(2, 1)$ and $(6, 5)$ as opposite vertices, with sides parallel to the axes. Find its area.',
    answerType: 'numeric', primaryAnswer: '16', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Width: $|6 - 2| = 4$. Height: $|5 - 1| = 4$.' },
      { level: 'guide', text: 'Area $= 4 \\times 4$.' },
      { level: 'reveal', text: '$16$.' },
    ],
    explanation: ['Width $4$, height $4$. Area $= 16$.'],
    tags: ['coord', 'area'], estimatedSeconds: 60,
  },
  {
    domain: '6.G', num: 54, unit: 6, order: 4, slug: 'mix-fence',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A rectangular garden is $15$ ft × $10$ ft. How much fencing for the perimeter?',
    answerType: 'numeric', primaryAnswer: '50', alternativeAnswers: ['50 ft'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$P = 2(l + w)$.' },
      { level: 'guide', text: '$2(15 + 10) = 2(25)$.' },
      { level: 'reveal', text: '$50$.' },
    ],
    explanation: ['$P = 2(15 + 10) = 50$ ft.'],
    tags: ['CA', 'perimeter', 'word'], estimatedSeconds: 55,
  },
  {
    domain: '6.G', num: 55, unit: 6, order: 5, slug: 'mix-paint-sa',
    standard: '6.G.A.4', difficulty: 3,
    prompt: 'You paint all faces of a cube with side $3$ ft. How many square feet?',
    answerType: 'numeric', primaryAnswer: '54', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Surface area of cube: $6s^2$.' },
      { level: 'guide', text: '$6 \\times 9$.' },
      { level: 'reveal', text: '$54$.' },
    ],
    explanation: ['$SA = 6(3)^2 = 54$ sq ft.'],
    tags: ['surface-area', 'word'], estimatedSeconds: 55,
  },
  {
    domain: '6.G', num: 56, unit: 6, order: 6, slug: 'mix-tri-roof',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A triangular roof piece has base $12$ ft and height $5$ ft. Find its area.',
    answerType: 'numeric', primaryAnswer: '30', alternativeAnswers: ['30 sq ft'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$\\frac{1}{2} b h$.' },
      { level: 'guide', text: '$\\frac{1}{2}(12)(5)$.' },
      { level: 'reveal', text: '$30$.' },
    ],
    explanation: ['$A = \\frac{1}{2}(12)(5) = 30$ sq ft.'],
    tags: ['triangle', 'word'], estimatedSeconds: 45,
  },
  {
    domain: '6.G', num: 57, unit: 6, order: 7, slug: 'mix-box-fit',
    standard: '6.G.A.2', difficulty: 3,
    prompt: 'How many $1$ cm cubes fit in a $4 \\times 3 \\times 5$ cm box?',
    answerType: 'numeric', primaryAnswer: '60', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Volume in cubic cm = number of unit cubes.' },
      { level: 'guide', text: '$4 \\times 3 \\times 5$.' },
      { level: 'reveal', text: '$60$.' },
    ],
    explanation: ['Volume $= 60$ cubic cm. So $60$ unit cubes.'],
    tags: ['MAP-practice', 'volume'], estimatedSeconds: 60,
  },
  {
    domain: '6.G', num: 58, unit: 6, order: 8, slug: 'mix-perim-side',
    standard: '6.G.A.1', difficulty: 2,
    prompt: 'A regular hexagon has $6$ equal sides each $4$ cm. Find its perimeter.',
    answerType: 'numeric', primaryAnswer: '24', alternativeAnswers: ['24 cm'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add all sides — or multiply.' },
      { level: 'guide', text: '$6 \\times 4$.' },
      { level: 'reveal', text: '$24$.' },
    ],
    explanation: ['$P = 6 \\times 4 = 24$ cm.'],
    tags: ['perimeter'], estimatedSeconds: 40,
  },
  {
    domain: '6.G', num: 59, unit: 6, order: 9, slug: 'mix-comp-pool',
    standard: '6.G.A.1', difficulty: 3,
    prompt: 'A patio is L-shaped: $8 \\times 6$ minus a $3 \\times 2$ corner. Find the area.',
    answerType: 'numeric', primaryAnswer: '42', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$48 - 6$.' },
      { level: 'guide', text: 'Big minus cut.' },
      { level: 'reveal', text: '$42$.' },
    ],
    explanation: ['$48 - 6 = 42$.'],
    tags: ['CA', 'composite', 'word'], estimatedSeconds: 65,
  },
  {
    domain: '6.G', num: 60, unit: 6, order: 10, slug: 'mix-vol-find',
    standard: '6.G.A.2', difficulty: 3,
    prompt: 'A box is $\\frac{1}{2}$ m wide, $1$ m long, $2$ m tall. Find its volume in m³.',
    answerType: 'numeric', primaryAnswer: '1', alternativeAnswers: ['1 m³'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply: $\\frac{1}{2} \\cdot 1 \\cdot 2$.' },
      { level: 'guide', text: '$\\frac{1}{2} \\cdot 2 = 1$.' },
      { level: 'reveal', text: '$1$ m³.' },
    ],
    explanation: ['$V = \\frac{1}{2} \\cdot 1 \\cdot 2 = 1$ m³.'],
    tags: ['volume', 'fraction'], estimatedSeconds: 50,
  },
];
