import type { SeedProblem } from './types';

// 6.NS — The Number System
// Adds 52 new (5 to U1, 7 to U2, 10 each to U3-U6).

export const problems6NS: SeedProblem[] = [
  // ---------------- UNIT 1 — Intro: fractions, decimals, GCF (orders 6-10) ----------------
  {
    domain: '6.NS', num: 9, unit: 1, order: 6, slug: 'fraction-divide-basic',
    standard: '6.NS.A.1', difficulty: 1,
    prompt: 'Compute $\\frac{1}{2} \\div \\frac{1}{4}$.',
    answerType: 'fraction',
    primaryAnswer: '2', alternativeAnswers: ['2/1'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Dividing by a fraction is the same as multiplying by its **reciprocal**.' },
      { level: 'guide', text: '$\\frac{1}{2} \\div \\frac{1}{4} = \\frac{1}{2} \\times \\frac{4}{1}$.' },
      { level: 'reveal', text: '$\\frac{1}{2} \\times 4 = 2$.' },
    ],
    explanation: ['Flip the divisor: $\\frac{1}{4} \\to \\frac{4}{1}$.', 'Multiply: $\\frac{1}{2} \\cdot \\frac{4}{1} = \\frac{4}{2} = 2$.'],
    tags: ['fraction-division'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 10, unit: 1, order: 7, slug: 'decimal-add',
    standard: '6.NS.B.3', difficulty: 1,
    prompt: 'Add: $2.45 + 1.7$.',
    answerType: 'numeric',
    primaryAnswer: '4.15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Line up the decimal points.' },
      { level: 'guide', text: 'Rewrite $1.7$ as $1.70$ for the same place values.' },
      { level: 'reveal', text: '$2.45 + 1.70 = 4.15$.' },
    ],
    explanation: ['Align decimals: $2.45 + 1.70$.', 'Add column-by-column: $4.15$.'],
    tags: ['decimal'], estimatedSeconds: 30,
  },
  {
    domain: '6.NS', num: 11, unit: 1, order: 8, slug: 'decimal-subtract',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'Subtract: $5.6 - 2.84$.',
    answerType: 'numeric',
    primaryAnswer: '2.76', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Line up the decimal points.' },
      { level: 'guide', text: 'Rewrite as $5.60 - 2.84$.' },
      { level: 'reveal', text: 'Borrow as needed: $5.60 - 2.84 = 2.76$.' },
    ],
    explanation: ['Align: $5.60 - 2.84$.', 'Subtract: $2.76$.'],
    tags: ['decimal'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 12, unit: 1, order: 9, slug: 'long-division',
    standard: '6.NS.B.2', difficulty: 2,
    prompt: 'Compute $156 \\div 12$.',
    answerType: 'numeric',
    primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'How many $12$s in $156$?' },
      { level: 'guide', text: '$12 \\times 10 = 120$. Subtract from $156$: $36$. How many $12$s in $36$?' },
      { level: 'reveal', text: '$10 + 3 = 13$.' },
    ],
    explanation: ['$12 \\times 10 = 120$, $156 - 120 = 36$.', '$12 \\times 3 = 36$. Total: $13$.'],
    tags: ['long-division'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 13, unit: 1, order: 10, slug: 'mixed-frac-divide',
    standard: '6.NS.A.1', difficulty: 3,
    prompt: 'How many $\\frac{1}{3}$ cup servings are in $2$ cups?',
    answerType: 'numeric',
    primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You\'re dividing $2 \\div \\frac{1}{3}$.' },
      { level: 'guide', text: 'Flip and multiply: $2 \\times 3$.' },
      { level: 'reveal', text: '$2 \\times 3 = 6$ servings.' },
    ],
    explanation: ['$2 \\div \\frac{1}{3} = 2 \\times \\frac{3}{1} = 6$.', 'There are $6$ servings.'],
    tags: ['CA', 'fraction-division', 'word'], estimatedSeconds: 60,
  },

  // ---------------- UNIT 2 — Multi-digit operations (orders 4-10) ----------------
  {
    domain: '6.NS', num: 14, unit: 2, order: 4, slug: 'mult-decimal',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'Multiply: $0.6 \\times 0.4$.',
    answerType: 'numeric',
    primaryAnswer: '0.24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Ignore decimals first: $6 \\times 4 = 24$.' },
      { level: 'guide', text: 'Count decimal places: $0.6$ has $1$, $0.4$ has $1$. Total: $2$.' },
      { level: 'reveal', text: 'Move the decimal $2$ places left: $0.24$.' },
    ],
    explanation: ['$6 \\times 4 = 24$.', '$1 + 1 = 2$ decimal places.', 'Result: $0.24$.'],
    tags: ['decimal', 'multiply'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 15, unit: 2, order: 5, slug: 'divide-decimal',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'Divide: $4.8 \\div 6$.',
    answerType: 'numeric',
    primaryAnswer: '0.8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$48 \\div 6 = 8$. Now place the decimal.' },
      { level: 'guide', text: '$4.8 \\div 6$ — same as $48 \\div 6 = 8$ with one decimal place.' },
      { level: 'reveal', text: '$4.8 \\div 6 = 0.8$.' },
    ],
    explanation: ['$48 \\div 6 = 8$.', 'Keep decimal place: $0.8$.'],
    tags: ['decimal', 'divide'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 16, unit: 2, order: 6, slug: 'mult-digit',
    standard: '6.NS.B.2', difficulty: 2,
    prompt: 'Multiply: $24 \\times 35$.',
    answerType: 'numeric',
    primaryAnswer: '840', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Split: $24 \\times 35 = 24 \\times 30 + 24 \\times 5$.' },
      { level: 'guide', text: '$24 \\times 30 = 720$ and $24 \\times 5 = 120$.' },
      { level: 'reveal', text: '$720 + 120 = 840$.' },
    ],
    explanation: ['$24 \\times 30 = 720$.', '$24 \\times 5 = 120$.', 'Sum: $840$.'],
    tags: ['multiply', 'multi-digit'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 17, unit: 2, order: 7, slug: 'long-div-remainder',
    standard: '6.NS.B.2', difficulty: 2,
    prompt: 'Compute $173 \\div 8$ and give the answer as a **decimal**.',
    answerType: 'numeric',
    primaryAnswer: '21.625', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.001,
    hints: [
      { level: 'nudge', text: '$8 \\times 21 = 168$. What\'s left over?' },
      { level: 'guide', text: 'Remainder is $5$. Keep dividing: $50 \\div 8 = 6$ remainder $2$, etc.' },
      { level: 'reveal', text: '$173 \\div 8 = 21.625$.' },
    ],
    explanation: ['$8 \\times 21 = 168$, remainder $5$.', 'Decimal: $5 \\div 8 = 0.625$.', 'Total: $21.625$.'],
    tags: ['long-division', 'decimal'], estimatedSeconds: 75,
  },
  {
    domain: '6.NS', num: 18, unit: 2, order: 8, slug: 'money-add',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'You buy items for \\$$4.75$, \\$$3.20$, and \\$$1.05$. What is the total?',
    answerType: 'numeric',
    primaryAnswer: '9', alternativeAnswers: ['$9', '$9.00', '9.00'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add carefully — line up decimals.' },
      { level: 'guide', text: '$4.75 + 3.20 = 7.95$.' },
      { level: 'reveal', text: '$7.95 + 1.05 = 9.00$.' },
    ],
    explanation: ['$4.75 + 3.20 = 7.95$.', '$7.95 + 1.05 = 9.00$.'],
    tags: ['CA', 'decimal', 'money'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 19, unit: 2, order: 9, slug: 'divide-by-decimal',
    standard: '6.NS.B.3', difficulty: 3,
    prompt: 'Compute $1.5 \\div 0.3$.',
    answerType: 'numeric',
    primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply both numbers by $10$ to remove the decimal in the divisor.' },
      { level: 'guide', text: '$1.5 \\div 0.3 = 15 \\div 3$.' },
      { level: 'reveal', text: '$15 \\div 3 = 5$.' },
    ],
    explanation: ['$1.5 \\div 0.3 = \\frac{15}{3} = 5$.'],
    tags: ['decimal', 'divide'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 20, unit: 2, order: 10, slug: 'multi-step-decimal',
    standard: '6.NS.B.3', difficulty: 3,
    prompt: 'Each pencil costs \\$$0.25$. How many can you buy with \\$$3.00$?',
    answerType: 'numeric',
    primaryAnswer: '12', alternativeAnswers: ['12 pencils'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide total dollars by cost per pencil.' },
      { level: 'guide', text: '$3.00 \\div 0.25 = ?$' },
      { level: 'reveal', text: '$3 \\div 0.25 = 12$ pencils.' },
    ],
    explanation: ['$3 \\div 0.25 = 12$.', 'You can buy $12$ pencils.'],
    tags: ['MAP-practice', 'decimal', 'money'], estimatedSeconds: 65,
  },

  // ---------------- UNIT 3 — GCF/LCM/Factors (1-10) ----------------
  {
    domain: '6.NS', num: 21, unit: 3, order: 1, slug: 'gcf-basic',
    standard: '6.NS.B.4', difficulty: 1,
    prompt: 'Find the GCF (greatest common factor) of $12$ and $18$.',
    answerType: 'numeric',
    primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'List factors of each, find the largest in both.' },
      { level: 'guide', text: 'Factors of $12$: $1, 2, 3, 4, 6, 12$. Factors of $18$: $1, 2, 3, 6, 9, 18$.' },
      { level: 'reveal', text: 'Common factors: $1, 2, 3, 6$. Greatest: $6$.' },
    ],
    explanation: ['Factors of $12$: $1, 2, 3, 4, 6, 12$.', 'Factors of $18$: $1, 2, 3, 6, 9, 18$.', 'GCF $= 6$.'],
    tags: ['gcf'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 22, unit: 3, order: 2, slug: 'lcm-basic',
    standard: '6.NS.B.4', difficulty: 1,
    prompt: 'Find the LCM (least common multiple) of $4$ and $6$.',
    answerType: 'numeric',
    primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'List multiples of each, find the smallest in both.' },
      { level: 'guide', text: 'Multiples of $4$: $4, 8, 12, 16, \\ldots$. Multiples of $6$: $6, 12, 18, \\ldots$' },
      { level: 'reveal', text: 'Smallest common multiple: $12$.' },
    ],
    explanation: ['Multiples of $4$: $4, 8, \\mathbf{12}, 16$.', 'Multiples of $6$: $6, \\mathbf{12}, 18$.', 'LCM $= 12$.'],
    tags: ['lcm'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 23, unit: 3, order: 3, slug: 'gcf-24-36',
    standard: '6.NS.B.4', difficulty: 2,
    prompt: 'Find the GCF of $24$ and $36$.',
    answerType: 'numeric',
    primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Try common factors of $24$ and $36$.' },
      { level: 'guide', text: 'Both are divisible by $12$.' },
      { level: 'reveal', text: '$24 = 12 \\times 2$, $36 = 12 \\times 3$. GCF $= 12$.' },
    ],
    explanation: ['$24 = 2^3 \\times 3$.', '$36 = 2^2 \\times 3^2$.', 'GCF $= 2^2 \\times 3 = 12$.'],
    tags: ['gcf'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 24, unit: 3, order: 4, slug: 'lcm-3-5',
    standard: '6.NS.B.4', difficulty: 1,
    prompt: 'Find the LCM of $3$ and $5$.',
    answerType: 'numeric',
    primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'When numbers share no factors, LCM is their product.' },
      { level: 'guide', text: '$3 \\times 5 = ?$' },
      { level: 'reveal', text: '$15$.' },
    ],
    explanation: ['$3$ and $5$ share no common factors.', 'LCM $= 3 \\times 5 = 15$.'],
    tags: ['lcm'], estimatedSeconds: 35,
  },
  {
    domain: '6.NS', num: 25, unit: 3, order: 5, slug: 'distributive-factor',
    standard: '6.NS.B.4', difficulty: 2,
    prompt: 'Use the distributive property to rewrite $24 + 32$ as a multiplication.',
    answerType: 'short-text',
    primaryAnswer: '8(3+4)', alternativeAnswers: ['8 (3+4)', '8 × (3 + 4)', '8*(3+4)'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find GCF of $24$ and $32$ first.' },
      { level: 'guide', text: 'GCF is $8$. So $24 = 8 \\times 3$ and $32 = 8 \\times 4$.' },
      { level: 'reveal', text: '$24 + 32 = 8(3 + 4)$.' },
    ],
    explanation: ['GCF of $24$ and $32$ is $8$.', 'Factor: $24 + 32 = 8 \\times 3 + 8 \\times 4 = 8(3+4)$.'],
    tags: ['CA', 'gcf', 'distributive'], estimatedSeconds: 75,
  },
  {
    domain: '6.NS', num: 26, unit: 3, order: 6, slug: 'lcm-word',
    standard: '6.NS.B.4', difficulty: 3,
    prompt: 'Two friends visit a park: Ana every $4$ days, Ben every $6$ days. In how many days will they both visit on the same day next?',
    answerType: 'numeric',
    primaryAnswer: '12', alternativeAnswers: ['12 days'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You need the LCM of $4$ and $6$.' },
      { level: 'guide', text: 'Smallest number that\'s a multiple of both $4$ and $6$.' },
      { level: 'reveal', text: 'LCM$(4, 6) = 12$.' },
    ],
    explanation: ['Ana: $4, 8, 12, \\ldots$', 'Ben: $6, 12, \\ldots$', 'Both on day $12$.'],
    tags: ['CA', 'lcm', 'word'], estimatedSeconds: 70,
  },
  {
    domain: '6.NS', num: 27, unit: 3, order: 7, slug: 'gcf-word',
    standard: '6.NS.B.4', difficulty: 3,
    prompt: 'You have $18$ apples and $24$ oranges. What is the **greatest** number of identical fruit baskets you can make using all the fruit?',
    answerType: 'numeric',
    primaryAnswer: '6', alternativeAnswers: ['6 baskets'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You need GCF of $18$ and $24$.' },
      { level: 'guide', text: 'Find the largest factor that divides both $18$ and $24$.' },
      { level: 'reveal', text: 'GCF $= 6$. So $6$ baskets ($3$ apples + $4$ oranges each).' },
    ],
    explanation: ['GCF of $18$ and $24$ is $6$.', '$6$ baskets, each with $3$ apples and $4$ oranges.'],
    tags: ['MAP-practice', 'gcf', 'word'], estimatedSeconds: 70,
  },
  {
    domain: '6.NS', num: 28, unit: 3, order: 8, slug: 'factor-list',
    standard: '6.NS.B.4', difficulty: 1,
    prompt: 'How many factors does $20$ have?',
    answerType: 'numeric',
    primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'List them: $1$ × what?' },
      { level: 'guide', text: '$1, 2, 4, 5, 10, 20$.' },
      { level: 'reveal', text: 'That\'s $6$ factors.' },
    ],
    explanation: ['Factors of $20$: $1, 2, 4, 5, 10, 20$.', 'Count: $6$.'],
    tags: ['factors'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 29, unit: 3, order: 9, slug: 'mc-prime',
    standard: '6.NS.B.4', difficulty: 1,
    prompt: 'Which number is **prime**?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$9$', correct: false },
      { id: 'B', label: '$15$', correct: false },
      { id: 'C', label: '$17$', correct: true },
      { id: 'D', label: '$21$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'A prime number has only $1$ and itself as factors.' },
      { level: 'guide', text: '$9 = 3 \\times 3$, $15 = 3 \\times 5$, $21 = 3 \\times 7$.' },
      { level: 'reveal', text: '$17$ has no factors except $1$ and $17$.' },
    ],
    explanation: ['$9, 15, 21$ all have factors besides $1$ and themselves.', '$17$ is prime.'],
    tags: ['prime'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 30, unit: 3, order: 10, slug: 'gcf-lcm-mixed',
    standard: '6.NS.B.4', difficulty: 3,
    prompt: 'Find the LCM of $8$ and $12$.',
    answerType: 'numeric',
    primaryAnswer: '24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'List multiples until you find a common one.' },
      { level: 'guide', text: 'Multiples of $8$: $8, 16, 24, 32$. Multiples of $12$: $12, 24, 36$.' },
      { level: 'reveal', text: 'Smallest match: $24$.' },
    ],
    explanation: ['Multiples of $8$: $8, 16, \\mathbf{24}$.', 'Multiples of $12$: $12, \\mathbf{24}$.', 'LCM $= 24$.'],
    tags: ['lcm'], estimatedSeconds: 50,
  },

  // ---------------- UNIT 4 — Integers & absolute value (1-10) ----------------
  {
    domain: '6.NS', num: 31, unit: 4, order: 1, slug: 'integer-real-world',
    standard: '6.NS.C.5', difficulty: 1,
    prompt: 'A diver is $30$ feet **below** sea level. Represent this as an integer.',
    answerType: 'numeric',
    primaryAnswer: '-30', alternativeAnswers: ['−30', '-30 ft'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Below" sea level means negative.' },
      { level: 'guide', text: 'Sea level is $0$. Below is negative.' },
      { level: 'reveal', text: '$-30$ feet.' },
    ],
    explanation: ['Below sea level is negative.', 'Answer: $-30$ feet.'],
    tags: ['integer', 'word'], estimatedSeconds: 35,
  },
  {
    domain: '6.NS', num: 32, unit: 4, order: 2, slug: 'integer-opposite',
    standard: '6.NS.C.6.a', difficulty: 1,
    prompt: 'What is the opposite of $-7$?',
    answerType: 'numeric',
    primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Opposite means flip the sign.' },
      { level: 'guide', text: '$-(-7) = ?$' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['The opposite of $-7$ is $7$.'],
    tags: ['integer', 'opposite'], estimatedSeconds: 25,
  },
  {
    domain: '6.NS', num: 33, unit: 4, order: 3, slug: 'abs-value-basic',
    standard: '6.NS.C.7.c', difficulty: 1,
    prompt: 'Compute $|{-8}|$.',
    answerType: 'numeric',
    primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Absolute value is the distance from $0$ — always non-negative.' },
      { level: 'guide', text: 'How far is $-8$ from $0$?' },
      { level: 'reveal', text: '$8$ units.' },
    ],
    explanation: ['$|{-8}|$ is the distance from $-8$ to $0$.', 'That distance is $8$.'],
    tags: ['absolute-value'], estimatedSeconds: 30,
  },
  {
    domain: '6.NS', num: 34, unit: 4, order: 4, slug: 'integer-compare',
    standard: '6.NS.C.7.a', difficulty: 2,
    prompt: 'Which is greater: $-3$ or $-8$?',
    answerType: 'numeric',
    primaryAnswer: '-3', alternativeAnswers: ['−3'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'On a number line, greater means further right.' },
      { level: 'guide', text: '$-3$ is to the right of $-8$.' },
      { level: 'reveal', text: '$-3 > -8$.' },
    ],
    explanation: ['On the number line, $-3$ is to the right of $-8$.', '$-3$ is greater.'],
    tags: ['integer', 'compare'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 35, unit: 4, order: 5, slug: 'order-integers',
    standard: '6.NS.C.7.a', difficulty: 2,
    prompt: 'Order from least to greatest: $5, -2, 0, -7, 3$. What is the **second** number?',
    answerType: 'numeric',
    primaryAnswer: '-2', alternativeAnswers: ['−2'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Smallest first — that\'s the most negative.' },
      { level: 'guide', text: 'Sorted: $-7, -2, 0, 3, 5$.' },
      { level: 'reveal', text: 'Second is $-2$.' },
    ],
    explanation: ['Ordered: $-7, -2, 0, 3, 5$.', 'Second: $-2$.'],
    tags: ['integer', 'order'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 36, unit: 4, order: 6, slug: 'temperature',
    standard: '6.NS.C.5', difficulty: 2,
    prompt: 'The temperature was $-3°$F at $6$ a.m. and rose by $12°$F by noon. What is the noon temperature?',
    answerType: 'numeric',
    primaryAnswer: '9', alternativeAnswers: ['9°F', '9 degrees'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Rose" means add.' },
      { level: 'guide', text: '$-3 + 12 = ?$' },
      { level: 'reveal', text: '$-3 + 12 = 9$.' },
    ],
    explanation: ['$-3 + 12 = 9$.', 'Noon temperature: $9°$F.'],
    tags: ['CA', 'integer', 'word'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 37, unit: 4, order: 7, slug: 'abs-bank',
    standard: '6.NS.C.7.c', difficulty: 2,
    prompt: 'A bank statement shows $-\\$45$ (overdraft). What is the size of the debt?',
    answerType: 'numeric',
    primaryAnswer: '45', alternativeAnswers: ['$45'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Size" of debt means absolute value.' },
      { level: 'guide', text: '$|{-45}| = ?$' },
      { level: 'reveal', text: '$45$.' },
    ],
    explanation: ['$|{-45}| = 45$.', 'Debt size: \\$$45$.'],
    tags: ['absolute-value', 'word'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 38, unit: 4, order: 8, slug: 'inequality-pair',
    standard: '6.NS.C.7.b', difficulty: 2,
    prompt: 'Which symbol makes this true: $-15 \\ ?\\ -10$? Type $<$ or $>$.',
    answerType: 'short-text',
    primaryAnswer: '<', alternativeAnswers: ['less than'],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'More negative means smaller.' },
      { level: 'guide', text: '$-15$ is further left of $-10$ on the number line.' },
      { level: 'reveal', text: '$-15 < -10$.' },
    ],
    explanation: ['$-15$ is to the left of $-10$.', 'So $-15 < -10$.'],
    tags: ['integer', 'compare'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 39, unit: 4, order: 9, slug: 'integer-add',
    standard: '6.NS.C.7', difficulty: 3,
    prompt: 'Compute $-5 + 8$.',
    answerType: 'numeric',
    primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Start at $-5$ on the number line and move $8$ right.' },
      { level: 'guide', text: 'You\'ll pass $0$ and end up at $3$.' },
      { level: 'reveal', text: '$-5 + 8 = 3$.' },
    ],
    explanation: ['Start at $-5$, move $8$ right: $-5 \\to 0 \\to 3$.', 'Result: $3$.'],
    tags: ['integer', 'add'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 40, unit: 4, order: 10, slug: 'abs-distance',
    standard: '6.NS.C.7.c', difficulty: 3,
    prompt: 'On a number line, what is the **distance** between $-4$ and $7$?',
    answerType: 'numeric',
    primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Distance is always positive.' },
      { level: 'guide', text: 'Subtract and take absolute value: $|7 - (-4)|$.' },
      { level: 'reveal', text: '$|7 - (-4)| = |11| = 11$.' },
    ],
    explanation: ['Distance $= |7 - (-4)| = |7 + 4| = 11$.'],
    tags: ['MAP-practice', 'absolute-value', 'distance'], estimatedSeconds: 60,
  },

  // ---------------- UNIT 5 — Coordinate plane (1-10) ----------------
  {
    domain: '6.NS', num: 41, unit: 5, order: 1, slug: 'plot-point',
    standard: '6.NS.C.6.b', difficulty: 1,
    prompt: 'In which quadrant is the point $(3, -5)$?',
    answerType: 'numeric',
    primaryAnswer: '4', alternativeAnswers: ['IV', 'iv', 'four', 'quadrant 4'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$x$ positive, $y$ negative — which quadrant?' },
      { level: 'guide', text: 'Quadrant I is upper-right ($+,+$). Quadrant IV is lower-right ($+,-$).' },
      { level: 'reveal', text: 'Quadrant IV (or $4$).' },
    ],
    explanation: ['$x = 3 > 0$, $y = -5 < 0$ → lower-right.', 'Quadrant IV.'],
    tags: ['coordinate'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 42, unit: 5, order: 2, slug: 'reflect-y',
    standard: '6.NS.C.6.b', difficulty: 2,
    prompt: 'Reflect $(2, 4)$ across the $y$-axis. What is the new point?',
    answerType: 'short-text',
    primaryAnswer: '(-2, 4)', alternativeAnswers: ['(-2,4)', '-2, 4', '-2,4'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Reflecting across the $y$-axis flips the sign of $x$.' },
      { level: 'guide', text: '$(2, 4) \\to (-2, 4)$.' },
      { level: 'reveal', text: 'Answer: $(-2, 4)$.' },
    ],
    explanation: ['Across $y$-axis: flip $x$, keep $y$.', '$(2, 4) \\to (-2, 4)$.'],
    tags: ['coordinate', 'reflect'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 43, unit: 5, order: 3, slug: 'reflect-x',
    standard: '6.NS.C.6.b', difficulty: 2,
    prompt: 'Reflect $(-3, 5)$ across the $x$-axis. What is the new point?',
    answerType: 'short-text',
    primaryAnswer: '(-3, -5)', alternativeAnswers: ['(-3,-5)', '-3, -5', '-3,-5'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Reflecting across the $x$-axis flips the sign of $y$.' },
      { level: 'guide', text: '$(-3, 5) \\to (-3, -5)$.' },
      { level: 'reveal', text: 'Answer: $(-3, -5)$.' },
    ],
    explanation: ['Across $x$-axis: keep $x$, flip $y$.', '$(-3, 5) \\to (-3, -5)$.'],
    tags: ['coordinate', 'reflect'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 44, unit: 5, order: 4, slug: 'distance-x-axis',
    standard: '6.NS.C.8', difficulty: 2,
    prompt: 'Find the distance between $(2, 5)$ and $(2, -3)$.',
    answerType: 'numeric',
    primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$x$ is the same, so the distance is just the $y$ difference (absolute value).' },
      { level: 'guide', text: '$|5 - (-3)| = ?$' },
      { level: 'reveal', text: '$|5 + 3| = 8$.' },
    ],
    explanation: ['Same $x$, so distance $= |5 - (-3)| = |8| = 8$.'],
    tags: ['coordinate', 'distance'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 45, unit: 5, order: 5, slug: 'distance-y-axis',
    standard: '6.NS.C.8', difficulty: 2,
    prompt: 'Find the distance between $(-4, 1)$ and $(6, 1)$.',
    answerType: 'numeric',
    primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$y$ is the same, so distance is the $x$ difference (absolute value).' },
      { level: 'guide', text: '$|6 - (-4)| = ?$' },
      { level: 'reveal', text: '$|10| = 10$.' },
    ],
    explanation: ['Same $y$, so distance $= |6 - (-4)| = 10$.'],
    tags: ['coordinate', 'distance'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 46, unit: 5, order: 6, slug: 'quadrant-rule',
    standard: '6.NS.C.6.b', difficulty: 1,
    prompt: 'Which quadrant has BOTH $x < 0$ and $y < 0$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'I', correct: false },
      { id: 'B', label: 'II', correct: false },
      { id: 'C', label: 'III', correct: true },
      { id: 'D', label: 'IV', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Both negative is the lower-left.' },
      { level: 'guide', text: 'Quadrant III is lower-left ($-,-$).' },
      { level: 'reveal', text: 'III.' },
    ],
    explanation: ['Lower-left quadrant has $x < 0$ and $y < 0$ → Quadrant III.'],
    tags: ['coordinate', 'quadrant'], estimatedSeconds: 35,
  },
  {
    domain: '6.NS', num: 47, unit: 5, order: 7, slug: 'identify-point',
    standard: '6.NS.C.6.c', difficulty: 1,
    prompt: 'A point is $4$ units right of the origin and $2$ units down. What are its coordinates?',
    answerType: 'short-text',
    primaryAnswer: '(4, -2)', alternativeAnswers: ['(4,-2)', '4, -2', '4,-2'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Right is positive $x$, down is negative $y$.' },
      { level: 'guide', text: '$x = 4$, $y = -2$.' },
      { level: 'reveal', text: '$(4, -2)$.' },
    ],
    explanation: ['Right $4$: $x = 4$. Down $2$: $y = -2$.', '$(4, -2)$.'],
    tags: ['coordinate'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 48, unit: 5, order: 8, slug: 'rect-perim',
    standard: '6.NS.C.8', difficulty: 3,
    prompt: 'A rectangle has corners at $(1, 2), (1, 6), (5, 2), (5, 6)$. What is its **perimeter**?',
    answerType: 'numeric',
    primaryAnswer: '16', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find length and width from coordinates.' },
      { level: 'guide', text: 'Width: $|5 - 1| = 4$. Height: $|6 - 2| = 4$.' },
      { level: 'reveal', text: 'Perimeter $= 2(4 + 4) = 16$.' },
    ],
    explanation: ['Width: $4$. Height: $4$.', 'Perimeter $= 2(4) + 2(4) = 16$.'],
    tags: ['CA', 'coordinate', 'perimeter'], estimatedSeconds: 85,
  },
  {
    domain: '6.NS', num: 49, unit: 5, order: 9, slug: 'quadrant-mc',
    standard: '6.NS.C.6.b', difficulty: 2,
    prompt: 'Which point is in Quadrant II?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$(3, 5)$', correct: false },
      { id: 'B', label: '$(-2, 4)$', correct: true },
      { id: 'C', label: '$(-1, -1)$', correct: false },
      { id: 'D', label: '$(4, -7)$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Quadrant II: $x < 0$, $y > 0$.' },
      { level: 'guide', text: 'Find the point with negative $x$ and positive $y$.' },
      { level: 'reveal', text: '$(-2, 4)$.' },
    ],
    explanation: ['Quadrant II: upper-left, $x < 0$, $y > 0$.', '$(-2, 4)$ fits.'],
    tags: ['coordinate'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 50, unit: 5, order: 10, slug: 'origin-distance',
    standard: '6.NS.C.8', difficulty: 2,
    prompt: 'What is the distance from $(0, 0)$ to $(0, 7)$?',
    answerType: 'numeric',
    primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Same $x$ — vertical distance.' },
      { level: 'guide', text: '$|7 - 0| = ?$' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['Distance from origin to $(0, 7)$ is $7$ units.'],
    tags: ['coordinate', 'distance'], estimatedSeconds: 30,
  },

  // ---------------- UNIT 6 — Mixed (1-10) ----------------
  {
    domain: '6.NS', num: 51, unit: 6, order: 1, slug: 'm-frac-mult',
    standard: '6.NS.A.1', difficulty: 1,
    prompt: 'Compute $\\frac{2}{3} \\times \\frac{3}{4}$.',
    answerType: 'fraction',
    primaryAnswer: '1/2', alternativeAnswers: ['0.5', '2/4', '6/12'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply numerators and denominators.' },
      { level: 'guide', text: '$\\frac{2 \\times 3}{3 \\times 4} = \\frac{6}{12}$.' },
      { level: 'reveal', text: 'Simplify: $\\frac{6}{12} = \\frac{1}{2}$.' },
    ],
    explanation: ['$\\frac{2}{3} \\times \\frac{3}{4} = \\frac{6}{12} = \\frac{1}{2}$.'],
    tags: ['fraction', 'multiply'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 52, unit: 6, order: 2, slug: 'm-decimal-pct',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'What is $0.15 \\times 80$?',
    answerType: 'numeric',
    primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$0.15 = 15\\%$.' },
      { level: 'guide', text: '$10\\%$ of $80$ is $8$. $5\\%$ is $4$.' },
      { level: 'reveal', text: '$8 + 4 = 12$.' },
    ],
    explanation: ['$0.15 \\times 80 = 12$.'],
    tags: ['decimal', 'percent'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 53, unit: 6, order: 3, slug: 'm-integer-subtract',
    standard: '6.NS.C.7', difficulty: 2,
    prompt: 'Compute $4 - (-2)$.',
    answerType: 'numeric',
    primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Subtracting a negative is adding.' },
      { level: 'guide', text: '$4 - (-2) = 4 + 2$.' },
      { level: 'reveal', text: '$6$.' },
    ],
    explanation: ['$4 - (-2) = 4 + 2 = 6$.'],
    tags: ['integer'], estimatedSeconds: 35,
  },
  {
    domain: '6.NS', num: 54, unit: 6, order: 4, slug: 'm-fraction-divide-mc',
    standard: '6.NS.A.1', difficulty: 2,
    prompt: 'Which equals $\\frac{2}{5} \\div \\frac{1}{10}$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$\\frac{1}{25}$', correct: false },
      { id: 'B', label: '$\\frac{2}{50}$', correct: false },
      { id: 'C', label: '$4$', correct: true },
      { id: 'D', label: '$\\frac{1}{5}$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Flip and multiply.' },
      { level: 'guide', text: '$\\frac{2}{5} \\times 10 = \\frac{20}{5}$.' },
      { level: 'reveal', text: '$\\frac{20}{5} = 4$.' },
    ],
    explanation: ['$\\frac{2}{5} \\div \\frac{1}{10} = \\frac{2}{5} \\times \\frac{10}{1} = \\frac{20}{5} = 4$.'],
    tags: ['fraction-division'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 55, unit: 6, order: 5, slug: 'm-coord-mix',
    standard: '6.NS.C.6', difficulty: 2,
    prompt: 'Reflect $(5, -2)$ over the $x$-axis. New point?',
    answerType: 'short-text',
    primaryAnswer: '(5, 2)', alternativeAnswers: ['(5,2)', '5, 2'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Flip the sign of $y$.' },
      { level: 'guide', text: '$y = -2 \\to y = 2$.' },
      { level: 'reveal', text: '$(5, 2)$.' },
    ],
    explanation: ['Across $x$-axis: keep $x$, flip $y$.', '$(5, -2) \\to (5, 2)$.'],
    tags: ['coordinate'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 56, unit: 6, order: 6, slug: 'm-word-frac',
    standard: '6.NS.A.1', difficulty: 3,
    prompt: 'A ribbon is $\\frac{5}{6}$ meter long. You cut it into $\\frac{1}{3}$-meter pieces. How many pieces?',
    answerType: 'numeric',
    primaryAnswer: '2', alternativeAnswers: ['2.5', '5/2'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set up: $\\frac{5}{6} \\div \\frac{1}{3}$.' },
      { level: 'guide', text: 'Flip: $\\frac{5}{6} \\times 3 = \\frac{15}{6}$.' },
      { level: 'reveal', text: '$\\frac{15}{6} = 2.5$ pieces (so $2$ whole + half).' },
    ],
    explanation: ['$\\frac{5}{6} \\div \\frac{1}{3} = \\frac{5}{6} \\times \\frac{3}{1} = \\frac{15}{6} = \\frac{5}{2} = 2.5$.'],
    tags: ['CA', 'fraction-division', 'word'], estimatedSeconds: 80,
  },
  {
    domain: '6.NS', num: 57, unit: 6, order: 7, slug: 'm-lcm-quick',
    standard: '6.NS.B.4', difficulty: 2,
    prompt: 'Find the LCM of $6$ and $10$.',
    answerType: 'numeric',
    primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiples of $6$: $6, 12, 18, 24, 30$.' },
      { level: 'guide', text: 'Multiples of $10$: $10, 20, 30$.' },
      { level: 'reveal', text: 'Smallest match: $30$.' },
    ],
    explanation: ['Multiples of $6$: $6, 12, 18, 24, \\mathbf{30}$.', 'Multiples of $10$: $10, 20, \\mathbf{30}$.', 'LCM $= 30$.'],
    tags: ['lcm'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 58, unit: 6, order: 8, slug: 'm-decimal-word',
    standard: '6.NS.B.3', difficulty: 3,
    prompt: 'You buy $3$ items costing \\$$2.49$ each. How much total?',
    answerType: 'numeric',
    primaryAnswer: '7.47', alternativeAnswers: ['$7.47'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply $2.49 \\times 3$.' },
      { level: 'guide', text: '$2 \\times 3 + 0.49 \\times 3$.' },
      { level: 'reveal', text: '$6 + 1.47 = 7.47$.' },
    ],
    explanation: ['$2.49 \\times 3 = 7.47$.'],
    tags: ['MAP-practice', 'decimal', 'money'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 59, unit: 6, order: 9, slug: 'm-integer-word',
    standard: '6.NS.C.5', difficulty: 2,
    prompt: 'An elevator goes from floor $5$ to floor $-2$. How many floors did it descend?',
    answerType: 'numeric',
    primaryAnswer: '7', alternativeAnswers: ['7 floors'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Distance $= |5 - (-2)|$.' },
      { level: 'guide', text: '$5 - (-2) = 5 + 2 = 7$.' },
      { level: 'reveal', text: '$7$ floors.' },
    ],
    explanation: ['$|5 - (-2)| = 7$.', 'Elevator descended $7$ floors.'],
    tags: ['integer', 'word'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 60, unit: 6, order: 10, slug: 'm-mixed-grand',
    standard: '6.NS.A.1', difficulty: 3,
    prompt: 'A box holds $\\frac{3}{4}$ pound of nuts. How many boxes can be filled from $6$ pounds?',
    answerType: 'numeric',
    primaryAnswer: '8', alternativeAnswers: ['8 boxes'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$6 \\div \\frac{3}{4}$.' },
      { level: 'guide', text: 'Flip: $6 \\times \\frac{4}{3} = \\frac{24}{3}$.' },
      { level: 'reveal', text: '$\\frac{24}{3} = 8$.' },
    ],
    explanation: ['$6 \\div \\frac{3}{4} = 6 \\times \\frac{4}{3} = \\frac{24}{3} = 8$.'],
    tags: ['CA', 'fraction-division', 'word'], estimatedSeconds: 75,
  },

  // ============================================================
  // UNIT 7 — Decimal & multi-digit ops II (6.NS.B.2, B.3)
  // ============================================================
  {
    domain: '6.NS', num: 61, unit: 7, order: 1, slug: 'multi-add-425-376',
    standard: '6.NS.B.3', difficulty: 1,
    prompt: 'Compute $425 + 376$.',
    answerType: 'numeric', primaryAnswer: '801', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Line up the digits by place value, then add.' },
      { level: 'guide', text: 'Ones: $5 + 6 = 11$ (carry $1$). Tens: $2 + 7 + 1 = 10$ (carry $1$). Hundreds: $4 + 3 + 1 = 8$.' },
      { level: 'reveal', text: '$801$.' },
    ],
    explanation: ['Stack the numbers and add column by column.', 'Ones: $11$ (write 1, carry 1). Tens: $10$ (write 0, carry 1). Hundreds: $8$.', 'Result: $801$.'],
    alternativeExplanations: [
      { title: 'Round-then-adjust', steps: ['$425 + 400 = 825$.', 'We added $24$ extra, so subtract: $825 - 24 = 801$.'] },
    ],
    tags: ['add', 'multi-digit'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 62, unit: 7, order: 2, slug: 'multi-sub-952-387',
    standard: '6.NS.B.3', difficulty: 1,
    prompt: 'Compute $952 - 387$.',
    answerType: 'numeric', primaryAnswer: '565', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Stack and subtract right to left, regrouping as needed.' },
      { level: 'guide', text: 'Ones: regroup, $12 - 7 = 5$. Tens: $4 - 8$ regroup, $14 - 8 = 6$. Hundreds: $8 - 3 = 5$.' },
      { level: 'reveal', text: '$565$.' },
    ],
    explanation: ['Subtract column by column with regrouping.', 'Ones: $12 - 7 = 5$. Tens: $14 - 8 = 6$. Hundreds: $8 - 3 = 5$.', 'Result: $565$.'],
    alternativeExplanations: [
      { title: 'Use a friendly number', steps: ['$952 - 400 = 552$.', 'We subtracted $13$ too many, so add back: $552 + 13 = 565$.'] },
    ],
    tags: ['subtract', 'multi-digit'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 63, unit: 7, order: 3, slug: 'multi-mul-38-24',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'Compute $38 \\times 24$.',
    answerType: 'numeric', primaryAnswer: '912', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply by tens and ones separately, then add.' },
      { level: 'guide', text: '$38 \\times 20 = 760$. $38 \\times 4 = 152$.' },
      { level: 'reveal', text: '$760 + 152 = 912$.' },
    ],
    explanation: ['Break $24$ into $20 + 4$.', '$38 \\times 20 = 760$.', '$38 \\times 4 = 152$.', '$760 + 152 = 912$.'],
    alternativeExplanations: [
      { title: 'Area-model rectangles', steps: ['Split: $(30 + 8)(20 + 4)$.', '$30 \\cdot 20 = 600$; $30 \\cdot 4 = 120$; $8 \\cdot 20 = 160$; $8 \\cdot 4 = 32$.', 'Sum: $600 + 120 + 160 + 32 = 912$.'] },
    ],
    tags: ['multiply', 'multi-digit'], estimatedSeconds: 65,
  },
  {
    domain: '6.NS', num: 64, unit: 7, order: 4, slug: 'multi-div-256-8',
    standard: '6.NS.B.2', difficulty: 2,
    prompt: 'Compute $256 \\div 8$.',
    answerType: 'numeric', primaryAnswer: '32', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Think: $8 \\times \\boxed{?} = 256$.' },
      { level: 'guide', text: '$8 \\times 30 = 240$. $256 - 240 = 16$, and $16 \\div 8 = 2$.' },
      { level: 'reveal', text: '$30 + 2 = 32$.' },
    ],
    explanation: ['$8$ goes into $25$ three times ($24$); bring down $6$ for $16$. $16 \\div 8 = 2$.', 'Quotient: $32$.'],
    alternativeExplanations: [
      { title: 'Halve, halve, halve', steps: ['$256 \\div 2 = 128$.', '$128 \\div 2 = 64$.', '$64 \\div 2 = 32$. (Three halvings = $\\div 8$.)'] },
    ],
    tags: ['divide', 'multi-digit'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 65, unit: 7, order: 5, slug: 'dec-add-07-145',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'Compute $0.7 + 1.45$.',
    answerType: 'numeric', primaryAnswer: '2.15',
    alternativeAnswers: ['2.15'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Line up the decimal points.' },
      { level: 'guide', text: 'Write $0.70 + 1.45$.' },
      { level: 'reveal', text: '$0.70 + 1.45 = 2.15$.' },
    ],
    explanation: ['Match decimal places: $0.70 + 1.45$.', 'Add: $2.15$.'],
    tags: ['decimal', 'add'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 66, unit: 7, order: 6, slug: 'dec-sub-65-278',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'Compute $6.5 - 2.78$.',
    answerType: 'numeric', primaryAnswer: '3.72',
    alternativeAnswers: ['3.72'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Pad to the same number of decimal places: $6.50 - 2.78$.' },
      { level: 'guide', text: 'Subtract column by column, regrouping.' },
      { level: 'reveal', text: '$6.50 - 2.78 = 3.72$.' },
    ],
    explanation: ['Rewrite $6.5$ as $6.50$.', '$6.50 - 2.78 = 3.72$.'],
    tags: ['decimal', 'subtract'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 67, unit: 7, order: 7, slug: 'dec-mul-04-005',
    standard: '6.NS.B.3', difficulty: 2,
    prompt: 'Compute $0.4 \\times 0.05$.',
    answerType: 'numeric', primaryAnswer: '0.02',
    alternativeAnswers: ['.02', '0.020'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply as whole numbers, then count decimal places.' },
      { level: 'guide', text: '$4 \\times 5 = 20$. Decimal places: $1 + 2 = 3$.' },
      { level: 'reveal', text: '$0.020 = 0.02$.' },
    ],
    explanation: ['$4 \\times 5 = 20$.', 'Total decimal places: $1 + 2 = 3$.', 'Place the point: $0.020 = 0.02$.'],
    tags: ['decimal', 'multiply'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 68, unit: 7, order: 8, slug: 'dec-div-5-02',
    standard: '6.NS.B.3', difficulty: 3,
    prompt: 'Compute $5 \\div 0.2$.',
    answerType: 'numeric', primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Move both decimal points so the divisor is a whole number.' },
      { level: 'guide', text: 'Move one place: $50 \\div 2$.' },
      { level: 'reveal', text: '$50 \\div 2 = 25$.' },
    ],
    explanation: ['Shift both numbers $\\times 10$: $5 \\div 0.2 = 50 \\div 2$.', '$50 \\div 2 = 25$.'],
    alternativeExplanations: [
      { title: 'How many 0.2s fit?', steps: ['$0.2 + 0.2 + 0.2 + 0.2 + 0.2 = 1$.', 'So $5$ ones contain $5 \\times 5 = 25$ groups of $0.2$.'] },
    ],
    tags: ['MAP-practice', 'decimal', 'divide'], estimatedSeconds: 75,
  },
  {
    domain: '6.NS', num: 69, unit: 7, order: 9, slug: 'dec-mul-136-45',
    standard: '6.NS.B.3', difficulty: 3,
    prompt: 'Compute $13.6 \\times 4.5$.',
    answerType: 'numeric', primaryAnswer: '61.2',
    alternativeAnswers: ['61.20'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply as whole numbers, then place the decimal.' },
      { level: 'guide', text: '$136 \\times 45 = 6120$. Total decimal places: $1 + 1 = 2$.' },
      { level: 'reveal', text: '$61.20 = 61.2$.' },
    ],
    explanation: ['$136 \\times 45$: $136 \\times 40 = 5440$; $136 \\times 5 = 680$; sum $= 6120$.', 'Decimal places: $1 + 1 = 2$.', '$6120 \\to 61.20 = 61.2$.'],
    tags: ['MAP-practice', 'decimal', 'multiply'], estimatedSeconds: 95,
  },
  {
    domain: '6.NS', num: 70, unit: 7, order: 10, slug: 'dec-book-1275',
    standard: '6.NS.B.3', difficulty: 3,
    prompt: 'A book costs \\$$12.75$. How much do **three** books cost?',
    answerType: 'numeric', primaryAnswer: '38.25',
    alternativeAnswers: ['$38.25'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$3$ books = $3 \\times 12.75$.' },
      { level: 'guide', text: '$3 \\times 12 = 36$; $3 \\times 0.75 = 2.25$.' },
      { level: 'reveal', text: '$36 + 2.25 = 38.25$.' },
    ],
    explanation: ['Break it up: $3 \\times 12 = 36$ and $3 \\times 0.75 = 2.25$.', 'Total: $36 + 2.25 = 38.25$.'],
    alternativeExplanations: [
      { title: 'Stack and add', steps: ['$12.75 + 12.75 = 25.50$.', '$25.50 + 12.75 = 38.25$.'] },
    ],
    tags: ['MAP-practice', 'decimal', 'word'], estimatedSeconds: 80,
  },

  // ============================================================
  // UNIT 8 — Comparing & ordering rationals (6.NS.C.7.a / .b)
  // ============================================================
  {
    domain: '6.NS', num: 71, unit: 8, order: 1, slug: 'compare-neg3-1',
    standard: '6.NS.C.7.a', difficulty: 1,
    prompt: 'Which is greater: $-3$ or $1$?',
    answerType: 'short-text', primaryAnswer: '1',
    alternativeAnswers: ['+1', 'one'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'On a number line, greater means farther to the right.' },
      { level: 'guide', text: '$1$ is to the right of $-3$.' },
      { level: 'reveal', text: '$1 > -3$.' },
    ],
    explanation: ['Positive numbers are always greater than negative numbers.', '$1 > -3$.'],
    tags: ['integer', 'compare'], estimatedSeconds: 30,
  },
  {
    domain: '6.NS', num: 72, unit: 8, order: 2, slug: 'order-neg2-0-neg5',
    standard: '6.NS.C.7.a', difficulty: 1,
    prompt: 'Order from **least to greatest**: $-2,\\ 0,\\ -5$ (separate with commas).',
    answerType: 'short-text', primaryAnswer: '-5, -2, 0',
    alternativeAnswers: ['-5,-2,0', '-5 -2 0'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Most-negative first.' },
      { level: 'guide', text: '$-5 < -2 < 0$.' },
      { level: 'reveal', text: '$-5,\\ -2,\\ 0$.' },
    ],
    explanation: ['On a number line, $-5$ is farthest left, then $-2$, then $0$.', 'Order: $-5,\\ -2,\\ 0$.'],
    tags: ['integer', 'order'], estimatedSeconds: 40,
  },
  {
    domain: '6.NS', num: 73, unit: 8, order: 3, slug: 'compare-neg7-neg3',
    standard: '6.NS.C.7.a', difficulty: 2,
    prompt: 'Which is greater: $-7$ or $-3$?',
    answerType: 'short-text', primaryAnswer: '-3',
    alternativeAnswers: ['−3', 'neg 3'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Closer to $0$ on the number line means greater.' },
      { level: 'guide', text: '$-3$ is to the right of $-7$.' },
      { level: 'reveal', text: '$-3 > -7$.' },
    ],
    explanation: ['$-3$ is closer to $0$ than $-7$ is.', 'So $-3 > -7$.'],
    alternativeExplanations: [
      { title: 'Owe-money picture', steps: ['Owing \\$$3$ is better than owing \\$$7$.', 'So $-3$ is greater than $-7$.'] },
    ],
    tags: ['integer', 'compare', 'common-error'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 74, unit: 8, order: 4, slug: 'compare-absvalue',
    standard: '6.NS.C.7.c', difficulty: 2,
    prompt: 'Which is greater: $|-7|$ or $|3|$?',
    answerType: 'short-text', primaryAnswer: '|-7|',
    alternativeAnswers: ['|−7|', 'abs(-7)', '7'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Absolute value = distance from $0$.' },
      { level: 'guide', text: '$|-7| = 7$ and $|3| = 3$.' },
      { level: 'reveal', text: '$7 > 3$, so $|-7| > |3|$.' },
    ],
    explanation: ['$|-7| = 7$ and $|3| = 3$.', '$7 > 3$, so $|-7|$ is greater.'],
    tags: ['absolute-value', 'compare'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 75, unit: 8, order: 5, slug: 'compare-05-quarter',
    standard: '6.NS.C.7.a', difficulty: 2,
    prompt: 'Compare: $0.5$ ___ $\\frac{1}{4}$ (use $>$, $<$, or $=$).',
    answerType: 'short-text', primaryAnswer: '>',
    alternativeAnswers: ['gt', 'greater than'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Put both in the same form.' },
      { level: 'guide', text: '$\\tfrac{1}{4} = 0.25$.' },
      { level: 'reveal', text: '$0.5 > 0.25$, so $0.5 > \\tfrac{1}{4}$.' },
    ],
    explanation: ['$\\tfrac{1}{4} = 0.25$.', '$0.5 > 0.25$, so $0.5 > \\tfrac{1}{4}$.'],
    alternativeExplanations: [
      { title: 'Use a common fraction', steps: ['$0.5 = \\tfrac{1}{2} = \\tfrac{2}{4}$.', '$\\tfrac{2}{4} > \\tfrac{1}{4}$.'] },
    ],
    tags: ['compare', 'fraction-decimal'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 76, unit: 8, order: 6, slug: 'order-03-half-025',
    standard: '6.NS.C.7.a', difficulty: 2,
    prompt: 'Order from **least to greatest**: $0.3,\\ \\frac{1}{2},\\ 0.25$ (separate with commas).',
    answerType: 'short-text', primaryAnswer: '0.25, 0.3, 1/2',
    alternativeAnswers: ['0.25,0.3,1/2', '0.25, 0.3, 0.5'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Convert each to a decimal.' },
      { level: 'guide', text: '$\\tfrac{1}{2} = 0.5$. Now order $0.3,\\ 0.5,\\ 0.25$.' },
      { level: 'reveal', text: '$0.25 < 0.3 < 0.5$.' },
    ],
    explanation: ['Convert: $\\tfrac{1}{2} = 0.5$.', 'Decimals: $0.3,\\ 0.5,\\ 0.25$.', 'Sorted: $0.25,\\ 0.3,\\ \\tfrac{1}{2}$.'],
    tags: ['order', 'fraction-decimal'], estimatedSeconds: 65,
  },
  {
    domain: '6.NS', num: 77, unit: 8, order: 7, slug: 'closer-to-zero',
    standard: '6.NS.C.7.c', difficulty: 3,
    prompt: 'Which number is **closer to $0$** on a number line: $-4$ or $6$?',
    answerType: 'short-text', primaryAnswer: '-4',
    alternativeAnswers: ['−4', '-4 is closer'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Distance to $0$ is the absolute value.' },
      { level: 'guide', text: '$|-4| = 4$ and $|6| = 6$.' },
      { level: 'reveal', text: '$4 < 6$, so $-4$ is closer to $0$.' },
    ],
    explanation: ['$|-4| = 4$ and $|6| = 6$.', '$-4$ sits $4$ away from $0$; $6$ sits $6$ away.', '$-4$ is closer to $0$.'],
    tags: ['MAP-practice', 'absolute-value'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 78, unit: 8, order: 8, slug: 'true-statement-neg',
    standard: '6.NS.C.7.a', difficulty: 3,
    prompt: 'Which statement is true?',
    answerType: 'multiple-choice', primaryAnswer: 'B',
    choices: [
      { id: 'A', label: '$-10 > -5$', correct: false },
      { id: 'B', label: '$-5 > -10$', correct: true },
      { id: 'C', label: '$-5 = -10$', correct: false },
    ],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Which is farther right on a number line?' },
      { level: 'guide', text: '$-5$ is to the right of $-10$.' },
      { level: 'reveal', text: '$-5 > -10$.' },
    ],
    explanation: ['$-5$ is closer to $0$ than $-10$, and on a number line closer-to-$0$ on the negative side means greater.', '$-5 > -10$.'],
    tags: ['MAP-practice', 'integer', 'compare'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 79, unit: 8, order: 9, slug: 'temp-drop-neg8-5',
    standard: '6.NS.C.5', difficulty: 3,
    prompt: 'The temperature was $-8\\degree$F. It dropped another $5$ degrees. What is the new temperature?',
    answerType: 'numeric', primaryAnswer: '-13',
    alternativeAnswers: ['−13', '-13 F', '-13°F'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Dropping makes it more negative.' },
      { level: 'guide', text: '$-8 - 5$.' },
      { level: 'reveal', text: '$-13$.' },
    ],
    explanation: ['Subtract: $-8 - 5 = -13$.', 'New temperature: $-13\\degree$F.'],
    alternativeExplanations: [
      { title: 'Number-line walk', steps: ['Start at $-8$.', 'Move $5$ to the left (colder): $-9,\\ -10,\\ -11,\\ -12,\\ -13$.'] },
    ],
    tags: ['MAP-practice', 'integer', 'word'], estimatedSeconds: 65,
  },
  {
    domain: '6.NS', num: 80, unit: 8, order: 10, slug: 'stock-fell-more',
    standard: '6.NS.C.7.c', difficulty: 3,
    prompt: 'Stock A changed by $-3.5$ points; Stock B changed by $-1.25$ points. **Which stock fell more**?',
    answerType: 'short-text', primaryAnswer: 'A',
    alternativeAnswers: ['Stock A', 'A fell more'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Compare how far each is from $0$.' },
      { level: 'guide', text: '$|-3.5| = 3.5$ and $|-1.25| = 1.25$.' },
      { level: 'reveal', text: '$3.5 > 1.25$, so Stock A fell more.' },
    ],
    explanation: ['Absolute values: $|-3.5| = 3.5,\\ |-1.25| = 1.25$.', '$3.5 > 1.25$, so A had the bigger drop.'],
    alternativeExplanations: [
      { title: 'Be careful with comparison', steps: ['$-3.5 < -1.25$ (more negative), but the **size** of the drop is what matters.', 'A drop of $3.5$ is bigger than a drop of $1.25$, so A fell more.'] },
    ],
    tags: ['MAP-practice', 'absolute-value', 'word'], estimatedSeconds: 80,
  },

  // ============================================================
  // UNIT 9 — Integers in context & opposites (6.NS.C.5, C.6.a / .c)
  // ============================================================
  {
    domain: '6.NS', num: 81, unit: 9, order: 1, slug: 'opp-of-7',
    standard: '6.NS.C.6.a', difficulty: 1,
    prompt: 'What is the **opposite** of $7$?',
    answerType: 'numeric', primaryAnswer: '-7',
    alternativeAnswers: ['−7'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The opposite has the same distance from $0$ but the other sign.' },
      { level: 'guide', text: 'Flip the sign: $7 \\to -7$.' },
      { level: 'reveal', text: '$-7$.' },
    ],
    explanation: ['Opposite of $7$ is $-7$ (same distance from $0$, opposite sign).'],
    tags: ['integer', 'opposite'], estimatedSeconds: 25,
  },
  {
    domain: '6.NS', num: 82, unit: 9, order: 2, slug: 'opp-of-neg12',
    standard: '6.NS.C.6.a', difficulty: 1,
    prompt: 'What is the opposite of $-12$?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Flip the sign.' },
      { level: 'guide', text: '$-12 \\to 12$.' },
      { level: 'reveal', text: '$12$.' },
    ],
    explanation: ['Opposite of $-12$ is $12$.'],
    tags: ['integer', 'opposite'], estimatedSeconds: 25,
  },
  {
    domain: '6.NS', num: 83, unit: 9, order: 3, slug: 'below-zero-5',
    standard: '6.NS.C.5', difficulty: 1,
    prompt: 'Which number represents "$5$ degrees **below** zero"?',
    answerType: 'numeric', primaryAnswer: '-5',
    alternativeAnswers: ['−5'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Below" zero means negative.' },
      { level: 'guide', text: 'Use a minus sign.' },
      { level: 'reveal', text: '$-5$.' },
    ],
    explanation: ['Below zero is represented by a negative number.', '"$5$ below" $= -5$.'],
    tags: ['integer', 'context'], estimatedSeconds: 30,
  },
  {
    domain: '6.NS', num: 84, unit: 9, order: 4, slug: 'elevator-down3-up5',
    standard: '6.NS.C.5', difficulty: 2,
    prompt: 'An elevator goes **down** $3$ floors, then **up** $5$ floors. What is the **net change** in floors?',
    answerType: 'numeric', primaryAnswer: '2',
    alternativeAnswers: ['+2', '2 floors up'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Down is negative, up is positive.' },
      { level: 'guide', text: '$-3 + 5$.' },
      { level: 'reveal', text: '$+2$.' },
    ],
    explanation: ['Down $3 \\to -3$. Up $5 \\to +5$.', '$-3 + 5 = 2$.', 'Net: $2$ floors up.'],
    tags: ['integer', 'context', 'word'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 85, unit: 9, order: 5, slug: 'diver-neg45-up20',
    standard: '6.NS.C.5', difficulty: 2,
    prompt: 'A diver is at $-45$ ft (below sea level) and rises $20$ ft. What is the diver\'s new position?',
    answerType: 'numeric', primaryAnswer: '-25',
    alternativeAnswers: ['−25', '-25 ft'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Rising is positive.' },
      { level: 'guide', text: '$-45 + 20$.' },
      { level: 'reveal', text: '$-25$.' },
    ],
    explanation: ['Start at $-45$. Add the rise: $-45 + 20 = -25$ ft.'],
    tags: ['integer', 'word'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 86, unit: 9, order: 6, slug: 'bank-100-40-25',
    standard: '6.NS.C.5', difficulty: 2,
    prompt: 'Starting balance \\$$100$. Withdraw \\$$40$, deposit \\$$25$. What is the final balance?',
    answerType: 'numeric', primaryAnswer: '85',
    alternativeAnswers: ['$85'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Withdraw subtracts; deposit adds.' },
      { level: 'guide', text: '$100 - 40 + 25$.' },
      { level: 'reveal', text: '$85$.' },
    ],
    explanation: ['$100 - 40 = 60$.', '$60 + 25 = 85$.'],
    tags: ['integer', 'word', 'money'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 87, unit: 9, order: 7, slug: 'neg-abs-neg15',
    standard: '6.NS.C.7.c', difficulty: 2,
    prompt: 'Evaluate $-|-15|$.',
    answerType: 'numeric', primaryAnswer: '-15',
    alternativeAnswers: ['−15'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Work the absolute value first, then take the opposite.' },
      { level: 'guide', text: '$|-15| = 15$. The leading minus makes it $-15$.' },
      { level: 'reveal', text: '$-15$.' },
    ],
    explanation: ['Inside the bars: $|-15| = 15$.', 'The negative outside: $-(15) = -15$.'],
    tags: ['absolute-value', 'order-of-ops'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 88, unit: 9, order: 8, slug: 'dist-neg8-to-8',
    standard: '6.NS.C.6', difficulty: 3,
    prompt: 'Opposites are the same distance from $0$. What is the **distance from $-8$ to $8$** on a number line?',
    answerType: 'numeric', primaryAnswer: '16', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Each opposite is $8$ from $0$.' },
      { level: 'guide', text: '$8 + 8$.' },
      { level: 'reveal', text: '$16$.' },
    ],
    explanation: ['$-8$ is $8$ from $0$ on the left; $8$ is $8$ from $0$ on the right.', 'Total distance: $8 + 8 = 16$.'],
    alternativeExplanations: [
      { title: 'Subtract with absolute value', steps: ['Distance $= |8 - (-8)| = |16| = 16$.'] },
    ],
    tags: ['MAP-practice', 'integer', 'distance'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 89, unit: 9, order: 9, slug: 'football-5-8-3',
    standard: '6.NS.C.5', difficulty: 3,
    prompt: 'A football team gains $5$ yards, loses $8$ yards, then gains $3$ yards. What is the **net yardage**?',
    answerType: 'numeric', primaryAnswer: '0', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Gains are $+$, losses are $-$.' },
      { level: 'guide', text: '$5 - 8 + 3$.' },
      { level: 'reveal', text: '$0$.' },
    ],
    explanation: ['$5 - 8 = -3$.', '$-3 + 3 = 0$.', 'Net: no change.'],
    tags: ['MAP-practice', 'integer', 'word'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 90, unit: 9, order: 10, slug: 'sub-neg250-up75',
    standard: '6.NS.C.5', difficulty: 3,
    prompt: 'A submarine dives to $-250$ ft, then rises $75$ ft. **How far from sea level** is the submarine now?',
    answerType: 'numeric', primaryAnswer: '175',
    alternativeAnswers: ['175 ft'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the new position first, then take its absolute value.' },
      { level: 'guide', text: 'Position: $-250 + 75 = -175$. Distance: $|-175|$.' },
      { level: 'reveal', text: '$175$ ft below sea level — $175$ ft from sea level.' },
    ],
    explanation: ['New position: $-250 + 75 = -175$.', 'Distance from sea level (the value $0$): $|-175| = 175$ ft.'],
    tags: ['MAP-practice', 'integer', 'absolute-value', 'word'], estimatedSeconds: 90,
  },

  // ============================================================
  // UNIT 10 — Coordinate plane & challenge (6.NS.C.8 + mix)
  // ============================================================
  {
    domain: '6.NS', num: 91, unit: 10, order: 1, slug: 'cp-vert-3-2-3-7',
    standard: '6.NS.C.8', difficulty: 2,
    prompt: 'On a coordinate plane, find the distance from $(3, 2)$ to $(3, 7)$.',
    answerType: 'numeric', primaryAnswer: '5',
    alternativeAnswers: ['5 units'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Same x-value means vertical.' },
      { level: 'guide', text: 'Subtract the y-values: $|7 - 2|$.' },
      { level: 'reveal', text: '$|7 - 2| = 5$.' },
    ],
    explanation: ['Both points share $x = 3$ → vertical segment.', '$|7 - 2| = 5$ units.'],
    tags: ['coordinate-plane', 'distance'], estimatedSeconds: 45,
  },
  {
    domain: '6.NS', num: 92, unit: 10, order: 2, slug: 'cp-horiz-neg2-4-to-5-4',
    standard: '6.NS.C.8', difficulty: 2,
    prompt: 'Find the distance from $(-2, 4)$ to $(5, 4)$.',
    answerType: 'numeric', primaryAnswer: '7',
    alternativeAnswers: ['7 units'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Same y-value means horizontal.' },
      { level: 'guide', text: 'Subtract the x-values: $|5 - (-2)|$.' },
      { level: 'reveal', text: '$|5 - (-2)| = 7$.' },
    ],
    explanation: ['Both points share $y = 4$ → horizontal segment.', '$|5 - (-2)| = |7| = 7$.'],
    alternativeExplanations: [
      { title: 'Count along the x-axis', steps: ['From $x = -2$, step right to $x = 5$.', 'That\'s $7$ steps.'] },
    ],
    tags: ['coordinate-plane', 'distance'], estimatedSeconds: 55,
  },
  {
    domain: '6.NS', num: 93, unit: 10, order: 3, slug: 'cp-quad-4-neg3',
    standard: '6.NS.C.6.b', difficulty: 2,
    prompt: 'In which quadrant is the point $(4, -3)$?',
    answerType: 'short-text', primaryAnswer: 'IV',
    alternativeAnswers: ['4', 'iv', 'quadrant iv'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Check the signs of x and y.' },
      { level: 'guide', text: 'x positive, y negative → bottom-right.' },
      { level: 'reveal', text: 'Quadrant IV.' },
    ],
    explanation: ['$x = 4 > 0$ (right side); $y = -3 < 0$ (below the x-axis).', 'Bottom-right = Quadrant IV.'],
    tags: ['coordinate-plane', 'quadrants'], estimatedSeconds: 35,
  },
  {
    domain: '6.NS', num: 94, unit: 10, order: 4, slug: 'cp-reflect-x',
    standard: '6.NS.C.6.b', difficulty: 2,
    prompt: 'Reflect the point $(3, -5)$ across the **x-axis**. Write the new coordinates.',
    answerType: 'short-text', primaryAnswer: '(3, 5)',
    alternativeAnswers: ['(3,5)', '3, 5', '3,5'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Across the x-axis: flip the sign of $y$.' },
      { level: 'guide', text: '$y = -5 \\to y = 5$.' },
      { level: 'reveal', text: '$(3, 5)$.' },
    ],
    explanation: ['Reflecting across the x-axis flips the sign of the y-coordinate.', '$(3, -5) \\to (3, 5)$.'],
    tags: ['coordinate-plane', 'reflection'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 95, unit: 10, order: 5, slug: 'cp-reflect-y',
    standard: '6.NS.C.6.b', difficulty: 2,
    prompt: 'Reflect the point $(-2, 4)$ across the **y-axis**.',
    answerType: 'short-text', primaryAnswer: '(2, 4)',
    alternativeAnswers: ['(2,4)', '2, 4', '2,4'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Across the y-axis: flip the sign of $x$.' },
      { level: 'guide', text: '$x = -2 \\to x = 2$.' },
      { level: 'reveal', text: '$(2, 4)$.' },
    ],
    explanation: ['Reflecting across the y-axis flips the sign of the x-coordinate.', '$(-2, 4) \\to (2, 4)$.'],
    tags: ['coordinate-plane', 'reflection'], estimatedSeconds: 50,
  },
  {
    domain: '6.NS', num: 96, unit: 10, order: 6, slug: 'cp-rect-perim',
    standard: '6.NS.C.8', difficulty: 3,
    prompt: 'A rectangle has vertices $(0, 0)$, $(5, 0)$, $(5, 3)$, $(0, 3)$. Find its **perimeter**.',
    answerType: 'numeric', primaryAnswer: '16',
    alternativeAnswers: ['16 units'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the side lengths.' },
      { level: 'guide', text: 'Length = $5 - 0 = 5$. Width = $3 - 0 = 3$.' },
      { level: 'reveal', text: 'Perimeter $= 2(5 + 3) = 16$.' },
    ],
    explanation: ['Length: $|5 - 0| = 5$. Width: $|3 - 0| = 3$.', 'Perimeter $= 2(L + W) = 2(8) = 16$.'],
    tags: ['MAP-practice', 'coordinate-plane', 'perimeter'], estimatedSeconds: 75,
  },
  {
    domain: '6.NS', num: 97, unit: 10, order: 7, slug: 'cp-right-tri-area',
    standard: '6.NS.C.8', difficulty: 3,
    prompt: 'A right triangle has vertices $(0, 0)$, $(6, 0)$, $(6, 4)$. Find its **area**.',
    answerType: 'numeric', primaryAnswer: '12',
    alternativeAnswers: ['12 sq units'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the leg lengths first.' },
      { level: 'guide', text: 'Horizontal leg = $6$, vertical leg = $4$. Area = $\\tfrac{1}{2} \\cdot 6 \\cdot 4$.' },
      { level: 'reveal', text: '$\\tfrac{1}{2} \\cdot 24 = 12$.' },
    ],
    explanation: ['Legs are $6$ (horizontal) and $4$ (vertical).', 'Area of right triangle: $\\tfrac{1}{2} \\cdot 6 \\cdot 4 = 12$.'],
    tags: ['MAP-practice', 'coordinate-plane', 'area'], estimatedSeconds: 80,
  },
  {
    domain: '6.NS', num: 98, unit: 10, order: 8, slug: 'cp-vert-neg2-5',
    standard: '6.NS.C.8', difficulty: 3,
    prompt: 'Find the distance from $(1, -2)$ to $(1, 5)$.',
    answerType: 'numeric', primaryAnswer: '7',
    alternativeAnswers: ['7 units'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Same x — vertical distance.' },
      { level: 'guide', text: '$|5 - (-2)|$.' },
      { level: 'reveal', text: '$|5 - (-2)| = |7| = 7$.' },
    ],
    explanation: ['Same x → vertical segment.', '$|5 - (-2)| = |7| = 7$.'],
    tags: ['MAP-practice', 'coordinate-plane', 'distance'], estimatedSeconds: 60,
  },
  {
    domain: '6.NS', num: 99, unit: 10, order: 9, slug: 'cp-rect-area-neg3-4',
    standard: '6.NS.C.8', difficulty: 3,
    prompt: 'A rectangle has corners $(-3, 1)$, $(4, 1)$, $(4, 5)$, $(-3, 5)$. Find its **area**.',
    answerType: 'numeric', primaryAnswer: '28',
    alternativeAnswers: ['28 sq units'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the width and height first.' },
      { level: 'guide', text: 'Width $= |4 - (-3)| = 7$. Height $= |5 - 1| = 4$.' },
      { level: 'reveal', text: '$7 \\times 4 = 28$.' },
    ],
    explanation: ['Width: $|4 - (-3)| = 7$. Height: $|5 - 1| = 4$.', 'Area: $7 \\times 4 = 28$.'],
    tags: ['MAP-practice', 'coordinate-plane', 'area'], estimatedSeconds: 85,
  },
  {
    domain: '6.NS', num: 100, unit: 10, order: 10, slug: 'cp-fourth-vertex',
    standard: '6.NS.C.8', difficulty: 3,
    prompt: 'Three vertices of a rectangle are $(-1, 2)$, $(5, 2)$, and $(5, 6)$. What is the fourth vertex?',
    answerType: 'short-text', primaryAnswer: '(-1, 6)',
    alternativeAnswers: ['(-1,6)', '-1, 6', '-1,6'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'In a rectangle, opposite sides have the same length.' },
      { level: 'guide', text: 'The missing vertex shares $x = -1$ with one vertex and $y = 6$ with another.' },
      { level: 'reveal', text: '$(-1, 6)$.' },
    ],
    explanation: ['$(-1, 2)$ and $(5, 2)$ form the bottom edge ($y = 2$).', '$(5, 2)$ and $(5, 6)$ form the right edge ($x = 5$).', 'The top-left vertex needs $x = -1$ and $y = 6$ → $(-1, 6)$.'],
    alternativeExplanations: [
      { title: 'Match opposite sides', steps: ['Bottom edge runs from $x = -1$ to $x = 5$ (length $6$).', 'Top edge at $y = 6$ must also run from $-1$ to $5$.', 'Top-left vertex: $(-1, 6)$.'] },
    ],
    tags: ['MAP-practice', 'coordinate-plane', 'geometry'], estimatedSeconds: 100,
  },
];
