import type { SeedProblem } from './types';

// 6.RP — Ratios & Proportional Relationships
// Adds 53 new problems (8 to U1, 8 to U2, 10 each to U3-U6).
// Existing: 001-005 in U1, 006-007 in U2 (kept untouched).

export const problems6RP: SeedProblem[] = [
  // ---------------- UNIT 1 — Ratios & rates intro (orders 6-10) ----------------
  {
    domain: '6.RP', num: 8, unit: 1, order: 6, slug: 'ratio-words',
    standard: '6.RP.A.1', difficulty: 1,
    prompt: 'A bag has $5$ red marbles and $3$ blue marbles. What is the ratio of **red to blue**?',
    answerType: 'short-text',
    primaryAnswer: '5:3', alternativeAnswers: ['5 to 3', '5/3', '5 : 3'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A ratio compares two amounts. The order matters!' },
      { level: 'guide', text: 'You want **red : blue**, so write the red count first.' },
      { level: 'reveal', text: 'Red is $5$, blue is $3$. Write it as $5:3$ (or $5$ to $3$).' },
    ],
    explanation: [
      'A ratio compares two quantities. **Red : blue** puts red first.',
      'There are $5$ red and $3$ blue.',
      'Write it as $5:3$ or "$5$ to $3$".',
    ],
    alternativeExplanations: [{
      title: 'As a fraction',
      steps: ['Ratios can be written as fractions: $\\frac{5}{3}$.', 'This means $5$ reds **for every** $3$ blues.'],
    }],
    tags: ['CA', 'ratio'], estimatedSeconds: 30,
  },
  {
    domain: '6.RP', num: 9, unit: 1, order: 7, slug: 'rate-words',
    standard: '6.RP.A.2', difficulty: 1,
    prompt: 'A car travels $120$ km in $2$ hours. What is the rate in **km per hour**?',
    answerType: 'numeric',
    primaryAnswer: '60', alternativeAnswers: ['60 km/h', '60kmh'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A rate per hour means: per **1** hour.' },
      { level: 'guide', text: 'Divide the total km by the total hours.' },
      { level: 'reveal', text: '$120 \\div 2 = ?$' },
    ],
    explanation: ['Set up: $\\frac{120 \\text{ km}}{2 \\text{ hr}}$.', 'Divide: $120 \\div 2 = 60$.', 'Rate is $60$ km/h.'],
    tags: ['rate'], estimatedSeconds: 40,
  },
  {
    domain: '6.RP', num: 10, unit: 1, order: 8, slug: 'simplify-ratio',
    standard: '6.RP.A.1', difficulty: 2,
    prompt: 'Simplify the ratio $12 : 18$ to its lowest terms.',
    answerType: 'short-text',
    primaryAnswer: '2:3', alternativeAnswers: ['2 to 3', '2/3', '2 : 3'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find a number that divides both sides evenly.' },
      { level: 'guide', text: 'What is the greatest common factor of $12$ and $18$?' },
      { level: 'reveal', text: 'GCF is $6$. Divide both: $12 \\div 6 = 2$, $18 \\div 6 = 3$. Answer: $2:3$.' },
    ],
    explanation: [
      'The greatest common factor of $12$ and $18$ is $6$.',
      'Divide both parts by $6$: $\\frac{12}{6} = 2$ and $\\frac{18}{6} = 3$.',
      'Simplified ratio: $2:3$.',
    ],
    tags: ['ratio', 'simplify'], estimatedSeconds: 45,
  },
  {
    domain: '6.RP', num: 11, unit: 1, order: 9, slug: 'recipe-ratio',
    standard: '6.RP.A.3', difficulty: 2,
    prompt: 'A recipe uses $2$ cups of flour for every $3$ cups of sugar. If you use $6$ cups of flour, how many cups of sugar do you need?',
    answerType: 'numeric',
    primaryAnswer: '9', alternativeAnswers: ['9 cups'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'How many times more flour than $2$ is $6$?' },
      { level: 'guide', text: 'Scale **both** sides by the same factor.' },
      { level: 'reveal', text: 'Flour: $2 \\to 6$ is $\\times 3$. So sugar: $3 \\times 3 = 9$.' },
    ],
    explanation: ['Flour scaled by $6 \\div 2 = 3$.', 'Apply the same factor to sugar: $3 \\times 3 = 9$.', 'You need $9$ cups of sugar.'],
    tags: ['CA', 'ratio', 'recipe'], estimatedSeconds: 45,
  },
  {
    domain: '6.RP', num: 12, unit: 1, order: 10, slug: 'mc-equivalent-ratio',
    standard: '6.RP.A.1', difficulty: 2,
    prompt: 'Which ratio is equivalent to $4 : 6$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$3 : 4$', correct: false },
      { id: 'B', label: '$6 : 9$', correct: true },
      { id: 'C', label: '$8 : 10$', correct: false },
      { id: 'D', label: '$2 : 4$', correct: false },
    ],
    primaryAnswer: 'B', alternativeAnswers: [], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Equivalent ratios reduce to the same simplest form.' },
      { level: 'guide', text: 'Simplify $4:6$ first.' },
      { level: 'reveal', text: '$4:6 = 2:3$. Check each option: $6:9 = 2:3$ ✓.' },
    ],
    explanation: ['$4:6$ simplifies to $2:3$ (divide both by $2$).', 'Check $6:9$: divide both by $3$ → $2:3$. ✓', 'Answer: $6:9$.'],
    tags: ['MAP-practice', 'ratio'], estimatedSeconds: 50,
  },

  // ---------------- UNIT 2 — Unit rates & shopping (orders 3-10) ----------------
  {
    domain: '6.RP', num: 13, unit: 2, order: 3, slug: 'price-per-unit',
    standard: '6.RP.A.2', difficulty: 1,
    prompt: '$8$ apples cost \\$$4$. What is the price **per apple**?',
    answerType: 'numeric',
    primaryAnswer: '0.5', alternativeAnswers: ['$0.50', '50 cents', '1/2', '0.50'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Per apple" means: cost for one apple.' },
      { level: 'guide', text: 'Divide total cost by the number of apples.' },
      { level: 'reveal', text: '$4 \\div 8 = 0.5$ dollars (or $50$ cents).' },
    ],
    explanation: ['Divide total cost by number of apples: $4 \\div 8 = 0.5$.', 'Price per apple is \\$$0.50$.'],
    tags: ['unit-rate', 'money'], estimatedSeconds: 35,
  },
  {
    domain: '6.RP', num: 14, unit: 2, order: 4, slug: 'words-per-minute',
    standard: '6.RP.A.2', difficulty: 1,
    prompt: 'Mia types $240$ words in $4$ minutes. How many words **per minute**?',
    answerType: 'numeric',
    primaryAnswer: '60', alternativeAnswers: ['60 wpm'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find words for $1$ minute.' },
      { level: 'guide', text: '$\\frac{240}{4} = ?$' },
      { level: 'reveal', text: '$240 \\div 4 = 60$ words per minute.' },
    ],
    explanation: ['Divide: $240 \\div 4 = 60$.', 'Mia types $60$ words per minute.'],
    tags: ['unit-rate'], estimatedSeconds: 30,
  },
  {
    domain: '6.RP', num: 15, unit: 2, order: 5, slug: 'best-buy',
    standard: '6.RP.A.2', difficulty: 2,
    prompt: 'Bottle A: $12$ oz for \\$$3$. Bottle B: $20$ oz for \\$$4$. Which is the **better buy** (lower price per oz)?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Bottle A', correct: false },
      { id: 'B', label: 'Bottle B', correct: true },
      { id: 'C', label: 'Same price per oz', correct: false },
      { id: 'D', label: 'Cannot tell', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Find price per ounce for each.' },
      { level: 'guide', text: 'A: $3 \\div 12$. B: $4 \\div 20$.' },
      { level: 'reveal', text: 'A: \\$$0.25$/oz. B: \\$$0.20$/oz. B is cheaper per oz.' },
    ],
    explanation: ['A: $3 \\div 12 = \\$0.25$/oz.', 'B: $4 \\div 20 = \\$0.20$/oz.', 'B costs less per ounce — better buy.'],
    tags: ['CA', 'MAP-practice', 'unit-price'], estimatedSeconds: 60,
  },
  {
    domain: '6.RP', num: 16, unit: 2, order: 6, slug: 'speed-distance',
    standard: '6.RP.A.3.b', difficulty: 2,
    prompt: 'A train goes $300$ miles in $5$ hours. At this rate, how far in $7$ hours?',
    answerType: 'numeric',
    primaryAnswer: '420', alternativeAnswers: ['420 miles', '420mi'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find the rate per hour.' },
      { level: 'guide', text: 'Then multiply that rate by $7$.' },
      { level: 'reveal', text: '$300 \\div 5 = 60$ mph. $60 \\times 7 = 420$ miles.' },
    ],
    explanation: ['Unit rate: $300 \\div 5 = 60$ mph.', 'Distance in $7$ hours: $60 \\times 7 = 420$ miles.'],
    tags: ['unit-rate', 'speed'], estimatedSeconds: 60,
  },
  {
    domain: '6.RP', num: 17, unit: 2, order: 7, slug: 'mpg',
    standard: '6.RP.A.2', difficulty: 2,
    prompt: 'A car uses $4$ gallons of gas to drive $120$ miles. How many **miles per gallon**?',
    answerType: 'numeric',
    primaryAnswer: '30', alternativeAnswers: ['30 mpg'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Per gallon" means: miles for $1$ gallon.' },
      { level: 'guide', text: 'Divide miles by gallons.' },
      { level: 'reveal', text: '$120 \\div 4 = 30$ miles per gallon.' },
    ],
    explanation: ['$\\frac{120 \\text{ mi}}{4 \\text{ gal}} = 30$ mpg.', 'The car gets $30$ miles per gallon.'],
    tags: ['unit-rate'], estimatedSeconds: 35,
  },
  {
    domain: '6.RP', num: 18, unit: 2, order: 8, slug: 'pay-per-hour',
    standard: '6.RP.A.3.b', difficulty: 2,
    prompt: 'Liam earns \\$$72$ for $8$ hours of work. How much does he earn **per hour**?',
    answerType: 'numeric',
    primaryAnswer: '9', alternativeAnswers: ['$9', '9 dollars'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find pay for $1$ hour.' },
      { level: 'guide', text: '$72 \\div 8 = ?$' },
      { level: 'reveal', text: '$72 \\div 8 = 9$. Liam earns \\$$9$/hour.' },
    ],
    explanation: ['Total pay ÷ hours: $72 \\div 8 = 9$.', 'Pay rate is \\$$9$ per hour.'],
    tags: ['unit-rate', 'money'], estimatedSeconds: 30,
  },
  {
    domain: '6.RP', num: 19, unit: 2, order: 9, slug: 'unit-rate-mc',
    standard: '6.RP.A.2', difficulty: 2,
    prompt: 'Which unit rate is greatest?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$150$ miles in $3$ hr', correct: false },
      { id: 'B', label: '$240$ miles in $4$ hr', correct: true },
      { id: 'C', label: '$300$ miles in $6$ hr', correct: false },
      { id: 'D', label: '$80$ miles in $2$ hr', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Find each as miles per $1$ hour.' },
      { level: 'guide', text: 'A: $50$ mph. B: $60$ mph. C: $50$ mph. D: $40$ mph.' },
      { level: 'reveal', text: 'B gives $60$ mph — the largest unit rate.' },
    ],
    explanation: ['A: $150 \\div 3 = 50$ mph.', 'B: $240 \\div 4 = 60$ mph.', 'C: $300 \\div 6 = 50$ mph.', 'D: $80 \\div 2 = 40$ mph.', 'Largest: B at $60$ mph.'],
    tags: ['MAP-practice', 'unit-rate'], estimatedSeconds: 70,
  },
  {
    domain: '6.RP', num: 20, unit: 2, order: 10, slug: 'rate-word-3',
    standard: '6.RP.A.3.b', difficulty: 3,
    prompt: 'A printer prints $5$ pages in $20$ seconds. At this rate, how many pages in $2$ minutes?',
    answerType: 'numeric',
    primaryAnswer: '30', alternativeAnswers: ['30 pages'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$2$ minutes is how many seconds?' },
      { level: 'guide', text: 'Find pages per second, then multiply by $120$.' },
      { level: 'reveal', text: '$\\frac{5}{20} = 0.25$ pages/sec. $0.25 \\times 120 = 30$ pages.' },
    ],
    explanation: ['Rate: $5 \\div 20 = 0.25$ pages/sec.', '$2$ minutes $= 120$ sec.', 'Pages: $0.25 \\times 120 = 30$.'],
    alternativeExplanations: [{
      title: 'Scale up the ratio',
      steps: ['$5$ pages : $20$ sec. Multiply both sides by $6$ (since $20 \\times 6 = 120$).', '$5 \\times 6 = 30$ pages in $120$ sec.'],
    }],
    tags: ['CA', 'unit-rate'], estimatedSeconds: 75,
  },

  // ---------------- UNIT 3 — Ratio tables & double number lines (1-10) ----------------
  {
    domain: '6.RP', num: 21, unit: 3, order: 1, slug: 'rt-fill',
    standard: '6.RP.A.3.a', difficulty: 1,
    prompt: 'In the ratio table $1 \\to 3$, $2 \\to 6$, $3 \\to 9$, $4 \\to ?$ — what fills the blank?',
    answerType: 'numeric',
    primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Look at the pattern: each output is $3$ times the input.' },
      { level: 'guide', text: 'Multiply $4$ by $3$.' },
      { level: 'reveal', text: '$4 \\times 3 = 12$.' },
    ],
    explanation: ['The pattern is "multiply input by $3$".', '$4 \\times 3 = 12$.'],
    tags: ['ratio-table'], estimatedSeconds: 30,
  },
  {
    domain: '6.RP', num: 22, unit: 3, order: 2, slug: 'rt-find-x',
    standard: '6.RP.A.3.a', difficulty: 1,
    prompt: 'In a ratio table, $2 \\to 10$ and $5 \\to 25$. What does $8$ map to?',
    answerType: 'numeric',
    primaryAnswer: '40', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'What\'s the multiplier from input to output?' },
      { level: 'guide', text: '$\\frac{10}{2} = 5$ and $\\frac{25}{5} = 5$. So output $= 5 \\times$ input.' },
      { level: 'reveal', text: '$8 \\times 5 = 40$.' },
    ],
    explanation: ['Each output is $5$ times the input.', '$8 \\times 5 = 40$.'],
    tags: ['ratio-table'], estimatedSeconds: 35,
  },
  {
    domain: '6.RP', num: 23, unit: 3, order: 3, slug: 'rt-scale-down',
    standard: '6.RP.A.3.a', difficulty: 2,
    prompt: 'A recipe makes $12$ cookies with $3$ cups of flour. How many cups of flour to make $4$ cookies?',
    answerType: 'numeric',
    primaryAnswer: '1', alternativeAnswers: ['1 cup'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set up: $12$ cookies → $3$ cups. What about $4$ cookies?' },
      { level: 'guide', text: '$4$ is $\\frac{1}{3}$ of $12$. Apply the same scale.' },
      { level: 'reveal', text: '$3 \\times \\frac{1}{3} = 1$ cup.' },
    ],
    explanation: ['Scale: $4 \\div 12 = \\frac{1}{3}$.', 'Flour: $3 \\times \\frac{1}{3} = 1$ cup.'],
    tags: ['CA', 'ratio-table'], estimatedSeconds: 50,
  },
  {
    domain: '6.RP', num: 24, unit: 3, order: 4, slug: 'rt-money',
    standard: '6.RP.A.3.a', difficulty: 2,
    prompt: '$3$ pencils cost \\$$1.50$. How much do $7$ pencils cost?',
    answerType: 'numeric',
    primaryAnswer: '3.50', alternativeAnswers: ['$3.50', '3.5', '$3.5'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find the cost per pencil.' },
      { level: 'guide', text: 'Cost per pencil $= 1.50 \\div 3 = 0.50$.' },
      { level: 'reveal', text: '$7 \\times 0.50 = 3.50$.' },
    ],
    explanation: ['Per pencil: $1.50 \\div 3 = 0.50$.', 'For $7$: $7 \\times 0.50 = 3.50$.', 'Total: \\$$3.50$.'],
    tags: ['ratio-table', 'money'], estimatedSeconds: 50,
  },
  {
    domain: '6.RP', num: 25, unit: 3, order: 5, slug: 'rt-mixed',
    standard: '6.RP.A.3.a', difficulty: 2,
    prompt: 'In a ratio table $\\frac{x}{y}$: $2/8$, $5/?$, $10/40$. What is the missing $y$?',
    answerType: 'numeric',
    primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the ratio $y \\div x$ from the other rows.' },
      { level: 'guide', text: '$8/2 = 4$ and $40/10 = 4$, so $y = 4x$.' },
      { level: 'reveal', text: 'For $x = 5$: $y = 5 \\times 4 = 20$.' },
    ],
    explanation: ['Pattern: $y = 4x$.', 'For $x = 5$: $y = 20$.'],
    tags: ['MAP-practice', 'ratio-table'], estimatedSeconds: 50,
  },
  {
    domain: '6.RP', num: 26, unit: 3, order: 6, slug: 'rt-time-distance',
    standard: '6.RP.A.3.b', difficulty: 2,
    prompt: 'A bike goes $5$ miles in $20$ minutes. How many minutes for $15$ miles?',
    answerType: 'numeric',
    primaryAnswer: '60', alternativeAnswers: ['60 minutes', '1 hour'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$15$ is how many times $5$?' },
      { level: 'guide', text: 'Multiply both sides by $3$.' },
      { level: 'reveal', text: '$5 \\times 3 = 15$ miles, $20 \\times 3 = 60$ min.' },
    ],
    explanation: ['Scale by $3$: $5 \\to 15$.', 'Time: $20 \\times 3 = 60$ minutes.'],
    tags: ['ratio-table', 'unit-rate'], estimatedSeconds: 50,
  },
  {
    domain: '6.RP', num: 27, unit: 3, order: 7, slug: 'rt-paint-mix',
    standard: '6.RP.A.3', difficulty: 3,
    prompt: 'Paint mix: $2$ red : $3$ blue makes purple. To make purple with $9$ blue, how much red?',
    answerType: 'numeric',
    primaryAnswer: '6', alternativeAnswers: ['6 cups', '6 parts'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the scale factor from $3$ blue to $9$ blue.' },
      { level: 'guide', text: '$9 \\div 3 = 3$. Apply $\\times 3$ to red.' },
      { level: 'reveal', text: '$2 \\times 3 = 6$ parts red.' },
    ],
    explanation: ['$3 \\to 9$ is $\\times 3$.', 'Red: $2 \\times 3 = 6$.'],
    tags: ['CA', 'ratio'], estimatedSeconds: 60,
  },
  {
    domain: '6.RP', num: 28, unit: 3, order: 8, slug: 'rt-find-input',
    standard: '6.RP.A.3.a', difficulty: 3,
    prompt: 'A ratio table has $3 \\to 21$ and $? \\to 49$. What is the missing input?',
    answerType: 'numeric',
    primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the rule first.' },
      { level: 'guide', text: '$\\frac{21}{3} = 7$, so output is $7 \\times$ input.' },
      { level: 'reveal', text: 'If output is $49$, input $= 49 \\div 7 = 7$.' },
    ],
    explanation: ['Rule: output $= 7 \\times$ input.', 'Inverse: input $= 49 \\div 7 = 7$.'],
    tags: ['ratio-table'], estimatedSeconds: 55,
  },
  {
    domain: '6.RP', num: 29, unit: 3, order: 9, slug: 'rt-double-nl',
    standard: '6.RP.A.3', difficulty: 3,
    prompt: 'On a double number line, $4$ matches $24$. What value on the bottom line matches $7$ on the top?',
    answerType: 'numeric',
    primaryAnswer: '42', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The pairs form a constant ratio.' },
      { level: 'guide', text: '$24 / 4 = 6$, so bottom is $6 \\times$ top.' },
      { level: 'reveal', text: '$7 \\times 6 = 42$.' },
    ],
    explanation: ['Ratio: $6$ per $1$.', '$7 \\times 6 = 42$.'],
    tags: ['double-number-line'], estimatedSeconds: 55,
  },
  {
    domain: '6.RP', num: 30, unit: 3, order: 10, slug: 'rt-word-conv',
    standard: '6.RP.A.3.d', difficulty: 3,
    prompt: 'There are $12$ inches in $1$ foot. How many inches in $4.5$ feet?',
    answerType: 'numeric',
    primaryAnswer: '54', alternativeAnswers: ['54 in', '54 inches'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Each foot adds $12$ inches.' },
      { level: 'guide', text: 'Multiply $4.5 \\times 12$.' },
      { level: 'reveal', text: '$4 \\times 12 = 48$, plus $0.5 \\times 12 = 6$. Total: $54$ inches.' },
    ],
    explanation: ['$1$ ft $= 12$ in.', '$4.5 \\times 12 = 54$ inches.'],
    tags: ['MAP-practice', 'conversion', 'ratio-table'], estimatedSeconds: 60,
  },

  // ---------------- UNIT 4 — Equivalent ratios & graphs (1-10) ----------------
  {
    domain: '6.RP', num: 31, unit: 4, order: 1, slug: 'eq-ratio-test',
    standard: '6.RP.A.1', difficulty: 1,
    prompt: 'Is $3 : 4$ equivalent to $9 : 12$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Yes', correct: true },
      { id: 'B', label: 'No', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Simplify $9:12$ and compare.' },
      { level: 'guide', text: 'Divide both sides of $9:12$ by $3$.' },
      { level: 'reveal', text: '$9 \\div 3 = 3$, $12 \\div 3 = 4$. So $9:12 = 3:4$. Yes!' },
    ],
    explanation: ['$9:12$ divided by $3$ on both sides gives $3:4$.', 'They are equivalent.'],
    tags: ['ratio', 'equivalent'], estimatedSeconds: 30,
  },
  {
    domain: '6.RP', num: 32, unit: 4, order: 2, slug: 'eq-ratio-multiply',
    standard: '6.RP.A.1', difficulty: 1,
    prompt: 'Write a ratio equivalent to $2 : 5$ by multiplying both sides by $3$.',
    answerType: 'short-text',
    primaryAnswer: '6:15', alternativeAnswers: ['6 to 15', '6/15', '6 : 15'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply each side by $3$.' },
      { level: 'guide', text: '$2 \\times 3 = ?$ and $5 \\times 3 = ?$' },
      { level: 'reveal', text: '$6 : 15$.' },
    ],
    explanation: ['$2 \\times 3 = 6$.', '$5 \\times 3 = 15$.', 'Answer: $6:15$.'],
    tags: ['equivalent', 'ratio'], estimatedSeconds: 35,
  },
  {
    domain: '6.RP', num: 33, unit: 4, order: 3, slug: 'eq-ratio-divide',
    standard: '6.RP.A.1', difficulty: 2,
    prompt: 'Write $20 : 30$ as an equivalent ratio in **simplest form**.',
    answerType: 'short-text',
    primaryAnswer: '2:3', alternativeAnswers: ['2 to 3', '2 : 3'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the GCF and divide both.' },
      { level: 'guide', text: 'GCF of $20$ and $30$ is $10$.' },
      { level: 'reveal', text: '$20 \\div 10 = 2$, $30 \\div 10 = 3$. → $2:3$.' },
    ],
    explanation: ['GCF$(20, 30) = 10$.', 'Divide: $2:3$.'],
    tags: ['equivalent', 'simplify'], estimatedSeconds: 40,
  },
  {
    domain: '6.RP', num: 34, unit: 4, order: 4, slug: 'eq-which-not',
    standard: '6.RP.A.1', difficulty: 2,
    prompt: 'Which is **NOT** equivalent to $4 : 6$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$2 : 3$', correct: false },
      { id: 'B', label: '$8 : 12$', correct: false },
      { id: 'C', label: '$6 : 9$', correct: false },
      { id: 'D', label: '$5 : 7$', correct: true },
    ],
    primaryAnswer: 'D', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Simplify $4:6$.' },
      { level: 'guide', text: '$4:6 = 2:3$. Which option does NOT simplify to $2:3$?' },
      { level: 'reveal', text: '$5:7$ has no common factor — not equivalent.' },
    ],
    explanation: ['$4:6 = 2:3$.', '$8:12 = 2:3$, $6:9 = 2:3$, $2:3$ ✓ — all equivalent.', '$5:7$ has GCF $1$ — not equivalent.'],
    tags: ['MAP-practice', 'equivalent'], estimatedSeconds: 50,
  },
  {
    domain: '6.RP', num: 35, unit: 4, order: 5, slug: 'plot-ratio',
    standard: '6.RP.A.3.a', difficulty: 2,
    prompt: 'A ratio of $1 : 2$ is plotted on the coordinate plane. The pairs are $(1, 2), (2, 4), (3, 6)$. What is the next pair?',
    answerType: 'short-text',
    primaryAnswer: '(4, 8)', alternativeAnswers: ['(4,8)', '4, 8', '4,8'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $y$ value is always twice $x$.' },
      { level: 'guide', text: 'If $x = 4$, then $y = ?$' },
      { level: 'reveal', text: '$y = 2 \\times 4 = 8$. Pair: $(4, 8)$.' },
    ],
    explanation: ['Each $y$ is $2 \\times$ the $x$.', '$x = 4 \\Rightarrow y = 8$.', 'Pair: $(4, 8)$.'],
    tags: ['ratio', 'graph'], estimatedSeconds: 45,
  },
  {
    domain: '6.RP', num: 36, unit: 4, order: 6, slug: 'ratio-three-part',
    standard: '6.RP.A.1', difficulty: 2,
    prompt: 'A bracelet uses red, blue, and green beads in the ratio $2 : 3 : 5$. If there are $20$ beads total, how many are **green**?',
    answerType: 'numeric',
    primaryAnswer: '10', alternativeAnswers: ['10 beads'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add the parts of the ratio to get the total.' },
      { level: 'guide', text: 'Parts $= 2 + 3 + 5 = 10$. Each part $= 20 / 10 = 2$ beads.' },
      { level: 'reveal', text: 'Green has $5$ parts: $5 \\times 2 = 10$.' },
    ],
    explanation: ['Total parts: $2 + 3 + 5 = 10$.', 'Each part: $20 \\div 10 = 2$ beads.', 'Green: $5 \\times 2 = 10$.'],
    tags: ['CA', 'ratio'], estimatedSeconds: 70,
  },
  {
    domain: '6.RP', num: 37, unit: 4, order: 7, slug: 'graph-line-pairs',
    standard: '6.RP.A.3.a', difficulty: 2,
    prompt: 'A line through the origin passes through $(3, 12)$. What is the unit rate ($y$ per $1$ $x$)?',
    answerType: 'numeric',
    primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Unit rate = $y / x$ at one point.' },
      { level: 'guide', text: '$\\frac{12}{3} = ?$' },
      { level: 'reveal', text: '$12 \\div 3 = 4$.' },
    ],
    explanation: ['Unit rate: $\\frac{12}{3} = 4$.', 'For every $1$ $x$, $y$ goes up by $4$.'],
    tags: ['graph', 'unit-rate'], estimatedSeconds: 50,
  },
  {
    domain: '6.RP', num: 38, unit: 4, order: 8, slug: 'ratio-scale-up',
    standard: '6.RP.A.3', difficulty: 3,
    prompt: 'In a class, the ratio of boys to girls is $3 : 4$. If there are $12$ boys, how many girls?',
    answerType: 'numeric',
    primaryAnswer: '16', alternativeAnswers: ['16 girls'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the scale factor from $3$ to $12$.' },
      { level: 'guide', text: '$12 \\div 3 = 4$.' },
      { level: 'reveal', text: 'Girls: $4 \\times 4 = 16$.' },
    ],
    explanation: ['Scale: $12 \\div 3 = 4$.', 'Girls: $4 \\times 4 = 16$.'],
    tags: ['ratio'], estimatedSeconds: 50,
  },
  {
    domain: '6.RP', num: 39, unit: 4, order: 9, slug: 'ratio-find-total',
    standard: '6.RP.A.3', difficulty: 3,
    prompt: 'The ratio of cats to dogs at a shelter is $5 : 2$. If there are $10$ cats, how many animals are there in total?',
    answerType: 'numeric',
    primaryAnswer: '14', alternativeAnswers: ['14 animals'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find the number of dogs.' },
      { level: 'guide', text: 'Cats scaled by $\\frac{10}{5} = 2$. Apply to dogs: $2 \\times 2 = 4$ dogs.' },
      { level: 'reveal', text: 'Total: $10 + 4 = 14$.' },
    ],
    explanation: ['Scale: $10 / 5 = 2$.', 'Dogs: $2 \\times 2 = 4$.', 'Total: $10 + 4 = 14$.'],
    tags: ['MAP-practice', 'ratio'], estimatedSeconds: 65,
  },
  {
    domain: '6.RP', num: 40, unit: 4, order: 10, slug: 'eq-prove-pair',
    standard: '6.RP.A.1', difficulty: 3,
    prompt: 'A constant-speed car covers $\\frac{120 \\text{ mi}}{2 \\text{ hr}}$. Which pair gives an equivalent rate?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$180$ mi in $4$ hr', correct: false },
      { id: 'B', label: '$300$ mi in $5$ hr', correct: true },
      { id: 'C', label: '$240$ mi in $3$ hr', correct: false },
      { id: 'D', label: '$90$ mi in $2$ hr', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Find the unit rate from $120 / 2$ first.' },
      { level: 'guide', text: '$120 / 2 = 60$ mph. Check each option.' },
      { level: 'reveal', text: 'B: $300 / 5 = 60$ mph ✓.' },
    ],
    explanation: ['Unit rate: $120 / 2 = 60$ mph.', 'A: $45$ mph; B: $60$ mph ✓; C: $80$ mph; D: $45$ mph.'],
    tags: ['CA', 'equivalent'], estimatedSeconds: 75,
  },

  // ---------------- UNIT 5 — Percent (orders 1-10) ----------------
  {
    domain: '6.RP', num: 41, unit: 5, order: 1, slug: 'pct-25',
    standard: '6.RP.A.3.c', difficulty: 1,
    prompt: 'What is $25\\%$ of $80$?',
    answerType: 'numeric',
    primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$25\\%$ is the same as $\\frac{1}{4}$.' },
      { level: 'guide', text: 'Find $\\frac{1}{4}$ of $80$.' },
      { level: 'reveal', text: '$80 \\div 4 = 20$.' },
    ],
    explanation: ['$25\\% = 0.25 = \\frac{1}{4}$.', '$80 \\div 4 = 20$.'],
    tags: ['percent'], estimatedSeconds: 30,
  },
  {
    domain: '6.RP', num: 42, unit: 5, order: 2, slug: 'pct-10',
    standard: '6.RP.A.3.c', difficulty: 1,
    prompt: 'What is $10\\%$ of $250$?',
    answerType: 'numeric',
    primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$10\\%$ means $\\frac{1}{10}$.' },
      { level: 'guide', text: 'Move the decimal one place left.' },
      { level: 'reveal', text: '$250 \\div 10 = 25$.' },
    ],
    explanation: ['$10\\% = 0.10$.', '$250 \\times 0.10 = 25$.'],
    tags: ['percent'], estimatedSeconds: 25,
  },
  {
    domain: '6.RP', num: 43, unit: 5, order: 3, slug: 'pct-50',
    standard: '6.RP.A.3.c', difficulty: 1,
    prompt: 'What is $50\\%$ of $42$?',
    answerType: 'numeric',
    primaryAnswer: '21', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$50\\%$ is one half.' },
      { level: 'guide', text: 'Divide by $2$.' },
      { level: 'reveal', text: '$42 \\div 2 = 21$.' },
    ],
    explanation: ['$50\\% = \\frac{1}{2}$.', '$42 \\div 2 = 21$.'],
    tags: ['percent'], estimatedSeconds: 25,
  },
  {
    domain: '6.RP', num: 44, unit: 5, order: 4, slug: 'pct-find-part',
    standard: '6.RP.A.3.c', difficulty: 2,
    prompt: 'What is $30\\%$ of $90$?',
    answerType: 'numeric',
    primaryAnswer: '27', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$30\\% = 0.30$.' },
      { level: 'guide', text: 'Multiply $90 \\times 0.30$.' },
      { level: 'reveal', text: '$90 \\times 0.30 = 27$.' },
    ],
    explanation: ['Convert: $30\\% = 0.30$.', '$90 \\times 0.30 = 27$.'],
    tags: ['percent'], estimatedSeconds: 35,
  },
  {
    domain: '6.RP', num: 45, unit: 5, order: 5, slug: 'pct-as-fraction',
    standard: '6.RP.A.3.c', difficulty: 2,
    prompt: 'Express $75\\%$ as a **fraction** in simplest form.',
    answerType: 'fraction',
    primaryAnswer: '3/4', alternativeAnswers: ['3 over 4', '0.75'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Percent means "per $100$".' },
      { level: 'guide', text: '$\\frac{75}{100}$. Simplify it.' },
      { level: 'reveal', text: 'GCF of $75$ and $100$ is $25$. $\\frac{75}{100} = \\frac{3}{4}$.' },
    ],
    explanation: ['$75\\% = \\frac{75}{100}$.', 'Divide both by $25$: $\\frac{3}{4}$.'],
    tags: ['percent', 'fraction'], estimatedSeconds: 45,
  },
  {
    domain: '6.RP', num: 46, unit: 5, order: 6, slug: 'pct-find-whole',
    standard: '6.RP.A.3.c', difficulty: 2,
    prompt: '$20$ is $10\\%$ of what number?',
    answerType: 'numeric',
    primaryAnswer: '200', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$10\\%$ of something is $20$. The whole is $10$ times bigger.' },
      { level: 'guide', text: 'Multiply $20 \\times 10$.' },
      { level: 'reveal', text: '$20 \\times 10 = 200$.' },
    ],
    explanation: ['If $10\\%$ is $20$, then $100\\%$ is $20 \\times 10 = 200$.'],
    alternativeExplanations: [{
      title: 'Using an equation',
      steps: ['$0.10 \\cdot x = 20$.', 'Divide both sides by $0.10$: $x = 200$.'],
    }],
    tags: ['percent', 'find-whole'], estimatedSeconds: 55,
  },
  {
    domain: '6.RP', num: 47, unit: 5, order: 7, slug: 'pct-tax',
    standard: '6.RP.A.3.c', difficulty: 3,
    prompt: 'A shirt costs \\$$20$ plus $8\\%$ tax. What is the **total** cost?',
    answerType: 'numeric',
    primaryAnswer: '21.60', alternativeAnswers: ['$21.60', '21.6', '$21.6'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find $8\\%$ of $20$, then add to $20$.' },
      { level: 'guide', text: '$8\\%$ of $20 = 1.60$.' },
      { level: 'reveal', text: '$20 + 1.60 = 21.60$.' },
    ],
    explanation: ['Tax: $20 \\times 0.08 = 1.60$.', 'Total: $20 + 1.60 = 21.60$.', 'Cost is \\$$21.60$.'],
    tags: ['CA', 'percent', 'money'], estimatedSeconds: 65,
  },
  {
    domain: '6.RP', num: 48, unit: 5, order: 8, slug: 'pct-tip',
    standard: '6.RP.A.3.c', difficulty: 3,
    prompt: 'You leave a $15\\%$ tip on a \\$$40$ meal. How much is the tip?',
    answerType: 'numeric',
    primaryAnswer: '6', alternativeAnswers: ['$6', '$6.00'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$10\\%$ of $40$ is $4$. What\'s $5\\%$?' },
      { level: 'guide', text: '$5\\%$ is half of $10\\%$, so $5\\% = 2$. Add: $10\\% + 5\\% = 4 + 2 = 6$.' },
      { level: 'reveal', text: '$15\\%$ of $40 = 6$ dollars.' },
    ],
    explanation: ['$10\\%$ of $40 = 4$.', '$5\\%$ of $40 = 2$.', 'Total $15\\%$: $4 + 2 = 6$ dollars.'],
    tags: ['MAP-practice', 'percent', 'tip'], estimatedSeconds: 65,
  },

  // ---------------- UNIT 6 — Mixed application (1-10) ----------------
  {
    domain: '6.RP', num: 49, unit: 6, order: 1, slug: 'mix-conversion',
    standard: '6.RP.A.3.d', difficulty: 1,
    prompt: 'There are $4$ quarts in $1$ gallon. How many quarts in $3$ gallons?',
    answerType: 'numeric',
    primaryAnswer: '12', alternativeAnswers: ['12 quarts'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Each gallon adds $4$ quarts.' },
      { level: 'guide', text: 'Multiply $3 \\times 4$.' },
      { level: 'reveal', text: '$3 \\times 4 = 12$.' },
    ],
    explanation: ['$3 \\times 4 = 12$ quarts.'],
    tags: ['conversion'], estimatedSeconds: 30,
  },
  {
    domain: '6.RP', num: 50, unit: 6, order: 2, slug: 'mix-discount',
    standard: '6.RP.A.3.c', difficulty: 2,
    prompt: 'A \\$$60$ jacket is $25\\%$ off. What is the **sale price**?',
    answerType: 'numeric',
    primaryAnswer: '45', alternativeAnswers: ['$45', '$45.00'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the discount, then subtract.' },
      { level: 'guide', text: 'Discount $= 25\\%$ of $60 = 15$.' },
      { level: 'reveal', text: 'Sale: $60 - 15 = 45$ dollars.' },
    ],
    explanation: ['$25\\%$ of $60$: $60 \\div 4 = 15$.', 'Sale: $60 - 15 = 45$.'],
    alternativeExplanations: [{
      title: 'Pay percent shortcut',
      steps: ['Sale price is $75\\%$ of original.', '$60 \\times 0.75 = 45$ dollars.'],
    }],
    tags: ['CA', 'percent', 'discount'], estimatedSeconds: 55,
  },
  {
    domain: '6.RP', num: 51, unit: 6, order: 3, slug: 'mix-bestbuy',
    standard: '6.RP.A.2', difficulty: 2,
    prompt: '$6$ pencils for \\$$1.20$ or $10$ pencils for \\$$1.80$. Which has the **lower** price per pencil?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$6$ for \\$$1.20$', correct: false },
      { id: 'B', label: '$10$ for \\$$1.80$', correct: true },
      { id: 'C', label: 'Same', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Find price per pencil for both.' },
      { level: 'guide', text: 'A: $1.20 / 6$. B: $1.80 / 10$.' },
      { level: 'reveal', text: 'A: \\$$0.20$/pencil; B: \\$$0.18$/pencil. B wins.' },
    ],
    explanation: ['A: $\\$1.20 \\div 6 = \\$0.20$.', 'B: $\\$1.80 \\div 10 = \\$0.18$.', 'B is cheaper per pencil.'],
    tags: ['MAP-practice', 'unit-price'], estimatedSeconds: 60,
  },
  {
    domain: '6.RP', num: 52, unit: 6, order: 4, slug: 'mix-cooking',
    standard: '6.RP.A.3', difficulty: 2,
    prompt: 'A recipe for $4$ servings uses $2$ cups of milk. How many cups for $10$ servings?',
    answerType: 'numeric',
    primaryAnswer: '5', alternativeAnswers: ['5 cups'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find milk per serving.' },
      { level: 'guide', text: 'Per serving: $2 \\div 4 = 0.5$ cup.' },
      { level: 'reveal', text: '$10 \\times 0.5 = 5$ cups.' },
    ],
    explanation: ['Per serving: $2 / 4 = 0.5$ cup.', 'For $10$: $10 \\times 0.5 = 5$ cups.'],
    tags: ['CA', 'recipe', 'ratio'], estimatedSeconds: 60,
  },
  {
    domain: '6.RP', num: 53, unit: 6, order: 5, slug: 'mix-scale-map',
    standard: '6.RP.A.3.d', difficulty: 2,
    prompt: 'A map scale is $1$ inch $= 50$ miles. How many miles is $3.5$ inches?',
    answerType: 'numeric',
    primaryAnswer: '175', alternativeAnswers: ['175 miles'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Each inch represents $50$ miles.' },
      { level: 'guide', text: '$3.5 \\times 50$.' },
      { level: 'reveal', text: '$3 \\times 50 = 150$, plus $0.5 \\times 50 = 25$. Total: $175$.' },
    ],
    explanation: ['$3.5 \\times 50 = 175$ miles.'],
    tags: ['conversion', 'scale'], estimatedSeconds: 55,
  },
  {
    domain: '6.RP', num: 54, unit: 6, order: 6, slug: 'mix-pct-back',
    standard: '6.RP.A.3.c', difficulty: 3,
    prompt: 'A class has $30$ students. $40\\%$ are girls. How many girls?',
    answerType: 'numeric',
    primaryAnswer: '12', alternativeAnswers: ['12 girls'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$40\\% = 0.40$.' },
      { level: 'guide', text: '$30 \\times 0.40 = ?$' },
      { level: 'reveal', text: '$30 \\times 0.40 = 12$.' },
    ],
    explanation: ['$40\\%$ of $30$: $30 \\times 0.40 = 12$.'],
    tags: ['percent', 'word'], estimatedSeconds: 50,
  },
  {
    domain: '6.RP', num: 55, unit: 6, order: 7, slug: 'mix-mix-mc',
    standard: '6.RP.A.3', difficulty: 3,
    prompt: 'A bag has $\\frac{3}{5}$ red marbles. If there are $20$ marbles, how many are **NOT red**?',
    answerType: 'numeric',
    primaryAnswer: '8', alternativeAnswers: ['8 marbles'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Not red means $\\frac{2}{5}$.' },
      { level: 'guide', text: '$\\frac{2}{5}$ of $20$.' },
      { level: 'reveal', text: '$\\frac{2}{5} \\times 20 = 8$.' },
    ],
    explanation: ['Not red: $1 - \\frac{3}{5} = \\frac{2}{5}$.', '$\\frac{2}{5} \\times 20 = 8$.'],
    tags: ['MAP-practice', 'fraction', 'ratio'], estimatedSeconds: 65,
  },
  {
    domain: '6.RP', num: 56, unit: 6, order: 8, slug: 'mix-rate-table',
    standard: '6.RP.A.3.b', difficulty: 3,
    prompt: 'At a rate of $4$ tickets for \\$$10$, how much do $14$ tickets cost?',
    answerType: 'numeric',
    primaryAnswer: '35', alternativeAnswers: ['$35', '$35.00'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find cost per ticket first.' },
      { level: 'guide', text: 'Per ticket: $10 / 4 = 2.50$.' },
      { level: 'reveal', text: '$14 \\times 2.50 = 35$.' },
    ],
    explanation: ['Per ticket: $10 \\div 4 = 2.50$.', '$14 \\times 2.50 = 35$ dollars.'],
    tags: ['CA', 'rate'], estimatedSeconds: 70,
  },
  {
    domain: '6.RP', num: 57, unit: 6, order: 9, slug: 'mix-double',
    standard: '6.RP.A.3', difficulty: 3,
    prompt: 'A car uses $5$ gallons per $150$ miles. How many gallons for a $480$-mile trip?',
    answerType: 'numeric',
    primaryAnswer: '16', alternativeAnswers: ['16 gallons'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find gallons per mile (or miles per gallon).' },
      { level: 'guide', text: 'MPG: $150 / 5 = 30$. Gallons: $480 / 30$.' },
      { level: 'reveal', text: '$480 \\div 30 = 16$ gallons.' },
    ],
    explanation: ['$150 \\div 5 = 30$ mpg.', '$480 \\div 30 = 16$ gallons.'],
    tags: ['rate', 'word'], estimatedSeconds: 75,
  },
  {
    domain: '6.RP', num: 58, unit: 6, order: 10, slug: 'mix-pct-change',
    standard: '6.RP.A.3.c', difficulty: 3,
    prompt: 'A book\'s price went from \\$$20$ to \\$$25$. What is the **percent increase**?',
    answerType: 'short-text',
    primaryAnswer: '25%', alternativeAnswers: ['25 percent', '25 %'],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Find the **change**, then divide by the **original**.' },
      { level: 'guide', text: 'Change: $25 - 20 = 5$. Divide by $20$: $5/20 = 0.25$.' },
      { level: 'reveal', text: '$0.25 = 25\\%$ increase.' },
    ],
    explanation: ['Change: $25 - 20 = 5$.', '$\\frac{5}{20} = 0.25 = 25\\%$.', 'Price went up $25\\%$.'],
    tags: ['MAP-practice', 'percent-change'], estimatedSeconds: 85,
  },
  {
    domain: '6.RP', num: 59, unit: 5, order: 9, slug: 'class-ratio-mixed',
    standard: '6.RP.A.1', difficulty: 2,
    prompt: 'A class has $24$ students. The ratio of boys to girls is $2 : 1$. How many **boys** are there?',
    answerType: 'numeric',
    primaryAnswer: '16', alternativeAnswers: ['16 boys'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add parts: $2 + 1 = 3$.' },
      { level: 'guide', text: 'Each part is $24 / 3 = 8$ students.' },
      { level: 'reveal', text: 'Boys: $2 \\times 8 = 16$.' },
    ],
    explanation: ['Parts: $3$. Each part: $24 / 3 = 8$.', 'Boys: $2 \\times 8 = 16$.'],
    tags: ['ratio'], estimatedSeconds: 60,
  },
  {
    domain: '6.RP', num: 60, unit: 5, order: 10, slug: 'pct-back-from-raise',
    standard: '6.RP.A.3.c', difficulty: 3,
    prompt: 'After a $10\\%$ raise, a worker earns \\$$22$/hr. What was the original hourly wage?',
    answerType: 'numeric',
    primaryAnswer: '20', alternativeAnswers: ['$20', '$20.00'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'New wage is $110\\%$ of original.' },
      { level: 'guide', text: '$1.10 \\cdot x = 22$, so $x = 22 / 1.10$.' },
      { level: 'reveal', text: '$22 \\div 1.10 = 20$.' },
    ],
    explanation: ['$110\\%$ of original $= 22$.', '$22 \\div 1.10 = 20$.', 'Original: \\$$20$/hr.'],
    tags: ['CA', 'percent', 'work-back'], estimatedSeconds: 90,
  },
];
