import type { SeedProblem } from './types';

// 6.SP — Statistics & Probability. Adds 52 new (5 to U1, 7 to U2, 10 each to U3-U6).

export const problems6SP: SeedProblem[] = [
  // ---------------- UNIT 1 — Center & spread basics (orders 6-10) ----------------
  {
    domain: '6.SP', num: 9, unit: 1, order: 6, slug: 'mean-basic',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the **mean** of $3, 7, 8, 6$.',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Mean = sum divided by count.' },
      { level: 'guide', text: 'Sum: $3 + 7 + 8 + 6 = 24$. Count: $4$.' },
      { level: 'reveal', text: '$24 \\div 4 = 6$.' },
    ],
    explanation: ['Sum: $24$. Count: $4$. Mean: $6$.'],
    tags: ['mean'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 10, unit: 1, order: 7, slug: 'median-odd',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the **median** of $2, 5, 9, 11, 7$.',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sort first.' },
      { level: 'guide', text: 'Sorted: $2, 5, 7, 9, 11$. Middle value?' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['Sorted: $2, 5, 7, 9, 11$.', 'Middle: $7$.'],
    tags: ['median'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 11, unit: 1, order: 8, slug: 'mode-basic',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the **mode** of $1, 4, 4, 7, 4, 2$.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Mode = most frequent.' },
      { level: 'guide', text: 'Count: $4$ appears $3$ times.' },
      { level: 'reveal', text: '$4$.' },
    ],
    explanation: ['$4$ appears most often.', 'Mode: $4$.'],
    tags: ['mode'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 12, unit: 1, order: 9, slug: 'range-basic',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the **range** of $12, 5, 18, 9, 14$.',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Range = max - min.' },
      { level: 'guide', text: 'Max: $18$. Min: $5$.' },
      { level: 'reveal', text: '$18 - 5 = 13$.' },
    ],
    explanation: ['Max: $18$, Min: $5$.', 'Range: $13$.'],
    tags: ['range'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 13, unit: 1, order: 10, slug: 'mean-include-zero',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mean of $0, 4, 6, 10$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Don\'t forget to count $0$.' },
      { level: 'guide', text: 'Sum: $0 + 4 + 6 + 10 = 20$. Count: $4$.' },
      { level: 'reveal', text: '$20 / 4 = 5$.' },
    ],
    explanation: ['Sum: $20$. Count: $4$. Mean: $5$.'],
    tags: ['mean'], estimatedSeconds: 45,
  },

  // ---------------- UNIT 2 — Stat questions & MAD (orders 4-10) ----------------
  {
    domain: '6.SP', num: 14, unit: 2, order: 4, slug: 'is-statistical',
    standard: '6.SP.A.1', difficulty: 1,
    prompt: 'Which is a **statistical** question?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'How old is my teacher?', correct: false },
      { id: 'B', label: 'How tall are students in our class?', correct: true },
      { id: 'C', label: 'What time is it now?', correct: false },
      { id: 'D', label: 'How many days in a week?', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Statistical questions have varied answers.' },
      { level: 'guide', text: 'Which one expects different answers from different people?' },
      { level: 'reveal', text: 'B — students\' heights vary.' },
    ],
    explanation: ['Statistical questions anticipate variability.', 'Heights of students vary across the class.'],
    tags: ['statistical-question'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 15, unit: 2, order: 5, slug: 'mean-vs-median',
    standard: '6.SP.A.3', difficulty: 2,
    prompt: 'A dataset is: $4, 5, 6, 7, 100$. Which is **larger**, mean or median?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Mean', correct: true },
      { id: 'B', label: 'Median', correct: false },
      { id: 'C', label: 'They are equal', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The $100$ is an outlier — it pulls the mean up.' },
      { level: 'guide', text: 'Mean: $122/5 = 24.4$. Median: $6$.' },
      { level: 'reveal', text: 'Mean ($24.4$) > median ($6$).' },
    ],
    explanation: ['Mean: $(4 + 5 + 6 + 7 + 100)/5 = 24.4$.', 'Median: $6$.', 'Mean is much larger because of the outlier.'],
    tags: ['MAP-practice', 'mean', 'median'], estimatedSeconds: 70,
  },
  {
    domain: '6.SP', num: 16, unit: 2, order: 6, slug: 'mean-decimal',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mean of $2.5, 3.5, 4$.',
    answerType: 'numeric',
    primaryAnswer: '3.33', alternativeAnswers: ['10/3', '3.333', '3.3'],
    acceptanceMode: 'numeric-tolerance', numericTolerance: 0.05,
    hints: [
      { level: 'nudge', text: 'Sum then divide by count.' },
      { level: 'guide', text: 'Sum: $10$. Count: $3$.' },
      { level: 'reveal', text: '$10 / 3 \\approx 3.33$.' },
    ],
    explanation: ['Sum: $2.5 + 3.5 + 4 = 10$.', '$10 / 3 \\approx 3.33$.'],
    tags: ['mean', 'decimal'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 17, unit: 2, order: 7, slug: 'median-bigger',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the median of $10, 4, 7, 12, 15, 9, 6$.',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sort the numbers.' },
      { level: 'guide', text: 'Sorted: $4, 6, 7, 9, 10, 12, 15$. Find the middle.' },
      { level: 'reveal', text: '$9$.' },
    ],
    explanation: ['Sorted: $4, 6, 7, 9, 10, 12, 15$.', '$7$ values, middle is the $4$th: $9$.'],
    tags: ['median'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 18, unit: 2, order: 8, slug: 'spread-larger-set',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Which set has greater **range**: $\\{5, 7, 9\\}$ or $\\{2, 5, 9, 14\\}$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$\\{5, 7, 9\\}$', correct: false },
      { id: 'B', label: '$\\{2, 5, 9, 14\\}$', correct: true },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Range = max - min for each.' },
      { level: 'guide', text: 'A: $9 - 5 = 4$. B: $14 - 2 = 12$.' },
      { level: 'reveal', text: 'B has range $12$.' },
    ],
    explanation: ['A range: $4$. B range: $12$.', 'B is greater.'],
    tags: ['range', 'compare'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 19, unit: 2, order: 9, slug: 'mean-bigger-set',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mean of $11, 13, 14, 16, 18, 18$.',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sum / count.' },
      { level: 'guide', text: 'Sum: $11 + 13 + 14 + 16 + 18 + 18 = 90$. Count: $6$.' },
      { level: 'reveal', text: '$90 / 6 = 15$.' },
    ],
    explanation: ['Sum: $90$. Count: $6$. Mean: $15$.'],
    tags: ['mean'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 20, unit: 2, order: 10, slug: 'outlier-effect',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'A dataset $\\{8, 10, 12, 14\\}$ has mean $11$. Add an outlier of $50$. What is the new mean?',
    answerType: 'numeric', primaryAnswer: '18.8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sum increases by $50$, count increases by $1$.' },
      { level: 'guide', text: 'New sum: $44 + 50 = 94$. New count: $5$.' },
      { level: 'reveal', text: '$94 / 5 = 18.8$.' },
    ],
    explanation: ['Old sum: $44$. New sum: $94$.', 'New count: $5$.', 'New mean: $18.8$.'],
    tags: ['CA', 'mean', 'outlier'], estimatedSeconds: 80,
  },

  // ---------------- UNIT 3 — Variability (IQR, MAD intro) (1-10) ----------------
  {
    domain: '6.SP', num: 21, unit: 3, order: 1, slug: 'iqr-intro',
    standard: '6.SP.A.3', difficulty: 2,
    prompt: 'In the data $1, 3, 5, 7, 9, 11, 13$, what is the median?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'It\'s already sorted. Find the middle.' },
      { level: 'guide', text: '$7$ numbers, middle is $4$th.' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['Middle of $7$ sorted: $7$.'],
    tags: ['median'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 22, unit: 3, order: 2, slug: 'q1-q3',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $1, 3, 5, 7, 9, 11, 13$: $Q1$ is the median of the lower half. What is $Q1$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Lower half: $1, 3, 5$.' },
      { level: 'guide', text: 'Median of $1, 3, 5$.' },
      { level: 'reveal', text: '$3$.' },
    ],
    explanation: ['Lower half: $1, 3, 5$.', 'Median: $3$.'],
    tags: ['CA', 'quartile'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 23, unit: 3, order: 3, slug: 'iqr-compute',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $1, 3, 5, 7, 9, 11, 13$: $Q1 = 3$, $Q3 = 11$. What is the IQR?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR = $Q3 - Q1$.' },
      { level: 'guide', text: '$11 - 3$.' },
      { level: 'reveal', text: '$8$.' },
    ],
    explanation: ['IQR $= 11 - 3 = 8$.'],
    tags: ['MAP-practice', 'IQR'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 24, unit: 3, order: 4, slug: 'mad-step',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $\\{2, 4, 6\\}$ (mean $4$), find the mean absolute deviation (MAD).',
    answerType: 'fraction',
    primaryAnswer: '4/3', alternativeAnswers: ['1.33', '1.333'],
    acceptanceMode: 'numeric-tolerance', numericTolerance: 0.05,
    hints: [
      { level: 'nudge', text: 'Find each distance from the mean, then average.' },
      { level: 'guide', text: 'Distances: $|2-4| = 2, |4-4| = 0, |6-4| = 2$.' },
      { level: 'reveal', text: 'Sum: $4$. Average: $4/3 \\approx 1.33$.' },
    ],
    explanation: ['Distances from $4$: $2, 0, 2$.', 'Mean: $4 / 3 \\approx 1.33$.'],
    tags: ['MAD'], estimatedSeconds: 80,
  },
  {
    domain: '6.SP', num: 25, unit: 3, order: 5, slug: 'range-spread',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the range of $8, 12, 7, 15, 9$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Max minus min.' },
      { level: 'guide', text: 'Max: $15$, Min: $7$.' },
      { level: 'reveal', text: '$15 - 7 = 8$.' },
    ],
    explanation: ['$15 - 7 = 8$.'],
    tags: ['range'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 26, unit: 3, order: 6, slug: 'spread-compare',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Set $A$: $5, 6, 7$. Set $B$: $1, 6, 11$. Which has greater spread?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'A', correct: false },
      { id: 'B', label: 'B', correct: true },
      { id: 'C', label: 'Same', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Spread = how far apart the values are.' },
      { level: 'guide', text: 'A range: $2$. B range: $10$.' },
      { level: 'reveal', text: 'B.' },
    ],
    explanation: ['A: range $2$. B: range $10$.', 'B has greater spread.'],
    tags: ['spread'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 27, unit: 3, order: 7, slug: 'find-q3',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $2, 4, 6, 8, 10, 12, 14, 16, 18$: median is $10$. What is $Q3$?',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Upper half: $12, 14, 16, 18$.' },
      { level: 'guide', text: 'Median of $12, 14, 16, 18$: average of $14$ and $16$.' },
      { level: 'reveal', text: '$(14 + 16)/2 = 15$.' },
    ],
    explanation: ['Upper half (above median): $12, 14, 16, 18$.', 'Median of upper: $15$.'],
    tags: ['quartile'], estimatedSeconds: 60,
  },
  {
    domain: '6.SP', num: 28, unit: 3, order: 8, slug: 'mad-vocab',
    standard: '6.SP.A.3', difficulty: 1,
    prompt: 'MAD measures the **average distance** of values from what?',
    answerType: 'short-text',
    primaryAnswer: 'mean', alternativeAnswers: ['the mean', 'average'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'MAD = Mean Absolute Deviation — from what center?' },
      { level: 'guide', text: 'It uses the mean as center.' },
      { level: 'reveal', text: 'The mean.' },
    ],
    explanation: ['MAD is the mean of $|x - \\bar{x}|$ for each value.'],
    tags: ['MAD', 'vocabulary'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 29, unit: 3, order: 9, slug: 'small-range',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the range of $5, 5, 5, 5$.',
    answerType: 'numeric', primaryAnswer: '0', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Max minus min.' },
      { level: 'guide', text: 'Max and min are both $5$.' },
      { level: 'reveal', text: '$5 - 5 = 0$.' },
    ],
    explanation: ['All values equal $5$. Range: $0$.'],
    tags: ['range'], estimatedSeconds: 25,
  },
  {
    domain: '6.SP', num: 30, unit: 3, order: 10, slug: 'iqr-bigger',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $1, 2, 4, 5, 7, 8, 10, 11$: $Q1 = 2.5$, $Q3 = 9$. Find IQR.',
    answerType: 'numeric', primaryAnswer: '6.5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR = $Q3 - Q1$.' },
      { level: 'guide', text: '$9 - 2.5$.' },
      { level: 'reveal', text: '$6.5$.' },
    ],
    explanation: ['$Q3 - Q1 = 6.5$.'],
    tags: ['CA', 'IQR'], estimatedSeconds: 50,
  },

  // ---------------- UNIT 4 — Data displays (1-10) ----------------
  {
    domain: '6.SP', num: 31, unit: 4, order: 1, slug: 'dot-plot-mode',
    standard: '6.SP.B.4', difficulty: 1,
    prompt: 'A dot plot shows: value $2$ has $3$ dots, $4$ has $5$ dots, $6$ has $2$ dots. What is the mode?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Mode = most dots.' },
      { level: 'guide', text: 'Most dots is at $4$.' },
      { level: 'reveal', text: '$4$.' },
    ],
    explanation: ['Value $4$ has $5$ dots — the most.', 'Mode: $4$.'],
    tags: ['dot-plot'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 32, unit: 4, order: 2, slug: 'histogram-bin',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A histogram groups data into bins. If bin $0-9$ has $4$ values and bin $10-19$ has $7$ values, which bin has more?',
    answerType: 'short-text',
    primaryAnswer: '10-19', alternativeAnswers: ['10–19', '10 to 19'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Higher bar = more values.' },
      { level: 'guide', text: '$7 > 4$.' },
      { level: 'reveal', text: '$10$–$19$.' },
    ],
    explanation: ['$10$–$19$ has $7$ vs. $4$ in $0$–$9$.', 'More values in $10$–$19$.'],
    tags: ['histogram'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 33, unit: 4, order: 3, slug: 'box-plot-median',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'In a box plot, the line inside the box represents what?',
    answerType: 'short-text',
    primaryAnswer: 'median', alternativeAnswers: ['the median'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A box plot shows 5 numbers: min, Q1, ?, Q3, max.' },
      { level: 'guide', text: 'Center of the box is the median.' },
      { level: 'reveal', text: 'Median.' },
    ],
    explanation: ['The vertical line in a box plot marks the median.'],
    tags: ['box-plot'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 34, unit: 4, order: 4, slug: 'dot-plot-mean',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A dot plot shows: $2, 3, 3, 4, 5$. Find the mean.',
    answerType: 'numeric', primaryAnswer: '3.4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add all dot-values and divide by count.' },
      { level: 'guide', text: 'Sum: $2 + 3 + 3 + 4 + 5 = 17$. Count: $5$.' },
      { level: 'reveal', text: '$17 / 5 = 3.4$.' },
    ],
    explanation: ['Sum: $17$. Count: $5$. Mean: $3.4$.'],
    tags: ['dot-plot', 'mean'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 35, unit: 4, order: 5, slug: 'histogram-bins-count',
    standard: '6.SP.B.4', difficulty: 1,
    prompt: 'A histogram has bins for $0-4, 5-9, 10-14, 15-19, 20-24$. How many bins?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Just count them.' },
      { level: 'guide', text: 'List them out.' },
      { level: 'reveal', text: '$5$.' },
    ],
    explanation: ['Bins: $5$.'],
    tags: ['histogram'], estimatedSeconds: 25,
  },
  {
    domain: '6.SP', num: 36, unit: 4, order: 6, slug: 'box-plot-range',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A box plot shows min $= 5$ and max $= 25$. What is the range?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Max - min.' },
      { level: 'guide', text: '$25 - 5$.' },
      { level: 'reveal', text: '$20$.' },
    ],
    explanation: ['Range: $25 - 5 = 20$.'],
    tags: ['box-plot', 'range'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 37, unit: 4, order: 7, slug: 'choose-display',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'Which display is best for showing the **shape** of a distribution with many values?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Dot plot', correct: false },
      { id: 'B', label: 'Histogram', correct: true },
      { id: 'C', label: 'Box plot', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Dot plots get cluttered with many values.' },
      { level: 'guide', text: 'Histograms bin values to show shape.' },
      { level: 'reveal', text: 'Histogram.' },
    ],
    explanation: ['Histograms group values into bins and show the shape clearly.'],
    tags: ['CA', 'display'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 38, unit: 4, order: 8, slug: 'dot-plot-count',
    standard: '6.SP.B.4', difficulty: 1,
    prompt: 'A dot plot has $3, 4, 5$ dots at three values. How many data points total?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add the dots.' },
      { level: 'guide', text: '$3 + 4 + 5$.' },
      { level: 'reveal', text: '$12$.' },
    ],
    explanation: ['$3 + 4 + 5 = 12$.'],
    tags: ['dot-plot'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 39, unit: 4, order: 9, slug: 'histogram-shape',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'A histogram has a tail on the **right** (bigger bin heights on the left). The distribution is:',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Symmetric', correct: false },
      { id: 'B', label: 'Skewed right', correct: true },
      { id: 'C', label: 'Skewed left', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The skew direction follows the tail.' },
      { level: 'guide', text: 'Tail on right = skewed right.' },
      { level: 'reveal', text: 'Skewed right.' },
    ],
    explanation: ['Tail extends to the right → skewed right.'],
    tags: ['MAP-practice', 'histogram', 'shape'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 40, unit: 4, order: 10, slug: 'box-plot-q1',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A box plot has $Q1 = 12$ and $Q3 = 20$. What is the IQR?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR = $Q3 - Q1$.' },
      { level: 'guide', text: '$20 - 12$.' },
      { level: 'reveal', text: '$8$.' },
    ],
    explanation: ['IQR: $20 - 12 = 8$.'],
    tags: ['box-plot', 'IQR'], estimatedSeconds: 35,
  },

  // ---------------- UNIT 5 — Describing distributions (1-10) ----------------
  {
    domain: '6.SP', num: 41, unit: 5, order: 1, slug: 'shape-symmetric',
    standard: '6.SP.B.5.d', difficulty: 1,
    prompt: 'In a **symmetric** distribution, the mean and median are typically:',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Equal', correct: true },
      { id: 'B', label: 'Mean much greater', correct: false },
      { id: 'C', label: 'Median much greater', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Symmetric means evenly balanced.' },
      { level: 'guide', text: 'No outliers pulling either way.' },
      { level: 'reveal', text: 'Equal.' },
    ],
    explanation: ['In symmetric distributions, mean ≈ median.'],
    tags: ['shape'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 42, unit: 5, order: 2, slug: 'outlier-effect-2',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'Outliers usually affect which measure more: mean or median?',
    answerType: 'short-text',
    primaryAnswer: 'mean', alternativeAnswers: ['the mean'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'One big number can shift the average a lot.' },
      { level: 'guide', text: 'Median uses position; mean uses value.' },
      { level: 'reveal', text: 'Mean.' },
    ],
    explanation: ['Mean uses every value, so outliers shift it.', 'Median is based on rank — outliers barely affect it.'],
    tags: ['outlier'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 43, unit: 5, order: 3, slug: 'cluster',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'In a histogram, a region where bins are very tall is called a:',
    answerType: 'short-text',
    primaryAnswer: 'cluster', alternativeAnswers: ['Cluster'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A clustering of values.' },
      { level: 'guide', text: 'Many values bunched together.' },
      { level: 'reveal', text: 'Cluster.' },
    ],
    explanation: ['Tall bins close together form a cluster.'],
    tags: ['shape', 'vocabulary'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 44, unit: 5, order: 4, slug: 'shape-skew-left',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'A distribution has a long tail on the **left**. The mean is typically:',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Less than median', correct: true },
      { id: 'B', label: 'Greater than median', correct: false },
      { id: 'C', label: 'Equal to median', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Skew direction = tail direction.' },
      { level: 'guide', text: 'Skewed left → tail of small values pulls mean down.' },
      { level: 'reveal', text: 'Mean < median.' },
    ],
    explanation: ['Long tail on left pulls the mean toward small values.', 'Mean < median.'],
    tags: ['MAP-practice', 'shape', 'skew'], estimatedSeconds: 60,
  },
  {
    domain: '6.SP', num: 45, unit: 5, order: 5, slug: 'gap',
    standard: '6.SP.B.5.d', difficulty: 1,
    prompt: 'In a dot plot, a region with no dots is called a:',
    answerType: 'short-text',
    primaryAnswer: 'gap', alternativeAnswers: ['Gap'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'An empty space.' },
      { level: 'guide', text: 'Same word as for a space between things.' },
      { level: 'reveal', text: 'Gap.' },
    ],
    explanation: ['Empty regions are called gaps.'],
    tags: ['vocabulary'], estimatedSeconds: 25,
  },
  {
    domain: '6.SP', num: 46, unit: 5, order: 6, slug: 'measure-of-center',
    standard: '6.SP.A.2', difficulty: 1,
    prompt: 'Which is NOT a measure of center?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Mean', correct: false },
      { id: 'B', label: 'Median', correct: false },
      { id: 'C', label: 'Range', correct: true },
      { id: 'D', label: 'Mode', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Range measures **spread**, not center.' },
      { level: 'guide', text: 'Mean, median, mode = center. Range = spread.' },
      { level: 'reveal', text: 'Range.' },
    ],
    explanation: ['Mean, median, mode describe center.', 'Range describes spread.'],
    tags: ['vocabulary'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 47, unit: 5, order: 7, slug: 'best-center-outliers',
    standard: '6.SP.B.5.d', difficulty: 3,
    prompt: 'A dataset has a big outlier. Which measure of center is most reliable?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Mean', correct: false },
      { id: 'B', label: 'Median', correct: true },
      { id: 'C', label: 'Mode', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Outliers shift the mean.' },
      { level: 'guide', text: 'Median is based on rank, so it\'s stable.' },
      { level: 'reveal', text: 'Median.' },
    ],
    explanation: ['Median is resistant to outliers.', 'Mean is pulled by extreme values.'],
    tags: ['CA', 'outlier', 'center'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 48, unit: 5, order: 8, slug: 'symmetric-mean',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'A symmetric dataset has mean $50$. The median is approximately:',
    answerType: 'numeric', primaryAnswer: '50', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Symmetric → mean ≈ median.' },
      { level: 'guide', text: 'Median ≈ mean.' },
      { level: 'reveal', text: '$50$.' },
    ],
    explanation: ['Symmetric: mean ≈ median.', 'Both ≈ $50$.'],
    tags: ['shape', 'mean', 'median'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 49, unit: 5, order: 9, slug: 'cluster-gap-mc',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'You see a dot plot with most dots near $20$ and a few dots near $50$. What describes the spread?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Cluster + gap', correct: true },
      { id: 'B', label: 'Symmetric', correct: false },
      { id: 'C', label: 'Uniform', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'A bunch of dots, then nothing, then a few more.' },
      { level: 'guide', text: 'Cluster around $20$ and gap before the dots at $50$.' },
      { level: 'reveal', text: 'Cluster + gap.' },
    ],
    explanation: ['Dots near $20$ are a cluster.', 'Empty area between $20$ and $50$ is a gap.'],
    tags: ['shape'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 50, unit: 5, order: 10, slug: 'best-describe-shape',
    standard: '6.SP.B.5.d', difficulty: 3,
    prompt: 'When describing a data set, which features should you mention?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Center, spread, shape', correct: true },
      { id: 'B', label: 'Just the mean', correct: false },
      { id: 'C', label: 'Color and pattern', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Three big things to look at.' },
      { level: 'guide', text: 'Where it\'s centered, how spread out, what shape.' },
      { level: 'reveal', text: 'Center, spread, and shape.' },
    ],
    explanation: ['A complete description includes center (mean/median), spread (range/IQR), and shape (symmetric, skewed, clusters, gaps, outliers).'],
    tags: ['MAP-practice', 'describe'], estimatedSeconds: 55,
  },

  // ---------------- UNIT 6 — Mixed reasoning (1-10) ----------------
  {
    domain: '6.SP', num: 51, unit: 6, order: 1, slug: 'm-mean-4',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the mean of $10, 20, 30, 40$.',
    answerType: 'numeric', primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sum / count.' },
      { level: 'guide', text: 'Sum: $100$. Count: $4$.' },
      { level: 'reveal', text: '$100 / 4 = 25$.' },
    ],
    explanation: ['Sum: $100$. Mean: $25$.'],
    tags: ['mean'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 52, unit: 6, order: 2, slug: 'm-median-4',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the median of $1, 3, 5, 7$.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Even number of values → average the middle two.' },
      { level: 'guide', text: 'Middle: $3$ and $5$. Average them.' },
      { level: 'reveal', text: '$(3 + 5)/2 = 4$.' },
    ],
    explanation: ['Middle two: $3, 5$. Mean: $4$.'],
    tags: ['median'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 53, unit: 6, order: 3, slug: 'm-question-stat',
    standard: '6.SP.A.1', difficulty: 1,
    prompt: 'Is "How tall is the Empire State Building?" a statistical question?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Yes', correct: false },
      { id: 'B', label: 'No', correct: true },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'It has just one answer.' },
      { level: 'guide', text: 'Statistical questions anticipate variability.' },
      { level: 'reveal', text: 'No — one fixed answer.' },
    ],
    explanation: ['One fixed answer → not statistical.'],
    tags: ['statistical-question'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 54, unit: 6, order: 4, slug: 'm-mean-fix',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: '$5$ scores have mean $80$. If a $6$th score of $74$ is added, the new mean is approximately:',
    answerType: 'numeric', primaryAnswer: '79', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Old sum is $5 \\times 80 = 400$.' },
      { level: 'guide', text: 'New sum: $474$. New count: $6$.' },
      { level: 'reveal', text: '$474 / 6 = 79$.' },
    ],
    explanation: ['Old sum: $400$. Add $74$: $474$.', 'Divide by $6$: $79$.'],
    tags: ['CA', 'mean'], estimatedSeconds: 75,
  },
  {
    domain: '6.SP', num: 55, unit: 6, order: 5, slug: 'm-mode-multi',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'In $\\{3, 3, 5, 7, 7, 9\\}$, how many modes?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count which values tie for most appearances.' },
      { level: 'guide', text: '$3$ appears twice; $7$ appears twice.' },
      { level: 'reveal', text: '$2$ modes.' },
    ],
    explanation: ['$3$ and $7$ both appear $2$ times.', '$2$ modes.'],
    tags: ['mode'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 56, unit: 6, order: 6, slug: 'm-iqr-quick',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Data: $5, 7, 9, 12, 15, 20, 25$ has $Q1 = 7$, $Q3 = 20$. Find IQR.',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR $= Q3 - Q1$.' },
      { level: 'guide', text: '$20 - 7$.' },
      { level: 'reveal', text: '$13$.' },
    ],
    explanation: ['IQR $= 13$.'],
    tags: ['IQR'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 57, unit: 6, order: 7, slug: 'm-display-pick',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'You have $5$ test scores from $5$ students. Which display works well?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Dot plot', correct: true },
      { id: 'B', label: 'Histogram with $1$-point bins', correct: false },
      { id: 'C', label: 'Pie chart of grade letters', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'For small datasets, dots show every value.' },
      { level: 'guide', text: 'Histograms shine with many values.' },
      { level: 'reveal', text: 'Dot plot.' },
    ],
    explanation: ['Dot plots are great for small datasets — every value is visible.'],
    tags: ['display'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 58, unit: 6, order: 8, slug: 'm-range-quick',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the range of $1, 8, 4, 12, 2$.',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Max - min.' },
      { level: 'guide', text: '$12 - 1$.' },
      { level: 'reveal', text: '$11$.' },
    ],
    explanation: ['$12 - 1 = 11$.'],
    tags: ['range'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 59, unit: 6, order: 9, slug: 'm-pick-center',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'A teacher\'s ages: $30, 31, 32, 33, 65$. Which is a better summary of "typical age"?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Mean', correct: false },
      { id: 'B', label: 'Median', correct: true },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '$65$ is an outlier.' },
      { level: 'guide', text: 'Median is resistant to outliers.' },
      { level: 'reveal', text: 'Median.' },
    ],
    explanation: ['Mean: $38.2$ (pulled up by $65$).', 'Median: $32$ (resistant to outlier).', 'Median better describes typical age.'],
    tags: ['MAP-practice', 'outlier', 'center'], estimatedSeconds: 70,
  },
  {
    domain: '6.SP', num: 60, unit: 6, order: 10, slug: 'm-mean-find-missing',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Four numbers have mean $10$. Three of them are $8, 11, 9$. What is the fourth?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Total sum is $40$ ($4 \\times 10$).' },
      { level: 'guide', text: 'Three sum to $8 + 11 + 9 = 28$.' },
      { level: 'reveal', text: '$40 - 28 = 12$.' },
    ],
    explanation: ['Sum needed: $40$. Have: $28$.', 'Missing: $12$.'],
    tags: ['CA', 'mean'], estimatedSeconds: 80,
  },

  // ============================================================
  // UNIT 7 — Statistical questions & variability (6.SP.A.1, A.2)
  // ============================================================
  {
    domain: '6.SP', num: 61, unit: 7, order: 1, slug: 'stat-q-tall-me',
    standard: '6.SP.A.1', difficulty: 1,
    prompt: 'Is "How tall am I?" a **statistical question**? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'no',
    alternativeAnswers: ['No', 'n'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Statistical questions expect a variety of answers.' },
      { level: 'guide', text: '"How tall am I?" has just one answer.' },
      { level: 'reveal', text: 'No — no variability.' },
    ],
    explanation: ['A statistical question anticipates variability.', '"How tall am I?" has a single answer → not statistical.'],
    tags: ['statistical-question'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 62, unit: 7, order: 2, slug: 'stat-q-tall-class',
    standard: '6.SP.A.1', difficulty: 1,
    prompt: 'Is "How tall are the students in my class?" a statistical question? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'yes',
    alternativeAnswers: ['Yes', 'y'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Different students may have different heights.' },
      { level: 'guide', text: 'Multiple answers expected → statistical.' },
      { level: 'reveal', text: 'Yes.' },
    ],
    explanation: ['Different students have different heights, so the question anticipates variability.', 'Yes — it is statistical.'],
    tags: ['statistical-question'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 63, unit: 7, order: 3, slug: 'stat-q-pick',
    standard: '6.SP.A.1', difficulty: 2,
    prompt: 'Which is a **statistical question**?',
    answerType: 'multiple-choice', primaryAnswer: 'B',
    choices: [
      { id: 'A', label: 'How old is your teacher?', correct: false },
      { id: 'B', label: 'How many siblings do students in your school have?', correct: true },
      { id: 'C', label: 'What is the boiling point of water?', correct: false },
    ],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Look for the question with many possible answers.' },
      { level: 'guide', text: 'Sibling counts vary across students.' },
      { level: 'reveal', text: 'B.' },
    ],
    explanation: ['A and C each have a single answer.', 'B asks across many students with varying counts → statistical.'],
    tags: ['statistical-question'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 64, unit: 7, order: 4, slug: 'anticipate-variability',
    standard: '6.SP.A.1', difficulty: 2,
    prompt: 'Fill in the blank: A statistical question anticipates ___.',
    answerType: 'short-text', primaryAnswer: 'variability',
    alternativeAnswers: ['Variability', 'variation', 'different answers'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'It expects answers to differ.' },
      { level: 'guide', text: 'The word starts with V.' },
      { level: 'reveal', text: 'variability.' },
    ],
    explanation: ['A statistical question expects a variety of answers — that is, variability.'],
    tags: ['vocabulary'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 65, unit: 7, order: 5, slug: 'stat-q-2-plus-2',
    standard: '6.SP.A.1', difficulty: 2,
    prompt: 'Is "What is $2 + 2$?" a statistical question? (yes/no)',
    answerType: 'short-text', primaryAnswer: 'no',
    alternativeAnswers: ['No', 'n'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Is there variability?' },
      { level: 'guide', text: '$2 + 2$ has exactly one answer.' },
      { level: 'reveal', text: 'No.' },
    ],
    explanation: ['$2 + 2 = 4$ — single fixed answer, no variability.', 'Not statistical.'],
    tags: ['statistical-question'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 66, unit: 7, order: 6, slug: 'stat-q-pick-tall',
    standard: '6.SP.A.1', difficulty: 2,
    prompt: 'Which one is a statistical question?',
    answerType: 'multiple-choice', primaryAnswer: 'B',
    choices: [
      { id: 'A', label: 'How tall is the Empire State Building?', correct: false },
      { id: 'B', label: 'How tall are 6th graders in our school?', correct: true },
    ],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Which has many possible answers?' },
      { level: 'guide', text: 'Many 6th graders, many heights.' },
      { level: 'reveal', text: 'B.' },
    ],
    explanation: ['A has one fixed answer.', 'B varies across students → statistical.'],
    tags: ['statistical-question'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 67, unit: 7, order: 7, slug: 'why-variability-ages',
    standard: '6.SP.A.2', difficulty: 2,
    prompt: 'Why might the data "ages of students in 6th grade" show variability?',
    answerType: 'multiple-choice', primaryAnswer: 'A',
    choices: [
      { id: 'A', label: 'Different students have different birthdays.', correct: true },
      { id: 'B', label: 'All students are exactly the same age.', correct: false },
      { id: 'C', label: 'Age is the same for everyone in 6th grade.', correct: false },
    ],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Are all 6th graders born on the same day?' },
      { level: 'guide', text: 'No — birthdays spread across many months.' },
      { level: 'reveal', text: 'A.' },
    ],
    explanation: ['6th graders are typically $11$ or $12$ depending on birthday — different ages → variability.'],
    tags: ['variability'], estimatedSeconds: 60,
  },
  {
    domain: '6.SP', num: 68, unit: 7, order: 8, slug: 'centers-names',
    standard: '6.SP.A.3', difficulty: 3,
    prompt: 'Name TWO measures of **center** for a data set (separate with a comma).',
    answerType: 'short-text', primaryAnswer: 'mean, median',
    alternativeAnswers: ['median, mean', 'mean,median', 'mean and median', 'mode, mean', 'mean, mode'],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Center asks "what is typical?"' },
      { level: 'guide', text: 'Two of: mean, median, mode.' },
      { level: 'reveal', text: 'mean, median (or mean, mode, or median, mode).' },
    ],
    explanation: ['The three measures of center are mean, median, and mode.', 'Naming any two is fine.'],
    tags: ['vocabulary', 'center'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 69, unit: 7, order: 9, slug: 'spreads-names',
    standard: '6.SP.A.3', difficulty: 3,
    prompt: 'Name TWO measures of **variability** for a data set (separate with a comma).',
    answerType: 'short-text', primaryAnswer: 'range, IQR',
    alternativeAnswers: ['IQR, range', 'range, MAD', 'MAD, range', 'IQR, MAD', 'range and IQR'],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Variability = how spread out the data is.' },
      { level: 'guide', text: 'Two of: range, IQR, MAD.' },
      { level: 'reveal', text: 'range, IQR (or any two of range / IQR / MAD).' },
    ],
    explanation: ['Measures of variability include range, IQR (interquartile range), and MAD (mean absolute deviation).'],
    tags: ['vocabulary', 'spread'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 70, unit: 7, order: 10, slug: 'no-variability-555',
    standard: '6.SP.A.2', difficulty: 3,
    prompt: 'What is the variability of the data set $\\{5,\\ 5,\\ 5\\}$?',
    answerType: 'numeric', primaryAnswer: '0', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Compare the values to each other.' },
      { level: 'guide', text: 'All values are the same.' },
      { level: 'reveal', text: 'Variability $= 0$.' },
    ],
    explanation: ['Every value equals $5$, so the data does not spread at all.', 'Range $= 5 - 5 = 0$.'],
    tags: ['MAP-practice', 'variability'], estimatedSeconds: 50,
  },

  // ============================================================
  // UNIT 8 — Center & spread II: MAD, IQR (6.SP.A.3, B.5.c/d)
  // ============================================================
  {
    domain: '6.SP', num: 71, unit: 8, order: 1, slug: 'median-3-5-7-9-11',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the median of $\\{3,\\ 5,\\ 7,\\ 9,\\ 11\\}$.',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The middle value (data is already sorted).' },
      { level: 'guide', text: 'Five values; middle is position $3$.' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['Sorted: $3, 5, 7, 9, 11$. Middle value is $7$.'],
    tags: ['median'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 72, unit: 8, order: 2, slug: 'median-2-4-6-8',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the median of $\\{2,\\ 4,\\ 6,\\ 8\\}$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Even count → average the two middle values.' },
      { level: 'guide', text: 'Middle two: $4$ and $6$. Average $= (4 + 6)/2$.' },
      { level: 'reveal', text: '$5$.' },
    ],
    explanation: ['Even number of values: average the two middle ones.', '$(4 + 6) / 2 = 5$.'],
    tags: ['median', 'even-count'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 73, unit: 8, order: 3, slug: 'q1-1-8',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find $Q_1$ (the lower quartile) of $\\{1,\\ 2,\\ 3,\\ 4,\\ 5,\\ 6,\\ 7,\\ 8\\}$.',
    answerType: 'numeric', primaryAnswer: '2.5',
    alternativeAnswers: ['5/2'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Lower half: $\\{1, 2, 3, 4\\}$.' },
      { level: 'guide', text: 'Median of the lower half: average of $2$ and $3$.' },
      { level: 'reveal', text: '$(2 + 3)/2 = 2.5$.' },
    ],
    explanation: ['Lower half: $\\{1, 2, 3, 4\\}$.', 'Median: $(2 + 3)/2 = 2.5$.'],
    tags: ['quartile'], estimatedSeconds: 60,
  },
  {
    domain: '6.SP', num: 74, unit: 8, order: 4, slug: 'q3-1-8',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find $Q_3$ (the upper quartile) of $\\{1,\\ 2,\\ 3,\\ 4,\\ 5,\\ 6,\\ 7,\\ 8\\}$.',
    answerType: 'numeric', primaryAnswer: '6.5',
    alternativeAnswers: ['13/2'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Upper half: $\\{5, 6, 7, 8\\}$.' },
      { level: 'guide', text: 'Median: $(6 + 7)/2$.' },
      { level: 'reveal', text: '$6.5$.' },
    ],
    explanation: ['Upper half: $\\{5, 6, 7, 8\\}$.', 'Median: $(6 + 7)/2 = 6.5$.'],
    tags: ['quartile'], estimatedSeconds: 60,
  },
  {
    domain: '6.SP', num: 75, unit: 8, order: 5, slug: 'iqr-1-8',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the IQR of $\\{1,\\ 2,\\ 3,\\ 4,\\ 5,\\ 6,\\ 7,\\ 8\\}$.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR $= Q_3 - Q_1$.' },
      { level: 'guide', text: '$Q_3 = 6.5$ and $Q_1 = 2.5$.' },
      { level: 'reveal', text: '$6.5 - 2.5 = 4$.' },
    ],
    explanation: ['From the previous two problems: $Q_1 = 2.5$, $Q_3 = 6.5$.', 'IQR: $6.5 - 2.5 = 4$.'],
    tags: ['IQR'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 76, unit: 8, order: 6, slug: 'mad-1-4-7-12',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the MAD (mean absolute deviation) of $\\{1,\\ 4,\\ 7,\\ 12\\}$.',
    answerType: 'numeric', primaryAnswer: '3.5',
    alternativeAnswers: ['7/2'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the mean first.' },
      { level: 'guide', text: 'Mean $= (1+4+7+12)/4 = 24/4 = 6$. Distances from $6$: $5, 2, 1, 6$.' },
      { level: 'reveal', text: 'MAD $= (5+2+1+6)/4 = 14/4 = 3.5$.' },
    ],
    explanation: ['Mean: $24/4 = 6$.', '$|1-6|=5,\\ |4-6|=2,\\ |7-6|=1,\\ |12-6|=6$. Sum: $14$.', 'MAD: $14/4 = 3.5$.'],
    alternativeExplanations: [
      { title: 'Think of it as average distance', steps: ['Each value\'s distance from the mean: $5, 2, 1, 6$.', 'Average: $3.5$ — the typical distance from the mean.'] },
    ],
    tags: ['MAP-practice', 'MAD'], estimatedSeconds: 100,
  },
  {
    domain: '6.SP', num: 77, unit: 8, order: 7, slug: 'mean-4-6-8-10-12',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mean of $\\{4,\\ 6,\\ 8,\\ 10,\\ 12\\}$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sum, then divide by the count.' },
      { level: 'guide', text: 'Sum $= 40$, count $= 5$.' },
      { level: 'reveal', text: '$40/5 = 8$.' },
    ],
    explanation: ['$4+6+8+10+12 = 40$.', '$40 / 5 = 8$.'],
    alternativeExplanations: [
      { title: 'Use symmetry', steps: ['Values evenly spaced around the middle one ($8$).', 'Mean equals the middle value: $8$.'] },
    ],
    tags: ['mean'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 78, unit: 8, order: 8, slug: 'mad-2-5-8-9',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Find the MAD of $\\{2,\\ 5,\\ 8,\\ 9\\}$.',
    answerType: 'numeric', primaryAnswer: '2.5',
    alternativeAnswers: ['5/2'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Mean first.' },
      { level: 'guide', text: 'Mean $= 24/4 = 6$. Distances: $4, 1, 2, 3$.' },
      { level: 'reveal', text: 'MAD $= (4+1+2+3)/4 = 10/4 = 2.5$.' },
    ],
    explanation: ['Mean: $24/4 = 6$.', '$|2-6|=4,\\ |5-6|=1,\\ |8-6|=2,\\ |9-6|=3$. Sum: $10$.', 'MAD: $10/4 = 2.5$.'],
    tags: ['MAP-practice', 'MAD'], estimatedSeconds: 90,
  },
  {
    domain: '6.SP', num: 79, unit: 8, order: 9, slug: 'iqr-2-16-by-2s',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Find the IQR of $\\{2,\\ 4,\\ 6,\\ 8,\\ 10,\\ 12,\\ 14,\\ 16\\}$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find $Q_1$ and $Q_3$, then subtract.' },
      { level: 'guide', text: 'Lower half: $\\{2,4,6,8\\}$, $Q_1 = 5$. Upper half: $\\{10,12,14,16\\}$, $Q_3 = 13$.' },
      { level: 'reveal', text: 'IQR $= 13 - 5 = 8$.' },
    ],
    explanation: ['Lower-half median: $(4+6)/2 = 5$ → $Q_1$.', 'Upper-half median: $(12+14)/2 = 13$ → $Q_3$.', 'IQR: $13 - 5 = 8$.'],
    tags: ['MAP-practice', 'IQR'], estimatedSeconds: 110,
  },
  {
    domain: '6.SP', num: 80, unit: 8, order: 10, slug: 'median-3-9',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'In the five-number summary of $\\{3,\\ 4,\\ 5,\\ 6,\\ 7,\\ 8,\\ 9\\}$, what is the **median**?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Seven values → middle value at position $4$.' },
      { level: 'guide', text: '$3, 4, 5, \\boxed{6}, 7, 8, 9$.' },
      { level: 'reveal', text: '$6$.' },
    ],
    explanation: ['Sorted with $7$ values, the middle is the $4$th: $6$.'],
    tags: ['MAP-practice', 'median', 'five-number-summary'], estimatedSeconds: 45,
  },

  // ============================================================
  // UNIT 9 — Dot plots, histograms & box plots II (6.SP.B.4)
  // ============================================================
  {
    domain: '6.SP', num: 81, unit: 9, order: 1, slug: 'dot-meaning',
    standard: '6.SP.B.4', difficulty: 1,
    prompt: 'On a dot plot, each dot represents ___?',
    answerType: 'short-text', primaryAnswer: 'one data point',
    alternativeAnswers: ['one value', 'one data value', 'a data point', '1 value'],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Each dot is one observation.' },
      { level: 'guide', text: '"One data ___".' },
      { level: 'reveal', text: 'one data point (or one value).' },
    ],
    explanation: ['Each dot in a dot plot represents one observation (one data value).'],
    tags: ['dot-plot'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 82, unit: 9, order: 2, slug: 'histogram-bar-height-5',
    standard: '6.SP.B.4', difficulty: 1,
    prompt: 'A histogram bar over the interval $10$–$19$ has height $5$. How many data points are in that interval?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Bar height = count.' },
      { level: 'guide', text: 'Height $= 5$ → $5$ data points.' },
      { level: 'reveal', text: '$5$.' },
    ],
    explanation: ['On a histogram, the height of a bar tells how many data points fall in that interval.', '$5$.'],
    tags: ['histogram'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 83, unit: 9, order: 3, slug: 'box-left-whisker',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'On a box plot, the left whisker reaches the ___?',
    answerType: 'short-text', primaryAnswer: 'minimum',
    alternativeAnswers: ['Minimum', 'min', 'smallest value', 'lowest value'],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Whiskers extend to the extremes.' },
      { level: 'guide', text: 'Left = smallest.' },
      { level: 'reveal', text: 'minimum.' },
    ],
    explanation: ['Left whisker → minimum value of the data. Right whisker → maximum.'],
    tags: ['box-plot'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 84, unit: 9, order: 4, slug: 'box-shows-median',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'True or false: Box plots show both the median and the quartiles.',
    answerType: 'short-text', primaryAnswer: 'true',
    alternativeAnswers: ['True', 't', 'yes'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The box ends are quartiles, the middle line is the median.' },
      { level: 'guide', text: 'Both are visible.' },
      { level: 'reveal', text: 'True.' },
    ],
    explanation: ['On a box plot: box edges $= Q_1$ and $Q_3$; the line inside $=$ median.', 'True.'],
    tags: ['box-plot'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 85, unit: 9, order: 5, slug: 'middle-50-pct',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'The middle $50\\%$ of the data sits between which two quartiles?',
    answerType: 'short-text', primaryAnswer: 'Q1 and Q3',
    alternativeAnswers: ['Q1, Q3', 'Q_1 and Q_3', 'q1 and q3'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The box of a box plot.' },
      { level: 'guide', text: 'Lower and upper quartiles.' },
      { level: 'reveal', text: '$Q_1$ and $Q_3$.' },
    ],
    explanation: ['$Q_1$ marks the $25\\%$ point and $Q_3$ marks the $75\\%$ point.', 'Between them sits the middle $50\\%$ of the data.'],
    tags: ['quartile', 'box-plot'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 86, unit: 9, order: 6, slug: 'dot-count-5',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A dot plot shows the data $\\{2, 3, 3, 5, 5, 5\\}$. How many dots sit **above the value $5$**?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count how many $5$\'s.' },
      { level: 'guide', text: '$5$ appears in the data three times.' },
      { level: 'reveal', text: '$3$.' },
    ],
    explanation: ['Three $5$\'s → three dots above $5$.'],
    tags: ['dot-plot'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 87, unit: 9, order: 7, slug: 'hist-no-gaps',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'True or false: Histogram bars are drawn **without gaps** between them.',
    answerType: 'short-text', primaryAnswer: 'true',
    alternativeAnswers: ['True', 't', 'yes'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Histograms group continuous intervals.' },
      { level: 'guide', text: 'Bars touch.' },
      { level: 'reveal', text: 'True.' },
    ],
    explanation: ['Histograms cover continuous intervals, so bars share edges.', 'True.'],
    tags: ['histogram'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 88, unit: 9, order: 8, slug: 'iqr-box-Q1-10-Q3-22',
    standard: '6.SP.B.4', difficulty: 3,
    prompt: 'A box plot has $Q_1 = 10$ and $Q_3 = 22$. Find the IQR.',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR $= Q_3 - Q_1$.' },
      { level: 'guide', text: '$22 - 10$.' },
      { level: 'reveal', text: '$12$.' },
    ],
    explanation: ['IQR $= Q_3 - Q_1 = 22 - 10 = 12$.'],
    tags: ['MAP-practice', 'IQR', 'box-plot'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 89, unit: 9, order: 9, slug: 'box-range-2-14',
    standard: '6.SP.B.4', difficulty: 3,
    prompt: 'A box plot has min $= 2$, $Q_1 = 5$, median $= 8$, $Q_3 = 11$, max $= 14$. What is the **range**?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Range $= \\text{max} - \\text{min}$.' },
      { level: 'guide', text: '$14 - 2$.' },
      { level: 'reveal', text: '$12$.' },
    ],
    explanation: ['Range = maximum $-$ minimum $= 14 - 2 = 12$.'],
    tags: ['MAP-practice', 'range', 'box-plot'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 90, unit: 9, order: 10, slug: 'hist-vs-bar',
    standard: '6.SP.B.4', difficulty: 3,
    prompt: 'Which display has bars drawn over **numerical intervals** with no gaps: a bar graph or a histogram?',
    answerType: 'short-text', primaryAnswer: 'histogram',
    alternativeAnswers: ['Histogram', 'a histogram'], acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Bar graphs use categories; the other uses ranges.' },
      { level: 'guide', text: 'Equal-width intervals, no gaps.' },
      { level: 'reveal', text: 'Histogram.' },
    ],
    explanation: ['Bar graphs compare separate categories (and bars have gaps).', 'Histograms group numerical data into intervals (bars touch).'],
    tags: ['MAP-practice', 'histogram', 'bar-graph'], estimatedSeconds: 50,
  },

  // ============================================================
  // UNIT 10 — Data challenge mix (6.SP.B.5 + mix)
  // ============================================================
  {
    domain: '6.SP', num: 91, unit: 10, order: 1, slug: 'mean-10-50',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mean of $\\{10, 20, 30, 40, 50\\}$.',
    answerType: 'numeric', primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sum and divide by $5$.' },
      { level: 'guide', text: 'Sum $= 150$.' },
      { level: 'reveal', text: '$150 / 5 = 30$.' },
    ],
    explanation: ['Sum: $150$.', 'Mean: $150 / 5 = 30$.'],
    alternativeExplanations: [
      { title: 'Symmetry shortcut', steps: ['Values evenly spaced around $30$.', 'Mean equals the middle: $30$.'] },
    ],
    tags: ['mean'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 92, unit: 10, order: 2, slug: 'median-3-7-1-9-5',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the median of $\\{3, 7, 1, 9, 5\\}$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sort first.' },
      { level: 'guide', text: 'Sorted: $1, 3, 5, 7, 9$.' },
      { level: 'reveal', text: 'Middle = $5$.' },
    ],
    explanation: ['Sort: $1, 3, 5, 7, 9$. Middle value: $5$.'],
    tags: ['median'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 93, unit: 10, order: 3, slug: 'mode-2-3-3-4-5-3',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mode of $\\{2, 3, 3, 4, 5, 3\\}$.',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Most common value.' },
      { level: 'guide', text: '$3$ appears three times.' },
      { level: 'reveal', text: '$3$.' },
    ],
    explanation: ['$3$ appears three times — more than any other value.', 'Mode = $3$.'],
    tags: ['mode'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 94, unit: 10, order: 4, slug: 'range-7-10-4-15',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the range of $\\{7, 10, 4, 15\\}$.',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Range $= \\text{max} - \\text{min}$.' },
      { level: 'guide', text: 'Max $= 15$, min $= 4$.' },
      { level: 'reveal', text: '$15 - 4 = 11$.' },
    ],
    explanation: ['Max $= 15$, min $= 4$.', 'Range $= 15 - 4 = 11$.'],
    tags: ['range'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 95, unit: 10, order: 5, slug: 'find-missing-mean',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'The mean of four numbers is $12$. Three of them are $10$, $14$, and $9$. What is the fourth?',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Total $=$ mean $\\times$ count.' },
      { level: 'guide', text: 'Sum $= 12 \\cdot 4 = 48$. Current sum: $10 + 14 + 9 = 33$.' },
      { level: 'reveal', text: 'Missing $= 48 - 33 = 15$.' },
    ],
    explanation: ['Need total: $12 \\cdot 4 = 48$.', 'Sum of three: $10 + 14 + 9 = 33$.', 'Missing: $48 - 33 = 15$.'],
    alternativeExplanations: [
      { title: 'Deviation method', steps: ['Each number\'s deviation from $12$: $-2, +2, -3$. Net: $-3$.', 'Fourth must be $+3$ to balance: $12 + 3 = 15$.'] },
    ],
    tags: ['MAP-practice', 'mean', 'inverse'], estimatedSeconds: 110,
  },
  {
    domain: '6.SP', num: 96, unit: 10, order: 6, slug: 'new-mean-add-12',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'The mean of $\\{2, 4, 6\\}$ is $4$. If you add the value $12$ to the data, what is the new mean?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the new sum, then divide by the new count.' },
      { level: 'guide', text: 'Old sum $= 12$. New sum $= 24$. New count $= 4$.' },
      { level: 'reveal', text: '$24 / 4 = 6$.' },
    ],
    explanation: ['Old sum: $2+4+6 = 12$.', 'Add $12$: new sum $= 24$.', 'New count: $4$. New mean: $24 / 4 = 6$.'],
    tags: ['MAP-practice', 'mean', 'effect'], estimatedSeconds: 80,
  },
  {
    domain: '6.SP', num: 97, unit: 10, order: 7, slug: 'mean-vs-median-skew',
    standard: '6.SP.B.5.d', difficulty: 3,
    prompt: 'A teacher reports a mean of $70$ but a median of $85$. This suggests there are likely some ___?',
    answerType: 'multiple-choice', primaryAnswer: 'A',
    choices: [
      { id: 'A', label: 'low outliers (a few very small values)', correct: true },
      { id: 'B', label: 'high outliers (a few very large values)', correct: false },
      { id: 'C', label: 'no outliers — perfectly normal data', correct: false },
    ],
    acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Which type of outlier pulls the mean DOWN, away from the median?' },
      { level: 'guide', text: 'Low values pull the mean below the median.' },
      { level: 'reveal', text: 'A.' },
    ],
    explanation: ['Outliers pull the mean toward them but barely move the median.', 'Mean ($70$) is less than median ($85$) → some low outliers pulled it down.'],
    tags: ['MAP-practice', 'mean-vs-median', 'outliers'], estimatedSeconds: 110,
  },
  {
    domain: '6.SP', num: 98, unit: 10, order: 8, slug: 'total-from-mean-85',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'A class of $20$ students has a mean test score of $85$. What is the **total** of all the scores?',
    answerType: 'numeric', primaryAnswer: '1700', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Total $=$ mean $\\times$ count.' },
      { level: 'guide', text: '$20 \\cdot 85$.' },
      { level: 'reveal', text: '$1700$.' },
    ],
    explanation: ['Sum $=$ mean $\\times$ count $= 85 \\cdot 20 = 1700$.'],
    tags: ['MAP-practice', 'mean', 'inverse'], estimatedSeconds: 60,
  },
  {
    domain: '6.SP', num: 99, unit: 10, order: 9, slug: 'median-even-count',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Find the median of $\\{12, 14, 18, 20, 25, 26\\}$.',
    answerType: 'numeric', primaryAnswer: '19', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Six values: average the middle two.' },
      { level: 'guide', text: 'Middle two: $18$ and $20$. Average: $(18+20)/2$.' },
      { level: 'reveal', text: '$19$.' },
    ],
    explanation: ['Six values (already sorted).', 'Middle two: $18, 20$. Median: $(18+20)/2 = 19$.'],
    tags: ['MAP-practice', 'median', 'even-count'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 100, unit: 10, order: 10, slug: 'shift-mean',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'The mean of $\\{6, 8, 10, 12\\}$ is $9$. If you add $4$ to **each** value, what is the new mean?',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Adding the same number to every value shifts the mean by that number.' },
      { level: 'guide', text: 'New mean $= 9 + 4$.' },
      { level: 'reveal', text: '$13$.' },
    ],
    explanation: ['Adding a constant to every value shifts the mean by the same constant.', 'New mean: $9 + 4 = 13$.'],
    alternativeExplanations: [
      { title: 'Recompute', steps: ['New data: $\\{10, 12, 14, 16\\}$, sum $= 52$.', '$52 / 4 = 13$.'] },
    ],
    tags: ['MAP-practice', 'mean', 'transformation'], estimatedSeconds: 100,
  },
];
