import type { SeedProblem } from './types';

// 6.SP — Statistics & Probability. Adds 52 new (5 to U1, 7 to U2, 10 each to U3-U6).

export const problems6SP: SeedProblem[] = [
  // ---------------- UNIT 1 — Center & spread basics (orders 6-10) ----------------
  {
    domain: '6.SP', num: 9, unit: 1, order: 6, slug: 'mean-basic',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the **mean** of $3, 7, 8, 6$.',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Mean = sum divided by count.' },
      { level: 'guide', text: 'Sum: $3 + 7 + 8 + 6 = 24$. Count: $4$.' },
      { level: 'reveal', text: '$24 \\div 4 = 6$.' },
    ],
    explanation: ['Sum: $24$. Count: $4$. Mean: $6$.'],
    tags: ['mean'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 10, unit: 1, order: 7, slug: 'median-odd',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the **median** of $2, 5, 9, 11, 7$.',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sort first.' },
      { level: 'guide', text: 'Sorted: $2, 5, 7, 9, 11$. Middle value?' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['Sorted: $2, 5, 7, 9, 11$.', 'Middle: $7$.'],
    tags: ['median'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 11, unit: 1, order: 8, slug: 'mode-basic',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the **mode** of $1, 4, 4, 7, 4, 2$.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Mode = most frequent.' },
      { level: 'guide', text: 'Count: $4$ appears $3$ times.' },
      { level: 'reveal', text: '$4$.' },
    ],
    explanation: ['$4$ appears most often.', 'Mode: $4$.'],
    tags: ['mode'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 12, unit: 1, order: 9, slug: 'range-basic',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the **range** of $12, 5, 18, 9, 14$.',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Range = max - min.' },
      { level: 'guide', text: 'Max: $18$. Min: $5$.' },
      { level: 'reveal', text: '$18 - 5 = 13$.' },
    ],
    explanation: ['Max: $18$, Min: $5$.', 'Range: $13$.'],
    tags: ['range'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 13, unit: 1, order: 10, slug: 'mean-include-zero',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mean of $0, 4, 6, 10$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Don\'t forget to count $0$.' },
      { level: 'guide', text: 'Sum: $0 + 4 + 6 + 10 = 20$. Count: $4$.' },
      { level: 'reveal', text: '$20 / 4 = 5$.' },
    ],
    explanation: ['Sum: $20$. Count: $4$. Mean: $5$.'],
    tags: ['mean'], estimatedSeconds: 45,
  },

  // ---------------- UNIT 2 — Stat questions & MAD (orders 4-10) ----------------
  {
    domain: '6.SP', num: 14, unit: 2, order: 4, slug: 'is-statistical',
    standard: '6.SP.A.1', difficulty: 1,
    prompt: 'Which is a **statistical** question?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'How old is my teacher?', correct: false },
      { id: 'B', label: 'How tall are students in our class?', correct: true },
      { id: 'C', label: 'What time is it now?', correct: false },
      { id: 'D', label: 'How many days in a week?', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Statistical questions have varied answers.' },
      { level: 'guide', text: 'Which one expects different answers from different people?' },
      { level: 'reveal', text: 'B — students\' heights vary.' },
    ],
    explanation: ['Statistical questions anticipate variability.', 'Heights of students vary across the class.'],
    tags: ['statistical-question'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 15, unit: 2, order: 5, slug: 'mean-vs-median',
    standard: '6.SP.A.3', difficulty: 2,
    prompt: 'A dataset is: $4, 5, 6, 7, 100$. Which is **larger**, mean or median?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Mean', correct: true },
      { id: 'B', label: 'Median', correct: false },
      { id: 'C', label: 'They are equal', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The $100$ is an outlier — it pulls the mean up.' },
      { level: 'guide', text: 'Mean: $122/5 = 24.4$. Median: $6$.' },
      { level: 'reveal', text: 'Mean ($24.4$) > median ($6$).' },
    ],
    explanation: ['Mean: $(4 + 5 + 6 + 7 + 100)/5 = 24.4$.', 'Median: $6$.', 'Mean is much larger because of the outlier.'],
    tags: ['MAP-practice', 'mean', 'median'], estimatedSeconds: 70,
  },
  {
    domain: '6.SP', num: 16, unit: 2, order: 6, slug: 'mean-decimal',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mean of $2.5, 3.5, 4$.',
    answerType: 'numeric',
    primaryAnswer: '3.33', alternativeAnswers: ['10/3', '3.333', '3.3'],
    acceptanceMode: 'numeric-tolerance', numericTolerance: 0.05,
    hints: [
      { level: 'nudge', text: 'Sum then divide by count.' },
      { level: 'guide', text: 'Sum: $10$. Count: $3$.' },
      { level: 'reveal', text: '$10 / 3 \\approx 3.33$.' },
    ],
    explanation: ['Sum: $2.5 + 3.5 + 4 = 10$.', '$10 / 3 \\approx 3.33$.'],
    tags: ['mean', 'decimal'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 17, unit: 2, order: 7, slug: 'median-bigger',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the median of $10, 4, 7, 12, 15, 9, 6$.',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sort the numbers.' },
      { level: 'guide', text: 'Sorted: $4, 6, 7, 9, 10, 12, 15$. Find the middle.' },
      { level: 'reveal', text: '$9$.' },
    ],
    explanation: ['Sorted: $4, 6, 7, 9, 10, 12, 15$.', '$7$ values, middle is the $4$th: $9$.'],
    tags: ['median'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 18, unit: 2, order: 8, slug: 'spread-larger-set',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Which set has greater **range**: $\\{5, 7, 9\\}$ or $\\{2, 5, 9, 14\\}$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$\\{5, 7, 9\\}$', correct: false },
      { id: 'B', label: '$\\{2, 5, 9, 14\\}$', correct: true },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Range = max - min for each.' },
      { level: 'guide', text: 'A: $9 - 5 = 4$. B: $14 - 2 = 12$.' },
      { level: 'reveal', text: 'B has range $12$.' },
    ],
    explanation: ['A range: $4$. B range: $12$.', 'B is greater.'],
    tags: ['range', 'compare'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 19, unit: 2, order: 9, slug: 'mean-bigger-set',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the mean of $11, 13, 14, 16, 18, 18$.',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sum / count.' },
      { level: 'guide', text: 'Sum: $11 + 13 + 14 + 16 + 18 + 18 = 90$. Count: $6$.' },
      { level: 'reveal', text: '$90 / 6 = 15$.' },
    ],
    explanation: ['Sum: $90$. Count: $6$. Mean: $15$.'],
    tags: ['mean'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 20, unit: 2, order: 10, slug: 'outlier-effect',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'A dataset $\\{8, 10, 12, 14\\}$ has mean $11$. Add an outlier of $50$. What is the new mean?',
    answerType: 'numeric', primaryAnswer: '18.8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sum increases by $50$, count increases by $1$.' },
      { level: 'guide', text: 'New sum: $44 + 50 = 94$. New count: $5$.' },
      { level: 'reveal', text: '$94 / 5 = 18.8$.' },
    ],
    explanation: ['Old sum: $44$. New sum: $94$.', 'New count: $5$.', 'New mean: $18.8$.'],
    tags: ['CA', 'mean', 'outlier'], estimatedSeconds: 80,
  },

  // ---------------- UNIT 3 — Variability (IQR, MAD intro) (1-10) ----------------
  {
    domain: '6.SP', num: 21, unit: 3, order: 1, slug: 'iqr-intro',
    standard: '6.SP.A.3', difficulty: 2,
    prompt: 'In the data $1, 3, 5, 7, 9, 11, 13$, what is the median?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'It\'s already sorted. Find the middle.' },
      { level: 'guide', text: '$7$ numbers, middle is $4$th.' },
      { level: 'reveal', text: '$7$.' },
    ],
    explanation: ['Middle of $7$ sorted: $7$.'],
    tags: ['median'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 22, unit: 3, order: 2, slug: 'q1-q3',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $1, 3, 5, 7, 9, 11, 13$: $Q1$ is the median of the lower half. What is $Q1$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Lower half: $1, 3, 5$.' },
      { level: 'guide', text: 'Median of $1, 3, 5$.' },
      { level: 'reveal', text: '$3$.' },
    ],
    explanation: ['Lower half: $1, 3, 5$.', 'Median: $3$.'],
    tags: ['CA', 'quartile'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 23, unit: 3, order: 3, slug: 'iqr-compute',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $1, 3, 5, 7, 9, 11, 13$: $Q1 = 3$, $Q3 = 11$. What is the IQR?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR = $Q3 - Q1$.' },
      { level: 'guide', text: '$11 - 3$.' },
      { level: 'reveal', text: '$8$.' },
    ],
    explanation: ['IQR $= 11 - 3 = 8$.'],
    tags: ['MAP-practice', 'IQR'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 24, unit: 3, order: 4, slug: 'mad-step',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $\\{2, 4, 6\\}$ (mean $4$), find the mean absolute deviation (MAD).',
    answerType: 'fraction',
    primaryAnswer: '4/3', alternativeAnswers: ['1.33', '1.333'],
    acceptanceMode: 'numeric-tolerance', numericTolerance: 0.05,
    hints: [
      { level: 'nudge', text: 'Find each distance from the mean, then average.' },
      { level: 'guide', text: 'Distances: $|2-4| = 2, |4-4| = 0, |6-4| = 2$.' },
      { level: 'reveal', text: 'Sum: $4$. Average: $4/3 \\approx 1.33$.' },
    ],
    explanation: ['Distances from $4$: $2, 0, 2$.', 'Mean: $4 / 3 \\approx 1.33$.'],
    tags: ['MAD'], estimatedSeconds: 80,
  },
  {
    domain: '6.SP', num: 25, unit: 3, order: 5, slug: 'range-spread',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the range of $8, 12, 7, 15, 9$.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Max minus min.' },
      { level: 'guide', text: 'Max: $15$, Min: $7$.' },
      { level: 'reveal', text: '$15 - 7 = 8$.' },
    ],
    explanation: ['$15 - 7 = 8$.'],
    tags: ['range'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 26, unit: 3, order: 6, slug: 'spread-compare',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Set $A$: $5, 6, 7$. Set $B$: $1, 6, 11$. Which has greater spread?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'A', correct: false },
      { id: 'B', label: 'B', correct: true },
      { id: 'C', label: 'Same', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Spread = how far apart the values are.' },
      { level: 'guide', text: 'A range: $2$. B range: $10$.' },
      { level: 'reveal', text: 'B.' },
    ],
    explanation: ['A: range $2$. B: range $10$.', 'B has greater spread.'],
    tags: ['spread'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 27, unit: 3, order: 7, slug: 'find-q3',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $2, 4, 6, 8, 10, 12, 14, 16, 18$: median is $10$. What is $Q3$?',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Upper half: $12, 14, 16, 18$.' },
      { level: 'guide', text: 'Median of $12, 14, 16, 18$: average of $14$ and $16$.' },
      { level: 'reveal', text: '$(14 + 16)/2 = 15$.' },
    ],
    explanation: ['Upper half (above median): $12, 14, 16, 18$.', 'Median of upper: $15$.'],
    tags: ['quartile'], estimatedSeconds: 60,
  },
  {
    domain: '6.SP', num: 28, unit: 3, order: 8, slug: 'mad-vocab',
    standard: '6.SP.A.3', difficulty: 1,
    prompt: 'MAD measures the **average distance** of values from what?',
    answerType: 'short-text',
    primaryAnswer: 'mean', alternativeAnswers: ['the mean', 'average'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'MAD = Mean Absolute Deviation — from what center?' },
      { level: 'guide', text: 'It uses the mean as center.' },
      { level: 'reveal', text: 'The mean.' },
    ],
    explanation: ['MAD is the mean of $|x - \\bar{x}|$ for each value.'],
    tags: ['MAD', 'vocabulary'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 29, unit: 3, order: 9, slug: 'small-range',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the range of $5, 5, 5, 5$.',
    answerType: 'numeric', primaryAnswer: '0', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Max minus min.' },
      { level: 'guide', text: 'Max and min are both $5$.' },
      { level: 'reveal', text: '$5 - 5 = 0$.' },
    ],
    explanation: ['All values equal $5$. Range: $0$.'],
    tags: ['range'], estimatedSeconds: 25,
  },
  {
    domain: '6.SP', num: 30, unit: 3, order: 10, slug: 'iqr-bigger',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'For $1, 2, 4, 5, 7, 8, 10, 11$: $Q1 = 2.5$, $Q3 = 9$. Find IQR.',
    answerType: 'numeric', primaryAnswer: '6.5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR = $Q3 - Q1$.' },
      { level: 'guide', text: '$9 - 2.5$.' },
      { level: 'reveal', text: '$6.5$.' },
    ],
    explanation: ['$Q3 - Q1 = 6.5$.'],
    tags: ['CA', 'IQR'], estimatedSeconds: 50,
  },

  // ---------------- UNIT 4 — Data displays (1-10) ----------------
  {
    domain: '6.SP', num: 31, unit: 4, order: 1, slug: 'dot-plot-mode',
    standard: '6.SP.B.4', difficulty: 1,
    prompt: 'A dot plot shows: value $2$ has $3$ dots, $4$ has $5$ dots, $6$ has $2$ dots. What is the mode?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Mode = most dots.' },
      { level: 'guide', text: 'Most dots is at $4$.' },
      { level: 'reveal', text: '$4$.' },
    ],
    explanation: ['Value $4$ has $5$ dots — the most.', 'Mode: $4$.'],
    tags: ['dot-plot'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 32, unit: 4, order: 2, slug: 'histogram-bin',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A histogram groups data into bins. If bin $0-9$ has $4$ values and bin $10-19$ has $7$ values, which bin has more?',
    answerType: 'short-text',
    primaryAnswer: '10-19', alternativeAnswers: ['10–19', '10 to 19'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Higher bar = more values.' },
      { level: 'guide', text: '$7 > 4$.' },
      { level: 'reveal', text: '$10$–$19$.' },
    ],
    explanation: ['$10$–$19$ has $7$ vs. $4$ in $0$–$9$.', 'More values in $10$–$19$.'],
    tags: ['histogram'], estimatedSeconds: 45,
  },
  {
    domain: '6.SP', num: 33, unit: 4, order: 3, slug: 'box-plot-median',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'In a box plot, the line inside the box represents what?',
    answerType: 'short-text',
    primaryAnswer: 'median', alternativeAnswers: ['the median'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A box plot shows 5 numbers: min, Q1, ?, Q3, max.' },
      { level: 'guide', text: 'Center of the box is the median.' },
      { level: 'reveal', text: 'Median.' },
    ],
    explanation: ['The vertical line in a box plot marks the median.'],
    tags: ['box-plot'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 34, unit: 4, order: 4, slug: 'dot-plot-mean',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A dot plot shows: $2, 3, 3, 4, 5$. Find the mean.',
    answerType: 'numeric', primaryAnswer: '3.4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add all dot-values and divide by count.' },
      { level: 'guide', text: 'Sum: $2 + 3 + 3 + 4 + 5 = 17$. Count: $5$.' },
      { level: 'reveal', text: '$17 / 5 = 3.4$.' },
    ],
    explanation: ['Sum: $17$. Count: $5$. Mean: $3.4$.'],
    tags: ['dot-plot', 'mean'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 35, unit: 4, order: 5, slug: 'histogram-bins-count',
    standard: '6.SP.B.4', difficulty: 1,
    prompt: 'A histogram has bins for $0-4, 5-9, 10-14, 15-19, 20-24$. How many bins?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Just count them.' },
      { level: 'guide', text: 'List them out.' },
      { level: 'reveal', text: '$5$.' },
    ],
    explanation: ['Bins: $5$.'],
    tags: ['histogram'], estimatedSeconds: 25,
  },
  {
    domain: '6.SP', num: 36, unit: 4, order: 6, slug: 'box-plot-range',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A box plot shows min $= 5$ and max $= 25$. What is the range?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Max - min.' },
      { level: 'guide', text: '$25 - 5$.' },
      { level: 'reveal', text: '$20$.' },
    ],
    explanation: ['Range: $25 - 5 = 20$.'],
    tags: ['box-plot', 'range'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 37, unit: 4, order: 7, slug: 'choose-display',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'Which display is best for showing the **shape** of a distribution with many values?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Dot plot', correct: false },
      { id: 'B', label: 'Histogram', correct: true },
      { id: 'C', label: 'Box plot', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Dot plots get cluttered with many values.' },
      { level: 'guide', text: 'Histograms bin values to show shape.' },
      { level: 'reveal', text: 'Histogram.' },
    ],
    explanation: ['Histograms group values into bins and show the shape clearly.'],
    tags: ['CA', 'display'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 38, unit: 4, order: 8, slug: 'dot-plot-count',
    standard: '6.SP.B.4', difficulty: 1,
    prompt: 'A dot plot has $3, 4, 5$ dots at three values. How many data points total?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add the dots.' },
      { level: 'guide', text: '$3 + 4 + 5$.' },
      { level: 'reveal', text: '$12$.' },
    ],
    explanation: ['$3 + 4 + 5 = 12$.'],
    tags: ['dot-plot'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 39, unit: 4, order: 9, slug: 'histogram-shape',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'A histogram has a tail on the **right** (bigger bin heights on the left). The distribution is:',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Symmetric', correct: false },
      { id: 'B', label: 'Skewed right', correct: true },
      { id: 'C', label: 'Skewed left', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The skew direction follows the tail.' },
      { level: 'guide', text: 'Tail on right = skewed right.' },
      { level: 'reveal', text: 'Skewed right.' },
    ],
    explanation: ['Tail extends to the right → skewed right.'],
    tags: ['MAP-practice', 'histogram', 'shape'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 40, unit: 4, order: 10, slug: 'box-plot-q1',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'A box plot has $Q1 = 12$ and $Q3 = 20$. What is the IQR?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR = $Q3 - Q1$.' },
      { level: 'guide', text: '$20 - 12$.' },
      { level: 'reveal', text: '$8$.' },
    ],
    explanation: ['IQR: $20 - 12 = 8$.'],
    tags: ['box-plot', 'IQR'], estimatedSeconds: 35,
  },

  // ---------------- UNIT 5 — Describing distributions (1-10) ----------------
  {
    domain: '6.SP', num: 41, unit: 5, order: 1, slug: 'shape-symmetric',
    standard: '6.SP.B.5.d', difficulty: 1,
    prompt: 'In a **symmetric** distribution, the mean and median are typically:',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Equal', correct: true },
      { id: 'B', label: 'Mean much greater', correct: false },
      { id: 'C', label: 'Median much greater', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Symmetric means evenly balanced.' },
      { level: 'guide', text: 'No outliers pulling either way.' },
      { level: 'reveal', text: 'Equal.' },
    ],
    explanation: ['In symmetric distributions, mean ≈ median.'],
    tags: ['shape'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 42, unit: 5, order: 2, slug: 'outlier-effect-2',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'Outliers usually affect which measure more: mean or median?',
    answerType: 'short-text',
    primaryAnswer: 'mean', alternativeAnswers: ['the mean'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'One big number can shift the average a lot.' },
      { level: 'guide', text: 'Median uses position; mean uses value.' },
      { level: 'reveal', text: 'Mean.' },
    ],
    explanation: ['Mean uses every value, so outliers shift it.', 'Median is based on rank — outliers barely affect it.'],
    tags: ['outlier'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 43, unit: 5, order: 3, slug: 'cluster',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'In a histogram, a region where bins are very tall is called a:',
    answerType: 'short-text',
    primaryAnswer: 'cluster', alternativeAnswers: ['Cluster'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A clustering of values.' },
      { level: 'guide', text: 'Many values bunched together.' },
      { level: 'reveal', text: 'Cluster.' },
    ],
    explanation: ['Tall bins close together form a cluster.'],
    tags: ['shape', 'vocabulary'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 44, unit: 5, order: 4, slug: 'shape-skew-left',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'A distribution has a long tail on the **left**. The mean is typically:',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Less than median', correct: true },
      { id: 'B', label: 'Greater than median', correct: false },
      { id: 'C', label: 'Equal to median', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Skew direction = tail direction.' },
      { level: 'guide', text: 'Skewed left → tail of small values pulls mean down.' },
      { level: 'reveal', text: 'Mean < median.' },
    ],
    explanation: ['Long tail on left pulls the mean toward small values.', 'Mean < median.'],
    tags: ['MAP-practice', 'shape', 'skew'], estimatedSeconds: 60,
  },
  {
    domain: '6.SP', num: 45, unit: 5, order: 5, slug: 'gap',
    standard: '6.SP.B.5.d', difficulty: 1,
    prompt: 'In a dot plot, a region with no dots is called a:',
    answerType: 'short-text',
    primaryAnswer: 'gap', alternativeAnswers: ['Gap'],
    acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'An empty space.' },
      { level: 'guide', text: 'Same word as for a space between things.' },
      { level: 'reveal', text: 'Gap.' },
    ],
    explanation: ['Empty regions are called gaps.'],
    tags: ['vocabulary'], estimatedSeconds: 25,
  },
  {
    domain: '6.SP', num: 46, unit: 5, order: 6, slug: 'measure-of-center',
    standard: '6.SP.A.2', difficulty: 1,
    prompt: 'Which is NOT a measure of center?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Mean', correct: false },
      { id: 'B', label: 'Median', correct: false },
      { id: 'C', label: 'Range', correct: true },
      { id: 'D', label: 'Mode', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Range measures **spread**, not center.' },
      { level: 'guide', text: 'Mean, median, mode = center. Range = spread.' },
      { level: 'reveal', text: 'Range.' },
    ],
    explanation: ['Mean, median, mode describe center.', 'Range describes spread.'],
    tags: ['vocabulary'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 47, unit: 5, order: 7, slug: 'best-center-outliers',
    standard: '6.SP.B.5.d', difficulty: 3,
    prompt: 'A dataset has a big outlier. Which measure of center is most reliable?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Mean', correct: false },
      { id: 'B', label: 'Median', correct: true },
      { id: 'C', label: 'Mode', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Outliers shift the mean.' },
      { level: 'guide', text: 'Median is based on rank, so it\'s stable.' },
      { level: 'reveal', text: 'Median.' },
    ],
    explanation: ['Median is resistant to outliers.', 'Mean is pulled by extreme values.'],
    tags: ['CA', 'outlier', 'center'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 48, unit: 5, order: 8, slug: 'symmetric-mean',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'A symmetric dataset has mean $50$. The median is approximately:',
    answerType: 'numeric', primaryAnswer: '50', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Symmetric → mean ≈ median.' },
      { level: 'guide', text: 'Median ≈ mean.' },
      { level: 'reveal', text: '$50$.' },
    ],
    explanation: ['Symmetric: mean ≈ median.', 'Both ≈ $50$.'],
    tags: ['shape', 'mean', 'median'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 49, unit: 5, order: 9, slug: 'cluster-gap-mc',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'You see a dot plot with most dots near $20$ and a few dots near $50$. What describes the spread?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Cluster + gap', correct: true },
      { id: 'B', label: 'Symmetric', correct: false },
      { id: 'C', label: 'Uniform', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'A bunch of dots, then nothing, then a few more.' },
      { level: 'guide', text: 'Cluster around $20$ and gap before the dots at $50$.' },
      { level: 'reveal', text: 'Cluster + gap.' },
    ],
    explanation: ['Dots near $20$ are a cluster.', 'Empty area between $20$ and $50$ is a gap.'],
    tags: ['shape'], estimatedSeconds: 55,
  },
  {
    domain: '6.SP', num: 50, unit: 5, order: 10, slug: 'best-describe-shape',
    standard: '6.SP.B.5.d', difficulty: 3,
    prompt: 'When describing a data set, which features should you mention?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Center, spread, shape', correct: true },
      { id: 'B', label: 'Just the mean', correct: false },
      { id: 'C', label: 'Color and pattern', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Three big things to look at.' },
      { level: 'guide', text: 'Where it\'s centered, how spread out, what shape.' },
      { level: 'reveal', text: 'Center, spread, and shape.' },
    ],
    explanation: ['A complete description includes center (mean/median), spread (range/IQR), and shape (symmetric, skewed, clusters, gaps, outliers).'],
    tags: ['MAP-practice', 'describe'], estimatedSeconds: 55,
  },

  // ---------------- UNIT 6 — Mixed reasoning (1-10) ----------------
  {
    domain: '6.SP', num: 51, unit: 6, order: 1, slug: 'm-mean-4',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the mean of $10, 20, 30, 40$.',
    answerType: 'numeric', primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sum / count.' },
      { level: 'guide', text: 'Sum: $100$. Count: $4$.' },
      { level: 'reveal', text: '$100 / 4 = 25$.' },
    ],
    explanation: ['Sum: $100$. Mean: $25$.'],
    tags: ['mean'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 52, unit: 6, order: 2, slug: 'm-median-4',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'Find the median of $1, 3, 5, 7$.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Even number of values → average the middle two.' },
      { level: 'guide', text: 'Middle: $3$ and $5$. Average them.' },
      { level: 'reveal', text: '$(3 + 5)/2 = 4$.' },
    ],
    explanation: ['Middle two: $3, 5$. Mean: $4$.'],
    tags: ['median'], estimatedSeconds: 40,
  },
  {
    domain: '6.SP', num: 53, unit: 6, order: 3, slug: 'm-question-stat',
    standard: '6.SP.A.1', difficulty: 1,
    prompt: 'Is "How tall is the Empire State Building?" a statistical question?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Yes', correct: false },
      { id: 'B', label: 'No', correct: true },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'It has just one answer.' },
      { level: 'guide', text: 'Statistical questions anticipate variability.' },
      { level: 'reveal', text: 'No — one fixed answer.' },
    ],
    explanation: ['One fixed answer → not statistical.'],
    tags: ['statistical-question'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 54, unit: 6, order: 4, slug: 'm-mean-fix',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: '$5$ scores have mean $80$. If a $6$th score of $74$ is added, the new mean is approximately:',
    answerType: 'numeric', primaryAnswer: '79', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Old sum is $5 \\times 80 = 400$.' },
      { level: 'guide', text: 'New sum: $474$. New count: $6$.' },
      { level: 'reveal', text: '$474 / 6 = 79$.' },
    ],
    explanation: ['Old sum: $400$. Add $74$: $474$.', 'Divide by $6$: $79$.'],
    tags: ['CA', 'mean'], estimatedSeconds: 75,
  },
  {
    domain: '6.SP', num: 55, unit: 6, order: 5, slug: 'm-mode-multi',
    standard: '6.SP.B.5.c', difficulty: 2,
    prompt: 'In $\\{3, 3, 5, 7, 7, 9\\}$, how many modes?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count which values tie for most appearances.' },
      { level: 'guide', text: '$3$ appears twice; $7$ appears twice.' },
      { level: 'reveal', text: '$2$ modes.' },
    ],
    explanation: ['$3$ and $7$ both appear $2$ times.', '$2$ modes.'],
    tags: ['mode'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 56, unit: 6, order: 6, slug: 'm-iqr-quick',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Data: $5, 7, 9, 12, 15, 20, 25$ has $Q1 = 7$, $Q3 = 20$. Find IQR.',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'IQR $= Q3 - Q1$.' },
      { level: 'guide', text: '$20 - 7$.' },
      { level: 'reveal', text: '$13$.' },
    ],
    explanation: ['IQR $= 13$.'],
    tags: ['IQR'], estimatedSeconds: 35,
  },
  {
    domain: '6.SP', num: 57, unit: 6, order: 7, slug: 'm-display-pick',
    standard: '6.SP.B.4', difficulty: 2,
    prompt: 'You have $5$ test scores from $5$ students. Which display works well?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Dot plot', correct: true },
      { id: 'B', label: 'Histogram with $1$-point bins', correct: false },
      { id: 'C', label: 'Pie chart of grade letters', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'For small datasets, dots show every value.' },
      { level: 'guide', text: 'Histograms shine with many values.' },
      { level: 'reveal', text: 'Dot plot.' },
    ],
    explanation: ['Dot plots are great for small datasets — every value is visible.'],
    tags: ['display'], estimatedSeconds: 50,
  },
  {
    domain: '6.SP', num: 58, unit: 6, order: 8, slug: 'm-range-quick',
    standard: '6.SP.B.5.c', difficulty: 1,
    prompt: 'Find the range of $1, 8, 4, 12, 2$.',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Max - min.' },
      { level: 'guide', text: '$12 - 1$.' },
      { level: 'reveal', text: '$11$.' },
    ],
    explanation: ['$12 - 1 = 11$.'],
    tags: ['range'], estimatedSeconds: 30,
  },
  {
    domain: '6.SP', num: 59, unit: 6, order: 9, slug: 'm-pick-center',
    standard: '6.SP.B.5.d', difficulty: 2,
    prompt: 'A teacher\'s ages: $30, 31, 32, 33, 65$. Which is a better summary of "typical age"?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Mean', correct: false },
      { id: 'B', label: 'Median', correct: true },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: '$65$ is an outlier.' },
      { level: 'guide', text: 'Median is resistant to outliers.' },
      { level: 'reveal', text: 'Median.' },
    ],
    explanation: ['Mean: $38.2$ (pulled up by $65$).', 'Median: $32$ (resistant to outlier).', 'Median better describes typical age.'],
    tags: ['MAP-practice', 'outlier', 'center'], estimatedSeconds: 70,
  },
  {
    domain: '6.SP', num: 60, unit: 6, order: 10, slug: 'm-mean-find-missing',
    standard: '6.SP.B.5.c', difficulty: 3,
    prompt: 'Four numbers have mean $10$. Three of them are $8, 11, 9$. What is the fourth?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Total sum is $40$ ($4 \\times 10$).' },
      { level: 'guide', text: 'Three sum to $8 + 11 + 9 = 28$.' },
      { level: 'reveal', text: '$40 - 28 = 12$.' },
    ],
    explanation: ['Sum needed: $40$. Have: $28$.', 'Missing: $12$.'],
    tags: ['CA', 'mean'], estimatedSeconds: 80,
  },
];
