import type { SeedProblem } from './types';

// A1 — Algebra 1, Units 5-8: Functions, Slope, Graphing y = mx + b, Writing
// line equations. 10 problems per unit, nums 41-80.

export const problemsA1u05: SeedProblem[] = [
  // ---------------- UNIT 5 — Functions (A1.FUN.A.1) ----------------
  {
    domain: 'A1', num: 41, unit: 5, order: 1, slug: 'fn-machine-double',
    standard: 'A1.FUN.A.1', difficulty: 1,
    prompt: 'A function machine DOUBLES every input. You feed it a $7$. What number comes out?',
    answerType: 'numeric', primaryAnswer: '14', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A function is a machine: one input goes in, one output comes out.' },
      { level: 'guide', text: 'The machine\'s rule is "double" — multiply the input by $2$.' },
      { level: 'reveal', text: '$7 \\times 2 = 14$.' },
    ],
    explanation: ['The machine\'s rule: multiply the input by $2$.', 'Input $7$: $7 \\times 2 = 14$.', 'One input in, exactly ONE output out — that is what makes it a function.'],
    alternativeExplanations: [
      { title: 'As a table', steps: ['Build an input-output table: $1 \\to 2$, $2 \\to 4$, $3 \\to 6$.', 'Every output is twice its input, so $7 \\to 14$.'] },
    ],
    tags: ['functions', 'function-machine'], estimatedSeconds: 25,
  },
  {
    domain: 'A1', num: 42, unit: 5, order: 2, slug: 'fn-quiz-points',
    standard: 'A1.FUN.A.1', difficulty: 1,
    prompt: 'On a quiz, each question is worth $4$ points, so your score is $f(q) = 4q$. What is $f(3)$? Give just the number.',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$f(3)$ means "feed the machine a $3$" — replace $q$ with $3$.' },
      { level: 'guide', text: '$f(3) = 4 \\times 3$.' },
      { level: 'reveal', text: '$4 \\times 3 = 12$ points.' },
    ],
    explanation: ['$f(q) = 4q$ is a machine named $f$: input questions, output points.', '$f(3)$ means put $3$ into the machine: $4 \\times 3 = 12$.', 'Three correct questions earn $12$ points.'],
    alternativeExplanations: [
      { title: 'Count it out', steps: ['Each question is worth $4$ points.', 'Three questions: $4 + 4 + 4 = 12$ points.'] },
    ],
    tags: ['functions', 'function-notation', 'word-problem'], estimatedSeconds: 30,
  },
  {
    domain: 'A1', num: 43, unit: 5, order: 3, slug: 'fn-table-output',
    standard: 'A1.FUN.A.1', difficulty: 1,
    prompt: 'A function\'s table shows: input $1 \\to$ output $5$, input $2 \\to$ output $10$, input $3 \\to$ output $15$. What is the output for input $2$?',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the row of the table where the input is $2$.' },
      { level: 'guide', text: 'The table pairs each input with exactly one output: $2 \\to ?$' },
      { level: 'reveal', text: 'Input $2$ pairs with output $10$.' },
    ],
    explanation: ['A table is a list of the machine\'s input-output pairs.', 'The pair with input $2$ is $2 \\to 10$.', 'The output is $10$.'],
    alternativeExplanations: [
      { title: 'Spot the rule', steps: ['Each output is $5$ times its input: $1 \\to 5$, $3 \\to 15$.', 'So input $2$ gives $2 \\times 5 = 10$.'] },
    ],
    tags: ['functions', 'tables'], estimatedSeconds: 25,
  },
  {
    domain: 'A1', num: 44, unit: 5, order: 4, slug: 'fn-eval-3x-plus-2',
    standard: 'A1.FUN.A.1', difficulty: 2,
    prompt: 'Let $f(x) = 3x + 2$. What is $f(4)$? Give just the number.',
    answerType: 'numeric', primaryAnswer: '14', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$f(4)$ means feed the machine a $4$: replace every $x$ with $4$.' },
      { level: 'guide', text: 'Compute $3 \\times 4$ first, then add $2$.' },
      { level: 'reveal', text: '$3 \\times 4 = 12$, then $12 + 2 = 14$.' },
    ],
    explanation: ['Replace $x$ with $4$: $f(4) = 3 \\times 4 + 2$.', 'Multiply first: $3 \\times 4 = 12$.', 'Add: $12 + 2 = 14$.'],
    alternativeExplanations: [
      { title: 'Two-step machine', steps: ['Picture the machine doing two moves: first "times 3", then "plus 2".', 'Input $4$: times $3$ gives $12$; plus $2$ gives $14$.'] },
    ],
    tags: ['functions', 'function-notation', 'evaluate'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 45, unit: 5, order: 5, slug: 'fn-eval-subtract',
    standard: 'A1.FUN.A.1', difficulty: 2,
    prompt: 'Let $g(x) = 10 - 2x$. What is $g(3)$? Give just the number.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$g$ is just another machine\'s name. Feed it a $3$: replace $x$ with $3$.' },
      { level: 'guide', text: 'Compute $2 \\times 3$ first, then subtract from $10$.' },
      { level: 'reveal', text: '$10 - 2 \\times 3 = 10 - 6 = 4$.' },
    ],
    explanation: ['Replace $x$ with $3$: $g(3) = 10 - 2 \\times 3$.', 'Multiply first: $2 \\times 3 = 6$.', 'Subtract: $10 - 6 = 4$.'],
    alternativeExplanations: [
      { title: 'Countdown machine', steps: ['The machine starts at $10$ and takes away $2$ for every $1$ of input.', 'Input $3$: take away $2$ three times — $10 \\to 8 \\to 6 \\to 4$.'] },
    ],
    tags: ['functions', 'function-notation', 'evaluate'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 46, unit: 5, order: 6, slug: 'fn-photo-filter',
    standard: 'A1.FUN.A.1', difficulty: 2,
    prompt: 'A photo filter on your phone is a function: it adds $15$ to a photo\'s brightness, $f(p) = p + 15$. A photo has brightness $40$. What brightness comes out?',
    answerType: 'numeric', primaryAnswer: '55', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The filter is a machine: one photo in, exactly one filtered photo out.' },
      { level: 'guide', text: 'Feed in $40$: $f(40) = 40 + 15$.' },
      { level: 'reveal', text: '$40 + 15 = 55$.' },
    ],
    explanation: ['The filter\'s rule: add $15$ to the brightness.', '$f(40) = 40 + 15 = 55$.', 'Every input photo gets exactly ONE output photo — that is why a filter is a function.'],
    alternativeExplanations: [
      { title: 'Table of photos', steps: ['Try a few inputs: brightness $10 \\to 25$, $20 \\to 35$, $30 \\to 45$.', 'Every output is $15$ more, so $40 \\to 55$.'] },
    ],
    tags: ['functions', 'word-problem', 'evaluate'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 47, unit: 5, order: 7, slug: 'fn-vending-domain',
    standard: 'A1.FUN.A.1', difficulty: 2,
    prompt: 'A vending machine only has buttons numbered $1$ through $8$ — those are its allowed inputs (its DOMAIN). What is the largest number in the domain?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Domain = the set of inputs the machine ACCEPTS.' },
      { level: 'guide', text: 'The buttons run from $1$ up to $8$. Which is the biggest allowed input?' },
      { level: 'reveal', text: 'The largest allowed input is $8$.' },
    ],
    explanation: ['The domain is the list of allowed inputs: the buttons $1, 2, 3, \\ldots, 8$.', 'Pressing $9$ does nothing — $9$ is not in the domain.', 'The largest number in the domain is $8$.'],
    alternativeExplanations: [
      { title: 'Domain vs range', steps: ['Inputs (buttons) form the domain; outputs (snacks) form the range.', 'The question asks about buttons only, and they stop at $8$.'] },
    ],
    tags: ['functions', 'domain', 'word-problem'], estimatedSeconds: 30,
  },
  {
    domain: 'A1', num: 48, unit: 5, order: 8, slug: 'fn-find-input',
    standard: 'A1.FUN.A.1', difficulty: 3,
    prompt: 'Let $f(x) = 5x$. If $f(x) = 35$, what input $x$ was fed into the machine?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'This time you know the OUTPUT ($35$) and need the input. Run the machine backward.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Easier machine: if $f(x) = 5x$ and the output is $10$, the input was $10 \\div 5 = 2$. Undo the machine by dividing.' },
      { level: 'guide', text: 'The machine multiplies by $5$, so undo it: divide $35$ by $5$.' },
      { level: 'reveal', text: '$35 \\div 5 = 7$.' },
    ],
    explanation: ['Set up the equation: $5x = 35$.', 'Undo "times $5$" with "divide by $5$": $x = 35 \\div 5$.', 'The input was $x = 7$.'],
    alternativeExplanations: [
      { title: 'Guess and check', steps: ['Try inputs: $f(6) = 30$ — too small. $f(8) = 40$ — too big.', '$f(7) = 35$ — exactly right, so the input was $7$.'] },
    ],
    tags: ['functions', 'solve-for-input'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 49, unit: 5, order: 9, slug: 'fn-quiz-range-max',
    standard: 'A1.FUN.A.1', difficulty: 3,
    prompt: 'Your quiz score is $f(q) = 4q$ points, and the quiz has at most $10$ questions ($q$ can be $0$ to $10$). What is the LARGEST output in the range?',
    answerType: 'numeric', primaryAnswer: '40', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Range = the set of possible OUTPUTS. The biggest output comes from the biggest input.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Check the ends: $q = 0$ gives $0$ points and $q = 10$ gives $40$ points. The range is everything the machine CAN output between those.' },
      { level: 'guide', text: 'The biggest allowed input is $q = 10$. Compute $f(10)$.' },
      { level: 'reveal', text: '$f(10) = 4 \\times 10 = 40$.' },
    ],
    explanation: ['The domain (allowed inputs) is $q = 0$ to $10$.', 'The rule multiplies by $4$, so bigger inputs give bigger outputs.', 'Largest output: $f(10) = 4 \\times 10 = 40$ points.'],
    alternativeExplanations: [
      { title: 'List the outputs', steps: ['The outputs are $0, 4, 8, 12, \\ldots$ climbing by $4$ each time.', 'They stop when the questions run out at $q = 10$: the last one is $40$.'] },
    ],
    tags: ['functions', 'range', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'A1', num: 50, unit: 5, order: 10, slug: 'fn-backward-two-step',
    standard: 'A1.FUN.A.1', difficulty: 3,
    prompt: 'Let $f(x) = 2x + 3$. The machine spits out $19$. What input went in?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The machine does "times $2$, then plus $3$". Undo the steps in REVERSE order.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Simpler: $2x + 3 = 9$ gives $2x = 6$, so $x = 3$. Undo in reverse — subtract the $3$, then divide by the $2$.' },
      { level: 'guide', text: 'First undo "plus $3$": $19 - 3 = 16$. Then undo "times $2$".' },
      { level: 'reveal', text: '$16 \\div 2 = 8$.' },
    ],
    explanation: ['Set up: $2x + 3 = 19$.', 'Undo "plus $3$": $2x = 19 - 3 = 16$.', 'Undo "times $2$": $x = 16 \\div 2 = 8$.'],
    alternativeExplanations: [
      { title: 'Check with the table', steps: ['Try $f(7) = 17$ and $f(9) = 21$ — the output $19$ sits between them.', '$f(8) = 2 \\times 8 + 3 = 19$. The input was $8$.'] },
    ],
    tags: ['functions', 'solve-for-input', 'two-step'], estimatedSeconds: 55,
  },

  // ---------------- UNIT 6 — Slope & rate of change (A1.LIN.A.1) ----------------
  {
    domain: 'A1', num: 51, unit: 6, order: 1, slug: 'slope-rise-run-basic',
    standard: 'A1.LIN.A.1', difficulty: 1,
    prompt: 'A staircase rises $6$ units while running $2$ units across. What is the slope (rise over run)?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Slope = rise $\\div$ run.' },
      { level: 'guide', text: 'Rise is $6$, run is $2$: compute $6 \\div 2$.' },
      { level: 'reveal', text: '$6 \\div 2 = 3$.' },
    ],
    explanation: ['Slope is rise over run: $\\frac{6}{2}$.', '$6 \\div 2 = 3$.', 'For every $1$ step across, the stairs climb $3$ up.'],
    alternativeExplanations: [
      { title: 'Shrink the staircase', steps: ['$6$ up over $2$ across is the same steepness as $3$ up over $1$ across.', 'The "up per one across" number IS the slope: $3$.'] },
    ],
    tags: ['slope', 'rise-over-run'], estimatedSeconds: 25,
  },
  {
    domain: 'A1', num: 52, unit: 6, order: 2, slug: 'slope-battery-drain',
    standard: 'A1.LIN.A.1', difficulty: 1,
    prompt: 'Your phone battery drops from $80\\%$ to $56\\%$ in $2$ hours. How many percent does it drop per hour?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find the TOTAL drop: $80 - 56$.' },
      { level: 'guide', text: 'It dropped $24\\%$ in $2$ hours. Divide by the hours.' },
      { level: 'reveal', text: '$24 \\div 2 = 12$ percent per hour.' },
    ],
    explanation: ['Total drop: $80 - 56 = 24$ percent.', 'Per hour: $24 \\div 2 = 12$.', 'The rate of change is $-12\\%$ per hour — battery is going DOWN.'],
    alternativeExplanations: [
      { title: 'As stairs going down', steps: ['Picture a staircase: every 1 hour across (run), the battery steps 12 down (rise = −12).', 'Slope = rise over run = −24 over 2 = −12 per hour.'] },
    ],
    tags: ['slope', 'rate-of-change', 'word-problem'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 53, unit: 6, order: 3, slug: 'slope-ramp',
    standard: 'A1.LIN.A.1', difficulty: 1,
    prompt: 'A wheelchair ramp rises $2$ ft over a run of $8$ ft. What is its slope? Write it as a fraction.',
    answerType: 'numeric', primaryAnswer: '1/4', alternativeAnswers: ['0.25', '2/8'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Slope = rise over run: put $2$ over $8$.' },
      { level: 'guide', text: '$\\frac{2}{8}$ can be simplified — divide top and bottom by $2$.' },
      { level: 'reveal', text: '$\\frac{2}{8} = \\frac{1}{4}$.' },
    ],
    explanation: ['Slope = rise over run = $\\frac{2}{8}$.', 'Simplify: $\\frac{2}{8} = \\frac{1}{4}$.', 'The ramp climbs $1$ ft for every $4$ ft across — a gentle slope.'],
    alternativeExplanations: [
      { title: 'One foot at a time', steps: ['The ramp gains $2$ ft of height spread over $8$ ft of floor.', 'Per single foot across: $2 \\div 8 = 0.25$ ft up — that decimal equals $\\frac{1}{4}$.'] },
    ],
    tags: ['slope', 'rise-over-run', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 54, unit: 6, order: 4, slug: 'slope-two-points',
    standard: 'A1.LIN.A.1', difficulty: 2,
    prompt: 'Find the slope of the line through $(1, 2)$ and $(3, 8)$.',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Slope $= \\frac{y_2 - y_1}{x_2 - x_1}$ — change in $y$ over change in $x$.' },
      { level: 'guide', text: 'Rise: $8 - 2 = 6$. Run: $3 - 1 = 2$.' },
      { level: 'reveal', text: '$6 \\div 2 = 3$.' },
    ],
    explanation: ['Rise: $y_2 - y_1 = 8 - 2 = 6$.', 'Run: $x_2 - x_1 = 3 - 1 = 2$.', 'Slope $= \\frac{6}{2} = 3$.'],
    alternativeExplanations: [
      { title: 'Walk the stairs', steps: ['Start at $(1, 2)$. To reach $(3, 8)$ you walk $2$ across and $6$ up.', 'Per single step across that is $3$ up — slope $3$.'] },
    ],
    tags: ['slope', 'two-points'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 55, unit: 6, order: 5, slug: 'slope-negative-points',
    standard: 'A1.LIN.A.1', difficulty: 2,
    prompt: 'Find the slope of the line through $(0, 10)$ and $(5, 0)$.',
    answerType: 'numeric', primaryAnswer: '-2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The line goes DOWN from left to right, so expect a negative slope.' },
      { level: 'guide', text: 'Rise: $0 - 10 = -10$. Run: $5 - 0 = 5$.' },
      { level: 'reveal', text: '$-10 \\div 5 = -2$.' },
    ],
    explanation: ['Rise: $0 - 10 = -10$ (the $y$-values FALL).', 'Run: $5 - 0 = 5$.', 'Slope $= \\frac{-10}{5} = -2$ — downhill.'],
    alternativeExplanations: [
      { title: 'Downhill stairs', steps: ['From $(0,10)$ to $(5,0)$ you drop $10$ while walking $5$ across.', 'Each step across drops you $2$: the slope is $-2$.'] },
    ],
    tags: ['slope', 'two-points', 'negative-slope'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 56, unit: 6, order: 6, slug: 'slope-dog-walking-pay',
    standard: 'A1.LIN.A.1', difficulty: 2,
    prompt: 'You walk dogs for pay. After $3$ walks you have earned $\\$18$; after $5$ walks, $\\$30$. What is your rate in dollars per walk?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Rate = change in money $\\div$ change in walks — that is a slope!' },
      { level: 'guide', text: 'Money changed $30 - 18 = 12$ dollars over $5 - 3 = 2$ walks.' },
      { level: 'reveal', text: '$12 \\div 2 = 6$ dollars per walk.' },
    ],
    explanation: ['Treat the data as points: $(3, 18)$ and $(5, 30)$.', 'Rise: $30 - 18 = 12$. Run: $5 - 3 = 2$.', 'Slope $= 12 \\div 2 = 6$ — you earn $\\$6$ per walk.'],
    alternativeExplanations: [
      { title: 'Check with one point', steps: ['If each walk pays $\\$6$, then $3$ walks pay $3 \\times 6 = \\$18$. Matches!', 'And $5$ walks pay $5 \\times 6 = \\$30$. The rate $\\$6$ per walk fits both.'] },
    ],
    tags: ['slope', 'rate-of-change', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'A1', num: 57, unit: 6, order: 7, slug: 'slope-fraction-points',
    standard: 'A1.LIN.A.1', difficulty: 2,
    prompt: 'Find the slope of the line through $(2, 1)$ and $(6, 4)$. Write it as a fraction.',
    answerType: 'numeric', primaryAnswer: '3/4', alternativeAnswers: ['0.75'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Slope $= \\frac{y_2 - y_1}{x_2 - x_1}$. Keep the answer as a fraction.' },
      { level: 'guide', text: 'Rise: $4 - 1 = 3$. Run: $6 - 2 = 4$.' },
      { level: 'reveal', text: 'Slope $= \\frac{3}{4}$.' },
    ],
    explanation: ['Rise: $4 - 1 = 3$.', 'Run: $6 - 2 = 4$.', 'Slope $= \\frac{3}{4}$ — up $3$ for every $4$ across. A slope does not have to be a whole number!'],
    alternativeExplanations: [
      { title: 'Gentle stairs', steps: ['From $(2,1)$ walk $4$ tiles across and climb only $3$ up to land on $(6,4)$.', 'Less than $1$ up per tile across: exactly $\\frac{3}{4}$ up each tile.'] },
    ],
    tags: ['slope', 'two-points', 'fractions'], estimatedSeconds: 50,
  },
  {
    domain: 'A1', num: 58, unit: 6, order: 8, slug: 'slope-zero-flat',
    standard: 'A1.LIN.A.1', difficulty: 3,
    prompt: 'Find the slope of the line through $(4, 7)$ and $(9, 7)$.',
    answerType: 'numeric', primaryAnswer: '0', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Compare the $y$-values of the two points. Do they change at all?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Plot two points with the SAME height, like $(1, 5)$ and $(6, 5)$. The line is flat, so it rises $0$ — and $0$ divided by anything is $0$.' },
      { level: 'guide', text: 'Rise: $7 - 7 = 0$. Run: $9 - 4 = 5$. Now divide.' },
      { level: 'reveal', text: '$0 \\div 5 = 0$. A flat line has slope $0$.' },
    ],
    explanation: ['Rise: $7 - 7 = 0$ — the height never changes.', 'Run: $9 - 4 = 5$.', 'Slope $= \\frac{0}{5} = 0$: a perfectly FLAT line, like a hallway floor.'],
    alternativeExplanations: [
      { title: 'Flat floor, not no floor', steps: ['Both points sit at height $7$, so walking between them is walking on flat ground.', 'Flat means zero steepness — slope $0$ (not "no slope").'] },
    ],
    tags: ['slope', 'zero-slope'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 59, unit: 6, order: 9, slug: 'slope-battery-table',
    standard: 'A1.LIN.A.1', difficulty: 3,
    prompt: 'A battery log on your phone reads: hour $1 \\to 88\\%$, hour $3 \\to 64\\%$. What is the rate of change in percent per hour? (Include the sign.)',
    answerType: 'numeric', primaryAnswer: '-12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The battery is DRAINING, so the rate should come out negative.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Simpler log: $80\\%$ at hour $1$ and $70\\%$ at hour $2$ drops $10$ over $1$ hour = $-10$ per hour. Find the drop, then divide by the hours.' },
      { level: 'guide', text: 'Change in percent: $64 - 88 = -24$. Change in hours: $3 - 1 = 2$.' },
      { level: 'reveal', text: '$-24 \\div 2 = -12$ percent per hour.' },
    ],
    explanation: ['Points: $(1, 88)$ and $(3, 64)$.', 'Rise: $64 - 88 = -24$. Run: $3 - 1 = 2$.', 'Slope $= \\frac{-24}{2} = -12$: the battery loses $12\\%$ each hour.'],
    alternativeExplanations: [
      { title: 'Fill the missing hour', steps: ['From hour $1$ to hour $3$ the battery fell $24\\%$ over $2$ hours — split it evenly.', 'Hour $2$ must read $76\\%$: each hour drops $12$, so the rate is $-12$.'] },
    ],
    tags: ['slope', 'rate-of-change', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: 'A1', num: 60, unit: 6, order: 10, slug: 'slope-negative-fraction',
    standard: 'A1.LIN.A.1', difficulty: 3,
    prompt: 'Find the slope of the line through $(1, 5)$ and $(5, 2)$. Write it as a fraction.',
    answerType: 'numeric', primaryAnswer: '-3/4', alternativeAnswers: ['-0.75'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $y$-values drop from $5$ to $2$, so the slope is negative.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up with $(1, 5)$ and $(3, 1)$: rise $= 1 - 5 = -4$, run $= 3 - 1 = 2$, slope $= -2$. Same subtraction order every time.' },
      { level: 'guide', text: 'Rise: $2 - 5 = -3$. Run: $5 - 1 = 4$.' },
      { level: 'reveal', text: 'Slope $= \\frac{-3}{4}$.' },
    ],
    explanation: ['Rise: $2 - 5 = -3$.', 'Run: $5 - 1 = 4$.', 'Slope $= -\\frac{3}{4}$ — a gentle downhill: down $3$ for every $4$ across.'],
    alternativeExplanations: [
      { title: 'Subtract the other way', steps: ['Swap the order of BOTH subtractions: rise $5 - 2 = 3$, run $1 - 5 = -4$.', '$\\frac{3}{-4}$ is still $-\\frac{3}{4}$ — same slope, as long as both are swapped together.'] },
    ],
    tags: ['slope', 'two-points', 'negative-slope', 'fractions'], estimatedSeconds: 55,
  },

  // ---------------- UNIT 7 — Graphing lines: y = mx + b (A1.LIN.A.2) ----------------
  {
    domain: 'A1', num: 61, unit: 7, order: 1, slug: 'read-slope-from-eq',
    standard: 'A1.LIN.A.2', difficulty: 1,
    prompt: 'In the equation $y = 5x + 2$, what is the slope?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'In $y = mx + b$, the slope $m$ is the number MULTIPLYING $x$.' },
      { level: 'guide', text: 'What number sits right in front of $x$ in $5x + 2$?' },
      { level: 'reveal', text: 'The slope is $5$.' },
    ],
    explanation: ['Match $y = 5x + 2$ to $y = mx + b$.', 'The number multiplying $x$ is $m = 5$ — how you MOVE.', 'The $+2$ is $b$, where you START — not the slope.'],
    alternativeExplanations: [
      { title: 'Test two inputs', steps: ['At $x = 0$, $y = 2$; at $x = 1$, $y = 7$.', 'One step across made $y$ jump by $5$ — that jump is the slope.'] },
    ],
    tags: ['slope-intercept', 'read-equation'], estimatedSeconds: 25,
  },
  {
    domain: 'A1', num: 62, unit: 7, order: 2, slug: 'read-intercept-from-eq',
    standard: 'A1.LIN.A.2', difficulty: 1,
    prompt: 'In the equation $y = 3x - 4$, what is the $y$-intercept?',
    answerType: 'numeric', primaryAnswer: '-4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'In $y = mx + b$, the $y$-intercept $b$ is the number ADDED at the end — where the line STARTS on the $y$-axis.' },
      { level: 'guide', text: '$3x - 4$ is the same as $3x + (-4)$.' },
      { level: 'reveal', text: 'The $y$-intercept is $-4$.' },
    ],
    explanation: ['Match $y = 3x - 4$ to $y = mx + b$: here $b = -4$.', 'The minus sign belongs to the $4$ — the start is BELOW zero.', 'The line crosses the $y$-axis at $(0, -4)$.'],
    alternativeExplanations: [
      { title: 'Plug in x = 0', steps: ['The $y$-intercept is the $y$-value when $x = 0$.', '$y = 3 \\times 0 - 4 = -4$.'] },
    ],
    tags: ['slope-intercept', 'y-intercept', 'read-equation'], estimatedSeconds: 30,
  },
  {
    domain: 'A1', num: 63, unit: 7, order: 3, slug: 'scooter-unlock-fee',
    standard: 'A1.LIN.A.2', difficulty: 1,
    prompt: 'A scooter app charges $y = 2 + 0.15m$ dollars for a ride of $m$ minutes. How many dollars do you pay before riding a single minute ($m = 0$)?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Before riding, $m = 0$. That makes this a "where do you START" question.' },
      { level: 'guide', text: 'Plug in $m = 0$: $y = 2 + 0.15 \\times 0$.' },
      { level: 'reveal', text: '$y = 2 + 0 = 2$ dollars — the unlock fee.' },
    ],
    explanation: ['At $m = 0$: $y = 2 + 0.15 \\times 0 = 2$.', 'The $2$ is the $y$-intercept $b$ — the START, the unlock fee you pay no matter what.', 'The $0.15$ is the slope — how the cost MOVES per minute.'],
    alternativeExplanations: [
      { title: 'Start-then-move', steps: ['Every $y = mx + b$ story splits into a start and a move.', 'Here the start is $\\$2$ (unlock) and the move is $\\$0.15$ each minute; at zero minutes only the start is charged.'] },
    ],
    tags: ['slope-intercept', 'y-intercept', 'word-problem'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 64, unit: 7, order: 4, slug: 'plant-growth-week-5',
    standard: 'A1.LIN.A.2', difficulty: 2,
    prompt: 'A plant is $4$ cm tall and grows $3$ cm each week: $h = 4 + 3w$. How tall is it after $5$ weeks?',
    answerType: 'numeric', primaryAnswer: '19', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Start at $4$ (that is $b$), then MOVE up $3$ for each of the $5$ weeks.' },
      { level: 'guide', text: 'Growth: $3 \\times 5 = 15$. Add the starting height.' },
      { level: 'reveal', text: '$4 + 15 = 19$ cm.' },
    ],
    explanation: ['Plug in $w = 5$: $h = 4 + 3 \\times 5$.', 'Multiply first: $3 \\times 5 = 15$.', 'Add the start: $4 + 15 = 19$ cm tall.'],
    alternativeExplanations: [
      { title: 'Week by week', steps: ['Start $4$, then climb $3$ each week: $7, 10, 13, 16, 19$.', 'After week $5$ the plant is $19$ cm — same as $4 + 3 \\times 5$.'] },
    ],
    tags: ['slope-intercept', 'evaluate', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 65, unit: 7, order: 5, slug: 'point-on-line',
    standard: 'A1.LIN.A.2', difficulty: 2,
    prompt: 'A line has equation $y = 2x + 1$. What is $y$ when $x = 4$?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Replace $x$ with $4$ in the equation.' },
      { level: 'guide', text: '$y = 2 \\times 4 + 1$. Multiply first.' },
      { level: 'reveal', text: '$8 + 1 = 9$.' },
    ],
    explanation: ['Substitute: $y = 2 \\times 4 + 1$.', '$2 \\times 4 = 8$, then $8 + 1 = 9$.', 'So the point $(4, 9)$ sits on the line.'],
    alternativeExplanations: [
      { title: 'Start, then climb', steps: ['Start at $b = 1$ on the $y$-axis.', 'Slope $2$ means climb $2$ per step across; four steps climb $8$: $1 + 8 = 9$.'] },
    ],
    tags: ['slope-intercept', 'evaluate'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 66, unit: 7, order: 6, slug: 'savings-week-6',
    standard: 'A1.LIN.A.2', difficulty: 2,
    prompt: 'Your savings follow $s = 15 + 5w$: you start with $\\$15$ and add $\\$5$ each week. How many dollars do you have after $6$ weeks?',
    answerType: 'numeric', primaryAnswer: '45', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'START at $15$, then MOVE up $5$ per week for $6$ weeks.' },
      { level: 'guide', text: 'Added money: $5 \\times 6 = 30$. Now add the start.' },
      { level: 'reveal', text: '$15 + 30 = 45$ dollars.' },
    ],
    explanation: ['Plug in $w = 6$: $s = 15 + 5 \\times 6$.', '$5 \\times 6 = 30$.', '$15 + 30 = 45$ — you have $\\$45$.'],
    alternativeExplanations: [
      { title: 'On the graph', steps: ['The savings line starts at $(0, 15)$ and rises $5$ for every $1$ week across.', 'Six steps of rise $5$ lift you $30$ above the start: $15 + 30 = 45$.'] },
    ],
    tags: ['slope-intercept', 'evaluate', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 67, unit: 7, order: 7, slug: 'horizontal-line-y3',
    standard: 'A1.LIN.A.2', difficulty: 2,
    prompt: 'A line has equation $y = 3$. What is $y$ on this line when $x = 100$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$y = 3$ has no $x$ in it at all. What does that tell you?' },
      { level: 'guide', text: 'Think of it as $y = 0x + 3$: slope $0$, start $3$.' },
      { level: 'reveal', text: '$y$ is ALWAYS $3$, even at $x = 100$.' },
    ],
    explanation: ['$y = 3$ means $y = 0x + 3$: the slope is $0$.', 'With zero slope the line never climbs or falls — it is horizontal.', 'At $x = 100$ (or any $x$), $y = 3$.'],
    alternativeExplanations: [
      { title: 'A flat hallway', steps: ['Start at height $3$ and move with slope $0$: every step across stays at height $3$.', 'Walk $100$ steps and you are still at height $3$.'] },
    ],
    tags: ['slope-intercept', 'horizontal-line'], estimatedSeconds: 30,
  },
  {
    domain: 'A1', num: 68, unit: 7, order: 8, slug: 'scooter-20-minutes',
    standard: 'A1.LIN.A.2', difficulty: 3,
    prompt: 'The scooter app charges $y = 2 + 0.15m$ dollars for $m$ minutes. How many dollars does a $20$-minute ride cost?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Plug in $m = 20$. Handle $0.15 \\times 20$ carefully.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try $10$ minutes first: $2 + 0.15(10) = 2 + 1.50 = \\$3.50$. Now do the same with $20$ minutes.' },
      { level: 'guide', text: '$0.15 \\times 20 = 3$. Now add the unlock fee.' },
      { level: 'reveal', text: '$2 + 3 = 5$ dollars.' },
    ],
    explanation: ['Substitute $m = 20$: $y = 2 + 0.15 \\times 20$.', '$0.15 \\times 20 = 3$ — fifteen cents, twenty times, is $\\$3$.', 'Total: $2 + 3 = \\$5$.'],
    alternativeExplanations: [
      { title: 'Money in pieces', steps: ['Ten minutes of riding costs $10 \\times \\$0.15 = \\$1.50$, so twenty minutes costs $\\$3$.', 'Add the $\\$2$ unlock fee at the start: $\\$5$ total.'] },
    ],
    tags: ['slope-intercept', 'evaluate', 'decimals', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: 'A1', num: 69, unit: 7, order: 9, slug: 'plot-b-then-move',
    standard: 'A1.LIN.A.2', difficulty: 3,
    prompt: 'To graph $y = 3x + 2$, you plot the start $(0, 2)$, then move right $1$. What $y$-value do you land on?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The slope $3$ means: for every $1$ right, go UP $3$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Start at the y-intercept $(0, 2)$. Moving right $1$ climbs by the slope $3$: $2 + 3 = 5$. The slope IS the step size.' },
      { level: 'guide', text: 'Start at height $2$, rise $3$: $2 + 3 = ?$' },
      { level: 'reveal', text: 'You land at $(1, 5)$, so $y = 5$.' },
    ],
    explanation: ['Graphing recipe: plot $b$, then use $m$ as rise over run.', 'Slope $3 = \\frac{3}{1}$: right $1$, up $3$.', 'From $(0, 2)$: right $1$, up $3$ lands on $(1, 5)$ — the $y$-value is $5$.'],
    alternativeExplanations: [
      { title: 'Just plug in', steps: ['Moving right $1$ from $x = 0$ puts you at $x = 1$.', '$y = 3 \\times 1 + 2 = 5$ — the graph move and the formula agree.'] },
    ],
    tags: ['slope-intercept', 'graphing', 'rise-over-run'], estimatedSeconds: 50,
  },
  {
    domain: 'A1', num: 70, unit: 7, order: 10, slug: 'x-intercept-4x-minus-8',
    standard: 'A1.LIN.A.2', difficulty: 3,
    prompt: 'The line $y = 4x - 8$ crosses the $x$-axis where $y = 0$. What is $x$ there?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set $y = 0$: solve $0 = 4x - 8$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Simpler: $y = 2x - 4$ hits zero when $2x = 4$, so $x = 2$. Set your $y$ to $0$ and solve the same way.' },
      { level: 'guide', text: 'Add $8$ to both sides: $8 = 4x$. Then divide.' },
      { level: 'reveal', text: '$x = 8 \\div 4 = 2$.' },
    ],
    explanation: ['On the $x$-axis, $y = 0$: set $0 = 4x - 8$.', 'Add $8$: $8 = 4x$.', 'Divide by $4$: $x = 2$. The line crosses at $(2, 0)$.'],
    alternativeExplanations: [
      { title: 'Climb from the start', steps: ['The line starts at $(0, -8)$, which is $8$ below the $x$-axis, and climbs $4$ per step.', 'It needs $8 \\div 4 = 2$ steps to reach height $0$ — so it crosses at $x = 2$.'] },
    ],
    tags: ['slope-intercept', 'x-intercept', 'solve'], estimatedSeconds: 60,
  },

  // ---------------- UNIT 8 — Writing line equations (A1.LIN.B.1) ----------------
  {
    domain: 'A1', num: 71, unit: 8, order: 1, slug: 'write-from-m-and-b',
    standard: 'A1.LIN.B.1', difficulty: 1,
    prompt: 'A line has slope $5$ and $y$-intercept $1$. Write its equation in the form $y = mx + b$.',
    answerType: 'expression', primaryAnswer: 'y = 5x + 1',
    alternativeAnswers: ['y=5x+1', '5x + 1', '5x+1'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'In $y = mx + b$, drop the slope into the $m$ spot and the intercept into the $b$ spot.' },
      { level: 'guide', text: '$m = 5$ and $b = 1$: $y = 5x + \\underline{\\ \\ }$.' },
      { level: 'reveal', text: '$y = 5x + 1$.' },
    ],
    explanation: ['The template is $y = mx + b$.', 'Slope $m = 5$ goes in front of $x$; intercept $b = 1$ is added at the end.', 'Equation: $y = 5x + 1$.'],
    alternativeExplanations: [
      { title: 'Start-then-move story', steps: ['The intercept is where you START: height $1$ on the $y$-axis.', 'The slope is how you MOVE: up $5$ per step across.', 'Start $1$, move $5x$: $y = 5x + 1$.'] },
      { title: 'Build the table first', steps: ['Start at $x = 0, y = 1$ and jump $5$ each step: $0 \\to 1$, $1 \\to 6$, $2 \\to 11$.', 'Jump $5$ means $5x$; the value at zero, $1$, is the $+b$: $y = 5x + 1$.'] },
    ],
    tags: ['write-equation', 'slope-intercept'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 72, unit: 8, order: 2, slug: 'savings-story-equation',
    standard: 'A1.LIN.B.1', difficulty: 1,
    prompt: 'You start with $\\$15$ saved and add $\\$5$ every week. Write an equation for your savings $y$ after $x$ weeks.',
    answerType: 'expression', primaryAnswer: 'y = 5x + 15',
    alternativeAnswers: ['y=5x+15', '5x + 15', '5x+15', 'y = 15 + 5x', 'y=15+5x', '15 + 5x', '15+5x'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the START (money at week $0$) and the MOVE (money added per week).' },
      { level: 'guide', text: 'Start $b = 15$, move $m = 5$ per week. Fill in $y = mx + b$.' },
      { level: 'reveal', text: '$y = 5x + 15$.' },
    ],
    explanation: ['The start is $b = 15$ — the money before any weeks pass.', 'The move is $m = 5$ — dollars added each week.', 'Equation: $y = 5x + 15$.'],
    alternativeExplanations: [
      { title: 'Test it on a week', steps: ['After $2$ weeks you should have $15 + 5 + 5 = 25$ dollars.', 'The equation says $y = 5 \\times 2 + 15 = 25$. It matches, so it is right.'] },
      { title: 'From a table', steps: ['Week $0 \\to 15$, week $1 \\to 20$, week $2 \\to 25$: a steady jump of $+5$.', 'The jump is $m = 5$; the week-zero value $15$ is $b$: $y = 5x + 15$.'] },
    ],
    tags: ['write-equation', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 73, unit: 8, order: 3, slug: 'table-find-start-b',
    standard: 'A1.LIN.B.1', difficulty: 1,
    prompt: 'A table shows $x: 0, 1, 2$ and $y: 7, 10, 13$. What is $b$, the starting value of the line?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$b$ is the $y$-value when $x = 0$ — the START.' },
      { level: 'guide', text: 'Look at the first column of the table: $x = 0$ pairs with which $y$?' },
      { level: 'reveal', text: '$b = 7$.' },
    ],
    explanation: ['The $y$-intercept $b$ is the output at $x = 0$.', 'The table says $x = 0 \\to y = 7$.', 'So $b = 7$. (The jump of $+3$ each step is $m$, but that is not what was asked.)'],
    alternativeExplanations: [
      { title: 'On the graph', steps: ['Plot the pairs: $(0,7)$, $(1,10)$, $(2,13)$.', 'The point on the $y$-axis is $(0, 7)$ — the line starts at height $7$.'] },
      { title: 'Walk the pattern backward', steps: ['The $y$-values climb by $3$: $7, 10, 13$.', 'Step back from $x = 1$: $10 - 3 = 7$ at $x = 0$ — the start is $7$.'] },
    ],
    tags: ['write-equation', 'tables', 'y-intercept'], estimatedSeconds: 30,
  },
  {
    domain: 'A1', num: 74, unit: 8, order: 4, slug: 'table-find-jump-m',
    standard: 'A1.LIN.B.1', difficulty: 2,
    prompt: 'A table shows $x: 1, 2, 3$ and $y: 9, 13, 17$. The $y$-values jump by the same amount each step. What is the slope $m$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The slope is the constant JUMP in $y$ each time $x$ grows by $1$.' },
      { level: 'guide', text: 'From $9$ to $13$ is a jump of how much? Check $13$ to $17$ too.' },
      { level: 'reveal', text: 'Both jumps are $4$, so $m = 4$.' },
    ],
    explanation: ['$x$ climbs by $1$ each column, and $y$ climbs $9 \\to 13 \\to 17$.', 'Each jump: $13 - 9 = 4$ and $17 - 13 = 4$.', 'A constant jump of $4$ per step means slope $m = 4$.'],
    alternativeExplanations: [
      { title: 'Slope formula', steps: ['Take two rows as points: $(1, 9)$ and $(3, 17)$.', '$m = \\frac{17 - 9}{3 - 1} = \\frac{8}{2} = 4$ — same answer as the jump.'] },
      { title: 'Rate story', steps: ['Read the table as pay: hour $1 \\to \\$9$, hour $2 \\to \\$13$, hour $3 \\to \\$17$.', 'You earn $\\$4$ more every hour — that per-hour rate is the slope, $4$.'] },
    ],
    tags: ['write-equation', 'tables', 'slope'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 75, unit: 8, order: 5, slug: 'gym-membership-equation',
    standard: 'A1.LIN.B.1', difficulty: 2,
    prompt: 'A gym charges a $\\$25$ sign-up fee plus $\\$10$ per month. Write an equation for the total cost $y$ after $x$ months.',
    answerType: 'expression', primaryAnswer: 'y = 10x + 25',
    alternativeAnswers: ['y=10x+25', '10x + 25', '10x+25', 'y = 25 + 10x', 'y=25+10x', '25 + 10x', '25+10x'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The one-time fee is the START ($b$); the monthly charge is the MOVE ($m$).' },
      { level: 'guide', text: '$b = 25$, $m = 10$. Fill in $y = mx + b$.' },
      { level: 'reveal', text: '$y = 10x + 25$.' },
    ],
    explanation: ['At $0$ months you already owe the sign-up fee: $b = 25$.', 'Each month adds $\\$10$: $m = 10$.', 'Equation: $y = 10x + 25$.'],
    alternativeExplanations: [
      { title: 'Check with 3 months', steps: ['Three months should cost $25 + 10 + 10 + 10 = \\$55$.', 'The equation gives $10 \\times 3 + 25 = 55$ — it checks out.'] },
      { title: 'Table of bills', steps: ['Month $0 \\to 25$, month $1 \\to 35$, month $2 \\to 45$: constant jump $+10$.', 'Jump $10$ is $m$; month-zero bill $25$ is $b$: $y = 10x + 25$.'] },
    ],
    tags: ['write-equation', 'word-problem'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 76, unit: 8, order: 6, slug: 'candle-burn-equation',
    standard: 'A1.LIN.B.1', difficulty: 2,
    prompt: 'A candle starts $20$ cm tall and burns $2$ cm every hour. Write an equation for its height $h$ after $t$ hours.',
    answerType: 'expression', primaryAnswer: 'h = 20 - 2t',
    alternativeAnswers: ['h=20-2t', '20 - 2t', '20-2t', 'h = -2t + 20', 'h=-2t+20', '-2t + 20', '-2t+20'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The height goes DOWN, so the rate is negative: $-2$ cm per hour.' },
      { level: 'guide', text: 'Start at $20$, subtract $2$ for each hour: $h = 20 - \\underline{\\ \\ }t$.' },
      { level: 'reveal', text: '$h = 20 - 2t$.' },
    ],
    explanation: ['Start: $b = 20$ cm at $t = 0$.', 'Move: the candle LOSES $2$ cm per hour, so $m = -2$.', 'Equation: $h = 20 - 2t$.'],
    alternativeExplanations: [
      { title: 'Check an hour', steps: ['After $3$ hours the candle burned $3 \\times 2 = 6$ cm, leaving $20 - 6 = 14$ cm.', 'The equation gives $h = 20 - 2 \\times 3 = 14$ — it matches.'] },
      { title: 'Downhill stairs table', steps: ['Hour $0 \\to 20$, hour $1 \\to 18$, hour $2 \\to 16$: a steady jump of $-2$.', 'Jump $-2$ is the slope, start $20$ is $b$: $h = -2t + 20$, the same as $20 - 2t$.'] },
    ],
    tags: ['write-equation', 'negative-slope', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'A1', num: 77, unit: 8, order: 7, slug: 'equation-from-table',
    standard: 'A1.LIN.B.1', difficulty: 2,
    prompt: 'A table shows $x: 0, 1, 2$ and $y: 3, 8, 13$. Write the equation of the line in the form $y = mx + b$.',
    answerType: 'expression', primaryAnswer: 'y = 5x + 3',
    alternativeAnswers: ['y=5x+3', '5x + 3', '5x+3', 'y = 3 + 5x', 'y=3+5x'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two jobs: find the constant JUMP (that is $m$), then the value at $x = 0$ (that is $b$).' },
      { level: 'guide', text: 'Jump: $8 - 3 = 5$. Start: $y = 3$ when $x = 0$.' },
      { level: 'reveal', text: '$y = 5x + 3$.' },
    ],
    explanation: ['The jump: $3 \\to 8 \\to 13$ climbs by $5$ each step, so $m = 5$.', 'The start: at $x = 0$, $y = 3$, so $b = 3$.', 'Equation: $y = 5x + 3$. Check: $x = 2$ gives $5 \\times 2 + 3 = 13$. Correct!'],
    alternativeExplanations: [
      { title: 'Machine story', steps: ['Think of a machine: input $x$, and the output starts at $3$ then adds $5$ per input step.', '"Times 5, plus 3" in machine language is $y = 5x + 3$.'] },
      { title: 'Slope formula on two rows', steps: ['Points $(0, 3)$ and $(2, 13)$: $m = \\frac{13 - 3}{2 - 0} = 5$.', 'The row $(0, 3)$ hands you $b = 3$ directly: $y = 5x + 3$.'] },
    ],
    tags: ['write-equation', 'tables'], estimatedSeconds: 55,
  },
  {
    domain: 'A1', num: 78, unit: 8, order: 8, slug: 'two-points-with-intercept',
    standard: 'A1.LIN.B.1', difficulty: 3,
    prompt: 'A line passes through $(0, 6)$ and $(2, 12)$. Write its equation in the form $y = mx + b$.',
    answerType: 'expression', primaryAnswer: 'y = 3x + 6',
    alternativeAnswers: ['y=3x+6', '3x + 6', '3x+6', 'y = 6 + 3x', 'y=6+3x'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Slope first: $m = \\frac{y_2 - y_1}{x_2 - x_1}$. Then notice one point has $x = 0$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Easier pair: $(0, 1)$ and $(2, 5)$ rise $4$ over run $2$, so $m = 2$ and $b = 1$: $y = 2x + 1$. The $b$ is free when one point has $x = 0$.' },
      { level: 'guide', text: '$m = \\frac{12 - 6}{2 - 0} = 3$. The point $(0, 6)$ IS the $y$-intercept.' },
      { level: 'reveal', text: '$y = 3x + 6$.' },
    ],
    explanation: ['Slope: $m = \\frac{12 - 6}{2 - 0} = \\frac{6}{2} = 3$.', 'A point with $x = 0$ gives $b$ for free: $b = 6$.', 'Equation: $y = 3x + 6$.'],
    alternativeExplanations: [
      { title: 'Growth story', steps: ['Read the points as a plant: $6$ cm at week $0$, $12$ cm at week $2$.', 'It grew $6$ cm in $2$ weeks — $3$ cm per week from a $6$ cm start: $y = 3x + 6$.'] },
      { title: 'Fill in the table', steps: ['Between $x = 0$ and $x = 2$, $y$ goes $6 \\to ? \\to 12$; the middle must be $9$.', 'Jump $+3$ per step and start $6$: $y = 3x + 6$.'] },
    ],
    tags: ['write-equation', 'two-points'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 79, unit: 8, order: 9, slug: 'temperature-rise-equation',
    standard: 'A1.LIN.B.1', difficulty: 3,
    prompt: 'At sunrise the temperature is $55^\\circ$ and it rises $3^\\circ$ every hour. Write an equation for the temperature $y$ after $x$ hours.',
    answerType: 'expression', primaryAnswer: 'y = 3x + 55',
    alternativeAnswers: ['y=3x+55', '3x + 55', '3x+55', 'y = 55 + 3x', 'y=55+3x', '55 + 3x', '55+3x'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sunrise is hour $0$ — that temperature is your START, $b$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Check hour $1$: $55 + 3 = 58$ degrees. The starting temperature is $b$ and the hourly rise is $m$.' },
      { level: 'guide', text: '$b = 55$ and the MOVE is $+3$ per hour, so $m = 3$.' },
      { level: 'reveal', text: '$y = 3x + 55$.' },
    ],
    explanation: ['At $x = 0$ hours the temperature is $55^\\circ$: $b = 55$.', 'It rises $3^\\circ$ per hour: $m = 3$.', 'Equation: $y = 3x + 55$.'],
    alternativeExplanations: [
      { title: 'Check at noon-ish', steps: ['After $4$ hours it should be $55 + 3 \\times 4 = 67$ degrees.', 'Counting by threes from $55$: $58, 61, 64, 67$ — the equation agrees.'] },
      { title: 'Table of hours', steps: ['Hour $0 \\to 55$, hour $1 \\to 58$, hour $2 \\to 61$: constant jump $+3$.', 'Jump $3$ is $m$, hour-zero value $55$ is $b$: $y = 3x + 55$.'] },
    ],
    tags: ['write-equation', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: 'A1', num: 80, unit: 8, order: 10, slug: 'two-points-no-intercept',
    standard: 'A1.LIN.B.1', difficulty: 3,
    prompt: 'A line passes through $(1, 5)$ and $(3, 11)$. Write its equation in the form $y = mx + b$.',
    answerType: 'expression', primaryAnswer: 'y = 3x + 2',
    alternativeAnswers: ['y=3x+2', '3x + 2', '3x+2', 'y = 2 + 3x', 'y=2+3x'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Step 1: slope from the two points. Step 2: plug one point into $y = 3x + b$ to find $b$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up with $(1, 3)$ and $(2, 5)$: slope $= 2$, then back-solve $3 = 2(1) + b$ to get $b = 1$. Find $m$ first, then hunt for $b$.' },
      { level: 'guide', text: '$m = \\frac{11 - 5}{3 - 1} = 3$. Then $5 = 3 \\times 1 + b$, so $b = ?$' },
      { level: 'reveal', text: '$b = 2$, so $y = 3x + 2$.' },
    ],
    explanation: ['Slope: $m = \\frac{11 - 5}{3 - 1} = \\frac{6}{2} = 3$.', 'Find $b$ with the point $(1, 5)$: $5 = 3 \\times 1 + b$, so $b = 2$.', 'Equation: $y = 3x + 2$. Check with $(3, 11)$: $3 \\times 3 + 2 = 11$. Correct!'],
    alternativeExplanations: [
      { title: 'Walk back to the start', steps: ['The slope is $3$, so stepping LEFT one unit drops $y$ by $3$.', 'From $(1, 5)$, step back to $x = 0$: $y = 5 - 3 = 2$. That start is $b$: $y = 3x + 2$.'] },
      { title: 'Table with a gap', steps: ['Rows: $x = 1 \\to 5$, $x = 2 \\to ?$, $x = 3 \\to 11$; the jump must be $3$, so the middle is $8$.', 'Extend back to $x = 0$: $5 - 3 = 2$. Jump $3$, start $2$: $y = 3x + 2$.'] },
    ],
    tags: ['write-equation', 'two-points'], estimatedSeconds: 75,
  },
];
