import type { SeedProblem } from './types';

// Algebra 1 — Units 9–11: systems of equations, exponent rules, and
// exponential vs. linear growth. Nums 81–110, 10 problems per unit,
// difficulty ramp 1-1-1-2-2-2-2-3-3-3 within each unit.
export const problemsA1u09: SeedProblem[] = [
  // ---------------- Unit 9 — Systems of equations (A1.SYS.A.1) ----------------
  {
    domain: 'A1', num: 81, unit: 9, order: 1, slug: 'system-two-rules-cross',
    standard: 'A1.SYS.A.1', difficulty: 1,
    prompt: 'Two rules must BOTH be true: $y = x + 3$ and $y = 2x$. What is $x$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Both rules give the same $y$, so the right sides must match: set $x + 3 = 2x$.' },
      { level: 'guide', text: 'Subtract $x$ from both sides of $x + 3 = 2x$ to get $3 = x$.' },
      { level: 'reveal', text: '$x = 3$. Check: $y = 3 + 3 = 6$ and $y = 2 \\times 3 = 6$. Both rules agree.' },
    ],
    explanation: ['A system is two rules that must both be true at once — the point where two lines cross.', 'Since both equal $y$, set them equal: $x + 3 = 2x$.', 'Subtract $x$: $3 = x$. Check: both rules give $y = 6$. ✓'],
    alternativeExplanations: [
      { title: 'Build a table', steps: ['Try x-values in both rules. x = 1: rule one gives 4, rule two gives 2. x = 2: gives 5 and 4.', 'x = 3: gives 6 and 6 — a match! The rules agree at x = 3.'] },
      { title: 'As two racers', steps: ['Racer one starts 3 steps ahead and moves 1 step per turn (y = x + 3). Racer two starts at 0 but moves 2 steps per turn (y = 2x).', 'Racer two closes the 3-step gap by 1 step each turn, so they meet after 3 turns: x = 3.'] },
    ],
    tags: ['system-of-equations', 'substitution'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 82, unit: 9, order: 2, slug: 'system-substitution-basic',
    standard: 'A1.SYS.A.1', difficulty: 1,
    prompt: 'Solve the system by substitution: $y = x + 1$ and $x + y = 9$. What is $x$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitution means "swap in what $y$ equals." Replace $y$ in the second equation with $x + 1$.' },
      { level: 'guide', text: 'That gives $x + (x + 1) = 9$, so $2x + 1 = 9$.' },
      { level: 'reveal', text: '$2x = 8$, so $x = 4$. (And $y = 5$.)' },
    ],
    explanation: ['The first rule tells you exactly what $y$ is: $x + 1$. Swap that in for $y$ in the second rule.', '$x + (x + 1) = 9$ becomes $2x + 1 = 9$, so $2x = 8$.', '$x = 4$. Check: $y = 5$ and $4 + 5 = 9$. ✓'],
    alternativeExplanations: [
      { title: 'Think in words', steps: ['Two numbers add to 9, and one of them is exactly 1 bigger than the other.', 'Split 9 into two nearly-equal parts: 4 and 5. The smaller one is x, so x = 4.'] },
      { title: 'Guess and check with a table', steps: ['Try x = 3: then y = 4 and x + y = 7. Too small. Try x = 5: then y = 6 and x + y = 11. Too big.', 'Try x = 4: then y = 5 and 4 + 5 = 9. Just right, so x = 4.'] },
    ],
    tags: ['system-of-equations', 'substitution'], estimatedSeconds: 50,
  },
  {
    domain: 'A1', num: 83, unit: 9, order: 3, slug: 'system-pets-cats-dogs',
    standard: 'A1.SYS.A.1', difficulty: 1,
    prompt: 'A shelter has 12 pets total, all cats and dogs. There are 4 more cats than dogs. How many cats are there?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Write two rules: $c + d = 12$ and $c = d + 4$.' },
      { level: 'guide', text: 'Swap in what $c$ equals: $(d + 4) + d = 12$, so $2d + 4 = 12$.' },
      { level: 'reveal', text: '$2d = 8$, so $d = 4$ dogs and $c = 4 + 4 = 8$ cats.' },
    ],
    explanation: ['Two rules must both be true: cats plus dogs is 12, and cats are 4 more than dogs.', 'Substitute $c = d + 4$ into $c + d = 12$: $2d + 4 = 12$, so $d = 4$.', 'Cats: $c = 4 + 4 = 8$. Check: $8 + 4 = 12$ pets. ✓'],
    alternativeExplanations: [
      { title: 'Share it out evenly first', steps: ['Split 12 pets evenly: 6 cats and 6 dogs. But cats need to be 4 MORE than dogs.', 'Move 2 pets from the dog pile to the cat pile: 8 cats and 4 dogs. Now the gap is 4. Cats = 8.'] },
      { title: 'Take away the extra', steps: ['Set the 4 extra cats aside. The remaining 12 − 4 = 8 pets split evenly: 4 cats and 4 dogs.', 'Give the 4 extras back to the cats: 4 + 4 = 8 cats.'] },
    ],
    tags: ['system-of-equations', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 84, unit: 9, order: 4, slug: 'system-phone-plans',
    standard: 'A1.SYS.A.1', difficulty: 2,
    prompt: 'Plan A costs $\\$20$ plus $\\$5$ per month. Plan B costs $\\$10$ plus $\\$7$ per month. After how many months do they cost the same?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set the two costs equal: $20 + 5m = 10 + 7m$.' },
      { level: 'guide', text: 'Subtract $5m$ and $10$ from both sides: $10 = 2m$.' },
      { level: 'reveal', text: '$m = 10 \\div 2 = 5$ months.' },
    ],
    explanation: ['Same cost means $20 + 5m = 10 + 7m$.', 'Subtract $5m$: $20 = 10 + 2m$. Subtract $10$: $10 = 2m$.', '$m = 5$. Check: both plans cost $\\$45$ at 5 months. ✓'],
    alternativeExplanations: [
      { title: 'Build a table', steps: ['Month 1: A = 25, B = 17. Month 3: A = 35, B = 31. B is catching up by $2 each month.', 'A starts $10 ahead and B gains $2 per month: 10 ÷ 2 = 5 months to tie.'] },
      { title: 'As two racers', steps: ['Plan A starts 10 dollars ahead but walks 5 per month; B runs 7 per month.', 'B closes the 10-dollar gap at 2 per month → catches A after 5 months.'] },
    ],
    tags: ['system-of-equations', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 85, unit: 9, order: 5, slug: 'system-substitution-two-step',
    standard: 'A1.SYS.A.1', difficulty: 2,
    prompt: 'Solve by substitution: $y = 2x - 1$ and $3x + y = 14$. What is $x$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Swap in what $y$ equals: replace $y$ in $3x + y = 14$ with $2x - 1$.' },
      { level: 'guide', text: '$3x + 2x - 1 = 14$ becomes $5x - 1 = 14$, so $5x = 15$.' },
      { level: 'reveal', text: '$x = 15 \\div 5 = 3$. (And $y = 2 \\times 3 - 1 = 5$.)' },
    ],
    explanation: ['The first rule hands you $y$ on a plate: $y = 2x - 1$. Swap it into the second rule.', '$3x + (2x - 1) = 14$ combines to $5x - 1 = 14$.', 'Add 1: $5x = 15$, so $x = 3$. Check: $9 + 5 = 14$. ✓'],
    alternativeExplanations: [
      { title: 'Guess and check with a table', steps: ['Try x = 2: y = 3 and 3(2) + 3 = 9. Too small. Try x = 4: y = 7 and 12 + 7 = 19. Too big.', 'Try x = 3: y = 5 and 9 + 5 = 14. That is it — x = 3.'] },
      { title: 'Picture the swap', steps: ['Think of y as a labeled box. The label says "2x − 1 lives inside."', 'The second equation 3x + [box] = 14 becomes 3x + 2x − 1 = 14, which is 5 copies of x minus 1. Five copies make 15, so each copy is 3.'] },
    ],
    tags: ['system-of-equations', 'substitution'], estimatedSeconds: 70,
  },
  {
    domain: 'A1', num: 86, unit: 9, order: 6, slug: 'system-elimination-add',
    standard: 'A1.SYS.A.1', difficulty: 2,
    prompt: 'Solve by elimination: $x + y = 10$ and $x - y = 4$. What is $x$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Stack the equations and add them. The $+y$ and $-y$ cancel out.' },
      { level: 'guide', text: 'Adding gives $2x = 14$.' },
      { level: 'reveal', text: '$x = 14 \\div 2 = 7$. (And $y = 3$.)' },
    ],
    explanation: ['Elimination means "stack and cancel." Stack the two equations and add straight down.', '$x + x = 2x$, $y + (-y) = 0$, and $10 + 4 = 14$. The $y$s vanish: $2x = 14$.', '$x = 7$. Check: $7 + 3 = 10$ and $7 - 3 = 4$. ✓'],
    alternativeExplanations: [
      { title: 'Sum and difference story', steps: ['Two numbers add to 10 and are 4 apart. The bigger one sits half the gap above the middle.', 'The middle of 10 is 5, and half of 4 is 2. Bigger number: 5 + 2 = 7. So x = 7.'] },
      { title: 'Build a table', steps: ['List pairs that add to 10: (6, 4), (7, 3), (8, 2).', 'Which pair is 4 apart? 7 − 3 = 4. So x = 7 and y = 3.'] },
    ],
    tags: ['system-of-equations', 'elimination'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 87, unit: 9, order: 7, slug: 'system-tickets-adult-price',
    standard: 'A1.SYS.A.1', difficulty: 2,
    prompt: 'At a school play, 3 adult tickets and 2 kid tickets cost $\\$41$. One adult ticket and 2 kid tickets cost $\\$23$. How many dollars does one adult ticket cost?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Both orders have the SAME 2 kid tickets. Stack the equations and subtract to cancel the kids.' },
      { level: 'guide', text: '$(3a + 2k) - (a + 2k) = 41 - 23$ gives $2a = 18$.' },
      { level: 'reveal', text: '$a = 18 \\div 2 = 9$ dollars per adult ticket.' },
    ],
    explanation: ['Write the rules: $3a + 2k = 41$ and $a + 2k = 23$.', 'Both have $2k$, so subtract the second from the first — the kid tickets cancel: $2a = 18$.', '$a = 9$. Check: $2k = 23 - 9 = 14$, and $27 + 14 = 41$. ✓'],
    alternativeExplanations: [
      { title: 'Compare the two receipts', steps: ['The big order is the small order plus 2 extra adult tickets. The price difference is 41 − 23 = 18 dollars.', 'So 2 adult tickets cost $18, and one costs 18 ÷ 2 = 9 dollars.'] },
      { title: 'Picture the ticket piles', steps: ['Draw both orders: [A A A K K] = 41 and [A K K] = 23.', 'Cross off one A and two Ks from each pile. What is left is [A A] = 18, so each A is 9.'] },
    ],
    tags: ['system-of-equations', 'elimination', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'A1', num: 88, unit: 9, order: 8, slug: 'system-elimination-multiply',
    standard: 'A1.SYS.A.1', difficulty: 3,
    prompt: 'Solve the system: $2x + 3y = 19$ and $x + y = 8$. What is $y$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $x$s do not match yet. Multiply the whole second equation by 2 to get $2x + 2y = 16$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Simpler system: $x + y = 5$ and $x = 3$ gives $y = 2$. Here, rewrite $x + y = 8$ as $x = 8 - y$ and swap it in.' },
      { level: 'guide', text: 'Now stack and subtract: $(2x + 3y) - (2x + 2y) = 19 - 16$.' },
      { level: 'reveal', text: 'The $x$s cancel: $y = 3$. (And $x = 5$.)' },
    ],
    explanation: ['To cancel with elimination, the copies must match. Double the second equation: $2x + 2y = 16$.', 'Subtract it from the first: the $2x$s vanish and $3y - 2y = y$.', '$y = 19 - 16 = 3$. Check: $x = 5$, and $10 + 9 = 19$. ✓'],
    alternativeExplanations: [
      { title: 'Substitution instead', steps: ['From x + y = 8, we know x = 8 − y. Swap that into the first rule: 2(8 − y) + 3y = 19.', 'That is 16 − 2y + 3y = 19, so 16 + y = 19 and y = 3.'] },
      { title: 'Guess pairs from the easy rule', steps: ['Pairs that add to 8: (5, 3), (4, 4), (6, 2). Test each in 2x + 3y = 19.', '(5, 3) gives 10 + 9 = 19. It works, so y = 3.'] },
    ],
    tags: ['system-of-equations', 'elimination'], estimatedSeconds: 85,
  },
  {
    domain: 'A1', num: 89, unit: 9, order: 9, slug: 'system-streaming-signup-fee',
    standard: 'A1.SYS.A.1', difficulty: 3,
    prompt: 'A streaming service charges a $\\$12$ sign-up fee plus $\\$8$ per month. A rival charges no fee but $\\$10$ per month. After how many months have you paid the same total on both?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Write both totals: $12 + 8m$ and $10m$. Set them equal.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Test month $1$: $12 + 8 = \\$20$ versus the rival. Keep testing months, or set both cost expressions equal.' },
      { level: 'guide', text: '$12 + 8m = 10m$. Subtract $8m$ from both sides: $12 = 2m$.' },
      { level: 'reveal', text: '$m = 12 \\div 2 = 6$ months. Both totals are $\\$60$.' },
    ],
    explanation: ['Total cost is where the two rules cross: $12 + 8m = 10m$.', 'Subtract $8m$: $12 = 2m$, so $m = 6$.', 'Check: $12 + 48 = 60$ and $10 \\times 6 = 60$. Same total. ✓'],
    alternativeExplanations: [
      { title: 'Gap-closing story', steps: ['The fee puts you $12 behind on service one from day zero. But each month it charges $2 LESS than the rival.', 'Saving $2 a month erases a $12 head start in 12 ÷ 2 = 6 months.'] },
      { title: 'Build a table', steps: ['Month 2: fee plan = 28, rival = 20. Month 4: 44 vs 40. Month 6: 60 vs 60.', 'The totals tie at month 6.'] },
    ],
    tags: ['system-of-equations', 'word-problem'], estimatedSeconds: 80,
  },
  {
    domain: 'A1', num: 90, unit: 9, order: 10, slug: 'system-coins-nickels',
    standard: 'A1.SYS.A.1', difficulty: 3,
    prompt: 'You have 15 coins, all nickels and dimes, worth $\\$1.10$ total. How many nickels do you have?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two rules in cents: $n + d = 15$ coins and $5n + 10d = 110$ cents.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try all-nickels first: $15$ nickels is only $\\$0.75$ — too little by $\\$0.35$. Every dime swap adds $\\$0.05$, so count the swaps.' },
      { level: 'guide', text: 'Swap in $d = 15 - n$: $5n + 10(15 - n) = 110$, so $150 - 5n = 110$.' },
      { level: 'reveal', text: '$5n = 40$, so $n = 8$ nickels. (And 7 dimes.)' },
    ],
    explanation: ['Count rule: $n + d = 15$. Money rule in cents: $5n + 10d = 110$.', 'Substitute $d = 15 - n$: $5n + 150 - 10n = 110$, so $-5n = -40$.', '$n = 8$. Check: $8 \\times 5 + 7 \\times 10 = 40 + 70 = 110$ cents. ✓'],
    alternativeExplanations: [
      { title: 'Pretend they are all dimes', steps: ['If all 15 coins were dimes, you would have 150 cents — that is 40 cents too much.', 'Swapping a dime for a nickel drops the total by 5 cents. You need 40 ÷ 5 = 8 swaps, so 8 nickels.'] },
      { title: 'Build a table', steps: ['10 nickels, 5 dimes: 50 + 50 = 100 cents. Too low. 6 nickels, 9 dimes: 30 + 90 = 120. Too high.', '8 nickels, 7 dimes: 40 + 70 = 110 cents. That is the match — 8 nickels.'] },
    ],
    tags: ['system-of-equations', 'word-problem'], estimatedSeconds: 90,
  },

  // ---------------- Unit 10 — Exponent rules (A1.EXPO.A.1) ----------------
  {
    domain: 'A1', num: 91, unit: 10, order: 1, slug: 'expo-paper-fold-five',
    standard: 'A1.EXPO.A.1', difficulty: 1,
    prompt: 'You fold a sheet of paper 5 times. Each fold doubles the layers, so you get $2^5$ layers. How many layers is that?',
    answerType: 'numeric', primaryAnswer: '32', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$2^5$ means five copies of 2 multiplied: $2 \\times 2 \\times 2 \\times 2 \\times 2$.' },
      { level: 'guide', text: 'Double step by step: 2, 4, 8, 16, ...' },
      { level: 'reveal', text: 'One more double: $16 \\times 2 = 32$ layers.' },
    ],
    explanation: ['An exponent counts the copies: $2^5 = 2 \\times 2 \\times 2 \\times 2 \\times 2$.', 'Double five times: 2, 4, 8, 16, 32.', 'After 5 folds you have 32 layers.'],
    alternativeExplanations: [
      { title: 'Fold-by-fold table', steps: ['Fold 1: 2 layers. Fold 2: 4. Fold 3: 8. Fold 4: 16. Fold 5: 32.', 'Each row doubles the one before, so 5 folds give 32 layers.'] },
      { title: 'Pair the copies', steps: ['Group 2⁵ as (2 × 2) × (2 × 2) × 2 = 4 × 4 × 2.', '4 × 4 = 16, and 16 × 2 = 32.'] },
    ],
    tags: ['exponents', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 92, unit: 10, order: 2, slug: 'expo-product-rule-basic',
    standard: 'A1.EXPO.A.1', difficulty: 1,
    prompt: 'Simplify: $x^3 \\cdot x^4$. Write your answer as a power of $x$.',
    answerType: 'expression', primaryAnswer: 'x^7', alternativeAnswers: ['x⁷'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$x^3$ is 3 copies of $x$, and $x^4$ is 4 more copies. Count ALL the copies.' },
      { level: 'guide', text: 'Multiplying powers with the same base ADDS the exponents: $x^{3+4}$.' },
      { level: 'reveal', text: '$x^3 \\cdot x^4 = x^7$.' },
    ],
    explanation: ['$x^3 \\cdot x^4$ means $(x \\cdot x \\cdot x)(x \\cdot x \\cdot x \\cdot x)$ — copies of $x$ lined up.', 'Count them: $3 + 4 = 7$ copies total.', 'So $x^3 \\cdot x^4 = x^7$. Product rule: add the exponents.'],
    alternativeExplanations: [
      { title: 'Test with real numbers', steps: ['Let x = 2. Then 2³ = 8 and 2⁴ = 16, and 8 × 16 = 128.', '128 is 2⁷, not 2¹². So the exponents add: x⁷.'] },
      { title: 'Two boxes of copies', steps: ['Picture a box holding 3 x-tiles and a box holding 4 x-tiles, all being multiplied together.', 'Dump both boxes into one: 3 + 4 = 7 tiles, which is x⁷.'] },
    ],
    tags: ['exponents', 'product-rule'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 93, unit: 10, order: 3, slug: 'expo-evaluate-five-cubed',
    standard: 'A1.EXPO.A.1', difficulty: 1,
    prompt: 'Evaluate: $5^3$.',
    answerType: 'numeric', primaryAnswer: '125', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$5^3$ means three copies of 5 multiplied: $5 \\times 5 \\times 5$.' },
      { level: 'guide', text: 'First pair: $5 \\times 5 = 25$. Now multiply by the last 5.' },
      { level: 'reveal', text: '$25 \\times 5 = 125$.' },
    ],
    explanation: ['The exponent counts copies: $5^3 = 5 \\times 5 \\times 5$.', 'Step by step: $5 \\times 5 = 25$, then $25 \\times 5 = 125$.', '$5^3 = 125$ — not $5 \\times 3 = 15$.'],
    alternativeExplanations: [
      { title: 'Picture a cube', steps: ['5³ counts the little blocks in a 5-by-5-by-5 cube.', 'One layer holds 5 × 5 = 25 blocks, and there are 5 layers: 25 × 5 = 125.'] },
      { title: 'Break 25 apart', steps: ['25 × 5 is the same as (20 + 5) × 5.', '20 × 5 = 100 and 5 × 5 = 25, so the total is 100 + 25 = 125.'] },
    ],
    tags: ['exponents', 'evaluate'], estimatedSeconds: 30,
  },
  {
    domain: 'A1', num: 94, unit: 10, order: 4, slug: 'expo-quotient-rule-basic',
    standard: 'A1.EXPO.A.1', difficulty: 2,
    prompt: 'Simplify: $x^8 \\div x^3$. Write your answer as a power of $x$.',
    answerType: 'expression', primaryAnswer: 'x^5', alternativeAnswers: ['x⁵'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Write it as a fraction: 8 copies of $x$ on top, 3 copies on the bottom.' },
      { level: 'guide', text: 'Each bottom copy cancels one top copy. How many top copies survive?' },
      { level: 'reveal', text: '$8 - 3 = 5$ copies survive: $x^5$.' },
    ],
    explanation: ['$\\frac{x^8}{x^3}$ has 8 copies of $x$ upstairs and 3 downstairs.', 'Cancel the copies: each bottom $x$ wipes out one top $x$, three times.', 'That leaves $8 - 3 = 5$ copies: $x^5$. Quotient rule: subtract the exponents.'],
    alternativeExplanations: [
      { title: 'Test with real numbers', steps: ['Let x = 2. Then 2⁸ = 256 and 2³ = 8, and 256 ÷ 8 = 32.', '32 = 2⁵, so the exponents subtract: x⁵.'] },
      { title: 'Undo a multiplication', steps: ['Division undoes multiplication. Ask: x³ times WHAT gives x⁸?', 'Multiplying adds exponents, so you need 3 + ? = 8. The missing power is x⁵.'] },
    ],
    tags: ['exponents', 'quotient-rule'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 95, unit: 10, order: 5, slug: 'expo-power-rule-basic',
    standard: 'A1.EXPO.A.1', difficulty: 2,
    prompt: 'Simplify: $(x^2)^4$. Write your answer as a power of $x$.',
    answerType: 'expression', primaryAnswer: 'x^8', alternativeAnswers: ['x⁸'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$(x^2)^4$ means four copies of $x^2$ multiplied: $x^2 \\cdot x^2 \\cdot x^2 \\cdot x^2$.' },
      { level: 'guide', text: 'Each $x^2$ carries 2 copies of $x$, and there are 4 groups: $2 \\times 4$ copies.' },
      { level: 'reveal', text: '$(x^2)^4 = x^{2 \\times 4} = x^8$.' },
    ],
    explanation: ['A power of a power is copies of copies: 4 groups, each holding 2 copies of $x$.', '4 groups $\\times$ 2 copies each $= 8$ copies.', 'So $(x^2)^4 = x^8$. Power rule: multiply the exponents.'],
    alternativeExplanations: [
      { title: 'Add them up with the product rule', steps: ['Unroll it: (x²)⁴ = x² · x² · x² · x².', 'Multiplying powers adds exponents: 2 + 2 + 2 + 2 = 8, so x⁸.'] },
      { title: 'Egg-carton picture', steps: ['Picture 4 cartons, each holding 2 eggs. Every egg is one copy of x being multiplied.', 'Total eggs: 4 × 2 = 8, so the answer is x⁸.'] },
    ],
    tags: ['exponents', 'power-rule'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 96, unit: 10, order: 6, slug: 'expo-rumor-round-four',
    standard: 'A1.EXPO.A.1', difficulty: 2,
    prompt: 'A rumor spreads in rounds: each person tells exactly 3 new people. In round 4, the number of new people who hear it is $3^4$. How many people is that?',
    answerType: 'numeric', primaryAnswer: '81', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$3^4$ means four copies of 3 multiplied: $3 \\times 3 \\times 3 \\times 3$.' },
      { level: 'guide', text: 'Triple step by step: 3, 9, 27, ...' },
      { level: 'reveal', text: 'One more triple: $27 \\times 3 = 81$ people.' },
    ],
    explanation: ['Each round multiplies by 3, so round 4 is $3^4 = 3 \\times 3 \\times 3 \\times 3$.', 'Step by step: $3 \\times 3 = 9$, $9 \\times 3 = 27$, $27 \\times 3 = 81$.', '81 new people hear the rumor in round 4.'],
    alternativeExplanations: [
      { title: 'Round-by-round table', steps: ['Round 1: 3 people. Round 2: 9. Round 3: 27. Round 4: 81.', 'Each row is triple the last, so round 4 reaches 81 people.'] },
      { title: 'Pair the copies', steps: ['Group 3⁴ as (3 × 3) × (3 × 3) = 9 × 9.', '9 × 9 = 81.'] },
    ],
    tags: ['exponents', 'word-problem'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 97, unit: 10, order: 7, slug: 'expo-zero-power-multiplier',
    standard: 'A1.EXPO.A.1', difficulty: 2,
    prompt: 'A game power-up multiplies your score by $4^0$. What number does it multiply your score by?',
    answerType: 'numeric', primaryAnswer: '1', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The exponent counts copies of 4 to multiply. Here there are ZERO copies.' },
      { level: 'guide', text: 'Zero copies of multiplying leaves the do-nothing number for multiplication.' },
      { level: 'reveal', text: '$4^0 = 1$. Your score is multiplied by 1 — it stays the same.' },
    ],
    explanation: ['Anything (except 0) to the 0 power is 1.', 'Zero copies of multiplying means you do nothing, and the do-nothing number for multiplication is 1.', 'So $4^0 = 1$, and your score does not change.'],
    alternativeExplanations: [
      { title: 'Walk down the staircase', steps: ['4³ = 64, 4² = 16, 4¹ = 4. Each step DOWN divides by 4.', 'One more step: 4⁰ = 4 ÷ 4 = 1.'] },
      { title: 'Use the quotient rule', steps: ['4⁰ is the same as 4² ÷ 4², since 2 − 2 = 0.', 'But any number divided by itself is 1, so 4⁰ = 1.'] },
    ],
    tags: ['exponents', 'zero-exponent', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 98, unit: 10, order: 8, slug: 'expo-negative-exponent',
    standard: 'A1.EXPO.A.1', difficulty: 3,
    prompt: 'Evaluate: $2^{-3}$. Write your answer as a fraction.',
    answerType: 'fraction', primaryAnswer: '1/8', alternativeAnswers: ['0.125'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A negative exponent means "flip it under 1": $2^{-3} = \\frac{1}{2^3}$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up with $2^{-1}$, which is $\\frac{1}{2}$. A negative exponent flips the power under a $1$ — so $2^{-3}$ flips $2^3$.' },
      { level: 'guide', text: 'Evaluate the bottom: $2^3 = 8$.' },
      { level: 'reveal', text: '$2^{-3} = \\frac{1}{8}$.' },
    ],
    explanation: ['A negative exponent is not a negative number — it flips the power under 1.', '$2^{-3} = \\frac{1}{2^3}$, and $2^3 = 8$.', 'So $2^{-3} = \\frac{1}{8}$.'],
    alternativeExplanations: [
      { title: 'Walk down the staircase', steps: ['2² = 4, 2¹ = 2, 2⁰ = 1. Each step down divides by 2.', 'Keep going: 2⁻¹ = 1/2, 2⁻² = 1/4, 2⁻³ = 1/8.'] },
      { title: 'Use the quotient rule', steps: ['2⁻³ is the same as 2¹ ÷ 2⁴, since 1 − 4 = −3.', 'That is 2/16 = 1/8.'] },
    ],
    tags: ['exponents', 'negative-exponent'], estimatedSeconds: 55,
  },
  {
    domain: 'A1', num: 99, unit: 10, order: 9, slug: 'expo-mixed-rules',
    standard: 'A1.EXPO.A.1', difficulty: 3,
    prompt: 'Simplify: $(x^3)^2 \\cdot x^4 \\div x^5$. Write your answer as a power of $x$.',
    answerType: 'expression', primaryAnswer: 'x^5', alternativeAnswers: ['x⁵'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Handle the power of a power first: $(x^3)^2 = x^{3 \\times 2} = x^6$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Do one rule at a time. First $(x^3)^2 = x^6$ (multiply the exponents). Now it is just $x^6 \\cdot x^4 \\div x^5$.' },
      { level: 'guide', text: 'Now multiply: $x^6 \\cdot x^4 = x^{6+4} = x^{10}$. Then divide.' },
      { level: 'reveal', text: '$x^{10} \\div x^5 = x^{10-5} = x^5$.' },
    ],
    explanation: ['Power rule first: $(x^3)^2 = x^6$ — 2 groups of 3 copies.', 'Product rule: $x^6 \\cdot x^4 = x^{10}$ — combine the copies.', 'Quotient rule: $x^{10} \\div x^5 = x^5$ — cancel 5 copies. Answer: $x^5$.'],
    alternativeExplanations: [
      { title: 'One running count of copies', steps: ['Count copies of x from left to right: the square of x³ gives 6 copies, then +4 more makes 10.', 'Dividing by x⁵ erases 5 copies: 10 − 5 = 5 copies left, so x⁵.'] },
      { title: 'Test with real numbers', steps: ['Let x = 2. (2³)² = 64, times 2⁴ = 16 gives 1024. Divide by 2⁵ = 32: 1024 ÷ 32 = 32.', '32 = 2⁵, so the simplified form is x⁵.'] },
    ],
    tags: ['exponents', 'product-rule', 'quotient-rule', 'power-rule'], estimatedSeconds: 80,
  },
  {
    domain: 'A1', num: 100, unit: 10, order: 10, slug: 'expo-text-chain',
    standard: 'A1.EXPO.A.1', difficulty: 3,
    prompt: 'You text a funny picture to 2 friends, and every person who gets it sends it to 2 new people. After 10 rounds, the round reaches $2^{10}$ people. How many people is that?',
    answerType: 'numeric', primaryAnswer: '1024', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$2^{10}$ is ten copies of 2 multiplied. Use a landmark: $2^5 = 32$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Count one round at a time: round $1$ reaches $2$ people, round $2$ reaches $4$, round $3$ reaches $8$. Each round DOUBLES.' },
      { level: 'guide', text: 'Product rule with numbers: $2^{10} = 2^5 \\times 2^5 = 32 \\times 32$.' },
      { level: 'reveal', text: '$32 \\times 32 = 1024$ people.' },
    ],
    explanation: ['Each round doubles the reach, so round 10 is $2^{10}$.', 'Split it with the product rule: $2^{10} = 2^5 \\cdot 2^5$ because $5 + 5 = 10$.', '$32 \\times 32 = 1024$ people.'],
    alternativeExplanations: [
      { title: 'Keep doubling a list', steps: ['2, 4, 8, 16, 32, 64, 128, 256, 512, 1024.', 'The 10th number in the doubling list is 1024.'] },
      { title: 'Land on 1000 fast', steps: ['2¹⁰ = 2⁴ × 2⁶ = 16 × 64.', '16 × 64 = 16 × 60 + 16 × 4 = 960 + 64 = 1024.'] },
    ],
    tags: ['exponents', 'word-problem'], estimatedSeconds: 70,
  },

  // ------------- Unit 11 — Exponential vs. linear growth (A1.EXPO.A.2) -------------
  {
    domain: 'A1', num: 101, unit: 11, order: 1, slug: 'growth-find-the-factor',
    standard: 'A1.EXPO.A.2', difficulty: 1,
    prompt: 'A pattern goes 3, 6, 12, 24, ... Each step multiplies by the same number. What is that growth factor?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide any term by the one before it: $6 \\div 3 = ?$' },
      { level: 'guide', text: '$6 \\div 3 = 2$, and $12 \\div 6 = 2$ too. The multiplier repeats.' },
      { level: 'reveal', text: 'The growth factor is 2 — each step doubles.' },
    ],
    explanation: ['Exponential patterns MULTIPLY by the same factor each step.', 'Divide neighbors to find it: $6 \\div 3 = 2$, $12 \\div 6 = 2$, $24 \\div 12 = 2$.', 'The growth factor is 2.'],
    alternativeExplanations: [
      { title: 'Rule out adding', steps: ['If the pattern ADDED the same amount, the jumps would match: but 3→6 adds 3 while 6→12 adds 6.', 'The jumps grow, so it multiplies. Each term is exactly double the last: factor 2.'] },
      { title: 'Photocopier picture', steps: ['Imagine a copier set to "enlarge ×2." Feed in 3, get 6. Feed in 6, get 12. Feed in 12, get 24.', 'One machine setting explains every step: the factor is 2.'] },
    ],
    tags: ['exponential-growth', 'patterns'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 102, unit: 11, order: 2, slug: 'growth-linear-followers',
    standard: 'A1.EXPO.A.2', difficulty: 1,
    prompt: 'An account starts with 200 followers and gains 100 new followers every week — the same amount each time. How many followers after 3 weeks?',
    answerType: 'numeric', primaryAnswer: '500', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Adding the same amount each step is LINEAR growth: start plus 100 per week.' },
      { level: 'guide', text: 'Total added in 3 weeks: $3 \\times 100 = 300$.' },
      { level: 'reveal', text: '$200 + 300 = 500$ followers.' },
    ],
    explanation: ['Linear growth ADDS the same amount every step.', 'Rule: followers $= 200 + 100w$. At $w = 3$: $200 + 300$.', 'That is 500 followers.'],
    alternativeExplanations: [
      { title: 'Week-by-week table', steps: ['Week 1: 300. Week 2: 400. Week 3: 500.', 'Each row climbs by exactly 100 — a straight staircase to 500.'] },
      { title: 'Picture a straight ramp', steps: ['On a graph, linear growth is a straight line starting at 200 and rising 100 per week.', 'Three equal steps up from 200 lands at 500.'] },
    ],
    tags: ['linear-growth', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 103, unit: 11, order: 3, slug: 'growth-bacteria-double',
    standard: 'A1.EXPO.A.2', difficulty: 1,
    prompt: 'A dish starts with 5 bacteria, and the count doubles every hour. How many bacteria after 3 hours?',
    answerType: 'numeric', primaryAnswer: '40', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Doubling is exponential: multiply by 2 each hour, three times.' },
      { level: 'guide', text: 'Hour 1: $5 \\times 2 = 10$. Hour 2: $10 \\times 2 = 20$.' },
      { level: 'reveal', text: 'Hour 3: $20 \\times 2 = 40$ bacteria.' },
    ],
    explanation: ['Exponential growth multiplies by the same factor each step: here, $\\times 2$ every hour.', 'Formula: $y = 5 \\cdot 2^x$. At $x = 3$: $5 \\cdot 2^3 = 5 \\cdot 8$.', 'That is 40 bacteria.'],
    alternativeExplanations: [
      { title: 'Hour-by-hour table', steps: ['Hour 0: 5. Hour 1: 10. Hour 2: 20. Hour 3: 40.', 'Each row doubles the last — after 3 hours, 40 bacteria.'] },
      { title: 'Compare with adding', steps: ['If the dish ADDED 5 each hour (linear), 3 hours would give 5 + 15 = 20.', 'Doubling is faster: 5 × 8 = 40 — exponential growth pulls ahead.'] },
    ],
    tags: ['exponential-growth', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 104, unit: 11, order: 4, slug: 'growth-factor-from-percent-up',
    standard: 'A1.EXPO.A.2', difficulty: 2,
    prompt: 'A quantity grows by $10\\%$ each year. What growth factor do you multiply by each year? (Write it as a decimal.)',
    answerType: 'numeric', primaryAnswer: '1.10', alternativeAnswers: ['1.1'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Growing 10% means you keep ALL of it (100%) plus 10% more.' },
      { level: 'guide', text: '$100\\% + 10\\% = 110\\%$. Turn that percent into a decimal.' },
      { level: 'reveal', text: '$110\\% = 1.10$. Multiply by 1.10 each year.' },
    ],
    explanation: ['"Up 10%" means the new amount is 110% of the old one.', 'As a decimal, $110\\% = 1.10$.', 'So each year you multiply by the growth factor 1.10.'],
    alternativeExplanations: [
      { title: 'Test it on $100', steps: ['Start with $100. Growing 10% adds $10, giving $110.', 'What times 100 gives 110? 110 ÷ 100 = 1.10 — that is the factor.'] },
      { title: 'Keep-plus-gain picture', steps: ['Picture the amount as a full bar (the 1) plus a small extra slice (the 0.10).', 'Keep + gain = 1 + 0.10 = 1.10 per year.'] },
    ],
    tags: ['exponential-growth', 'percent'], estimatedSeconds: 40,
  },
  {
    domain: 'A1', num: 105, unit: 11, order: 5, slug: 'growth-factor-from-percent-down',
    standard: 'A1.EXPO.A.2', difficulty: 2,
    prompt: 'A quantity shrinks by $20\\%$ each year. What factor do you multiply by each year? (Write it as a decimal.)',
    answerType: 'numeric', primaryAnswer: '0.80', alternativeAnswers: ['0.8', '.8'], acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Losing 20% means you KEEP the rest. What percent is left?' },
      { level: 'guide', text: '$100\\% - 20\\% = 80\\%$. Turn that into a decimal.' },
      { level: 'reveal', text: '$80\\% = 0.80$. Multiply by 0.80 each year.' },
    ],
    explanation: ['"Down 20%" means you keep $100\\% - 20\\% = 80\\%$ of the amount.', 'As a decimal, $80\\% = 0.80$.', 'So each year you multiply by 0.80. (Never multiply by 0.20 — that is what you LOSE.)'],
    alternativeExplanations: [
      { title: 'Test it on $100', steps: ['Start with $100. Losing 20% takes away $20, leaving $80.', '80 ÷ 100 = 0.80, so the yearly factor is 0.80.'] },
      { title: 'Pizza picture', steps: ['Cut the amount into 5 equal slices. Losing 20% means one slice disappears.', 'Four of five slices remain: 4/5 = 0.80 of the amount each year.'] },
    ],
    tags: ['exponential-decay', 'percent'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 106, unit: 11, order: 6, slug: 'growth-evaluate-formula',
    standard: 'A1.EXPO.A.2', difficulty: 2,
    prompt: 'An exponential rule is $y = 3 \\cdot 2^x$ (start 3, factor 2). What is $y$ when $x = 4$?',
    answerType: 'numeric', primaryAnswer: '48', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Exponent first: $2^4 = ?$' },
      { level: 'guide', text: '$2^4 = 16$. Now multiply by the start value 3.' },
      { level: 'reveal', text: '$y = 3 \\times 16 = 48$.' },
    ],
    explanation: ['$y = a \\cdot b^x$ means start $\\times$ factor, applied $x$ times.', 'Compute the power first: $2^4 = 16$.', 'Then $y = 3 \\times 16 = 48$. (Not $6^4$ — never multiply the start into the base!)'],
    alternativeExplanations: [
      { title: 'Double step by step', steps: ['Start at 3 and double 4 times: 3 → 6 → 12 → 24 → 48.', 'After 4 doublings, y = 48.'] },
      { title: 'Table of x and y', steps: ['x = 0: y = 3. x = 1: y = 6. x = 2: y = 12. x = 3: y = 24. x = 4: y = 48.', 'Each row doubles, landing on 48 at x = 4.'] },
    ],
    tags: ['exponential-growth', 'evaluate'], estimatedSeconds: 50,
  },
  {
    domain: 'A1', num: 107, unit: 11, order: 7, slug: 'growth-phone-value-decay',
    standard: 'A1.EXPO.A.2', difficulty: 2,
    prompt: 'Your phone is worth $\\$500$ new and loses $20\\%$ of its value each year. How many dollars is it worth after 2 years?',
    answerType: 'numeric', primaryAnswer: '320', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Losing 20% means keeping 80%: multiply by 0.80 each year.' },
      { level: 'guide', text: 'Year 1: $500 \\times 0.80 = 400$. Now do year 2.' },
      { level: 'reveal', text: 'Year 2: $400 \\times 0.80 = 320$ dollars.' },
    ],
    explanation: ['Each year the phone keeps 80% of its value: factor 0.80.', 'Formula: $500 \\times 0.80^2 = 500 \\times 0.64$.', 'That is $\\$320$ after 2 years.'],
    alternativeExplanations: [
      { title: 'Year-by-year table', steps: ['New: $500. After year 1: 500 × 0.8 = $400. After year 2: 400 × 0.8 = $320.', 'Notice it loses $100 the first year but only $80 the second — decay shrinks by a factor, not a fixed amount.'] },
      { title: 'Slice off a fifth twice', steps: ['Losing 20% = losing one fifth. One fifth of 500 is 100, leaving 400.', 'One fifth of 400 is 80, leaving 320. Value: $320.'] },
    ],
    tags: ['exponential-decay', 'percent', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'A1', num: 108, unit: 11, order: 8, slug: 'growth-penny-doubling',
    standard: 'A1.EXPO.A.2', difficulty: 3,
    prompt: 'A magic penny starts at 1 cent and doubles in value every day. After 10 doublings, how many cents is it worth?',
    answerType: 'numeric', primaryAnswer: '1024', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Ten doublings means $1 \\times 2^{10}$ cents.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Shrink it: after $3$ doublings a penny is $1 \\to 2 \\to 4 \\to 8$ cents, which is $2^3$. So $10$ doublings is $2^{10}$.' },
      { level: 'guide', text: 'Use a landmark: $2^5 = 32$, and $2^{10} = 32 \\times 32$.' },
      { level: 'reveal', text: '$32 \\times 32 = 1024$ cents (over ten dollars!).' },
    ],
    explanation: ['Doubling is exponential: $y = 1 \\cdot 2^x$ cents after $x$ doublings.', 'At $x = 10$: $2^{10} = 2^5 \\times 2^5 = 32 \\times 32$.', 'The penny is worth 1024 cents — more than $\\$10$ from one cent.'],
    alternativeExplanations: [
      { title: 'List the doubles', steps: ['1 → 2 → 4 → 8 → 16 → 32 → 64 → 128 → 256 → 512 → 1024.', 'Ten arrows, ten doublings: 1024 cents.'] },
      { title: 'Compare with $5 a day', steps: ['Adding $5 a day for 10 days gives $50 — but that pace never speeds up.', 'The doubling penny hits $10.24 by day 10 and would pass $5,000,000 by day 30. Multiplying beats adding in the long run.'] },
    ],
    tags: ['exponential-growth', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'A1', num: 109, unit: 11, order: 9, slug: 'growth-double-vs-add-race',
    standard: 'A1.EXPO.A.2', difficulty: 3,
    prompt: 'Account A starts with 10 followers and DOUBLES every week. Account B starts with 10 and ADDS 100 every week. After how many weeks does A first have more followers than B?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Track both: A is $10 \\cdot 2^w$ and B is $10 + 100w$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Fill two weeks: A goes $10 \\to 20 \\to 40$ while B goes $10 \\to 20 \\to 30$. Doubling starts slow, then rockets past adding.' },
      { level: 'guide', text: 'Week 5: A $= 320$, B $= 510$. B still leads. Try week 6.' },
      { level: 'reveal', text: 'Week 6: A $= 640$, B $= 610$. A first passes B at week 6.' },
    ],
    explanation: ['Linear B adds 100 each week; exponential A multiplies by 2.', 'Table — week 4: A = 160, B = 410. Week 5: A = 320, B = 510. Week 6: A = 640, B = 610.', 'A first passes B after 6 weeks. Exponential always wins eventually.'],
    alternativeExplanations: [
      { title: 'Watch the weekly jumps', steps: ['B always jumps by exactly 100. A jumps by its whole current size: +160 in week 5, +320 in week 6.', 'Once A jumps more than 100 per week AND closes the gap, it takes the lead — that happens in week 6 (640 vs 610).'] },
      { title: 'Tortoise and rocket', steps: ['B is a tortoise on a moving walkway: steady +100, a straight line on a graph. A is a rocket: slow at launch, then curving up faster and faster.', 'The rocket lags for 5 weeks, then blasts past in week 6 and never looks back.'] },
    ],
    tags: ['exponential-growth', 'linear-growth', 'word-problem'], estimatedSeconds: 90,
  },
  {
    domain: 'A1', num: 110, unit: 11, order: 10, slug: 'growth-town-population',
    standard: 'A1.EXPO.A.2', difficulty: 3,
    prompt: 'A town of 2000 people grows $10\\%$ per year. How many people after 2 years?',
    answerType: 'numeric', primaryAnswer: '2420', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Up 10% means multiply by 1.10 each year — do NOT just add 200 twice.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'One year first: $10\\%$ of $2000$ is $200$, so year one ends at $2200$. Now take $10\\%$ of the NEW total, not the old one.' },
      { level: 'guide', text: 'Year 1: $2000 \\times 1.10 = 2200$. Now grow year 2 from 2200.' },
      { level: 'reveal', text: 'Year 2: $2200 \\times 1.10 = 2420$ people.' },
    ],
    explanation: ['Growth factor: $100\\% + 10\\% = 1.10$ per year.', 'Two years: $2000 \\times 1.10^2 = 2000 \\times 1.21$.', 'That is 2420 people — more than $2000 + 200 + 200 = 2400$, because year 2 grows the NEW total.'],
    alternativeExplanations: [
      { title: 'Year-by-year table', steps: ['Start: 2000. Year 1 adds 10% of 2000 = 200 → 2200.', 'Year 2 adds 10% of 2200 = 220 → 2420. The add-on grows each year.'] },
      { title: 'Interest on the interest', steps: ['Plain adding would give 2000 + 200 + 200 = 2400.', 'But the 200 newcomers from year 1 also grow 10% in year 2 — that extra 10% of 200 is 20 more, so 2400 + 20 = 2420.'] },
    ],
    tags: ['exponential-growth', 'percent', 'word-problem'], estimatedSeconds: 85,
  },
];
