import type { SeedProblem } from './types';

// A1 Units 12-14 — Polynomials (add/subtract/multiply), Factoring, Quadratics.
// 10 problems per unit, difficulty ramp 1-1-1-2-2-2-2-3-3-3.

export const problemsA1u12: SeedProblem[] = [
  // ---------------- UNIT 12 — Polynomials: add, subtract, multiply ----------------
  {
    domain: 'A1', num: 111, unit: 12, order: 1, slug: 'poly-combine-like-terms',
    standard: 'A1.POLY.A.1', difficulty: 1,
    prompt: 'Simplify $4x + 3x$.',
    answerType: 'expression', primaryAnswer: '7x', acceptanceMode: 'normalized',
    alternativeAnswers: ['7 x'],
    hints: [
      { level: 'nudge', text: 'Both terms are $x$-terms — the same kind of sticker.' },
      { level: 'guide', text: 'Four $x$ stickers plus three $x$ stickers. Add the front numbers: $4 + 3$.' },
      { level: 'reveal', text: '$4x + 3x = 7x$.' },
    ],
    explanation: ['$4x$ and $3x$ are like terms — same variable part.', 'Add the coefficients: $4 + 3 = 7$.', 'Answer: $7x$.'],
    alternativeExplanations: [
      { title: 'Sticker sorting', steps: ['Picture 4 apple stickers and 3 more apple stickers — all the same kind.', 'Same kind means you can count them together: 7 apple stickers, so 7x.'] },
      { title: 'Test a value', steps: ['Try x = 2: then 4x + 3x = 8 + 6 = 14.', 'And 7x = 14 too — the shorter form gives the same value, so 7x is right.'] },
    ],
    tags: ['polynomial', 'like-terms'], estimatedSeconds: 25,
  },
  {
    domain: 'A1', num: 112, unit: 12, order: 2, slug: 'poly-add-binomials',
    standard: 'A1.POLY.A.1', difficulty: 1,
    prompt: 'Add: $(3x + 4) + (2x + 5)$.',
    answerType: 'expression', primaryAnswer: '5x + 9', acceptanceMode: 'normalized',
    alternativeAnswers: ['5x+9', '9 + 5x'],
    hints: [
      { level: 'nudge', text: 'Sort the stickers: $x$-terms in one pile, plain numbers in another.' },
      { level: 'guide', text: '$3x + 2x$ makes one pile, $4 + 5$ makes the other.' },
      { level: 'reveal', text: '$3x + 2x = 5x$ and $4 + 5 = 9$, so the sum is $5x + 9$.' },
    ],
    explanation: ['Adding polynomials means combining like terms.', '$x$-terms: $3x + 2x = 5x$.', 'Numbers: $4 + 5 = 9$.', 'Answer: $5x + 9$.'],
    alternativeExplanations: [
      { title: 'Two bags of blocks', steps: ['Bag one holds 3 long x-blocks and 4 unit cubes. Bag two holds 2 long blocks and 5 cubes.', 'Pour both bags out: 5 long blocks and 9 cubes total — that is 5x + 9.'] },
      { title: 'Stack them vertically', steps: ['Write 3x + 4 on top of 2x + 5, lining up x-terms over x-terms.', 'Add each column like column addition: 5x in the x column, 9 in the number column.'] },
    ],
    tags: ['polynomial', 'addition'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 113, unit: 12, order: 3, slug: 'poly-mono-distribute',
    standard: 'A1.POLY.A.1', difficulty: 1,
    prompt: 'Multiply: $x(x + 5)$.',
    answerType: 'expression', primaryAnswer: 'x^2 + 5x', acceptanceMode: 'normalized',
    alternativeAnswers: ['x^2+5x', 'x² + 5x', 'x²+5x'],
    hints: [
      { level: 'nudge', text: 'The outside $x$ hands a snack to EVERYONE inside the parentheses.' },
      { level: 'guide', text: '$x \\times x = x^2$ and $x \\times 5 = 5x$.' },
      { level: 'reveal', text: '$x(x + 5) = x^2 + 5x$.' },
    ],
    explanation: ['Distribute the outside $x$ to both terms inside.', '$x \\times x = x^2$.', '$x \\times 5 = 5x$.', 'Answer: $x^2 + 5x$.'],
    alternativeExplanations: [
      { title: 'Area picture', steps: ['Draw a rectangle x tall and (x + 5) wide, split into two patches: one x wide, one 5 wide.', 'The patches have areas x·x = x² and x·5 = 5x. Total area: x² + 5x.'] },
      { title: 'Test a value', steps: ['Try x = 2: the original is 2(2 + 5) = 2 × 7 = 14.', 'The answer form gives 2² + 5·2 = 4 + 10 = 14. Same value — the multiplication is correct.'] },
    ],
    tags: ['polynomial', 'distribute'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 114, unit: 12, order: 4, slug: 'poly-subtract-binomials',
    standard: 'A1.POLY.A.1', difficulty: 2,
    prompt: 'Subtract: $(5x + 7) - (2x + 3)$.',
    answerType: 'expression', primaryAnswer: '3x + 4', acceptanceMode: 'normalized',
    alternativeAnswers: ['3x+4', '4 + 3x'],
    hints: [
      { level: 'nudge', text: 'The minus sign hits EVERY term in the second parentheses.' },
      { level: 'guide', text: 'Rewrite it as $5x + 7 - 2x - 3$, then combine like terms.' },
      { level: 'reveal', text: '$5x - 2x = 3x$ and $7 - 3 = 4$, so the answer is $3x + 4$.' },
    ],
    explanation: ['Distribute the minus: $(5x + 7) - (2x + 3) = 5x + 7 - 2x - 3$.', '$x$-terms: $5x - 2x = 3x$.', 'Numbers: $7 - 3 = 4$.', 'Answer: $3x + 4$.'],
    alternativeExplanations: [
      { title: 'Take away stickers', steps: ['Start with 5 x-stickers and 7 dot-stickers.', 'Peel off 2 x-stickers and 3 dot-stickers — take BOTH kinds away.', 'You are left with 3 x-stickers and 4 dots: 3x + 4.'] },
      { title: 'Check with a value', steps: ['Try x = 10: (50 + 7) − (20 + 3) = 57 − 23 = 34.', 'And 3x + 4 at x = 10 is 30 + 4 = 34. The forms match, so 3x + 4 is right.'] },
    ],
    tags: ['polynomial', 'subtraction'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 115, unit: 12, order: 5, slug: 'poly-phone-case-profit',
    standard: 'A1.POLY.A.1', difficulty: 2,
    prompt: 'Your phone case business brings in revenue of $3x^2 + 5x$ dollars and pays costs of $x^2 + 2x$ dollars. Write the profit: revenue minus cost.',
    answerType: 'expression', primaryAnswer: '2x^2 + 3x', acceptanceMode: 'normalized',
    alternativeAnswers: ['2x^2+3x', '2x² + 3x', '2x²+3x'],
    hints: [
      { level: 'nudge', text: 'Profit means money in minus money out: $(3x^2 + 5x) - (x^2 + 2x)$.' },
      { level: 'guide', text: 'The minus distributes: $3x^2 + 5x - x^2 - 2x$. Now match $x^2$ with $x^2$, and $x$ with $x$.' },
      { level: 'reveal', text: '$3x^2 - x^2 = 2x^2$ and $5x - 2x = 3x$. Profit: $2x^2 + 3x$.' },
    ],
    explanation: ['Profit = revenue $-$ cost = $(3x^2 + 5x) - (x^2 + 2x)$.', 'Distribute the minus: $3x^2 + 5x - x^2 - 2x$.', 'Combine like terms: $3x^2 - x^2 = 2x^2$, $5x - 2x = 3x$.', 'Profit: $2x^2 + 3x$ dollars.'],
    alternativeExplanations: [
      { title: 'Two sticker piles', steps: ['x²-terms are one kind of sticker, x-terms are another — never mix the piles.', 'x² pile: 3 minus 1 leaves 2, so 2x². x pile: 5 minus 2 leaves 3, so 3x.', 'Profit: 2x² + 3x.'] },
      { title: 'Try a sales number', steps: ['Say x = 10 cases. Revenue: 3(100) + 50 = 350 dollars. Cost: 100 + 20 = 120 dollars.', 'Profit: 350 − 120 = 230. Check the formula: 2(100) + 3(10) = 230. It works.'] },
    ],
    tags: ['polynomial', 'subtraction', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 116, unit: 12, order: 6, slug: 'poly-garden-area-model',
    standard: 'A1.POLY.A.1', difficulty: 2,
    prompt: 'A rectangular garden is $(x + 3)$ meters long and $(x + 2)$ meters wide. Multiply to write its area.',
    answerType: 'expression', primaryAnswer: 'x^2 + 5x + 6', acceptanceMode: 'normalized',
    alternativeAnswers: ['x^2+5x+6', 'x² + 5x + 6', 'x²+5x+6'],
    hints: [
      { level: 'nudge', text: 'Split the garden into 4 patches: cut the length into $x$ and $3$, the width into $x$ and $2$.' },
      { level: 'guide', text: 'The 4 patch areas are $x \\times x$, $x \\times 2$, $3 \\times x$, and $3 \\times 2$. Add them up.' },
      { level: 'reveal', text: '$x^2 + 2x + 3x + 6 = x^2 + 5x + 6$.' },
    ],
    explanation: ['Draw the area model: a rectangle split into 4 patches.', 'Patch areas: $x^2$, $2x$, $3x$, and $6$.', 'Combine the middle terms: $2x + 3x = 5x$.', 'Area: $x^2 + 5x + 6$ square meters.'],
    alternativeExplanations: [
      { title: 'Distribute twice', steps: ['Hand (x + 2) to each part of (x + 3): x(x + 2) + 3(x + 2).', 'That gives x² + 2x + 3x + 6.', 'Combine: x² + 5x + 6.'] },
      { title: 'Check with a real garden', steps: ['Let x = 5. Then the garden is 8 m by 7 m, area 56 square meters.', 'The formula: 5² + 5·5 + 6 = 25 + 25 + 6 = 56. The expanded form is correct.'] },
    ],
    tags: ['polynomial', 'area-model', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'A1', num: 117, unit: 12, order: 7, slug: 'poly-mono-times-binomial',
    standard: 'A1.POLY.A.1', difficulty: 2,
    prompt: 'Multiply: $2x(3x + 4)$.',
    answerType: 'expression', primaryAnswer: '6x^2 + 8x', acceptanceMode: 'normalized',
    alternativeAnswers: ['6x^2+8x', '6x² + 8x', '6x²+8x'],
    hints: [
      { level: 'nudge', text: 'The $2x$ outside hands a snack to BOTH terms inside.' },
      { level: 'guide', text: '$2x \\times 3x = 6x^2$ (multiply numbers, multiply the $x$s).' },
      { level: 'reveal', text: '$2x \\times 3x = 6x^2$ and $2x \\times 4 = 8x$, so the answer is $6x^2 + 8x$.' },
    ],
    explanation: ['Distribute $2x$ to each term.', '$2x \\times 3x = 6x^2$ — the coefficients multiply and $x \\times x = x^2$.', '$2x \\times 4 = 8x$.', 'Answer: $6x^2 + 8x$.'],
    alternativeExplanations: [
      { title: 'Area picture', steps: ['Draw a rectangle 2x tall and (3x + 4) wide, cut into two patches.', 'Left patch: 2x by 3x, area 6x². Right patch: 2x by 4, area 8x.', 'Total: 6x² + 8x.'] },
      { title: 'Test a value', steps: ['Try x = 1: the original is 2(3 + 4) = 14.', 'The answer gives 6 + 8 = 14 — same number, so the distribution worked.'] },
    ],
    tags: ['polynomial', 'distribute'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 118, unit: 12, order: 8, slug: 'poly-binomial-x-coefficient',
    standard: 'A1.POLY.A.1', difficulty: 3,
    prompt: 'Multiply $(x + 5)(x + 2)$. What is the coefficient of the $x$ term in the result?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Use the area model: 4 patches. Two of them are $x$-patches.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try $(x + 1)(x + 2)$: the middle terms are $2x + 1x = 3x$. The x-coefficient is just the two numbers ADDED.' },
      { level: 'guide', text: 'The $x$-patches are $2 \\times x$ and $5 \\times x$. Add them.' },
      { level: 'reveal', text: '$2x + 5x = 7x$, so the coefficient is $7$.' },
    ],
    explanation: ['Expand: $(x + 5)(x + 2) = x^2 + 2x + 5x + 10$.', 'The $x$-terms combine: $2x + 5x = 7x$.', 'The coefficient of $x$ is $7$.'],
    alternativeExplanations: [
      { title: 'Garden patches', steps: ['A garden (x + 5) by (x + 2) splits into 4 patches: a square x by x, a 2-by-x strip, a 5-by-x strip, and a 5-by-2 corner.', 'The two strips are the x-terms: 2x and 5x, which is 7x together. Coefficient: 7.'] },
      { title: 'Shortcut for this pattern', steps: ['For (x + a)(x + b), the middle coefficient is always a + b.', 'Here a = 5 and b = 2, so the x coefficient is 5 + 2 = 7.'] },
    ],
    tags: ['polynomial', 'area-model'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 119, unit: 12, order: 9, slug: 'poly-bedrooms-total-area',
    standard: 'A1.POLY.A.1', difficulty: 3,
    prompt: 'One bedroom has floor area $x^2 + 6x$ square feet, and a second bedroom has $2x^2 + 3x$ square feet. Write the total floor area of both bedrooms.',
    answerType: 'expression', primaryAnswer: '3x^2 + 9x', acceptanceMode: 'normalized',
    alternativeAnswers: ['3x^2+9x', '3x² + 9x', '3x²+9x'],
    hints: [
      { level: 'nudge', text: 'Total means ADD the two areas: $(x^2 + 6x) + (2x^2 + 3x)$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Practice combining first: $x^2 + 2x^2 = 3x^2$. Only match x-squared with x-squared, and plain x with plain x.' },
      { level: 'guide', text: 'Sort by kind: $x^2$-terms together, $x$-terms together.' },
      { level: 'reveal', text: '$x^2 + 2x^2 = 3x^2$ and $6x + 3x = 9x$. Total: $3x^2 + 9x$.' },
    ],
    explanation: ['Add the two polynomials: $(x^2 + 6x) + (2x^2 + 3x)$.', '$x^2$-terms: $1x^2 + 2x^2 = 3x^2$.', '$x$-terms: $6x + 3x = 9x$.', 'Total area: $3x^2 + 9x$ square feet.'],
    alternativeExplanations: [
      { title: 'Two kinds of tiles', steps: ['Think of x²-tiles (big squares) and x-tiles (long strips) covering each floor.', 'Room one uses 1 big square and 6 strips; room two uses 2 big squares and 3 strips.', 'Together: 3 big squares and 9 strips — 3x² + 9x.'] },
      { title: 'Check with x = 10', steps: ['Room one: 100 + 60 = 160 sq ft. Room two: 200 + 30 = 230 sq ft. Total: 390.', 'Formula check: 3(100) + 9(10) = 300 + 90 = 390. It matches.'] },
    ],
    tags: ['polynomial', 'addition', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 120, unit: 12, order: 10, slug: 'poly-patio-minus-multiply',
    standard: 'A1.POLY.A.1', difficulty: 3,
    prompt: 'A patio is $(x + 5)$ meters long and $(x - 2)$ meters wide. Multiply to write its area.',
    answerType: 'expression', primaryAnswer: 'x^2 + 3x - 10', acceptanceMode: 'normalized',
    alternativeAnswers: ['x^2+3x-10', 'x² + 3x - 10', 'x²+3x-10'],
    hints: [
      { level: 'nudge', text: 'Same area model as before, but one edge piece is $-2$. Keep its sign!' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up with $(x + 2)(x - 1)$: that is $x^2 - x + 2x - 2 = x^2 + x - 2$. Multiply all four pairs, then combine.' },
      { level: 'guide', text: 'The 4 patches: $x^2$, $-2x$, $5x$, and $5 \\times (-2) = -10$.' },
      { level: 'reveal', text: '$x^2 - 2x + 5x - 10 = x^2 + 3x - 10$.' },
    ],
    explanation: ['Distribute twice: $(x + 5)(x - 2) = x(x - 2) + 5(x - 2)$.', 'That gives $x^2 - 2x + 5x - 10$.', 'Combine the middle terms: $-2x + 5x = 3x$.', 'Area: $x^2 + 3x - 10$ square meters.'],
    alternativeExplanations: [
      { title: 'Area model with a sign', steps: ['Split the rectangle into 4 patches, labeling the width pieces x and −2.', 'Patch areas: x², −2x, 5x, −10 — the negative pieces are area being trimmed off.', 'Add: x² + 3x − 10.'] },
      { title: 'Test with x = 4', steps: ['At x = 4 the patio is 9 m by 2 m, so the area is 18 square meters.', 'The formula: 16 + 12 − 10 = 18. The expansion is correct.'] },
    ],
    tags: ['polynomial', 'area-model', 'word-problem'], estimatedSeconds: 75,
  },

  // ---------------- UNIT 13 — Factoring ----------------
  {
    domain: 'A1', num: 121, unit: 13, order: 1, slug: 'factor-find-gcf',
    standard: 'A1.POLY.A.2', difficulty: 1,
    prompt: 'The two terms of $4x + 8$ share a greatest common factor. What is it?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'What is the biggest number that divides BOTH $4$ and $8$?' },
      { level: 'guide', text: '$4 = 4 \\times 1$ and $8 = 4 \\times 2$ — both terms hold a $4$.' },
      { level: 'reveal', text: 'The GCF is $4$.' },
    ],
    explanation: ['List what each term shares.', '$4x = 4 \\times x$ and $8 = 4 \\times 2$.', 'The biggest shared factor is $4$.'],
    alternativeExplanations: [
      { title: 'Equal gift bags', steps: ['You have 4 pencils and 8 erasers to split into identical bags with nothing left over.', 'The most bags you can make is 4 — each bag gets 1 pencil (an x) and 2 erasers.', 'That bag count IS the GCF: 4.'] },
      { title: 'Factor lists', steps: ['Factors of 4: 1, 2, 4. Factors of 8: 1, 2, 4, 8.', 'The largest number on both lists is 4.'] },
    ],
    tags: ['factoring', 'gcf'], estimatedSeconds: 25,
  },
  {
    domain: 'A1', num: 122, unit: 13, order: 2, slug: 'factor-gcf-simple',
    standard: 'A1.POLY.A.2', difficulty: 1,
    prompt: 'Factor: $5x + 10$.',
    answerType: 'expression', primaryAnswer: '5(x + 2)', acceptanceMode: 'normalized',
    alternativeAnswers: ['5(x+2)', '5 (x + 2)'],
    hints: [
      { level: 'nudge', text: 'Pull out what every term shares. What divides both $5x$ and $10$?' },
      { level: 'guide', text: 'The GCF is $5$. Write $5x + 10 = 5(\\;? + ?\\;)$ and fill the blanks.' },
      { level: 'reveal', text: '$5x + 10 = 5(x + 2)$.' },
    ],
    explanation: ['Both terms share a factor of $5$.', 'Pull it out: $5x = 5 \\times x$ and $10 = 5 \\times 2$.', 'Factored form: $5(x + 2)$.'],
    alternativeExplanations: [
      { title: 'Un-multiply it', steps: ['Factoring runs distribution backwards: you know the spread-out answer, find what was multiplied.', 'Ask: 5 times WHAT gives 5x + 10? Answer: (x + 2).', 'So 5x + 10 = 5(x + 2). Distribute to check!'] },
      { title: 'Area model backwards', steps: ['Picture a rectangle of area 5x + 10 with one side 5.', 'Split the area into 5x and 10; the other side must be x and 2.', 'The sides are 5 and (x + 2).'] },
    ],
    tags: ['factoring', 'gcf'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 123, unit: 13, order: 3, slug: 'factor-number-pair-hunt',
    standard: 'A1.POLY.A.2', difficulty: 1,
    prompt: 'Two numbers MULTIPLY to $12$ and ADD to $7$. What is the larger of the two numbers?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'List the pairs that multiply to $12$: $1 \\times 12$, $2 \\times 6$, $3 \\times 4$.' },
      { level: 'guide', text: 'Which pair adds to $7$? Check: $1 + 12 = 13$, $2 + 6 = 8$, $3 + 4 = ?$' },
      { level: 'reveal', text: '$3 + 4 = 7$, so the pair is $3$ and $4$. The larger is $4$.' },
    ],
    explanation: ['List factor pairs of 12: (1, 12), (2, 6), (3, 4).', 'Only $3 + 4 = 7$.', 'The larger number is $4$.'],
    alternativeExplanations: [
      { title: 'Why this hunt matters', steps: ['This is the exact search you use to factor x² + 7x + 12.', 'The pair 3 and 4 becomes (x + 3)(x + 4) — the number hunt IS factoring practice.'] },
      { title: 'Split 7 and test', steps: ['Break 7 into pairs: 1 + 6, 2 + 5, 3 + 4.', 'Multiply each: 6, 10, 12. Only 3 × 4 hits 12, so the numbers are 3 and 4.'] },
    ],
    tags: ['factoring', 'number-pairs'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 124, unit: 13, order: 4, slug: 'factor-trinomial-basic',
    standard: 'A1.POLY.A.2', difficulty: 2,
    prompt: 'Factor: $x^2 + 5x + 6$.',
    answerType: 'expression', primaryAnswer: '(x + 2)(x + 3)', acceptanceMode: 'normalized',
    alternativeAnswers: ['(x+2)(x+3)', '(x + 3)(x + 2)', '(x+3)(x+2)'],
    hints: [
      { level: 'nudge', text: 'Hunt for two numbers that MULTIPLY to $6$ and ADD to $5$.' },
      { level: 'guide', text: 'Pairs for $6$: $1 \\times 6$ and $2 \\times 3$. Which pair adds to $5$?' },
      { level: 'reveal', text: '$2 + 3 = 5$ and $2 \\times 3 = 6$, so $x^2 + 5x + 6 = (x + 2)(x + 3)$.' },
    ],
    explanation: ['Find two numbers that multiply to $6$ and add to $5$.', 'The pair is $2$ and $3$.', 'So $x^2 + 5x + 6 = (x + 2)(x + 3)$.', 'Check by expanding: $x^2 + 3x + 2x + 6$. It matches.'],
    alternativeExplanations: [
      { title: 'Run the area model backwards', steps: ['You know the garden area is x² + 5x + 6 — find the sides.', 'The x² patch forces both sides to start with x. The 6 corner splits as 2 × 3.', 'Only 2 and 3 also make the strips add to 5x, so the sides are (x + 2) and (x + 3).'] },
      { title: 'Guess and check', steps: ['Try (x + 1)(x + 6): expands to x² + 7x + 6. Middle term too big.', 'Try (x + 2)(x + 3): expands to x² + 5x + 6. That is the one.'] },
    ],
    tags: ['factoring', 'trinomial'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 125, unit: 13, order: 5, slug: 'factor-gift-bags-tickets',
    standard: 'A1.POLY.A.2', difficulty: 2,
    prompt: 'You have $6x + 12$ raffle tickets to split into identical gift bags with none left over. What is the GREATEST number of bags you can make?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The number of bags must divide BOTH terms: $6x$ and $12$.' },
      { level: 'guide', text: 'The greatest number that divides $6$ and $12$ is the GCF.' },
      { level: 'reveal', text: 'GCF of $6x$ and $12$ is $6$: you can make $6$ bags, each holding $x + 2$ tickets.' },
    ],
    explanation: ['Identical bags with none left over means each term must split evenly.', 'The GCF of $6x$ and $12$ is $6$.', 'Factored: $6x + 12 = 6(x + 2)$ — that is $6$ bags of $(x + 2)$ tickets each.'],
    alternativeExplanations: [
      { title: 'Test bag counts', steps: ['Could you make 12 bags? 12 divides 12, but 12 does not divide 6x evenly. No.', 'Could you make 6 bags? 6x ÷ 6 = x and 12 ÷ 6 = 2 — yes, each bag gets x + 2 tickets.', 'Nothing bigger works, so 6 is the greatest.'] },
      { title: 'See it with a real x', steps: ['Suppose x = 5, so you have 30 + 12 = 42 tickets.', 'With 6 bags, each holds 7 tickets — exactly x + 2 = 7. The GCF plan works for any x.'] },
    ],
    tags: ['factoring', 'gcf', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: 'A1', num: 126, unit: 13, order: 6, slug: 'factor-banner-other-side',
    standard: 'A1.POLY.A.2', difficulty: 2,
    prompt: 'A rectangular banner has area $x^2 + 7x + 12$ square feet. One side measures $(x + 3)$ feet. What is the length of the other side?',
    answerType: 'expression', primaryAnswer: 'x + 4', acceptanceMode: 'normalized',
    alternativeAnswers: ['x+4', '(x + 4)', '(x+4)'],
    hints: [
      { level: 'nudge', text: 'You know the area and one side — run the area model backwards to find the other side.' },
      { level: 'guide', text: 'Hunt for two numbers that multiply to $12$ and add to $7$. One of them is $3$.' },
      { level: 'reveal', text: '$3 \\times 4 = 12$ and $3 + 4 = 7$, so the area factors as $(x + 3)(x + 4)$. The other side is $x + 4$.' },
    ],
    explanation: ['Factor the area: find numbers multiplying to $12$, adding to $7$.', 'The pair is $3$ and $4$: $x^2 + 7x + 12 = (x + 3)(x + 4)$.', 'One side is $(x + 3)$, so the other side is $x + 4$ feet.'],
    alternativeExplanations: [
      { title: 'Un-multiply the area', steps: ['Area = side × side, so ask: (x + 3) times WHAT equals x² + 7x + 12?', 'The mystery side must start with x (to make x²) and end with 4 (since 3 × 4 = 12).', 'Check: (x + 3)(x + 4) = x² + 7x + 12. The other side is x + 4.'] },
      { title: 'Try a real banner', steps: ['Let x = 2: the area is 4 + 14 + 12 = 30 square feet, and the known side is 5 feet.', 'The other side must be 30 ÷ 5 = 6 feet — exactly x + 4 = 6. It fits.'] },
    ],
    tags: ['factoring', 'trinomial', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'A1', num: 127, unit: 13, order: 7, slug: 'factor-difference-squares',
    standard: 'A1.POLY.A.2', difficulty: 2,
    prompt: 'Factor: $x^2 - 25$.',
    answerType: 'expression', primaryAnswer: '(x + 5)(x - 5)', acceptanceMode: 'normalized',
    alternativeAnswers: ['(x+5)(x-5)', '(x - 5)(x + 5)', '(x-5)(x+5)'],
    hints: [
      { level: 'nudge', text: 'This is a DIFFERENCE of SQUARES: $x^2$ is a square, and $25 = 5^2$ is a square.' },
      { level: 'guide', text: 'The pattern: $a^2 - b^2 = (a + b)(a - b)$. Here $a = x$ and $b = 5$.' },
      { level: 'reveal', text: '$x^2 - 25 = (x + 5)(x - 5)$.' },
    ],
    explanation: ['Spot the pattern: both terms are perfect squares with a minus between them.', '$a^2 - b^2 = (a + b)(a - b)$ with $a = x$, $b = 5$.', 'So $x^2 - 25 = (x + 5)(x - 5)$.'],
    alternativeExplanations: [
      { title: 'Why the middle vanishes', steps: ['Expand (x + 5)(x − 5): the strips are +5x and −5x.', 'They are perfect opposites, so they cancel to zero.', 'Left over: x² − 25 — that is why the factored form has a plus AND a minus.'] },
      { title: 'Two-number hunt still works', steps: ['Think of x² − 25 as x² + 0x − 25: numbers multiplying to −25 and adding to 0.', 'That pair is 5 and −5, giving (x + 5)(x − 5).'] },
    ],
    tags: ['factoring', 'difference-of-squares'], estimatedSeconds: 50,
  },
  {
    domain: 'A1', num: 128, unit: 13, order: 8, slug: 'factor-negative-c',
    standard: 'A1.POLY.A.2', difficulty: 3,
    prompt: 'Factor: $x^2 - x - 6$.',
    answerType: 'expression', primaryAnswer: '(x - 3)(x + 2)', acceptanceMode: 'normalized',
    alternativeAnswers: ['(x-3)(x+2)', '(x + 2)(x - 3)', '(x+2)(x-3)'],
    hints: [
      { level: 'nudge', text: 'Hunt for two numbers that multiply to $-6$ and add to $-1$. One must be negative!' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Easier one: $x^2 + 5x + 6$ needs two numbers multiplying to $6$ and adding to $5$ — that is $2$ and $3$. Yours needs a NEGATIVE product.' },
      { level: 'guide', text: 'Try the pairs: $-6$ and $1$ add to $-5$. What about $-3$ and $2$?' },
      { level: 'reveal', text: '$-3 \\times 2 = -6$ and $-3 + 2 = -1$, so $x^2 - x - 6 = (x - 3)(x + 2)$.' },
    ],
    explanation: ['Need two numbers with product $-6$ and sum $-1$.', 'A negative product means one number is negative.', 'The pair $-3$ and $+2$ works: product $-6$, sum $-1$.', 'So $x^2 - x - 6 = (x - 3)(x + 2)$.'],
    alternativeExplanations: [
      { title: 'Sign detective', steps: ['Product negative → the two numbers have DIFFERENT signs.', 'Sum negative → the bigger-sized number wears the minus.', 'Pairs for 6: (1, 6) and (2, 3). Only −3 and +2 sum to −1.'] },
      { title: 'Check by expanding', steps: ['Expand (x − 3)(x + 2): x² + 2x − 3x − 6.', 'Combine: x² − x − 6. It matches the original, so the factoring is right.'] },
    ],
    tags: ['factoring', 'trinomial', 'signs'], estimatedSeconds: 70,
  },
  {
    domain: 'A1', num: 129, unit: 13, order: 9, slug: 'factor-garden-width',
    standard: 'A1.POLY.A.2', difficulty: 3,
    prompt: 'A community garden covers $x^2 + 9x + 18$ square meters. Its length is $(x + 6)$ meters. Factor to find its width.',
    answerType: 'expression', primaryAnswer: 'x + 3', acceptanceMode: 'normalized',
    alternativeAnswers: ['x+3', '(x + 3)', '(x+3)'],
    hints: [
      { level: 'nudge', text: 'You know the garden area — run the area model backwards to find the missing side.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Simpler: area $x^2 + 5x$ with length $x$ means width $x + 5$. Divide the area by the known side, or find the pair of numbers.' },
      { level: 'guide', text: 'Two numbers that multiply to $18$ and add to $9$: one is $6$, the other is...?' },
      { level: 'reveal', text: '$6 \\times 3 = 18$ and $6 + 3 = 9$, so the area is $(x + 6)(x + 3)$. Width: $x + 3$.' },
    ],
    explanation: ['Factor the area: numbers multiplying to $18$, adding to $9$.', 'The pair is $6$ and $3$: $x^2 + 9x + 18 = (x + 6)(x + 3)$.', 'The length is $(x + 6)$, so the width is $x + 3$ meters.'],
    alternativeExplanations: [
      { title: 'Un-multiply', steps: ['Ask: (x + 6) times WHAT gives x² + 9x + 18?', 'It must start with x (for the x²) and end with 18 ÷ 6 = 3.', 'Check: (x + 6)(x + 3) = x² + 9x + 18. Width: x + 3.'] },
      { title: 'Plug in a value', steps: ['Let x = 4: the area is 16 + 36 + 18 = 70 square meters and the length is 10 m.', 'Width = 70 ÷ 10 = 7 m, which is exactly x + 3 = 7.'] },
    ],
    tags: ['factoring', 'trinomial', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'A1', num: 130, unit: 13, order: 10, slug: 'factor-photo-cutout',
    standard: 'A1.POLY.A.2', difficulty: 3,
    prompt: 'A square poster with side $x$ has a square photo of side $4$ cut out of it. The leftover area is $x^2 - 16$, which factors as $(x + a)(x - a)$. What is $a$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'This is a difference of squares: $x^2 - 16 = x^2 - (\\;?\\;)^2$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try numbers: $x = 10$ gives $100 - 16 = 84$, and $(10 + 4)(10 - 4) = 14 \\times 6 = 84$. Difference of squares always splits like this.' },
      { level: 'guide', text: 'What number squared gives $16$?' },
      { level: 'reveal', text: '$4^2 = 16$, so $x^2 - 16 = (x + 4)(x - 4)$ and $a = 4$.' },
    ],
    explanation: ['Write $16$ as a square: $16 = 4^2$.', 'Difference of squares: $x^2 - 4^2 = (x + 4)(x - 4)$.', 'So $a = 4$.'],
    alternativeExplanations: [
      { title: 'Scissors-and-tape picture', steps: ['Cut the 4-by-4 photo hole out of the x-by-x poster and snip the leftover L-shape into two pieces.', 'Slide the pieces into one rectangle: it measures (x + 4) by (x − 4).', 'The rectangle sides show a = 4.'] },
      { title: 'Check by expanding', steps: ['Expand (x + 4)(x − 4): x² − 4x + 4x − 16 = x² − 16.', 'The middle terms cancel, and the match confirms a = 4.'] },
    ],
    tags: ['factoring', 'difference-of-squares', 'word-problem'], estimatedSeconds: 70,
  },

  // ---------------- UNIT 14 — Quadratics ----------------
  {
    domain: 'A1', num: 131, unit: 14, order: 1, slug: 'quad-plug-into-parabola',
    standard: 'A1.QUAD.A.1', difficulty: 1,
    prompt: 'The parabola $y = x^2$ makes a U shape. What is $y$ when $x = 3$?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $3$ for $x$ in $y = x^2$.' },
      { level: 'guide', text: '$y = 3^2$ means $3 \\times 3$.' },
      { level: 'reveal', text: '$y = 9$.' },
    ],
    explanation: ['Substitute: $y = 3^2$.', '$3 \\times 3 = 9$.', 'So $y = 9$.'],
    alternativeExplanations: [
      { title: 'Read it off a table', steps: ['Build a quick table for y = x²: x = 0, 1, 2, 3 gives y = 0, 1, 4, 9.', 'The y-values climb faster and faster — that is the U shape. At x = 3, y = 9.'] },
      { title: 'A square floor', steps: ['y = x² is the area of a square floor with side x.', 'A 3-by-3 floor holds 9 tiles, so y = 9.'] },
    ],
    tags: ['quadratic', 'parabola'], estimatedSeconds: 25,
  },
  {
    domain: 'A1', num: 132, unit: 14, order: 2, slug: 'quad-square-root-25',
    standard: 'A1.QUAD.A.1', difficulty: 1,
    prompt: 'Solve $x^2 = 25$. Give the POSITIVE solution.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'What number times itself gives $25$?' },
      { level: 'guide', text: 'Both $5 \\times 5$ and $(-5) \\times (-5)$ equal $25$.' },
      { level: 'reveal', text: 'The positive solution is $x = 5$.' },
    ],
    explanation: ['Ask: what squared gives 25?', '$5^2 = 25$ and $(-5)^2 = 25$ — squares have TWO roots.', 'The positive one is $x = 5$.'],
    alternativeExplanations: [
      { title: 'As a square garden', steps: ['A square garden has area 25 square meters. Each side is the number that multiplies by itself to give 25.', 'Side length: 5 meters — lengths are positive, so the garden answer is the positive root.'] },
      { title: 'Undo the square', steps: ['Squaring and square-rooting undo each other, like tying and untying a shoe.', '√25 = 5, and its mirror twin −5 also works since a negative times a negative is positive.'] },
    ],
    tags: ['quadratic', 'square-root'], estimatedSeconds: 35,
  },
  {
    domain: 'A1', num: 133, unit: 14, order: 3, slug: 'quad-negative-input',
    standard: 'A1.QUAD.A.1', difficulty: 1,
    prompt: 'For the parabola $y = x^2$, what is $y$ when $x = -4$?',
    answerType: 'numeric', primaryAnswer: '16', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Squaring means the number times ITSELF: $(-4) \\times (-4)$.' },
      { level: 'guide', text: 'A negative times a negative is positive.' },
      { level: 'reveal', text: '$(-4)^2 = 16$, so $y = 16$.' },
    ],
    explanation: ['Substitute: $y = (-4)^2 = (-4) \\times (-4)$.', 'Negative times negative is positive: $16$.', 'So $y = 16$ — same as $x = 4$. That is why the U is symmetric.'],
    alternativeExplanations: [
      { title: 'Mirror twins on the U', steps: ['On the parabola, x = 4 and x = −4 sit at the same height, like mirror twins.', 'Since 4² = 16, the twin −4 also lands at y = 16.'] },
      { title: 'Table of values', steps: ['Fill a table: x = −4, −2, 0, 2, 4 gives y = 16, 4, 0, 4, 16.', 'The left side copies the right side — read off y = 16 at x = −4.'] },
    ],
    tags: ['quadratic', 'parabola', 'negatives'], estimatedSeconds: 30,
  },
  {
    domain: 'A1', num: 134, unit: 14, order: 4, slug: 'quad-zero-product',
    standard: 'A1.QUAD.A.1', difficulty: 2,
    prompt: 'Solve $(x - 3)(x + 5) = 0$. Give the POSITIVE solution.',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Zero-product rule: if two things multiply to zero, one of them IS zero.' },
      { level: 'guide', text: 'Either $x - 3 = 0$ or $x + 5 = 0$. Solve each little equation.' },
      { level: 'reveal', text: '$x = 3$ or $x = -5$. The positive solution is $3$.' },
    ],
    explanation: ['If a product is zero, one factor must be zero.', 'Set each factor to zero: $x - 3 = 0$ gives $x = 3$; $x + 5 = 0$ gives $x = -5$.', 'The positive solution is $x = 3$.'],
    alternativeExplanations: [
      { title: 'Why zero is special', steps: ['Multiply any two nonzero numbers — you never get zero. Try it: 2 × 3, 0.5 × (−8)...', 'So if the product IS zero, at least one factor must secretly be zero.', 'Here that means x = 3 or x = −5; the positive one is 3.'] },
      { title: 'Check by plugging in', steps: ['Try x = 3: (3 − 3)(3 + 5) = 0 × 8 = 0. Works.', 'Try x = −5: (−8)(0) = 0. Also works — but the positive answer asked for is 3.'] },
    ],
    tags: ['quadratic', 'zero-product'], estimatedSeconds: 45,
  },
  {
    domain: 'A1', num: 135, unit: 14, order: 5, slug: 'quad-solve-by-factoring',
    standard: 'A1.QUAD.A.1', difficulty: 2,
    prompt: 'Solve $x^2 - 5x + 6 = 0$ by factoring. Give the LARGER solution.',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First factor: two numbers that multiply to $6$ and add to $-5$.' },
      { level: 'guide', text: 'The pair is $-2$ and $-3$: so $(x - 2)(x - 3) = 0$. Now use the zero-product rule.' },
      { level: 'reveal', text: '$x = 2$ or $x = 3$. The larger solution is $3$.' },
    ],
    explanation: ['Factor: numbers with product $6$ and sum $-5$ are $-2$ and $-3$.', 'So $(x - 2)(x - 3) = 0$.', 'Zero-product rule: $x = 2$ or $x = 3$.', 'The larger solution is $3$.'],
    alternativeExplanations: [
      { title: 'Table of values', steps: ['Compute x² − 5x + 6 for x = 1, 2, 3, 4: you get 2, 0, 0, 2.', 'It hits zero at x = 2 and x = 3 — those are the solutions, and 3 is larger.'] },
      { title: 'Where the U crosses the floor', steps: ['The graph of y = x² − 5x + 6 is a U. Solving = 0 asks where the U touches the x-axis floor.', 'The U dips down and crosses at x = 2 and x = 3, so the larger crossing is 3.'] },
    ],
    tags: ['quadratic', 'factoring', 'zero-product'], estimatedSeconds: 60,
  },
  {
    domain: 'A1', num: 136, unit: 14, order: 6, slug: 'quad-ball-drop-time',
    standard: 'A1.QUAD.A.1', difficulty: 2,
    prompt: 'A ball is dropped from a balcony. Its height in meters after $t$ seconds is $h = 45 - 5t^2$. After how many seconds does it hit the ground ($h = 0$)?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Hitting the ground means $h = 0$: solve $45 - 5t^2 = 0$.' },
      { level: 'guide', text: 'Move and divide: $5t^2 = 45$, so $t^2 = 9$.' },
      { level: 'reveal', text: '$t^2 = 9$ gives $t = 3$ (time can\'t be negative). It lands after $3$ seconds.' },
    ],
    explanation: ['Set the height to zero: $45 - 5t^2 = 0$.', 'Add $5t^2$ to both sides: $45 = 5t^2$.', 'Divide by 5: $t^2 = 9$, so $t = 3$ or $t = -3$.', 'Time must be positive: the ball lands after $3$ seconds.'],
    alternativeExplanations: [
      { title: 'Second-by-second table', steps: ['t = 0: h = 45. t = 1: h = 45 − 5 = 40. t = 2: h = 45 − 20 = 25.', 't = 3: h = 45 − 45 = 0 — the ball reaches the ground at 3 seconds.', 'Notice it falls faster each second: that is the parabola at work.'] },
      { title: 'Two roots, one real landing', steps: ['t² = 9 has two answers, 3 and −3 — every square does.', 'But t = −3 would mean 3 seconds BEFORE the drop, which makes no sense here.', 'Keep the positive root: 3 seconds.'] },
    ],
    tags: ['quadratic', 'projectile', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'A1', num: 137, unit: 14, order: 7, slug: 'quad-fountain-landing',
    standard: 'A1.QUAD.A.1', difficulty: 2,
    prompt: 'A water fountain jet follows $h = 20t - 5t^2$, where $h$ is the water\'s height in meters after $t$ seconds. For what positive $t$ does the water land back at $h = 0$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set $h = 0$ and pull out the GCF: $20t - 5t^2 = 5t(4 - t)$.' },
      { level: 'guide', text: 'Zero-product rule on $5t(4 - t) = 0$: either $t = 0$ or $4 - t = 0$.' },
      { level: 'reveal', text: '$t = 0$ is the launch; the landing is $t = 4$ seconds.' },
    ],
    explanation: ['Set the height to zero: $20t - 5t^2 = 0$.', 'Factor out the GCF: $5t(4 - t) = 0$.', 'Zero-product rule: $t = 0$ or $t = 4$.', '$t = 0$ is when the water leaves the spout; it lands at $t = 4$ seconds.'],
    alternativeExplanations: [
      { title: 'Watch the arc in a table', steps: ['t = 0: h = 0 (launch). t = 1: h = 15. t = 2: h = 20 (top). t = 3: h = 15. t = 4: h = 0.', 'The water rises, peaks, and mirrors back down — landing at t = 4.'] },
      { title: 'Symmetry of the arc', steps: ['A parabola\'s arc is symmetric, like a rainbow: up-time equals down-time.', 'The peak is at t = 2, so the landing is the mirror of the launch: 2 + 2 = 4 seconds.'] },
    ],
    tags: ['quadratic', 'zero-product', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'A1', num: 138, unit: 14, order: 8, slug: 'quad-basketball-vertex',
    standard: 'A1.QUAD.A.1', difficulty: 3,
    prompt: 'A basketball\'s arc follows $h = 9 - (t - 2)^2$, with $h$ in feet and $t$ in seconds. The vertex is the arc\'s highest point. What is the MAXIMUM height, in feet?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A square like $(t - 2)^2$ is never negative — its smallest value is $0$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Read the vertex form: in $h = 9 - (t - 2)^2$, the squared part is never negative, so the biggest $h$ happens when it equals $0$.' },
      { level: 'guide', text: '$h$ is biggest when you subtract the LEAST. When does $(t - 2)^2 = 0$?' },
      { level: 'reveal', text: 'At $t = 2$ the square is $0$, so $h = 9 - 0 = 9$ feet — the maximum.' },
    ],
    explanation: ['$(t - 2)^2$ is a square, so it is always $0$ or more.', '$h = 9$ minus that square, so $h$ peaks when the square is $0$.', 'That happens at $t = 2$: maximum height $= 9 - 0 = 9$ feet.'],
    alternativeExplanations: [
      { title: 'Test times around the peak', steps: ['t = 1: h = 9 − 1 = 8. t = 2: h = 9 − 0 = 9. t = 3: h = 9 − 1 = 8.', 'Heights rise to 9 and fall back — the vertex of the arc is 9 feet.'] },
      { title: 'Read the vertex form', steps: ['h = 9 − (t − 2)² says: start at the peak height 9, then subtract a penalty for being away from t = 2.', 'Zero penalty at t = 2, so the highest point of the ball\'s flight is 9 feet.'] },
    ],
    tags: ['quadratic', 'vertex', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'A1', num: 139, unit: 14, order: 9, slug: 'quad-factor-solve-positive',
    standard: 'A1.QUAD.A.1', difficulty: 3,
    prompt: 'Solve $x^2 - 2x - 15 = 0$ by factoring. Give the POSITIVE solution.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two numbers that multiply to $-15$ and add to $-2$. Different signs!' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Easier factor: $x^2 - x - 6 = (x - 3)(x + 2)$ gives $x = 3$ or $x = -2$. Find two numbers with the right product and sum.' },
      { level: 'guide', text: 'The pair is $-5$ and $+3$: $(x - 5)(x + 3) = 0$. Now zero-product.' },
      { level: 'reveal', text: '$x = 5$ or $x = -3$. The positive solution is $5$.' },
    ],
    explanation: ['Hunt: product $-15$, sum $-2$. The pair is $-5$ and $3$.', 'Factor: $(x - 5)(x + 3) = 0$.', 'Zero-product rule: $x = 5$ or $x = -3$.', 'The positive solution is $5$.'],
    alternativeExplanations: [
      { title: 'Sign detective', steps: ['Product −15 is negative, so the two numbers have different signs.', 'Sum −2 is negative, so the bigger-sized number is negative: −5 with +3.', 'Factors (x − 5)(x + 3) give x = 5 as the positive root.'] },
      { title: 'Check both candidates', steps: ['Plug in x = 5: 25 − 10 − 15 = 0. Yes.', 'Plug in x = −3: 9 + 6 − 15 = 0. Also yes — two roots, and the positive one is 5.'] },
    ],
    tags: ['quadratic', 'factoring', 'zero-product'], estimatedSeconds: 75,
  },
  {
    domain: 'A1', num: 140, unit: 14, order: 10, slug: 'quad-trampoline-max-height',
    standard: 'A1.QUAD.A.1', difficulty: 3,
    prompt: 'A trampoline bounce follows $h = 30t - 5t^2$, with $h$ in centimeters above the mat after $t$ seconds. Using the arc\'s symmetry, find the MAXIMUM height, in centimeters.',
    answerType: 'numeric', primaryAnswer: '45', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find the landing: factor $5t(6 - t) = 0$, so $h = 0$ at $t = 0$ and $t = 6$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Test a time: at $t = 2$, $h = 60 - 20 = 40$ cm. To find when it lands, ask when $h$ returns to $0$ and factor out the $t$.' },
      { level: 'guide', text: 'The peak sits halfway between takeoff and landing: $t = 3$. Now compute $h$ there.' },
      { level: 'reveal', text: '$h = 30 \\times 3 - 5 \\times 9 = 90 - 45 = 45$ centimeters.' },
    ],
    explanation: ['Factor to find the ground times: $30t - 5t^2 = 5t(6 - t) = 0$, so $t = 0$ or $t = 6$.', 'A parabola is symmetric, so the vertex is halfway: $t = 3$.', 'Height there: $h = 30(3) - 5(3)^2 = 90 - 45 = 45$.', 'Maximum height: $45$ centimeters.'],
    alternativeExplanations: [
      { title: 'Table of the bounce', steps: ['t = 0: h = 0. t = 1: h = 25. t = 2: h = 40. t = 3: h = 45. t = 4: h = 40.', 'The heights climb, peak at 45, then mirror back down — the max is 45 cm.'] },
      { title: 'Rainbow symmetry', steps: ['The bounce arc is a rainbow: up-time equals down-time.', 'In the air from t = 0 to t = 6, so the top is at t = 3.', 'Plug in t = 3: 90 − 45 = 45 cm at the very top.'] },
    ],
    tags: ['quadratic', 'vertex', 'word-problem'], estimatedSeconds: 90,
  },
];
