import type { SeedProblem } from './types';

// Precalculus — Units 9–11: the unit circle & radians, graphing sine and
// cosine, and trig identities & equations. Nums 81–110, 10 problems per unit,
// difficulty ramp 1-1-1-2-2-2-2-3-3-3 within each unit. Difficulty-3 problems
// carry a fourth, titled "try a simpler one" nudge.
export const problemsPCu09: SeedProblem[] = [
  // ---------------- Unit 9 — The unit circle & radians (PC.TRIG.A.2) ----------------
  {
    domain: 'PC', num: 81, unit: 9, order: 1, slug: 'unit-circle-cos-zero-degrees',
    standard: 'PC.TRIG.A.2', difficulty: 1,
    prompt: 'On the unit circle, the angle $0^\\circ$ lands on the point $(1, 0)$. Cosine is the SHADOW ACROSS. What is $\\cos 0^\\circ$?',
    answerType: 'numeric', primaryAnswer: '1', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Cosine is the FIRST number in the point $(x, y)$ — how far across you are.' },
      { level: 'guide', text: 'The point at $0^\\circ$ is $(1, 0)$, so the across number is $1$.' },
      { level: 'reveal', text: '$\\cos 0^\\circ = 1$.' },
    ],
    explanation: ['The unit circle is a circle of radius $1$ centred at the origin.', 'Every angle names one point on it, and that point is always $(\\cos\\theta, \\sin\\theta)$ — cosine is the shadow ACROSS, sine is the height UP.', 'At $0^\\circ$ you sit at the far right edge, the point $(1, 0)$, so $\\cos 0^\\circ = 1$.'],
    alternativeExplanations: [
      { title: 'Picture the clock hand', steps: ['Point a hand of length 1 straight to the right, like a clock hand aimed at 3 o\'clock. That is the 0° direction.', 'Its tip is 1 unit across and 0 units up. The across number IS the cosine, so cos 0° = 1.'] },
      { title: 'The radius is the ruler', steps: ['The circle has radius 1, so the tip of the hand is never more than 1 unit from the centre.', 'At 0° the hand lies flat along the across-direction, spending ALL of its length going across. Across = 1, up = 0.'] },
    ],
    tags: ['unit-circle', 'cosine'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 82, unit: 9, order: 2, slug: 'unit-circle-sin-ninety-degrees',
    standard: 'PC.TRIG.A.2', difficulty: 1,
    prompt: 'On the unit circle, the angle $90^\\circ$ lands on the point $(0, 1)$. Sine is the HEIGHT UP. What is $\\sin 90^\\circ$?',
    answerType: 'numeric', primaryAnswer: '1', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sine is the SECOND number in the point $(x, y)$ — how high up you are.' },
      { level: 'guide', text: 'The point at $90^\\circ$ is $(0, 1)$, so the height is $1$.' },
      { level: 'reveal', text: '$\\sin 90^\\circ = 1$.' },
    ],
    explanation: ['A quarter turn from the right edge takes you straight to the top of the circle.', 'The top point is $(0, 1)$: zero across, one unit up.', 'Sine reads the height, so $\\sin 90^\\circ = 1$. This is the biggest sine can ever be.'],
    alternativeExplanations: [
      { title: 'Picture the clock hand', steps: ['Aim a hand of length 1 straight UP, like a clock hand at 12. That is the 90° direction.', 'The tip is 0 units across and 1 unit up. The up number IS the sine, so sin 90° = 1.'] },
      { title: 'Sine can never beat 1', steps: ['The circle has radius 1, so no point on it is more than 1 unit above the centre.', 'The very top is exactly 1 unit up, and you reach it at 90°. So sin 90° = 1 is the ceiling for sine.'] },
    ],
    tags: ['unit-circle', 'sine'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 83, unit: 9, order: 3, slug: 'clock-hand-quarter-turn-degrees',
    standard: 'PC.TRIG.A.2', difficulty: 1,
    prompt: 'A clock hand points at the 12. It sweeps around to the 3. That is a QUARTER of a full turn. How many degrees did it turn?',
    answerType: 'numeric', primaryAnswer: '90', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A full turn all the way around is $360^\\circ$.' },
      { level: 'guide', text: 'A quarter of a full turn is $360 \\div 4$.' },
      { level: 'reveal', text: '$360 \\div 4 = 90$, so the hand turned $90^\\circ$.' },
    ],
    explanation: ['One trip all the way around a circle is $360^\\circ$.', 'Twelve to three is one quarter of the way around the clock face.', '$360 \\div 4 = 90$, so the hand swept $90^\\circ$ — a right angle.'],
    alternativeExplanations: [
      { title: 'Count the hour marks', steps: ['The clock face has 12 hour marks, and the whole face is 360°.', 'So each hour mark is 360 ÷ 12 = 30°. From 12 to 3 is 3 marks: 3 × 30 = 90°.'] },
      { title: 'Fold the circle in half, then half again', steps: ['Half a turn is 180° — that would land the hand on the 6.', 'Half of THAT is 90°, which lands on the 3. So a quarter turn is 90°.'] },
    ],
    tags: ['degrees', 'word-problem'], estimatedSeconds: 35,
  },
  {
    domain: 'PC', num: 84, unit: 9, order: 4, slug: 'radians-half-turn-to-degrees',
    standard: 'PC.TRIG.A.2', difficulty: 2,
    prompt: 'Radians measure an angle by the ARC LENGTH you walk around the unit circle. Half a turn is $\\pi$ radians. How many degrees is $\\pi$ radians?',
    answerType: 'numeric', primaryAnswer: '180', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Half of a full turn. A full turn is $360^\\circ$.' },
      { level: 'guide', text: 'Half of $360^\\circ$ is $360 \\div 2$.' },
      { level: 'reveal', text: '$\\pi$ radians $= 180^\\circ$. This is the swap rule you will use again and again.' },
    ],
    explanation: ['Walking all the way around a circle of radius $1$ covers an arc of $2\\pi$, so a full turn is $2\\pi$ radians.', 'Half of that walk is $\\pi$ radians, and half of a full turn is $360 \\div 2 = 180^\\circ$.', 'So $\\pi$ radians $= 180^\\circ$. Radians and degrees are two rulers measuring the same turn.'],
    alternativeExplanations: [
      { title: 'Two rulers, one turn', steps: ['Think of measuring a table in inches or centimetres. Same table, two numbers.', 'Degrees chop a full turn into 360 pieces. Radians measure the same turn by arc length: 2π all the way round, so π is halfway = 180°.'] },
      { title: 'Walk it out', steps: ['Start at the far right of the unit circle and walk counter-clockwise along the rim.', 'When you have walked an arc of length π you are at the far LEFT — directly opposite where you started. Opposite means half a turn, which is 180°.'] },
    ],
    tags: ['radians', 'degrees'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 85, unit: 9, order: 5, slug: 'radians-pi-over-three-to-degrees',
    standard: 'PC.TRIG.A.2', difficulty: 2,
    prompt: 'How many degrees is $\\frac{\\pi}{3}$ radians?',
    answerType: 'numeric', primaryAnswer: '60', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Start from the swap rule: $\\pi$ radians $= 180^\\circ$.' },
      { level: 'guide', text: '$\\frac{\\pi}{3}$ is one third of $\\pi$, so take one third of $180^\\circ$.' },
      { level: 'reveal', text: '$180 \\div 3 = 60$, so $\\frac{\\pi}{3}$ radians $= 60^\\circ$.' },
    ],
    explanation: ['The swap rule is $\\pi$ radians $= 180^\\circ$.', '$\\frac{\\pi}{3}$ means $\\pi$ cut into 3 equal pieces, so cut $180^\\circ$ into 3 equal pieces too.', '$180 \\div 3 = 60$. So $\\frac{\\pi}{3}$ radians $= 60^\\circ$.'],
    alternativeExplanations: [
      { title: 'Swap π for 180 and simplify', steps: ['Wherever you see π, write 180° instead. So π/3 becomes 180°/3.', '180 ÷ 3 = 60. The answer is 60°.'] },
      { title: 'Build a quick table', steps: ['π = 180°, so π/2 = 90°, π/3 = 60°, π/4 = 45°, π/6 = 30°.', 'The bigger the number under π, the smaller the slice. π/3 sits at 60° — one of the exact-value angles.'] },
    ],
    tags: ['radians', 'degrees'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 86, unit: 9, order: 6, slug: 'bike-valve-full-turn-radians',
    standard: 'PC.TRIG.A.2', difficulty: 2,
    prompt: 'The valve on your bike wheel rolls all the way around exactly once. In radians, one full turn is $n\\pi$ radians. What is $n$?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Half a turn is $\\pi$ radians. A full turn is two halves.' },
      { level: 'guide', text: 'Two halves means $\\pi + \\pi = 2\\pi$ radians.' },
      { level: 'reveal', text: 'A full turn is $2\\pi$ radians, so $n = 2$.' },
    ],
    explanation: ['Radians measure a turn by how far you walk around the rim of a circle of radius $1$.', 'The whole rim has length $2\\pi$ (that is what circumference $= 2\\pi r$ says when $r = 1$).', 'So one full turn is $2\\pi$ radians and $n = 2$. Check with degrees: $2 \\times 180 = 360^\\circ$. ✓'],
    alternativeExplanations: [
      { title: 'Two half turns', steps: ['The valve goes from the top, down to the bottom — that is half a turn, or π radians.', 'Then bottom back to top — another π. Together π + π = 2π radians.'] },
      { title: 'Use the circumference formula', steps: ['Rolling once means the valve travels the whole rim: circumference = 2 × π × r.', 'On the unit circle r = 1, so the trip is 2π. Radians ARE that arc length, so one turn = 2π.'] },
    ],
    tags: ['radians', 'word-problem'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 87, unit: 9, order: 7, slug: 'quadrant-cos-negative-sin-positive',
    standard: 'PC.TRIG.A.2', difficulty: 2,
    prompt: 'In which quadrant is the cosine (across) NEGATIVE while the sine (up) is POSITIVE? Answer with the quadrant number.',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Negative across means LEFT of centre. Positive up means ABOVE centre.' },
      { level: 'guide', text: 'Left and above is the top-left corner of the circle. Quadrants are numbered counter-clockwise starting from the top-right.' },
      { level: 'reveal', text: 'Top-left is Quadrant $2$ (angles from $90^\\circ$ to $180^\\circ$).' },
    ],
    explanation: ['Cosine is the across number, so cosine is negative when you are to the LEFT of the centre.', 'Sine is the up number, so sine is positive when you are ABOVE the centre.', 'Left and above is the top-left corner — Quadrant $2$, covering $90^\\circ$ to $180^\\circ$.'],
    alternativeExplanations: [
      { title: 'Test one angle', steps: ['Try 120°, which lands in the top-left. Its point is about (−0.5, 0.87).', 'The across number is negative and the up number is positive. That angle is in Quadrant 2.'] },
      { title: 'Map the four corners', steps: ['Q1 top-right: across +, up +. Q2 top-left: across −, up +.', 'Q3 bottom-left: across −, up −. Q4 bottom-right: across +, up −. Only Q2 has minus-then-plus.'] },
    ],
    tags: ['unit-circle', 'quadrants'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 88, unit: 9, order: 8, slug: 'sin-thirty-as-unit-fraction',
    standard: 'PC.TRIG.A.2', difficulty: 3,
    prompt: 'One of the exact-value angles: $\\sin 30^\\circ = \\frac{1}{n}$. What is $n$?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$\\sin 30^\\circ$ is the HEIGHT of the point at $30^\\circ$ on the unit circle. It is exactly half of the radius.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up with $\\sin 90^\\circ$: the point is $(0, 1)$, so the height is $1$. Now ask the same question at $30^\\circ$ — is that height bigger or smaller than $1$? It turns out to be exactly half.' },
      { level: 'guide', text: 'Half of $1$ is $\\frac{1}{2}$, so $\\sin 30^\\circ = \\frac{1}{2}$.' },
      { level: 'reveal', text: 'The denominator is $2$, so $n = 2$.' },
    ],
    explanation: ['The point at $30^\\circ$ on the unit circle is $\\left(\\frac{\\sqrt{3}}{2}, \\frac{1}{2}\\right)$.', 'Sine reads the height, which is $\\frac{1}{2}$ — exactly half the radius.', 'Written as $\\frac{1}{n}$, that makes $n = 2$.'],
    alternativeExplanations: [
      { title: 'The half-equilateral triangle', steps: ['Draw an equilateral triangle with sides of length 1. Every angle is 60°.', 'Slice it down the middle. The half is a right triangle with a 30° angle, a long side of 1, and a short side of exactly 1/2 — because the slice cut a side of length 1 in half.', 'That short side is the height at 30°, so sin 30° = 1/2.'] },
      { title: 'Sanity-check the size', steps: ['Sine is a height on a circle of radius 1, so it always sits between 0 and 1 in the top half.', '30° is only a third of the way to the top (90°), so the height should be small. 1/2 = 0.5 fits; 1/3 or 1/4 would be too low for 30°.'] },
    ],
    tags: ['unit-circle', 'exact-values'], estimatedSeconds: 60,
  },
  {
    domain: 'PC', num: 89, unit: 9, order: 9, slug: 'ferris-wheel-seat-height-quarter-turn',
    standard: 'PC.TRIG.A.2', difficulty: 3,
    prompt: 'A Ferris wheel has radius $15$ m and its centre sits $20$ m above the ground. A seat starts at the far right of the wheel and turns $90^\\circ$. How many metres above the ground is the seat now?',
    answerType: 'numeric', primaryAnswer: '35', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Height above ground $=$ centre height $+$ radius $\\times \\sin\\theta$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try the same wheel at $\\theta = 0^\\circ$ first. $\\sin 0^\\circ = 0$, so the seat is $20 + 15 \\times 0 = 20$ m — level with the centre. Now redo it with $\\sin 90^\\circ$.' },
      { level: 'guide', text: '$\\sin 90^\\circ = 1$, so the height is $20 + 15 \\times 1$.' },
      { level: 'reveal', text: '$20 + 15 = 35$ metres.' },
    ],
    explanation: ['Put the centre of the wheel at the middle of a unit-circle picture. The seat rides the rim.', 'Its height above the centre is radius $\\times \\sin\\theta = 15\\sin\\theta$, and the centre itself is $20$ m up.', 'At $\\theta = 90^\\circ$, $\\sin 90^\\circ = 1$, so the height is $20 + 15 \\times 1 = 35$ m.'],
    alternativeExplanations: [
      { title: 'No formula — just picture it', steps: ['A quarter turn from the far right puts the seat at the very TOP of the wheel.', 'The top is one radius above the centre: 20 + 15 = 35 m above the ground.'] },
      { title: 'Highest and lowest first', steps: ['The seat can never go above 20 + 15 = 35 m or below 20 − 15 = 5 m.', 'A 90° turn from the side reaches the peak, and the peak is 35 m.'] },
    ],
    tags: ['unit-circle', 'sine', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'PC', num: 90, unit: 9, order: 10, slug: 'game-character-facing-three-hundred',
    standard: 'PC.TRIG.A.2', difficulty: 3,
    prompt: 'A game character faces $300^\\circ$, measured counter-clockwise from due east. Which quadrant is that facing direction in? Answer with the quadrant number.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The quadrant boundaries are $90^\\circ$, $180^\\circ$, $270^\\circ$ and $360^\\circ$. Which two does $300^\\circ$ sit between?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try $200^\\circ$ first: it sits between $180^\\circ$ and $270^\\circ$, so it is in Quadrant $3$. Now do the same sorting for $300^\\circ$.' },
      { level: 'guide', text: '$300^\\circ$ is between $270^\\circ$ and $360^\\circ$ — the bottom-right slice.' },
      { level: 'reveal', text: 'Bottom-right is Quadrant $4$, so the answer is $4$.' },
    ],
    explanation: ['Quadrants are counted counter-clockwise from due east: Q1 is $0^\\circ$–$90^\\circ$, Q2 is $90^\\circ$–$180^\\circ$, Q3 is $180^\\circ$–$270^\\circ$, Q4 is $270^\\circ$–$360^\\circ$.', '$300^\\circ$ lands between $270^\\circ$ and $360^\\circ$.', 'So the character faces into Quadrant $4$ — down and to the right. There $\\cos$ is positive and $\\sin$ is negative.'],
    alternativeExplanations: [
      { title: 'Back up from a full turn', steps: ['A full turn is 360°. Facing 300° is the same as being 60° short of all the way around.', 'Sixty degrees short of due east means aimed slightly downward and to the right — the bottom-right corner, Quadrant 4.'] },
      { title: 'Check the signs of the point', steps: ['At 300° the character is right of centre and below it, so the point is (positive, negative).', 'Across positive with up negative only happens in Quadrant 4.'] },
    ],
    tags: ['unit-circle', 'quadrants', 'word-problem'], estimatedSeconds: 65,
  },

  // ---------------- Unit 10 — Graphing sine & cosine (PC.TRIG.B.1) ----------------
  {
    domain: 'PC', num: 91, unit: 10, order: 1, slug: 'amplitude-basic-sine-four',
    standard: 'PC.TRIG.B.1', difficulty: 1,
    prompt: 'What is the AMPLITUDE of $y = 4\\sin(x)$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The amplitude is the number multiplying the sine.' },
      { level: 'guide', text: 'In $y = a\\sin(x)$, the amplitude is $a$ — how far the wave swings from the middle.' },
      { level: 'reveal', text: 'The amplitude is $4$.' },
    ],
    explanation: ['A sine graph is a WAVE that rises and falls forever around a middle level.', 'Amplitude is how far it swings above and below that middle, and it is the number in front of $\\sin$.', 'In $y = 4\\sin(x)$ that number is $4$, so the amplitude is $4$.'],
    alternativeExplanations: [
      { title: 'From the highest and lowest points', steps: ['Plain sin(x) rides between −1 and 1. Multiplying by 4 stretches it to between −4 and 4.', 'Amplitude is HALF the gap: (4 − (−4)) ÷ 2 = 8 ÷ 2 = 4.'] },
      { title: 'The jump-rope picture', steps: ['Imagine a jump rope shaken up and down. The middle of the rope is the midline.', 'The amplitude is how far your hand lifts the rope above that middle — here, 4 units.'] },
    ],
    tags: ['amplitude'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 92, unit: 10, order: 2, slug: 'midline-sine-plus-seven',
    standard: 'PC.TRIG.B.1', difficulty: 1,
    prompt: 'What is the MIDLINE of $y = \\sin(x) + 7$? Give the $y$-value.',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The midline is set by the number ADDED at the end.' },
      { level: 'guide', text: 'In $y = a\\sin(x) + k$, the midline is $y = k$.' },
      { level: 'reveal', text: 'The midline is $y = 7$.' },
    ],
    explanation: ['Plain $\\sin(x)$ wiggles around $y = 0$.', 'Adding $7$ lifts every single point of the wave up by $7$, so the whole wave now wiggles around $y = 7$.', 'The midline is $y = 7$.'],
    alternativeExplanations: [
      { title: 'Average the peak and the trough', steps: ['sin(x) + 7 rises to 8 at its peak and falls to 6 at its trough.', 'The middle is the average: (8 + 6) ÷ 2 = 7.'] },
      { title: 'The heartbeat-monitor picture', steps: ['On a heart monitor there is a flat resting line, and the trace bounces above and below it.', 'The + 7 tells you where that resting line sits: 7 units up.'] },
    ],
    tags: ['midline'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 93, unit: 10, order: 3, slug: 'amplitude-ferris-wheel-seat',
    standard: 'PC.TRIG.B.1', difficulty: 1,
    prompt: 'A Ferris wheel seat follows $h = 18\\sin(x) + 22$ metres. What is the AMPLITUDE?',
    answerType: 'numeric', primaryAnswer: '18', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The amplitude is the number multiplying the sine.' },
      { level: 'guide', text: 'In $h = a\\sin(x) + k$, the amplitude is $a$ and the midline is $k$.' },
      { level: 'reveal', text: 'The amplitude is $18$ metres.' },
    ],
    explanation: ['Compare to $h = a\\sin(x) + k$.', 'Here $a = 18$ and the midline $k = 22$.', 'The seat rises $18$ m above and falls $18$ m below the $22$ m midline, so the amplitude is $18$.'],
    alternativeExplanations: [
      { title: 'From the highest and lowest points', steps: ['Highest is 22 + 18 = 40 m; lowest is 22 − 18 = 4 m.', 'Amplitude is HALF the gap: (40 − 4) ÷ 2 = 36 ÷ 2 = 18 m.'] },
      { title: 'Picture the wheel', steps: ['The centre of the wheel sits 22 m up — that is the midline.', 'The wheel carries you 18 m above and 18 m below that centre, so the amplitude IS the radius: 18 m.'] },
    ],
    tags: ['amplitude', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 94, unit: 10, order: 4, slug: 'period-sine-two-x',
    standard: 'PC.TRIG.B.1', difficulty: 2,
    prompt: 'What is the PERIOD of $y = \\sin(2x)$, in degrees?',
    answerType: 'numeric', primaryAnswer: '180', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Period $= 360^\\circ \\div b$, where $b$ is the number in FRONT of $x$ inside the sine.' },
      { level: 'guide', text: 'Here $b = 2$, so the period is $360 \\div 2$.' },
      { level: 'reveal', text: '$360 \\div 2 = 180$, so the period is $180^\\circ$.' },
    ],
    explanation: ['The period is how far along $x$ you travel before one full wave finishes and starts over.', 'Plain $\\sin(x)$ takes $360^\\circ$. The $2$ inside makes $x$ count DOUBLE-time, so the wave finishes twice as fast.', 'Period $= 360 \\div 2 = 180^\\circ$.'],
    alternativeExplanations: [
      { title: 'Follow the inside', steps: ['One full wave happens while the inside of the sine runs from 0 to 360.', 'The inside is 2x, so 2x = 360 means x = 180. The x-trip is only 180°.'] },
      { title: 'Squeeze the jump rope', steps: ['A bigger number in front of x squeezes the wave sideways, packing more waves into the same space.', 'b = 2 packs 2 whole waves into 360°, so each one is 360 ÷ 2 = 180° wide.'] },
    ],
    tags: ['period'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 95, unit: 10, order: 5, slug: 'phase-shift-sine-right',
    standard: 'PC.TRIG.B.1', difficulty: 2,
    prompt: 'The graph of $y = \\sin(x - 30^\\circ)$ is the graph of $y = \\sin(x)$ slid sideways. How many degrees does it slide to the RIGHT?',
    answerType: 'numeric', primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A phase shift slides the whole wave sideways. Look at the number subtracted inside the brackets.' },
      { level: 'guide', text: 'In $y = \\sin(x - c)$, the wave slides $c$ degrees to the RIGHT. Here $c = 30$.' },
      { level: 'reveal', text: 'It slides $30^\\circ$ to the right.' },
    ],
    explanation: ['Plain $\\sin(x)$ starts its climb at $x = 0$.', 'For $\\sin(x - 30^\\circ)$, the inside is zero when $x = 30^\\circ$, so the wave starts its climb $30^\\circ$ later.', 'Starting later means the whole wave has slid $30^\\circ$ to the RIGHT.'],
    alternativeExplanations: [
      { title: 'Ask when the inside is zero', steps: ['Whatever plain sine did at 0, the shifted wave does when the inside equals 0.', 'x − 30 = 0 gives x = 30. Every feature arrives 30° later, which is a slide right.'] },
      { title: 'The late-running tide', steps: ['Think of high tide arriving 30 minutes later than usual each day.', 'The tide pattern is exactly the same shape, just running late. Running late = sliding right on a time graph.'] },
    ],
    tags: ['phase-shift'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 96, unit: 10, order: 6, slug: 'heartbeat-monitor-one-beat-period',
    standard: 'PC.TRIG.B.1', difficulty: 2,
    prompt: 'A heart monitor trace is modelled by $y = 3\\sin(6x)$, where $x$ is in degrees. How many degrees wide is ONE full beat?',
    answerType: 'numeric', primaryAnswer: '60', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'One full beat is one full wave — that is the PERIOD.' },
      { level: 'guide', text: 'Period $= 360^\\circ \\div b$, and here $b = 6$.' },
      { level: 'reveal', text: '$360 \\div 6 = 60$, so one beat is $60^\\circ$ wide.' },
    ],
    explanation: ['On a monitor, the trace repeats the same bump over and over. One repeat is one period.', 'The number in front of $x$ inside the sine is $6$, so the wave is squeezed six times tighter.', 'Period $= 360 \\div 6 = 60^\\circ$. The amplitude $3$ tells you how TALL the bump is, not how wide.'],
    alternativeExplanations: [
      { title: 'Count the beats in one turn', steps: ['b = 6 means 6 whole waves fit into 360°.', 'Share 360° out among 6 beats: 360 ÷ 6 = 60° each.'] },
      { title: 'Follow the inside', steps: ['A wave finishes when the inside of the sine has run from 0 all the way to 360.', 'The inside is 6x, so 6x = 360 gives x = 60. One beat spans 60° of x.'] },
    ],
    tags: ['period', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 97, unit: 10, order: 7, slug: 'tide-midline-high-low',
    standard: 'PC.TRIG.B.1', difficulty: 2,
    prompt: 'At a harbour the water is $9$ m deep at high tide and $3$ m deep at low tide. The depth follows a sine wave. What is the MIDLINE depth, in metres?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The midline is the level the wave wiggles around — right between the highest and lowest.' },
      { level: 'guide', text: 'Average them: $(9 + 3) \\div 2$.' },
      { level: 'reveal', text: '$(9 + 3) \\div 2 = 6$ metres.' },
    ],
    explanation: ['A tide graph is a wave: high, low, high, low, forever.', 'The midline sits exactly halfway between the peak and the trough, so average them.', '$(9 + 3) \\div 2 = 12 \\div 2 = 6$ m. (The amplitude would be the half-GAP: $(9 - 3) \\div 2 = 3$ m.)'],
    alternativeExplanations: [
      { title: 'Climb up from the bottom', steps: ['The gap from low to high is 9 − 3 = 6 m.', 'The middle is half that gap above the low point: 3 + 3 = 6 m.'] },
      { title: 'Write the equation', steps: ['The model is depth = a·sin(x) + k, with k the midline and a the amplitude.', 'High = k + a = 9 and low = k − a = 3. Add the two lines: 2k = 12, so k = 6.'] },
    ],
    tags: ['midline', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 98, unit: 10, order: 8, slug: 'daylight-hours-amplitude',
    standard: 'PC.TRIG.B.1', difficulty: 3,
    prompt: 'In one town the longest day of the year has $16$ hours of daylight and the shortest has $8$ hours. Daylight through the year follows a sine wave. What is the AMPLITUDE, in hours?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Amplitude is HALF the distance from the highest point to the lowest point.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Practise on an easier wave: it peaks at $10$ and dips to $2$. The gap is $8$, so the amplitude is $8 \\div 2 = 4$. Now use the same two steps on $16$ and $8$.' },
      { level: 'guide', text: 'The gap is $16 - 8 = 8$ hours. Halve it.' },
      { level: 'reveal', text: '$8 \\div 2 = 4$ hours.' },
    ],
    explanation: ['Peak $= 16$ h, trough $= 8$ h.', 'Amplitude is the half-gap: $(16 - 8) \\div 2 = 8 \\div 2 = 4$ hours.', 'Check with the midline: the middle is $(16 + 8) \\div 2 = 12$ h, and $12 + 4 = 16$, $12 - 4 = 8$. ✓'],
    alternativeExplanations: [
      { title: 'Find the midline first', steps: ['The midline is the average of the two extremes: (16 + 8) ÷ 2 = 12 hours.', 'The amplitude is how far the peak sits above that midline: 16 − 12 = 4 hours.'] },
      { title: 'Build the equation', steps: ['Write daylight = a·sin(x) + k. Peak means k + a = 16; trough means k − a = 8.', 'Subtract the second from the first: 2a = 8, so a = 4 hours.'] },
    ],
    tags: ['amplitude', 'word-problem'], estimatedSeconds: 65,
  },
  {
    domain: 'PC', num: 99, unit: 10, order: 9, slug: 'ferris-wheel-highest-point',
    standard: 'PC.TRIG.B.1', difficulty: 3,
    prompt: 'A Ferris wheel seat follows $h = 18\\sin(x) + 22$ metres. What is the HIGHEST height the seat reaches, in metres?',
    answerType: 'numeric', primaryAnswer: '40', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sine can never be bigger than $1$, so the biggest $18\\sin(x)$ can be is $18$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try $h = 2\\sin(x) + 5$. The biggest sine is $1$, so the top is $2 \\times 1 + 5 = 7$. Same two steps work for $18$ and $22$.' },
      { level: 'guide', text: 'Highest $=$ midline $+$ amplitude $= 22 + 18$.' },
      { level: 'reveal', text: '$22 + 18 = 40$ metres.' },
    ],
    explanation: ['The wave climbs highest when $\\sin(x) = 1$, which happens at $x = 90^\\circ$.', 'Then $h = 18 \\times 1 + 22$.', '$h = 40$ metres. That is the midline $22$ plus the amplitude $18$.'],
    alternativeExplanations: [
      { title: 'Picture the wheel', steps: ['The centre of the wheel is 22 m above the ground and the radius is 18 m.', 'The very top of a wheel is one radius above its centre: 22 + 18 = 40 m.'] },
      { title: 'Make a small table', steps: ['x = 0°: h = 0 + 22 = 22. x = 45°: h ≈ 12.7 + 22 ≈ 34.7. x = 90°: h = 18 + 22 = 40.', 'x = 135°: back down to about 34.7. The peak is at 90°, giving 40 m.'] },
    ],
    tags: ['amplitude', 'midline', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'PC', num: 100, unit: 10, order: 10, slug: 'sound-wave-period-from-equation',
    standard: 'PC.TRIG.B.1', difficulty: 3,
    prompt: 'A speaker makes a tone modelled by $y = 2\\sin(9x)$, where $x$ is in degrees. How many degrees long is ONE full wave?',
    answerType: 'numeric', primaryAnswer: '40', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'One full wave is the PERIOD, and period $= 360^\\circ \\div b$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up with $y = 2\\sin(3x)$: the period is $360 \\div 3 = 120^\\circ$. Now use the same division with $b = 9$.' },
      { level: 'guide', text: 'Here $b = 9$, so compute $360 \\div 9$.' },
      { level: 'reveal', text: '$360 \\div 9 = 40$, so one wave is $40^\\circ$ long.' },
    ],
    explanation: ['For $y = a\\sin(bx)$, the period is $360^\\circ \\div b$.', 'The $2$ out front is the amplitude — how LOUD the tone is — and it does not change the length of a wave.', '$360 \\div 9 = 40^\\circ$. A bigger $b$ packs the waves tighter, which is what a higher pitch sounds like.'],
    alternativeExplanations: [
      { title: 'Count the waves in one turn', steps: ['b = 9 means 9 complete waves are squeezed into a 360° stretch.', 'Share the 360° among 9 waves: 360 ÷ 9 = 40° each.'] },
      { title: 'Follow the inside', steps: ['A wave is finished when the inside of the sine has gone from 0 up to 360.', 'The inside is 9x, so set 9x = 360. Dividing gives x = 40, so the x-trip is 40°.'] },
    ],
    tags: ['period', 'word-problem'], estimatedSeconds: 70,
  },

  // ---------------- Unit 11 — Trig identities & equations (PC.TRIG.B.2) ----------------
  {
    domain: 'PC', num: 101, unit: 11, order: 1, slug: 'pythagorean-identity-equals-one',
    standard: 'PC.TRIG.B.2', difficulty: 1,
    prompt: 'For ANY angle $\\theta$, what does $\\sin^2\\theta + \\cos^2\\theta$ equal?',
    answerType: 'numeric', primaryAnswer: '1', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'On the unit circle the point is $(\\cos\\theta, \\sin\\theta)$ and the radius is $1$.' },
      { level: 'guide', text: 'The Pythagorean theorem on that little triangle says across$^2$ $+$ up$^2$ $=$ radius$^2$.' },
      { level: 'reveal', text: 'Radius$^2 = 1^2 = 1$, so $\\sin^2\\theta + \\cos^2\\theta = 1$.' },
    ],
    explanation: ['Draw the point for angle $\\theta$ on the unit circle and drop a straight line down to the $x$-axis.', 'You get a right triangle: the across leg is $\\cos\\theta$, the up leg is $\\sin\\theta$, and the slanted side is the radius $1$.', 'Pythagoras says leg$^2$ + leg$^2$ = hypotenuse$^2$, so $\\cos^2\\theta + \\sin^2\\theta = 1^2 = 1$. This is TRUE for every angle.'],
    alternativeExplanations: [
      { title: 'Test it with real numbers', steps: ['Take θ = 30°: sin 30° = 0.5 and cos 30° ≈ 0.866.', '0.5² + 0.866² = 0.25 + 0.75 = 1. Try θ = 0°: 0² + 1² = 1. It always lands on 1.'] },
      { title: 'It IS the Pythagorean theorem', steps: ['You already know a² + b² = c² for right triangles.', 'On the unit circle the two legs are named cos θ and sin θ, and the hypotenuse is always 1. Same theorem, new names, and c² = 1.'] },
    ],
    tags: ['pythagorean-identity'], estimatedSeconds: 35,
  },
  {
    domain: 'PC', num: 102, unit: 11, order: 2, slug: 'simplify-one-minus-sin-squared',
    standard: 'PC.TRIG.B.2', difficulty: 1,
    prompt: 'Simplify $1 - \\sin^2\\theta$. It equals $\\cos^n\\theta$. What is $n$?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Start from the identity $\\sin^2\\theta + \\cos^2\\theta = 1$.' },
      { level: 'guide', text: 'Subtract $\\sin^2\\theta$ from both sides: $\\cos^2\\theta = 1 - \\sin^2\\theta$.' },
      { level: 'reveal', text: 'So $1 - \\sin^2\\theta = \\cos^2\\theta$ and $n = 2$.' },
    ],
    explanation: ['The Pythagorean identity says $\\sin^2\\theta + \\cos^2\\theta = 1$.', 'Move $\\sin^2\\theta$ to the other side: $\\cos^2\\theta = 1 - \\sin^2\\theta$.', 'So the expression simplifies to $\\cos^2\\theta$, and the power is $n = 2$.'],
    alternativeExplanations: [
      { title: 'Test it with real numbers', steps: ['Take θ = 30°: sin 30° = 0.5, so 1 − 0.5² = 1 − 0.25 = 0.75.', 'And cos 30° ≈ 0.866, so cos² 30° ≈ 0.75. They match, so the power is 2, not 1.'] },
      { title: 'Think of a full pie', steps: ['The identity says sin² and cos² are two slices that together make one whole pie.', 'Take the sin² slice away from the whole pie and what is left is exactly the cos² slice.'] },
    ],
    tags: ['pythagorean-identity', 'simplify'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 103, unit: 11, order: 3, slug: 'tan-forty-five-equals-one',
    standard: 'PC.TRIG.B.2', difficulty: 1,
    prompt: 'Tangent is defined as $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$. At $45^\\circ$ the sine and the cosine are exactly equal. What is $\\tan 45^\\circ$?',
    answerType: 'numeric', primaryAnswer: '1', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You are dividing a number by ITSELF.' },
      { level: 'guide', text: 'Any number divided by itself (as long as it is not zero) equals $1$.' },
      { level: 'reveal', text: '$\\tan 45^\\circ = 1$.' },
    ],
    explanation: ['$\\tan\\theta$ is just sine divided by cosine — height up divided by shadow across.', 'At $45^\\circ$ you are exactly on the diagonal, so you have gone as far up as you have gone across: $\\sin 45^\\circ = \\cos 45^\\circ$.', 'Dividing equal numbers gives $1$, so $\\tan 45^\\circ = 1$.'],
    alternativeExplanations: [
      { title: 'Use the actual values', steps: ['sin 45° = √2/2 ≈ 0.707 and cos 45° = √2/2 ≈ 0.707.', '0.707 ÷ 0.707 = 1. The messy square roots cancel each other out.'] },
      { title: 'Tangent is slope', steps: ['tan θ is rise over run — the steepness of the line from the centre out to the point.', 'At 45° the line rises 1 for every 1 it runs, which is a slope of exactly 1.'] },
    ],
    tags: ['tangent'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 104, unit: 11, order: 4, slug: 'pythagorean-find-cos-squared',
    standard: 'PC.TRIG.B.2', difficulty: 2,
    prompt: 'For some angle $\\theta$, $\\sin^2\\theta = 0.36$. What is $\\cos^2\\theta$?',
    answerType: 'numeric', primaryAnswer: '0.64', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The two squares always add to $1$.' },
      { level: 'guide', text: '$\\cos^2\\theta = 1 - \\sin^2\\theta = 1 - 0.36$.' },
      { level: 'reveal', text: '$1 - 0.36 = 0.64$.' },
    ],
    explanation: ['The Pythagorean identity: $\\sin^2\\theta + \\cos^2\\theta = 1$.', 'Substitute the known piece: $0.36 + \\cos^2\\theta = 1$.', 'Subtract: $\\cos^2\\theta = 1 - 0.36 = 0.64$.'],
    alternativeExplanations: [
      { title: 'Two pieces of one whole', steps: ['Picture a bar exactly 1 unit long, split into a sin² piece and a cos² piece.', 'The sin² piece takes 0.36 of the bar, so the cos² piece must fill the rest: 1 − 0.36 = 0.64.'] },
      { title: 'Check with the triangle', steps: ['sin² θ = 0.36 means sin θ = 0.6, so the up leg is 0.6 and the slanted side is 1.', 'Pythagoras: 0.6² + b² = 1², so b² = 1 − 0.36 = 0.64 (and cos θ = 0.8).'] },
    ],
    tags: ['pythagorean-identity'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 105, unit: 11, order: 5, slug: 'tan-from-sin-over-cos',
    standard: 'PC.TRIG.B.2', difficulty: 2,
    prompt: 'For an angle $\\theta$ you know $\\sin\\theta = 0.6$ and $\\cos\\theta = 0.8$. What is $\\tan\\theta$?',
    answerType: 'numeric', primaryAnswer: '0.75', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Use the identity $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$.' },
      { level: 'guide', text: 'Divide: $0.6 \\div 0.8$.' },
      { level: 'reveal', text: '$0.6 \\div 0.8 = 0.75$.' },
    ],
    explanation: ['Tangent is height up divided by shadow across: $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$.', 'Substitute: $\\tan\\theta = \\frac{0.6}{0.8}$.', '$0.6 \\div 0.8 = 0.75$. (Check: $0.6^2 + 0.8^2 = 0.36 + 0.64 = 1$, so these values really can sit on the unit circle.)'],
    alternativeExplanations: [
      { title: 'Turn it into a fraction', steps: ['0.6/0.8 is the same as 6/8 after multiplying top and bottom by 10.', 'Simplify 6/8 to 3/4, which is 0.75.'] },
      { title: 'Read it as slope', steps: ['tan θ is rise over run for the line from the centre to the point (0.8, 0.6).', 'It rises 0.6 while it runs 0.8, so the slope is 0.6 ÷ 0.8 = 0.75 — a gentle uphill.'] },
    ],
    tags: ['tangent'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 106, unit: 11, order: 6, slug: 'platform-highest-angle',
    standard: 'PC.TRIG.B.2', difficulty: 2,
    prompt: 'A rotating platform lifts a robot to height $h = 5\\sin\\theta + 5$ metres as it spins. For $0^\\circ \\le \\theta < 360^\\circ$, at what angle $\\theta$ is the robot HIGHEST? Give the angle in degrees.',
    answerType: 'numeric', primaryAnswer: '90', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The height is biggest when $\\sin\\theta$ is biggest.' },
      { level: 'guide', text: 'The largest value sine can ever take is $1$. Which angle in one turn gives $\\sin\\theta = 1$?' },
      { level: 'reveal', text: '$\\sin 90^\\circ = 1$, so the robot is highest at $\\theta = 90^\\circ$ (height $10$ m).' },
    ],
    explanation: ['Only the $\\sin\\theta$ part changes; the $+5$ is fixed.', 'Sine tops out at $1$, and on the unit circle the height is $1$ only at the very top: $\\theta = 90^\\circ$.', 'There $h = 5 \\times 1 + 5 = 10$ m, the highest the platform reaches.'],
    alternativeExplanations: [
      { title: 'Make a small table', steps: ['θ = 0°: h = 5. θ = 45°: h ≈ 8.5. θ = 90°: h = 10. θ = 135°: h ≈ 8.5. θ = 180°: h = 5.', 'The numbers climb to 10 at 90° and then fall back, so 90° is the peak.'] },
      { title: 'Picture the unit circle', steps: ['Sine is the HEIGHT UP of the point on the circle.', 'The highest point on any circle is straight up from the centre, and that direction is 90°.'] },
    ],
    tags: ['trig-equation', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 107, unit: 11, order: 7, slug: 'game-motion-cosine-to-sine',
    standard: 'PC.TRIG.B.2', difficulty: 2,
    prompt: 'A game stores a character\'s facing direction as $\\cos\\theta = 0.6$, with $\\theta$ in Quadrant 1. To move the character, the game needs $\\sin\\theta$. What is $\\sin\\theta$?',
    answerType: 'numeric', primaryAnswer: '0.8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Use $\\sin^2\\theta + \\cos^2\\theta = 1$ to find $\\sin^2\\theta$ first.' },
      { level: 'guide', text: '$\\sin^2\\theta = 1 - 0.6^2 = 1 - 0.36 = 0.64$. Now take the square root.' },
      { level: 'reveal', text: '$\\sqrt{0.64} = 0.8$. In Quadrant 1 sine is positive, so $\\sin\\theta = 0.8$.' },
    ],
    explanation: ['The identity $\\sin^2\\theta + \\cos^2\\theta = 1$ links the two values, so knowing one gives the other.', '$\\sin^2\\theta = 1 - 0.6^2 = 1 - 0.36 = 0.64$.', 'Take the square root: $\\sin\\theta = 0.8$. Quadrant 1 is up-and-right, where sine is positive, so keep the plus.'],
    alternativeExplanations: [
      { title: 'Spot the 3-4-5 triangle', steps: ['cos θ = 0.6 = 3/5 means the across leg is 3 and the slanted side is 5.', 'That is the famous 3-4-5 right triangle, so the up leg is 4. sin θ = 4/5 = 0.8.'] },
      { title: 'Check the game math', steps: ['A facing direction must be a point on the unit circle, so across² + up² has to equal 1.', 'Test 0.8: 0.6² + 0.8² = 0.36 + 0.64 = 1. It checks out, so 0.8 is the value the game needs.'] },
    ],
    tags: ['pythagorean-identity', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: 'PC', num: 108, unit: 11, order: 8, slug: 'count-solutions-sin-half',
    standard: 'PC.TRIG.B.2', difficulty: 3,
    prompt: 'How many angles $\\theta$ between $0^\\circ$ and $360^\\circ$ make $\\sin\\theta = 0.5$ true?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$\\sin\\theta$ is the HEIGHT of the point. Draw a flat line at height $0.5$ across the unit circle and count the crossings.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try height $0$ first: the circle sits at height $0$ at $0^\\circ$ and again at $180^\\circ$ — two spots in one turn. A flat line usually cuts a circle in two places. Now do the same at height $0.5$.' },
      { level: 'guide', text: 'The line at height $0.5$ cuts the circle once on the way up (Quadrant 1) and once on the way back down (Quadrant 2).' },
      { level: 'reveal', text: 'There are $2$ solutions: $30^\\circ$ and $150^\\circ$.' },
    ],
    explanation: ['Picture the unit circle and a flat horizontal line drawn at height $0.5$.', 'Going once around, you pass through that height on the way UP at $30^\\circ$ and again on the way DOWN at $150^\\circ$.', 'So there are $2$ solutions in one full turn. Almost every basic trig equation has TWO answers per turn.'],
    alternativeExplanations: [
      { title: 'Read it off the wave graph', steps: ['Graph y = sin θ from 0° to 360° — it rises to 1, falls to −1, and comes back.', 'Draw the flat line y = 0.5 across it. The wave crosses that line twice: once climbing, once falling.'] },
      { title: 'Think of a rotating platform', steps: ['A seat on a spinning platform passes each height twice per turn — once rising, once falling.', 'The only heights hit just once are the very top and the very bottom. 0.5 is neither, so it gets hit twice.'] },
    ],
    tags: ['trig-equation'], estimatedSeconds: 65,
  },
  {
    domain: 'PC', num: 109, unit: 11, order: 9, slug: 'platform-second-solution-sine-half',
    standard: 'PC.TRIG.B.2', difficulty: 3,
    prompt: 'A rotating platform is at the right height when $\\sin\\theta = 0.5$. One answer is $\\theta = 30^\\circ$. What is the OTHER answer between $0^\\circ$ and $360^\\circ$? Give it in degrees.',
    answerType: 'numeric', primaryAnswer: '150', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sine is positive in Quadrant 1 AND Quadrant 2, so the partner answer is in Quadrant 2.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Practise the rule with $\\sin\\theta = 0.7$, first answer about $44^\\circ$: the partner is $180 - 44 = 136^\\circ$. Now use $180 - 30$.' },
      { level: 'guide', text: 'The partner in Quadrant 2 is $180^\\circ - \\theta$, so compute $180 - 30$.' },
      { level: 'reveal', text: '$180 - 30 = 150$, so the other answer is $150^\\circ$.' },
    ],
    explanation: ['Two points on the unit circle sit at the same height: one in Quadrant 1 and its mirror in Quadrant 2.', 'The mirror of $\\theta$ across the top of the circle is $180^\\circ - \\theta$.', '$180 - 30 = 150^\\circ$. Check: $\\sin 150^\\circ = 0.5$ too. ✓'],
    alternativeExplanations: [
      { title: 'Mirror the picture', steps: ['Fold the circle along the vertical line through the centre.', 'The point at 30° lands exactly on the point at 150°. Folding sideways keeps the HEIGHT the same, so both have sine 0.5.'] },
      { title: 'The platform rises, then falls', steps: ['Turning from 0°, the platform rises and hits the target height at 30°.', 'It keeps rising to the top at 90°, then comes back DOWN and passes the same height again — the same 30° of turn past the top, at 90 + 60 = 150°.'] },
    ],
    tags: ['trig-equation', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'PC', num: 110, unit: 11, order: 10, slug: 'ramp-tangent-second-solution',
    standard: 'PC.TRIG.B.2', difficulty: 3,
    prompt: 'A ramp-checking app solves $\\tan\\theta = 1$ for $0^\\circ \\le \\theta < 360^\\circ$. One answer is $45^\\circ$. What is the OTHER answer, in degrees?',
    answerType: 'numeric', primaryAnswer: '225', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$. If sine and cosine BOTH flip sign, the fraction stays the same.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Test the idea with numbers: $\\frac{0.7}{0.7} = 1$ and $\\frac{-0.7}{-0.7} = 1$ too. So the opposite direction on the circle gives the same tangent. Opposite means add $180^\\circ$.' },
      { level: 'guide', text: 'Add half a turn to the first answer: $45 + 180$.' },
      { level: 'reveal', text: '$45 + 180 = 225$, so the other answer is $225^\\circ$.' },
    ],
    explanation: ['At $45^\\circ$ the point is $(0.707, 0.707)$, so $\\tan 45^\\circ = 1$.', 'Straight across the circle, at $225^\\circ$, the point is $(-0.707, -0.707)$. Both parts flipped sign, and two minus signs cancel when you divide.', '$\\tan 225^\\circ = \\frac{-0.707}{-0.707} = 1$ as well, so the other answer is $225^\\circ$.'],
    alternativeExplanations: [
      { title: 'Tangent is slope', steps: ['tan θ is the slope of the line from the centre through the point.', 'A single straight line through the centre passes through the circle at TWO opposite spots, and both share the same slope of 1. Those spots are 45° and 45 + 180 = 225°.'] },
      { title: 'Sort by quadrant signs', steps: ['tan is positive when sin and cos share a sign: both plus (Quadrant 1) or both minus (Quadrant 3).', 'Quadrant 1 gives 45°. The matching Quadrant 3 angle is half a turn further on: 225°.'] },
    ],
    tags: ['tangent', 'trig-equation', 'word-problem'], estimatedSeconds: 80,
  },
];
