import type { SeedProblem } from './types';

// PC Units 12-14 — Law of Sines & Law of Cosines, Sequences & series,
// Intro to limits & rate of change. 10 problems per unit, difficulty ramp
// 1-1-1-2-2-2-2-3-3-3. Every difficulty-3 problem carries a second, titled
// nudge that reworks the method on an easier parallel case.

export const problemsPCu12: SeedProblem[] = [
  // ---------------- UNIT 12 — Law of Sines & Law of Cosines ----------------
  {
    domain: 'PC', num: 111, unit: 12, order: 1, slug: 'triangle-third-angle-first',
    standard: 'PC.TRIG.C.1', difficulty: 1,
    prompt: 'Two angles of a triangle measure $40^\\circ$ and $75^\\circ$. What is the third angle, in degrees?',
    answerType: 'numeric', primaryAnswer: '65', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The three angles of ANY triangle always add to $180^\\circ$.' },
      { level: 'guide', text: 'First add what you know: $40 + 75 = 115$. Then see what is missing from $180$.' },
      { level: 'reveal', text: '$180 - 115 = 65$, so the third angle is $65^\\circ$.' },
    ],
    explanation: ['Every triangle\'s angles total $180^\\circ$.', 'The two known angles add to $40 + 75 = 115$.', '$180 - 115 = 65^\\circ$.'],
    alternativeExplanations: [
      { title: 'Tear the corners off', steps: ['Cut a paper triangle and tear off all three corners.', 'Slide the three torn corners together and they form a perfectly straight line — and a straight line is 180°.', 'So the missing corner is whatever is left over: 180 − 115 = 65°.'] },
      { title: 'Work backwards', steps: ['Start at the full 180° and take away the pieces you already have.', '180 − 40 = 140. Then 140 − 75 = 65.', 'Same answer, one subtraction at a time — handy when the numbers are messy.'] },
    ],
    tags: ['triangle', 'angle-sum'], estimatedSeconds: 25,
  },
  {
    domain: 'PC', num: 112, unit: 12, order: 2, slug: 'law-of-sines-find-side-basic',
    standard: 'PC.TRIG.C.1', difficulty: 1,
    prompt: 'In triangle $ABC$, angle $A = 30^\\circ$ and angle $B = 90^\\circ$. Side $b$ (the side across from $B$) is $10$. Find side $a$, the side across from $A$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You have a matching pair (side $b$ with angle $B$), so reach for the Law of Sines.' },
      { level: 'guide', text: 'Set up $\\frac{a}{\\sin A} = \\frac{b}{\\sin B}$, which is $\\frac{a}{\\sin 30^\\circ} = \\frac{10}{\\sin 90^\\circ}$.' },
      { level: 'reveal', text: '$\\sin 30^\\circ = \\frac{1}{2}$ and $\\sin 90^\\circ = 1$, so $a = 10 \\times \\frac{1}{2} = 5$.' },
    ],
    explanation: ['The Law of Sines pairs each side with the angle ACROSS from it.', '$\\frac{a}{\\sin 30^\\circ} = \\frac{10}{\\sin 90^\\circ}$.', 'Since $\\sin 90^\\circ = 1$, the right side is just $10$.', '$a = 10 \\times \\sin 30^\\circ = 10 \\times \\frac{1}{2} = 5$.'],
    alternativeExplanations: [
      { title: 'A table of the two pairs', steps: ['Make two columns: ANGLE and SIDE ACROSS FROM IT.', 'Row 1: angle 30°, side a. Row 2: angle 90°, side 10.', 'The Law of Sines says both rows give the same ratio: a ÷ 0.5 must equal 10 ÷ 1 = 10, so a = 5.'] },
      { title: 'Picture the half-equilateral', steps: ['A 30-60-90 triangle is an equilateral triangle sliced straight down the middle.', 'The side across the 90° corner is the long slanted side; the side across the 30° corner is the short one.', 'In that sliced triangle the short side is exactly half the long one: half of 10 is 5.'] },
    ],
    tags: ['law-of-sines', 'triangle'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 113, unit: 12, order: 3, slug: 'law-of-cosines-find-side-basic',
    standard: 'PC.TRIG.C.1', difficulty: 1,
    prompt: 'In triangle $ABC$, $a = 3$, $b = 8$, and the angle between those two sides is $C = 60^\\circ$. Find side $c$.',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two sides and the angle squeezed between them (SAS) is the Law of Cosines tool.' },
      { level: 'guide', text: '$c^2 = a^2 + b^2 - 2ab\\cos C = 9 + 64 - 2 \\times 3 \\times 8 \\times \\cos 60^\\circ$.' },
      { level: 'reveal', text: '$\\cos 60^\\circ = \\frac{1}{2}$, so $c^2 = 73 - 24 = 49$ and $c = 7$.' },
    ],
    explanation: ['Use $c^2 = a^2 + b^2 - 2ab\\cos C$.', '$3^2 + 8^2 = 9 + 64 = 73$.', 'The correction term: $2 \\times 3 \\times 8 \\times \\frac{1}{2} = 24$.', '$c^2 = 73 - 24 = 49$, so $c = \\sqrt{49} = 7$.'],
    alternativeExplanations: [
      { title: 'Pythagoras plus a correction', steps: ['Pretend for a second the corner is a right angle. Then c² would be 9 + 64 = 73.', 'But the corner is only 60°, which is narrower than 90°, so the far side is pulled in shorter.', 'The correction term −24 does exactly that pulling: 73 − 24 = 49, so c = 7.'] },
      { title: 'Three pieces in a table', steps: ['Piece 1: a² = 9. Piece 2: b² = 64. Piece 3: 2ab·cos C = 24.', 'The formula is just piece 1 + piece 2 − piece 3.', '9 + 64 − 24 = 49, and √49 = 7. Filling a tiny table keeps you from losing a piece.'] },
    ],
    tags: ['law-of-cosines', 'triangle'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 114, unit: 12, order: 4, slug: 'drone-two-spotters',
    standard: 'PC.TRIG.C.1', difficulty: 2,
    prompt: 'Two friends stand $100$ m apart on a flat field and both look up at a drone. From friend $A$ the angle to the drone is $30^\\circ$; from friend $B$ it is $60^\\circ$. That makes the angle at the drone $90^\\circ$. How many meters is the drone from friend $B$?',
    answerType: 'numeric', primaryAnswer: '50', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $100$ m gap sits ACROSS from the drone\'s $90^\\circ$ angle — that is your matching pair.' },
      { level: 'guide', text: 'The side from $B$ to the drone sits across from angle $A = 30^\\circ$. So $\\frac{a}{\\sin 30^\\circ} = \\frac{100}{\\sin 90^\\circ}$.' },
      { level: 'reveal', text: '$a = 100 \\times \\frac{1}{2} = 50$ meters.' },
    ],
    explanation: ['Label the triangle: the two friends and the drone are the corners.', 'The $100$ m side is across from the $90^\\circ$ drone angle, so use that pair.', '$\\frac{a}{\\sin 30^\\circ} = \\frac{100}{\\sin 90^\\circ} = 100$.', '$a = 100 \\times \\frac{1}{2} = 50$ m.'],
    alternativeExplanations: [
      { title: 'Draw it in words first', steps: ['Sketch a flat line with friend A on the left and friend B on the right, 100 m apart.', 'Draw both sight lines up to the drone. The steeper 60° line belongs to friend B, so friend B is CLOSER.', 'Closer means the answer must be less than 100 m, and 50 m passes that sanity check.'] },
      { title: 'Which side goes with which angle', steps: ['Big angle, big side across from it. Order the angles: 30° < 60° < 90°.', 'So the shortest side is across from 30°, which is exactly the B-to-drone distance you want.', 'The 100 m side is across the biggest angle, and 50 is the smallest of the three — the sizes line up.'] },
    ],
    tags: ['law-of-sines', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: 'PC', num: 115, unit: 12, order: 5, slug: 'boat-turn-law-of-cosines',
    standard: 'PC.TRIG.C.1', difficulty: 2,
    prompt: 'A boat sails $5$ km in a straight line, then turns and sails $16$ km more. The angle inside the triangle at the turning point is $120^\\circ$. How many kilometers is the boat from where it started?',
    answerType: 'numeric', primaryAnswer: '19', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You know two sides and the angle squeezed between them. That is the Law of Cosines.' },
      { level: 'guide', text: '$c^2 = 5^2 + 16^2 - 2 \\times 5 \\times 16 \\times \\cos 120^\\circ$, and $\\cos 120^\\circ = -\\frac{1}{2}$.' },
      { level: 'reveal', text: 'Subtracting a negative ADDS: $c^2 = 281 + 80 = 361$, so $c = 19$ km.' },
    ],
    explanation: ['The two legs and the straight-home line form a triangle.', '$5^2 + 16^2 = 25 + 256 = 281$.', 'The correction: $2 \\times 5 \\times 16 \\times (-\\frac{1}{2}) = -80$, and subtracting $-80$ adds $80$.', '$c^2 = 281 + 80 = 361$, so $c = 19$ km.'],
    alternativeExplanations: [
      { title: 'Why a wide angle stretches it', steps: ['If the turn made a right angle, the distance home would be √281 ≈ 16.8 km.', 'A 120° corner is WIDER than a right angle, so the two ends swing farther apart.', 'That is why the answer 19 is bigger than 16.8 — a wide corner always stretches the far side.'] },
      { title: 'Check it against the limits', steps: ['If the boat had turned all the way around (180°), it would sit 16 − 5 = 11 km away.', 'If it had never turned at all (0°), it would be 5 + 16 = 21 km away.', 'The real answer must land between 11 and 21, and 19 does — close to 21 because 120° is a gentle bend.'] },
    ],
    tags: ['law-of-cosines', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: 'PC', num: 116, unit: 12, order: 6, slug: 'law-of-cosines-find-angle-sss',
    standard: 'PC.TRIG.C.1', difficulty: 2,
    prompt: 'A triangle has sides $3$, $5$, and $7$. Find the angle across from the side of length $7$, in degrees.',
    answerType: 'numeric', primaryAnswer: '120', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Three sides and no angles (SSS) means the Law of Cosines, rearranged to hunt for the angle.' },
      { level: 'guide', text: 'Put $7$ in the $c$ spot: $49 = 9 + 25 - 2 \\times 3 \\times 5 \\times \\cos C$, so $49 = 34 - 30\\cos C$.' },
      { level: 'reveal', text: '$30\\cos C = 34 - 49 = -15$, so $\\cos C = -\\frac{1}{2}$ and $C = 120^\\circ$.' },
    ],
    explanation: ['The angle you want is across from the side $7$, so $7$ plays the role of $c$.', '$49 = 9 + 25 - 30\\cos C$.', '$49 = 34 - 30\\cos C$, so $30\\cos C = -15$.', '$\\cos C = -\\frac{1}{2}$, which happens at $C = 120^\\circ$.'],
    alternativeExplanations: [
      { title: 'Predict before you compute', steps: ['Test the corner against Pythagoras first: 3² + 5² = 34, but 7² = 49.', 'The far side came out LONGER than a right angle would allow, so the corner must be wider than 90°.', 'Only an obtuse answer makes sense, and 120° is obtuse — the computation just confirms your prediction.'] },
      { title: 'Read the cosine backwards', steps: ['You end up needing the angle whose cosine is −1/2.', 'Cosine is positive for sharp angles and negative for wide ones, so the answer is past 90°.', 'From the special-angle list, cos 60° = 1/2 and cos 120° = −1/2. The answer is 120°.'] },
    ],
    tags: ['law-of-cosines', 'angle'], estimatedSeconds: 60,
  },
  {
    domain: 'PC', num: 117, unit: 12, order: 7, slug: 'park-pond-shortcut',
    standard: 'PC.TRIG.C.1', difficulty: 2,
    prompt: 'A pond sits in the middle of a park, so you cannot walk straight across it. From one corner, a path runs $30$ m to point $P$ and another path runs $80$ m to point $Q$. The angle between the two paths is $60^\\circ$. How many meters is it straight across from $P$ to $Q$?',
    answerType: 'numeric', primaryAnswer: '70', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You cannot measure the distance you want, but you have two sides and the angle between them.' },
      { level: 'guide', text: '$c^2 = 30^2 + 80^2 - 2 \\times 30 \\times 80 \\times \\cos 60^\\circ = 900 + 6400 - 2400$.' },
      { level: 'reveal', text: '$c^2 = 4900$, so $c = 70$ meters.' },
    ],
    explanation: ['The corner, $P$, and $Q$ form a triangle with the pond inside it.', '$30^2 + 80^2 = 900 + 6400 = 7300$.', 'Correction term: $2 \\times 30 \\times 80 \\times \\frac{1}{2} = 2400$.', '$c^2 = 7300 - 2400 = 4900$, so $c = 70$ m.'],
    alternativeExplanations: [
      { title: 'Scale down, then scale up', steps: ['Divide every length by 10: the paths become 3 m and 8 m at 60°.', 'That small triangle gives 9 + 64 − 24 = 49, so the small crossing is 7.', 'Now scale back up by 10: the real crossing is 70 m. Shrinking the numbers makes the arithmetic tiny.'] },
      { title: 'Does the answer make sense?', steps: ['Walking the two paths takes 30 + 80 = 110 m, and the straight cut must be shorter than that.', 'It must also be longer than the difference, 80 − 30 = 50 m.', '70 sits between 50 and 110, so it passes the sanity check — and it saves you 40 m of walking.'] },
    ],
    tags: ['law-of-cosines', 'word-problem'], estimatedSeconds: 65,
  },
  {
    domain: 'PC', num: 118, unit: 12, order: 8, slug: 'ball-field-odd-corner',
    standard: 'PC.TRIG.C.1', difficulty: 3,
    prompt: 'A ball field has an odd corner at home plate. One edge runs $90$ ft from home plate to a post, and another edge runs $150$ ft from home plate to a second post. The angle at home plate between the two edges is $120^\\circ$. How many feet apart are the two posts?',
    answerType: 'numeric', primaryAnswer: '210', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two edges and the angle squeezed between them: pull the Law of Cosines out of the toolbox.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Same method, tiny numbers: sides $3$ and $5$ with a $120^\\circ$ corner. $c^2 = 9 + 25 - 2(3)(5)(-\\frac{1}{2}) = 34 + 15 = 49$, so $c = 7$. Notice the minus and the negative cosine turned into a PLUS. Now redo it with $90$ and $150$.' },
      { level: 'guide', text: '$90^2 + 150^2 = 8100 + 22500 = 30600$, and the correction is $2 \\times 90 \\times 150 \\times (-\\frac{1}{2}) = -13500$.' },
      { level: 'reveal', text: 'Subtracting $-13500$ adds it: $c^2 = 30600 + 13500 = 44100$, so $c = 210$ ft.' },
    ],
    explanation: ['Home plate and the two posts form a triangle with a $120^\\circ$ corner.', '$c^2 = 90^2 + 150^2 - 2(90)(150)\\cos 120^\\circ$.', '$\\cos 120^\\circ = -\\frac{1}{2}$, so the last term is $-13500$ and subtracting it ADDS $13500$.', '$c^2 = 30600 + 13500 = 44100$, so $c = \\sqrt{44100} = 210$ ft.'],
    alternativeExplanations: [
      { title: 'Shrink the numbers first', steps: ['Divide both edges by 30: they become 3 ft and 5 ft with the same 120° corner.', 'The small triangle gives 9 + 25 + 15 = 49, so the small answer is 7.', 'Scale back by 30: 7 × 30 = 210 ft. Same shape, easy arithmetic.'] },
      { title: 'Find the square root in pieces', steps: ['√44100 looks scary, so split it: 44100 = 441 × 100.', '√441 = 21 because 21 × 21 = 441, and √100 = 10.', 'Multiply the two roots: 21 × 10 = 210 ft.'] },
    ],
    tags: ['law-of-cosines', 'word-problem'], estimatedSeconds: 80,
  },
  {
    domain: 'PC', num: 119, unit: 12, order: 9, slug: 'law-of-cosines-right-angle-check',
    standard: 'PC.TRIG.C.1', difficulty: 3,
    prompt: 'A triangle has sides $5$, $12$, and $13$. Use the Law of Cosines to find the angle across from the side of length $13$, in degrees.',
    answerType: 'numeric', primaryAnswer: '90', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Three sides, no angles. Put the side you are asking about in the $c$ spot and solve for $\\cos C$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Same method on a $3$-$4$-$5$ triangle: $25 = 9 + 16 - 2(3)(4)\\cos C$, so $25 = 25 - 24\\cos C$ and $\\cos C = 0$. An angle with cosine $0$ is $90^\\circ$. Now run the identical steps on $5$-$12$-$13$.' },
      { level: 'guide', text: '$169 = 25 + 144 - 2 \\times 5 \\times 12 \\times \\cos C$, which is $169 = 169 - 120\\cos C$.' },
      { level: 'reveal', text: 'That forces $120\\cos C = 0$, so $\\cos C = 0$ and $C = 90^\\circ$.' },
    ],
    explanation: ['Set $c = 13$: $13^2 = 5^2 + 12^2 - 2(5)(12)\\cos C$.', '$169 = 25 + 144 - 120\\cos C = 169 - 120\\cos C$.', 'Subtract $169$ from both sides: $0 = -120\\cos C$, so $\\cos C = 0$.', 'The angle with cosine $0$ is $90^\\circ$ — this triangle is a right triangle.'],
    alternativeExplanations: [
      { title: 'Pythagoras was here all along', steps: ['Check the two short sides: 5² + 12² = 25 + 144 = 169, and 13² = 169 too.', 'That is exactly the Pythagorean theorem, which only holds for right triangles.', 'So the corner is 90° — and the Law of Cosines agrees because its correction term shrinks to zero.'] },
      { title: 'What the correction term is telling you', steps: ['The Law of Cosines is Pythagoras plus a correction: c² = a² + b² − 2ab·cos C.', 'When C is exactly 90°, cos 90° = 0, so the whole correction disappears.', 'Seeing the correction vanish is a signal: the corner is square. Pythagoras is just the Law of Cosines on its best day.'] },
    ],
    tags: ['law-of-cosines', 'pythagorean'], estimatedSeconds: 75,
  },
  {
    domain: 'PC', num: 120, unit: 12, order: 10, slug: 'boat-straight-route-savings',
    standard: 'PC.TRIG.C.1', difficulty: 3,
    prompt: 'A boat sails $5$ km, turns so the angle inside the triangle at the turn is $120^\\circ$, then sails $16$ km. A friend takes the straight route from the start point to the finish point. How many kilometers shorter is the straight route than the boat\'s path?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'This is two steps: first find the straight-line distance, then compare it with the sailed distance.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Legs of $3$ km and $5$ km with a $120^\\circ$ turn: $c^2 = 9 + 25 + 15 = 49$, so straight $= 7$ km while the path is $3 + 5 = 8$ km. The saving is $8 - 7 = 1$ km. Now do the same two steps with $5$ and $16$.' },
      { level: 'guide', text: 'Straight line: $c^2 = 25 + 256 - 2(5)(16)(-\\frac{1}{2}) = 281 + 80 = 361$, so $c = 19$ km. The boat sailed $5 + 16 = 21$ km.' },
      { level: 'reveal', text: '$21 - 19 = 2$ kilometers saved.' },
    ],
    explanation: ['Step 1 — the straight route uses the Law of Cosines: $c^2 = 5^2 + 16^2 - 2(5)(16)\\cos 120^\\circ$.', '$\\cos 120^\\circ = -\\frac{1}{2}$, so $c^2 = 281 + 80 = 361$ and $c = 19$ km.', 'Step 2 — the boat actually sailed $5 + 16 = 21$ km.', 'The straight route is $21 - 19 = 2$ km shorter.'],
    alternativeExplanations: [
      { title: 'Two numbers on a number line', steps: ['Mark the sailed distance, 21 km, on a number line.', 'Mark the straight distance, 19 km, just to its left.', 'The gap between the marks IS the saving: 2 km. Drawing both numbers keeps you from answering with 19 by mistake.'] },
      { title: 'Why the saving is so small', steps: ['A 120° turn is a gentle bend — the boat almost keeps going straight.', 'A nearly straight path is barely longer than the true straight line, so the shortcut saves very little.', 'If the turn had been 90°, the straight line would be about 16.8 km and the saving would jump to about 4.2 km.'] },
    ],
    tags: ['law-of-cosines', 'word-problem', 'multi-step'], estimatedSeconds: 90,
  },

  // ---------------- UNIT 13 — Sequences & series ----------------
  {
    domain: 'PC', num: 121, unit: 13, order: 1, slug: 'arithmetic-next-term',
    standard: 'PC.SEQ.A.1', difficulty: 1,
    prompt: 'Look at the sequence $3,\\ 7,\\ 11,\\ 15,\\ \\dots$ What is the next term?',
    answerType: 'numeric', primaryAnswer: '19', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Check what happens from one term to the next. Is it the same jump every time?' },
      { level: 'guide', text: '$7 - 3 = 4$, $11 - 7 = 4$, $15 - 11 = 4$. The rule adds $4$ each step.' },
      { level: 'reveal', text: '$15 + 4 = 19$.' },
    ],
    explanation: ['A sequence is an ordered list with a rule.', 'The gaps are $4, 4, 4$ — the same amount each time, so this is ARITHMETIC.', 'Keep the rule going: $15 + 4 = 19$.'],
    alternativeExplanations: [
      { title: 'A gap table', steps: ['Write the terms in one row: 3, 7, 11, 15.', 'Write the gaps underneath, between the terms: 4, 4, 4.', 'A row of identical gaps means "add 4 forever", so the next term is 15 + 4 = 19.'] },
      { title: 'Hops on a number line', steps: ['Picture a number line and start at 3.', 'Each term is one hop of the same size to the right, landing on 7, 11, then 15.', 'One more hop of 4 lands you on 19.'] },
    ],
    tags: ['sequence', 'arithmetic'], estimatedSeconds: 25,
  },
  {
    domain: 'PC', num: 122, unit: 13, order: 2, slug: 'geometric-next-term',
    standard: 'PC.SEQ.A.1', difficulty: 1,
    prompt: 'Look at the sequence $2,\\ 6,\\ 18,\\ 54,\\ \\dots$ What is the next term?',
    answerType: 'numeric', primaryAnswer: '162', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The gaps keep growing, so try DIVIDING each term by the one before it instead.' },
      { level: 'guide', text: '$6 \\div 2 = 3$, $18 \\div 6 = 3$, $54 \\div 18 = 3$. The rule multiplies by $3$.' },
      { level: 'reveal', text: '$54 \\times 3 = 162$.' },
    ],
    explanation: ['The jumps are $4, 12, 36$ — not the same, so it is not arithmetic.', 'Divide instead: each term is $3$ times the one before, so this is GEOMETRIC with $r = 3$.', '$54 \\times 3 = 162$.'],
    alternativeExplanations: [
      { title: 'Arithmetic or geometric? A quick test', steps: ['Subtract first: 6 − 2 = 4 but 18 − 6 = 12. The gaps disagree, so it is NOT arithmetic.', 'Now divide: 6 ÷ 2 = 3 and 18 ÷ 6 = 3. The ratios agree, so it IS geometric.', 'Once the ratio is 3, the next term is 54 × 3 = 162.'] },
      { title: 'Write each term as powers of 3', steps: ['2, then 2 × 3, then 2 × 3 × 3, then 2 × 3 × 3 × 3 — that is 2, 6, 18, 54.', 'Each new term just glues on one more factor of 3.', 'The fifth term glues on one more: 2 × 3⁴ = 2 × 81 = 162.'] },
    ],
    tags: ['sequence', 'geometric'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 123, unit: 13, order: 3, slug: 'arithmetic-nth-term-formula',
    standard: 'PC.SEQ.A.1', difficulty: 1,
    prompt: 'An arithmetic sequence starts at $a_1 = 5$ and adds $d = 4$ each step. Find $a_{10}$.',
    answerType: 'numeric', primaryAnswer: '41', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Use $a_n = a_1 + (n - 1)d$. The first term has taken ZERO jumps, not one.' },
      { level: 'guide', text: 'To reach term $10$ you take $10 - 1 = 9$ jumps of size $4$, which is $36$.' },
      { level: 'reveal', text: '$a_{10} = 5 + 36 = 41$.' },
    ],
    explanation: ['$a_n = a_1 + (n - 1)d$.', '$a_{10} = 5 + (10 - 1) \\times 4$.', '$= 5 + 9 \\times 4 = 5 + 36$.', '$= 41$.'],
    alternativeExplanations: [
      { title: 'Count the jumps on your fingers', steps: ['Term 1 is 5 with no jumps yet. Term 2 is 9 after one jump. Term 3 is 13 after two jumps.', 'Notice the pattern: the jump count is always one less than the term number.', 'Term 10 means 9 jumps: 5 + 9(4) = 41.'] },
      { title: 'List it out to check', steps: ['5, 9, 13, 17, 21, 25, 29, 33, 37, 41.', 'Count the numbers you wrote: exactly ten of them.', 'The tenth is 41 — the formula and the list agree, and the list is a great safety net for small n.'] },
    ],
    tags: ['sequence', 'arithmetic', 'formula'], estimatedSeconds: 35,
  },
  {
    domain: 'PC', num: 124, unit: 13, order: 4, slug: 'theatre-seats-row-twenty',
    standard: 'PC.SEQ.A.1', difficulty: 2,
    prompt: 'In a theatre, row $1$ has $12$ seats. Every row after that has $3$ more seats than the row in front of it. How many seats are in row $20$?',
    answerType: 'numeric', primaryAnswer: '69', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Same amount added each row means this is an ARITHMETIC sequence with $a_1 = 12$ and $d = 3$.' },
      { level: 'guide', text: 'Row $20$ is $19$ rows behind row $1$, so it has taken $19$ jumps of $3$ seats: $57$ extra seats.' },
      { level: 'reveal', text: '$12 + 57 = 69$ seats.' },
    ],
    explanation: ['$a_n = a_1 + (n - 1)d$ with $a_1 = 12$ and $d = 3$.', '$a_{20} = 12 + (20 - 1) \\times 3$.', '$= 12 + 19 \\times 3 = 12 + 57$.', '$= 69$ seats.'],
    alternativeExplanations: [
      { title: 'A short table, then a leap', steps: ['Row 1: 12. Row 2: 15. Row 3: 18. Row 4: 21.', 'Look at row 4: it is 12 + 3(3), and the 3 is one less than the row number.', 'So row 20 is 12 + 19(3) = 69. The table finds the pattern; the formula does the leap.'] },
      { title: 'Work backwards to check', steps: ['If row 20 really holds 69 seats, walk backwards 19 rows of 3.', '19 × 3 = 57, and 69 − 57 = 12.', 'That is exactly row 1, so the answer checks out.'] },
    ],
    tags: ['sequence', 'arithmetic', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 125, unit: 13, order: 5, slug: 'geometric-nth-term-formula',
    standard: 'PC.SEQ.A.1', difficulty: 2,
    prompt: 'A geometric sequence starts at $a_1 = 3$ and multiplies by $r = 2$ each step. Find $a_8$.',
    answerType: 'numeric', primaryAnswer: '384', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Use $a_n = a_1 \\times r^{\\,n-1}$. Again the exponent is one LESS than the term number.' },
      { level: 'guide', text: '$a_8 = 3 \\times 2^{7}$, and $2^7 = 128$.' },
      { level: 'reveal', text: '$3 \\times 128 = 384$.' },
    ],
    explanation: ['$a_n = a_1 \\times r^{\\,n-1}$.', '$a_8 = 3 \\times 2^{8-1} = 3 \\times 2^7$.', '$2^7 = 128$.', '$3 \\times 128 = 384$.'],
    alternativeExplanations: [
      { title: 'Just keep doubling', steps: ['3, 6, 12, 24, 48, 96, 192, 384.', 'Count them: that is eight terms, so the last one is a₈.', '384 — doubling by hand is quick when n is small, and it double-checks the formula.'] },
      { title: 'Count the multiplications', steps: ['Term 1 has been multiplied zero times. Term 2 once. Term 3 twice.', 'So term 8 has been multiplied 7 times — that is where the exponent 7 comes from.', '3 × 2⁷ = 3 × 128 = 384.'] },
    ],
    tags: ['sequence', 'geometric', 'formula'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 126, unit: 13, order: 6, slug: 'gauss-sum-one-to-hundred',
    standard: 'PC.SEQ.A.1', difficulty: 2,
    prompt: 'Young Carl Gauss was told to add every whole number from $1$ to $100$. He finished in seconds by pairing the ends. What is the sum?',
    answerType: 'numeric', primaryAnswer: '5050', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Pair the first with the last: $1 + 100$. Then $2 + 99$. Notice anything?' },
      { level: 'guide', text: 'Every pair adds to $101$, and $100$ numbers make $50$ pairs.' },
      { level: 'reveal', text: '$50 \\times 101 = 5050$.' },
    ],
    explanation: ['Use the shortcut: sum $= n \\times \\frac{\\text{first} + \\text{last}}{2}$.', 'Here $n = 100$, first $= 1$, last $= 100$.', '$100 \\times \\frac{101}{2} = 50 \\times 101$.', '$= 5050$.'],
    alternativeExplanations: [
      { title: 'Pair the ends, in pictures', steps: ['Write 1 to 100 in a row, then write the same row backwards underneath it.', 'Every column now adds to 101, and there are 100 columns: 100 × 101 = 10100.', 'But you wrote the list twice, so halve it: 10100 ÷ 2 = 5050.'] },
      { title: 'Test the trick on a tiny list', steps: ['Add 1 to 10 the slow way: 1 + 2 + … + 10 = 55.', 'Now the shortcut: 10 × (1 + 10) ÷ 2 = 10 × 11 ÷ 2 = 55. It matches.', 'A trick that works on a list you can check by hand is a trick you can trust on 100 numbers.'] },
    ],
    tags: ['series', 'arithmetic', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 127, unit: 13, order: 7, slug: 'can-pyramid-total',
    standard: 'PC.SEQ.A.1', difficulty: 2,
    prompt: 'Cans are stacked in a pyramid. The bottom row has $20$ cans, each row above has one fewer can, and the top row has $1$ can. How many cans are in the whole stack?',
    answerType: 'numeric', primaryAnswer: '210', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The rows are $20, 19, 18, \\dots, 1$. That is an arithmetic list, so you can pair the ends.' },
      { level: 'guide', text: 'There are $n = 20$ rows, the first is $20$ and the last is $1$. Sum $= 20 \\times \\frac{20 + 1}{2}$.' },
      { level: 'reveal', text: '$20 \\times \\frac{21}{2} = 10 \\times 21 = 210$ cans.' },
    ],
    explanation: ['The rows form the arithmetic list $20, 19, \\dots, 2, 1$.', 'A series is the SUM of a sequence, and the shortcut is $n \\times \\frac{\\text{first} + \\text{last}}{2}$.', '$20 \\times \\frac{20 + 1}{2} = 20 \\times 10.5$.', '$= 210$ cans.'],
    alternativeExplanations: [
      { title: 'Pair the ends by hand', steps: ['Pair the bottom row with the top: 20 + 1 = 21. Next pair in: 19 + 2 = 21. Then 18 + 3 = 21.', 'Twenty rows make ten pairs, and every pair totals 21.', '10 × 21 = 210 cans.'] },
      { title: 'Two pyramids make a rectangle', steps: ['Build a second identical pyramid, flip it upside down, and push it against the first.', 'Every row now holds 20 + 1 = 21 cans, and there are 20 rows: 420 cans.', 'That is two pyramids, so one pyramid is 420 ÷ 2 = 210.'] },
    ],
    tags: ['series', 'arithmetic', 'word-problem'], estimatedSeconds: 60,
  },
  {
    domain: 'PC', num: 128, unit: 13, order: 8, slug: 'weekly-savings-total',
    standard: 'PC.SEQ.A.1', difficulty: 3,
    prompt: 'In week $1$ you save $5$ dollars. Every week after that you save $5$ dollars more than the week before, so week $2$ is $10$ and week $3$ is $15$. How many dollars have you saved in total after $12$ weeks?',
    answerType: 'numeric', primaryAnswer: '390', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You need a SERIES — the sum of the weekly amounts, not just week $12$ by itself.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Do the same job for just $4$ weeks: the savings are $5, 10, 15, 20$. Pair the ends: $5 + 20 = 25$ and $10 + 15 = 25$, giving $2 \\times 25 = 50$. The shortcut says $4 \\times \\frac{5 + 20}{2} = 50$ too. Now run those exact steps for $12$ weeks.' },
      { level: 'guide', text: 'First find the last term: week $12$ saves $5 + 11 \\times 5 = 60$ dollars. Now you have first $= 5$, last $= 60$, $n = 12$.' },
      { level: 'reveal', text: 'Sum $= 12 \\times \\frac{5 + 60}{2} = 6 \\times 65 = 390$ dollars.' },
    ],
    explanation: ['Step 1 — find the last term with $a_n = a_1 + (n-1)d$: $a_{12} = 5 + 11 \\times 5 = 60$.', 'Step 2 — add the list with the pair-the-ends shortcut: sum $= n \\times \\frac{\\text{first} + \\text{last}}{2}$.', '$12 \\times \\frac{5 + 60}{2} = 12 \\times 32.5$.', '$= 390$ dollars.'],
    alternativeExplanations: [
      { title: 'Pair the ends yourself', steps: ['The weeks are 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60.', 'Pair first with last: 5 + 60 = 65. Next pair: 10 + 55 = 65. Every pair makes 65.', 'Twelve numbers make six pairs: 6 × 65 = 390 dollars.'] },
      { title: 'Factor out the 5', steps: ['Every amount is a multiple of 5: the list is 5 × (1, 2, 3, …, 12).', 'Add 1 through 12 first using Gauss\'s trick: 12 × 13 ÷ 2 = 78.', 'Now multiply back: 5 × 78 = 390 dollars.'] },
    ],
    tags: ['series', 'arithmetic', 'word-problem'], estimatedSeconds: 80,
  },
  {
    domain: 'PC', num: 129, unit: 13, order: 9, slug: 'bouncing-ball-total-rise',
    standard: 'PC.SEQ.A.1', difficulty: 3,
    prompt: 'A ball bounces back to half its height every time. It rises $16$ cm, then $8$ cm, then $4$ cm, and so on forever. What is the total rise distance, in centimeters?',
    answerType: 'numeric', primaryAnswer: '32', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'This is a geometric series with $a_1 = 16$ and $r = \\frac{1}{2}$. Because the terms SHRINK, the running total creeps toward a limit.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try $a_1 = 1$ with $r = \\frac{1}{2}$: $1 + \\frac{1}{2} + \\frac{1}{4} + \\frac{1}{8} + \\dots$ The running totals are $1, 1.5, 1.75, 1.875, \\dots$ creeping toward $2$. The rule $\\frac{a_1}{1 - r}$ gives $\\frac{1}{0.5} = 2$. Now use the same rule with $a_1 = 16$.' },
      { level: 'guide', text: 'For a shrinking geometric series, the total is $\\frac{a_1}{1 - r} = \\frac{16}{1 - \\frac{1}{2}}$.' },
      { level: 'reveal', text: '$\\frac{16}{0.5} = 32$ cm.' },
    ],
    explanation: ['The rises are $16, 8, 4, 2, 1, \\dots$ — geometric with $r = \\frac{1}{2}$.', 'When $r$ is between $-1$ and $1$, the pieces shrink so fast that the sum settles on a limit.', 'Total $= \\frac{a_1}{1 - r} = \\frac{16}{1 - 0.5} = \\frac{16}{0.5}$.', '$= 32$ cm.'],
    alternativeExplanations: [
      { title: 'Watch the running total', steps: ['Add as you go: 16, then 24, then 28, then 30, then 31, then 31.5, then 31.75.', 'Each new bounce closes HALF the remaining gap to 32, so the total never passes 32.', 'The list is heading to 32 — that is exactly what a limit means.'] },
      { title: 'Walking halfway to the wall', steps: ['Stand 32 cm from a wall and step half the remaining distance each time: 16, then 8, then 4.', 'You add up infinitely many steps but you only ever cover the original 32 cm.', 'Infinitely many pieces can still add to a plain, finite number — as long as they shrink fast enough.'] },
    ],
    tags: ['series', 'geometric', 'limit', 'word-problem'], estimatedSeconds: 85,
  },
  {
    domain: 'PC', num: 130, unit: 13, order: 10, slug: 'chain-message-total-sent',
    standard: 'PC.SEQ.A.1', difficulty: 3,
    prompt: 'A chain message spreads. On day $1$, $2$ messages are sent. Every day after that, the number of messages sent DOUBLES. How many messages are sent in total over the first $6$ days?',
    answerType: 'numeric', primaryAnswer: '126', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The daily counts are $2, 4, 8, 16, \\dots$ — geometric with $r = 2$. You need their SUM.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Do just $3$ days first: $2 + 4 + 8 = 14$. Check it with the geometric sum rule $S_n = a_1 \\times \\frac{r^n - 1}{r - 1} = 2 \\times \\frac{8 - 1}{1} = 14$. It matches, so now run the rule with $n = 6$.' },
      { level: 'guide', text: '$S_6 = 2 \\times \\frac{2^6 - 1}{2 - 1} = 2 \\times (64 - 1)$.' },
      { level: 'reveal', text: '$2 \\times 63 = 126$ messages.' },
    ],
    explanation: ['The daily counts form a geometric sequence: $2, 4, 8, 16, 32, 64$.', 'A series is the sum, so use $S_n = a_1 \\times \\frac{r^n - 1}{r - 1}$.', '$S_6 = 2 \\times \\frac{2^6 - 1}{2 - 1} = 2 \\times 63$.', '$= 126$ messages.'],
    alternativeExplanations: [
      { title: 'Just add the six days', steps: ['Write the days out: 2, 4, 8, 16, 32, 64.', 'Add them left to right: 6, 14, 30, 62, 126.', '126 messages — and notice each running total is exactly one less than the next day\'s count.'] },
      { title: 'One less than the next term', steps: ['Look at the running totals: 2, 6, 14, 30, 62, 126.', 'Compare each to the next day\'s count: 4, 8, 16, 32, 64, 128. Every total is one short.', 'So the six-day total is 128 − 2 = 126. That "one short" pattern IS the formula, in disguise.'] },
    ],
    tags: ['series', 'geometric', 'word-problem'], estimatedSeconds: 85,
  },

  // ---------------- UNIT 14 — Intro to limits & rate of change ----------------
  {
    domain: 'PC', num: 131, unit: 14, order: 1, slug: 'limit-by-substitution',
    standard: 'PC.LIM.A.1', difficulty: 1,
    prompt: 'As $x \\to 2$, what value does $3x + 1$ approach?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A limit asks "where is this heading?" For a smooth, unbroken rule you can just walk right in and substitute.' },
      { level: 'guide', text: 'Put $x = 2$ into $3x + 1$: that is $3(2) + 1$.' },
      { level: 'reveal', text: '$6 + 1 = 7$.' },
    ],
    explanation: ['This rule has no holes and no breaks near $x = 2$.', 'When nothing is broken, the limit is just the value: substitute.', '$3(2) + 1 = 6 + 1$.', '$= 7$.'],
    alternativeExplanations: [
      { title: 'Sneak up with a table', steps: ['Try x = 1.9: 3(1.9) + 1 = 6.7. Try x = 1.99: 6.97. Try x = 1.999: 6.997.', 'Now from above: x = 2.1 gives 7.3, and x = 2.01 gives 7.03.', 'Both sides are squeezing toward the same number, 7. That is the limit.'] },
      { title: 'Read it off the line', steps: ['y = 3x + 1 is a straight line with no gaps anywhere.', 'Walk your finger along the line toward x = 2 and watch the height.', 'The height arrives exactly at 7 — for an unbroken graph, "heading toward" and "lands on" are the same thing.'] },
    ],
    tags: ['limit', 'substitution'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 132, unit: 14, order: 2, slug: 'average-rate-of-change',
    standard: 'PC.LIM.A.1', difficulty: 1,
    prompt: 'A car is $30$ km from home at $1$ hour and $150$ km from home at $3$ hours. What is its average speed in km per hour?',
    answerType: 'numeric', primaryAnswer: '60', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Average rate of change is just the SLOPE between two points.' },
      { level: 'guide', text: 'Distance changed by $150 - 30 = 120$ km; time changed by $3 - 1 = 2$ hours.' },
      { level: 'reveal', text: '$120 \\div 2 = 60$ km per hour.' },
    ],
    explanation: ['Average rate of change = change in distance ÷ change in time.', '$(150 - 30) \\div (3 - 1) = 120 \\div 2$.', '$= 60$ km per hour.'],
    alternativeExplanations: [
      { title: 'As rise over run', steps: ['Plot (1, 30) and (3, 150). The rise is 120 and the run is 2.', 'Slope = 120/2 = 60 — the same slope formula from Algebra 1, wearing a new name.'] },
      { title: 'Average versus right now', steps: ['This 60 km/h is the AVERAGE over the whole two hours, like a trip summary.', 'The speedometer at one instant could read 40 or 90 — a limit is what finds that instant value.'] },
    ],
    tags: ['rate-of-change', 'word-problem'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 133, unit: 14, order: 3, slug: 'limit-from-a-table',
    standard: 'PC.LIM.A.1', difficulty: 1,
    prompt: 'A function $f$ has a hole at $x = 2$, but nearby it gives: $f(1.9) = 3.9$, $f(1.99) = 3.99$, $f(2.01) = 4.01$, $f(2.1) = 4.1$. What number is $f(x)$ heading toward as $x \\to 2$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A limit does not care whether the function LANDS there. It only asks where the values are heading.' },
      { level: 'guide', text: 'From the left the outputs climb $3.9, 3.99, \\dots$ From the right they fall $4.1, 4.01, \\dots$' },
      { level: 'reveal', text: 'Both sides squeeze toward $4$, so the limit is $4$.' },
    ],
    explanation: ['Read the table from the left: $3.9$, then $3.99$ — creeping up.', 'Read it from the right: $4.1$, then $4.01$ — creeping down.', 'The two sides are closing in on the same number.', 'The limit is $4$, even though there is a hole exactly at $x = 2$.'],
    alternativeExplanations: [
      { title: 'A hole in the road', steps: ['Picture a smooth road with one single missing brick at x = 2.', 'Drivers coming from each side can still see exactly where the brick SHOULD be.', 'That spot is 4 — the limit describes where the road is headed, not whether the brick is there.'] },
      { title: 'Measure the gap', steps: ['At x = 1.99 the output misses 4 by 0.01. At x = 2.01 it misses by 0.01 the other way.', 'Get ten times closer in x and the miss shrinks ten times too.', 'A gap you can make as small as you like means the target is 4.'] },
    ],
    tags: ['limit', 'table'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 134, unit: 14, order: 4, slug: 'limit-cancel-difference-of-squares',
    standard: 'PC.LIM.A.1', difficulty: 2,
    prompt: 'Find the limit of $\\frac{x^2 - 9}{x - 3}$ as $x \\to 3$.',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substituting gives $\\frac{0}{0}$, which is a signal — not an answer. Factor the top.' },
      { level: 'guide', text: '$x^2 - 9 = (x - 3)(x + 3)$, so the $(x - 3)$ on top cancels the one on the bottom.' },
      { level: 'reveal', text: 'What is left is $x + 3$, and at $x = 3$ that is $6$.' },
    ],
    explanation: ['Substituting $x = 3$ gives $\\frac{0}{0}$ — that means "keep working", not "no answer".', 'Factor the top as a difference of squares: $(x - 3)(x + 3)$.', 'Cancel the shared $(x - 3)$, leaving $x + 3$ everywhere except at the hole.', 'Now substitute: $3 + 3 = 6$.'],
    alternativeExplanations: [
      { title: 'Sneak up with a table', steps: ['x = 2.9: (8.41 − 9)/(−0.1) = 5.9. x = 2.99: 5.99.', 'x = 3.1: (9.61 − 9)/(0.1) = 6.1. x = 3.01: 6.01.', 'Both sides squeeze toward 6 — the table agrees with the cancelling.'] },
      { title: 'What the graph really looks like', steps: ['After cancelling, the picture is just the straight line y = x + 3.', 'The only difference is a tiny open circle punched out at x = 3.', 'The line passes through height 6 there, so the limit is 6 — the hole changes nothing about where you are headed.'] },
    ],
    tags: ['limit', 'factoring'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 135, unit: 14, order: 5, slug: 'runner-split-average-speed',
    standard: 'PC.LIM.A.1', difficulty: 2,
    prompt: 'A runner has covered $100$ m at $15$ seconds and $400$ m at $75$ seconds. What is her average speed between those two split times, in meters per second?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Average speed is the slope between the two split points: change in distance over change in time.' },
      { level: 'guide', text: 'Distance change: $400 - 100 = 300$ m. Time change: $75 - 15 = 60$ s.' },
      { level: 'reveal', text: '$300 \\div 60 = 5$ meters per second.' },
    ],
    explanation: ['Use average rate of change = change in distance ÷ change in time.', '$400 - 100 = 300$ meters.', '$75 - 15 = 60$ seconds.', '$300 \\div 60 = 5$ m/s.'],
    alternativeExplanations: [
      { title: 'Rise over run on a graph', steps: ['Plot (15, 100) and (75, 400) with time across and distance up.', 'Draw the straight line joining them: the rise is 300 and the run is 60.', 'Slope = 300 ÷ 60 = 5. Average speed IS the slope of that connecting line.'] },
      { title: 'Only the gap matters', steps: ['Do not divide 400 by 75 — that averages her whole race, starting gun included.', 'The question asks only about the stretch BETWEEN the two splits, so subtract both times and both distances first.', '300 m in 60 s is 5 m/s. The whole-race average is about 5.3 m/s, so subtracting first really does change the answer.'] },
    ],
    tags: ['rate-of-change', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 136, unit: 14, order: 6, slug: 'average-rate-of-change-parabola',
    standard: 'PC.LIM.A.1', difficulty: 2,
    prompt: 'For $f(x) = x^2$, find the average rate of change from $x = 1$ to $x = 4$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the two heights first, then take rise over run.' },
      { level: 'guide', text: '$f(1) = 1$ and $f(4) = 16$, so the rise is $16 - 1 = 15$ and the run is $4 - 1 = 3$.' },
      { level: 'reveal', text: '$15 \\div 3 = 5$.' },
    ],
    explanation: ['Average rate of change $= \\frac{f(4) - f(1)}{4 - 1}$.', '$f(4) = 16$ and $f(1) = 1$.', '$\\frac{16 - 1}{4 - 1} = \\frac{15}{3}$.', '$= 5$.'],
    alternativeExplanations: [
      { title: 'Draw the connecting line', steps: ['Plot (1, 1) and (4, 16) on the U-shaped graph of y = x².', 'Lay a ruler across those two points — that straight line is called a secant line.', 'Its slope, 15 over 3, is 5. Average rate of change is always the slope of the connecting line.'] },
      { title: 'Steeper and steeper', steps: ['From x = 1 to x = 2, the rise is 3 over a run of 1: rate 3.', 'From x = 2 to x = 3 the rate is 5, and from x = 3 to x = 4 it is 7.', 'The three rates average to (3 + 5 + 7) ÷ 3 = 5 — the same answer, and it shows the curve steepening as you go right.'] },
    ],
    tags: ['rate-of-change', 'function'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 137, unit: 14, order: 7, slug: 'limit-cancel-trinomial',
    standard: 'PC.LIM.A.1', difficulty: 2,
    prompt: 'Find the limit of $\\frac{x^2 - 7x + 10}{x - 2}$ as $x \\to 2$.',
    answerType: 'numeric', primaryAnswer: '-3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substituting gives $\\frac{0}{0}$. Factor the top and look for a matching $(x - 2)$.' },
      { level: 'guide', text: 'Hunt two numbers that multiply to $10$ and add to $-7$: they are $-2$ and $-5$, so the top is $(x - 2)(x - 5)$.' },
      { level: 'reveal', text: 'Cancel $(x - 2)$ to leave $x - 5$. At $x = 2$ that is $2 - 5 = -3$.' },
    ],
    explanation: ['At $x = 2$ both top and bottom are $0$, so there is a hole, not a wall.', 'Factor: $x^2 - 7x + 10 = (x - 2)(x - 5)$.', 'Cancel the shared $(x - 2)$: what is left is $x - 5$.', 'Substitute: $2 - 5 = -3$.'],
    alternativeExplanations: [
      { title: 'Sneak up from both sides', steps: ['At x = 1.9 the fraction gives (3.61 − 13.3 + 10)/(−0.1) = −3.1.', 'At x = 2.1 it gives (4.41 − 14.7 + 10)/(0.1) = −2.9.', 'The two sides squeeze toward −3 — the table confirms the cancelling.'] },
      { title: 'Why a factor must cancel', steps: ['Plugging in x = 2 made the top zero, which means (x − 2) is one of its factors.', 'So the top and bottom share that factor, and sharing is exactly what makes a hole instead of a wall.', 'Peel the shared factor off and the leftover, x − 5, hands you the height of the hole: −3.'] },
    ],
    tags: ['limit', 'factoring'], estimatedSeconds: 60,
  },
  {
    domain: 'PC', num: 138, unit: 14, order: 8, slug: 'zoom-in-instant-slope',
    standard: 'PC.LIM.A.1', difficulty: 3,
    prompt: 'On a graphing app you zoom in on $f(x) = x^2$ at the point $x = 3$ until the curve looks like a straight line. The average rates of change from $x = 3$ to $x = 3.1$, then to $3.01$, then to $3.001$ come out as $6.1$, $6.01$, and $6.001$. What number are those rates heading toward?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Read the list like a limit: where are $6.1, 6.01, 6.001$ going?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Do the same squeeze at $x = 1$ on $f(x) = x^2$. From $1$ to $1.1$ the rate is $\\frac{1.21 - 1}{0.1} = 2.1$; from $1$ to $1.01$ it is $2.01$. Those head to $2$. Notice $2$ is double the $x$-value. Now read your own list the same way.' },
      { level: 'guide', text: 'Each time the second point moves ten times closer, the rate gets ten times closer to a single number.' },
      { level: 'reveal', text: 'The rates squeeze down to $6$ — the INSTANT rate of change at $x = 3$.' },
    ],
    explanation: ['The average rate between two points is the slope of the line joining them.', 'As the second point slides toward $x = 3$, the extra bit shrinks: $6.1 \\to 6.01 \\to 6.001$.', 'The leftovers $0.1, 0.01, 0.001$ are being squeezed to nothing.', 'The limit is $6$: the slope of the curve at that exact instant.'],
    alternativeExplanations: [
      { title: 'Do the algebra once', steps: ['Take a step of size h: the rate is ((3 + h)² − 9) ÷ h.', 'Expand the top: 9 + 6h + h² − 9 = 6h + h². Divide by h to get 6 + h.', 'Now let h shrink to 0 and the answer is plainly 6 — the h was the whole "extra bit" in 6.1 and 6.01.'] },
      { title: 'Keep zooming on the map', steps: ['Zooming into a curve is like zooming into a map of a curved coastline.', 'Zoom far enough and any smooth curve stops looking curved and looks like one straight street.', 'The slope of that street is the instant rate: 6. That is the exact idea calculus is built on.'] },
    ],
    tags: ['limit', 'rate-of-change', 'word-problem'], estimatedSeconds: 85,
  },
  {
    domain: 'PC', num: 139, unit: 14, order: 9, slug: 'temperature-settling-limit',
    standard: 'PC.LIM.A.1', difficulty: 3,
    prompt: 'Overnight, a room\'s temperature after $t$ hours is $T = 18 + \\frac{6}{t}$ degrees. As $t$ gets larger and larger, what temperature is the room settling toward, in degrees?',
    answerType: 'numeric', primaryAnswer: '18', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Watch the piece $\\frac{6}{t}$. What happens to it when $t$ becomes huge?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Look at $\\frac{1}{t}$ alone: at $t = 10$ it is $0.1$, at $t = 100$ it is $0.01$, at $t = 1000$ it is $0.001$. Bigger bottom means a tinier fraction, heading to $0$. Now do the same with $\\frac{6}{t}$ and add the $18$ back on.' },
      { level: 'guide', text: 'At $t = 6$, $\\frac{6}{t} = 1$; at $t = 60$ it is $0.1$; at $t = 600$ it is $0.01$. It is fading to $0$.' },
      { level: 'reveal', text: 'The temperature heads to $18 + 0 = 18$ degrees.' },
    ],
    explanation: ['Split the rule into two pieces: a fixed $18$ and a fading $\\frac{6}{t}$.', 'A fixed top over a growing bottom shrinks toward $0$: $1$, then $0.1$, then $0.01$.', 'So the whole thing heads to $18 + 0$.', 'The room settles at $18$ degrees — it gets closer and closer without ever quite landing.'],
    alternativeExplanations: [
      { title: 'A table of the night', steps: ['t = 1: 24 degrees. t = 2: 21. t = 3: 20. t = 6: 19.', 't = 12: 18.5. t = 60: 18.1. t = 600: 18.01.', 'Every row is closer to 18 than the one before, and none ever dips below it. The limit is 18.'] },
      { title: 'Read it off the graph', steps: ['Sketch the curve: it starts high and slides down, flattening out as it goes right.', 'Draw a horizontal line at 18 — the curve hugs it more and more tightly but never crosses.', 'That line is called an asymptote, and its height is the limit: 18 degrees.'] },
    ],
    tags: ['limit', 'asymptote', 'word-problem'], estimatedSeconds: 80,
  },
  {
    domain: 'PC', num: 140, unit: 14, order: 10, slug: 'speedometer-instant-speed',
    standard: 'PC.LIM.A.1', difficulty: 3,
    prompt: 'A car\'s distance is $d = 5t^2$ meters after $t$ seconds. Its average speed from $t = 2$ to $t = 2.1$ is $20.5$ m/s, and from $t = 2$ to $t = 2.01$ it is $20.05$ m/s. What does the speedometer read at exactly $t = 2$, in meters per second?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The averages are being squeezed. Read $20.5$ and $20.05$ like a limit and see where they land.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Same idea on $d = t^2$ at $t = 2$: from $2$ to $2.1$ the average is $\\frac{4.41 - 4}{0.1} = 4.1$; from $2$ to $2.01$ it is $4.01$. Those head to $4$. Now read your own two averages the same way.' },
      { level: 'guide', text: 'Each ten-times-smaller time window cuts the leftover by ten: $0.5$, then $0.05$, then $0.005$.' },
      { level: 'reveal', text: 'The leftovers vanish, so the speedometer reads $20$ m/s.' },
    ],
    explanation: ['Average speed over a window is the trip summary; the speedometer is the instant value.', 'Shrink the window: $20.5$, then $20.05$, then $20.005$.', 'The extra bits $0.5, 0.05, 0.005$ are being squeezed to $0$.', 'The limit is $20$ meters per second.'],
    alternativeExplanations: [
      { title: 'Do the algebra with a step h', steps: ['Over a step of size h the average is (5(2 + h)² − 20) ÷ h.', 'Expand: 5(4 + 4h + h²) − 20 = 20h + 5h². Divide by h to get 20 + 5h.', 'Let h shrink to 0 and only 20 survives — h = 0.1 gave 20.5 and h = 0.01 gave 20.05, exactly as predicted.'] },
      { title: 'Trip summary versus right now', steps: ['A 2-hour road trip averaging 60 km/h says nothing about any single moment — you stopped, you sped up.', 'Shrink the trip to a minute, then a second, then a blink, and the average has no room left to hide anything.', 'The number those shrinking averages settle on is the speedometer reading: 20 m/s here.'] },
    ],
    tags: ['limit', 'rate-of-change', 'word-problem'], estimatedSeconds: 90,
  },
];
