import type { SeedProblem } from './types';

// PC — Precalculus, Units 5-8: Exponential functions, Logarithms, Solving
// exponential & log equations, Right-triangle trigonometry. 10 problems per
// unit, nums 41-80. Difficulty-3 problems carry a titled "try a simpler one"
// nudge so a stuck kid gets an easier parallel case before the real help.

export const problemsPCu05: SeedProblem[] = [
  // ---------------- UNIT 5 — Exponential functions (PC.EXP.A.1) ----------------
  {
    domain: 'PC', num: 41, unit: 5, order: 1, slug: 'exp-start-value',
    standard: 'PC.EXP.A.1', difficulty: 1,
    prompt: 'Every exponential function looks like $y = a \\cdot b^x$. The number $a$ is the START. In $y = 5 \\cdot 3^x$, what is the start value?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The START is the number sitting out front, before the power.' },
      { level: 'guide', text: 'Try $x = 0$. Since $3^0 = 1$, you get $y = 5 \\times 1$.' },
      { level: 'reveal', text: 'The start value is $5$.' },
    ],
    explanation: ['An exponential function has two jobs packed into $y = a \\cdot b^x$.', 'The front number $a$ is where you START, before any steps happen.', 'Here $a = 5$, so the start value is $5$.'],
    alternativeExplanations: [
      { title: 'Plug in zero', steps: ['The start happens at $x = 0$ — zero steps taken.', '$y = 5 \\cdot 3^0$, and anything to the zero power is $1$.', 'So $y = 5 \\times 1 = 5$.'] },
    ],
    tags: ['exponential', 'start-value'], estimatedSeconds: 25,
  },
  {
    domain: 'PC', num: 42, unit: 5, order: 2, slug: 'exp-growth-factor-read',
    standard: 'PC.EXP.A.1', difficulty: 1,
    prompt: 'In $y = 200 \\cdot 1.5^x$, what is the growth factor — the number you multiply by at each step?',
    answerType: 'numeric', primaryAnswer: '1.5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The growth factor is the base — the number being raised to the power $x$.' },
      { level: 'guide', text: 'In $y = a \\cdot b^x$, the factor is $b$. Which number is in the $b$ spot?' },
      { level: 'reveal', text: 'The base is $1.5$, so the growth factor is $1.5$.' },
    ],
    explanation: ['In $y = a \\cdot b^x$, the base $b$ is the GROWTH FACTOR.', 'It answers one question: what do I multiply by each step?', 'Here the base is $1.5$, so you multiply by $1.5$ every step.'],
    alternativeExplanations: [
      { title: 'Watch one step happen', steps: ['At $x = 0$ you have $200$. At $x = 1$ you have $200 \\times 1.5 = 300$.', 'Compare: $300 \\div 200 = 1.5$.', 'The number you multiply by is $1.5$ — the growth factor.'] },
    ],
    tags: ['exponential', 'growth-factor'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 43, unit: 5, order: 3, slug: 'exp-evaluate-power',
    standard: 'PC.EXP.A.1', difficulty: 1,
    prompt: 'Evaluate $y = 4 \\cdot 2^x$ when $x = 3$.',
    answerType: 'numeric', primaryAnswer: '32', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Do the power FIRST, then multiply by the start.' },
      { level: 'guide', text: '$2^3 = 2 \\times 2 \\times 2 = 8$. Now multiply by $4$.' },
      { level: 'reveal', text: '$4 \\times 8 = 32$.' },
    ],
    explanation: ['Powers come before multiplying.', '$2^3 = 8$.', '$4 \\times 8 = 32$, so $y = 32$.'],
    alternativeExplanations: [
      { title: 'Take the steps one at a time', steps: ['Start at $4$.', 'Step 1: $4 \\times 2 = 8$. Step 2: $8 \\times 2 = 16$. Step 3: $16 \\times 2 = 32$.', 'Three steps of doubling land on $32$.'] },
    ],
    tags: ['exponential', 'evaluate'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 44, unit: 5, order: 4, slug: 'exp-bacteria-doubling-4-hours',
    standard: 'PC.EXP.A.1', difficulty: 2,
    prompt: 'A dish starts with $50$ bacteria. The number DOUBLES every hour. How many bacteria are there after $4$ hours?',
    answerType: 'numeric', primaryAnswer: '800', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Doubling means the growth factor is $2$. The start is $50$.' },
      { level: 'guide', text: 'Use $y = 50 \\cdot 2^x$ with $x = 4$. First find $2^4$.' },
      { level: 'reveal', text: '$2^4 = 16$, and $50 \\times 16 = 800$ bacteria.' },
    ],
    explanation: ['Start $a = 50$, growth factor $b = 2$, steps $x = 4$.', '$y = 50 \\cdot 2^4$.', '$2^4 = 16$, so $y = 50 \\times 16 = 800$ bacteria.'],
    alternativeExplanations: [
      { title: 'Make an hour-by-hour table', steps: ['Hour 0: $50$. Hour 1: $100$. Hour 2: $200$.', 'Hour 3: $400$. Hour 4: $800$.', 'Doubling four times gets you to $800$.'] },
    ],
    tags: ['exponential', 'doubling', 'word-problem'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 45, unit: 5, order: 5, slug: 'exp-savings-percent-to-factor',
    standard: 'PC.EXP.A.1', difficulty: 2,
    prompt: 'A savings account grows by $8\\%$ each year. What is the growth factor you multiply by each year? (For example, up $5\\%$ is $1.05$.)',
    answerType: 'numeric', primaryAnswer: '1.08', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You keep everything you had — that is $100\\%$ — and then add more.' },
      { level: 'guide', text: '$100\\% + 8\\% = 108\\%$. Now turn $108\\%$ into a decimal.' },
      { level: 'reveal', text: '$108\\% = 1.08$, so the growth factor is $1.08$.' },
    ],
    explanation: ['Growing by $8\\%$ means you keep all $100\\%$ AND gain $8\\%$ more.', 'Together that is $108\\%$ of what you had.', '$108\\% = 1.08$, so multiply by $1.08$ each year.'],
    alternativeExplanations: [
      { title: 'Try it on \\$100', steps: ['Put $\\$100$ in. Eight percent of $\\$100$ is $\\$8$.', 'Now you have $\\$108$.', '$108 \\div 100 = 1.08$ — that is the factor.'] },
    ],
    tags: ['exponential', 'percent-to-factor', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 46, unit: 5, order: 6, slug: 'exp-followers-two-weeks',
    standard: 'PC.EXP.A.1', difficulty: 2,
    prompt: 'You have $200$ followers and gain $10\\%$ more each week. How many followers do you have after $2$ weeks?',
    answerType: 'numeric', primaryAnswer: '242', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Up $10\\%$ means the growth factor is $1.1$.' },
      { level: 'guide', text: 'Week 1: $200 \\times 1.1 = 220$. Now grow $220$ by another $10\\%$.' },
      { level: 'reveal', text: '$220 \\times 1.1 = 242$ followers.' },
    ],
    explanation: ['Up $10\\%$ gives a growth factor of $1.1$.', 'After week 1: $200 \\times 1.1 = 220$.', 'After week 2: $220 \\times 1.1 = 242$ followers.'],
    alternativeExplanations: [
      { title: 'Add the ten percent each time', steps: ['Ten percent of $200$ is $20$, so week 1 ends at $200 + 20 = 220$.', 'Ten percent of $220$ is $22$, so week 2 ends at $220 + 22 = 242$.', 'The second week adds MORE than the first — that is what exponential means.'] },
    ],
    tags: ['exponential', 'percent-growth', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 47, unit: 5, order: 7, slug: 'exp-medicine-decay-factor',
    standard: 'PC.EXP.A.1', difficulty: 2,
    prompt: 'Each hour, $20\\%$ of a medicine leaves your bloodstream. What is the decay factor you multiply by each hour?',
    answerType: 'numeric', primaryAnswer: '0.8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'If $20\\%$ leaves, ask what percent STAYS.' },
      { level: 'guide', text: '$100\\% - 20\\% = 80\\%$ stays. Turn $80\\%$ into a decimal.' },
      { level: 'reveal', text: '$80\\% = 0.8$, so the decay factor is $0.8$.' },
    ],
    explanation: ['A decay factor is about what is LEFT, not what left.', '$100\\% - 20\\% = 80\\%$ stays each hour.', '$80\\% = 0.8$, so multiply by $0.8$ every hour. Because $0.8$ is between $0$ and $1$, the amount shrinks.'],
    alternativeExplanations: [
      { title: 'Try it on 100 mg', steps: ['Start with $100$ mg. Twenty percent of $100$ is $20$ mg, which leaves.', 'What remains is $80$ mg.', '$80 \\div 100 = 0.8$ — that is the factor.'] },
    ],
    tags: ['exponential', 'decay', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 48, unit: 5, order: 8, slug: 'exp-phone-value-two-years',
    standard: 'PC.EXP.A.1', difficulty: 3,
    prompt: 'A phone costs $\\$600$ new. It loses $25\\%$ of its value every year. What is it worth after $2$ years, in dollars?',
    answerType: 'numeric', primaryAnswer: '337.5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Losing $25\\%$ means keeping $75\\%$. Turn that into a decay factor.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: a $\\$100$ item that loses $50\\%$ a year is worth $\\$50$ after one year and $\\$25$ after two. Same move — multiply by the keep-factor once per year.' },
      { level: 'guide', text: '$100\\% - 25\\% = 75\\% = 0.75$. Year 1: $600 \\times 0.75 = 450$.' },
      { level: 'reveal', text: 'Year 2: $450 \\times 0.75 = 337.5$, so the phone is worth $\\$337.50$.' },
    ],
    explanation: ['Losing $25\\%$ means $75\\%$ stays, so the decay factor is $0.75$.', 'After year 1: $600 \\times 0.75 = 450$.', 'After year 2: $450 \\times 0.75 = 337.5$ dollars.'],
    alternativeExplanations: [
      { title: 'Subtract a quarter each year', steps: ['A quarter of $600$ is $150$, so year 1 ends at $600 - 150 = 450$.', 'A quarter of $450$ is $112.50$, so year 2 ends at $450 - 112.50 = 337.50$.', 'The drop gets smaller each year because it is a percent of a smaller number.'] },
      { title: 'One power instead of two steps', steps: ['Two years of the same factor is $0.75^2$.', '$0.75 \\times 0.75 = 0.5625$.', '$600 \\times 0.5625 = 337.5$ dollars.'] },
    ],
    tags: ['exponential', 'decay', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'PC', num: 49, unit: 5, order: 9, slug: 'exp-colony-doubling-time',
    standard: 'PC.EXP.A.1', difficulty: 3,
    prompt: 'A colony of $100$ cells doubles every $3$ hours. How many cells are there after $12$ hours?',
    answerType: 'numeric', primaryAnswer: '1600', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The clock is in hours, but the growth happens in DOUBLINGS. Count the doublings first.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: something doubling every $2$ hours for $6$ hours doubles $6 \\div 2 = 3$ times. Same move — divide the total time by the doubling time.' },
      { level: 'guide', text: '$12 \\div 3 = 4$ doublings. Now compute $100 \\cdot 2^4$.' },
      { level: 'reveal', text: '$2^4 = 16$, so $100 \\times 16 = 1600$ cells.' },
    ],
    explanation: ['Doubling time is $3$ hours, so in $12$ hours there are $12 \\div 3 = 4$ doublings.', 'Each doubling multiplies by $2$, so multiply by $2^4 = 16$.', '$100 \\times 16 = 1600$ cells.'],
    alternativeExplanations: [
      { title: 'Walk the clock', steps: ['Hour 0: $100$. Hour 3: $200$. Hour 6: $400$.', 'Hour 9: $800$. Hour 12: $1600$.', 'Only the doubling moments matter, not every single hour.'] },
      { title: 'Write the formula first', steps: ['With doubling time $3$, the rule is $y = 100 \\cdot 2^{t/3}$.', 'Put in $t = 12$: the exponent is $12/3 = 4$.', '$100 \\cdot 2^4 = 100 \\times 16 = 1600$.'] },
    ],
    tags: ['exponential', 'doubling-time', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'PC', num: 50, unit: 5, order: 10, slug: 'exp-horizontal-asymptote-zero',
    standard: 'PC.EXP.A.1', difficulty: 3,
    prompt: 'The graph of $y = 12 \\cdot \\left(\\frac{1}{2}\\right)^x$ keeps dropping and hugs one horizontal line forever without ever touching it. What is the $y$-value of that line?',
    answerType: 'numeric', primaryAnswer: '0', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Keep halving $12$ out loud and listen to where the numbers are heading.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: halve $8$ over and over: $4, 2, 1, 0.5, 0.25, 0.125$. The numbers shrink toward one value but never land on it. Same move here.' },
      { level: 'guide', text: '$12, 6, 3, 1.5, 0.75, 0.375, \\ldots$ — the values get tiny but stay above one number.' },
      { level: 'reveal', text: 'They close in on $0$ without reaching it, so the horizontal asymptote is $y = 0$.' },
    ],
    explanation: ['Half of a positive number is still positive, so the values never hit zero.', 'But they shrink toward zero forever: $12, 6, 3, 1.5, 0.75, \\ldots$', 'That invisible floor is the HORIZONTAL ASYMPTOTE, $y = 0$.'],
    alternativeExplanations: [
      { title: 'Think about the pieces', steps: ['Imagine cutting a rope in half, then halving the piece you keep, again and again.', 'There is always some rope left, but it becomes too small to see.', 'The amount heads toward $0$ and never gets there — that is the asymptote.'] },
      { title: 'Read the formula', steps: ['$y = 12 \\cdot \\left(\\frac{1}{2}\\right)^x$ is a start times a positive factor.', 'A positive number times a positive number is always positive, so $y$ is never $0$ or negative.', 'Since nothing is added on the end, the values crowd down to $y = 0$.'] },
    ],
    tags: ['exponential', 'asymptote'], estimatedSeconds: 60,
  },

  // ---------------- UNIT 6 — Logarithms (PC.LOG.A.1) ----------------
  {
    domain: 'PC', num: 51, unit: 6, order: 1, slug: 'log-asks-what-power',
    standard: 'PC.LOG.A.1', difficulty: 1,
    prompt: 'Evaluate $\\log_2(32)$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The log is asking one question: $2$ to WHAT power gives $32$?' },
      { level: 'guide', text: 'Count the doublings: $2, 4, 8, 16, 32$.' },
      { level: 'reveal', text: '$2^5 = 32$, so $\\log_2(32) = 5$.' },
    ],
    explanation: ['A log asks for the exponent, and the answer IS the exponent.', '$2^5 = 32$.', 'So $\\log_2(32) = 5$.'],
    alternativeExplanations: [
      { title: 'Count the doublings', steps: ['Start at $1$ and keep doubling: $1, 2, 4, 8, 16, 32$ — that is $5$ doublings.', 'The number of doublings IS the logarithm.', 'So $\\log_2(32) = 5$.'] },
    ],
    tags: ['logarithm'], estimatedSeconds: 35,
  },
  {
    domain: 'PC', num: 52, unit: 6, order: 2, slug: 'log-game-coins-triple',
    standard: 'PC.LOG.A.1', difficulty: 1,
    prompt: 'In a video game your coins TRIPLE at the end of every level. You start with $1$ coin. After how many levels do you have $81$ coins?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'This is really asking $\\log_3(81)$: $3$ to what power gives $81$?' },
      { level: 'guide', text: 'Triple your way up: $1, 3, 9, 27, 81$.' },
      { level: 'reveal', text: '$3^4 = 81$, so it takes $4$ levels.' },
    ],
    explanation: ['Tripling each level means the coins follow $3^x$.', 'You need $3^x = 81$, which is the question $\\log_3(81)$ asks.', '$3 \\times 3 \\times 3 \\times 3 = 81$, so $x = 4$ levels.'],
    alternativeExplanations: [
      { title: 'Make a level list', steps: ['Level 1: $3$ coins. Level 2: $9$ coins.', 'Level 3: $27$ coins. Level 4: $81$ coins.', 'Counting the rows gives $4$ — a log is just counting the steps.'] },
    ],
    tags: ['logarithm', 'word-problem'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 53, unit: 6, order: 3, slug: 'log-base-10-of-1000',
    standard: 'PC.LOG.A.1', difficulty: 1,
    prompt: 'Evaluate $\\log_{10}(1000)$.',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Ask: $10$ to what power gives $1000$?' },
      { level: 'guide', text: '$10 \\times 10 \\times 10 = 1000$. How many tens did you use?' },
      { level: 'reveal', text: '$10^3 = 1000$, so $\\log_{10}(1000) = 3$.' },
    ],
    explanation: ['Base $10$ logs ask how many tens are multiplied together.', '$10^3 = 1000$.', 'So $\\log_{10}(1000) = 3$.'],
    alternativeExplanations: [
      { title: 'Count the zeros', steps: ['With base $10$, the answer is simply the number of zeros.', '$1000$ has three zeros.', 'So $\\log_{10}(1000) = 3$. Check: $100$ has two zeros and $\\log_{10}(100) = 2$.'] },
    ],
    tags: ['logarithm', 'base-ten'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 54, unit: 6, order: 4, slug: 'log-product-rule-add',
    standard: 'PC.LOG.A.1', difficulty: 2,
    prompt: 'You are told $\\log(2) = 0.301$ and $\\log(5) = 0.699$. Use the rule $\\log(AB) = \\log A + \\log B$ to find $\\log(10)$.',
    answerType: 'numeric', primaryAnswer: '1', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Notice that $2 \\times 5 = 10$. Multiplying inside a log turns into ADDING outside.' },
      { level: 'guide', text: '$\\log(10) = \\log(2 \\times 5) = \\log(2) + \\log(5)$.' },
      { level: 'reveal', text: '$0.301 + 0.699 = 1$, so $\\log(10) = 1$.' },
    ],
    explanation: ['The product rule says $\\log(AB) = \\log A + \\log B$: multiply inside, add outside.', 'Since $10 = 2 \\times 5$, write $\\log(10) = \\log(2) + \\log(5)$.', '$0.301 + 0.699 = 1$.'],
    alternativeExplanations: [
      { title: 'Check it the direct way', steps: ['A log asks: $10$ to what power gives $10$?', '$10^1 = 10$, so $\\log(10) = 1$.', 'The rule agrees, which is exactly why the rule is trustworthy.'] },
    ],
    tags: ['logarithm', 'product-rule'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 55, unit: 6, order: 5, slug: 'log-paper-folds-1024',
    standard: 'PC.LOG.A.1', difficulty: 2,
    prompt: 'Every time you fold a sheet of paper, the number of layers DOUBLES. You start with $1$ layer. How many folds does it take to reach $1024$ layers?',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The question is $\\log_2(1024)$: $2$ to what power gives $1024$?' },
      { level: 'guide', text: 'Double from $1$: $2, 4, 8, 16, 32, 64, 128, 256, 512, 1024$.' },
      { level: 'reveal', text: 'That is $10$ doublings, so $\\log_2(1024) = 10$ folds.' },
    ],
    explanation: ['Each fold multiplies the layers by $2$, so layers $= 2^{\\text{folds}}$.', 'You need $2^x = 1024$, which is the question $\\log_2(1024)$.', 'Counting doublings up to $1024$ gives $10$ folds.'],
    alternativeExplanations: [
      { title: 'Use a power you already know', steps: ['You may remember $2^{10} = 1024$ from computers — a kilobyte.', 'That instantly answers $2^x = 1024$.', 'So $x = 10$ folds.'] },
    ],
    tags: ['logarithm', 'doubling', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 56, unit: 6, order: 6, slug: 'log-power-rule-slide-out',
    standard: 'PC.LOG.A.1', difficulty: 2,
    prompt: 'Evaluate $\\log_2(8^3)$.',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'An exponent inside a log SLIDES OUT to the front: $\\log(A^n) = n \\cdot \\log A$.' },
      { level: 'guide', text: '$\\log_2(8^3) = 3 \\cdot \\log_2(8)$, and $\\log_2(8) = 3$.' },
      { level: 'reveal', text: '$3 \\times 3 = 9$.' },
    ],
    explanation: ['The power rule lets the exponent slide out front: $\\log_2(8^3) = 3 \\cdot \\log_2(8)$.', '$\\log_2(8) = 3$ because $2^3 = 8$.', '$3 \\times 3 = 9$.'],
    alternativeExplanations: [
      { title: 'Just multiply it out', steps: ['$8^3 = 8 \\times 8 \\times 8 = 512$.', 'Now ask: $2$ to what power gives $512$? Count doublings: $2, 4, 8, 16, 32, 64, 128, 256, 512$.', 'That is $9$ doublings, so the answer is $9$.'] },
    ],
    tags: ['logarithm', 'power-rule'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 57, unit: 6, order: 7, slug: 'log-richter-7-vs-4',
    standard: 'PC.LOG.A.1', difficulty: 2,
    prompt: 'On the Richter earthquake scale, each whole step up means $10$ times more shaking. How many times more shaking is a magnitude $7$ quake than a magnitude $4$ quake?',
    answerType: 'numeric', primaryAnswer: '1000', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First count the steps between $4$ and $7$.' },
      { level: 'guide', text: 'That is $7 - 4 = 3$ steps, and each step multiplies by $10$.' },
      { level: 'reveal', text: '$10^3 = 1000$ times more shaking.' },
    ],
    explanation: ['The Richter scale is a log scale, so the NUMBER is really an exponent.', 'From $4$ to $7$ is $3$ steps, and each step means $\\times 10$.', '$10 \\times 10 \\times 10 = 1000$ times more shaking.'],
    alternativeExplanations: [
      { title: 'Climb one step at a time', steps: ['Magnitude $4$ to $5$: $10$ times more.', 'Magnitude $5$ to $6$: $10$ times more again, now $100$.', 'Magnitude $6$ to $7$: $10$ times again, now $1000$.'] },
    ],
    tags: ['logarithm', 'log-scale', 'word-problem'], estimatedSeconds: 50,
  },
  {
    domain: 'PC', num: 58, unit: 6, order: 8, slug: 'log-decibels-concert-whisper',
    standard: 'PC.LOG.A.1', difficulty: 3,
    prompt: 'Loudness in decibels is $10 \\times \\log_{10}$ of the sound intensity. A concert is $1{,}000{,}000$ times as intense as a whisper. How many decibels louder is the concert?',
    answerType: 'numeric', primaryAnswer: '60', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find $\\log_{10}(1{,}000{,}000)$ first, then multiply by $10$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: if a sound were $100$ times as intense, then $\\log_{10}(100) = 2$ and $10 \\times 2 = 20$ decibels louder. Same two moves, bigger number.' },
      { level: 'guide', text: '$1{,}000{,}000$ has six zeros, so $\\log_{10}(1{,}000{,}000) = 6$.' },
      { level: 'reveal', text: '$10 \\times 6 = 60$ decibels louder.' },
    ],
    explanation: ['A million is $10^6$, so $\\log_{10}(1{,}000{,}000) = 6$.', 'Decibels multiply that log by $10$.', '$10 \\times 6 = 60$ decibels louder.'],
    alternativeExplanations: [
      { title: 'Count the zeros', steps: ['With base $10$, the log is just the number of zeros.', '$1{,}000{,}000$ has six zeros, so the log is $6$.', 'Decibels are ten times that: $60$.'] },
      { title: 'Ten decibels at a time', steps: ['Every $\\times 10$ in intensity adds exactly $10$ decibels.', 'A million is six tens multiplied together.', 'Six of those jumps add $6 \\times 10 = 60$ decibels.'] },
    ],
    tags: ['logarithm', 'log-scale', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'PC', num: 59, unit: 6, order: 9, slug: 'log-quotient-rule-subtract',
    standard: 'PC.LOG.A.1', difficulty: 3,
    prompt: 'Evaluate $\\log_2(96) - \\log_2(3)$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Subtracting logs means DIVIDING inside: $\\log A - \\log B = \\log\\left(\\frac{A}{B}\\right)$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: $\\log_2(16) - \\log_2(2) = \\log_2(8) = 3$. Same move — divide inside first, then ask the log question once.' },
      { level: 'guide', text: 'Combine into one log: $\\log_2\\left(\\frac{96}{3}\\right) = \\log_2(32)$.' },
      { level: 'reveal', text: '$2^5 = 32$, so the answer is $5$.' },
    ],
    explanation: ['The quotient rule: subtracting logs is dividing inside.', '$\\log_2(96) - \\log_2(3) = \\log_2\\left(\\frac{96}{3}\\right) = \\log_2(32)$.', '$2^5 = 32$, so the answer is $5$.'],
    alternativeExplanations: [
      { title: 'Break 96 into friendly pieces', steps: ['$96 = 32 \\times 3$, so $\\log_2(96) = \\log_2(32) + \\log_2(3)$.', 'Now subtract $\\log_2(3)$ from both sides — it cancels out.', 'What is left is $\\log_2(32) = 5$.'] },
      { title: 'Undo twins', steps: ['Logs turn multiplying into adding, and dividing into subtracting.', 'So a subtraction outside must be a division inside: $96 \\div 3 = 32$.', 'Count doublings to $32$: $2, 4, 8, 16, 32$ — five of them.'] },
    ],
    tags: ['logarithm', 'quotient-rule'], estimatedSeconds: 65,
  },
  {
    domain: 'PC', num: 60, unit: 6, order: 10, slug: 'log-ph-lemon-vs-water',
    standard: 'PC.LOG.A.1', difficulty: 3,
    prompt: 'On the pH scale, each step DOWN means $10$ times more acidic. Lemon juice has pH $2$ and pure water has pH $7$. How many times more acidic is lemon juice than water?',
    answerType: 'numeric', primaryAnswer: '100000', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count the steps between pH $7$ and pH $2$ first.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: pH $6$ versus pH $4$ is $2$ steps, so $10^2 = 100$ times more acidic. Same move — count steps, then raise $10$ to that many.' },
      { level: 'guide', text: '$7 - 2 = 5$ steps, and each step is $\\times 10$. Compute $10^5$.' },
      { level: 'reveal', text: '$10^5 = 100000$, so lemon juice is $100{,}000$ times more acidic.' },
    ],
    explanation: ['pH is a log scale, so each whole number is one power of ten.', 'From pH $7$ down to pH $2$ is $5$ steps.', '$10^5 = 100000$ times more acidic.'],
    alternativeExplanations: [
      { title: 'Walk down the scale', steps: ['pH $7$ to $6$: $10$ times. To $5$: $100$ times. To $4$: $1000$ times.', 'To $3$: $10{,}000$ times. To $2$: $100{,}000$ times.', 'Five steps, five zeros.'] },
      { title: 'Write it as one subtraction', steps: ['Acidity compares as $10^{7-2}$.', 'The exponent is $7 - 2 = 5$.', '$10^5 = 100000$.'] },
    ],
    tags: ['logarithm', 'log-scale', 'word-problem'], estimatedSeconds: 70,
  },

  // ------- UNIT 7 — Solving exponential & log equations (PC.LOG.A.2) -------
  {
    domain: 'PC', num: 61, unit: 7, order: 1, slug: 'solve-same-base-2x-32',
    standard: 'PC.LOG.A.2', difficulty: 1,
    prompt: 'Solve for $x$: $2^x = 32$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Try writing $32$ as a power of $2$ so both sides share a base.' },
      { level: 'guide', text: '$32 = 2^5$, so the equation says $2^x = 2^5$.' },
      { level: 'reveal', text: 'Same base means the exponents match: $x = 5$.' },
    ],
    explanation: ['The same-base trick: make both sides powers of the SAME base.', '$32 = 2^5$, so $2^x = 2^5$.', 'If the bases match, the exponents must match: $x = 5$.'],
    alternativeExplanations: [
      { title: 'Count the doublings', steps: ['Start at $1$ and double: $2, 4, 8, 16, 32$.', 'That took $5$ doublings.', 'So $x = 5$.'] },
      { title: 'Take a log of both sides', steps: ['Apply $\\log_2$ to both sides: $\\log_2(2^x) = \\log_2(32)$.', 'A log and a power with the same base undo each other, so the left side is just $x$.', '$\\log_2(32) = 5$, so $x = 5$.'] },
    ],
    tags: ['exponential-equation', 'same-base'], estimatedSeconds: 35,
  },
  {
    domain: 'PC', num: 62, unit: 7, order: 2, slug: 'solve-same-base-5x-625',
    standard: 'PC.LOG.A.2', difficulty: 1,
    prompt: 'Solve for $x$: $5^x = 625$.',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Keep multiplying by $5$ and see how many it takes to reach $625$.' },
      { level: 'guide', text: '$5, 25, 125, 625$ — count them.' },
      { level: 'reveal', text: '$5^4 = 625$, so $x = 4$.' },
    ],
    explanation: ['Write $625$ as a power of $5$.', '$5 \\times 5 \\times 5 \\times 5 = 625$, so $625 = 5^4$.', 'Now $5^x = 5^4$, so $x = 4$.'],
    alternativeExplanations: [
      { title: 'Build it in two chunks', steps: ['$5^2 = 25$, and $25 \\times 25 = 625$.', 'So $625 = 5^2 \\times 5^2 = 5^4$.', 'Matching exponents gives $x = 4$.'] },
      { title: 'Ask the log question', steps: ['The equation is the same as $x = \\log_5(625)$.', 'A log asks: $5$ to what power gives $625$?', 'The answer is $4$.'] },
    ],
    tags: ['exponential-equation', 'same-base'], estimatedSeconds: 35,
  },
  {
    domain: 'PC', num: 63, unit: 7, order: 3, slug: 'solve-log-to-exponential-form',
    standard: 'PC.LOG.A.2', difficulty: 1,
    prompt: 'Solve for $x$: $\\log_4(x) = 3$.',
    answerType: 'numeric', primaryAnswer: '64', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Rewrite the log in exponential form. The base stays the base, and the answer becomes the exponent.' },
      { level: 'guide', text: '$\\log_4(x) = 3$ means $4^3 = x$.' },
      { level: 'reveal', text: '$4^3 = 64$, so $x = 64$.' },
    ],
    explanation: ['A log equation flips into an exponential one.', '$\\log_4(x) = 3$ says: $4$ raised to the $3$ gives $x$.', '$4 \\times 4 \\times 4 = 64$, so $x = 64$.'],
    alternativeExplanations: [
      { title: 'Read it as a sentence', steps: ['Say it out loud: "$4$ to WHAT power is $x$? The answer is $3$."', 'So $x$ must be $4$ multiplied by itself $3$ times.', '$4 \\times 4 \\times 4 = 64$.'] },
      { title: 'Undo with a power', steps: ['Logs and exponents are undo twins.', 'Raise $4$ to both sides: $4^{\\log_4(x)} = 4^3$.', 'The left side collapses to $x$, so $x = 64$.'] },
    ],
    tags: ['log-equation', 'exponential-form'], estimatedSeconds: 40,
  },
  {
    domain: 'PC', num: 64, unit: 7, order: 4, slug: 'solve-exponent-shifted',
    standard: 'PC.LOG.A.2', difficulty: 2,
    prompt: 'Solve for $x$: $2^{x+1} = 16$.',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Write $16$ as a power of $2$ so both sides match.' },
      { level: 'guide', text: '$16 = 2^4$, so $2^{x+1} = 2^4$, which means $x + 1 = 4$.' },
      { level: 'reveal', text: '$x + 1 = 4$ gives $x = 3$.' },
    ],
    explanation: ['Make the bases match: $16 = 2^4$.', 'Now $2^{x+1} = 2^4$, so the exponents are equal: $x + 1 = 4$.', 'Subtract $1$: $x = 3$. Check: $2^{3+1} = 2^4 = 16$.'],
    alternativeExplanations: [
      { title: 'Test whole numbers', steps: ['Try $x = 2$: $2^3 = 8$, too small.', 'Try $x = 3$: $2^4 = 16$ — exactly right.', 'So $x = 3$.'] },
      { title: 'Split the power first', steps: ['$2^{x+1}$ is the same as $2^x \\times 2^1$, or $2 \\cdot 2^x$.', 'So $2 \\cdot 2^x = 16$, which gives $2^x = 8$.', '$2^3 = 8$, so $x = 3$.'] },
    ],
    tags: ['exponential-equation', 'same-base'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 65, unit: 7, order: 5, slug: 'solve-savings-double-years',
    standard: 'PC.LOG.A.2', difficulty: 2,
    prompt: 'Your savings DOUBLE every $7$ years. You have $\\$2000$ today. In how many years will you have $\\$16000$?',
    answerType: 'numeric', primaryAnswer: '21', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find how many times the money has to double.' },
      { level: 'guide', text: '$16000 \\div 2000 = 8$, and $8 = 2^3$, so that is $3$ doublings.' },
      { level: 'reveal', text: '$3$ doublings $\\times 7$ years each $= 21$ years.' },
    ],
    explanation: ['Compare the amounts: $16000 \\div 2000 = 8$.', 'Solve $2^n = 8$, so $n = 3$ doublings.', 'Each doubling takes $7$ years: $3 \\times 7 = 21$ years.'],
    alternativeExplanations: [
      { title: 'Walk the years', steps: ['Year 0: $\\$2000$. Year 7: $\\$4000$.', 'Year 14: $\\$8000$. Year 21: $\\$16000$.', 'You land on it at year $21$.'] },
      { title: 'Use the formula', steps: ['With doubling time $7$, the rule is $A = 2000 \\cdot 2^{t/7}$.', 'Set $A = 16000$: $2^{t/7} = 8 = 2^3$, so $t/7 = 3$.', 'Multiply both sides by $7$: $t = 21$ years.'] },
    ],
    tags: ['exponential-equation', 'doubling-time', 'word-problem'], estimatedSeconds: 65,
  },
  {
    domain: 'PC', num: 66, unit: 7, order: 6, slug: 'solve-two-plans-same-cost',
    standard: 'PC.LOG.A.2', difficulty: 2,
    prompt: 'A streaming service charges $\\$80$ a month for its top plan. A rival plan costs $\\$5$ in month $1$ and DOUBLES every month after that. In which month does the rival plan cost $\\$80$?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The rival plan in month $m$ costs $5 \\cdot 2^{m-1}$. Set that equal to $80$.' },
      { level: 'guide', text: 'Divide both sides by $5$: $2^{m-1} = 16$, so $m - 1 = 4$.' },
      { level: 'reveal', text: '$m - 1 = 4$ gives $m = 5$, so the plans match in month $5$.' },
    ],
    explanation: ['The rival plan is exponential: $\\text{cost} = 5 \\cdot 2^{m-1}$.', 'Set it equal to $80$ and divide by $5$: $2^{m-1} = 16 = 2^4$.', 'So $m - 1 = 4$ and $m = 5$.'],
    alternativeExplanations: [
      { title: 'Just list the months', steps: ['Month 1: $\\$5$. Month 2: $\\$10$. Month 3: $\\$20$.', 'Month 4: $\\$40$. Month 5: $\\$80$.', 'Month $5$ is the match.'] },
      { title: 'Count the doublings', steps: ['Going from $\\$5$ to $\\$80$ means multiplying by $16$.', '$16 = 2^4$, so that is $4$ doublings.', 'Four doublings after month $1$ lands on month $5$.'] },
    ],
    tags: ['exponential-equation', 'compare', 'word-problem'], estimatedSeconds: 65,
  },
  {
    domain: 'PC', num: 67, unit: 7, order: 7, slug: 'solve-divide-then-same-base',
    standard: 'PC.LOG.A.2', difficulty: 2,
    prompt: 'Solve for $x$: $3 \\cdot 2^x = 96$.',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The power is not alone yet. Get $2^x$ by itself first.' },
      { level: 'guide', text: 'Divide both sides by $3$: $2^x = 32$.' },
      { level: 'reveal', text: '$32 = 2^5$, so $x = 5$.' },
    ],
    explanation: ['Peel away the multiplier before touching the exponent.', 'Divide both sides by $3$: $2^x = 32$.', '$32 = 2^5$, so $x = 5$. Check: $3 \\times 32 = 96$.'],
    alternativeExplanations: [
      { title: 'Take the log of both sides', steps: ['After dividing by $3$ you have $2^x = 32$.', 'Take $\\log_2$ of both sides — the exponent slides down: $x = \\log_2(32)$.', '$\\log_2(32) = 5$, so $x = 5$.'] },
      { title: 'Guess and adjust', steps: ['Try $x = 4$: $3 \\times 16 = 48$, too small.', 'Try $x = 5$: $3 \\times 32 = 96$ — exactly right.', 'So $x = 5$.'] },
    ],
    tags: ['exponential-equation', 'isolate'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 68, unit: 7, order: 8, slug: 'solve-drug-wears-off-hours',
    standard: 'PC.LOG.A.2', difficulty: 3,
    prompt: 'A $400$ mg dose of medicine loses HALF its amount every $4$ hours. After how many hours is only $25$ mg left?',
    answerType: 'numeric', primaryAnswer: '16', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Count how many halvings take $400$ down to $25$, then convert halvings into hours.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: $80$ mg down to $20$ mg is $2$ halvings ($80 \\to 40 \\to 20$). If each halving is $4$ hours, that is $8$ hours. Same move, more steps.' },
      { level: 'guide', text: '$400 \\to 200 \\to 100 \\to 50 \\to 25$ is $4$ halvings.' },
      { level: 'reveal', text: '$4$ halvings $\\times 4$ hours each $= 16$ hours.' },
    ],
    explanation: ['Halving means the decay factor is $\\frac{1}{2}$.', '$400 \\to 200 \\to 100 \\to 50 \\to 25$ takes $4$ halvings.', 'Each halving takes $4$ hours, so $4 \\times 4 = 16$ hours.'],
    alternativeExplanations: [
      { title: 'Divide first, then log', steps: ['$25 \\div 400 = \\frac{1}{16}$ of the dose is left.', '$\\frac{1}{16} = \\left(\\frac{1}{2}\\right)^4$, so $4$ half-lives have passed.', '$4 \\times 4 = 16$ hours.'] },
      { title: 'Fill in a clock table', steps: ['Hour 0: $400$ mg. Hour 4: $200$ mg. Hour 8: $100$ mg.', 'Hour 12: $50$ mg. Hour 16: $25$ mg.', 'The table lands on $25$ mg at hour $16$.'] },
    ],
    tags: ['exponential-equation', 'half-life', 'word-problem'], estimatedSeconds: 75,
  },
  {
    domain: 'PC', num: 69, unit: 7, order: 9, slug: 'solve-log-reject-negative',
    standard: 'PC.LOG.A.2', difficulty: 3,
    prompt: 'Solve for $x$: $\\log_2(x) + \\log_2(x - 6) = 4$. Give the one answer that works.',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Adding logs means multiplying inside: combine them into one log first.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: $\\log_2(x) + \\log_2(2) = 3$ becomes $\\log_2(2x) = 3$, so $2x = 8$ and $x = 4$. Same move — combine, then rewrite as a power.' },
      { level: 'guide', text: '$\\log_2\\big(x(x-6)\\big) = 4$ means $x(x - 6) = 2^4 = 16$, so $x^2 - 6x - 16 = 0$.' },
      { level: 'reveal', text: 'That factors as $(x - 8)(x + 2) = 0$, giving $x = 8$ or $x = -2$. But $\\log_2(-2)$ is impossible, so $x = 8$.' },
    ],
    explanation: ['Combine with the product rule: $\\log_2\\big(x(x-6)\\big) = 4$.', 'Rewrite as a power: $x(x - 6) = 2^4 = 16$, so $x^2 - 6x - 16 = 0$.', 'Factor: $(x - 8)(x + 2) = 0$. The value $x = -2$ BREAKS the log (you cannot log a negative), so the only answer is $x = 8$.'],
    alternativeExplanations: [
      { title: 'Check both answers in the original', steps: ['Try $x = 8$: $\\log_2(8) + \\log_2(2) = 3 + 1 = 4$. It works.', 'Try $x = -2$: the very first term is $\\log_2(-2)$, and no power of $2$ is negative.', 'So $x = -2$ is thrown out and $x = 8$ stands.'] },
      { title: 'Fence off the illegal values first', steps: ['Before solving, note $x > 0$ AND $x - 6 > 0$, so $x$ must be bigger than $6$.', 'Now solve $x(x-6) = 16$ to get $x = 8$ or $x = -2$.', 'Only $x = 8$ is inside the fence.'] },
    ],
    tags: ['log-equation', 'extraneous'], estimatedSeconds: 90,
  },
  {
    domain: 'PC', num: 70, unit: 7, order: 10, slug: 'solve-population-passes-10000',
    standard: 'PC.LOG.A.2', difficulty: 3,
    prompt: 'A town has $1250$ people and its population DOUBLES every $10$ years. After how many years does the town reach $10000$ people?',
    answerType: 'numeric', primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide the target by the start to see how much growth is needed.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: going from $100$ to $400$ is $\\times 4$, and $4 = 2^2$, so $2$ doublings. Same move — divide, then count doublings.' },
      { level: 'guide', text: '$10000 \\div 1250 = 8$, and $8 = 2^3$, so you need $3$ doublings.' },
      { level: 'reveal', text: '$3$ doublings $\\times 10$ years each $= 30$ years.' },
    ],
    explanation: ['Set up $1250 \\cdot 2^{t/10} = 10000$.', 'Divide by $1250$: $2^{t/10} = 8 = 2^3$, so $t/10 = 3$.', 'Multiply by $10$: $t = 30$ years.'],
    alternativeExplanations: [
      { title: 'Count decade by decade', steps: ['Year 0: $1250$. Year 10: $2500$.', 'Year 20: $5000$. Year 30: $10000$.', 'The town hits $10{,}000$ people at year $30$.'] },
      { title: 'Use a log to finish', steps: ['After dividing you have $2^{t/10} = 8$.', 'Take $\\log_2$ of both sides: $t/10 = \\log_2(8) = 3$.', 'So $t = 30$ years.'] },
    ],
    tags: ['exponential-equation', 'population', 'word-problem'], estimatedSeconds: 80,
  },

  // ------- UNIT 8 — Right-triangle trigonometry (PC.TRIG.A.1) -------
  {
    domain: 'PC', num: 71, unit: 8, order: 1, slug: 'trig-name-the-hypotenuse',
    standard: 'PC.TRIG.A.1', difficulty: 1,
    prompt: 'A right triangle has sides of length $3$, $4$, and $5$. The HYPOTENUSE is the side across from the right angle, and it is always the longest. How long is the hypotenuse?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The hypotenuse is always the longest side of a right triangle.' },
      { level: 'guide', text: 'Compare $3$, $4$, and $5$. Which is biggest?' },
      { level: 'reveal', text: 'The hypotenuse is $5$.' },
    ],
    explanation: ['The hypotenuse sits directly across from the $90^\\circ$ corner.', 'It is always the longest side.', 'Of $3$, $4$, and $5$, the longest is $5$.'],
    alternativeExplanations: [
      { title: 'Check with Pythagoras', steps: ['The two shorter sides are the legs: $3^2 + 4^2 = 9 + 16 = 25$.', 'The hypotenuse squared must be $25$, so the hypotenuse is $\\sqrt{25} = 5$.', 'The $3$-$4$-$5$ triangle is worth memorizing.'] },
      { title: 'Draw it and look', steps: ['Sketch a right angle with legs $3$ across and $4$ up.', 'The slanted side connecting the ends is the hypotenuse.', 'That slant stretches farther than either leg, so it is the $5$.'] },
    ],
    tags: ['trigonometry', 'labeling'], estimatedSeconds: 30,
  },
  {
    domain: 'PC', num: 72, unit: 8, order: 2, slug: 'trig-sine-3-4-5',
    standard: 'PC.TRIG.A.1', difficulty: 1,
    prompt: 'In a right triangle, an angle has opposite side $3$, adjacent side $4$, and hypotenuse $5$. What is the sine of that angle, as a decimal?',
    answerType: 'numeric', primaryAnswer: '0.6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'SOH: Sine is Opposite over Hypotenuse.' },
      { level: 'guide', text: 'Opposite is $3$ and hypotenuse is $5$, so sine $= \\frac{3}{5}$.' },
      { level: 'reveal', text: '$\\frac{3}{5} = 0.6$.' },
    ],
    explanation: ['SOH-CAH-TOA starts with SOH: Sine $=$ Opposite $\\div$ Hypotenuse.', 'Here that is $3 \\div 5$.', '$3 \\div 5 = 0.6$.'],
    alternativeExplanations: [
      { title: 'Say the ritual out loud', steps: ['Point at the angle. The side touching it (not the slant) is ADJACENT.', 'The side across the triangle from it is OPPOSITE, and the slant is the HYPOTENUSE.', 'Sine wants opposite over hypotenuse: $3$ over $5$, which is $0.6$.'] },
      { title: 'Think in fractions of the slant', steps: ['Sine asks: how tall is the triangle compared with its slanted side?', 'The height is $3$ and the slant is $5$, so the height is $\\frac{3}{5}$ of the slant.', '$\\frac{3}{5} = 0.6$.'] },
    ],
    tags: ['trigonometry', 'sine'], estimatedSeconds: 35,
  },
  {
    domain: 'PC', num: 73, unit: 8, order: 3, slug: 'trig-cosine-3-4-5',
    standard: 'PC.TRIG.A.1', difficulty: 1,
    prompt: 'For the same angle, the opposite side is $3$, the adjacent side is $4$, and the hypotenuse is $5$. What is the cosine of that angle, as a decimal?',
    answerType: 'numeric', primaryAnswer: '0.8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'CAH: Cosine is Adjacent over Hypotenuse.' },
      { level: 'guide', text: 'Adjacent is $4$ and hypotenuse is $5$, so cosine $= \\frac{4}{5}$.' },
      { level: 'reveal', text: '$\\frac{4}{5} = 0.8$.' },
    ],
    explanation: ['CAH: Cosine $=$ Adjacent $\\div$ Hypotenuse.', 'Adjacent means the leg that touches the angle.', '$4 \\div 5 = 0.8$.'],
    alternativeExplanations: [
      { title: 'Adjacent means next door', steps: ['Two sides touch the angle: one leg and the hypotenuse.', 'The leg that touches is the ADJACENT side — the neighbour.', 'Cosine is that neighbour over the hypotenuse: $\\frac{4}{5} = 0.8$.'] },
      { title: 'Sine and cosine trade places', steps: ['For this angle sine was $\\frac{3}{5}$, using the far side.', 'Cosine uses the other leg instead, so it is $\\frac{4}{5}$.', '$\\frac{4}{5} = 0.8$.'] },
    ],
    tags: ['trigonometry', 'cosine'], estimatedSeconds: 35,
  },
  {
    domain: 'PC', num: 74, unit: 8, order: 4, slug: 'trig-tangent-6-8-10',
    standard: 'PC.TRIG.A.1', difficulty: 2,
    prompt: 'A right triangle has legs $6$ and $8$ and hypotenuse $10$. For the angle whose opposite side is $6$ and adjacent side is $8$, what is the tangent, as a decimal?',
    answerType: 'numeric', primaryAnswer: '0.75', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'TOA: Tangent is Opposite over Adjacent. The hypotenuse is not invited.' },
      { level: 'guide', text: 'Opposite is $6$, adjacent is $8$, so tangent $= \\frac{6}{8}$.' },
      { level: 'reveal', text: '$\\frac{6}{8} = \\frac{3}{4} = 0.75$.' },
    ],
    explanation: ['TOA: Tangent $=$ Opposite $\\div$ Adjacent.', 'Here that is $6 \\div 8$.', 'Simplify: $\\frac{6}{8} = \\frac{3}{4} = 0.75$.'],
    alternativeExplanations: [
      { title: 'Tangent is steepness', steps: ['Tangent is just rise over run — the slope of the slanted side.', 'The triangle rises $6$ while running $8$ across.', '$6 \\div 8 = 0.75$, so it climbs $0.75$ for every $1$ across.'] },
      { title: 'Shrink to the 3-4-5', steps: ['The $6$-$8$-$10$ triangle is a $3$-$4$-$5$ triangle doubled.', 'Same shape means the same angles and the same ratios.', 'Tangent is $\\frac{3}{4} = 0.75$ either way.'] },
    ],
    tags: ['trigonometry', 'tangent'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 75, unit: 8, order: 5, slug: 'trig-ladder-angle-45',
    standard: 'PC.TRIG.A.1', difficulty: 2,
    prompt: 'A ladder leans against a wall. It touches the wall $5$ m up, and its foot sits $5$ m out from the wall. What angle does the ladder make with the ground, in degrees?',
    answerType: 'numeric', primaryAnswer: '45', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You know the opposite side ($5$ up) and the adjacent side ($5$ out), so use tangent.' },
      { level: 'guide', text: '$\\tan(\\text{angle}) = \\frac{5}{5} = 1$. Which angle has a tangent of $1$?' },
      { level: 'reveal', text: 'The inverse tangent of $1$ is $45^\\circ$.' },
    ],
    explanation: ['Opposite $= 5$ and adjacent $= 5$, so use TOA.', '$\\tan(\\text{angle}) = \\frac{5}{5} = 1$.', 'Inverse tangent turns the ratio back into an angle: the angle is $45^\\circ$.'],
    alternativeExplanations: [
      { title: 'Spot the 45-45-90 triangle', steps: ['Both legs are $5$, so the triangle is isosceles.', 'The two non-right angles must be equal and add to $90^\\circ$.', '$90 \\div 2 = 45$, so the ladder meets the ground at $45^\\circ$.'] },
      { title: 'Draw and sanity-check', steps: ['Sketch it: the ladder goes up exactly as much as it goes out.', 'That slant is a perfect diagonal, halfway between flat and straight up.', 'Halfway between $0^\\circ$ and $90^\\circ$ is $45^\\circ$.'] },
    ],
    tags: ['trigonometry', 'inverse-trig', 'word-problem'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 76, unit: 8, order: 6, slug: 'trig-30-60-90-short-leg',
    standard: 'PC.TRIG.A.1', difficulty: 2,
    prompt: 'In a $30$-$60$-$90$ triangle the hypotenuse is $12$. How long is the short leg, the one opposite the $30^\\circ$ angle?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Use SOH with the $30^\\circ$ angle: $\\sin(30^\\circ) = \\frac{\\text{opposite}}{12}$.' },
      { level: 'guide', text: '$\\sin(30^\\circ) = \\frac{1}{2}$, so opposite $= \\frac{1}{2} \\times 12$.' },
      { level: 'reveal', text: '$\\frac{1}{2} \\times 12 = 6$.' },
    ],
    explanation: ['In a $30$-$60$-$90$ triangle, the side opposite $30^\\circ$ is always HALF the hypotenuse.', 'That is the same as $\\sin(30^\\circ) = \\frac{1}{2}$.', '$\\frac{1}{2} \\times 12 = 6$.'],
    alternativeExplanations: [
      { title: 'Cut a triangle in half', steps: ['Take an equilateral triangle with all sides $12$ and slice it straight down the middle.', 'Each half is a $30$-$60$-$90$ triangle, and the bottom edge of $12$ got cut into two $6$s.', 'That $6$ is the short leg.'] },
      { title: 'Use the memorized ratio', steps: ['A $30$-$60$-$90$ triangle has sides in the ratio $1 : \\sqrt{3} : 2$.', 'The hypotenuse matches the $2$, so $2$ parts $= 12$ and $1$ part $= 6$.', 'The short leg is $1$ part, so it is $6$.'] },
    ],
    tags: ['trigonometry', 'special-triangles'], estimatedSeconds: 55,
  },
  {
    domain: 'PC', num: 77, unit: 8, order: 7, slug: 'trig-slide-third-angle',
    standard: 'PC.TRIG.A.1', difficulty: 2,
    prompt: 'A slide at the park makes a right triangle with the ground and the ladder post. One angle is the right angle, and the slide meets the ground at $55^\\circ$. What is the third angle, in degrees?',
    answerType: 'numeric', primaryAnswer: '35', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The three angles of ANY triangle add up to $180^\\circ$.' },
      { level: 'guide', text: 'The right angle already uses $90^\\circ$, so the other two must share $90^\\circ$.' },
      { level: 'reveal', text: '$90 - 55 = 35$, so the third angle is $35^\\circ$.' },
    ],
    explanation: ['Every triangle\'s angles total $180^\\circ$.', 'The right angle takes $90^\\circ$, leaving $90^\\circ$ for the other two.', '$90 - 55 = 35$, so the third angle is $35^\\circ$.'],
    alternativeExplanations: [
      { title: 'Subtract from 180 all at once', steps: ['Add what you know: $90 + 55 = 145$.', 'Subtract from the total: $180 - 145 = 35$.', 'The third angle is $35^\\circ$.'] },
      { title: 'Picture the slide tipping', steps: ['A very steep slide meets the ground near $90^\\circ$ and leaves almost nothing at the top.', 'A gentle slide meets the ground near $0^\\circ$ and leaves almost $90^\\circ$ at the top.', 'At $55^\\circ$ the leftover is $90 - 55 = 35^\\circ$.'] },
    ],
    tags: ['trigonometry', 'angles', 'word-problem'], estimatedSeconds: 45,
  },
  {
    domain: 'PC', num: 78, unit: 8, order: 8, slug: 'trig-tree-shadow-elevation-45',
    standard: 'PC.TRIG.A.1', difficulty: 3,
    prompt: 'A tree casts a shadow $20$ ft long. From the tip of the shadow, the angle of elevation up to the top of the tree is $45^\\circ$. How tall is the tree, in feet?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Draw the right triangle: the shadow is the bottom, the tree is the upright side.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: a $10$ ft shadow with a $45^\\circ$ elevation gives a $10$ ft pole, because $\\tan(45^\\circ) = 1$ makes height equal shadow. Same move, bigger number.' },
      { level: 'guide', text: 'From the shadow tip, the tree is opposite and the shadow is adjacent: $\\tan(45^\\circ) = \\frac{h}{20}$.' },
      { level: 'reveal', text: '$\\tan(45^\\circ) = 1$, so $\\frac{h}{20} = 1$ and $h = 20$ ft.' },
    ],
    explanation: ['Angle of elevation is measured UP from the flat ground.', 'The tree is opposite that angle and the shadow is adjacent, so use TOA: $\\tan(45^\\circ) = \\frac{h}{20}$.', '$\\tan(45^\\circ) = 1$, so $h = 20$ ft.'],
    alternativeExplanations: [
      { title: 'It is a 45-45-90 triangle', steps: ['One angle is $90^\\circ$ and another is $45^\\circ$, so the last one is $45^\\circ$ too.', 'Two equal angles mean two equal legs.', 'The shadow leg is $20$ ft, so the tree leg is also $20$ ft.'] },
      { title: 'The shadow rule of thumb', steps: ['When the sun sits at $45^\\circ$, every object casts a shadow exactly as long as it is tall.', 'The shadow measures $20$ ft.', 'So the tree stands $20$ ft tall.'] },
    ],
    tags: ['trigonometry', 'angle-of-elevation', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'PC', num: 79, unit: 8, order: 9, slug: 'trig-ramp-rise-30-degrees',
    standard: 'PC.TRIG.A.1', difficulty: 3,
    prompt: 'A wheelchair ramp is $10$ ft long along the slope and rises at an angle of $30^\\circ$ to the ground. How high is the top of the ramp, in feet?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $10$ ft slope is the HYPOTENUSE, and the height is opposite the $30^\\circ$ angle.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: a $4$ ft slope at $30^\\circ$ rises $\\frac{1}{2} \\times 4 = 2$ ft, because $\\sin(30^\\circ) = \\frac{1}{2}$. Same move, bigger slope.' },
      { level: 'guide', text: 'Opposite over hypotenuse means sine: $\\sin(30^\\circ) = \\frac{h}{10}$.' },
      { level: 'reveal', text: '$\\sin(30^\\circ) = \\frac{1}{2}$, so $h = \\frac{1}{2} \\times 10 = 5$ ft.' },
    ],
    explanation: ['Label first: the ramp itself is the hypotenuse ($10$ ft), and the height is opposite the $30^\\circ$ angle.', 'Opposite and hypotenuse means SOH: $\\sin(30^\\circ) = \\frac{h}{10}$.', '$\\sin(30^\\circ) = \\frac{1}{2}$, so $h = 5$ ft.'],
    alternativeExplanations: [
      { title: 'Half the hypotenuse', steps: ['In every $30$-$60$-$90$ triangle, the side opposite $30^\\circ$ is exactly half the hypotenuse.', 'The hypotenuse is $10$ ft.', 'Half of $10$ is $5$ ft.'] },
      { title: 'Sanity-check the size', steps: ['The height must be smaller than the ramp itself, so the answer has to be under $10$ ft.', 'A gentle $30^\\circ$ ramp should rise only a modest amount.', '$5$ ft fits both checks, while an answer like $20$ ft would be impossible.'] },
    ],
    tags: ['trigonometry', 'sine', 'word-problem'], estimatedSeconds: 70,
  },
  {
    domain: 'PC', num: 80, unit: 8, order: 10, slug: 'trig-kite-string-inverse-sine',
    standard: 'PC.TRIG.A.1', difficulty: 3,
    prompt: 'You fly a kite on a straight string $40$ m long. The kite is $20$ m above your hands. What angle does the string make with the level ground, in degrees?',
    answerType: 'numeric', primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The string is the hypotenuse and the height is opposite the angle, so sine is the tool.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Warm up: a $10$ m string with the kite $5$ m up gives $\\sin(\\text{angle}) = \\frac{5}{10} = \\frac{1}{2}$, so the angle is $30^\\circ$. Same move, bigger numbers.' },
      { level: 'guide', text: '$\\sin(\\text{angle}) = \\frac{20}{40} = \\frac{1}{2}$. Now ask which angle has sine $\\frac{1}{2}$.' },
      { level: 'reveal', text: 'The inverse sine of $\\frac{1}{2}$ is $30^\\circ$.' },
    ],
    explanation: ['Label the triangle: string $= $ hypotenuse $= 40$, height $= $ opposite $= 20$.', 'SOH gives $\\sin(\\text{angle}) = \\frac{20}{40} = \\frac{1}{2}$.', 'Inverse sine turns the ratio back into an angle: $30^\\circ$.'],
    alternativeExplanations: [
      { title: 'Recognize the half-hypotenuse', steps: ['The height is exactly half the string.', 'The only right triangle where a leg is half the hypotenuse is the $30$-$60$-$90$.', 'The angle across from that short leg is $30^\\circ$.'] },
      { title: 'Ratio to angle, in that order', steps: ['Sine takes an angle and gives a ratio; inverse sine goes backward.', 'Here you already have the ratio $\\frac{1}{2}$, so you need the backward trip.', 'The angle whose sine is $\\frac{1}{2}$ is $30^\\circ$.'] },
    ],
    tags: ['trigonometry', 'inverse-trig', 'word-problem'], estimatedSeconds: 75,
  },
];
