import type { SeedProblem } from './types';

// SAT — Geometry and Trigonometry (blueprint area GEO, ~15% of the Math
// section). Units 15-18, problems 141-180.
//
// The smallest area on the test, but the one where memorized facts pay off
// most directly: the reference sheet is provided, yet every lookup costs
// about fifteen seconds, and these questions cluster late in a module.

export const problemsSATgeo: SeedProblem[] = [
  // ═══════════════ UNIT 15 — Lines, Angles, and Triangles ═══════════════
  {
    domain: 'SAT', num: 141, unit: 15, order: 1, slug: 'sat-triangle-sum',
    standard: 'SAT.GEO.1', difficulty: 1,
    prompt: 'Two angles of a triangle measure $40°$ and $65°$. What is the measure, in degrees, of the third angle?',
    answerType: 'numeric', primaryAnswer: '75', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The three angles of any triangle add to $180°$.' },
      { level: 'guide', text: '$40 + 65 = 105$.' },
      { level: 'reveal', text: '$180 - 105 = 75$ degrees.' },
    ],
    learningObjective: 'Apply the triangle angle sum.',
    topic: 'Triangle angles',
    explanation: [
      'The interior angles of a triangle always sum to $180°$.',
      '$40 + 65 = 105$.',
      '$180 - 105 = 75°$.',
    ],
    alternativeExplanations: [
      { title: 'The sum never changes', steps: ['It is $180°$ for every triangle — acute, right, obtuse, large or small.', 'This is the single most-used fact in SAT geometry, and it is not on the reference sheet.', 'Any question giving you two angles of a triangle is handing you the third for free.'] },
    ],
    tags: ['triangle', 'angle-sum'], estimatedSeconds: 35,
  },
  {
    domain: 'SAT', num: 142, unit: 15, order: 2, slug: 'sat-supplementary-angles',
    standard: 'SAT.GEO.1', difficulty: 1,
    prompt: 'Two angles are supplementary. One measures $118°$. What is the measure, in degrees, of the other?',
    answerType: 'numeric', primaryAnswer: '62', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Supplementary angles sum to $180°$.' },
      { level: 'guide', text: '$180 - 118$.' },
      { level: 'reveal', text: '$62$ degrees.' },
    ],
    learningObjective: 'Apply the supplementary-angle relationship.',
    topic: 'Angle pairs',
    explanation: [
      'Supplementary angles add to $180°$ — they form a straight line.',
      '$180 - 118 = 62°$.',
      'Complementary angles, by contrast, add to $90°$.',
    ],
    alternativeExplanations: [
      { title: 'Keeping the two words apart', steps: ['Complementary comes before supplementary alphabetically, and $90$ comes before $180$ numerically.', 'That ordering is enough to keep them straight under time pressure.', 'Choosing the wrong one here gives $-28$, which is obviously impossible — so a quick plausibility check catches the mix-up too.'] },
    ],
    tags: ['supplementary', 'angle-pairs'], estimatedSeconds: 30,
  },
  {
    domain: 'SAT', num: 143, unit: 15, order: 3, slug: 'sat-parallel-lines-angles',
    standard: 'SAT.GEO.1', difficulty: 2,
    prompt: 'Two parallel lines are cut by a transversal. One of the eight angles formed measures $115°$. What is the measure, in degrees, of an angle that is supplementary to it?',
    answerType: 'numeric', primaryAnswer: '65', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'When parallel lines are cut by a transversal, every angle is either equal to $115°$ or supplementary to it.' },
      { level: 'guide', text: 'The supplementary partner satisfies $115 + x = 180$.' },
      { level: 'reveal', text: '$x = 65$ degrees.' },
    ],
    learningObjective: 'Use the two-angle structure formed by a transversal across parallel lines.',
    topic: 'Parallel lines',
    explanation: [
      'A transversal crossing two parallel lines creates only two distinct angle measures, and they are supplementary.',
      'One is $115°$, so the other is $180 - 115 = 65°$.',
      'Four of the eight angles measure $115°$ and the other four measure $65°$.',
    ],
    alternativeExplanations: [
      { title: 'Only two numbers exist in the figure', steps: ['Rather than memorizing "corresponding", "alternate interior", and "co-interior" separately, notice that every angle is one of just two values.', 'Angles that look equal are equal; angles that look different are supplementary.', 'With parallel lines, the picture is reliable in exactly this one respect — and it collapses eight angle names into one idea.'] },
    ],
    tags: ['parallel-lines', 'transversal', 'supplementary'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 144, unit: 15, order: 4, slug: 'sat-exterior-angle',
    standard: 'SAT.GEO.1', difficulty: 2,
    prompt: 'In a triangle, the two angles not adjacent to a certain exterior angle measure $50°$ and $70°$. What is the measure, in degrees, of that exterior angle?',
    answerType: 'numeric', primaryAnswer: '120', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'An exterior angle equals the sum of the two remote interior angles.' },
      { level: 'guide', text: '$50 + 70$.' },
      { level: 'reveal', text: '$120$ degrees.' },
    ],
    learningObjective: 'Apply the exterior angle theorem.',
    topic: 'Triangle angles',
    explanation: [
      'The Exterior Angle Theorem: an exterior angle of a triangle equals the sum of the two non-adjacent (remote) interior angles.',
      '$50 + 70 = 120°$.',
      'Check the long way: the third interior angle is $180 - 120 = 60°$, and its exterior partner is $180 - 60 = 120°$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Why the shortcut works', steps: ['The exterior angle is supplementary to its adjacent interior angle: exterior $= 180 - $ adjacent.', 'The three interior angles sum to $180$, so $180 - $ adjacent $=$ the other two added together.', 'The theorem is just those two facts combined — which is why you can always fall back on the long route if you forget it.'] },
    ],
    tags: ['exterior-angle', 'triangle'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 145, unit: 15, order: 5, slug: 'sat-isosceles-base-angles',
    standard: 'SAT.GEO.1', difficulty: 2,
    prompt: 'In an isosceles triangle, the angle between the two congruent sides measures $40°$. What is the measure, in degrees, of each base angle?',
    answerType: 'numeric', primaryAnswer: '70', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The two base angles of an isosceles triangle are equal.' },
      { level: 'guide', text: 'They share the remaining $180 - 40 = 140$ degrees.' },
      { level: 'reveal', text: '$140 \\div 2 = 70$ degrees each.' },
    ],
    learningObjective: 'Combine the isosceles base-angle property with the triangle sum.',
    topic: 'Isosceles triangles',
    explanation: [
      'In an isosceles triangle, the angles opposite the two congruent sides are equal — these are the base angles.',
      'The vertex angle is $40°$, leaving $180 - 40 = 140°$ split evenly between them.',
      'Each base angle is $140 \\div 2 = 70°$.',
    ],
    alternativeExplanations: [
      { title: 'Equal sides face equal angles', steps: ['The rule runs both ways: equal sides mean equal opposite angles, and equal angles mean equal opposite sides.', 'Locate which sides are marked congruent, then look *across* from each to find the equal angles.', 'Getting the vertex and base angles backwards gives $(180 - 70)/2 = 55$, and that will be an answer choice.'] },
    ],
    tags: ['isosceles', 'triangle', 'angle-sum'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 146, unit: 15, order: 6, slug: 'sat-polygon-angle-sum',
    standard: 'SAT.GEO.1', difficulty: 2,
    prompt: 'What is the sum, in degrees, of the interior angles of a pentagon?',
    answerType: 'numeric', primaryAnswer: '540', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The formula is $(n - 2) \\times 180°$ for an $n$-sided polygon.' },
      { level: 'guide', text: 'A pentagon has $n = 5$, so $(5 - 2) \\times 180$.' },
      { level: 'reveal', text: '$3 \\times 180 = 540$ degrees.' },
    ],
    learningObjective: 'Apply the polygon interior-angle-sum formula.',
    topic: 'Polygons',
    explanation: [
      'An $n$-sided polygon splits into $n - 2$ triangles, each contributing $180°$.',
      'For a pentagon: $(5 - 2) \\times 180 = 3 \\times 180 = 540°$.',
      'If the pentagon is regular, each angle is $540 \\div 5 = 108°$.',
    ],
    alternativeExplanations: [
      { title: 'Derive it rather than memorize it', steps: ['Pick one vertex and draw diagonals to every non-adjacent vertex.', 'A pentagon splits into exactly $3$ triangles this way, which is where the $n - 2$ comes from.', 'If you blank on the formula, drawing the triangles rebuilds it in ten seconds.'] },
    ],
    tags: ['polygon', 'angle-sum'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 147, unit: 15, order: 7, slug: 'sat-angle-ratio-triangle',
    standard: 'SAT.GEO.1', difficulty: 3,
    prompt: 'The measures of the three angles of a triangle are in the ratio $1 : 2 : 3$. What is the measure, in degrees, of the largest angle?',
    answerType: 'numeric', primaryAnswer: '90', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Call the angles $x$, $2x$, and $3x$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easier ratio: angles in the ratio $1 : 1 : 2$ give $4x = 180$, so $x = 45$ and the angles are $45$, $45$, $90$. Add the ratio parts, then divide $180$ among them.' },
      { level: 'guide', text: 'Their sum is $6x = 180$.' },
      { level: 'reveal', text: '$x = 30$, so the largest angle is $3(30) = 90$ degrees.' },
    ],
    learningObjective: 'Use a ratio together with the triangle angle sum.',
    topic: 'Triangle angles',
    explanation: [
      'Let the angles be $x$, $2x$, and $3x$.',
      'Their sum is $180$: $x + 2x + 3x = 6x = 180$, so $x = 30$.',
      'The angles are $30°$, $60°$, and $90°$ — the largest is $90°$, so this is a right triangle.',
    ],
    alternativeExplanations: [
      { title: 'Ratio parts split the total', steps: ['The ratio $1 : 2 : 3$ has $6$ parts in total, and those parts share $180°$.', 'Each part is $180 \\div 6 = 30°$, so the angles are $30$, $60$, and $90$.', 'This "total parts" method works for any ratio question — angles, money, or ingredients.'] },
    ],
    tags: ['ratio', 'triangle', 'angle-sum'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 148, unit: 15, order: 8, slug: 'sat-transversal-algebra',
    standard: 'SAT.GEO.1', difficulty: 3,
    prompt: 'Two parallel lines are cut by a transversal. One angle measures $(3x + 10)°$ and the corresponding angle measures $(5x - 30)°$. What is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Corresponding angles formed by a transversal across parallel lines are equal.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try easier expressions: if corresponding angles are $(x + 20)°$ and $(2x)°$, then $x + 20 = 2x$ and $x = 20$. Congruent angles means set the expressions equal.' },
      { level: 'guide', text: 'So $3x + 10 = 5x - 30$.' },
      { level: 'reveal', text: '$40 = 2x$, so $x = 20$.' },
    ],
    learningObjective: 'Set up an equation from an angle relationship in a parallel-line figure.',
    topic: 'Parallel lines',
    explanation: [
      'Corresponding angles are congruent when the lines are parallel, so set the expressions equal: $3x + 10 = 5x - 30$.',
      'Subtract $3x$ and add $30$: $40 = 2x$.',
      '$x = 20$. Check: both angles measure $70°$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Equal or supplementary decides the equation', steps: ['If the angles are congruent (corresponding, alternate interior, alternate exterior, vertical), set the expressions equal.', 'If they are supplementary (co-interior, or a linear pair), set the sum to $180$.', 'Identifying which relationship applies is the whole question — the algebra afterwards is routine.'] },
    ],
    tags: ['parallel-lines', 'corresponding-angles', 'algebra'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 149, unit: 15, order: 9, slug: 'sat-triangle-inequality',
    standard: 'SAT.GEO.1', difficulty: 3,
    prompt: 'Which set of side lengths could NOT form a triangle?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$5$, $7$, $10$', correct: false },
      { id: 'B', label: '$3$, $4$, $8$', correct: true },
      { id: 'C', label: '$6$, $6$, $6$', correct: false },
      { id: 'D', label: '$8$, $15$, $17$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The two shorter sides must together exceed the longest side.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an obvious failure: $1$, $2$, and $9$ cannot close, since $1 + 2 = 3 < 9$. Compare the two shortest sides against the longest — that one check is enough.' },
      { level: 'guide', text: 'For choice B: is $3 + 4$ greater than $8$?' },
      { level: 'reveal', text: '$3 + 4 = 7 < 8$, so those lengths cannot close into a triangle.' },
    ],
    learningObjective: 'Apply the triangle inequality.',
    topic: 'Triangle inequality',
    explanation: [
      'The Triangle Inequality: the sum of any two sides must exceed the third. In practice, just check the two shortest against the longest.',
      'A: $5 + 7 = 12 > 10$ ✓. B: $3 + 4 = 7 < 8$ ✗. C: $6 + 6 = 12 > 6$ ✓. D: $8 + 15 = 23 > 17$ ✓',
      'Only choice B fails.',
    ],
    alternativeExplanations: [
      { title: 'Picture the two short sides swinging shut', steps: ['Imagine the two shorter sides as hinged arms attached to the ends of the longest side.', 'If they are too short to meet in the middle, no triangle exists — they cannot reach across.', 'Checking the two shortest against the longest is sufficient; the other two comparisons are then automatic.'] },
    ],
    tags: ['triangle-inequality', 'sides'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 150, unit: 15, order: 10, slug: 'sat-triangle-algebra-angles',
    standard: 'SAT.GEO.1', difficulty: 3,
    prompt: 'The angles of a triangle measure $(2x)°$, $(3x + 10)°$, and $(x - 10)°$. What is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set the sum of the three expressions equal to $180$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try simpler expressions: angles $x$, $x$, and $x$ give $3x = 180$, so $x = 60$. Sum all three expressions, set the total to $180$, and solve.' },
      { level: 'guide', text: '$2x + (3x + 10) + (x - 10) = 180$.' },
      { level: 'reveal', text: 'The constants cancel: $6x = 180$, so $x = 30$.' },
    ],
    learningObjective: 'Solve for a variable using the triangle angle sum.',
    topic: 'Triangle angles',
    explanation: [
      'The three angles sum to $180°$: $2x + 3x + 10 + x - 10 = 180$.',
      'Combine like terms — the $+10$ and $-10$ cancel: $6x = 180$.',
      '$x = 30$. The angles are $60°$, $100°$, and $20°$, which do sum to $180$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Finish by checking, not by stopping', steps: ['The question asked for $x$, which is $30$ — not for an angle measure.', 'But computing the three angles anyway is a fast, complete verification.', 'If they had not summed to $180$, you would know immediately that the algebra went wrong.'] },
    ],
    tags: ['triangle', 'angle-sum', 'algebra'], estimatedSeconds: 70,
  },

  // ═══════════════ UNIT 16 — Area, Volume, and Similarity ═══════════════
  {
    domain: 'SAT', num: 151, unit: 16, order: 1, slug: 'sat-triangle-area',
    standard: 'SAT.GEO.2', difficulty: 1,
    prompt: 'A triangle has a base of $12$ and a height of $5$. What is its area?',
    answerType: 'numeric', primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Area of a triangle is half the base times the height.' },
      { level: 'guide', text: '$\\tfrac{1}{2}(12)(5)$.' },
      { level: 'reveal', text: '$30$.' },
    ],
    learningObjective: 'Compute the area of a triangle.',
    topic: 'Area',
    explanation: [
      'Area $= \\tfrac{1}{2}bh = \\tfrac{1}{2}(12)(5)$.',
      '$= \\tfrac{1}{2}(60) = 30$.',
      'Forgetting the $\\tfrac{1}{2}$ gives $60$, which is the area of the surrounding rectangle — and an answer choice.',
    ],
    alternativeExplanations: [
      { title: 'Why the one-half is there', steps: ['Any triangle is exactly half of a rectangle with the same base and height.', 'Draw the rectangle around it and the halving becomes obvious rather than memorized.', 'This also explains why the height must be perpendicular to the base — it is the side of that rectangle.'] },
    ],
    tags: ['area', 'triangle'], estimatedSeconds: 30,
  },
  {
    domain: 'SAT', num: 152, unit: 16, order: 2, slug: 'sat-prism-volume',
    standard: 'SAT.GEO.2', difficulty: 1,
    prompt: 'A rectangular prism has dimensions $4$ by $5$ by $6$. What is its volume?',
    answerType: 'numeric', primaryAnswer: '120', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Volume of a rectangular prism is length times width times height.' },
      { level: 'guide', text: '$4 \\times 5 \\times 6$.' },
      { level: 'reveal', text: '$120$.' },
    ],
    learningObjective: 'Compute the volume of a rectangular prism.',
    topic: 'Volume',
    explanation: [
      'Volume $= \\ell wh = 4 \\times 5 \\times 6 = 120$.',
      'Equivalently: one layer holds $4 \\times 5 = 20$ unit cubes, and there are $6$ layers.',
      'The order of multiplication does not matter.',
    ],
    alternativeExplanations: [
      { title: 'Volume versus surface area', steps: ['Volume is what fits inside, measured in cubic units.', 'Surface area is the wrapping, measured in square units — here it would be $2(20 + 24 + 30) = 148$.', 'The units in the answer choices often tell you which one is wanted, so read them.'] },
    ],
    tags: ['volume', 'prism'], estimatedSeconds: 30,
  },
  {
    domain: 'SAT', num: 153, unit: 16, order: 3, slug: 'sat-circle-area',
    standard: 'SAT.GEO.2', difficulty: 2,
    prompt: 'What is the area of a circle with radius $6$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$12\\pi$', correct: false },
      { id: 'B', label: '$36\\pi$', correct: true },
      { id: 'C', label: '$6\\pi$', correct: false },
      { id: 'D', label: '$144\\pi$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Area of a circle is $\\pi r^2$.' },
      { level: 'guide', text: '$\\pi (6)^2$.' },
      { level: 'reveal', text: '$36\\pi$.' },
    ],
    learningObjective: 'Compute the area of a circle from its radius.',
    topic: 'Circles',
    explanation: [
      'Area $= \\pi r^2 = \\pi(6)^2 = 36\\pi$.',
      'Choice A, $12\\pi$, is the *circumference* ($2\\pi r$) — the classic mix-up.',
      'Choice D squares the diameter instead of the radius.',
    ],
    alternativeExplanations: [
      { title: 'Area squares, circumference does not', steps: ['Area $= \\pi r^2$ has an exponent, so the answer grows with the square of the radius.', 'Circumference $= 2\\pi r$ is linear in $r$.', 'If a question mentions units, area is square units and circumference is plain units — another way to tell which formula is wanted.'] },
    ],
    tags: ['circle', 'area'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 154, unit: 16, order: 4, slug: 'sat-cylinder-volume',
    standard: 'SAT.GEO.2', difficulty: 2,
    prompt: 'What is the volume of a cylinder with radius $3$ and height $10$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$30\\pi$', correct: false },
      { id: 'B', label: '$60\\pi$', correct: false },
      { id: 'C', label: '$90\\pi$', correct: true },
      { id: 'D', label: '$300\\pi$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Volume of a cylinder is the base area times the height.' },
      { level: 'guide', text: 'The base is a circle of area $\\pi(3)^2 = 9\\pi$.' },
      { level: 'reveal', text: '$9\\pi \\times 10 = 90\\pi$.' },
    ],
    learningObjective: 'Compute the volume of a cylinder.',
    topic: 'Volume',
    explanation: [
      'Volume $= \\pi r^2 h$, which is the circular base area times the height.',
      '$\\pi(3)^2(10) = 9\\pi \\times 10 = 90\\pi$.',
      'Choice A forgets to square the radius; choice D squares the height instead.',
    ],
    alternativeExplanations: [
      { title: 'Every prism and cylinder follows one rule', steps: ['Volume $=$ base area $\\times$ height, whatever the base shape is.', 'For a cylinder the base is a circle; for a rectangular prism it is a rectangle.', 'Cones and pyramids take a third of that — the $\\tfrac{1}{3}$ appears exactly when the shape narrows to a point.'] },
    ],
    tags: ['volume', 'cylinder'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 155, unit: 16, order: 5, slug: 'sat-similar-area-ratio',
    standard: 'SAT.GEO.2', difficulty: 2,
    prompt: 'Two similar triangles have corresponding sides in the ratio $1 : 3$. What is the ratio of their areas?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$1 : 3$', correct: false },
      { id: 'B', label: '$1 : 6$', correct: false },
      { id: 'C', label: '$1 : 9$', correct: true },
      { id: 'D', label: '$1 : 27$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Area is a two-dimensional measure, so the scale factor applies twice.' },
      { level: 'guide', text: 'The area ratio is the side ratio squared.' },
      { level: 'reveal', text: '$3^2 = 9$, so the ratio is $1 : 9$.' },
    ],
    learningObjective: 'Apply the square relationship between linear scale and area.',
    topic: 'Similarity',
    explanation: [
      'For similar figures with side ratio $k$, the area ratio is $k^2$ and the volume ratio is $k^3$.',
      'Here $k = 3$, so the areas are in the ratio $1 : 3^2 = 1 : 9$.',
      'Choice A is the trap that scales linearly; choice D uses the volume rule.',
    ],
    alternativeExplanations: [
      { title: 'Verify with an actual pair', steps: ['Take a triangle with base $2$ and height $2$: area $2$. Scale by $3$ to base $6$, height $6$: area $18$.', '$18 \\div 2 = 9$ ✓', 'Building a concrete example takes fifteen seconds and settles the rule permanently.'] },
    ],
    tags: ['similarity', 'area-ratio', 'scale'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 156, unit: 16, order: 6, slug: 'sat-composite-area',
    standard: 'SAT.GEO.2', difficulty: 2,
    prompt: 'A rectangular garden measures $20$ feet by $15$ feet. A square patio measuring $5$ feet on each side is built inside it. What is the area, in square feet, of the remaining garden?',
    answerType: 'numeric', primaryAnswer: '275', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the whole area, then subtract the part that is no longer garden.' },
      { level: 'guide', text: 'Garden: $20 \\times 15 = 300$. Patio: $5 \\times 5 = 25$.' },
      { level: 'reveal', text: '$300 - 25 = 275$ square feet.' },
    ],
    learningObjective: 'Compute a composite area by subtraction.',
    topic: 'Composite area',
    explanation: [
      'Total rectangle area: $20 \\times 15 = 300$ square feet.',
      'Patio area: $5^2 = 25$ square feet.',
      'Remaining garden: $300 - 25 = 275$ square feet.',
    ],
    alternativeExplanations: [
      { title: 'Subtract the hole, do not rebuild the shape', steps: ['Trying to carve the remaining region into rectangles works but takes four times as long.', 'Whole minus hole is the standard move for any shaded-region or leftover-area question.', 'It also works for circles inside squares, which is the most common version on the test.'] },
    ],
    tags: ['composite-area', 'subtraction'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 157, unit: 16, order: 7, slug: 'sat-sphere-volume',
    standard: 'SAT.GEO.2', difficulty: 3,
    prompt: 'What is the volume of a sphere with radius $3$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$12\\pi$', correct: false },
      { id: 'B', label: '$36\\pi$', correct: true },
      { id: 'C', label: '$27\\pi$', correct: false },
      { id: 'D', label: '$108\\pi$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The sphere volume formula is on the reference sheet: $V = \\tfrac{4}{3}\\pi r^3$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try radius $1$: $V = \\tfrac{4}{3}\\pi(1)^3 = \\tfrac{4}{3}\\pi$. Cube the radius first, then multiply by $\\tfrac{4}{3}\\pi$ — the exponent applies to $r$ alone.' },
      { level: 'guide', text: '$\\tfrac{4}{3}\\pi (3)^3 = \\tfrac{4}{3}\\pi (27)$.' },
      { level: 'reveal', text: '$36\\pi$.' },
    ],
    learningObjective: 'Apply the sphere volume formula.',
    topic: 'Volume',
    explanation: [
      '$V = \\tfrac{4}{3}\\pi r^3$ with $r = 3$.',
      '$r^3 = 27$, so $V = \\tfrac{4}{3}\\pi(27) = 4\\pi \\times 9 = 36\\pi$.',
      'Cube the radius before multiplying by the fraction — $\\left(\\tfrac{4}{3} \\times 3\\right)^3$ is a different and wrong quantity.',
    ],
    alternativeExplanations: [
      { title: 'Use the reference sheet without losing time', steps: ['The sphere, cone, and pyramid formulas are all provided — you do not need to memorize them.', 'But each lookup costs about fifteen seconds, and geometry questions cluster late in a module.', 'Knowing them cold converts that lookup time into checking time.'] },
    ],
    tags: ['volume', 'sphere', 'reference-sheet'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 158, unit: 16, order: 8, slug: 'sat-volume-scaling',
    standard: 'SAT.GEO.2', difficulty: 3,
    prompt: 'All three dimensions of a rectangular prism are doubled. The volume of the new prism is how many times the volume of the original?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Volume multiplies three lengths together, and each one doubled.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a unit cube: a $1 \\times 1 \\times 1$ cube has volume $1$; doubled to $2 \\times 2 \\times 2$ it has volume $8$. Each of the three dimensions contributes one factor of $2$.' },
      { level: 'guide', text: '$2 \\times 2 \\times 2$.' },
      { level: 'reveal', text: '$8$ times.' },
    ],
    learningObjective: 'Apply the cube relationship between linear scale and volume.',
    topic: 'Similarity',
    explanation: [
      'Volume is $\\ell wh$. Doubling each of the three dimensions gives $(2\\ell)(2w)(2h) = 8\\ell wh$.',
      'So the volume becomes $8$ times as large.',
      'Concretely: a $2 \\times 3 \\times 4$ prism has volume $24$; doubled to $4 \\times 6 \\times 8$ it has volume $192 = 8 \\times 24$ ✓',
    ],
    alternativeExplanations: [
      { title: 'The 1, 2, 3 rule', steps: ['Scaling lengths by $k$ multiplies lengths by $k$, areas by $k^2$, and volumes by $k^3$.', 'The exponent is just the number of dimensions being measured.', 'Doubling gives $\\times 2$, $\\times 4$, $\\times 8$ — and the trap answer is always the one that scaled linearly.'] },
    ],
    tags: ['scaling', 'volume', 'similarity'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 159, unit: 16, order: 9, slug: 'sat-similar-triangle-side',
    standard: 'SAT.GEO.2', difficulty: 3,
    prompt: 'Triangle $ABC$ is similar to triangle $DEF$. Side $AB = 6$ corresponds to side $DE = 15$, and side $BC = 8$. What is the length of side $EF$?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the scale factor from the pair of sides you know.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easy scale: if $AB = 2$ matches $DE = 6$, the factor is $3$, so a side of $5$ becomes $15$. Find the factor from the known pair, then apply it.' },
      { level: 'guide', text: '$15 \\div 6 = 2.5$.' },
      { level: 'reveal', text: '$8 \\times 2.5 = 20$.' },
    ],
    learningObjective: 'Use a similarity scale factor to find a missing side.',
    topic: 'Similarity',
    explanation: [
      'Corresponding sides of similar triangles are in a constant ratio: $\\dfrac{DE}{AB} = \\dfrac{15}{6} = 2.5$.',
      'Every side of $DEF$ is $2.5$ times its partner in $ABC$.',
      '$EF = 2.5 \\times BC = 2.5 \\times 8 = 20$.',
    ],
    alternativeExplanations: [
      { title: 'Set up a proportion instead', steps: ['$\\dfrac{AB}{DE} = \\dfrac{BC}{EF}$, so $\\dfrac{6}{15} = \\dfrac{8}{EF}$.', 'Cross-multiply: $6 \\cdot EF = 120$, so $EF = 20$.', 'Whichever route you take, keep the two triangles in a consistent order on both sides of the equation — mixing them up is how this question is usually lost.'] },
    ],
    tags: ['similarity', 'proportion', 'triangle'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 160, unit: 16, order: 10, slug: 'sat-cone-volume',
    standard: 'SAT.GEO.2', difficulty: 3,
    prompt: 'A cone and a cylinder have the same radius and the same height. The cylinder has a volume of $60$ cubic inches. What is the volume, in cubic inches, of the cone?',
    answerType: 'numeric', primaryAnswer: '20', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A cone with the same base and height holds one third as much as a cylinder.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try matching solids: a cylinder of volume $30$ has a same-base same-height cone of volume $10$. The cone is always one third — no need to know $r$ or $h$.' },
      { level: 'guide', text: '$60 \\div 3$.' },
      { level: 'reveal', text: '$20$ cubic inches.' },
    ],
    learningObjective: 'Relate cone and cylinder volumes with matching base and height.',
    topic: 'Volume',
    explanation: [
      'Cylinder volume is $\\pi r^2 h$; cone volume is $\\tfrac{1}{3}\\pi r^2 h$.',
      'With the same $r$ and $h$, the cone holds exactly one third as much.',
      '$60 \\div 3 = 20$ cubic inches.',
    ],
    alternativeExplanations: [
      { title: 'Where every one-third comes from', steps: ['Cone-to-cylinder and pyramid-to-prism are both exactly $\\tfrac{1}{3}$, given the same base and height.', 'The factor appears whenever a solid tapers to a single point instead of running straight up.', 'Recognizing this lets you answer without computing $r$ or $h$ at all — which is exactly why the question withholds them.'] },
    ],
    tags: ['volume', 'cone', 'cylinder', 'ratio'], estimatedSeconds: 70,
  },

  // ═══════════ UNIT 17 — Right Triangles and Trigonometry ═══════════
  {
    domain: 'SAT', num: 161, unit: 17, order: 1, slug: 'sat-pythagorean-basic',
    standard: 'SAT.GEO.3', difficulty: 1,
    prompt: 'A right triangle has legs of length $6$ and $8$. What is the length of the hypotenuse?',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Use $a^2 + b^2 = c^2$ — or recognize a familiar triple.' },
      { level: 'guide', text: '$36 + 64 = 100$.' },
      { level: 'reveal', text: '$c = \\sqrt{100} = 10$.' },
    ],
    learningObjective: 'Apply the Pythagorean theorem to find a hypotenuse.',
    topic: 'Pythagorean theorem',
    explanation: [
      '$a^2 + b^2 = c^2$, so $6^2 + 8^2 = c^2$.',
      '$36 + 64 = 100$, so $c = 10$.',
      'This is the $3$-$4$-$5$ triple doubled — recognizing it skips the arithmetic entirely.',
    ],
    alternativeExplanations: [
      { title: 'The triples worth memorizing', steps: ['$3$-$4$-$5$, $5$-$12$-$13$, $8$-$15$-$17$, $7$-$24$-$25$ — and every multiple of each.', '$6$-$8$-$10$, $9$-$12$-$15$, and $10$-$24$-$26$ are all disguised versions of these.', 'Spotting one turns a square-root computation into instant recall, which matters most late in a module.'] },
    ],
    tags: ['pythagorean', 'triple'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 162, unit: 17, order: 2, slug: 'sat-sine-ratio',
    standard: 'SAT.GEO.3', difficulty: 1,
    prompt: 'In a right triangle, the side opposite angle $\\theta$ has length $3$ and the hypotenuse has length $5$. What is the value of $\\sin\\theta$? Give your answer as a decimal.',
    answerType: 'numeric', primaryAnswer: '0.6', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.001,
    alternativeAnswers: ['3/5', '.6'],
    hints: [
      { level: 'nudge', text: 'SOH: sine is opposite over hypotenuse.' },
      { level: 'guide', text: '$\\sin\\theta = \\dfrac{3}{5}$.' },
      { level: 'reveal', text: '$0.6$.' },
    ],
    learningObjective: 'Compute a sine ratio in a right triangle.',
    topic: 'Right-triangle trigonometry',
    explanation: [
      'SOH-CAH-TOA: $\\sin = \\dfrac{\\text{opposite}}{\\text{hypotenuse}}$.',
      '$\\sin\\theta = \\dfrac{3}{5} = 0.6$.',
      'The third side would be $4$, making this a $3$-$4$-$5$ triangle.',
    ],
    alternativeExplanations: [
      { title: 'The hypotenuse never changes; the others do', steps: ['The hypotenuse is always the side across from the right angle, regardless of which acute angle you are working with.', 'But "opposite" and "adjacent" swap when you switch from one acute angle to the other.', 'Label the triangle relative to the named angle *before* choosing a ratio.'] },
    ],
    tags: ['trigonometry', 'sine', 'sohcahtoa'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 163, unit: 17, order: 3, slug: 'sat-45-45-90',
    standard: 'SAT.GEO.3', difficulty: 2,
    prompt: 'A $45°$-$45°$-$90°$ triangle has legs of length $7$. What is the length of the hypotenuse?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$7$', correct: false },
      { id: 'B', label: '$7\\sqrt{2}$', correct: true },
      { id: 'C', label: '$7\\sqrt{3}$', correct: false },
      { id: 'D', label: '$14$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The sides of a $45$-$45$-$90$ triangle are in the ratio $1 : 1 : \\sqrt{2}$.' },
      { level: 'guide', text: 'The hypotenuse is the leg times $\\sqrt{2}$.' },
      { level: 'reveal', text: '$7\\sqrt{2}$.' },
    ],
    learningObjective: 'Apply the 45-45-90 side ratio.',
    topic: 'Special right triangles',
    explanation: [
      'In a $45$-$45$-$90$ triangle the two legs are equal and the hypotenuse is $\\sqrt{2}$ times a leg.',
      'So the hypotenuse is $7\\sqrt{2}$.',
      'Verify with Pythagoras: $7^2 + 7^2 = 98$, and $\\sqrt{98} = 7\\sqrt{2}$ ✓',
    ],
    alternativeExplanations: [
      { title: 'The two special triangles', steps: ['$45$-$45$-$90$: sides $1 : 1 : \\sqrt{2}$, an isosceles right triangle — half a square along its diagonal.', '$30$-$60$-$90$: sides $1 : \\sqrt{3} : 2$, with the shortest side opposite the $30°$ — half an equilateral triangle.', 'Choice C uses the wrong triangle\'s radical, which is why both appear among the choices.'] },
    ],
    tags: ['special-triangle', '45-45-90'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 164, unit: 17, order: 4, slug: 'sat-30-60-90',
    standard: 'SAT.GEO.3', difficulty: 2,
    prompt: 'In a $30°$-$60°$-$90°$ triangle, the side opposite the $30°$ angle has length $5$. What is the length of the hypotenuse?',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The sides are in the ratio $1 : \\sqrt{3} : 2$, shortest opposite the $30°$.' },
      { level: 'guide', text: 'The hypotenuse is twice the shortest side.' },
      { level: 'reveal', text: '$2 \\times 5 = 10$.' },
    ],
    learningObjective: 'Apply the 30-60-90 side ratio.',
    topic: 'Special right triangles',
    explanation: [
      'In a $30$-$60$-$90$ triangle the sides are $x$, $x\\sqrt{3}$, and $2x$, with $x$ opposite the $30°$ angle.',
      'Here $x = 5$, so the hypotenuse is $2(5) = 10$.',
      'The remaining side, opposite the $60°$, is $5\\sqrt{3}$.',
    ],
    alternativeExplanations: [
      { title: 'Bigger angle, bigger opposite side', steps: ['In any triangle the largest angle faces the longest side.', 'So the $30°$ faces the shortest side and the $90°$ faces the hypotenuse — this orders the sides without memorizing which is which.', 'If your answer puts a long side opposite a small angle, you have matched them backwards.'] },
    ],
    tags: ['special-triangle', '30-60-90'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 165, unit: 17, order: 5, slug: 'sat-tangent-ratio',
    standard: 'SAT.GEO.3', difficulty: 2,
    prompt: 'In a right triangle, the side opposite angle $\\theta$ has length $12$ and the side adjacent to $\\theta$ has length $5$. What is the value of $\\tan\\theta$? Give your answer as a decimal.',
    answerType: 'numeric', primaryAnswer: '2.4', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.001,
    alternativeAnswers: ['12/5'],
    hints: [
      { level: 'nudge', text: 'TOA: tangent is opposite over adjacent.' },
      { level: 'guide', text: '$\\tan\\theta = \\dfrac{12}{5}$.' },
      { level: 'reveal', text: '$2.4$.' },
    ],
    learningObjective: 'Compute a tangent ratio in a right triangle.',
    topic: 'Right-triangle trigonometry',
    explanation: [
      '$\\tan = \\dfrac{\\text{opposite}}{\\text{adjacent}} = \\dfrac{12}{5} = 2.4$.',
      'The hypotenuse here would be $13$ — this is a $5$-$12$-$13$ triangle.',
      'Note that tangent, unlike sine and cosine, can exceed $1$.',
    ],
    alternativeExplanations: [
      { title: 'Range as a sanity check', steps: ['Sine and cosine are always between $-1$ and $1$, because the hypotenuse is the longest side.', 'Tangent has no such bound — it can be any real number.', 'So a sine answer above $1$ is definitely wrong, but a tangent above $1$ is perfectly ordinary.'] },
    ],
    tags: ['trigonometry', 'tangent', 'sohcahtoa'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 166, unit: 17, order: 6, slug: 'sat-cofunction-identity',
    standard: 'SAT.GEO.3', difficulty: 2,
    prompt: 'In a right triangle, angles $A$ and $B$ are the two acute angles. If $\\sin A = 0.8$, what is the value of $\\cos B$?',
    answerType: 'numeric', primaryAnswer: '0.8', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.001,
    alternativeAnswers: ['4/5', '.8'],
    hints: [
      { level: 'nudge', text: 'The two acute angles of a right triangle are complementary.' },
      { level: 'guide', text: 'And $\\sin x = \\cos(90° - x)$.' },
      { level: 'reveal', text: 'So $\\cos B = \\sin A = 0.8$.' },
    ],
    learningObjective: 'Apply the complementary-angle (cofunction) identity.',
    topic: 'Trigonometric identities',
    explanation: [
      'The acute angles of a right triangle sum to $90°$, so $B = 90° - A$.',
      'The cofunction identity says $\\cos(90° - A) = \\sin A$.',
      'Therefore $\\cos B = \\sin A = 0.8$.',
    ],
    alternativeExplanations: [
      { title: 'See it in the triangle', steps: ['The side opposite angle $A$ is the side *adjacent* to angle $B$ — it is the same physical side.', 'So $\\sin A$ and $\\cos B$ are literally the same ratio, over the shared hypotenuse.', 'That is the whole content of the cofunction identity, and it is a recurring SAT question.'] },
    ],
    tags: ['trigonometry', 'cofunction', 'complementary'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 167, unit: 17, order: 7, slug: 'sat-missing-leg',
    standard: 'SAT.GEO.3', difficulty: 3,
    prompt: 'A right triangle has a hypotenuse of length $13$ and one leg of length $5$. What is the length of the other leg?',
    answerType: 'numeric', primaryAnswer: '12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Rearrange $a^2 + b^2 = c^2$ to solve for the missing leg.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a known triple: hypotenuse $5$ with a leg of $3$ gives $\\sqrt{25 - 9} = 4$. Finding a leg means subtracting, and the answer must come out smaller than the hypotenuse.' },
      { level: 'guide', text: '$b^2 = 13^2 - 5^2 = 169 - 25 = 144$.' },
      { level: 'reveal', text: '$b = 12$.' },
    ],
    learningObjective: 'Apply the Pythagorean theorem to find a leg.',
    topic: 'Pythagorean theorem',
    explanation: [
      'The hypotenuse is $c = 13$, so $5^2 + b^2 = 13^2$.',
      '$b^2 = 169 - 25 = 144$, giving $b = 12$.',
      'This is the $5$-$12$-$13$ triple.',
    ],
    alternativeExplanations: [
      { title: 'Subtract when finding a leg, add when finding the hypotenuse', steps: ['Adding here would give $\\sqrt{169 + 25} \\approx 13.9$ — larger than the hypotenuse, which is impossible.', 'The hypotenuse is always the longest side, so a leg must come out smaller than it.', 'That plausibility check catches the add/subtract error immediately.'] },
    ],
    tags: ['pythagorean', 'missing-leg'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 168, unit: 17, order: 8, slug: 'sat-cos-to-sin',
    standard: 'SAT.GEO.3', difficulty: 3,
    prompt: 'In a right triangle, $\\cos\\theta = \\dfrac{5}{13}$ where $\\theta$ is an acute angle. What is the value of $\\sin\\theta$? Give your answer as a decimal rounded to the nearest hundredth.',
    answerType: 'numeric', primaryAnswer: '0.92', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.005,
    alternativeAnswers: ['12/13'],
    hints: [
      { level: 'nudge', text: 'Cosine gives you the adjacent side and the hypotenuse. Find the third side.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a $3$-$4$-$5$ triangle: if $\\cos\\theta = \\tfrac{3}{5}$, the third side is $4$, so $\\sin\\theta = \\tfrac{4}{5}$. Sketch the triangle from the ratio, then read the side you need.' },
      { level: 'guide', text: 'Adjacent $= 5$, hypotenuse $= 13$, so the opposite side is $12$.' },
      { level: 'reveal', text: '$\\sin\\theta = \\dfrac{12}{13} \\approx 0.92$.' },
    ],
    learningObjective: 'Find one trig ratio from another using the triangle sides.',
    topic: 'Right-triangle trigonometry',
    explanation: [
      '$\\cos\\theta = \\dfrac{\\text{adjacent}}{\\text{hypotenuse}} = \\dfrac{5}{13}$, so treat the adjacent side as $5$ and the hypotenuse as $13$.',
      'By the Pythagorean theorem the opposite side is $\\sqrt{169 - 25} = 12$.',
      '$\\sin\\theta = \\dfrac{\\text{opposite}}{\\text{hypotenuse}} = \\dfrac{12}{13} \\approx 0.92$.',
    ],
    alternativeExplanations: [
      { title: 'Or use the Pythagorean identity', steps: ['$\\sin^2\\theta + \\cos^2\\theta = 1$, so $\\sin^2\\theta = 1 - \\left(\\tfrac{5}{13}\\right)^2 = 1 - \\tfrac{25}{169} = \\tfrac{144}{169}$.', '$\\sin\\theta = \\tfrac{12}{13}$, taking the positive root since $\\theta$ is acute.', 'Sketching the triangle is usually faster and less error-prone, but the identity works when no triangle is described.'] },
    ],
    tags: ['trigonometry', 'pythagorean-identity', 'sine-cosine'], estimatedSeconds: 85,
  },
  {
    domain: 'SAT', num: 169, unit: 17, order: 9, slug: 'sat-ladder-trig',
    standard: 'SAT.GEO.3', difficulty: 3,
    prompt: 'A $20$-foot ladder leans against a wall, making a $60°$ angle with the ground. How far up the wall, in feet, does the ladder reach? Give your answer in the form $a\\sqrt{3}$ by entering the value of $a$.',
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The height up the wall is the side opposite the $60°$ angle, and the ladder is the hypotenuse.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a smaller ladder: a $10$-foot ladder at $60°$ is a $30$-$60$-$90$ triangle with hypotenuse $10$, so the short side is $5$ and the height is $5\\sqrt{3}$. Same triangle, half the size.' },
      { level: 'guide', text: 'This is a $30$-$60$-$90$ triangle with hypotenuse $20$, so the short side is $10$.' },
      { level: 'reveal', text: 'The side opposite the $60°$ is $10\\sqrt{3}$, so $a = 10$.' },
    ],
    learningObjective: 'Model a real-world situation with a special right triangle.',
    topic: 'Trigonometry in context',
    explanation: [
      'The ladder, the wall, and the ground form a right triangle with the ladder as the hypotenuse ($20$ feet).',
      'The ladder makes a $60°$ angle with the ground, so this is a $30$-$60$-$90$ triangle. The hypotenuse is $2x$, so $x = 10$.',
      'The height up the wall is opposite the $60°$ angle, which is $x\\sqrt{3} = 10\\sqrt{3}$ feet. So $a = 10$.',
    ],
    alternativeExplanations: [
      { title: 'Or go straight through sine', steps: ['$\\sin 60° = \\dfrac{\\text{height}}{20}$, so height $= 20\\sin 60° = 20 \\cdot \\dfrac{\\sqrt{3}}{2} = 10\\sqrt{3}$.', 'Same answer, and it does not require noticing the special triangle.', 'Recognizing $30$-$60$-$90$ is faster; the sine route is the reliable fallback.'] },
    ],
    tags: ['trigonometry', 'special-triangle', 'word-problem'], estimatedSeconds: 95,
  },
  {
    domain: 'SAT', num: 170, unit: 17, order: 10, slug: 'sat-angle-of-elevation',
    standard: 'SAT.GEO.3', difficulty: 3,
    prompt: 'From a point on level ground $40$ feet from the base of a tree, the angle of elevation to the top of the tree is $\\theta$, where $\\tan\\theta = 1.5$. What is the height of the tree, in feet?',
    answerType: 'numeric', primaryAnswer: '60', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Tangent relates the opposite side (the height) to the adjacent side (the ground distance).' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try easy numbers: if $\\tan\\theta = 2$ and the ground distance is $10$ feet, the height is $2 \\times 10 = 20$ feet. Tangent times the adjacent side gives the opposite side.' },
      { level: 'guide', text: '$\\tan\\theta = \\dfrac{\\text{height}}{40} = 1.5$.' },
      { level: 'reveal', text: 'Height $= 1.5 \\times 40 = 60$ feet.' },
    ],
    learningObjective: 'Use tangent to solve an angle-of-elevation problem.',
    topic: 'Trigonometry in context',
    explanation: [
      'The tree, the ground, and the line of sight form a right triangle. The height is opposite the angle; the $40$ feet is adjacent.',
      '$\\tan\\theta = \\dfrac{\\text{opposite}}{\\text{adjacent}} = \\dfrac{h}{40} = 1.5$.',
      '$h = 1.5 \\times 40 = 60$ feet.',
    ],
    alternativeExplanations: [
      { title: 'Tangent is the elevation ratio', steps: ['Angle-of-elevation and angle-of-depression problems almost always use tangent, because the two known quantities are height and horizontal distance — the two legs.', 'Sine and cosine appear only when the hypotenuse (the direct line of sight) is involved.', 'Identifying which two sides the problem hands you selects the ratio immediately.'] },
    ],
    tags: ['trigonometry', 'angle-of-elevation', 'tangent'], estimatedSeconds: 80,
  },

  // ═══════════ UNIT 18 — Circles: Equations, Arcs, and Sectors ═══════════
  {
    domain: 'SAT', num: 171, unit: 18, order: 1, slug: 'sat-circle-radius-from-equation',
    standard: 'SAT.GEO.4', difficulty: 1,
    prompt: 'The equation of a circle is $(x - 3)^2 + (y + 2)^2 = 25$. What is the radius of the circle?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'In standard form the right side is $r^2$, not $r$.' },
      { level: 'guide', text: 'So $r^2 = 25$.' },
      { level: 'reveal', text: '$r = 5$.' },
    ],
    learningObjective: 'Read the radius from the standard form of a circle equation.',
    topic: 'Circle equations',
    explanation: [
      'Standard form is $(x - h)^2 + (y - k)^2 = r^2$.',
      'Here $r^2 = 25$, so $r = \\sqrt{25} = 5$.',
      'Answering $25$ is the trap — the right side is the radius *squared*.',
    ],
    alternativeExplanations: [
      { title: 'Two traps in one equation', steps: ['First: the right side is $r^2$, so take a square root.', 'Second: the centre signs are opposite what they appear — $(x - 3)$ means $h = 3$, and $(y + 2)$ means $k = -2$.', 'Nearly every circle-equation question is built on one or both of these.'] },
    ],
    tags: ['circle', 'standard-form', 'radius'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 172, unit: 18, order: 2, slug: 'sat-circle-center',
    standard: 'SAT.GEO.4', difficulty: 1,
    prompt: 'What is the center of the circle $(x - 3)^2 + (y + 2)^2 = 25$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$(3, 2)$', correct: false },
      { id: 'B', label: '$(3, -2)$', correct: true },
      { id: 'C', label: '$(-3, 2)$', correct: false },
      { id: 'D', label: '$(-3, -2)$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The form is $(x - h)^2 + (y - k)^2 = r^2$ with centre $(h, k)$.' },
      { level: 'guide', text: '$(y + 2)$ is really $(y - (-2))$.' },
      { level: 'reveal', text: 'The centre is $(3, -2)$.' },
    ],
    learningObjective: 'Read the center from the standard form of a circle equation.',
    topic: 'Circle equations',
    explanation: [
      'Match against $(x - h)^2 + (y - k)^2 = r^2$.',
      '$(x - 3)$ gives $h = 3$. $(y + 2) = (y - (-2))$ gives $k = -2$.',
      'The centre is $(3, -2)$.',
    ],
    alternativeExplanations: [
      { title: 'Set each squared term to zero', steps: ['The centre is where both squared terms vanish, so solve $x - 3 = 0$ and $y + 2 = 0$.', 'That gives $x = 3$ and $y = -2$ directly, with the sign flip handled by the algebra rather than by memory.', 'This is the same reliable trick that reads a parabola vertex out of vertex form.'] },
    ],
    tags: ['circle', 'center', 'standard-form'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 173, unit: 18, order: 3, slug: 'sat-circumference',
    standard: 'SAT.GEO.4', difficulty: 2,
    prompt: 'What is the circumference of a circle with radius $7$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$7\\pi$', correct: false },
      { id: 'B', label: '$14\\pi$', correct: true },
      { id: 'C', label: '$49\\pi$', correct: false },
      { id: 'D', label: '$28\\pi$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Circumference is $2\\pi r$.' },
      { level: 'guide', text: '$2\\pi(7)$.' },
      { level: 'reveal', text: '$14\\pi$.' },
    ],
    learningObjective: 'Compute a circumference from a radius.',
    topic: 'Circles',
    explanation: [
      'Circumference $= 2\\pi r = 2\\pi(7) = 14\\pi$.',
      'Choice C, $49\\pi$, is the *area* — it squares the radius instead of doubling it.',
      'Circumference is also $\\pi d$, and the diameter here is $14$.',
    ],
    alternativeExplanations: [
      { title: 'Which formula, at a glance', steps: ['Circumference has no exponent: $2\\pi r$, or $\\pi d$.', 'Area has the square: $\\pi r^2$.', 'If the answer choices include both $14\\pi$ and $49\\pi$, the question is checking exactly this distinction.'] },
    ],
    tags: ['circle', 'circumference'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 174, unit: 18, order: 4, slug: 'sat-arc-length',
    standard: 'SAT.GEO.4', difficulty: 2,
    prompt: 'A circle has radius $8$. What is the length of an arc with a central angle of $90°$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$2\\pi$', correct: false },
      { id: 'B', label: '$4\\pi$', correct: true },
      { id: 'C', label: '$8\\pi$', correct: false },
      { id: 'D', label: '$16\\pi$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The arc is a fraction of the whole circumference — which fraction?' },
      { level: 'guide', text: '$\\dfrac{90}{360} = \\dfrac{1}{4}$, and the circumference is $16\\pi$.' },
      { level: 'reveal', text: '$\\tfrac{1}{4}(16\\pi) = 4\\pi$.' },
    ],
    learningObjective: 'Compute an arc length as a fraction of the circumference.',
    topic: 'Arcs and sectors',
    explanation: [
      'The central angle is $\\dfrac{90}{360} = \\dfrac{1}{4}$ of the full circle.',
      'The full circumference is $2\\pi(8) = 16\\pi$.',
      'The arc is one quarter of that: $4\\pi$.',
    ],
    alternativeExplanations: [
      { title: 'One idea covers arcs and sectors both', steps: ['Compute the fraction $\\dfrac{\\text{central angle}}{360}$ once.', 'Multiply it by the circumference for arc length, or by the area for sector area.', 'Do not memorize two formulas — memorize the fraction and then pick what to multiply it by.'] },
    ],
    tags: ['circle', 'arc-length', 'fraction'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 175, unit: 18, order: 5, slug: 'sat-sector-area',
    standard: 'SAT.GEO.4', difficulty: 2,
    prompt: 'A circle has radius $6$. What is the area of a sector with a central angle of $60°$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$2\\pi$', correct: false },
      { id: 'B', label: '$6\\pi$', correct: true },
      { id: 'C', label: '$12\\pi$', correct: false },
      { id: 'D', label: '$36\\pi$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Find the fraction of the circle, then take that fraction of the area.' },
      { level: 'guide', text: '$\\dfrac{60}{360} = \\dfrac{1}{6}$, and the area is $36\\pi$.' },
      { level: 'reveal', text: '$\\tfrac{1}{6}(36\\pi) = 6\\pi$.' },
    ],
    learningObjective: 'Compute a sector area as a fraction of the circle area.',
    topic: 'Arcs and sectors',
    explanation: [
      'The fraction of the circle is $\\dfrac{60}{360} = \\dfrac{1}{6}$.',
      'The full area is $\\pi r^2 = \\pi(6)^2 = 36\\pi$.',
      'The sector area is $\\dfrac{1}{6} \\times 36\\pi = 6\\pi$.',
    ],
    alternativeExplanations: [
      { title: 'Sector versus arc', steps: ['A sector is a pie slice — a two-dimensional region measured in square units.', 'An arc is just the curved edge — a one-dimensional length.', 'Here the arc would be $\\tfrac{1}{6}(12\\pi) = 2\\pi$, which is choice A. Both appear among the choices deliberately.'] },
    ],
    tags: ['circle', 'sector-area', 'fraction'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 176, unit: 18, order: 6, slug: 'sat-degrees-to-radians',
    standard: 'SAT.GEO.4', difficulty: 2,
    prompt: 'What is the radian measure of an angle of $135°$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$\\dfrac{3\\pi}{4}$', correct: true },
      { id: 'B', label: '$\\dfrac{4\\pi}{3}$', correct: false },
      { id: 'C', label: '$\\dfrac{2\\pi}{3}$', correct: false },
      { id: 'D', label: '$\\dfrac{3\\pi}{2}$', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Multiply by $\\dfrac{\\pi}{180}$ to convert degrees to radians.' },
      { level: 'guide', text: '$135 \\times \\dfrac{\\pi}{180} = \\dfrac{135\\pi}{180}$.' },
      { level: 'reveal', text: 'Simplify by $45$: $\\dfrac{3\\pi}{4}$.' },
    ],
    learningObjective: 'Convert between degrees and radians.',
    topic: 'Radians',
    explanation: [
      'Since $180° = \\pi$ radians, multiply degrees by $\\dfrac{\\pi}{180}$.',
      '$135 \\times \\dfrac{\\pi}{180} = \\dfrac{135\\pi}{180}$, and $\\gcd(135, 180) = 45$.',
      'Simplifying gives $\\dfrac{3\\pi}{4}$.',
    ],
    alternativeExplanations: [
      { title: 'Reason in quarter-turns', steps: ['$180°$ is $\\pi$, so $90°$ is $\\dfrac{\\pi}{2}$ and $45°$ is $\\dfrac{\\pi}{4}$.', '$135° = 3 \\times 45°$, so it is $3 \\times \\dfrac{\\pi}{4} = \\dfrac{3\\pi}{4}$.', 'Also a quick check: $135°$ is between $90°$ and $180°$, so the answer must be between $\\dfrac{\\pi}{2}$ and $\\pi$ — which eliminates B and D immediately.'] },
    ],
    tags: ['radians', 'conversion'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 177, unit: 18, order: 7, slug: 'sat-circle-complete-square',
    standard: 'SAT.GEO.4', difficulty: 3,
    prompt: 'The equation $x^2 + y^2 - 6x + 4y = 12$ describes a circle. What is the radius of the circle?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Complete the square in $x$ and again in $y$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try one variable: $x^2 - 4x = 5$ becomes $(x^2 - 4x + 4) = 5 + 4$, so $(x - 2)^2 = 9$. Do exactly that twice — once for $x$, once for $y$ — adding to both sides each time.' },
      { level: 'guide', text: '$(x^2 - 6x + 9) + (y^2 + 4y + 4) = 12 + 9 + 4$.' },
      { level: 'reveal', text: '$(x - 3)^2 + (y + 2)^2 = 25$, so $r = 5$.' },
    ],
    learningObjective: 'Convert an expanded circle equation to standard form.',
    topic: 'Circle equations',
    explanation: [
      'Group the terms: $(x^2 - 6x) + (y^2 + 4y) = 12$.',
      'Complete each square. For $x$: half of $-6$ is $-3$, squared is $9$. For $y$: half of $4$ is $2$, squared is $4$. Add both to *each* side: $(x^2 - 6x + 9) + (y^2 + 4y + 4) = 12 + 9 + 4$.',
      'That is $(x - 3)^2 + (y + 2)^2 = 25$, so the centre is $(3, -2)$ and the radius is $5$.',
    ],
    alternativeExplanations: [
      { title: 'The step people forget', steps: ['Whatever you add to complete a square must also be added to the right side — twice here, once for each variable.', 'Skipping that gives a right side of $12$ and a radius of $\\sqrt{12}$, which is wrong.', 'Write the additions on both sides in the same motion and the error cannot happen.'] },
    ],
    tags: ['circle', 'completing-the-square', 'radius'], estimatedSeconds: 100,
  },
  {
    domain: 'SAT', num: 178, unit: 18, order: 8, slug: 'sat-arc-length-radians',
    standard: 'SAT.GEO.4', difficulty: 3,
    prompt: 'A circle has radius $5$. What is the length of an arc that subtends a central angle of $1.2$ radians?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'When the angle is in radians, arc length has a very short formula.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try radius $1$: an angle of $2$ radians subtends an arc of $2$, since $s = r\\theta = 1 \\times 2$. That is the definition of a radian, which is why the formula is so short.' },
      { level: 'guide', text: '$s = r\\theta$.' },
      { level: 'reveal', text: '$s = 5 \\times 1.2 = 6$.' },
    ],
    learningObjective: 'Use the radian arc-length formula.',
    topic: 'Radians',
    explanation: [
      'For an angle measured in radians, arc length is $s = r\\theta$ — no fractions of $360$ required.',
      '$s = 5 \\times 1.2 = 6$.',
      'This simplicity is the whole reason radians exist as a unit.',
    ],
    alternativeExplanations: [
      { title: 'The formula only works in radians', steps: ['With $\\theta$ in degrees you must use $s = \\dfrac{\\theta}{360} \\cdot 2\\pi r$ instead.', 'Plugging a degree measure into $s = r\\theta$ gives an answer far too large.', 'Check the units the question states before choosing the formula — the SAT mixes both deliberately.'] },
    ],
    tags: ['arc-length', 'radians', 'formula'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 179, unit: 18, order: 9, slug: 'sat-area-from-circumference',
    standard: 'SAT.GEO.4', difficulty: 3,
    prompt: 'A circle has a circumference of $20\\pi$. What is its area?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$20\\pi$', correct: false },
      { id: 'B', label: '$100\\pi$', correct: true },
      { id: 'C', label: '$400\\pi$', correct: false },
      { id: 'D', label: '$40\\pi$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Work back to the radius first — it is the bridge between the two formulas.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a small circle: circumference $4\\pi$ gives $2\\pi r = 4\\pi$, so $r = 2$ and the area is $4\\pi$. Route through the radius — it connects the two formulas.' },
      { level: 'guide', text: '$2\\pi r = 20\\pi$ gives $r = 10$.' },
      { level: 'reveal', text: 'Area $= \\pi(10)^2 = 100\\pi$.' },
    ],
    learningObjective: 'Chain the circumference and area formulas through the radius.',
    topic: 'Circles',
    explanation: [
      'From the circumference: $2\\pi r = 20\\pi$, so $r = 10$.',
      'Then the area is $\\pi r^2 = \\pi(10)^2 = 100\\pi$.',
      'Choice C uses the diameter $20$ in place of the radius.',
    ],
    alternativeExplanations: [
      { title: 'The radius is always the middle step', steps: ['Any circle question that gives one measure and asks for another routes through the radius.', 'Circumference → radius → area, or area → radius → circumference.', 'Solving for $r$ first turns a two-formula question into two one-formula questions.'] },
    ],
    tags: ['circle', 'area', 'circumference', 'multi-step'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 180, unit: 18, order: 10, slug: 'sat-central-angle-from-arc',
    standard: 'SAT.GEO.4', difficulty: 3,
    prompt: 'In a circle of radius $9$, an arc has length $6\\pi$. What is the measure, in degrees, of the arc\'s central angle?',
    answerType: 'numeric', primaryAnswer: '120', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'What fraction of the full circumference is this arc?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a half circle: radius $2$ gives circumference $4\\pi$, so an arc of $2\\pi$ is half the circle, or $180°$. Find the fraction, then take that fraction of $360°$.' },
      { level: 'guide', text: 'The circumference is $18\\pi$, and $\\dfrac{6\\pi}{18\\pi} = \\dfrac{1}{3}$.' },
      { level: 'reveal', text: '$\\tfrac{1}{3}$ of $360° = 120°$.' },
    ],
    learningObjective: 'Recover a central angle from an arc length.',
    topic: 'Arcs and sectors',
    explanation: [
      'The full circumference is $2\\pi(9) = 18\\pi$.',
      'The arc is $\\dfrac{6\\pi}{18\\pi} = \\dfrac{1}{3}$ of the circle.',
      'So the central angle is $\\dfrac{1}{3} \\times 360° = 120°$.',
    ],
    alternativeExplanations: [
      { title: 'Or use s = rθ and convert', steps: ['$6\\pi = 9\\theta$ gives $\\theta = \\dfrac{2\\pi}{3}$ radians.', 'Convert: $\\dfrac{2\\pi}{3} \\times \\dfrac{180}{\\pi} = 120°$.', 'Both routes work. The fraction-of-the-circle method avoids the conversion, so it is usually faster when the answer is wanted in degrees.'] },
    ],
    tags: ['circle', 'central-angle', 'arc-length'], estimatedSeconds: 85,
  },
];
