import type { SeedProblem } from './types';

// SAT — Advanced Math (blueprint area ADV, ~35% of the Math section). Units
// 6-10, problems 51-100. This is the area that separates a 600 from a 700:
// equivalent expressions, quadratics in all three forms, nonlinear systems,
// polynomial and rational equations, and exponential models.

export const problemsSATadv: SeedProblem[] = [
  // ═══════════════ UNIT 6 — Equivalent Expressions and Exponents ═══════════════
  {
    domain: 'SAT', num: 51, unit: 6, order: 1, slug: 'sat-multiply-same-base',
    standard: 'SAT.ADV.1', difficulty: 1,
    prompt: 'Which expression is equivalent to $x^5 \\cdot x^3$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$x^{8}$', correct: true },
      { id: 'B', label: '$x^{15}$', correct: false },
      { id: 'C', label: '$2x^{8}$', correct: false },
      { id: 'D', label: '$x^{2}$', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Same base, multiplied together — the exponents combine by addition.' },
      { level: 'guide', text: '$x^5 \\cdot x^3 = x^{5+3}$.' },
      { level: 'reveal', text: '$x^8$.' },
    ],
    learningObjective: 'Apply the product rule for exponents.',
    topic: 'Exponent rules',
    explanation: [
      'When powers of the same base are multiplied, add the exponents: $x^5 \\cdot x^3 = x^{5+3} = x^8$.',
      'Choice B multiplies the exponents, which is the rule for a power raised to a power, not for a product.',
      'Choice C invents a coefficient of $2$ — the bases multiply, they do not add.',
    ],
    alternativeExplanations: [
      { title: 'Count the factors', steps: ['$x^5$ is five copies of $x$; $x^3$ is three copies.', 'Multiplied together that is eight copies of $x$ in a row, which is $x^8$.', 'Whenever an exponent rule feels uncertain, writing out the factors for small cases settles it in seconds.'] },
    ],
    tags: ['exponents', 'product-rule'], estimatedSeconds: 35,
  },
  {
    domain: 'SAT', num: 52, unit: 6, order: 2, slug: 'sat-power-of-product',
    standard: 'SAT.ADV.1', difficulty: 1,
    prompt: 'Which expression is equivalent to $(2x^3)^2$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$2x^{6}$', correct: false },
      { id: 'B', label: '$4x^{5}$', correct: false },
      { id: 'C', label: '$4x^{6}$', correct: true },
      { id: 'D', label: '$2x^{5}$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The outside exponent applies to *everything* inside the parentheses — the $2$ as well as the $x^3$.' },
      { level: 'guide', text: '$2^2 = 4$, and $(x^3)^2 = x^{3 \\cdot 2}$.' },
      { level: 'reveal', text: '$4x^6$.' },
    ],
    learningObjective: 'Apply the power-of-a-product and power-of-a-power rules together.',
    topic: 'Exponent rules',
    explanation: [
      'Distribute the outer exponent to each factor: $(2x^3)^2 = 2^2 \\cdot (x^3)^2$.',
      '$2^2 = 4$, and for a power raised to a power the exponents multiply: $(x^3)^2 = x^6$.',
      'The result is $4x^6$. Choices A and D forget to square the coefficient; choice B adds the exponents instead of multiplying.',
    ],
    alternativeExplanations: [
      { title: 'Test with a number', steps: ['Let $x = 2$. Then $(2 \\cdot 2^3)^2 = (16)^2 = 256$.', 'Check the choices at $x = 2$: A gives $128$, B gives $128$, C gives $4 \\cdot 64 = 256$ ✓, D gives $64$.', 'Picking a single value eliminated three choices at once, with no rules needed.'] },
    ],
    tags: ['exponents', 'power-rule', 'plug-in'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 53, unit: 6, order: 3, slug: 'sat-negative-exponent',
    standard: 'SAT.ADV.1', difficulty: 2,
    prompt: 'Which expression is equivalent to $3x^{-2}$, for $x \\neq 0$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$-3x^{2}$', correct: false },
      { id: 'B', label: '$\\dfrac{3}{x^{2}}$', correct: true },
      { id: 'C', label: '$\\dfrac{1}{3x^{2}}$', correct: false },
      { id: 'D', label: '$\\dfrac{-1}{3x^{2}}$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'A negative exponent means reciprocal, not negative.' },
      { level: 'guide', text: 'The exponent $-2$ belongs to $x$ only, not to the coefficient $3$.' },
      { level: 'reveal', text: '$3x^{-2} = 3 \\cdot \\dfrac{1}{x^2} = \\dfrac{3}{x^2}$.' },
    ],
    learningObjective: 'Rewrite a negative exponent as a reciprocal.',
    topic: 'Negative exponents',
    explanation: [
      'A negative exponent flips its base into the denominator: $x^{-2} = \\dfrac{1}{x^2}$.',
      'The coefficient $3$ has no negative exponent, so it stays in the numerator: $\\dfrac{3}{x^2}$.',
      'Choice A treats the negative exponent as a negative sign. Choice C wrongly moves the $3$ down with the $x$.',
    ],
    alternativeExplanations: [
      { title: 'Only what carries the exponent moves', steps: ['In $3x^{-2}$, the $-2$ sits on $x$ alone.', 'Had the expression been $(3x)^{-2}$, the whole product would move down, giving $\\dfrac{1}{9x^2}$.', 'Reading exactly what the exponent attaches to is the whole question here — and it is a standard SAT distinction.'] },
    ],
    tags: ['exponents', 'negative-exponent'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 54, unit: 6, order: 4, slug: 'sat-difference-of-squares',
    standard: 'SAT.ADV.1', difficulty: 2,
    prompt: 'Which expression is equivalent to $x^2 - 9$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$(x - 3)^2$', correct: false },
      { id: 'B', label: '$(x + 3)(x - 3)$', correct: true },
      { id: 'C', label: '$(x + 3)^2$', correct: false },
      { id: 'D', label: '$(x - 9)(x + 1)$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Both terms are perfect squares, separated by a minus sign.' },
      { level: 'guide', text: 'The pattern $a^2 - b^2 = (a + b)(a - b)$ applies with $a = x$ and $b = 3$.' },
      { level: 'reveal', text: '$(x + 3)(x - 3)$.' },
    ],
    learningObjective: 'Factor a difference of two squares.',
    topic: 'Factoring',
    explanation: [
      '$x^2 - 9$ is $x^2 - 3^2$: a difference of squares.',
      'The pattern is $a^2 - b^2 = (a + b)(a - b)$, giving $(x + 3)(x - 3)$.',
      'Expanding confirms it: $x^2 - 3x + 3x - 9 = x^2 - 9$ ✓. Choice A expands to $x^2 - 6x + 9$, which has a middle term the original does not.',
    ],
    alternativeExplanations: [
      { title: 'Why the middle term vanishes', steps: ['Multiplying $(x + 3)(x - 3)$ produces $-3x$ and $+3x$, which cancel.', 'That cancellation is the whole reason the difference of squares factors so cleanly.', 'It is the single most frequently used factoring pattern on the SAT — recognizing "square minus square" on sight is worth real points.'] },
    ],
    tags: ['factoring', 'difference-of-squares'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 55, unit: 6, order: 5, slug: 'sat-simplify-rational',
    standard: 'SAT.ADV.1', difficulty: 2,
    prompt: 'For $x \\neq -2$, which expression is equivalent to $\\dfrac{x^2 - 4}{x + 2}$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$x - 2$', correct: true },
      { id: 'B', label: '$x + 2$', correct: false },
      { id: 'C', label: '$x^2 - 2$', correct: false },
      { id: 'D', label: '$x - 4$', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Factor the numerator before trying to cancel anything.' },
      { level: 'guide', text: '$x^2 - 4 = (x + 2)(x - 2)$.' },
      { level: 'reveal', text: 'The $(x + 2)$ factors cancel, leaving $x - 2$.' },
    ],
    learningObjective: 'Simplify a rational expression by factoring and cancelling.',
    topic: 'Rational expressions',
    explanation: [
      'Factor the numerator as a difference of squares: $x^2 - 4 = (x + 2)(x - 2)$.',
      'The expression becomes $\\dfrac{(x + 2)(x - 2)}{x + 2}$.',
      'Cancel the common factor $(x + 2)$, which is legal because $x \\neq -2$: the result is $x - 2$.',
    ],
    alternativeExplanations: [
      { title: 'Cancel factors, never terms', steps: ['You may only cancel something that multiplies the *entire* numerator and denominator.', 'Cancelling the $x$ from $\\dfrac{x^2 - 4}{x + 2}$ without factoring first is the classic error — it produces nonsense.', 'Factoring converts a sum into a product, which is exactly what makes cancelling legal.'] },
    ],
    tags: ['rational-expression', 'factoring', 'simplify'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 56, unit: 6, order: 6, slug: 'sat-fractional-exponent',
    standard: 'SAT.ADV.1', difficulty: 2,
    prompt: 'What is the value of $27^{2/3}$?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The denominator of the exponent is a root; the numerator is a power.' },
      { level: 'guide', text: 'Take the cube root first: $\\sqrt[3]{27} = 3$.' },
      { level: 'reveal', text: 'Then square it: $3^2 = 9$.' },
    ],
    learningObjective: 'Evaluate a fractional exponent as a root and a power.',
    topic: 'Rational exponents',
    explanation: [
      '$a^{m/n}$ means the $n$th root of $a$, raised to the $m$th power.',
      'Here $n = 3$ and $m = 2$: $\\sqrt[3]{27} = 3$, then $3^2 = 9$.',
      'Rooting before powering keeps the numbers small — going the other way means computing $27^2 = 729$ and then taking its cube root.',
    ],
    alternativeExplanations: [
      { title: 'Rewrite the base as a power', steps: ['$27 = 3^3$, so $27^{2/3} = (3^3)^{2/3}$.', 'Powers of powers multiply: $3^{3 \\cdot 2/3} = 3^2 = 9$.', 'When the base is a perfect power, this route is the cleanest and involves no roots at all.'] },
    ],
    tags: ['rational-exponents', 'radicals'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 57, unit: 6, order: 7, slug: 'sat-multiply-monomials',
    standard: 'SAT.ADV.1', difficulty: 3,
    prompt: 'Which expression is equivalent to $(3x^2y^3)(4x^5y)$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$12x^{7}y^{4}$', correct: true },
      { id: 'B', label: '$12x^{10}y^{3}$', correct: false },
      { id: 'C', label: '$7x^{7}y^{4}$', correct: false },
      { id: 'D', label: '$12x^{7}y^{3}$', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Handle the coefficients, the $x$ powers, and the $y$ powers as three separate jobs.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try one variable first: $(2x^3)(5x^4) = 10x^7$ — coefficients multiply, exponents add. Two variables just means running that same rule twice, once per letter.' },
      { level: 'guide', text: 'Coefficients multiply: $3 \\times 4 = 12$. Exponents on matching bases add.' },
      { level: 'reveal', text: '$x^{2+5} = x^7$ and $y^{3+1} = y^4$, giving $12x^7y^4$.' },
    ],
    learningObjective: 'Multiply monomials with multiple variables.',
    topic: 'Exponent rules',
    explanation: [
      'Multiply the coefficients: $3 \\times 4 = 12$.',
      'Add the exponents on $x$: $x^2 \\cdot x^5 = x^7$.',
      'Add the exponents on $y$, remembering that a bare $y$ has exponent $1$: $y^3 \\cdot y^1 = y^4$. The product is $12x^7y^4$.',
    ],
    alternativeExplanations: [
      { title: 'The invisible exponent', steps: ['Choice D is the trap: it forgets that the lone $y$ carries an exponent of $1$.', 'Any variable written without an exponent has an exponent of $1$, and any expression without a coefficient has a coefficient of $1$.', 'Writing those in explicitly before you start costs a second and prevents the most common slip in this question type.'] },
    ],
    tags: ['exponents', 'monomials'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 58, unit: 6, order: 8, slug: 'sat-simplify-radical',
    standard: 'SAT.ADV.1', difficulty: 3,
    prompt: 'Which expression is equivalent to $\\sqrt{50}$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$25\\sqrt{2}$', correct: false },
      { id: 'B', label: '$5\\sqrt{2}$', correct: true },
      { id: 'C', label: '$2\\sqrt{5}$', correct: false },
      { id: 'D', label: '$10\\sqrt{5}$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Look for the largest perfect square that divides $50$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easier radical: $\\sqrt{12} = \\sqrt{4}\\sqrt{3} = 2\\sqrt{3}$. Pull out the largest perfect square you can find; the rest stays under the root.' },
      { level: 'guide', text: '$50 = 25 \\times 2$, and $25$ is a perfect square.' },
      { level: 'reveal', text: '$\\sqrt{50} = \\sqrt{25}\\sqrt{2} = 5\\sqrt{2}$.' },
    ],
    learningObjective: 'Simplify a radical by extracting a perfect-square factor.',
    topic: 'Radicals',
    explanation: [
      'Split $50$ into a perfect square times the rest: $50 = 25 \\times 2$.',
      'Radicals distribute over multiplication: $\\sqrt{50} = \\sqrt{25} \\cdot \\sqrt{2} = 5\\sqrt{2}$.',
      'Choice A leaves the $25$ inside and outside at once — the square root of $25$ is $5$, not $25$.',
    ],
    alternativeExplanations: [
      { title: 'Check with a decimal', steps: ['$\\sqrt{50} \\approx 7.07$.', 'Evaluate the choices: A is about $35.4$, B is about $7.07$ ✓, C is about $4.47$, D is about $22.4$.', 'A quick decimal estimate is a reliable check on any radical-simplification question, and it needs no rules at all.'] },
    ],
    tags: ['radicals', 'simplify'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 59, unit: 6, order: 9, slug: 'sat-expand-binomials',
    standard: 'SAT.ADV.1', difficulty: 3,
    prompt: 'When $(2x - 3)(x + 5)$ is expanded and written in the form $ax^2 + bx + c$, what is the value of $b$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You only need the $x$ terms, not the whole expansion.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller binomials: $(x + 1)(x + 2) = x^2 + 3x + 2$, where the middle term $3x$ came from $2x + x$. Only the outer and inner products make an $x$ term.' },
      { level: 'guide', text: 'The two products giving an $x$ term are $2x \\cdot 5$ and $-3 \\cdot x$.' },
      { level: 'reveal', text: '$10x - 3x = 7x$, so $b = 7$.' },
    ],
    learningObjective: 'Extract a single coefficient from a binomial product.',
    topic: 'Expanding expressions',
    explanation: [
      'Expanding fully: $(2x - 3)(x + 5) = 2x^2 + 10x - 3x - 15 = 2x^2 + 7x - 15$.',
      'So $a = 2$, $b = 7$, and $c = -15$.',
      'The question asks only for $b$, which is $7$.',
    ],
    alternativeExplanations: [
      { title: 'Target just the term you need', steps: ['The $x$ term comes only from the outer and inner products of FOIL.', 'Outer: $2x \\cdot 5 = 10x$. Inner: $-3 \\cdot x = -3x$. Sum: $7x$.', 'Skipping the first and last products saves time and removes two chances to make a sign error.'] },
    ],
    tags: ['expanding', 'foil', 'coefficient'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 60, unit: 6, order: 10, slug: 'sat-match-coefficients',
    standard: 'SAT.ADV.1', difficulty: 3,
    prompt: 'The equation $(x + a)(x + 3) = x^2 + 11x + b$ is true for all values of $x$, where $a$ and $b$ are constants. What is the value of $b$?',
    answerType: 'numeric', primaryAnswer: '24', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"True for all values of $x$" means the two sides are the same polynomial — match them term by term.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a smaller identity: $(x + a)(x + 1) = x^2 + 5x + b$. Expanding gives $x^2 + (a+1)x + a$, so $a = 4$ and $b = 4$. Match the like terms one at a time.' },
      { level: 'guide', text: 'Expanding the left gives $x^2 + (a + 3)x + 3a$. So $a + 3 = 11$.' },
      { level: 'reveal', text: '$a = 8$, and then $b = 3a = 24$.' },
    ],
    learningObjective: 'Use coefficient matching to find unknown constants in an identity.',
    topic: 'Polynomial identities',
    explanation: [
      'Expand the left side: $(x + a)(x + 3) = x^2 + 3x + ax + 3a = x^2 + (a + 3)x + 3a$.',
      'Since the equation holds for every $x$, matching coefficients gives $a + 3 = 11$ and $b = 3a$.',
      'From the first, $a = 8$. Then $b = 3(8) = 24$. Check: $(x + 8)(x + 3) = x^2 + 11x + 24$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Substitute a convenient value', steps: ['Since the identity holds for every $x$, pick one that simplifies things — say $x = 0$.', 'The left becomes $a \\cdot 3 = 3a$ and the right becomes $b$, so $b = 3a$ immediately.', 'Then use $x = 1$: $(1 + a)(4) = 1 + 11 + b$, so $4 + 4a = 12 + 3a$ and $a = 8$, giving $b = 24$.'] },
    ],
    tags: ['polynomial-identity', 'coefficient-matching'], estimatedSeconds: 90,
  },

  // ═══════════════ UNIT 7 — Quadratic Equations and the Discriminant ═══════════════
  {
    domain: 'SAT', num: 61, unit: 7, order: 1, slug: 'sat-factor-quadratic-basic',
    standard: 'SAT.ADV.2', difficulty: 1,
    prompt: 'What is the greater solution to $x^2 - 7x + 12 = 0$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find two numbers that multiply to $12$ and add to $-7$.' },
      { level: 'guide', text: 'Those numbers are $-3$ and $-4$, so the factored form is $(x - 3)(x - 4) = 0$.' },
      { level: 'reveal', text: 'The solutions are $3$ and $4$; the greater one is $4$.' },
    ],
    learningObjective: 'Solve a monic quadratic by factoring.',
    topic: 'Factoring quadratics',
    explanation: [
      'Look for two numbers whose product is $+12$ and whose sum is $-7$: those are $-3$ and $-4$.',
      'So $x^2 - 7x + 12 = (x - 3)(x - 4) = 0$.',
      'A product is zero only when a factor is zero, so $x = 3$ or $x = 4$. The greater is $4$.',
    ],
    alternativeExplanations: [
      { title: 'Sum and product without factoring', steps: ['For $x^2 + bx + c = 0$, the solutions sum to $-b$ and multiply to $c$.', 'Here they sum to $7$ and multiply to $12$ — that pair is $3$ and $4$ by inspection.', 'This shortcut is fast on monic quadratics and doubles as a check on your factoring.'] },
    ],
    tags: ['quadratic', 'factoring'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 62, unit: 7, order: 2, slug: 'sat-factor-gcf-quadratic',
    standard: 'SAT.ADV.2', difficulty: 1,
    prompt: 'What is the nonzero solution to $x^2 - 5x = 0$?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Both terms share a common factor of $x$.' },
      { level: 'guide', text: 'Factor it out: $x(x - 5) = 0$.' },
      { level: 'reveal', text: 'So $x = 0$ or $x = 5$; the nonzero solution is $5$.' },
    ],
    learningObjective: 'Solve a quadratic with no constant term by factoring out the variable.',
    topic: 'Factoring quadratics',
    explanation: [
      'Factor out the common $x$: $x(x - 5) = 0$.',
      'Setting each factor to zero: $x = 0$ or $x - 5 = 0$, so $x = 5$.',
      'The question asks for the nonzero one: $5$.',
    ],
    alternativeExplanations: [
      { title: 'Never divide both sides by x', steps: ['Dividing $x^2 = 5x$ by $x$ gives $x = 5$ — but it silently destroys the solution $x = 0$.', 'Dividing by a variable is only safe when you know it is not zero, and here it might be.', 'Move everything to one side and factor instead; you keep every solution that way.'] },
    ],
    tags: ['quadratic', 'factoring', 'gcf'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 63, unit: 7, order: 3, slug: 'sat-factor-leading-coefficient',
    standard: 'SAT.ADV.2', difficulty: 2,
    prompt: 'What is the positive solution to $2x^2 + 5x - 3 = 0$?',
    answerType: 'numeric', primaryAnswer: '0.5', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.001,
    alternativeAnswers: ['1/2', '.5'],
    hints: [
      { level: 'nudge', text: 'With a leading coefficient of $2$, look for factors of the form $(2x + \\square)(x + \\square)$.' },
      { level: 'guide', text: 'Try $(2x - 1)(x + 3)$ and expand to check the middle term.' },
      { level: 'reveal', text: '$(2x - 1)(x + 3) = 0$ gives $x = \\tfrac{1}{2}$ or $x = -3$; the positive one is $\\tfrac{1}{2}$.' },
    ],
    learningObjective: 'Solve a quadratic with a leading coefficient other than 1.',
    topic: 'Factoring quadratics',
    explanation: [
      'Factor: $2x^2 + 5x - 3 = (2x - 1)(x + 3)$. Verify the middle term: $6x - x = 5x$ ✓',
      'Set each factor to zero: $2x - 1 = 0$ gives $x = \\tfrac{1}{2}$, and $x + 3 = 0$ gives $x = -3$.',
      'The positive solution is $\\tfrac{1}{2}$, or $0.5$.',
    ],
    alternativeExplanations: [
      { title: 'Use the quadratic formula, or Desmos', steps: ['With $a = 2$, $b = 5$, $c = -3$: $x = \\dfrac{-5 \\pm \\sqrt{25 + 24}}{4} = \\dfrac{-5 \\pm 7}{4}$.', 'That gives $\\tfrac{2}{4} = \\tfrac{1}{2}$ and $\\tfrac{-12}{4} = -3$ — the same answers.', 'Faster still on test day: graph $y = 2x^2 + 5x - 3$ in Desmos and click the $x$-intercepts.'] },
    ],
    tags: ['quadratic', 'factoring', 'quadratic-formula'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 64, unit: 7, order: 4, slug: 'sat-discriminant-none',
    standard: 'SAT.ADV.2', difficulty: 2,
    prompt: 'How many real solutions does the equation $x^2 + 4x + 5 = 0$ have?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Zero', correct: true },
      { id: 'B', label: 'Exactly one', correct: false },
      { id: 'C', label: 'Exactly two', correct: false },
      { id: 'D', label: 'Infinitely many', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The discriminant $b^2 - 4ac$ counts real solutions.' },
      { level: 'guide', text: 'Compute $4^2 - 4(1)(5)$.' },
      { level: 'reveal', text: '$16 - 20 = -4$, which is negative — so there are no real solutions.' },
    ],
    learningObjective: 'Use the discriminant to count real solutions.',
    topic: 'The discriminant',
    explanation: [
      'The discriminant is $b^2 - 4ac = 4^2 - 4(1)(5) = 16 - 20 = -4$.',
      'A negative discriminant means the square root in the quadratic formula is imaginary, so there are no real solutions.',
      'Graphically, the parabola $y = x^2 + 4x + 5$ sits entirely above the $x$-axis and never crosses it.',
    ],
    alternativeExplanations: [
      { title: 'Complete the square to see it', steps: ['$x^2 + 4x + 5 = (x^2 + 4x + 4) + 1 = (x + 2)^2 + 1$.', 'A squared quantity is never negative, so $(x + 2)^2 + 1$ is always at least $1$.', 'It can never equal zero — which is exactly what "no real solutions" means, made visible.'] },
    ],
    tags: ['discriminant', 'no-real-solutions'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 65, unit: 7, order: 5, slug: 'sat-discriminant-one-solution',
    standard: 'SAT.ADV.2', difficulty: 2,
    prompt: 'In the equation $x^2 + 6x + c = 0$, $c$ is a constant. If the equation has exactly one real solution, what is the value of $c$?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Exactly one real solution means the discriminant is zero.' },
      { level: 'guide', text: 'Set $6^2 - 4(1)(c) = 0$.' },
      { level: 'reveal', text: '$36 = 4c$, so $c = 9$.' },
    ],
    learningObjective: 'Solve for a parameter using the discriminant-equals-zero condition.',
    topic: 'The discriminant',
    explanation: [
      'Exactly one real solution occurs when $b^2 - 4ac = 0$.',
      'Here $36 - 4c = 0$, so $c = 9$.',
      'Check: $x^2 + 6x + 9 = (x + 3)^2 = 0$ has the single solution $x = -3$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Recognize the perfect square', steps: ['One solution means the quadratic is a perfect square trinomial.', 'For $x^2 + 6x + c$ to be $(x + k)^2 = x^2 + 2kx + k^2$, we need $2k = 6$, so $k = 3$.', 'Then $c = k^2 = 9$ — the "halve $b$ and square it" rule, which is also the heart of completing the square.'] },
    ],
    tags: ['discriminant', 'perfect-square', 'parameter'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 66, unit: 7, order: 6, slug: 'sat-sum-of-solutions',
    standard: 'SAT.ADV.2', difficulty: 2,
    prompt: 'What is the sum of the solutions to $x^2 - 8x + 7 = 0$?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You can factor — or use the fact that the solutions of $ax^2 + bx + c = 0$ sum to $-b/a$.' },
      { level: 'guide', text: 'Here $a = 1$ and $b = -8$.' },
      { level: 'reveal', text: 'The sum is $-(-8)/1 = 8$.' },
    ],
    learningObjective: 'Use the sum-of-roots relationship for a quadratic.',
    topic: 'Roots of quadratics',
    explanation: [
      'For $ax^2 + bx + c = 0$, the two solutions sum to $-\\dfrac{b}{a}$ and multiply to $\\dfrac{c}{a}$.',
      'Here $-\\dfrac{-8}{1} = 8$.',
      'Confirm by factoring: $(x - 1)(x - 7) = 0$ gives $1$ and $7$, which sum to $8$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Why the shortcut is worth knowing', steps: ['Factoring works here, but the sum-of-roots rule works even when the quadratic does not factor nicely.', 'For $x^2 - 8x + 5 = 0$ the roots are irrational, yet they still sum to exactly $8$.', 'Any question asking for a sum or product of solutions can be answered without finding either one.'] },
    ],
    tags: ['quadratic', 'sum-of-roots'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 67, unit: 7, order: 7, slug: 'sat-quadratic-common-factor',
    standard: 'SAT.ADV.2', difficulty: 3,
    prompt: 'What is the greatest solution to $2x^2 - 8x = 0$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Factor out the greatest common factor first.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a smaller one: $x^2 - 3x = 0$ factors to $x(x - 3) = 0$, so $x = 0$ or $x = 3$. Pull out the common factor and read both roots — never divide the $x$ away.' },
      { level: 'guide', text: '$2x(x - 4) = 0$.' },
      { level: 'reveal', text: 'So $x = 0$ or $x = 4$; the greatest is $4$.' },
    ],
    learningObjective: 'Solve a quadratic by factoring out a common monomial.',
    topic: 'Factoring quadratics',
    explanation: [
      'Both terms share $2x$: $2x^2 - 8x = 2x(x - 4)$.',
      'Set the product to zero: $2x = 0$ gives $x = 0$, and $x - 4 = 0$ gives $x = 4$.',
      'The greatest solution is $4$.',
    ],
    alternativeExplanations: [
      { title: 'Pull out the constant first if it helps', steps: ['You could also factor as $2(x^2 - 4x) = 2 \\cdot x(x - 4)$.', 'The constant $2$ can never be zero, so it contributes no solution — only the variable factors matter.', 'Recognizing that a numerical factor is irrelevant to the roots saves you from chasing it.'] },
    ],
    tags: ['quadratic', 'gcf', 'factoring'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 68, unit: 7, order: 8, slug: 'sat-square-root-method',
    standard: 'SAT.ADV.2', difficulty: 3,
    prompt: 'What is the greater solution to $(x - 3)^2 = 16$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Take the square root of both sides — and remember that it produces two cases.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try easier numbers: $(x - 1)^2 = 9$ gives $x - 1 = \\pm 3$, so $x = 4$ or $x = -2$. The $\\pm$ is not optional — a square has two square roots.' },
      { level: 'guide', text: '$x - 3 = 4$ or $x - 3 = -4$.' },
      { level: 'reveal', text: '$x = 7$ or $x = -1$; the greater is $7$.' },
    ],
    learningObjective: 'Solve a quadratic in squared form using the square-root method.',
    topic: 'Square-root method',
    explanation: [
      'Taking the square root of both sides gives $x - 3 = \\pm 4$.',
      'The two cases: $x - 3 = 4$ gives $x = 7$; $x - 3 = -4$ gives $x = -1$.',
      'The greater solution is $7$. Check: $(7 - 3)^2 = 16$ ✓ and $(-1 - 3)^2 = 16$ ✓',
    ],
    alternativeExplanations: [
      { title: 'The forgotten negative root', steps: ['Writing only $x - 3 = 4$ loses half the answer, and the missing root is always among the choices.', 'Every time you take a square root to undo a square, write the $\\pm$ before anything else.', 'Expanding to $x^2 - 6x - 7 = 0$ and factoring to $(x - 7)(x + 1)$ gives the same pair — but takes longer.'] },
    ],
    tags: ['quadratic', 'square-root-method', 'plus-minus'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 69, unit: 7, order: 9, slug: 'sat-product-of-solutions',
    standard: 'SAT.ADV.2', difficulty: 3,
    prompt: 'What is the product of the solutions to $x^2 - 4x - 12 = 0$?',
    answerType: 'numeric', primaryAnswer: '-12', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The solutions of $ax^2 + bx + c = 0$ multiply to $c/a$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a factorable one: $x^2 - 5x + 6 = 0$ has roots $2$ and $3$, whose product is $6$ — exactly the constant term. That is the $c/a$ rule in miniature.' },
      { level: 'guide', text: 'Here $a = 1$ and $c = -12$.' },
      { level: 'reveal', text: 'The product is $-12$.' },
    ],
    learningObjective: 'Use the product-of-roots relationship for a quadratic.',
    topic: 'Roots of quadratics',
    explanation: [
      'For $ax^2 + bx + c = 0$, the product of the solutions is $\\dfrac{c}{a} = \\dfrac{-12}{1} = -12$.',
      'Confirm by factoring: $(x - 6)(x + 2) = 0$ gives $6$ and $-2$.',
      '$6 \\times (-2) = -12$ ✓',
    ],
    alternativeExplanations: [
      { title: 'A negative product is information', steps: ['If the product of the roots is negative, the two roots must have opposite signs.', 'If the product is positive, they share a sign — and then the sum tells you which.', 'Reading the signs off $b$ and $c$ before factoring often tells you what pair to look for.'] },
    ],
    tags: ['quadratic', 'product-of-roots'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 70, unit: 7, order: 10, slug: 'sat-discriminant-find-k',
    standard: 'SAT.ADV.2', difficulty: 3,
    prompt: 'In the equation $kx^2 + 12x + 9 = 0$, $k$ is a nonzero constant. If the equation has exactly one real solution, what is the value of $k$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Exactly one real solution means the discriminant equals zero.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try it with a known perfect square: $x^2 + 4x + 4$ has discriminant $16 - 16 = 0$ and the single root $x = -2$. Setting $b^2 - 4ac = 0$ is what forces exactly one solution.' },
      { level: 'guide', text: 'Set $12^2 - 4(k)(9) = 0$.' },
      { level: 'reveal', text: '$144 = 36k$, so $k = 4$.' },
    ],
    learningObjective: 'Solve for a leading coefficient using the discriminant condition.',
    topic: 'The discriminant',
    explanation: [
      'The discriminant is $b^2 - 4ac = 144 - 36k$, and one real solution requires it to be zero.',
      '$144 - 36k = 0$, so $k = 4$.',
      'Check: $4x^2 + 12x + 9 = (2x + 3)^2$, which has the single solution $x = -\\tfrac{3}{2}$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Let a Desmos slider find it', steps: ['Type $y = kx^2 + 12x + 9$ and add a slider for $k$.', 'Drag $k$ until the parabola just touches the $x$-axis at one point rather than crossing it twice.', 'The slider lands on $k = 4$. This is a genuinely fast route when the algebra is uncertain, and it makes the geometry of "one solution" visible.'] },
    ],
    tags: ['discriminant', 'parameter', 'desmos'], estimatedSeconds: 85,
  },

  // ═══════════════ UNIT 8 — Quadratic Graphs: Forms and Features ═══════════════
  {
    domain: 'SAT', num: 71, unit: 8, order: 1, slug: 'sat-vertex-from-vertex-form',
    standard: 'SAT.ADV.3', difficulty: 1,
    prompt: 'What is the vertex of the graph of $y = (x - 2)^2 + 5$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$(-2, 5)$', correct: false },
      { id: 'B', label: '$(2, 5)$', correct: true },
      { id: 'C', label: '$(2, -5)$', correct: false },
      { id: 'D', label: '$(-2, -5)$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Vertex form is $y = a(x - h)^2 + k$ with vertex $(h, k)$.' },
      { level: 'guide', text: 'Match $(x - 2)$ against $(x - h)$: what is $h$?' },
      { level: 'reveal', text: '$h = 2$ and $k = 5$, so the vertex is $(2, 5)$.' },
    ],
    learningObjective: 'Read the vertex directly from vertex form.',
    topic: 'Vertex form',
    explanation: [
      'In $y = a(x - h)^2 + k$, the vertex is $(h, k)$.',
      'Here the expression is $(x - 2)^2$, so $h = 2$ — the sign inside the parentheses is opposite the coordinate.',
      'And $k = 5$ is added outside, so the vertex is $(2, 5)$.',
    ],
    alternativeExplanations: [
      { title: 'Why the sign flips', steps: ['The vertex is where the squared term is zero, so solve $x - 2 = 0$.', 'That gives $x = 2$ — the sign flips because you are *solving*, not reading.', 'For $(x + 3)^2$ the same logic gives $x = -3$. Solving the inside for zero never lets you down.'] },
    ],
    tags: ['vertex-form', 'parabola'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 72, unit: 8, order: 2, slug: 'sat-parabola-y-intercept',
    standard: 'SAT.ADV.3', difficulty: 1,
    prompt: 'What is the $y$-intercept of the graph of $y = x^2 - 6x + 8$?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $y$-intercept is the value when $x = 0$.' },
      { level: 'guide', text: 'Substituting $x = 0$ kills both the $x^2$ and the $x$ term.' },
      { level: 'reveal', text: 'Only the constant survives: $y = 8$.' },
    ],
    learningObjective: 'Identify the y-intercept of a quadratic in standard form.',
    topic: 'Standard form',
    explanation: [
      'Substitute $x = 0$: $y = 0 - 0 + 8 = 8$.',
      'In standard form $y = ax^2 + bx + c$, the constant $c$ is always the $y$-intercept.',
      'This is the one feature standard form displays for free — the zeros and vertex both require work.',
    ],
    alternativeExplanations: [
      { title: 'What each form gives you', steps: ['Standard form $ax^2 + bx + c$ displays the $y$-intercept, $c$.', 'Factored form $a(x - p)(x - q)$ displays the zeros, $p$ and $q$.', 'Vertex form $a(x - h)^2 + k$ displays the vertex, $(h, k)$. Questions asking which form "displays" a feature are testing exactly this table.'] },
    ],
    tags: ['standard-form', 'y-intercept', 'parabola'], estimatedSeconds: 35,
  },
  {
    domain: 'SAT', num: 73, unit: 8, order: 3, slug: 'sat-axis-of-symmetry',
    standard: 'SAT.ADV.3', difficulty: 2,
    prompt: 'The function $f$ is defined by $f(x) = (x + 1)(x - 5)$. What is the $x$-coordinate of the vertex of the graph of $f$?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Factored form hands you the zeros. The vertex sits exactly between them.' },
      { level: 'guide', text: 'The zeros are $-1$ and $5$.' },
      { level: 'reveal', text: 'Their average is $\\dfrac{-1 + 5}{2} = 2$.' },
    ],
    learningObjective: 'Locate the axis of symmetry as the midpoint of the zeros.',
    topic: 'Factored form',
    explanation: [
      'Setting each factor to zero gives the $x$-intercepts $x = -1$ and $x = 5$.',
      'A parabola is symmetric, so its vertex lies halfway between the zeros.',
      'The midpoint is $\\dfrac{-1 + 5}{2} = 2$.',
    ],
    alternativeExplanations: [
      { title: 'Or expand and use −b/2a', steps: ['$(x + 1)(x - 5) = x^2 - 4x - 5$, so $a = 1$ and $b = -4$.', '$x = -\\dfrac{b}{2a} = -\\dfrac{-4}{2} = 2$ — the same answer.', 'Averaging the zeros is faster when the quadratic is already factored; $-b/2a$ is the general tool.'] },
    ],
    tags: ['factored-form', 'axis-of-symmetry', 'vertex'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 74, unit: 8, order: 4, slug: 'sat-max-value-vertex-form',
    standard: 'SAT.ADV.3', difficulty: 2,
    prompt: 'What is the maximum value of the function $f(x) = -2(x - 3)^2 + 7$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The leading coefficient is negative, so the parabola opens downward and has a maximum.' },
      { level: 'guide', text: 'The maximum occurs at the vertex. What is the $y$-coordinate of the vertex?' },
      { level: 'reveal', text: 'The vertex is $(3, 7)$, so the maximum value is $7$.' },
    ],
    learningObjective: 'Identify the maximum of a downward parabola from vertex form.',
    topic: 'Maximum and minimum values',
    explanation: [
      'The squared term $(x - 3)^2$ is never negative, and it is multiplied by $-2$, so $-2(x - 3)^2$ is never positive.',
      'The largest that term can be is $0$, which happens at $x = 3$.',
      'So the greatest value of $f$ is $0 + 7 = 7$.',
    ],
    alternativeExplanations: [
      { title: 'The value versus where it happens', steps: ['The maximum *value* is $7$, the $y$-coordinate. It occurs *at* $x = 3$.', 'Both numbers appear in the vertex, and both will appear among the answer choices.', 'Read whether the question asks for the maximum value or for the input that produces it — they are different questions with different answers.'] },
    ],
    tags: ['vertex-form', 'maximum', 'parabola'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 75, unit: 8, order: 5, slug: 'sat-which-form-displays',
    standard: 'SAT.ADV.3', difficulty: 2,
    prompt: 'Which form of a quadratic function displays the coordinates of its vertex as constants in the expression?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$f(x) = ax^2 + bx + c$', correct: false },
      { id: 'B', label: '$f(x) = a(x - p)(x - q)$', correct: false },
      { id: 'C', label: '$f(x) = a(x - h)^2 + k$', correct: true },
      { id: 'D', label: '$f(x) = ax^2 + c$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Which form is actually called "vertex form"?' },
      { level: 'guide', text: 'Look for the form built around a single squared binomial plus a constant.' },
      { level: 'reveal', text: '$a(x - h)^2 + k$ shows the vertex $(h, k)$ directly.' },
    ],
    learningObjective: 'Match each quadratic form to the feature it reveals.',
    topic: 'Forms of a quadratic',
    explanation: [
      'Vertex form $a(x - h)^2 + k$ has the vertex coordinates $h$ and $k$ appearing literally in the expression.',
      'Standard form displays the $y$-intercept $c$; factored form displays the zeros $p$ and $q$.',
      'Choice D is a special case of standard form whose vertex happens to be on the $y$-axis, but it cannot display a general vertex.',
    ],
    alternativeExplanations: [
      { title: 'What "displays" means on the SAT', steps: ['"Displays as constants" means the numbers are visible without any computation.', 'Standard form contains the vertex information, but you must compute $-b/2a$ to extract it — that is not displaying.', 'The distinction between containing and displaying is precisely what this question type tests.'] },
    ],
    tags: ['forms', 'vertex-form', 'conceptual'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 76, unit: 8, order: 6, slug: 'sat-minimum-standard-form',
    standard: 'SAT.ADV.3', difficulty: 2,
    prompt: 'What is the minimum value of the function $f(x) = x^2 - 8x + 12$?',
    answerType: 'numeric', primaryAnswer: '-4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find where the vertex is first, using $x = -\\dfrac{b}{2a}$.' },
      { level: 'guide', text: '$x = -\\dfrac{-8}{2(1)} = 4$. Now evaluate $f(4)$.' },
      { level: 'reveal', text: '$f(4) = 16 - 32 + 12 = -4$.' },
    ],
    learningObjective: 'Find the minimum of a quadratic given in standard form.',
    topic: 'Maximum and minimum values',
    explanation: [
      'The parabola opens upward ($a = 1 > 0$), so it has a minimum at its vertex.',
      'The vertex is at $x = -\\dfrac{b}{2a} = \\dfrac{8}{2} = 4$.',
      'The minimum value is $f(4) = 4^2 - 8(4) + 12 = 16 - 32 + 12 = -4$.',
    ],
    alternativeExplanations: [
      { title: 'Complete the square instead', steps: ['$x^2 - 8x + 12 = (x^2 - 8x + 16) - 16 + 12 = (x - 4)^2 - 4$.', 'Now it is in vertex form and the vertex $(4, -4)$ is visible without computing anything.', 'Completing the square costs a few more seconds but produces the whole vertex, not just half of it.'] },
    ],
    tags: ['standard-form', 'minimum', 'vertex'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 77, unit: 8, order: 7, slug: 'sat-complete-the-square',
    standard: 'SAT.ADV.3', difficulty: 3,
    prompt: 'Which expression is equivalent to $x^2 + 6x + 1$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$(x + 3)^2 - 8$', correct: true },
      { id: 'B', label: '$(x + 3)^2 + 1$', correct: false },
      { id: 'C', label: '$(x + 6)^2 - 35$', correct: false },
      { id: 'D', label: '$(x - 3)^2 - 8$', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Complete the square: halve the coefficient of $x$, then square it.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a smaller one: $x^2 + 2x + 5 = (x^2 + 2x + 1) - 1 + 5 = (x + 1)^2 + 4$. Halve the $x$-coefficient, square it, then add and subtract that number.' },
      { level: 'guide', text: 'Half of $6$ is $3$, and $3^2 = 9$. Add and subtract $9$.' },
      { level: 'reveal', text: '$(x^2 + 6x + 9) - 9 + 1 = (x + 3)^2 - 8$.' },
    ],
    learningObjective: 'Rewrite a quadratic in vertex form by completing the square.',
    topic: 'Completing the square',
    explanation: [
      'Take half of the $x$-coefficient: $6 \\div 2 = 3$. Square it: $9$.',
      'Add and subtract $9$ so the value is unchanged: $x^2 + 6x + 9 - 9 + 1$.',
      'The first three terms are $(x + 3)^2$, leaving $(x + 3)^2 - 8$. The vertex is $(-3, -8)$.',
    ],
    alternativeExplanations: [
      { title: 'Verify by testing x = 0', steps: ['The original at $x = 0$ gives $1$.', 'Choice A: $(0 + 3)^2 - 8 = 9 - 8 = 1$ ✓. Choice B gives $10$, C gives $1$ ✓, D gives $1$ ✓.', 'Test a second value, $x = 1$: original gives $8$; A gives $16 - 8 = 8$ ✓, C gives $49 - 35 = 14$ ✗, D gives $4 - 8 = -4$ ✗. Two test values is almost always enough.'] },
    ],
    tags: ['completing-the-square', 'vertex-form'], estimatedSeconds: 85,
  },
  {
    domain: 'SAT', num: 78, unit: 8, order: 8, slug: 'sat-projectile-max-height',
    standard: 'SAT.ADV.3', difficulty: 3,
    prompt: 'A ball is thrown upward, and its height in feet after $t$ seconds is $h(t) = -16t^2 + 64t$. What is the maximum height, in feet, that the ball reaches?',
    answerType: 'numeric', primaryAnswer: '64', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Maximum height means the vertex of this downward parabola.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try friendlier numbers: $h(t) = -t^2 + 4t$ peaks at $t = -\\tfrac{4}{2(-1)} = 2$, where $h = 4$. Find the vertex\'s $t$ first, then substitute to get the height.' },
      { level: 'guide', text: 'The vertex is at $t = -\\dfrac{64}{2(-16)} = 2$ seconds.' },
      { level: 'reveal', text: '$h(2) = -16(4) + 64(2) = -64 + 128 = 64$ feet.' },
    ],
    learningObjective: 'Apply the vertex formula to a projectile-motion model.',
    topic: 'Quadratic models in context',
    explanation: [
      'The coefficient of $t^2$ is negative, so the parabola opens downward and its vertex is the maximum.',
      'The vertex occurs at $t = -\\dfrac{b}{2a} = -\\dfrac{64}{-32} = 2$ seconds.',
      'The maximum height is $h(2) = -16(2)^2 + 64(2) = -64 + 128 = 64$ feet.',
    ],
    alternativeExplanations: [
      { title: 'Use symmetry between the zeros', steps: ['Factor: $h(t) = -16t(t - 4)$, so the ball is at height zero at $t = 0$ and $t = 4$.', 'By symmetry the peak is halfway between, at $t = 2$.', 'Then $h(2) = 64$ feet. Reading the launch and landing times off the factored form is often the fastest route on projectile questions.'] },
    ],
    tags: ['quadratic-model', 'projectile', 'maximum'], estimatedSeconds: 90,
  },
  {
    domain: 'SAT', num: 79, unit: 8, order: 9, slug: 'sat-parabola-through-point',
    standard: 'SAT.ADV.3', difficulty: 3,
    prompt: 'A parabola has $x$-intercepts at $-3$ and $5$ and passes through the point $(0, -15)$. Its equation can be written as $y = a(x + 3)(x - 5)$. What is the value of $a$?',
    answerType: 'numeric', primaryAnswer: '1', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute the known point into the equation and solve for $a$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try easier zeros: a parabola with zeros $0$ and $2$ through $(1, -2)$ is $y = a(x)(x-2)$, so $-2 = a(1)(-1)$ and $a = 2$. Substitute the extra point and solve for $a$.' },
      { level: 'guide', text: 'At $x = 0$: $-15 = a(3)(-5)$.' },
      { level: 'reveal', text: '$-15 = -15a$, so $a = 1$.' },
    ],
    learningObjective: 'Determine the leading coefficient of a parabola from a point and its zeros.',
    topic: 'Factored form',
    explanation: [
      'The zeros give the factors, but they do not determine the vertical stretch $a$ — a third point does.',
      'Substitute $(0, -15)$: $-15 = a(0 + 3)(0 - 5) = a(3)(-5) = -15a$.',
      'Divide: $a = 1$. The parabola is $y = (x + 3)(x - 5) = x^2 - 2x - 15$.',
    ],
    alternativeExplanations: [
      { title: 'Why a third point is needed', steps: ['Infinitely many parabolas share the same two $x$-intercepts — they differ only in how steeply they rise.', 'The value of $a$ is exactly that steepness, and one extra point pins it down.', 'This is why the SAT always supplies a third point when it asks you to build a parabola from its zeros.'] },
    ],
    tags: ['factored-form', 'parameter', 'parabola'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 80, unit: 8, order: 10, slug: 'sat-tangent-to-x-axis',
    standard: 'SAT.ADV.3', difficulty: 3,
    prompt: 'The graph of $f(x) = x^2 + bx + 9$ touches the $x$-axis at exactly one point, and $b$ is positive. What is the value of $b$?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Touching the $x$-axis at exactly one point means exactly one real zero.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a known case: $x^2 + 4x + 4 = (x + 2)^2$ touches the axis once, and here $b = 4$ with $c = 4$ — note $b = 2\\sqrt{c}$. Tangency means the trinomial is a perfect square.' },
      { level: 'guide', text: 'Set the discriminant to zero: $b^2 - 4(1)(9) = 0$.' },
      { level: 'reveal', text: '$b^2 = 36$, so $b = \\pm 6$; since $b$ is positive, $b = 6$.' },
    ],
    learningObjective: 'Connect tangency to the x-axis with a zero discriminant.',
    topic: 'The discriminant',
    explanation: [
      'A parabola touching the $x$-axis at exactly one point has a repeated root, so its discriminant is zero.',
      '$b^2 - 4(1)(9) = 0$ gives $b^2 = 36$ and $b = \\pm 6$.',
      'The problem states $b$ is positive, so $b = 6$. Check: $x^2 + 6x + 9 = (x + 3)^2$, tangent at $x = -3$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Read it as a perfect square', steps: ['One repeated root means the quadratic is a perfect square: $(x + k)^2 = x^2 + 2kx + k^2$.', 'Matching the constant: $k^2 = 9$, so $k = \\pm 3$.', 'Then $b = 2k = \\pm 6$, and the positivity condition selects $6$. The condition on $b$ exists precisely because both signs are otherwise valid.'] },
    ],
    tags: ['discriminant', 'tangent', 'perfect-square'], estimatedSeconds: 85,
  },

  // ═══════ UNIT 9 — Nonlinear Systems, Polynomials, and Rational Equations ═══════
  {
    domain: 'SAT', num: 81, unit: 9, order: 1, slug: 'sat-factor-theorem-basic',
    standard: 'SAT.ADV.4', difficulty: 1,
    prompt: 'The polynomial $p$ is defined by $p(x) = x^3 - 4x$. Which of the following is a factor of $p(x)$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$x - 4$', correct: false },
      { id: 'B', label: '$x - 2$', correct: true },
      { id: 'C', label: '$x + 4$', correct: false },
      { id: 'D', label: '$x^2 + 4$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Factor out the common $x$ first.' },
      { level: 'guide', text: '$x^3 - 4x = x(x^2 - 4)$, and $x^2 - 4$ is a difference of squares.' },
      { level: 'reveal', text: '$p(x) = x(x + 2)(x - 2)$, so $x - 2$ is a factor.' },
    ],
    learningObjective: 'Factor a cubic by extracting a common term and a difference of squares.',
    topic: 'Polynomial factoring',
    explanation: [
      'Factor out the common $x$: $x^3 - 4x = x(x^2 - 4)$.',
      'The remaining factor is a difference of squares: $x^2 - 4 = (x + 2)(x - 2)$.',
      'So $p(x) = x(x + 2)(x - 2)$, and $x - 2$ appears among the factors.',
    ],
    alternativeExplanations: [
      { title: 'Test each candidate with the Factor Theorem', steps: ['$(x - a)$ is a factor exactly when $p(a) = 0$.', 'Test $a = 2$: $p(2) = 8 - 8 = 0$ ✓ — so $x - 2$ is a factor.', 'Test $a = 4$: $p(4) = 64 - 16 = 48 \\neq 0$ ✗. Substituting is often faster than factoring when the choices are handed to you.'] },
    ],
    tags: ['polynomial', 'factoring', 'factor-theorem'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 82, unit: 9, order: 2, slug: 'sat-zero-means-factor',
    standard: 'SAT.ADV.4', difficulty: 1,
    prompt: 'For a polynomial $p$, the value of $p(3)$ is $0$. Which of the following must be true?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$x + 3$ is a factor of $p(x)$', correct: false },
      { id: 'B', label: '$x - 3$ is a factor of $p(x)$', correct: true },
      { id: 'C', label: '$p(0) = 3$', correct: false },
      { id: 'D', label: '$p(x)$ has degree $3$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'This is the Factor Theorem: a zero of the polynomial corresponds to a factor.' },
      { level: 'guide', text: 'If $p(a) = 0$, then $(x - a)$ divides $p(x)$.' },
      { level: 'reveal', text: 'With $a = 3$, the factor is $x - 3$.' },
    ],
    learningObjective: 'State and apply the Factor Theorem.',
    topic: 'The Factor Theorem',
    explanation: [
      'The Factor Theorem says $p(a) = 0$ if and only if $(x - a)$ is a factor of $p(x)$.',
      'Here $a = 3$, so the factor is $x - 3$ — note the sign is opposite the value.',
      'Choices C and D describe unrelated properties; nothing about $p(3) = 0$ constrains the degree or the value at $0$.',
    ],
    alternativeExplanations: [
      { title: 'Three ways the SAT says the same thing', steps: ['"$p(3) = 0$", "$3$ is a zero of $p$", "the graph of $p$ passes through $(3, 0)$", and "$x - 3$ divides $p(x)$" are four phrasings of one fact.', 'Questions often state it one way and ask for another.', 'Recognizing the equivalence instantly is most of what these questions are testing.'] },
    ],
    tags: ['factor-theorem', 'polynomial', 'conceptual'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 83, unit: 9, order: 3, slug: 'sat-rational-equation-basic',
    standard: 'SAT.ADV.4', difficulty: 2,
    prompt: 'If $\\dfrac{1}{x} + \\dfrac{1}{2} = \\dfrac{3}{4}$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Isolate the term containing $x$ first.' },
      { level: 'guide', text: 'Subtract $\\tfrac{1}{2}$: $\\dfrac{1}{x} = \\dfrac{3}{4} - \\dfrac{2}{4} = \\dfrac{1}{4}$.' },
      { level: 'reveal', text: 'If $\\dfrac{1}{x} = \\dfrac{1}{4}$, then $x = 4$.' },
    ],
    learningObjective: 'Solve a simple rational equation by isolating the reciprocal.',
    topic: 'Rational equations',
    explanation: [
      'Subtract $\\tfrac{1}{2}$ from both sides: $\\dfrac{1}{x} = \\dfrac{3}{4} - \\dfrac{1}{2} = \\dfrac{1}{4}$.',
      'Two fractions with numerator $1$ are equal only when their denominators are equal.',
      'So $x = 4$. Check: $\\tfrac{1}{4} + \\tfrac{1}{2} = \\tfrac{3}{4}$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Clear all denominators at once', steps: ['Multiply every term by the common denominator $4x$: $4 + 2x = 3x$.', 'Then $4 = x$.', 'This route generalizes to any rational equation, including ones where the reciprocal cannot be isolated so neatly.'] },
    ],
    tags: ['rational-equation', 'fractions'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 84, unit: 9, order: 4, slug: 'sat-nonlinear-system-parabola-line',
    standard: 'SAT.ADV.4', difficulty: 2,
    prompt: 'The system $y = x^2$ and $y = x + 6$ has two solutions. What is the greater of the two $x$-coordinates?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set the two expressions for $y$ equal to each other.' },
      { level: 'guide', text: '$x^2 = x + 6$, so $x^2 - x - 6 = 0$.' },
      { level: 'reveal', text: '$(x - 3)(x + 2) = 0$, so $x = 3$ or $x = -2$; the greater is $3$.' },
    ],
    learningObjective: 'Solve a nonlinear system by substitution.',
    topic: 'Nonlinear systems',
    explanation: [
      'Both equations give $y$, so set them equal: $x^2 = x + 6$.',
      'Rearrange to a standard quadratic: $x^2 - x - 6 = 0$.',
      'Factor: $(x - 3)(x + 2) = 0$, so $x = 3$ or $x = -2$. The greater is $3$.',
    ],
    alternativeExplanations: [
      { title: 'Graph both and click', steps: ['Enter $y = x^2$ and $y = x + 6$ in Desmos.', 'The curves cross at $(-2, 4)$ and $(3, 9)$, and Desmos labels both intersection points.', 'For any nonlinear system on the digital SAT this is the fastest reliable method, and it also tells you how many solutions exist at a glance.'] },
    ],
    tags: ['nonlinear-system', 'substitution', 'desmos'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 85, unit: 9, order: 5, slug: 'sat-rational-equation-cross',
    standard: 'SAT.ADV.4', difficulty: 2,
    prompt: 'If $\\dfrac{x}{x - 2} = 3$ and $x \\neq 2$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply both sides by the denominator.' },
      { level: 'guide', text: '$x = 3(x - 2)$.' },
      { level: 'reveal', text: '$x = 3x - 6$, so $-2x = -6$ and $x = 3$.' },
    ],
    learningObjective: 'Solve a rational equation by clearing the denominator.',
    topic: 'Rational equations',
    explanation: [
      'Multiply both sides by $(x - 2)$: $x = 3(x - 2)$.',
      'Distribute and collect: $x = 3x - 6$, so $2x = 6$ and $x = 3$.',
      'Check that it does not break the denominator: $x = 3 \\neq 2$ ✓, and $\\dfrac{3}{1} = 3$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Always check the denominator', steps: ['Multiplying by a variable expression can introduce a value that makes the original undefined.', 'Here the excluded value is $x = 2$; our answer of $3$ is safe.', 'Had the algebra produced $x = 2$, the correct response would be "no solution" — and that is a real SAT answer choice.'] },
    ],
    tags: ['rational-equation', 'extraneous'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 86, unit: 9, order: 6, slug: 'sat-polynomial-degree',
    standard: 'SAT.ADV.4', difficulty: 2,
    prompt: 'What is the degree of the polynomial $(x^2 + 1)(x^3 - 2)$ when it is fully expanded?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You do not need to expand — the degrees combine.' },
      { level: 'guide', text: 'The highest-degree term comes from multiplying the two leading terms: $x^2 \\cdot x^3$.' },
      { level: 'reveal', text: '$x^5$, so the degree is $5$.' },
    ],
    learningObjective: 'Determine the degree of a product of polynomials.',
    topic: 'Polynomial degree',
    explanation: [
      'When polynomials are multiplied, their degrees add.',
      'The first factor has degree $2$ and the second has degree $3$, so the product has degree $5$.',
      'Confirming by expansion: $x^5 - 2x^2 + x^3 - 2$, whose highest power is indeed $x^5$.',
    ],
    alternativeExplanations: [
      { title: 'Only the leading terms matter', steps: ['Every other product produces a lower power, so it cannot affect the degree.', 'Multiply just the leading terms — $x^2 \\cdot x^3 = x^5$ — and stop there.', 'The same shortcut answers "what is the leading coefficient" questions: multiply just the leading coefficients.'] },
    ],
    tags: ['polynomial', 'degree'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 87, unit: 9, order: 7, slug: 'sat-radical-extraneous',
    standard: 'SAT.ADV.4', difficulty: 3,
    prompt: 'What is the solution to $\\sqrt{x + 7} = x - 5$?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Square both sides — then check your answers in the original equation.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a small one: $\\sqrt{x} = x - 2$. Squaring gives $x^2 - 5x + 4 = 0$, so $x = 1$ or $x = 4$. But $x = 1$ fails the original ($1 \\neq -1$), leaving $x = 4$. Always check both.' },
      { level: 'guide', text: '$x + 7 = x^2 - 10x + 25$, so $x^2 - 11x + 18 = 0$.' },
      { level: 'reveal', text: '$(x - 9)(x - 2) = 0$ gives $x = 9$ or $x = 2$, but $x = 2$ fails the original. The solution is $9$.' },
    ],
    learningObjective: 'Solve a radical equation and reject extraneous solutions.',
    topic: 'Radical equations',
    explanation: [
      'Square both sides: $x + 7 = (x - 5)^2 = x^2 - 10x + 25$.',
      'Rearrange: $x^2 - 11x + 18 = 0$, which factors as $(x - 9)(x - 2) = 0$, giving $x = 9$ or $x = 2$.',
      'Check both. $x = 9$: $\\sqrt{16} = 4$ and $9 - 5 = 4$ ✓. $x = 2$: $\\sqrt{9} = 3$ but $2 - 5 = -3$ ✗. Only $x = 9$ works.',
    ],
    alternativeExplanations: [
      { title: 'Why squaring invents solutions', steps: ['Squaring erases signs: $3$ and $-3$ both square to $9$.', 'So the squared equation accepts a case the original rejects — here, the one where the right side is negative.', 'A square root is never negative, so any candidate making $x - 5 < 0$ is doomed from the start. Checking is not optional on radical equations.'] },
    ],
    tags: ['radical-equation', 'extraneous-solution'], estimatedSeconds: 95,
  },
  {
    domain: 'SAT', num: 88, unit: 9, order: 8, slug: 'sat-count-intersections',
    standard: 'SAT.ADV.4', difficulty: 3,
    prompt: 'How many solutions does the system $y = x^2 - 4x + 5$ and $y = 2x - 3$ have?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Zero', correct: false },
      { id: 'B', label: 'Exactly one', correct: false },
      { id: 'C', label: 'Exactly two', correct: true },
      { id: 'D', label: 'Infinitely many', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Set the two expressions equal and look at the resulting quadratic.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an obvious pair: $y = x^2$ and $y = 1$ meet where $x^2 - 1 = 0$, whose discriminant is $4 > 0$ — two crossings, at $x = \\pm 1$. The discriminant counts the intersections.' },
      { level: 'guide', text: '$x^2 - 4x + 5 = 2x - 3$ becomes $x^2 - 6x + 8 = 0$.' },
      { level: 'reveal', text: 'Its discriminant is $36 - 32 = 4 > 0$, so there are two solutions.' },
    ],
    learningObjective: 'Count intersections of a parabola and a line using the discriminant.',
    topic: 'Nonlinear systems',
    explanation: [
      'Set the expressions equal: $x^2 - 4x + 5 = 2x - 3$.',
      'Collect everything on one side: $x^2 - 6x + 8 = 0$.',
      'The discriminant is $(-6)^2 - 4(1)(8) = 36 - 32 = 4$, which is positive — two distinct real solutions. (Factoring confirms: $(x - 2)(x - 4) = 0$.)',
    ],
    alternativeExplanations: [
      { title: 'What the discriminant means geometrically', steps: ['Positive discriminant: the line cuts the parabola at two points.', 'Zero: the line is tangent, touching at exactly one point.', 'Negative: the line misses the parabola entirely. Questions asking for the $k$ that makes a line tangent to a curve are discriminant-equals-zero questions.'] },
    ],
    tags: ['nonlinear-system', 'discriminant', 'intersections'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 89, unit: 9, order: 9, slug: 'sat-cubic-other-zeros',
    standard: 'SAT.ADV.4', difficulty: 3,
    prompt: 'The polynomial $p$ is defined by $p(x) = x^3 - 2x^2 - 5x + 6$, and $p(1) = 0$. What is the greatest zero of $p$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Since $p(1) = 0$, the expression $(x - 1)$ divides $p(x)$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a smaller cubic: $x^3 - x = x(x-1)(x+1)$ has zeros $0$, $1$, and $-1$. One known zero lets you divide the cubic down to a quadratic you can factor by sight.' },
      { level: 'guide', text: 'Dividing gives $x^2 - x - 6$.' },
      { level: 'reveal', text: '$x^2 - x - 6 = (x - 3)(x + 2)$, so the zeros are $1$, $3$, and $-2$. The greatest is $3$.' },
    ],
    learningObjective: 'Use a known zero to factor a cubic and find the remaining zeros.',
    topic: 'Polynomial zeros',
    explanation: [
      '$p(1) = 1 - 2 - 5 + 6 = 0$, so by the Factor Theorem $(x - 1)$ is a factor.',
      'Dividing $x^3 - 2x^2 - 5x + 6$ by $(x - 1)$ gives the quotient $x^2 - x - 6$.',
      'That factors as $(x - 3)(x + 2)$, so the full factorization is $(x - 1)(x - 3)(x + 2)$ and the zeros are $1$, $3$, and $-2$. The greatest is $3$.',
    ],
    alternativeExplanations: [
      { title: 'Graph it, or test small integers', steps: ['Graphing $y = x^3 - 2x^2 - 5x + 6$ in Desmos shows three $x$-intercepts at $-2$, $1$, and $3$.', 'By hand, test the divisors of the constant term $6$: $\\pm 1, \\pm 2, \\pm 3, \\pm 6$.', '$p(3) = 27 - 18 - 15 + 6 = 0$ ✓ — the Rational Root Theorem means integer zeros can only be divisors of the constant, which makes the search short.'] },
    ],
    tags: ['polynomial', 'zeros', 'factor-theorem'], estimatedSeconds: 100,
  },
  {
    domain: 'SAT', num: 90, unit: 9, order: 10, slug: 'sat-horizontal-line-tangent',
    standard: 'SAT.ADV.4', difficulty: 3,
    prompt: 'The line $y = k$ intersects the graph of $y = x^2 - 6x + 5$ at exactly one point. What is the value of $k$?',
    answerType: 'numeric', primaryAnswer: '-4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A horizontal line meets a parabola once only when it passes through the vertex.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easy parabola: $y = x^2$ meets $y = k$ once only when $k = 0$, the vertex height. A horizontal line touches a parabola exactly once precisely at the vertex.' },
      { level: 'guide', text: 'The vertex is at $x = -\\dfrac{-6}{2} = 3$.' },
      { level: 'reveal', text: 'The vertex $y$-value is $9 - 18 + 5 = -4$, so $k = -4$.' },
    ],
    learningObjective: 'Connect a single intersection with a horizontal line to the vertex of a parabola.',
    topic: 'Nonlinear systems',
    explanation: [
      'A horizontal line either misses an upward parabola, cuts it twice, or touches it exactly once — and the last case happens only at the vertex.',
      'The vertex is at $x = -\\dfrac{b}{2a} = 3$, where $y = 3^2 - 6(3) + 5 = 9 - 18 + 5 = -4$.',
      'So $k = -4$.',
    ],
    alternativeExplanations: [
      { title: 'Or force the discriminant to zero', steps: ['Set $x^2 - 6x + 5 = k$, so $x^2 - 6x + (5 - k) = 0$.', 'One solution means $36 - 4(5 - k) = 0$, giving $36 - 20 + 4k = 0$ and $k = -4$.', 'Both routes work; recognizing the vertex is faster, but the discriminant route generalizes to non-horizontal lines.'] },
    ],
    tags: ['nonlinear-system', 'vertex', 'tangent'], estimatedSeconds: 90,
  },

  // ═══════════ UNIT 10 — Exponential Functions, Growth, and Decay ═══════════
  {
    domain: 'SAT', num: 91, unit: 10, order: 1, slug: 'sat-exponential-initial-value',
    standard: 'SAT.ADV.5', difficulty: 1,
    prompt: 'The function $f$ is defined by $f(x) = 3(2)^x$. What is the value of $f(0)$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Any nonzero number raised to the power $0$ equals $1$.' },
      { level: 'guide', text: '$f(0) = 3 \\cdot 2^0 = 3 \\cdot 1$.' },
      { level: 'reveal', text: '$f(0) = 3$.' },
    ],
    learningObjective: 'Evaluate an exponential function at zero to find its initial value.',
    topic: 'Exponential functions',
    explanation: [
      '$2^0 = 1$, since anything nonzero to the zero power is $1$.',
      'So $f(0) = 3 \\cdot 1 = 3$.',
      'In the form $f(x) = ab^x$, the coefficient $a$ is always the initial value — the output at $x = 0$.',
    ],
    alternativeExplanations: [
      { title: 'Read a and b as a story', steps: ['In $ab^x$, $a$ is where you start and $b$ is what you multiply by each step.', 'Here you start at $3$ and double each step: $3, 6, 12, 24, \\ldots$', 'Naming the two constants this way answers most exponential questions before any computation.'] },
    ],
    tags: ['exponential', 'initial-value'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 92, unit: 10, order: 2, slug: 'sat-growth-or-decay',
    standard: 'SAT.ADV.5', difficulty: 1,
    prompt: 'The function $y = 500(0.85)^t$ models a quantity over time. Which statement best describes the model?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'The quantity decreases by 15% each period', correct: true },
      { id: 'B', label: 'The quantity decreases by 85% each period', correct: false },
      { id: 'C', label: 'The quantity increases by 85% each period', correct: false },
      { id: 'D', label: 'The quantity decreases by 500 each period', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The base $0.85$ is less than $1$, so this is decay. But by how much?' },
      { level: 'guide', text: 'Keeping $85\\%$ of the amount means losing the other $15\\%$.' },
      { level: 'reveal', text: 'The quantity decreases by $15\\%$ each period.' },
    ],
    learningObjective: 'Interpret the base of an exponential model as a percent rate.',
    topic: 'Growth and decay rates',
    explanation: [
      'A base between $0$ and $1$ means decay; a base greater than $1$ means growth.',
      'The base $0.85$ means each period retains $85\\%$ of the previous amount, so it *loses* $15\\%$.',
      'Choice B is the trap: $0.85$ is what remains, not what is lost.',
    ],
    alternativeExplanations: [
      { title: 'The base-to-rate conversion', steps: ['For growth, base $= 1 + r$: a base of $1.07$ means $+7\\%$.', 'For decay, base $= 1 - r$: a base of $0.85$ means $r = 0.15$, so $-15\\%$.', 'Subtract the base from $1$ for decay, or subtract $1$ from the base for growth. Getting this backwards is the most common exponential error on the test.'] },
    ],
    tags: ['exponential', 'decay', 'percent-rate'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 93, unit: 10, order: 3, slug: 'sat-compound-growth-expression',
    standard: 'SAT.ADV.5', difficulty: 2,
    prompt: 'An investment of $\\$400$ grows by $6\\%$ each year. Which expression gives the value of the investment, in dollars, after $t$ years?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$400 + 0.06t$', correct: false },
      { id: 'B', label: '$400(1.06)^t$', correct: true },
      { id: 'C', label: '$400(0.06)^t$', correct: false },
      { id: 'D', label: '$400(6)^t$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Growing by a *percent* each year is repeated multiplication, not repeated addition.' },
      { level: 'guide', text: 'Each year the value is multiplied by $1 + 0.06 = 1.06$.' },
      { level: 'reveal', text: 'After $t$ years: $400(1.06)^t$.' },
    ],
    learningObjective: 'Build an exponential growth model from a percent rate.',
    topic: 'Exponential models',
    explanation: [
      'A $6\\%$ increase means keeping the original $100\\%$ and adding $6\\%$ more, so multiply by $1.06$.',
      'Repeating that for $t$ years gives $400(1.06)^t$.',
      'Choice A models linear growth of $6$ cents per year. Choice C loses $94\\%$ per year. Choice D multiplies by $6$ each year.',
    ],
    alternativeExplanations: [
      { title: 'Sanity-check with one year', steps: ['After one year, $\\$400$ growing $6\\%$ should be $\\$424$.', 'Test each choice at $t = 1$: A gives $400.06$, B gives $424$ ✓, C gives $24$, D gives $2400$.', 'A single well-chosen test value eliminates three choices instantly, and $t = 1$ is almost always the right one to pick.'] },
    ],
    tags: ['exponential', 'growth', 'modeling'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 94, unit: 10, order: 4, slug: 'sat-doubling-time-model',
    standard: 'SAT.ADV.5', difficulty: 2,
    prompt: 'A population of $2{,}000$ bacteria doubles every $5$ hours. Which function models the population $P$ after $t$ hours?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$P = 2000(2)^{5t}$', correct: false },
      { id: 'B', label: '$P = 2000(2)^{t/5}$', correct: true },
      { id: 'C', label: '$P = 2000(5)^{t/2}$', correct: false },
      { id: 'D', label: '$P = 2000 + 2t$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The base is the growth factor ($2$ for doubling). The exponent must count how many doublings have happened.' },
      { level: 'guide', text: 'After $t$ hours, the number of $5$-hour periods that have elapsed is $t/5$.' },
      { level: 'reveal', text: '$P = 2000(2)^{t/5}$.' },
    ],
    learningObjective: 'Build an exponential model when the period differs from the time unit.',
    topic: 'Exponential models',
    explanation: [
      'Doubling means the base is $2$.',
      'The exponent must count doublings, not hours. In $t$ hours there are $\\dfrac{t}{5}$ five-hour periods.',
      'So $P = 2000(2)^{t/5}$. Check at $t = 5$: $2000 \\cdot 2^1 = 4000$ ✓ — exactly one doubling.',
    ],
    alternativeExplanations: [
      { title: 'Divide by the period, never multiply', steps: ['Choice A gives $2000 \\cdot 2^{25}$ after 5 hours — astronomically wrong.', 'Whenever the growth period is longer than the time unit, the exponent divides.', 'The general form is $a \\cdot b^{t/p}$, where $p$ is how long one full growth period takes. Test at $t = p$ to confirm you get exactly one growth step.'] },
    ],
    tags: ['exponential', 'doubling-time', 'modeling'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 95, unit: 10, order: 5, slug: 'sat-evaluate-exponential',
    standard: 'SAT.ADV.5', difficulty: 2,
    prompt: 'The function $f$ is defined by $f(x) = 5(3)^x$. What is the value of $f(2)$?',
    answerType: 'numeric', primaryAnswer: '45', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Apply the exponent before the multiplication.' },
      { level: 'guide', text: '$3^2 = 9$, so $f(2) = 5 \\cdot 9$.' },
      { level: 'reveal', text: '$f(2) = 45$.' },
    ],
    learningObjective: 'Evaluate an exponential function, respecting order of operations.',
    topic: 'Exponential functions',
    explanation: [
      'The exponent applies only to the base $3$, not to the coefficient $5$.',
      '$3^2 = 9$, then $5 \\times 9 = 45$.',
      'Computing $(5 \\cdot 3)^2 = 225$ would be the order-of-operations error this question checks for.',
    ],
    alternativeExplanations: [
      { title: 'Step it out', steps: ['Start at $f(0) = 5$. Each step in $x$ multiplies by $3$.', '$f(1) = 15$, then $f(2) = 45$.', 'Stepping is slower for large inputs but makes the structure obvious, and it never falls for the order-of-operations trap.'] },
    ],
    tags: ['exponential', 'evaluate', 'order-of-operations'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 96, unit: 10, order: 6, slug: 'sat-exponential-from-table',
    standard: 'SAT.ADV.5', difficulty: 2,
    prompt: 'An exponential function $f$ satisfies $f(1) = 6$, $f(2) = 18$, and $f(3) = 54$. What is the value of $f(0)$?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the constant ratio between consecutive outputs.' },
      { level: 'guide', text: '$18 \\div 6 = 3$ and $54 \\div 18 = 3$, so the function triples each step.' },
      { level: 'reveal', text: 'Going *backwards* one step divides by $3$: $f(0) = 6 \\div 3 = 2$.' },
    ],
    learningObjective: 'Extend an exponential pattern backwards to its initial value.',
    topic: 'Exponential functions',
    explanation: [
      'Consecutive outputs have a constant ratio: $\\dfrac{18}{6} = \\dfrac{54}{18} = 3$. That constant ratio is what makes the function exponential.',
      'Stepping forward multiplies by $3$, so stepping backward divides by $3$.',
      '$f(0) = \\dfrac{6}{3} = 2$. (The function is $f(x) = 2 \\cdot 3^x$.)',
    ],
    alternativeExplanations: [
      { title: 'Linear or exponential? Check differences and ratios', steps: ['Differences here are $12$ and $36$ — not constant, so the function is not linear.', 'Ratios are $3$ and $3$ — constant, so it is exponential.', 'Running both checks takes ten seconds and settles every "which model fits this table" question on the test.'] },
    ],
    tags: ['exponential', 'table', 'ratio'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 97, unit: 10, order: 7, slug: 'sat-depreciation-expression',
    standard: 'SAT.ADV.5', difficulty: 3,
    prompt: 'A car purchased for $\\$24{,}000$ loses $12\\%$ of its value each year. Which expression represents the car\'s value, in dollars, after $t$ years?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$24000(0.12)^t$', correct: false },
      { id: 'B', label: '$24000(1.12)^t$', correct: false },
      { id: 'C', label: '$24000(0.88)^t$', correct: true },
      { id: 'D', label: '$24000 - 0.12t$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Losing $12\\%$ means keeping the rest. What fraction remains?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a round number: $\\$100$ losing $10\\%$ leaves $\\$90$, so the multiplier is $0.90 = 1 - 0.10$. Subtract the loss rate from $1$ to get the base of the decay model.' },
      { level: 'guide', text: '$100\\% - 12\\% = 88\\%$, so the multiplier is $0.88$.' },
      { level: 'reveal', text: '$24000(0.88)^t$.' },
    ],
    learningObjective: 'Build an exponential decay model from a percent loss.',
    topic: 'Exponential decay',
    explanation: [
      'A $12\\%$ loss leaves $88\\%$ of the value, so the annual multiplier is $0.88$.',
      'Applying it $t$ times gives $24000(0.88)^t$.',
      'Choice A retains only $12\\%$ each year; choice B grows the value; choice D is linear and subtracts 12 cents a year.',
    ],
    alternativeExplanations: [
      { title: 'Check the first year', steps: ['After one year the car should be worth $24000 - 0.12(24000) = 24000 - 2880 = \\$21{,}120$.', 'Choice C at $t = 1$: $24000(0.88) = 21120$ ✓', 'Building the expected first-year value before you look at the choices is the fastest way to handle every model-selection question.'] },
    ],
    tags: ['exponential', 'decay', 'depreciation'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 98, unit: 10, order: 8, slug: 'sat-extend-exponential-table',
    standard: 'SAT.ADV.5', difficulty: 3,
    prompt: 'A function $f$ has the values $f(0) = 5$, $f(1) = 10$, $f(2) = 20$, and $f(3) = 40$. What is the value of $f(5)$?',
    answerType: 'numeric', primaryAnswer: '160', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Are the outputs changing by a constant amount, or by a constant factor?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a shorter table: $3, 6, 12$ doubles each step, so the next terms are $24$ and $48$. Confirm the constant ratio, then keep applying it — and count your steps on paper.' },
      { level: 'guide', text: 'Each output is double the one before, so $f(x) = 5 \\cdot 2^x$.' },
      { level: 'reveal', text: '$f(5) = 5 \\cdot 32 = 160$.' },
    ],
    learningObjective: 'Identify an exponential pattern and extend it.',
    topic: 'Exponential functions',
    explanation: [
      'The ratios are all $2$ ($10/5 = 2$, $20/10 = 2$, $40/20 = 2$), so the function is exponential with base $2$.',
      'The initial value is $f(0) = 5$, so $f(x) = 5 \\cdot 2^x$.',
      '$f(5) = 5 \\cdot 2^5 = 5 \\cdot 32 = 160$.',
    ],
    alternativeExplanations: [
      { title: 'Just keep doubling', steps: ['$f(3) = 40$, so $f(4) = 80$ and $f(5) = 160$.', 'For a small number of steps this beats building the formula.', 'The trap answer is $80$ — stopping one step short. Count your steps on scratch paper rather than in your head.'] },
    ],
    tags: ['exponential', 'table', 'extend'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 99, unit: 10, order: 9, slug: 'sat-half-life',
    standard: 'SAT.ADV.5', difficulty: 3,
    prompt: 'A medication has a half-life of $6$ hours: every $6$ hours, half of the remaining amount leaves the body. If a patient takes $80$ milligrams, how many milligrams remain after $24$ hours?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'How many $6$-hour periods fit into $24$ hours?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try one halving at a time: $100$ mg with a $2$-hour half-life is $50$ mg at $2$ hours and $25$ mg at $4$ hours. The exponent counts halvings, not hours.' },
      { level: 'guide', text: 'Four periods, so the amount halves four times.' },
      { level: 'reveal', text: '$80 \\to 40 \\to 20 \\to 10 \\to 5$ mg.' },
    ],
    learningObjective: 'Apply repeated halving over a fixed number of half-life periods.',
    topic: 'Exponential decay',
    explanation: [
      '$24 \\div 6 = 4$, so four half-lives elapse.',
      'Halving four times: $80 \\to 40 \\to 20 \\to 10 \\to 5$.',
      'Using the formula: $80\\left(\\tfrac{1}{2}\\right)^{24/6} = 80\\left(\\tfrac{1}{2}\\right)^{4} = \\dfrac{80}{16} = 5$ mg.',
    ],
    alternativeExplanations: [
      { title: 'Count the halvings, not the hours', steps: ['The most common error is using an exponent of $24$ instead of $4$.', 'The exponent counts *periods*, and the number of periods is elapsed time divided by the half-life.', 'Writing "$24 \\div 6 = 4$ halvings" as your first line makes the exponent impossible to get wrong.'] },
    ],
    tags: ['exponential', 'half-life', 'decay'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 100, unit: 10, order: 10, slug: 'sat-find-a-exponential',
    standard: 'SAT.ADV.5', difficulty: 3,
    prompt: 'The function $f$ is defined by $f(x) = ab^x$, where $a$ and $b$ are positive constants. If $f(1) = 12$ and $f(3) = 48$, what is the value of $a$?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide the two equations to eliminate $a$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller values: if $f(1) = 6$ and $f(2) = 12$, dividing gives $b = 2$, and then $a(2) = 6$ so $a = 3$. Dividing the two equations always cancels $a$ and isolates $b$.' },
      { level: 'guide', text: '$\\dfrac{ab^3}{ab^1} = b^2 = \\dfrac{48}{12} = 4$, so $b = 2$.' },
      { level: 'reveal', text: 'Then $f(1) = a(2) = 12$, so $a = 6$.' },
    ],
    learningObjective: 'Recover both parameters of an exponential function from two values.',
    topic: 'Exponential functions',
    explanation: [
      'Divide the two given values: $\\dfrac{f(3)}{f(1)} = \\dfrac{ab^3}{ab} = b^2$, and $\\dfrac{48}{12} = 4$.',
      'So $b^2 = 4$ and, since $b$ is positive, $b = 2$.',
      'Substitute back: $f(1) = a \\cdot 2 = 12$, so $a = 6$. (The function is $f(x) = 6 \\cdot 2^x$.)',
    ],
    alternativeExplanations: [
      { title: 'Reason in steps', steps: ['Going from $x = 1$ to $x = 3$ is two steps, and the output went from $12$ to $48$ — a factor of $4$.', 'Two equal steps multiplying to $4$ means each step multiplies by $2$, so $b = 2$.', 'Step back once from $f(1) = 12$ to get $f(0) = 6$, which is $a$ by definition. Dividing to cancel $a$ is the general technique whenever two function values are given.'] },
    ],
    tags: ['exponential', 'parameters', 'ratio'], estimatedSeconds: 95,
  },
];
