import type { SeedProblem } from './types';

// SAT — Algebra (blueprint area ALG, ~35% of the Math section). Units 1-5,
// problems 1-50. Ten per unit, difficulty climbing 1 → 3 across each unit.
//
// Every problem's `alternativeExplanations` entry demonstrates a *test-taking*
// route — backsolving, picking numbers, or the built-in Desmos calculator —
// alongside the algebraic one, because on a timed section the fastest correct
// method is the right method.

export const problemsSATalg: SeedProblem[] = [
  // ═══════════════ UNIT 1 — Linear Equations in One Variable ═══════════════
  {
    domain: 'SAT', num: 1, unit: 1, order: 1, slug: 'sat-solve-3x-7-22',
    standard: 'SAT.ALG.1', difficulty: 1,
    prompt: 'If $3x + 7 = 22$, what is the value of $x$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$3$', correct: false },
      { id: 'B', label: '$5$', correct: true },
      { id: 'C', label: '$7$', correct: false },
      { id: 'D', label: '$29/3$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Undo the operations in reverse order: the $+7$ comes off before the $\\times 3$.' },
      { level: 'guide', text: 'Subtract $7$ from both sides to get $3x = 15$.' },
      { level: 'reveal', text: '$3x = 15$, so $x = 5$.' },
    ],
    learningObjective: 'Solve a two-step linear equation in one variable.',
    topic: 'Two-step equations',
    explanation: [
      'Subtract $7$ from both sides: $3x = 15$.',
      'Divide both sides by $3$: $x = 5$.',
      'Check: $3(5) + 7 = 15 + 7 = 22$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Backsolve instead', steps: ['The choices are plain numbers, so test one. Start with B, $x = 5$.', '$3(5) + 7 = 22$ ✓ — done, with no algebra at all.', 'On a timed section this is often faster than solving forward, and it cannot be derailed by a sign error.'] },
    ],
    tags: ['linear-equation', 'one-variable', 'backsolve'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 2, unit: 1, order: 2, slug: 'sat-solve-5x-minus-2',
    standard: 'SAT.ALG.1', difficulty: 1,
    prompt: 'If $5(x - 2) = 35$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'You can distribute the $5$ — or divide both sides by $5$ first. The second is faster.' },
      { level: 'guide', text: 'Dividing both sides by $5$ gives $x - 2 = 7$.' },
      { level: 'reveal', text: '$x - 2 = 7$, so $x = 9$.' },
    ],
    learningObjective: 'Solve a linear equation with a factored side efficiently.',
    topic: 'Equations with parentheses',
    explanation: [
      'The left side is $5$ times the quantity $(x - 2)$, so divide both sides by $5$ first: $x - 2 = 7$.',
      'Add $2$ to both sides: $x = 9$.',
      'Check: $5(9 - 2) = 5(7) = 35$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Distribute first', steps: ['$5(x - 2) = 5x - 10$, so the equation is $5x - 10 = 35$.', 'Add $10$: $5x = 45$. Divide by $5$: $x = 9$.', 'Same answer, one extra step — dividing by the outside factor first is the shortcut worth building as a habit.'] },
    ],
    tags: ['linear-equation', 'distribute'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 3, unit: 1, order: 3, slug: 'sat-variables-both-sides',
    standard: 'SAT.ALG.1', difficulty: 2,
    prompt: 'If $4x + 9 = 7x - 12$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Collect the $x$ terms on one side and the constants on the other.' },
      { level: 'guide', text: 'Subtract $4x$ from both sides: $9 = 3x - 12$.' },
      { level: 'reveal', text: 'Add $12$: $21 = 3x$, so $x = 7$.' },
    ],
    learningObjective: 'Solve a linear equation with the variable on both sides.',
    topic: 'Variables on both sides',
    explanation: [
      'Subtract $4x$ from both sides: $9 = 3x - 12$.',
      'Add $12$ to both sides: $21 = 3x$.',
      'Divide by $3$: $x = 7$. Check: $4(7) + 9 = 37$ and $7(7) - 12 = 37$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Move terms toward the larger coefficient', steps: ['Subtracting $4x$ (the smaller coefficient) keeps the $x$ term positive: $9 = 3x - 12$.', 'Had you subtracted $7x$ instead you would get $-3x + 9 = -12$ — correct, but with a negative coefficient to manage.', 'Choosing the direction that avoids a negative is a small habit that prevents a lot of sign errors.'] },
    ],
    tags: ['linear-equation', 'both-sides'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 4, unit: 1, order: 4, slug: 'sat-fraction-equation',
    standard: 'SAT.ALG.1', difficulty: 2,
    prompt: 'If $\\dfrac{x}{3} + 4 = 10$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '18', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Deal with the $+4$ before the division by $3$.' },
      { level: 'guide', text: 'Subtract $4$: $\\dfrac{x}{3} = 6$.' },
      { level: 'reveal', text: 'Multiply both sides by $3$: $x = 18$.' },
    ],
    learningObjective: 'Solve a linear equation containing a fractional coefficient.',
    topic: 'Equations with fractions',
    explanation: [
      'Subtract $4$ from both sides: $\\dfrac{x}{3} = 6$.',
      'Multiply both sides by $3$: $x = 18$.',
      'Check: $\\dfrac{18}{3} + 4 = 6 + 4 = 10$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Clear the fraction first', steps: ['Multiply every term by $3$ at the start: $x + 12 = 30$.', 'Subtract $12$: $x = 18$.', 'Multiplying through by the denominator is the general move — it works even when there are several different denominators.'] },
    ],
    tags: ['linear-equation', 'fractions'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 5, unit: 1, order: 5, slug: 'sat-literal-solve-h',
    standard: 'SAT.ALG.1', difficulty: 2,
    prompt: 'The area of a triangle is given by $A = \\tfrac{1}{2}bh$. Which equation correctly gives $h$ in terms of $A$ and $b$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$h = \\dfrac{A}{2b}$', correct: false },
      { id: 'B', label: '$h = \\dfrac{2A}{b}$', correct: true },
      { id: 'C', label: '$h = 2Ab$', correct: false },
      { id: 'D', label: '$h = \\dfrac{b}{2A}$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Treat $A$ and $b$ as if they were ordinary numbers and isolate $h$.' },
      { level: 'guide', text: 'Multiply both sides by $2$ to clear the fraction: $2A = bh$.' },
      { level: 'reveal', text: 'Divide both sides by $b$: $h = \\dfrac{2A}{b}$.' },
    ],
    learningObjective: 'Rearrange a literal equation to isolate a chosen variable.',
    topic: 'Literal equations',
    explanation: [
      'Multiply both sides by $2$: $2A = bh$.',
      'Divide both sides by $b$: $h = \\dfrac{2A}{b}$.',
      'The steps are identical to solving a numeric equation — the other letters simply come along for the ride.',
    ],
    alternativeExplanations: [
      { title: 'Test with real numbers', steps: ['Take a triangle with $b = 4$ and $h = 5$. Then $A = \\tfrac{1}{2}(4)(5) = 10$.', 'Now check each choice at $A = 10$, $b = 4$ and keep the one returning $h = 5$.', 'B gives $\\dfrac{2(10)}{4} = 5$ ✓. A gives $10/8$, C gives $80$, D gives $0.2$ — all eliminated in one pass.'] },
    ],
    tags: ['literal-equation', 'rearrange', 'plug-in'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 6, unit: 1, order: 6, slug: 'sat-infinitely-many',
    standard: 'SAT.ALG.1', difficulty: 2,
    prompt: 'In the equation $3(2x + 1) = 6x + c$, $c$ is a constant. If the equation has infinitely many solutions, what is the value of $c$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Infinitely many solutions means the two sides are the *same* expression.' },
      { level: 'guide', text: 'Expand the left side: $6x + 3$. Compare it term by term with $6x + c$.' },
      { level: 'reveal', text: 'The $x$ terms already match, so the constants must match too: $c = 3$.' },
    ],
    learningObjective: 'Recognize the condition for a linear equation to have infinitely many solutions.',
    topic: 'Number of solutions',
    explanation: [
      'Distribute on the left: $3(2x + 1) = 6x + 3$.',
      'The equation becomes $6x + 3 = 6x + c$.',
      'Infinitely many solutions means every $x$ works, which happens only when the two sides are identical. The $x$ terms already agree, so we need $c = 3$.',
    ],
    alternativeExplanations: [
      { title: 'The three-case rule', steps: ['Write both sides as $ax + b$ and $cx + d$.', 'Different $x$-coefficients → exactly one solution. Same coefficient, different constants → no solution. Same coefficient AND same constant → infinitely many.', 'Here the coefficients already match at $6$, so it is the constant that decides — this single rule handles every question of this type.'] },
    ],
    tags: ['number-of-solutions', 'identity'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 7, unit: 1, order: 7, slug: 'sat-decimal-equation',
    standard: 'SAT.ALG.1', difficulty: 3,
    prompt: 'If $0.25x + 1.5 = 0.4x - 0.6$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '14', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Decimals are not harder than integers — or multiply everything by $100$ to remove them.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try it with friendlier numbers first: $0.5x = 2$. Multiply both sides by $10$ to get $5x = 20$, so $x = 4$. Scaling away the decimals works the same way no matter how many terms there are.' },
      { level: 'guide', text: 'Subtract $0.25x$ from both sides: $1.5 = 0.15x - 0.6$.' },
      { level: 'reveal', text: 'Add $0.6$: $2.1 = 0.15x$, so $x = 14$.' },
    ],
    learningObjective: 'Solve a linear equation with decimal coefficients.',
    topic: 'Decimal coefficients',
    explanation: [
      'Subtract $0.25x$ from both sides: $1.5 = 0.15x - 0.6$.',
      'Add $0.6$ to both sides: $2.1 = 0.15x$.',
      'Divide: $x = \\dfrac{2.1}{0.15} = 14$. Check: $0.25(14) + 1.5 = 5$ and $0.4(14) - 0.6 = 5$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Clear decimals with Desmos, or by hand', steps: ['Multiply every term by $100$: $25x + 150 = 40x - 60$.', 'Then $210 = 15x$, so $x = 14$ — integers throughout.', 'Faster still: graph $y_1 = 0.25x + 1.5$ and $y_2 = 0.4x - 0.6$ in Desmos and click the intersection.'] },
    ],
    tags: ['linear-equation', 'decimals', 'desmos'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 8, unit: 1, order: 8, slug: 'sat-plumber-hours',
    standard: 'SAT.ALG.1', difficulty: 3,
    prompt: 'A plumber charges a flat call-out fee of $\\$75$ plus $\\$45$ for each hour of work. A customer\'s total bill was $\\$322.50$. How many hours did the plumber work?',
    answerType: 'numeric', primaryAnswer: '5.5', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.01,
    alternativeAnswers: ['11/2', '5.50'],
    hints: [
      { level: 'nudge', text: 'One number is charged once; the other is charged per hour. Build $75 + 45h = 322.50$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller numbers first: a $\\$10$ fee plus $\\$5$ per hour, with a $\\$35$ bill. Subtract the fee ($\\$25$ left) and divide by the rate: $5$ hours. The real problem is the same two steps.' },
      { level: 'guide', text: 'Subtract the flat fee: $45h = 247.50$.' },
      { level: 'reveal', text: '$h = \\dfrac{247.50}{45} = 5.5$ hours.' },
    ],
    learningObjective: 'Model a flat-fee-plus-rate situation and solve for the rate quantity.',
    topic: 'Linear models in context',
    explanation: [
      'The flat fee is paid once and the hourly rate is paid $h$ times, so the total is $75 + 45h$.',
      'Set that equal to the bill: $75 + 45h = 322.50$.',
      'Subtract $75$: $45h = 247.50$. Divide by $45$: $h = 5.5$ hours.',
    ],
    alternativeExplanations: [
      { title: 'Reason without algebra', steps: ['Of the $\\$322.50$ bill, $\\$75$ was not for labour, so $\\$247.50$ was.', 'At $\\$45$ per hour, $\\$225$ buys 5 hours and $\\$22.50$ buys half an hour.', 'That is $5.5$ hours — the same answer, reached by splitting the money rather than by solving.'] },
    ],
    tags: ['word-problem', 'flat-fee-plus-rate'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 9, unit: 1, order: 9, slug: 'sat-proportion-equation',
    standard: 'SAT.ALG.1', difficulty: 3,
    prompt: 'If $\\dfrac{2x - 1}{5} = \\dfrac{x + 4}{3}$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '23', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Two fractions set equal to each other — cross-multiply.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a simpler proportion: $\\dfrac{x}{2} = \\dfrac{6}{3}$. Cross-multiply to get $3x = 12$, so $x = 4$. Cross-multiplying works identically when the numerators are expressions instead of single letters.' },
      { level: 'guide', text: '$3(2x - 1) = 5(x + 4)$. Distribute both sides carefully.' },
      { level: 'reveal', text: '$6x - 3 = 5x + 20$, so $x = 23$.' },
    ],
    learningObjective: 'Solve a proportion involving linear expressions.',
    topic: 'Proportions with variables',
    explanation: [
      'Cross-multiply: $3(2x - 1) = 5(x + 4)$.',
      'Distribute: $6x - 3 = 5x + 20$.',
      'Subtract $5x$ and add $3$: $x = 23$. Check: $\\dfrac{45}{5} = 9$ and $\\dfrac{27}{3} = 9$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Multiply by the common denominator', steps: ['The denominators are $5$ and $3$, so multiply every term by $15$.', 'The left becomes $3(2x - 1)$ and the right becomes $5(x + 4)$ — exactly the cross-multiplied form.', 'Cross-multiplication is not a separate trick; it is this step with the arithmetic already done.'] },
    ],
    tags: ['proportion', 'cross-multiply'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 10, unit: 1, order: 10, slug: 'sat-no-solution-k',
    standard: 'SAT.ALG.1', difficulty: 3,
    prompt: 'In the equation $kx + 8 = 3x - 5$, $k$ is a constant. For which value of $k$ does the equation have **no** solution?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$-5$', correct: false },
      { id: 'B', label: '$0$', correct: false },
      { id: 'C', label: '$3$', correct: true },
      { id: 'D', label: '$8$', correct: false },
    ],
    primaryAnswer: 'C', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'No solution means the two sides never meet — parallel lines.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try the idea on plain numbers: $2x + 1 = 2x + 9$ has no solution, because subtracting $2x$ leaves $1 = 9$. Matching $x$-coefficients with different constants is exactly what makes an equation unsolvable.' },
      { level: 'guide', text: 'Gather the $x$ terms: $(k - 3)x = -13$.' },
      { level: 'reveal', text: 'If $k = 3$ the left side is $0$ and the equation reads $0 = -13$, which is impossible. So $k = 3$.' },
    ],
    learningObjective: 'Determine the constant that makes a linear equation unsolvable.',
    topic: 'Number of solutions',
    explanation: [
      'Move everything to one side: $kx - 3x = -5 - 8$, so $(k - 3)x = -13$.',
      'If $k \\neq 3$ you can divide by $(k - 3)$ and get exactly one solution.',
      'If $k = 3$, the equation becomes $0 \\cdot x = -13$, or $0 = -13$ — false for every $x$. So there is no solution when $k = 3$.',
    ],
    alternativeExplanations: [
      { title: 'Match the slopes', steps: ['Read each side as a line: $y = kx + 8$ and $y = 3x - 5$.', 'Two lines fail to intersect exactly when they are parallel — same slope, different intercept.', 'Same slope means $k = 3$; the intercepts $8$ and $-5$ already differ, so there is genuinely no solution.'] },
    ],
    tags: ['number-of-solutions', 'no-solution', 'parallel'], estimatedSeconds: 80,
  },

  // ═══════════════ UNIT 2 — Linear Functions and Rate of Change ═══════════════
  {
    domain: 'SAT', num: 11, unit: 2, order: 1, slug: 'sat-evaluate-f-of-3',
    standard: 'SAT.ALG.2', difficulty: 1,
    prompt: 'The function $f$ is defined by $f(x) = 4x - 7$. What is the value of $f(3)$?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$f(3)$ means "replace every $x$ with $3$".' },
      { level: 'guide', text: 'Compute $4(3) - 7$.' },
      { level: 'reveal', text: '$12 - 7 = 5$.' },
    ],
    learningObjective: 'Evaluate a linear function at a given input.',
    topic: 'Function notation',
    explanation: [
      'Function notation $f(3)$ is an instruction: substitute $3$ for $x$.',
      '$f(3) = 4(3) - 7 = 12 - 7 = 5$.',
    ],
    alternativeExplanations: [
      { title: 'Read it as a machine', steps: ['The rule "multiply by 4, then subtract 7" is a machine you feed a number to.', 'Feed it $3$: it multiplies to get $12$, then subtracts to get $5$.', 'Function notation names the machine ($f$) and the input ($3$) in one compact symbol.'] },
    ],
    tags: ['function-notation', 'evaluate'], estimatedSeconds: 30,
  },
  {
    domain: 'SAT', num: 12, unit: 2, order: 2, slug: 'sat-line-from-slope-intercept',
    standard: 'SAT.ALG.2', difficulty: 1,
    prompt: 'Which equation represents the line with slope $-2$ that passes through the point $(0, 5)$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$y = 5x - 2$', correct: false },
      { id: 'B', label: '$y = -2x + 5$', correct: true },
      { id: 'C', label: '$y = -2x - 5$', correct: false },
      { id: 'D', label: '$y = 2x + 5$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'A point with $x = 0$ is the $y$-intercept.' },
      { level: 'guide', text: 'In $y = mx + b$, $m$ is the slope and $b$ is the $y$-intercept.' },
      { level: 'reveal', text: '$m = -2$ and $b = 5$, so $y = -2x + 5$.' },
    ],
    learningObjective: 'Write a linear equation from a slope and the y-intercept.',
    topic: 'Slope-intercept form',
    explanation: [
      'The point $(0, 5)$ has $x = 0$, so it is the $y$-intercept: $b = 5$.',
      'The slope is given as $m = -2$.',
      'Substituting into $y = mx + b$ gives $y = -2x + 5$.',
    ],
    alternativeExplanations: [
      { title: 'Eliminate by testing the point', steps: ['Every correct choice must give $y = 5$ when $x = 0$.', 'A gives $-2$, C gives $-5$ — both out. B and D both give $5$.', 'Now use the slope to separate them: only B has $m = -2$.'] },
    ],
    tags: ['slope-intercept', 'linear-function'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 13, unit: 2, order: 3, slug: 'sat-interpret-slope-context',
    standard: 'SAT.ALG.2', difficulty: 2,
    prompt: 'A moving company charges according to $C(t) = 32t + 150$, where $C$ is the total cost in dollars and $t$ is the number of hours worked. What does the number $32$ represent?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'The fixed cost before any work begins', correct: false },
      { id: 'B', label: 'The cost per hour of work', correct: true },
      { id: 'C', label: 'The total cost of a one-hour job', correct: false },
      { id: 'D', label: 'The number of hours included in the base charge', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The number attached to $t$ is a *rate*. Ask what units it must carry.' },
      { level: 'guide', text: '$C$ is in dollars and $t$ is in hours, so the coefficient of $t$ is in dollars per hour.' },
      { level: 'reveal', text: '$32$ is the cost per hour; $150$ is the fixed charge.' },
    ],
    learningObjective: 'Interpret the slope of a linear model in context, with units.',
    topic: 'Interpreting slope',
    explanation: [
      'In a linear model, the coefficient of the variable is the slope, and the slope is always a rate: output units per input unit.',
      'Here the output is dollars and the input is hours, so $32$ is measured in dollars per hour — the cost of each additional hour.',
      'The constant $150$ is what you pay when $t = 0$: the fixed charge. Choice C is the trap — a one-hour job costs $32 + 150 = \\$182$, not $\\$32$.',
    ],
    alternativeExplanations: [
      { title: 'Compare two inputs', steps: ['At $t = 3$: $C = 32(3) + 150 = \\$246$. At $t = 4$: $C = 32(4) + 150 = \\$278$.', 'One extra hour of work added exactly $\\$32$ to the bill.', 'That is the definition of the slope in this context — what one more hour costs.'] },
    ],
    tags: ['interpret-slope', 'context', 'units'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 14, unit: 2, order: 4, slug: 'sat-slope-two-points',
    standard: 'SAT.ALG.2', difficulty: 2,
    prompt: 'A line passes through the points $(2, 7)$ and $(6, 19)$. What is the slope of the line?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Slope is rise over run: the change in $y$ divided by the change in $x$.' },
      { level: 'guide', text: 'The $y$ values change by $19 - 7 = 12$; the $x$ values change by $6 - 2 = 4$.' },
      { level: 'reveal', text: '$\\dfrac{12}{4} = 3$.' },
    ],
    learningObjective: 'Compute the slope of a line through two given points.',
    topic: 'Slope formula',
    explanation: [
      'Slope $= \\dfrac{y_2 - y_1}{x_2 - x_1} = \\dfrac{19 - 7}{6 - 2}$.',
      '$= \\dfrac{12}{4} = 3$.',
      'The order of the points does not matter as long as it is consistent: $\\dfrac{7 - 19}{2 - 6} = \\dfrac{-12}{-4} = 3$ too.',
    ],
    alternativeExplanations: [
      { title: 'Where the sign errors come from', steps: ['The one dangerous mistake is subtracting the $y$ values in one order and the $x$ values in the other.', '$\\dfrac{19 - 7}{2 - 6} = \\dfrac{12}{-4} = -3$ — right magnitude, wrong sign, and it will be one of the answer choices.', 'Write both differences top-to-bottom in the same order every time and this error disappears.'] },
    ],
    tags: ['slope', 'two-points'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 15, unit: 2, order: 5, slug: 'sat-find-a-linear-fn',
    standard: 'SAT.ALG.2', difficulty: 2,
    prompt: 'The function $f$ is defined by $f(x) = ax + b$, where $a$ and $b$ are constants. If $f(0) = -4$ and $f(5) = 11$, what is the value of $a$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '$f(0)$ hands you $b$ immediately — the $ax$ term vanishes.' },
      { level: 'guide', text: 'With $b = -4$, the second condition says $5a - 4 = 11$.' },
      { level: 'reveal', text: '$5a = 15$, so $a = 3$.' },
    ],
    learningObjective: 'Recover the parameters of a linear function from two function values.',
    topic: 'Building a linear function',
    explanation: [
      '$f(0) = a(0) + b = b$, so $b = -4$.',
      'Then $f(5) = 5a + b = 5a - 4 = 11$.',
      'Add $4$: $5a = 15$, so $a = 3$.',
    ],
    alternativeExplanations: [
      { title: 'Read it as slope between two points', steps: ['$f(0) = -4$ and $f(5) = 11$ are the points $(0, -4)$ and $(5, 11)$.', 'The constant $a$ in $ax + b$ *is* the slope: $\\dfrac{11 - (-4)}{5 - 0} = \\dfrac{15}{5} = 3$.', 'Seeing function values as coordinates turns most of these questions into a one-line slope computation.'] },
    ],
    tags: ['linear-function', 'parameters'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 16, unit: 2, order: 6, slug: 'sat-linear-table-extend',
    standard: 'SAT.ALG.2', difficulty: 2,
    prompt: 'A linear function $g$ satisfies $g(1) = 8$ and $g(3) = 14$. What is the value of $g(7)$?',
    answerType: 'numeric', primaryAnswer: '26', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the constant rate of change first.' },
      { level: 'guide', text: 'From $x = 1$ to $x = 3$ the output rose $6$ over a run of $2$, so the slope is $3$.' },
      { level: 'reveal', text: 'From $x = 3$ to $x = 7$ is 4 more steps: $14 + 3(4) = 26$.' },
    ],
    learningObjective: 'Extend a linear pattern using a constant rate of change.',
    topic: 'Linear growth',
    explanation: [
      'Slope $= \\dfrac{14 - 8}{3 - 1} = \\dfrac{6}{2} = 3$: every increase of $1$ in $x$ raises $g$ by $3$.',
      'From $x = 3$ to $x = 7$ is an increase of $4$, so $g$ rises by $3 \\times 4 = 12$.',
      '$g(7) = 14 + 12 = 26$.',
    ],
    alternativeExplanations: [
      { title: 'Build the whole equation', steps: ['With slope $3$ and the point $(1, 8)$: $g(x) = 3(x - 1) + 8 = 3x + 5$.', 'Then $g(7) = 3(7) + 5 = 26$.', 'Building the equation costs one extra step but pays off if the question asks for several values.'] },
    ],
    tags: ['linear-function', 'rate-of-change'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 17, unit: 2, order: 7, slug: 'sat-function-equation-solve',
    standard: 'SAT.ALG.2', difficulty: 3,
    prompt: 'The function $h$ is defined by $h(x) = 5 - 2x$. If $h(a) = h(3) + 4$, what is the value of $a$?',
    answerType: 'numeric', primaryAnswer: '1', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Compute the right-hand side to a single number before touching $a$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a smaller version: if $g(x) = 10 - x$ and $g(a) = g(2) + 3$, first get $g(2) = 8$, so $g(a) = 11$, giving $a = -1$. Always collapse the known side to a single number before solving.' },
      { level: 'guide', text: '$h(3) = 5 - 6 = -1$, so the right side is $-1 + 4 = 3$.' },
      { level: 'reveal', text: 'Solve $5 - 2a = 3$: $-2a = -2$, so $a = 1$.' },
    ],
    learningObjective: 'Solve an equation involving function notation on both sides.',
    topic: 'Function notation',
    explanation: [
      'First evaluate the known side: $h(3) = 5 - 2(3) = -1$.',
      'So the equation reads $h(a) = -1 + 4 = 3$.',
      'Now $5 - 2a = 3$, giving $-2a = -2$ and $a = 1$. Check: $h(1) = 3$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Use the slope directly', steps: ['The slope is $-2$: every step of $+1$ in $x$ drops the output by $2$.', 'You need an output $4$ higher than $h(3)$, so you must move $x$ down by $2$ steps.', '$a = 3 - 2 = 1$ — no equation solved at all.'] },
    ],
    tags: ['function-notation', 'slope-reasoning'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 18, unit: 2, order: 8, slug: 'sat-x-intercept-meaning',
    standard: 'SAT.ALG.2', difficulty: 3,
    prompt: 'A small business models its daily profit with $P(x) = 8.5x - 240$, where $x$ is the number of items sold and $P$ is profit in dollars. What does the $x$-intercept of this function represent?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'The profit made when no items are sold', correct: false },
      { id: 'B', label: 'The number of items that must be sold to break even', correct: true },
      { id: 'C', label: 'The profit earned on each item sold', correct: false },
      { id: 'D', label: 'The maximum number of items that can be sold', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The $x$-intercept is where the output is zero. What does zero profit mean here?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try it with tiny numbers: $P(x) = 2x - 6$. The $x$-intercept is $x = 3$, and selling 3 items yields exactly $\\$0$ profit — costs covered, nothing more. That is break-even.' },
      { level: 'guide', text: 'Zero profit means revenue exactly covers costs — that is the break-even point.' },
      { level: 'reveal', text: 'It is the number of items sold at which profit is $\\$0$: break even.' },
    ],
    learningObjective: 'Interpret the x-intercept of a linear model in context.',
    topic: 'Interpreting intercepts',
    explanation: [
      'The $x$-intercept is the value of $x$ making $P(x) = 0$.',
      'Zero profit means the business has covered its costs exactly and made nothing beyond them — the break-even point.',
      'Choice A describes the $y$-intercept ($-\\$240$, a loss) and choice C describes the slope ($\\$8.50$ per item). Every one of the wrong answers is a correct statement about a *different* feature of the model.',
    ],
    alternativeExplanations: [
      { title: 'Compute it and read the number', steps: ['Set $8.5x - 240 = 0$, so $x = \\dfrac{240}{8.5} \\approx 28.2$ items.', 'Selling 28 items still leaves a small loss; 29 turns the first profit.', 'A number like "about 28 items" only makes sense as a break-even count — the arithmetic itself rules the other choices out.'] },
    ],
    tags: ['interpret-intercept', 'context', 'break-even'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 19, unit: 2, order: 9, slug: 'sat-candle-initial-height',
    standard: 'SAT.ALG.2', difficulty: 3,
    prompt: 'A candle burns at a constant rate. After $2$ hours it is $18$ cm tall, and after $5$ hours it is $10.5$ cm tall. What was the height of the candle, in centimeters, before it was lit?',
    answerType: 'numeric', primaryAnswer: '23', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Constant rate means a linear model. Find the rate first.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easier pair: after $1$ hour a candle is $9$ cm and after $2$ hours it is $7$ cm, so it burns $2$ cm per hour. Running back one hour from the 9 cm mark gives $11$ cm at the start.' },
      { level: 'guide', text: 'It lost $18 - 10.5 = 7.5$ cm over $3$ hours, so it burns $2.5$ cm per hour.' },
      { level: 'reveal', text: 'Run back $2$ hours from the 18 cm mark: $18 + 2(2.5) = 23$ cm.' },
    ],
    learningObjective: 'Extrapolate a linear model backwards to its initial value.',
    topic: 'Linear models in context',
    explanation: [
      'The rate of change is $\\dfrac{10.5 - 18}{5 - 2} = \\dfrac{-7.5}{3} = -2.5$ cm per hour.',
      '"Before it was lit" means $t = 0$, which is $2$ hours before the 18 cm reading.',
      'Going backwards adds height: $18 + 2(2.5) = 23$ cm.',
    ],
    alternativeExplanations: [
      { title: 'Write the equation', steps: ['With slope $-2.5$ and point $(2, 18)$: $h = -2.5(t - 2) + 18 = -2.5t + 23$.', 'The initial height is the $y$-intercept, which the equation now displays directly: $23$ cm.', 'The trap is answering $-2.5$ or $18$ — both appear in the setup, neither is the initial height.'] },
    ],
    tags: ['word-problem', 'linear-model', 'initial-value'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 20, unit: 2, order: 10, slug: 'sat-linear-extend-negative',
    standard: 'SAT.ALG.2', difficulty: 3,
    prompt: 'The function $f$ is linear, with $f(2) = 9$ and $f(6) = 1$. What is the value of $f(10)$?',
    answerType: 'numeric', primaryAnswer: '-7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The outputs are decreasing, so the slope is negative.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller steps: if $f(1) = 6$ and $f(2) = 4$, the slope is $-2$, so $f(3) = 2$. Each step of $+1$ in $x$ subtracts the same amount — that is all a negative slope means.' },
      { level: 'guide', text: 'Slope $= \\dfrac{1 - 9}{6 - 2} = -2$.' },
      { level: 'reveal', text: 'From $x = 6$ to $x = 10$ is $4$ more steps: $1 + (-2)(4) = -7$.' },
    ],
    learningObjective: 'Extend a decreasing linear function beyond the given values.',
    topic: 'Linear growth',
    explanation: [
      'Slope $= \\dfrac{1 - 9}{6 - 2} = \\dfrac{-8}{4} = -2$.',
      'Each step of $+1$ in $x$ lowers the output by $2$.',
      'From $x = 6$ to $x = 10$: $f(10) = 1 - 2(4) = -7$.',
    ],
    alternativeExplanations: [
      { title: 'Spot the pattern', steps: ['$x = 2, 6, 10$ are equally spaced — each gap is $4$.', 'Equal steps in $x$ produce equal steps in $y$ for a linear function, and the first step was $9 \\to 1$, a drop of $8$.', 'So the next step drops $8$ again: $1 - 8 = -7$. No slope formula needed.'] },
    ],
    tags: ['linear-function', 'negative-slope', 'pattern'], estimatedSeconds: 70,
  },

  // ═══════════════ UNIT 3 — Linear Equations in Two Variables ═══════════════
  {
    domain: 'SAT', num: 21, unit: 3, order: 1, slug: 'sat-read-y-intercept',
    standard: 'SAT.ALG.3', difficulty: 1,
    prompt: 'What is the $y$-intercept of the graph of $y = 3x - 4$?',
    answerType: 'numeric', primaryAnswer: '-4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $y$-intercept is the output when $x = 0$.' },
      { level: 'guide', text: 'Substitute $x = 0$: $y = 3(0) - 4$.' },
      { level: 'reveal', text: '$y = -4$.' },
    ],
    learningObjective: 'Identify the y-intercept from slope-intercept form.',
    topic: 'Slope-intercept form',
    explanation: [
      'In $y = mx + b$, the constant $b$ is the $y$-intercept.',
      'Here $b = -4$, so the graph crosses the $y$-axis at $-4$.',
      'Confirm by substituting $x = 0$: $y = 3(0) - 4 = -4$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Watch the sign', steps: ['The equation is $y = 3x + (-4)$, so $b = -4$, not $4$.', 'A positive $4$ will always be one of the answer choices on a question like this.', 'Rewriting a subtraction as "plus a negative" once, in your head, removes the ambiguity.'] },
    ],
    tags: ['y-intercept', 'slope-intercept'], estimatedSeconds: 30,
  },
  {
    domain: 'SAT', num: 22, unit: 3, order: 2, slug: 'sat-x-intercept-standard',
    standard: 'SAT.ALG.3', difficulty: 1,
    prompt: 'What is the $x$-intercept of the graph of $2x + 3y = 12$?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'At an $x$-intercept, the graph is on the $x$-axis — so $y = 0$.' },
      { level: 'guide', text: 'Set $y = 0$: $2x + 3(0) = 12$.' },
      { level: 'reveal', text: '$2x = 12$, so $x = 6$.' },
    ],
    learningObjective: 'Find an intercept from standard form by zeroing the other variable.',
    topic: 'Intercepts from standard form',
    explanation: [
      'An $x$-intercept has $y = 0$. Substitute: $2x + 3(0) = 12$.',
      'That leaves $2x = 12$, so $x = 6$.',
      'The intercept point is $(6, 0)$; the question asks only for the $x$-value.',
    ],
    alternativeExplanations: [
      { title: 'The intercept shortcut for standard form', steps: ['For $Ax + By = C$, the $x$-intercept is $C/A$ and the $y$-intercept is $C/B$.', 'Here $x$-intercept $= 12/2 = 6$ and $y$-intercept $= 12/3 = 4$ — both in one glance.', 'This is worth memorizing: standard-form intercept questions appear on nearly every test.'] },
    ],
    tags: ['x-intercept', 'standard-form'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 23, unit: 3, order: 3, slug: 'sat-standard-to-slope',
    standard: 'SAT.ALG.3', difficulty: 2,
    prompt: 'What is the slope of the line $4x - 2y = 10$?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Solve for $y$ to reveal the slope.' },
      { level: 'guide', text: 'Subtract $4x$: $-2y = -4x + 10$. Now divide by $-2$.' },
      { level: 'reveal', text: '$y = 2x - 5$, so the slope is $2$.' },
    ],
    learningObjective: 'Convert standard form to slope-intercept form.',
    topic: 'Form conversion',
    explanation: [
      'Isolate the $y$ term: $-2y = -4x + 10$.',
      'Divide every term by $-2$: $y = 2x - 5$.',
      'The coefficient of $x$ is the slope: $2$. Both signs flipped when dividing by a negative — that is where this question is usually lost.',
    ],
    alternativeExplanations: [
      { title: 'Use the standard-form slope formula', steps: ['For $Ax + By = C$, the slope is $-A/B$.', 'Here $A = 4$ and $B = -2$, so the slope is $-\\dfrac{4}{-2} = 2$.', 'One step instead of three, and no chance of a sign slip during the division.'] },
    ],
    tags: ['slope', 'standard-form', 'conversion'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 24, unit: 3, order: 4, slug: 'sat-line-through-two-points',
    standard: 'SAT.ALG.3', difficulty: 2,
    prompt: 'Which equation describes the line passing through the points $(1, 2)$ and $(4, 11)$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$y = 3x - 1$', correct: true },
      { id: 'B', label: '$y = 3x + 1$', correct: false },
      { id: 'C', label: '$y = \\tfrac{1}{3}x + \\tfrac{5}{3}$', correct: false },
      { id: 'D', label: '$y = 9x - 7$', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Find the slope first, then use one point to pin down the intercept.' },
      { level: 'guide', text: 'Slope $= \\dfrac{11 - 2}{4 - 1} = 3$.' },
      { level: 'reveal', text: 'With $m = 3$ and the point $(1, 2)$: $2 = 3(1) + b$, so $b = -1$ and $y = 3x - 1$.' },
    ],
    learningObjective: 'Build the equation of a line through two given points.',
    topic: 'Writing linear equations',
    explanation: [
      'Slope $= \\dfrac{11 - 2}{4 - 1} = \\dfrac{9}{3} = 3$.',
      'Substitute a point into $y = 3x + b$. Using $(1, 2)$: $2 = 3 + b$, so $b = -1$.',
      'The line is $y = 3x - 1$. Verify with the other point: $3(4) - 1 = 11$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Test both points against the choices', steps: ['Any correct line must contain *both* points, so test each choice twice.', 'At $(1, 2)$: A gives $2$ ✓, B gives $4$ ✗, C gives $2$ ✓, D gives $2$ ✓ — B is out.', 'At $(4, 11)$: A gives $11$ ✓, C gives $3$ ✗, D gives $29$ ✗. Only A survives, with no algebra required.'] },
    ],
    tags: ['writing-equations', 'two-points'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 25, unit: 3, order: 5, slug: 'sat-parallel-line',
    standard: 'SAT.ALG.3', difficulty: 2,
    prompt: 'Line $\\ell$ is parallel to the graph of $y = -\\tfrac{1}{2}x + 7$ and passes through the point $(4, 1)$. What is the $y$-intercept of line $\\ell$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Parallel lines have identical slopes.' },
      { level: 'guide', text: 'So $\\ell$ has slope $-\\tfrac{1}{2}$. Substitute $(4, 1)$ into $y = -\\tfrac{1}{2}x + b$.' },
      { level: 'reveal', text: '$1 = -2 + b$, so $b = 3$.' },
    ],
    learningObjective: 'Use the parallel-slope condition to build a new line.',
    topic: 'Parallel lines',
    explanation: [
      'Parallel means same slope, so $\\ell$ has slope $-\\tfrac{1}{2}$.',
      'Substitute the point $(4, 1)$: $1 = -\\tfrac{1}{2}(4) + b = -2 + b$.',
      'So $b = 3$, and $\\ell$ is $y = -\\tfrac{1}{2}x + 3$.',
    ],
    alternativeExplanations: [
      { title: 'Walk back along the slope', steps: ['You are at $(4, 1)$ and want to reach $x = 0$ — a move of $4$ to the left.', 'A slope of $-\\tfrac{1}{2}$ means going left raises $y$ by $\\tfrac{1}{2}$ per step, so $4$ steps left adds $2$.', '$1 + 2 = 3$, the $y$-intercept. Stepping along the slope is often faster than substituting.'] },
    ],
    tags: ['parallel', 'y-intercept'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 26, unit: 3, order: 6, slug: 'sat-perpendicular-slope',
    standard: 'SAT.ALG.3', difficulty: 2,
    prompt: 'What is the slope of a line perpendicular to the graph of $y = \\tfrac{3}{4}x - 2$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$\\tfrac{3}{4}$', correct: false },
      { id: 'B', label: '$-\\tfrac{3}{4}$', correct: false },
      { id: 'C', label: '$\\tfrac{4}{3}$', correct: false },
      { id: 'D', label: '$-\\tfrac{4}{3}$', correct: true },
    ],
    primaryAnswer: 'D', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Perpendicular slopes are negative reciprocals — you must both flip and negate.' },
      { level: 'guide', text: 'Flip $\\tfrac{3}{4}$ to get $\\tfrac{4}{3}$, then attach the opposite sign.' },
      { level: 'reveal', text: 'The perpendicular slope is $-\\tfrac{4}{3}$.' },
    ],
    learningObjective: 'Apply the negative-reciprocal condition for perpendicular lines.',
    topic: 'Perpendicular lines',
    explanation: [
      'Perpendicular slopes multiply to $-1$.',
      'The given slope is $\\tfrac{3}{4}$, so the perpendicular slope $m$ satisfies $\\tfrac{3}{4}m = -1$.',
      '$m = -\\tfrac{4}{3}$. Check: $\\tfrac{3}{4} \\times -\\tfrac{4}{3} = -1$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Why both wrong answers exist', steps: ['Choice B negated but forgot to flip; choice C flipped but forgot to negate.', 'The College Board builds one distractor for each half of the rule, every single time.', 'Say the rule as two separate actions — "flip it, then negate it" — and check that you performed both.'] },
    ],
    tags: ['perpendicular', 'negative-reciprocal'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 27, unit: 3, order: 7, slug: 'sat-find-k-from-slope',
    standard: 'SAT.ALG.3', difficulty: 3,
    prompt: 'In the equation $3x + ky = 12$, $k$ is a nonzero constant. If the graph has a slope of $\\tfrac{3}{2}$, what is the value of $k$?',
    answerType: 'numeric', primaryAnswer: '-2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'For $Ax + By = C$, the slope is $-A/B$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try it with a known line: in $2x + 4y = 8$, solving for $y$ gives $y = -\\tfrac{1}{2}x + 2$, and indeed $-A/B = -2/4 = -\\tfrac{1}{2}$. Once you trust the formula, the unknown $k$ is just algebra.' },
      { level: 'guide', text: 'So $-\\dfrac{3}{k} = \\dfrac{3}{2}$.' },
      { level: 'reveal', text: 'Cross-multiply: $3k = -6$, so $k = -2$.' },
    ],
    learningObjective: 'Solve for an unknown coefficient given a required slope.',
    topic: 'Parameters in linear equations',
    explanation: [
      'Solve for $y$: $ky = -3x + 12$, so $y = -\\dfrac{3}{k}x + \\dfrac{12}{k}$.',
      'The slope is $-\\dfrac{3}{k}$, and this must equal $\\dfrac{3}{2}$.',
      'Cross-multiplying gives $-6 = 3k$, so $k = -2$. Check: $3x - 2y = 12$ becomes $y = \\tfrac{3}{2}x - 6$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Reason about the sign first', steps: ['The target slope is positive, but the slope formula is $-3/k$ with a positive $3$ on top.', 'A negative divided by $k$ can only be positive if $k$ itself is negative — so $k < 0$ before any computation.', 'That alone eliminates the positive choices, and the magnitude $|k| = 2$ finishes it.'] },
    ],
    tags: ['slope', 'parameter', 'standard-form'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 28, unit: 3, order: 8, slug: 'sat-predict-from-line',
    standard: 'SAT.ALG.3', difficulty: 3,
    prompt: 'A line passes through $(0, -3)$ and $(5, 7)$. What is the value of $y$ when $x = 8$?',
    answerType: 'numeric', primaryAnswer: '13', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'One of the given points is already the $y$-intercept.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try the same shape with easy numbers: through $(0, 1)$ and $(1, 3)$ the slope is $2$, so $y = 2x + 1$ and at $x = 4$, $y = 9$. Find the intercept, find the slope, then substitute.' },
      { level: 'guide', text: 'Slope $= \\dfrac{7 - (-3)}{5 - 0} = 2$, and $b = -3$.' },
      { level: 'reveal', text: '$y = 2x - 3$, so at $x = 8$: $y = 13$.' },
    ],
    learningObjective: 'Build a line from two points and evaluate it at a new input.',
    topic: 'Writing and using linear equations',
    explanation: [
      'The point $(0, -3)$ has $x = 0$, so the $y$-intercept is $-3$.',
      'Slope $= \\dfrac{7 - (-3)}{5 - 0} = \\dfrac{10}{5} = 2$.',
      'So $y = 2x - 3$, and at $x = 8$: $y = 16 - 3 = 13$.',
    ],
    alternativeExplanations: [
      { title: 'Step along the slope', steps: ['From $(5, 7)$ you need to reach $x = 8$ — three steps right.', 'Each step right raises $y$ by $2$, so $y$ rises by $6$.', '$7 + 6 = 13$. When a question gives a point close to the target, stepping beats rebuilding the equation.'] },
    ],
    tags: ['linear-equation', 'evaluate'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 29, unit: 3, order: 9, slug: 'sat-revenue-two-variable',
    standard: 'SAT.ALG.3', difficulty: 3,
    prompt: 'A vendor sells hot dogs for $\\$3$ each and drinks for $\\$2$ each. On one day the vendor collected $\\$180$ in total from these two items and sold $40$ hot dogs. How many drinks were sold?',
    answerType: 'numeric', primaryAnswer: '30', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Write the revenue equation: $3h + 2d = 180$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller quantities: pens cost $\\$2$ and pads $\\$5$, total $\\$21$, with $3$ pens sold. Pens gave $\\$6$, leaving $\\$15$, so $3$ pads. Subtract the known item\'s revenue, then divide.' },
      { level: 'guide', text: 'Substitute $h = 40$: $120 + 2d = 180$.' },
      { level: 'reveal', text: '$2d = 60$, so $d = 30$ drinks.' },
    ],
    learningObjective: 'Model a two-item revenue situation and solve for one quantity.',
    topic: 'Two-variable models in context',
    explanation: [
      'Total revenue is price times quantity, summed over both items: $3h + 2d = 180$.',
      'The vendor sold $40$ hot dogs, so $3(40) = \\$120$ came from hot dogs.',
      'That leaves $180 - 120 = \\$60$ from drinks at $\\$2$ each: $d = 30$.',
    ],
    alternativeExplanations: [
      { title: 'Track the money, not the equation', steps: ['Hot dogs brought in $40 \\times \\$3 = \\$120$.', 'Drinks must account for the remaining $\\$180 - \\$120 = \\$60$.', 'At $\\$2$ apiece that is $30$ drinks. On a word problem this simple, arithmetic beats setting up algebra.'] },
    ],
    tags: ['word-problem', 'two-variable', 'revenue'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 30, unit: 3, order: 10, slug: 'sat-perpendicular-intercept',
    standard: 'SAT.ALG.3', difficulty: 3,
    prompt: 'Line $\\ell$ has equation $5x - 2y = 8$. Line $m$ is perpendicular to $\\ell$ and passes through the point $(5, 1)$. What is the $y$-intercept of line $m$?',
    answerType: 'numeric', primaryAnswer: '3', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the slope of $\\ell$ first, then take the negative reciprocal.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easier line: $\\ell$ is $y = 2x$, so $m$ has slope $-\\tfrac{1}{2}$. Through $(2, 3)$: $3 = -1 + b$, so $b = 4$. Same three moves — convert, flip-and-negate, substitute.' },
      { level: 'guide', text: '$\\ell$ has slope $\\tfrac{5}{2}$, so $m$ has slope $-\\tfrac{2}{5}$.' },
      { level: 'reveal', text: 'Substitute $(5, 1)$: $1 = -\\tfrac{2}{5}(5) + b = -2 + b$, so $b = 3$.' },
    ],
    learningObjective: 'Chain the perpendicular condition with point substitution.',
    topic: 'Perpendicular lines',
    explanation: [
      'Rewrite $\\ell$: $-2y = -5x + 8$, so $y = \\tfrac{5}{2}x - 4$ and its slope is $\\tfrac{5}{2}$.',
      'Perpendicular slope is the negative reciprocal: $-\\tfrac{2}{5}$.',
      'Substitute $(5, 1)$ into $y = -\\tfrac{2}{5}x + b$: $1 = -2 + b$, so $b = 3$.',
    ],
    alternativeExplanations: [
      { title: 'Three separate places to lose this question', steps: ['First, dividing by $-2$ and forgetting to flip both signs — the slope of $\\ell$ is $+\\tfrac{5}{2}$, not $-\\tfrac{5}{2}$.', 'Second, flipping without negating for the perpendicular slope.', 'Third, stopping at the equation instead of reading off the intercept. Naming the three checkpoints as you go is how you keep a multi-step question clean.'] },
    ],
    tags: ['perpendicular', 'multi-step', 'y-intercept'], estimatedSeconds: 90,
  },

  // ═══════════════ UNIT 4 — Systems of Two Linear Equations ═══════════════
  {
    domain: 'SAT', num: 31, unit: 4, order: 1, slug: 'sat-system-add-eliminate',
    standard: 'SAT.ALG.4', difficulty: 1,
    prompt: 'If $x + y = 10$ and $x - y = 4$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '7', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $y$ terms are already opposites. What happens if you add the equations?' },
      { level: 'guide', text: 'Adding gives $2x = 14$.' },
      { level: 'reveal', text: '$x = 7$.' },
    ],
    learningObjective: 'Solve a system by elimination when a variable already cancels.',
    topic: 'Elimination',
    explanation: [
      'Add the two equations term by term: $(x + y) + (x - y) = 10 + 4$.',
      'The $y$ terms cancel: $2x = 14$.',
      '$x = 7$ (and then $y = 3$).',
    ],
    alternativeExplanations: [
      { title: 'Look for the cancellation before choosing a method', steps: ['Whenever a variable appears with equal-and-opposite coefficients, adding is the fastest possible move.', 'Substitution would work here too, but it takes three steps instead of one.', 'Scanning for a ready-made cancellation is the first thing to do on any system question.'] },
    ],
    tags: ['system', 'elimination'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 32, unit: 4, order: 2, slug: 'sat-system-substitution',
    standard: 'SAT.ALG.4', difficulty: 1,
    prompt: 'If $y = 2x$ and $3x + y = 20$, what is the value of $y$?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'One equation already gives $y$ in terms of $x$ — substitute it into the other.' },
      { level: 'guide', text: '$3x + 2x = 20$, so $5x = 20$.' },
      { level: 'reveal', text: '$x = 4$, so $y = 2(4) = 8$.' },
    ],
    learningObjective: 'Solve a system by substitution when one variable is isolated.',
    topic: 'Substitution',
    explanation: [
      'Replace $y$ with $2x$ in the second equation: $3x + 2x = 20$.',
      'That gives $5x = 20$, so $x = 4$.',
      'The question asks for $y$, so finish: $y = 2(4) = 8$.',
    ],
    alternativeExplanations: [
      { title: 'Do not stop at x', steps: ['Solving gives $x = 4$ first, and $4$ will be one of the answer choices.', 'The question asked for $y$, not $x$ — this is the single most common way to lose a system question.', 'Circle the requested variable before you start solving.'] },
    ],
    tags: ['system', 'substitution'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 33, unit: 4, order: 3, slug: 'sat-system-sum-xy',
    standard: 'SAT.ALG.4', difficulty: 2,
    prompt: 'If $3x + 2y = 16$ and $x - 2y = 0$, what is the value of $x + y$?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $2y$ terms are opposites — add the equations.' },
      { level: 'guide', text: 'Adding gives $4x = 16$, so $x = 4$.' },
      { level: 'reveal', text: 'Then $4 - 2y = 0$ gives $y = 2$, so $x + y = 6$.' },
    ],
    learningObjective: 'Solve a system and evaluate a requested combination of the variables.',
    topic: 'Elimination',
    explanation: [
      'Add the equations: $(3x + 2y) + (x - 2y) = 16 + 0$, so $4x = 16$ and $x = 4$.',
      'Substitute into the second equation: $4 - 2y = 0$, so $y = 2$.',
      'The question asks for $x + y = 4 + 2 = 6$.',
    ],
    alternativeExplanations: [
      { title: 'Check both equations before committing', steps: ['With $x = 4$ and $y = 2$: $3(4) + 2(2) = 16$ ✓ and $4 - 2(2) = 0$ ✓.', 'A solution must satisfy *both* equations; verifying only one is how a substitution error survives.', 'The check costs about ten seconds and catches nearly every algebra slip.'] },
    ],
    tags: ['system', 'elimination', 'combination'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 34, unit: 4, order: 4, slug: 'sat-system-infinite',
    standard: 'SAT.ALG.4', difficulty: 2,
    prompt: 'How many solutions does the system $2x + 3y = 12$ and $4x + 6y = 24$ have?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Exactly one', correct: false },
      { id: 'B', label: 'Exactly two', correct: false },
      { id: 'C', label: 'No solutions', correct: false },
      { id: 'D', label: 'Infinitely many', correct: true },
    ],
    primaryAnswer: 'D', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Compare the two equations. Is one a multiple of the other?' },
      { level: 'guide', text: 'Multiplying the first equation by $2$ gives exactly the second.' },
      { level: 'reveal', text: 'They are the same line, so every point on it is a solution: infinitely many.' },
    ],
    learningObjective: 'Recognize a dependent system from proportional coefficients.',
    topic: 'Number of solutions',
    explanation: [
      'Multiply the first equation by $2$: $4x + 6y = 24$ — identical to the second.',
      'Two identical equations describe the same line, so every point on that line satisfies both.',
      'The system has infinitely many solutions.',
    ],
    alternativeExplanations: [
      { title: 'Check the ratios', steps: ['Compare $\\dfrac{4}{2}$, $\\dfrac{6}{3}$, and $\\dfrac{24}{12}$ — all equal $2$.', 'All three ratios equal means the same line: infinitely many solutions. All three equal *except* the constant means parallel lines: no solutions.', 'This ratio check answers every "how many solutions" question in about ten seconds, without solving anything.'] },
    ],
    tags: ['system', 'number-of-solutions', 'dependent'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 35, unit: 4, order: 5, slug: 'sat-system-no-solution',
    standard: 'SAT.ALG.4', difficulty: 2,
    prompt: 'How many solutions does the system $2x + 3y = 12$ and $4x + 6y = 18$ have?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Exactly one', correct: false },
      { id: 'B', label: 'No solutions', correct: true },
      { id: 'C', label: 'Exactly two', correct: false },
      { id: 'D', label: 'Infinitely many', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Double the first equation and compare it with the second.' },
      { level: 'guide', text: 'Doubling gives $4x + 6y = 24$, but the second equation says $18$.' },
      { level: 'reveal', text: 'Same left side, different right side — parallel lines, so no solutions.' },
    ],
    learningObjective: 'Recognize an inconsistent system from proportional coefficients with a mismatched constant.',
    topic: 'Number of solutions',
    explanation: [
      'Multiply the first equation by $2$: $4x + 6y = 24$.',
      'The second equation says the same expression equals $18$. It cannot be both $24$ and $18$.',
      'The lines have the same slope but different intercepts — they are parallel and never meet, so there is no solution.',
    ],
    alternativeExplanations: [
      { title: 'Contrast with the previous question', steps: ['These two questions have identical left sides; only the constant differs.', 'Matching constants means one line drawn twice — infinitely many solutions. Mismatched constants mean two parallel lines — none.', 'The coefficients decide *whether* the lines are parallel; the constant decides whether they are the same line.'] },
    ],
    tags: ['system', 'number-of-solutions', 'inconsistent'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 36, unit: 4, order: 6, slug: 'sat-ticket-prices',
    standard: 'SAT.ALG.4', difficulty: 2,
    prompt: 'At a theater, $3$ adult tickets and $2$ child tickets cost $\\$34$, while $2$ adult tickets and $5$ child tickets cost $\\$41$. What is the price, in dollars, of one adult ticket?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Let $a$ be the adult price and $c$ the child price, then write both sentences as equations.' },
      { level: 'guide', text: '$3a + 2c = 34$ and $2a + 5c = 41$. Scale them so one variable cancels.' },
      { level: 'reveal', text: 'Multiply the first by $5$ and the second by $2$: $15a + 10c = 170$ and $4a + 10c = 82$. Subtracting gives $11a = 88$, so $a = 8$.' },
    ],
    learningObjective: 'Translate a two-item pricing situation into a system and solve it.',
    topic: 'Systems in context',
    explanation: [
      'Let $a$ = adult price and $c$ = child price. Then $3a + 2c = 34$ and $2a + 5c = 41$.',
      'To eliminate $c$, scale to a common coefficient of $10$: multiply the first by $5$ ($15a + 10c = 170$) and the second by $2$ ($4a + 10c = 82$).',
      'Subtract: $11a = 88$, so $a = \\$8$. (Then $c = \\$5$.)',
    ],
    alternativeExplanations: [
      { title: 'Backsolve from the choices', steps: ['If the choices are prices, test one. Suppose $a = 8$: the first equation gives $24 + 2c = 34$, so $c = 5$.', 'Check that pair in the second equation: $2(8) + 5(5) = 16 + 25 = 41$ ✓', 'One substitution and one check — often faster than scaling two equations, and much harder to get wrong.'] },
    ],
    tags: ['system', 'word-problem', 'pricing'], estimatedSeconds: 90,
  },
  {
    domain: 'SAT', num: 37, unit: 4, order: 7, slug: 'sat-system-parallel-k',
    standard: 'SAT.ALG.4', difficulty: 3,
    prompt: 'The system $kx + 3y = 9$ and $2x + y = 5$ has no solution. What is the value of $k$?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'No solution means the lines are parallel — equal slopes.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try it on a known pair: $y = 3x + 1$ and $y = 3x + 7$ never meet, because the slopes match and the intercepts do not. Setting the two slopes equal is the whole technique.' },
      { level: 'guide', text: 'The first line has slope $-\\dfrac{k}{3}$ and the second has slope $-2$.' },
      { level: 'reveal', text: 'Set them equal: $-\\dfrac{k}{3} = -2$, so $k = 6$.' },
    ],
    learningObjective: 'Find the parameter that makes a system inconsistent.',
    topic: 'Number of solutions',
    explanation: [
      'For $Ax + By = C$ the slope is $-A/B$. The first line has slope $-k/3$; the second has slope $-2/1 = -2$.',
      'Parallel lines have equal slopes: $-\\dfrac{k}{3} = -2$, so $k = 6$.',
      'Check that they are genuinely parallel rather than identical: with $k = 6$ the first is $6x + 3y = 9$, or $2x + y = 3$ — same slope as $2x + y = 5$ but a different constant, so they never meet ✓',
    ],
    alternativeExplanations: [
      { title: 'Scale to match, then compare', steps: ['Multiply the second equation by $3$: $6x + 3y = 15$.', 'For no solution the $x$ and $y$ coefficients must match the first equation while the constants differ.', 'Matching $6x$ requires $k = 6$, and the constants $9$ and $15$ do differ — confirming no solution rather than infinitely many.'] },
    ],
    tags: ['system', 'parameter', 'parallel'], estimatedSeconds: 85,
  },
  {
    domain: 'SAT', num: 38, unit: 4, order: 8, slug: 'sat-system-expression-value',
    standard: 'SAT.ALG.4', difficulty: 3,
    prompt: 'If $x + 2y = 11$ and $3x - y = 5$, what is the value of $2x - y$?',
    answerType: 'numeric', primaryAnswer: '2', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Solve the system, then build the requested expression.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a smaller system: $x + y = 5$ and $x - y = 1$ give $x = 3$, $y = 2$, so $2x - y = 4$. Solve completely first, then build whatever combination the question asks for.' },
      { level: 'guide', text: 'From the second equation, $y = 3x - 5$. Substitute into the first.' },
      { level: 'reveal', text: '$x + 2(3x - 5) = 11$ gives $7x = 21$, so $x = 3$ and $y = 4$. Then $2(3) - 4 = 2$.' },
    ],
    learningObjective: 'Solve a system and evaluate a compound expression.',
    topic: 'Systems and expressions',
    explanation: [
      'Isolate $y$ in the second equation: $y = 3x - 5$.',
      'Substitute into the first: $x + 2(3x - 5) = 11$, so $x + 6x - 10 = 11$ and $7x = 21$, giving $x = 3$.',
      'Then $y = 3(3) - 5 = 4$, and $2x - y = 6 - 4 = 2$.',
    ],
    alternativeExplanations: [
      { title: 'The trap answers', steps: ['$x = 3$ and $y = 4$ will both appear among the choices, as will $x + y = 7$.', 'The question asks for $2x - y$ — a quantity you only reach by doing one more step after solving.', 'Writing the requested expression at the top of your scratch work keeps you from stopping one step early.'] },
    ],
    tags: ['system', 'substitution', 'expression'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 39, unit: 4, order: 9, slug: 'sat-coins-system',
    standard: 'SAT.ALG.4', difficulty: 3,
    prompt: 'A jar contains only dimes and quarters. There are $30$ coins in all, worth $\\$5.70$ total. How many quarters are in the jar?',
    answerType: 'numeric', primaryAnswer: '18', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Write one equation for the *count* of coins and one for their *value*.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try fewer coins: $4$ coins of nickels and dimes worth $\\$0.35$. All nickels would be $\\$0.20$; the $\\$0.15$ excess divided by the $\\$0.05$ swap value gives $3$ dimes. Same assume-then-adjust logic.' },
      { level: 'guide', text: '$d + q = 30$ and $0.10d + 0.25q = 5.70$. Substitute $d = 30 - q$.' },
      { level: 'reveal', text: '$0.10(30 - q) + 0.25q = 5.70$ gives $3 + 0.15q = 5.70$, so $q = 18$.' },
    ],
    learningObjective: 'Model a count-and-value situation as a system.',
    topic: 'Systems in context',
    explanation: [
      'Let $d$ = dimes and $q$ = quarters. Count: $d + q = 30$. Value: $0.10d + 0.25q = 5.70$.',
      'Substitute $d = 30 - q$: $0.10(30 - q) + 0.25q = 5.70$, so $3 - 0.10q + 0.25q = 5.70$.',
      '$0.15q = 2.70$, so $q = 18$ quarters (and $12$ dimes). Check: $12(0.10) + 18(0.25) = 1.20 + 4.50 = \\$5.70$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Start from an all-dimes jar', steps: ['If all $30$ coins were dimes the jar would hold $\\$3.00$ — but it holds $\\$5.70$, an excess of $\\$2.70$.', 'Swapping one dime for one quarter adds $\\$0.15$ to the total.', '$\\$2.70 \\div \\$0.15 = 18$ swaps, so there are $18$ quarters. This "assume then adjust" method skips the system entirely.'] },
    ],
    tags: ['system', 'word-problem', 'coins'], estimatedSeconds: 95,
  },
  {
    domain: 'SAT', num: 40, unit: 4, order: 10, slug: 'sat-system-dependent-a',
    standard: 'SAT.ALG.4', difficulty: 3,
    prompt: 'The system $ax + 6y = 18$ and $2x + 3y = 9$ has infinitely many solutions. What is the value of $a$?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Infinitely many solutions means the two equations describe the same line.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an obvious pair: $2x + 2y = 6$ and $x + y = 3$ are the same line, since doubling the second gives the first. Find the scale factor from a matching term, then apply it everywhere.' },
      { level: 'guide', text: 'Double the second equation: $4x + 6y = 18$. Compare it with the first.' },
      { level: 'reveal', text: 'The $y$ terms and constants already match, so $a = 4$.' },
    ],
    learningObjective: 'Find the parameter that makes a system dependent.',
    topic: 'Number of solutions',
    explanation: [
      'For infinitely many solutions the equations must be multiples of one another.',
      'The first equation has $6y$ and the second has $3y$, so the scale factor is $2$. Multiply the second by $2$: $4x + 6y = 18$.',
      'That matches the first equation exactly when $a = 4$ — and the constants already agree at $18$, confirming the same line rather than parallel ones.',
    ],
    alternativeExplanations: [
      { title: 'Set all three ratios equal', steps: ['The condition for one identical line is $\\dfrac{a}{2} = \\dfrac{6}{3} = \\dfrac{18}{9}$.', 'The last two ratios both equal $2$, so $\\dfrac{a}{2} = 2$ and $a = 4$.', 'If the constant ratio had *not* matched, the same $a$ would instead have produced no solution — always check all three.'] },
    ],
    tags: ['system', 'parameter', 'dependent'], estimatedSeconds: 85,
  },

  // ═══════════════ UNIT 5 — Linear Inequalities and Systems ═══════════════
  {
    domain: 'SAT', num: 41, unit: 5, order: 1, slug: 'sat-basic-inequality',
    standard: 'SAT.ALG.5', difficulty: 1,
    prompt: 'Which of the following describes all solutions to $3x - 5 > 10$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$x > 5$', correct: true },
      { id: 'B', label: '$x < 5$', correct: false },
      { id: 'C', label: '$x > 15$', correct: false },
      { id: 'D', label: '$x > \\tfrac{5}{3}$', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Solve it exactly as you would an equation — you are dividing by a positive number, so the sign will not flip.' },
      { level: 'guide', text: 'Add $5$: $3x > 15$.' },
      { level: 'reveal', text: 'Divide by $3$: $x > 5$.' },
    ],
    learningObjective: 'Solve a two-step linear inequality.',
    topic: 'Linear inequalities',
    explanation: [
      'Add $5$ to both sides: $3x > 15$.',
      'Divide both sides by $3$. Since $3$ is positive, the direction of the inequality does not change: $x > 5$.',
      'Check with $x = 6$: $3(6) - 5 = 13 > 10$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Test a value to confirm the direction', steps: ['If you are unsure whether the answer is $x > 5$ or $x < 5$, test one number from each side.', '$x = 6$ gives $13 > 10$ ✓, and $x = 4$ gives $7 > 10$ ✗.', 'One test settles the direction, and it takes five seconds.'] },
    ],
    tags: ['inequality', 'solve'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 42, unit: 5, order: 2, slug: 'sat-inequality-flip',
    standard: 'SAT.ALG.5', difficulty: 1,
    prompt: 'Which of the following describes all solutions to $-2x \\ge 8$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$x \\ge -4$', correct: false },
      { id: 'B', label: '$x \\le -4$', correct: true },
      { id: 'C', label: '$x \\ge 4$', correct: false },
      { id: 'D', label: '$x \\le 4$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'You are about to divide by a negative number. That does something to the inequality sign.' },
      { level: 'guide', text: 'Dividing both sides by $-2$ reverses the direction.' },
      { level: 'reveal', text: '$x \\le -4$.' },
    ],
    learningObjective: 'Apply the sign-flip rule when dividing an inequality by a negative.',
    topic: 'Linear inequalities',
    explanation: [
      'Divide both sides by $-2$. Dividing by a negative reverses the inequality: $x \\le -4$.',
      'Check with $x = -5$: $-2(-5) = 10 \\ge 8$ ✓',
      'Check with $x = 0$: $-2(0) = 0 \\ge 8$ ✗ — confirming that values above $-4$ fail.',
    ],
    alternativeExplanations: [
      { title: 'Avoid the flip entirely', steps: ['Add $2x$ to both sides instead: $0 \\ge 8 + 2x$.', 'Then subtract $8$: $-8 \\ge 2x$, and divide by the *positive* $2$: $-4 \\ge x$, which is $x \\le -4$.', 'Keeping the variable coefficient positive means you never have to remember the flip rule at all.'] },
    ],
    tags: ['inequality', 'sign-flip'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 43, unit: 5, order: 3, slug: 'sat-inequality-multistep',
    standard: 'SAT.ALG.5', difficulty: 2,
    prompt: 'Which of the following describes all solutions to $4 - 3x < 19$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$x < -5$', correct: false },
      { id: 'B', label: '$x > -5$', correct: true },
      { id: 'C', label: '$x < 5$', correct: false },
      { id: 'D', label: '$x > 5$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Subtract $4$ from both sides first.' },
      { level: 'guide', text: '$-3x < 15$. Now divide by $-3$ — and remember what that does.' },
      { level: 'reveal', text: 'Dividing by $-3$ flips the sign: $x > -5$.' },
    ],
    learningObjective: 'Solve a multi-step inequality requiring a sign flip.',
    topic: 'Linear inequalities',
    explanation: [
      'Subtract $4$ from both sides: $-3x < 15$.',
      'Divide by $-3$ and reverse the inequality: $x > -5$.',
      'Check with $x = 0$: $4 - 0 = 4 < 19$ ✓, and $0$ is indeed greater than $-5$.',
    ],
    alternativeExplanations: [
      { title: 'Use x = 0 as a free test', steps: ['Whenever $0$ is not a boundary value, it is the cheapest possible test point.', 'Here $x = 0$ satisfies the original inequality, so the correct answer must include $0$.', 'That immediately kills A ($x < -5$) and C ($x < 5$ includes 0 — keep), then the boundary $-5$ vs $5$ separates B from C.'] },
    ],
    tags: ['inequality', 'sign-flip', 'test-point'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 44, unit: 5, order: 4, slug: 'sat-weight-limit-boxes',
    standard: 'SAT.ALG.5', difficulty: 2,
    prompt: 'A cart already holds $7$ pounds of equipment and can carry a total of no more than $40$ pounds. Each box loaded onto it weighs $3$ pounds. What is the greatest number of boxes that can be loaded onto the cart?',
    answerType: 'numeric', primaryAnswer: '11', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"No more than" means $\\le$. Build $3b + 7 \\le 40$.' },
      { level: 'guide', text: 'Subtract $7$: $3b \\le 33$.' },
      { level: 'reveal', text: '$b \\le 11$, so the greatest whole number of boxes is $11$.' },
    ],
    learningObjective: 'Translate a capacity constraint into an inequality and interpret the result.',
    topic: 'Inequalities in context',
    explanation: [
      '"No more than $40$" translates to $\\le 40$. The total weight is $3b + 7$.',
      'So $3b + 7 \\le 40$, giving $3b \\le 33$ and $b \\le 11$.',
      'Boxes come in whole numbers, so the maximum is $11$. Check: $3(11) + 7 = 40$ ✓, exactly at the limit.',
    ],
    alternativeExplanations: [
      { title: 'Reason with the remaining capacity', steps: ['Of the $40$-pound limit, $7$ pounds is already used, leaving $33$ pounds.', '$33 \\div 3 = 11$ boxes exactly.', 'When the division comes out even, the boundary value is achievable — "no more than" allows equality, so $11$ works rather than $10$.'] },
    ],
    tags: ['inequality', 'word-problem', 'capacity'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 45, unit: 5, order: 5, slug: 'sat-system-inequality-point',
    standard: 'SAT.ALG.5', difficulty: 2,
    prompt: 'Which ordered pair $(x, y)$ is a solution to the system $y > 2x - 3$ and $y < -x + 6$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$(4, 3)$', correct: false },
      { id: 'B', label: '$(1, 2)$', correct: true },
      { id: 'C', label: '$(0, -5)$', correct: false },
      { id: 'D', label: '$(5, 4)$', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Test each pair in both inequalities. It must satisfy both.' },
      { level: 'guide', text: 'For $(1, 2)$: is $2 > 2(1) - 3 = -1$? And is $2 < -1 + 6 = 5$?' },
      { level: 'reveal', text: 'Both hold, so $(1, 2)$ is the solution.' },
    ],
    learningObjective: 'Verify a point against a system of linear inequalities.',
    topic: 'Systems of inequalities',
    explanation: [
      'A solution must satisfy every inequality in the system.',
      '$(1, 2)$: first, $2 > 2(1) - 3 = -1$ ✓; second, $2 < -1 + 6 = 5$ ✓. Both hold.',
      'Check the others: $(4, 3)$ fails the first ($3 > 5$ is false). $(0, -5)$ fails the first ($-5 > -3$ is false). $(5, 4)$ fails the second ($4 < 1$ is false).',
    ],
    alternativeExplanations: [
      { title: 'Let Desmos shade it', steps: ['Type $y > 2x - 3$ and $y < -x + 6$ directly into Desmos — it shades each region.', 'The solution set is the overlap, where both shadings appear.', 'Then plot the four candidate points and see which one lands inside. This turns an algebra check into a glance.'] },
    ],
    tags: ['system-of-inequalities', 'test-point', 'desmos'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 46, unit: 5, order: 6, slug: 'sat-budget-system-setup',
    standard: 'SAT.ALG.5', difficulty: 2,
    prompt: 'A shopper buys $s$ shirts costing $\\$9$ each and $p$ pairs of pants costing $\\$15$ each. She spends no more than $\\$120$ and buys at least $4$ shirts. Which system represents this situation?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$9s + 15p \\le 120$ and $s \\ge 4$', correct: true },
      { id: 'B', label: '$9s + 15p \\ge 120$ and $s \\le 4$', correct: false },
      { id: 'C', label: '$9s + 15p < 120$ and $s > 4$', correct: false },
      { id: 'D', label: '$15s + 9p \\le 120$ and $s \\ge 4$', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Translate each phrase separately: "no more than" and "at least" are different symbols.' },
      { level: 'guide', text: '"No more than $\\$120$" is $\\le 120$; "at least $4$ shirts" is $s \\ge 4$.' },
      { level: 'reveal', text: 'And the shirts cost $\\$9$ each, so the shirt term is $9s$: choice A.' },
    ],
    learningObjective: 'Translate constraint language into a system of inequalities.',
    topic: 'Modeling with inequalities',
    explanation: [
      'Total spending is $9s + 15p$, and "no more than $\\$120$" allows equality: $9s + 15p \\le 120$.',
      '"At least $4$ shirts" also allows equality: $s \\ge 4$.',
      'Choice D swaps the prices onto the wrong items; choice C uses strict inequalities, which would wrongly exclude spending exactly $\\$120$ or buying exactly $4$ shirts.',
    ],
    alternativeExplanations: [
      { title: 'A translation table worth memorizing', steps: ['"At least", "no less than", "minimum of" → $\\ge$. "At most", "no more than", "maximum of" → $\\le$.', '"More than", "exceeds", "over" → $>$. "Less than", "under", "below" → $<$.', 'The words containing "no" or "at" almost always permit equality; the bare comparison words do not.'] },
    ],
    tags: ['system-of-inequalities', 'modeling', 'translate'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 47, unit: 5, order: 7, slug: 'sat-compound-inequality',
    standard: 'SAT.ALG.5', difficulty: 3,
    prompt: 'If $5 \\le 2x + 1 \\le 13$, what is the greatest possible value of $x$?',
    answerType: 'numeric', primaryAnswer: '6', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Whatever you do, do it to all three parts at once.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a shorter one: $3 \\le x + 1 \\le 7$. Subtract $1$ from all three parts to get $2 \\le x \\le 6$. Whatever you do, do it to every part at once.' },
      { level: 'guide', text: 'Subtract $1$ throughout: $4 \\le 2x \\le 12$.' },
      { level: 'reveal', text: 'Divide by $2$ throughout: $2 \\le x \\le 6$, so the greatest value is $6$.' },
    ],
    learningObjective: 'Solve a compound inequality and read off an extreme value.',
    topic: 'Compound inequalities',
    explanation: [
      'Subtract $1$ from all three parts: $4 \\le 2x \\le 12$.',
      'Divide all three parts by $2$: $2 \\le x \\le 6$.',
      'The inequality is inclusive, so $x = 6$ is allowed and is the greatest possible value. Check: $2(6) + 1 = 13 \\le 13$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Work only the end you need', steps: ['The question asks for the *greatest* $x$, which comes from the upper bound alone.', 'Solve just $2x + 1 \\le 13$: $2x \\le 12$, so $x \\le 6$.', 'Half the work when only one end is requested — but read carefully, because "greatest" and "least" look alike under time pressure.'] },
    ],
    tags: ['compound-inequality', 'bounds'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 48, unit: 5, order: 8, slug: 'sat-count-integers-inequality',
    standard: 'SAT.ALG.5', difficulty: 3,
    prompt: 'How many integer values of $x$ satisfy $-3 < \\dfrac{x - 4}{2} \\le 1$?',
    answerType: 'numeric', primaryAnswer: '8', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Clear the denominator by multiplying all three parts by $2$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try counting on a small range: $0 < x \\le 3$ holds for $x = 1, 2, 3$ — three integers. The strict end excludes its boundary, the inclusive end keeps it.' },
      { level: 'guide', text: '$-6 < x - 4 \\le 2$, then add $4$ throughout.' },
      { level: 'reveal', text: '$-2 < x \\le 6$, so $x$ runs from $-1$ to $6$: that is $8$ integers.' },
    ],
    learningObjective: 'Solve a compound inequality and count the integers in the solution set.',
    topic: 'Compound inequalities',
    explanation: [
      'Multiply all three parts by $2$: $-6 < x - 4 \\le 2$.',
      'Add $4$ to all three parts: $-2 < x \\le 6$.',
      'The left bound is strict, so $-2$ is excluded and the smallest integer is $-1$. The right bound is inclusive, so $6$ counts. The integers $-1, 0, 1, 2, 3, 4, 5, 6$ number $8$.',
    ],
    alternativeExplanations: [
      { title: 'Counting integers without slipping', steps: ['From $a$ to $b$ inclusive there are $b - a + 1$ integers — the "+1" is what people forget.', 'Here the range is $-1$ to $6$, so $6 - (-1) + 1 = 8$.', 'Listing them out is also fine when the range is short; it is the safest check on a fencepost error.'] },
    ],
    tags: ['compound-inequality', 'counting', 'integers'], estimatedSeconds: 85,
  },
  {
    domain: 'SAT', num: 49, unit: 5, order: 9, slug: 'sat-bridge-weight-limit',
    standard: 'SAT.ALG.5', difficulty: 3,
    prompt: 'An empty delivery van weighs $3{,}200$ pounds. It is loaded with boxes weighing $45$ pounds each, and it must cross a bridge with a weight limit of $5{,}000$ pounds. What is the maximum number of boxes the van can carry across the bridge?',
    answerType: 'numeric', primaryAnswer: '40', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Total weight is the van plus the boxes, and it must stay at or below the limit.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try smaller numbers: a $10$-pound cart with a $25$-pound limit, carrying $5$-pound boxes. That leaves $15$ pounds, so $3$ boxes. Subtract the fixed weight, then divide by the per-item weight.' },
      { level: 'guide', text: '$3200 + 45b \\le 5000$, so $45b \\le 1800$.' },
      { level: 'reveal', text: '$b \\le 40$, so $40$ boxes.' },
    ],
    learningObjective: 'Solve a real-world capacity inequality with a whole-number answer.',
    topic: 'Inequalities in context',
    explanation: [
      'The loaded weight is $3200 + 45b$, and it must satisfy $3200 + 45b \\le 5000$.',
      'Subtract: $45b \\le 1800$.',
      'Divide: $b \\le 40$. Since $1800 \\div 45 = 40$ exactly, the van can carry $40$ boxes and hit the limit precisely.',
    ],
    alternativeExplanations: [
      { title: 'When to round down, and when not to', steps: ['If the division had come out to $40.7$, the answer would be $40$ — you cannot load a fraction of a box.', 'Here it divides evenly, and "$\\le$" permits equality, so $40$ is achievable rather than one too many.', 'The rule: for a maximum with $\\le$, take the floor of the quotient; an exact quotient is itself the answer.'] },
    ],
    tags: ['inequality', 'word-problem', 'maximum'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 50, unit: 5, order: 10, slug: 'sat-not-a-solution',
    standard: 'SAT.ALG.5', difficulty: 3,
    prompt: 'Which value of $x$ is **not** a solution to $7 - 2x \\ge 1$?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$-2$', correct: false },
      { id: 'B', label: '$0$', correct: false },
      { id: 'C', label: '$3$', correct: false },
      { id: 'D', label: '$4$', correct: true },
    ],
    primaryAnswer: 'D', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Solve the inequality first, then see which choice falls outside the solution set.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a simpler one: which value fails $5 - x \\ge 2$? Solving gives $x \\le 3$, so $x = 4$ fails. Solve first, then test the choices against the solution set.' },
      { level: 'guide', text: '$-2x \\ge -6$; dividing by $-2$ flips it to $x \\le 3$.' },
      { level: 'reveal', text: 'Every choice at or below $3$ works, so the one that fails is $4$.' },
    ],
    learningObjective: 'Solve an inequality and identify a value outside the solution set.',
    topic: 'Linear inequalities',
    explanation: [
      'Subtract $7$: $-2x \\ge -6$.',
      'Divide by $-2$ and flip the inequality: $x \\le 3$.',
      'Choices A, B, and C are all at most $3$ and therefore work. Choice D, $x = 4$, is greater than $3$ and fails: $7 - 2(4) = -1$, which is not $\\ge 1$.',
    ],
    alternativeExplanations: [
      { title: 'Skip solving and just substitute', steps: ['With only four numbers to check, plugging in is often faster than solving.', '$x = -2$ gives $11$ ✓; $x = 0$ gives $7$ ✓; $x = 3$ gives $1 \\ge 1$ ✓; $x = 4$ gives $-1$ ✗.', 'This also sidesteps the sign-flip rule entirely — the single most common error on inequality questions.'] },
    ],
    tags: ['inequality', 'not-a-solution', 'substitution'], estimatedSeconds: 70,
  },
];
