import type { SeedProblem } from './types';

// SAT — Problem-Solving and Data Analysis (blueprint area PSDA, ~15% of the
// Math section). Units 11-14, problems 101-140.
//
// This area is more a reading test than a math test: the arithmetic is rarely
// hard, but the setup — which total, which row, which base for the percent —
// is where the points are won and lost. The alternate explanations lean on
// that: they name the misread the question is built to catch.

export const problemsSATpsda: SeedProblem[] = [
  // ═══════════ UNIT 11 — Ratios, Rates, Proportions, and Units ═══════════
  {
    domain: 'SAT', num: 101, unit: 11, order: 1, slug: 'sat-solve-proportion',
    standard: 'SAT.PSDA.1', difficulty: 1,
    prompt: 'If $\\dfrac{3}{4} = \\dfrac{x}{20}$, what is the value of $x$?',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Cross-multiply, or notice how the denominator changed.' },
      { level: 'guide', text: '$4 \\times 5 = 20$, so the numerator scales by $5$ too.' },
      { level: 'reveal', text: '$3 \\times 5 = 15$.' },
    ],
    learningObjective: 'Solve a basic proportion.',
    topic: 'Proportions',
    explanation: [
      'Cross-multiply: $3 \\times 20 = 4x$, so $60 = 4x$ and $x = 15$.',
      'Or scale directly: the denominator went from $4$ to $20$, a factor of $5$.',
      'Applying the same factor to the numerator: $3 \\times 5 = 15$.',
    ],
    alternativeExplanations: [
      { title: 'Scaling beats cross-multiplying when it is clean', steps: ['Whenever one denominator divides evenly into the other, scaling is faster and involves no division.', 'Here $20 \\div 4 = 5$, so multiply the top by $5$.', 'Save cross-multiplication for the cases where the numbers do not cooperate.'] },
    ],
    tags: ['proportion', 'scaling'], estimatedSeconds: 35,
  },
  {
    domain: 'SAT', num: 102, unit: 11, order: 2, slug: 'sat-unit-rate-speed',
    standard: 'SAT.PSDA.1', difficulty: 1,
    prompt: 'A car travels $180$ miles in $3$ hours at a constant speed. What is its speed, in miles per hour?',
    answerType: 'numeric', primaryAnswer: '60', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Per hour" means divide by the number of hours.' },
      { level: 'guide', text: '$180 \\div 3$.' },
      { level: 'reveal', text: '$60$ miles per hour.' },
    ],
    learningObjective: 'Compute a unit rate from a total and a quantity.',
    topic: 'Unit rates',
    explanation: [
      'A rate "per hour" is the total distance divided by the total time.',
      '$180 \\div 3 = 60$ miles per hour.',
      'The units confirm the setup: miles ÷ hours gives miles per hour.',
    ],
    alternativeExplanations: [
      { title: 'Let the units tell you the operation', steps: ['You want an answer in miles/hour — a fraction with miles on top and hours on the bottom.', 'So write $\\dfrac{180 \\text{ miles}}{3 \\text{ hours}}$ and the operation is decided for you.', 'On any rate question, writing the target units first prevents dividing the wrong way round.'] },
    ],
    tags: ['unit-rate', 'speed'], estimatedSeconds: 35,
  },
  {
    domain: 'SAT', num: 103, unit: 11, order: 3, slug: 'sat-recipe-proportion',
    standard: 'SAT.PSDA.1', difficulty: 2,
    prompt: 'A recipe uses $2$ cups of flour to make $24$ cookies. At the same rate, how many cups of flour are needed to make $60$ cookies?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Set up a proportion with cups on top and cookies on the bottom in both fractions.' },
      { level: 'guide', text: '$\\dfrac{2}{24} = \\dfrac{c}{60}$.' },
      { level: 'reveal', text: '$24c = 120$, so $c = 5$ cups.' },
    ],
    learningObjective: 'Set up and solve a proportion in context.',
    topic: 'Proportions',
    explanation: [
      'Keep the units consistent: $\\dfrac{2 \\text{ cups}}{24 \\text{ cookies}} = \\dfrac{c \\text{ cups}}{60 \\text{ cookies}}$.',
      'Cross-multiply: $2(60) = 24c$, so $120 = 24c$.',
      '$c = 5$ cups.',
    ],
    alternativeExplanations: [
      { title: 'Find the rate per cookie first', steps: ['$2$ cups makes $24$ cookies, so one cookie takes $\\dfrac{2}{24} = \\dfrac{1}{12}$ cup.', '$60$ cookies then take $60 \\times \\dfrac{1}{12} = 5$ cups.', 'The unit-rate route takes one extra step but reads more naturally, and it makes the answer easy to sanity-check.'] },
    ],
    tags: ['proportion', 'word-problem', 'recipe'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 104, unit: 11, order: 4, slug: 'sat-scale-drawing',
    standard: 'SAT.PSDA.1', difficulty: 2,
    prompt: 'A scale drawing uses a scale of $1$ centimeter to $250$ centimeters. A wall measures $6$ centimeters on the drawing. What is the actual length of the wall, in meters?',
    answerType: 'numeric', primaryAnswer: '15', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'First find the actual length in centimeters, then convert.' },
      { level: 'guide', text: '$6 \\times 250 = 1500$ centimeters.' },
      { level: 'reveal', text: '$1500$ cm $\\div 100 = 15$ meters.' },
    ],
    learningObjective: 'Apply a scale factor and convert the result to the requested unit.',
    topic: 'Scale and units',
    explanation: [
      'Each drawing centimeter represents $250$ actual centimeters, so $6$ cm represents $6 \\times 250 = 1500$ cm.',
      'The question asks for meters: $1500 \\text{ cm} \\div 100 = 15$ meters.',
      'Skipping the conversion gives $1500$, which will be one of the answer choices.',
    ],
    alternativeExplanations: [
      { title: 'Two-step questions hide the second step', steps: ['The scale work and the unit conversion are separate tasks, and only the first one is obvious.', 'Underline the unit the question asks for — here, "in meters" — before computing anything.', 'On the SAT, a question that changes units mid-problem is doing so deliberately.'] },
    ],
    tags: ['scale', 'unit-conversion'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 105, unit: 11, order: 5, slug: 'sat-convert-mph-fps',
    standard: 'SAT.PSDA.1', difficulty: 2,
    prompt: 'A car travels at $60$ miles per hour. There are $5{,}280$ feet in a mile and $3{,}600$ seconds in an hour. What is the car\'s speed, in feet per second?',
    answerType: 'numeric', primaryAnswer: '88', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Chain the conversion factors so the unwanted units cancel.' },
      { level: 'guide', text: '$\\dfrac{60 \\text{ mi}}{1 \\text{ hr}} \\times \\dfrac{5280 \\text{ ft}}{1 \\text{ mi}} \\times \\dfrac{1 \\text{ hr}}{3600 \\text{ s}}$.' },
      { level: 'reveal', text: '$\\dfrac{60 \\times 5280}{3600} = 88$ feet per second.' },
    ],
    learningObjective: 'Chain unit conversions using dimensional analysis.',
    topic: 'Unit conversion',
    explanation: [
      'Write each conversion as a fraction arranged so the unwanted unit cancels diagonally.',
      '$\\dfrac{60 \\text{ mi}}{\\text{hr}} \\times \\dfrac{5280 \\text{ ft}}{1 \\text{ mi}} \\times \\dfrac{1 \\text{ hr}}{3600 \\text{ s}}$: miles cancel, hours cancel, leaving feet per second.',
      '$\\dfrac{60 \\times 5280}{3600} = \\dfrac{316800}{3600} = 88$ ft/s.',
    ],
    alternativeExplanations: [
      { title: 'Units are a free error check', steps: ['If the units left standing are not the ones the question asked for, you have flipped a factor.', 'That check catches the mistake *before* you do any arithmetic, which is when it is cheapest to fix.', 'Worth memorizing: $60$ mph is exactly $88$ ft/s. It shows up often enough to recognize.'] },
    ],
    tags: ['unit-conversion', 'dimensional-analysis'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 106, unit: 11, order: 6, slug: 'sat-machine-rate',
    standard: 'SAT.PSDA.1', difficulty: 2,
    prompt: 'Three identical machines working together produce $120$ parts in $4$ hours. At the same rate, how many parts will five of these machines produce in $6$ hours?',
    answerType: 'numeric', primaryAnswer: '300', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Find the output of one machine in one hour first.' },
      { level: 'guide', text: '$120$ parts came from $3 \\times 4 = 12$ machine-hours, so the rate is $10$ parts per machine-hour.' },
      { level: 'reveal', text: '$5$ machines for $6$ hours is $30$ machine-hours: $30 \\times 10 = 300$ parts.' },
    ],
    learningObjective: 'Solve a work-rate problem by reducing to a single-unit rate.',
    topic: 'Rates',
    explanation: [
      'Total effort is machines × hours: $3 \\times 4 = 12$ machine-hours produced $120$ parts.',
      'So one machine-hour produces $120 \\div 12 = 10$ parts.',
      'The new scenario is $5 \\times 6 = 30$ machine-hours, giving $30 \\times 10 = 300$ parts.',
    ],
    alternativeExplanations: [
      { title: 'Scale the two factors separately', steps: ['Going from $3$ machines to $5$ multiplies output by $\\tfrac{5}{3}$.', 'Going from $4$ hours to $6$ multiplies it by $\\tfrac{6}{4} = \\tfrac{3}{2}$.', '$120 \\times \\tfrac{5}{3} \\times \\tfrac{3}{2} = 300$. Both routes work; the machine-hour route is harder to get backwards.'] },
    ],
    tags: ['rate', 'work-problem'], estimatedSeconds: 85,
  },
  {
    domain: 'SAT', num: 107, unit: 11, order: 7, slug: 'sat-currency-conversion',
    standard: 'SAT.PSDA.1', difficulty: 3,
    prompt: 'On a certain day, $1$ US dollar is worth $1.25$ Canadian dollars. How many US dollars are equivalent to $400$ Canadian dollars?',
    answerType: 'numeric', primaryAnswer: '320', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Decide whether the answer should be larger or smaller than $400$ before computing.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easy rate: if $1$ USD $= 2$ CAD, then $10$ CAD is clearly $5$ USD — you divide. Decide bigger-or-smaller first, and the operation follows.' },
      { level: 'guide', text: 'A US dollar is worth more, so the US amount must be smaller — divide.' },
      { level: 'reveal', text: '$400 \\div 1.25 = 320$ US dollars.' },
    ],
    learningObjective: 'Convert between currencies, choosing the correct direction.',
    topic: 'Unit conversion',
    explanation: [
      'The relationship is $1 \\text{ USD} = 1.25 \\text{ CAD}$.',
      'Set up so Canadian dollars cancel: $400 \\text{ CAD} \\times \\dfrac{1 \\text{ USD}}{1.25 \\text{ CAD}} = 320$ USD.',
      'Multiplying instead would give $500$, which is the trap answer.',
    ],
    alternativeExplanations: [
      { title: 'Estimate the direction first', steps: ['One US dollar buys more than one Canadian dollar, so any pile of money is a *smaller* number when counted in US dollars.', 'That single sentence tells you to divide, before you touch the arithmetic.', 'On every conversion question, predicting bigger-or-smaller first eliminates the multiply/divide coin flip.'] },
    ],
    tags: ['unit-conversion', 'currency', 'direction'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 108, unit: 11, order: 8, slug: 'sat-map-distance',
    standard: 'SAT.PSDA.1', difficulty: 3,
    prompt: 'On a map, $2$ inches represents $25$ miles. Two cities are $7.5$ inches apart on the map. What is the actual distance between the cities, in miles?',
    answerType: 'numeric', primaryAnswer: '93.75', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.01,
    hints: [
      { level: 'nudge', text: 'Set up a proportion: inches over miles equals inches over miles.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a cleaner scale: $1$ inch to $10$ miles means $3$ inches is $30$ miles. Find what one inch represents, then multiply by the number of inches.' },
      { level: 'guide', text: '$\\dfrac{2}{25} = \\dfrac{7.5}{d}$.' },
      { level: 'reveal', text: '$2d = 187.5$, so $d = 93.75$ miles.' },
    ],
    learningObjective: 'Apply a map scale that is not a unit rate.',
    topic: 'Scale and proportions',
    explanation: [
      'Write the proportion with matching units in matching positions: $\\dfrac{2 \\text{ in}}{25 \\text{ mi}} = \\dfrac{7.5 \\text{ in}}{d \\text{ mi}}$.',
      'Cross-multiply: $2d = 25 \\times 7.5 = 187.5$.',
      '$d = 93.75$ miles.',
    ],
    alternativeExplanations: [
      { title: 'Convert to a per-inch rate', steps: ['$2$ inches is $25$ miles, so $1$ inch is $12.5$ miles.', '$7.5 \\times 12.5 = 93.75$ miles.', 'Finding the per-one rate first makes the final step a single multiplication, and the intermediate value is easy to sanity-check.'] },
    ],
    tags: ['scale', 'proportion', 'map'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 109, unit: 11, order: 9, slug: 'sat-density-mass',
    standard: 'SAT.PSDA.1', difficulty: 3,
    prompt: 'A metal has a density of $7.8$ grams per cubic centimeter. What is the mass, in grams, of a $250$ cubic centimeter block of this metal?',
    answerType: 'numeric', primaryAnswer: '1950', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Density is mass per unit volume, so mass is density times volume.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try round numbers: at $2$ g per cm³, a $10$ cm³ block weighs $20$ g — you multiply. Density times volume gives mass, and the cm³ units cancel to confirm it.' },
      { level: 'guide', text: '$7.8 \\times 250$.' },
      { level: 'reveal', text: '$1{,}950$ grams.' },
    ],
    learningObjective: 'Apply a density rate to compute a total.',
    topic: 'Rates',
    explanation: [
      'Density $= \\dfrac{\\text{mass}}{\\text{volume}}$, so mass $=$ density $\\times$ volume.',
      '$7.8 \\dfrac{\\text{g}}{\\text{cm}^3} \\times 250 \\text{ cm}^3 = 1950$ grams — the cubic centimeters cancel, leaving grams ✓',
      'Dividing instead would give about $32$, which is not a plausible mass for a block of metal.',
    ],
    alternativeExplanations: [
      { title: 'Estimate to check the magnitude', steps: ['$7.8$ is nearly $8$, and $8 \\times 250 = 2000$.', 'The exact answer of $1950$ sits just below that, exactly as expected.', 'A five-second estimate catches an order-of-magnitude error, which is the kind that costs a whole question.'] },
    ],
    tags: ['density', 'rate', 'estimation'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 110, unit: 11, order: 10, slug: 'sat-printer-time',
    standard: 'SAT.PSDA.1', difficulty: 3,
    prompt: 'A printer produces pages at a constant rate of $18$ pages per minute. How many minutes does it take to print $693$ pages?',
    answerType: 'numeric', primaryAnswer: '38.5', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.01,
    alternativeAnswers: ['77/2'],
    hints: [
      { level: 'nudge', text: 'You want minutes, so divide pages by pages-per-minute.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try easy numbers: at $10$ pages per minute, $50$ pages takes $50 \\div 10 = 5$ minutes. Pages divided by pages-per-minute leaves minutes.' },
      { level: 'guide', text: '$693 \\div 18$.' },
      { level: 'reveal', text: '$38.5$ minutes.' },
    ],
    learningObjective: 'Invert a rate to find elapsed time.',
    topic: 'Rates',
    explanation: [
      'Time $= \\dfrac{\\text{total pages}}{\\text{pages per minute}} = \\dfrac{693}{18}$.',
      '$18 \\times 38 = 684$, leaving $9$ pages, which is half a minute more.',
      'So the time is $38.5$ minutes.',
    ],
    alternativeExplanations: [
      { title: 'Let the units place the division', steps: ['Pages ÷ (pages/minute) = pages × (minutes/page) = minutes ✓', 'Multiplying instead would give pages², which is meaningless — and that is how you know it is wrong.', 'Dimensional analysis is not just for physics; it settles every rate question on the SAT.'] },
    ],
    tags: ['rate', 'time', 'division'], estimatedSeconds: 60,
  },

  // ═══════ UNIT 12 — Percentages, Percent Change, and Interest ═══════
  {
    domain: 'SAT', num: 111, unit: 12, order: 1, slug: 'sat-percent-of',
    standard: 'SAT.PSDA.2', difficulty: 1,
    prompt: 'What is $30\\%$ of $250$?',
    answerType: 'numeric', primaryAnswer: '75', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Of" means multiply. Convert the percent to a decimal first.' },
      { level: 'guide', text: '$0.30 \\times 250$.' },
      { level: 'reveal', text: '$75$.' },
    ],
    learningObjective: 'Compute a percent of a number.',
    topic: 'Basic percentages',
    explanation: [
      '$30\\% = 0.30$.',
      '"Percent of" means multiply: $0.30 \\times 250 = 75$.',
      'Mental check: $10\\%$ of $250$ is $25$, so $30\\%$ is $3 \\times 25 = 75$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Build percents from 10%', steps: ['Finding $10\\%$ is just moving the decimal one place: $250 \\to 25$.', 'From there, $30\\%$ is three of those, $5\\%$ is half of one, and $1\\%$ is a tenth.', 'This decomposition handles most percent arithmetic mentally, faster than reaching for the calculator.'] },
    ],
    tags: ['percent'], estimatedSeconds: 30,
  },
  {
    domain: 'SAT', num: 112, unit: 12, order: 2, slug: 'sat-what-percent',
    standard: 'SAT.PSDA.2', difficulty: 1,
    prompt: '$18$ is what percent of $72$?',
    answerType: 'numeric', primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Divide the part by the whole, then convert to a percent.' },
      { level: 'guide', text: '$\\dfrac{18}{72} = 0.25$.' },
      { level: 'reveal', text: '$0.25 = 25\\%$.' },
    ],
    learningObjective: 'Express one number as a percent of another.',
    topic: 'Basic percentages',
    explanation: [
      'The structure is part $=$ percent $\\times$ whole, so percent $= \\dfrac{\\text{part}}{\\text{whole}}$.',
      '$\\dfrac{18}{72} = \\dfrac{1}{4} = 0.25$.',
      'As a percent that is $25\\%$.',
    ],
    alternativeExplanations: [
      { title: 'Identify the whole before dividing', steps: ['The number after "of" is always the whole; the other is the part.', 'Here the whole is $72$, so $72$ goes in the denominator.', 'Dividing the other way gives $4$, or $400\\%$ — a trap that appears whenever the part and whole could plausibly swap.'] },
    ],
    tags: ['percent', 'part-whole'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 113, unit: 12, order: 3, slug: 'sat-percent-increase-price',
    standard: 'SAT.PSDA.2', difficulty: 2,
    prompt: 'A jacket priced at $\\$80$ is marked up by $15\\%$. What is the new price, in dollars?',
    answerType: 'numeric', primaryAnswer: '92', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'A $15\\%$ increase means the new price is $115\\%$ of the old.' },
      { level: 'guide', text: '$80 \\times 1.15$.' },
      { level: 'reveal', text: '$\\$92$.' },
    ],
    learningObjective: 'Apply a percent increase using a single multiplier.',
    topic: 'Percent change',
    explanation: [
      'A $15\\%$ increase keeps the original $100\\%$ and adds $15\\%$, so multiply by $1.15$.',
      '$80 \\times 1.15 = 92$.',
      'Or compute the increase separately: $0.15 \\times 80 = 12$, then $80 + 12 = \\$92$.',
    ],
    alternativeExplanations: [
      { title: 'The multiplier method scales better', steps: ['One multiplication ($\\times 1.15$) replaces two steps, and there is no risk of forgetting to add the increase back.', 'It also chains: two successive $15\\%$ increases are just $\\times 1.15$ twice.', 'Get comfortable converting a percent change to a multiplier — it is the backbone of this entire unit.'] },
    ],
    tags: ['percent-increase', 'multiplier'], estimatedSeconds: 50,
  },
  {
    domain: 'SAT', num: 114, unit: 12, order: 4, slug: 'sat-reverse-percent',
    standard: 'SAT.PSDA.2', difficulty: 2,
    prompt: 'After a $25\\%$ discount, a pair of shoes costs $\\$60$. What was the original price, in dollars?',
    answerType: 'numeric', primaryAnswer: '80', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $\\$60$ represents what fraction of the original price?' },
      { level: 'guide', text: 'A $25\\%$ discount leaves $75\\%$, so $0.75p = 60$.' },
      { level: 'reveal', text: '$p = \\dfrac{60}{0.75} = 80$ dollars.' },
    ],
    learningObjective: 'Reverse a percent change to recover the original amount.',
    topic: 'Reverse percentages',
    explanation: [
      'A $25\\%$ discount means the customer pays $75\\%$ of the original price.',
      'So $0.75p = 60$, giving $p = \\dfrac{60}{0.75} = \\$80$.',
      'Check: $25\\%$ of $80$ is $20$, and $80 - 20 = \\$60$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Why adding 25% back fails', steps: ['Adding $25\\%$ to $\\$60$ gives $\\$75$, which is one of the answer choices — and it is wrong.', 'The discount was $25\\%$ of the *original*, not of the sale price, so the two percentages are taken from different bases.', 'Reverse percent questions are built entirely on this asymmetry. Always divide by the multiplier; never add the percent back.'] },
    ],
    tags: ['reverse-percent', 'discount'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 115, unit: 12, order: 5, slug: 'sat-percent-change',
    standard: 'SAT.PSDA.2', difficulty: 2,
    prompt: 'A quantity increases from $40$ to $50$. What is the percent increase?',
    answerType: 'numeric', primaryAnswer: '25', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Percent change is the change divided by the *original* value.' },
      { level: 'guide', text: 'The change is $10$, and the original is $40$.' },
      { level: 'reveal', text: '$\\dfrac{10}{40} = 0.25 = 25\\%$.' },
    ],
    learningObjective: 'Compute a percent increase from two values.',
    topic: 'Percent change',
    explanation: [
      'Percent change $= \\dfrac{\\text{new} - \\text{old}}{\\text{old}} = \\dfrac{50 - 40}{40}$.',
      '$= \\dfrac{10}{40} = 0.25$, or $25\\%$.',
      'Dividing by the new value instead gives $20\\%$ — the standard trap on this question type.',
    ],
    alternativeExplanations: [
      { title: 'Percent change is not symmetric', steps: ['Going $40 \\to 50$ is a $25\\%$ increase, but going $50 \\to 40$ is only a $20\\%$ decrease.', 'The same absolute change of $10$ gives different percentages because the base differs.', 'Whenever a question walks a value up and then back down, expect this asymmetry to be the point.'] },
    ],
    tags: ['percent-change', 'increase'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 116, unit: 12, order: 6, slug: 'sat-successive-percent',
    standard: 'SAT.PSDA.2', difficulty: 2,
    prompt: 'A price is increased by $20\\%$ and then the new price is decreased by $20\\%$. Compared with the original price, the final price is:',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'the same', correct: false },
      { id: 'B', label: '$4\\%$ lower', correct: true },
      { id: 'C', label: '$4\\%$ higher', correct: false },
      { id: 'D', label: '$40\\%$ lower', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Percent changes multiply — they do not add or cancel.' },
      { level: 'guide', text: 'The combined multiplier is $1.20 \\times 0.80$.' },
      { level: 'reveal', text: '$1.20 \\times 0.80 = 0.96$, which is $4\\%$ below the original.' },
    ],
    learningObjective: 'Chain successive percent changes with multipliers.',
    topic: 'Successive percent change',
    explanation: [
      'Apply the multipliers in order: $\\times 1.20$, then $\\times 0.80$.',
      '$1.20 \\times 0.80 = 0.96$, so the final price is $96\\%$ of the original — a $4\\%$ decrease.',
      'Concretely with $\\$100$: up $20\\%$ gives $\\$120$, then down $20\\%$ of $\\$120$ is $\\$24$ off, landing at $\\$96$.',
    ],
    alternativeExplanations: [
      { title: 'Why it does not cancel', steps: ['The $20\\%$ increase was taken on $\\$100$, but the $20\\%$ decrease was taken on the larger $\\$120$.', 'A bigger base makes the decrease bigger in absolute terms, so you end up below where you started.', 'The order does not matter — $0.80 \\times 1.20$ is the same $0.96$ — but the answer is never "the same".'] },
    ],
    tags: ['successive-percent', 'multiplier'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 117, unit: 12, order: 7, slug: 'sat-double-discount',
    standard: 'SAT.PSDA.2', difficulty: 3,
    prompt: 'An item originally priced at $\\$200$ is discounted by $20\\%$, and then an additional $10\\%$ is taken off the sale price. What is the final price, in dollars?',
    answerType: 'numeric', primaryAnswer: '144', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Apply the discounts one after the other, not added together.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try it on $\\$100$: down $50\\%$ gives $\\$50$, then down $10\\%$ of *that* gives $\\$45$ — not $\\$40$. The second discount applies to the reduced price, never to the original.' },
      { level: 'guide', text: '$200 \\times 0.80 = 160$, then take $10\\%$ off that.' },
      { level: 'reveal', text: '$160 \\times 0.90 = \\$144$.' },
    ],
    learningObjective: 'Apply successive discounts correctly.',
    topic: 'Successive percent change',
    explanation: [
      'First discount: $200 \\times 0.80 = \\$160$.',
      'Second discount, taken on the new price: $160 \\times 0.90 = \\$144$.',
      'Or combine the multipliers: $200 \\times 0.80 \\times 0.90 = 200 \\times 0.72 = \\$144$.',
    ],
    alternativeExplanations: [
      { title: 'A 30% discount is not the same thing', steps: ['Adding the discounts gives $30\\%$ off, or $\\$140$ — and that will be an answer choice.', 'The true combined multiplier is $0.80 \\times 0.90 = 0.72$, a $28\\%$ total discount, not $30\\%$.', 'Successive discounts always total *less* than their sum, because the second is taken on an already-reduced price.'] },
    ],
    tags: ['successive-discount', 'percent'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 118, unit: 12, order: 8, slug: 'sat-population-growth-percent',
    standard: 'SAT.PSDA.2', difficulty: 3,
    prompt: 'A town\'s population of $12{,}500$ grows by $4\\%$ in one year. What is the population after that year?',
    answerType: 'numeric', primaryAnswer: '13000', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Multiply by $1.04$.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a small town: $200$ growing $10\\%$ gains $20$, reaching $220$. Compute the increase, then decide whether the question wants the increase or the new total.' },
      { level: 'guide', text: '$4\\%$ of $12{,}500$ is $500$.' },
      { level: 'reveal', text: '$12{,}500 + 500 = 13{,}000$.' },
    ],
    learningObjective: 'Apply a percent increase to a large quantity.',
    topic: 'Percent change',
    explanation: [
      '$4\\%$ of $12{,}500$ is $0.04 \\times 12500 = 500$.',
      'The new population is $12500 + 500 = 13{,}000$.',
      'Or in one step: $12500 \\times 1.04 = 13{,}000$.',
    ],
    alternativeExplanations: [
      { title: 'Answer the question that was asked', steps: ['The increase is $500$; the new population is $13{,}000$. Both will appear as choices.', 'Read whether the question wants "the increase" or "the population after".', 'This is the single most common way to lose an otherwise trivial percent question.'] },
    ],
    tags: ['percent-increase', 'population'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 119, unit: 12, order: 9, slug: 'sat-reverse-percent-increase',
    standard: 'SAT.PSDA.2', difficulty: 3,
    prompt: 'A number increased by $30\\%$ is $156$. What was the original number?',
    answerType: 'numeric', primaryAnswer: '120', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The $156$ is $130\\%$ of the original.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try clean numbers: a number increased by $50\\%$ is $30$. Then $1.5n = 30$, so $n = 20$ — you divide by $1.5$, not subtract $50\\%$ from $30$.' },
      { level: 'guide', text: '$1.30n = 156$.' },
      { level: 'reveal', text: '$n = \\dfrac{156}{1.30} = 120$.' },
    ],
    learningObjective: 'Reverse a percent increase to recover the original value.',
    topic: 'Reverse percentages',
    explanation: [
      'Increasing by $30\\%$ means multiplying by $1.30$, so $1.30n = 156$.',
      'Divide: $n = \\dfrac{156}{1.3} = 120$.',
      'Check: $30\\%$ of $120$ is $36$, and $120 + 36 = 156$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Subtracting 30% is not the inverse', steps: ['Taking $30\\%$ off $156$ gives $109.2$ — and it is wrong, because the $30\\%$ was of the smaller original.', 'The inverse of "multiply by $1.30$" is "divide by $1.30$", never "subtract $30\\%$".', 'Whenever a question gives you the result and asks for the start, divide by the multiplier.'] },
    ],
    tags: ['reverse-percent', 'increase'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 120, unit: 12, order: 10, slug: 'sat-compound-interest',
    standard: 'SAT.PSDA.2', difficulty: 3,
    prompt: 'An account holds $\\$2{,}000$ and earns $5\\%$ interest compounded annually. What is the balance, in dollars, after $2$ years?',
    answerType: 'numeric', primaryAnswer: '2205', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Compounded means the second year earns interest on the first year\'s interest too.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try two easy years: $\\$100$ at $10\\%$ becomes $\\$110$, then $\\$121$ — not $\\$120$. The second year earns interest on the first year\'s interest too.' },
      { level: 'guide', text: '$2000 \\times 1.05 = 2100$ after one year.' },
      { level: 'reveal', text: '$2100 \\times 1.05 = \\$2{,}205$.' },
    ],
    learningObjective: 'Compute a compound-interest balance.',
    topic: 'Interest',
    explanation: [
      'Compound interest applies the multiplier once per period: $A = 2000(1.05)^2$.',
      'Year 1: $2000 \\times 1.05 = \\$2100$. Year 2: $2100 \\times 1.05 = \\$2205$.',
      'The extra $\\$5$ over simple interest is the interest earned on the first year\'s $\\$100$.',
    ],
    alternativeExplanations: [
      { title: 'Compound versus simple', steps: ['Simple interest would pay $5\\%$ of the original $\\$2000$ each year: $\\$100 + \\$100 = \\$2200$.', 'Compound interest pays on the growing balance, so it reaches $\\$2205$.', 'The gap is small over two years and enormous over twenty — which is why the SAT tests that you know they are different.'] },
    ],
    tags: ['compound-interest', 'exponential'], estimatedSeconds: 85,
  },

  // ═══════ UNIT 13 — One-Variable Data: Center, Spread, and Shape ═══════
  {
    domain: 'SAT', num: 121, unit: 13, order: 1, slug: 'sat-mean-basic',
    standard: 'SAT.PSDA.3', difficulty: 1,
    prompt: 'What is the mean of the data set $4$, $8$, $10$, $14$?',
    answerType: 'numeric', primaryAnswer: '9', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Add the values, then divide by how many there are.' },
      { level: 'guide', text: 'The sum is $36$ and there are $4$ values.' },
      { level: 'reveal', text: '$36 \\div 4 = 9$.' },
    ],
    learningObjective: 'Compute the mean of a small data set.',
    topic: 'Measures of center',
    explanation: [
      'Sum the values: $4 + 8 + 10 + 14 = 36$.',
      'Divide by the count: $36 \\div 4 = 9$.',
      'Sanity check: the mean must lie between the smallest and largest values, and $9$ is between $4$ and $14$ ✓',
    ],
    alternativeExplanations: [
      { title: 'The mean always lands inside the range', steps: ['If your computed mean is below the minimum or above the maximum, you have made an arithmetic error.', 'This one-second check catches a mis-added sum or a wrong count.', 'It is worth running on every mean question, especially the ones with more values.'] },
    ],
    tags: ['mean', 'measures-of-center'], estimatedSeconds: 35,
  },
  {
    domain: 'SAT', num: 122, unit: 13, order: 2, slug: 'sat-median-odd',
    standard: 'SAT.PSDA.3', difficulty: 1,
    prompt: 'What is the median of the data set $3$, $7$, $1$, $9$, $5$?',
    answerType: 'numeric', primaryAnswer: '5', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Sort the values before doing anything else.' },
      { level: 'guide', text: 'Sorted: $1, 3, 5, 7, 9$.' },
      { level: 'reveal', text: 'The middle value is $5$.' },
    ],
    learningObjective: 'Find the median of an unsorted data set.',
    topic: 'Measures of center',
    explanation: [
      'Sort the values: $1, 3, 5, 7, 9$.',
      'With five values, the median is the third one.',
      'That is $5$.',
    ],
    alternativeExplanations: [
      { title: 'Sorting is not optional', steps: ['Taking the middle of the unsorted list gives $1$ — the most common error on median questions.', 'The median is defined by *position after sorting*, not by position as listed.', 'Write the sorted list on scratch paper; do not try to sort in your head.'] },
    ],
    tags: ['median', 'measures-of-center'], estimatedSeconds: 40,
  },
  {
    domain: 'SAT', num: 123, unit: 13, order: 3, slug: 'sat-mean-vs-median-skew',
    standard: 'SAT.PSDA.3', difficulty: 2,
    prompt: 'For the data set $2$, $4$, $4$, $5$, $10$, which statement is true?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'The mean is greater than the median', correct: true },
      { id: 'B', label: 'The median is greater than the mean', correct: false },
      { id: 'C', label: 'The mean and median are equal', correct: false },
      { id: 'D', label: 'The mean is less than the smallest value', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Compute both, or reason from the shape: is there a value pulling one of them?' },
      { level: 'guide', text: 'Mean $= 25 \\div 5 = 5$; median is the middle value, $4$.' },
      { level: 'reveal', text: '$5 > 4$, so the mean is greater.' },
    ],
    learningObjective: 'Compare mean and median for a skewed data set.',
    topic: 'Center and shape',
    explanation: [
      'The values are already sorted, so the median is the third: $4$.',
      'The mean is $\\dfrac{2 + 4 + 4 + 5 + 10}{5} = \\dfrac{25}{5} = 5$.',
      'The mean exceeds the median because the value $10$ sits far above the rest and drags the mean up.',
    ],
    alternativeExplanations: [
      { title: 'Read the skew instead of computing', steps: ['The values cluster at $2$-$5$ with one straggler at $10$ — right-skewed.', 'The mean chases outliers; the median ignores them. So in a right-skewed set, mean > median.', 'Left-skewed reverses it. Knowing this rule answers most center-comparison questions without any arithmetic.'] },
    ],
    tags: ['mean', 'median', 'skew'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 124, unit: 13, order: 4, slug: 'sat-outlier-effect',
    standard: 'SAT.PSDA.3', difficulty: 2,
    prompt: 'A data set of $20$ test scores has a mean of $75$ and a median of $76$. One additional score of $12$ is added to the set. Which best describes the effect on the mean and the median?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'Both decrease substantially', correct: false },
      { id: 'B', label: 'The mean decreases substantially; the median changes little', correct: true },
      { id: 'C', label: 'The median decreases substantially; the mean changes little', correct: false },
      { id: 'D', label: 'Neither changes', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Which measure uses every value, and which uses only position?' },
      { level: 'guide', text: 'The mean sums all values, so an extreme value moves it. The median only shifts by one position.' },
      { level: 'reveal', text: 'The mean drops noticeably; the median barely moves.' },
    ],
    learningObjective: 'Predict how an outlier affects the mean versus the median.',
    topic: 'Outliers and resistance',
    explanation: [
      'The mean is computed from the sum, so adding a value far below the others pulls it down: the new mean is $\\dfrac{20(75) + 12}{21} = \\dfrac{1512}{21} = 72$.',
      'The median depends only on which value sits in the middle. Adding one low score shifts the middle position by half a slot, so the median moves at most a little.',
      'This is what "the median is resistant to outliers" means.',
    ],
    alternativeExplanations: [
      { title: 'Why the median resists', steps: ['To move the median substantially, you would have to add many low values, not one.', 'The median does not care *how* low the new value is — only that it is below the middle.', 'Replacing that $12$ with a $0$ would change the mean again but leave the median exactly where it is.'] },
    ],
    tags: ['outlier', 'mean', 'median', 'resistance'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 125, unit: 13, order: 5, slug: 'sat-standard-deviation-compare',
    standard: 'SAT.PSDA.3', difficulty: 2,
    prompt: 'Data set P is $10$, $10$, $11$, $12$, $12$. Data set Q is $2$, $6$, $11$, $16$, $20$. Both have a mean of $11$. Which statement is true?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'P has the greater standard deviation', correct: false },
      { id: 'B', label: 'Q has the greater standard deviation', correct: true },
      { id: 'C', label: 'They have equal standard deviations', correct: false },
      { id: 'D', label: 'Standard deviation cannot be compared without more information', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'Standard deviation measures how far the values sit from their mean.' },
      { level: 'guide', text: 'P\'s values are all within $1$ of the mean; Q\'s stretch $9$ away on each side.' },
      { level: 'reveal', text: 'Q is far more spread out, so Q has the greater standard deviation.' },
    ],
    learningObjective: 'Compare standard deviations by inspecting spread.',
    topic: 'Measures of spread',
    explanation: [
      'Standard deviation measures typical distance from the mean — it is a spread measure, not a center measure.',
      'Set P is tightly clustered: every value is within $1$ of $11$.',
      'Set Q ranges from $2$ to $20$, with values as far as $9$ from the mean. So Q has the larger standard deviation.',
    ],
    alternativeExplanations: [
      { title: 'You never actually compute it', steps: ['The SAT never asks you to calculate a standard deviation by hand — only to compare two sets.', 'Look at how tightly the values cluster around their mean; tighter means smaller.', 'Equal means tell you nothing about spread, which is exactly why the question gives both sets the same mean.'] },
    ],
    tags: ['standard-deviation', 'spread', 'comparison'], estimatedSeconds: 70,
  },
  {
    domain: 'SAT', num: 126, unit: 13, order: 6, slug: 'sat-needed-score',
    standard: 'SAT.PSDA.3', difficulty: 2,
    prompt: 'A student has taken $5$ tests with an average score of $82$. What score is needed on a sixth test to raise the average to exactly $84$?',
    answerType: 'numeric', primaryAnswer: '94', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Work with totals, not averages.' },
      { level: 'guide', text: 'Current total: $5 \\times 82 = 410$. Needed total: $6 \\times 84 = 504$.' },
      { level: 'reveal', text: '$504 - 410 = 94$.' },
    ],
    learningObjective: 'Use the sum-equals-mean-times-count relationship.',
    topic: 'Working with means',
    explanation: [
      'The key identity is sum $=$ mean $\\times$ count.',
      'Current sum: $5 \\times 82 = 410$. Required sum for six tests averaging $84$: $6 \\times 84 = 504$.',
      'The sixth score must make up the difference: $504 - 410 = 94$.',
    ],
    alternativeExplanations: [
      { title: 'Think in terms of the deficit', steps: ['To lift the average by $2$ points, all five existing tests need $2$ extra points each — a deficit of $10$.', 'The new test must also hit the target of $84$ itself, plus cover that $10$.', '$84 + 10 = 94$. This "cover the deficit" view is fast and makes the answer feel inevitable.'] },
    ],
    tags: ['mean', 'sum', 'word-problem'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 127, unit: 13, order: 7, slug: 'sat-remove-value-mean',
    standard: 'SAT.PSDA.3', difficulty: 3,
    prompt: 'A set of $8$ numbers has a mean of $15$. If the number $22$ is removed from the set, what is the mean of the remaining numbers?',
    answerType: 'numeric', primaryAnswer: '14', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Convert the mean into a total first.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a tiny set: three numbers with mean $10$ total $30$. Remove a $12$ and $18$ is left across two numbers, so the new mean is $9$. Always convert the mean to a total first.' },
      { level: 'guide', text: 'The total is $8 \\times 15 = 120$. Removing $22$ leaves $98$ across $7$ numbers.' },
      { level: 'reveal', text: '$98 \\div 7 = 14$.' },
    ],
    learningObjective: 'Recompute a mean after removing a value.',
    topic: 'Working with means',
    explanation: [
      'The original sum is $8 \\times 15 = 120$.',
      'Removing $22$ leaves a sum of $120 - 22 = 98$ across $7$ numbers.',
      'The new mean is $98 \\div 7 = 14$. It fell because the removed value was above the old mean.',
    ],
    alternativeExplanations: [
      { title: 'Predict the direction first', steps: ['Removing a value *above* the mean pulls the mean down; removing one below pushes it up.', 'Here $22 > 15$, so the new mean must be below $15$ — which rules out any choice at or above it.', 'Predicting the direction before computing turns a calculation into a check.'] },
    ],
    tags: ['mean', 'sum', 'removal'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 128, unit: 13, order: 8, slug: 'sat-median-even-count',
    standard: 'SAT.PSDA.3', difficulty: 3,
    prompt: 'What is the median of the data set $4$, $7$, $9$, $12$, $15$, $20$?',
    answerType: 'numeric', primaryAnswer: '10.5', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.01,
    alternativeAnswers: ['21/2'],
    hints: [
      { level: 'nudge', text: 'With an even number of values there is no single middle value.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try four values: for $2, 4, 6, 8$ the middle two are $4$ and $6$, so the median is $5$. With an even count you average the middle pair.' },
      { level: 'guide', text: 'The two middle values are $9$ and $12$.' },
      { level: 'reveal', text: 'Average them: $\\dfrac{9 + 12}{2} = 10.5$.' },
    ],
    learningObjective: 'Find the median of an even-sized data set.',
    topic: 'Measures of center',
    explanation: [
      'The data is already sorted. With $6$ values, the middle two are the 3rd and 4th: $9$ and $12$.',
      'The median is their average: $\\dfrac{9 + 12}{2} = 10.5$.',
      'Note that the median need not be a value in the data set.',
    ],
    alternativeExplanations: [
      { title: 'Locating the middle pair', steps: ['For $n$ values with $n$ even, the middle two sit at positions $\\dfrac{n}{2}$ and $\\dfrac{n}{2} + 1$.', 'Here $n = 6$, so positions $3$ and $4$ — the values $9$ and $12$.', 'Counting inward from both ends simultaneously is the practical version of this, and it is harder to miscount.'] },
    ],
    tags: ['median', 'even-count'], estimatedSeconds: 60,
  },
  {
    domain: 'SAT', num: 129, unit: 13, order: 9, slug: 'sat-frequency-table-mean',
    standard: 'SAT.PSDA.3', difficulty: 3,
    prompt: 'The table shows the number of pets owned by each of $20$ students. What is the mean number of pets per student?',
    diagram: {
      kind: 'ascii',
      art: [
        ' Pets  | Number of students',
        '-------+-------------------',
        '   1   |         2',
        '   2   |         5',
        '   3   |         8',
        '   4   |         5',
      ].join('\n'),
    },
    answerType: 'numeric', primaryAnswer: '2.8', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.01,
    alternativeAnswers: ['14/5'],
    hints: [
      { level: 'nudge', text: 'Each row represents several students, so weight each value by its frequency.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try two rows: if $1$ appears twice and $3$ appears twice, the total is $2 + 6 = 8$ across $4$ students, so the mean is $2$. Weight each value by its frequency.' },
      { level: 'guide', text: 'Total pets $= 1(2) + 2(5) + 3(8) + 4(5) = 2 + 10 + 24 + 20 = 56$.' },
      { level: 'reveal', text: '$56 \\div 20 = 2.8$ pets per student.' },
    ],
    learningObjective: 'Compute a mean from a frequency table.',
    topic: 'Frequency tables',
    explanation: [
      'Multiply each value by how many students reported it: $1(2) + 2(5) + 3(8) + 4(5)$.',
      'That is $2 + 10 + 24 + 20 = 56$ total pets.',
      'Divide by the number of students: $56 \\div 20 = 2.8$.',
    ],
    alternativeExplanations: [
      { title: 'Do not average the value column', steps: ['Averaging $1, 2, 3, 4$ gives $2.5$ — wrong, because it treats each row as one student.', 'The frequency column says how many students each row stands for, and it must weight the calculation.', 'Divide by the total *frequency* ($20$), never by the number of rows ($4$).'] },
    ],
    tags: ['frequency-table', 'weighted-mean'], estimatedSeconds: 90,
  },
  {
    domain: 'SAT', num: 130, unit: 13, order: 10, slug: 'sat-range-and-spread',
    standard: 'SAT.PSDA.3', difficulty: 3,
    prompt: 'A data set has a minimum of $12$ and a range of $37$. What is the maximum value in the data set?',
    answerType: 'numeric', primaryAnswer: '49', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Range is the maximum minus the minimum.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try small numbers: a set with minimum $5$ and range $10$ has maximum $15$, since $15 - 5 = 10$. Range is max minus min, so max is min plus range.' },
      { level: 'guide', text: 'So maximum $=$ minimum $+$ range.' },
      { level: 'reveal', text: '$12 + 37 = 49$.' },
    ],
    learningObjective: 'Rearrange the definition of range to find a missing extreme.',
    topic: 'Measures of spread',
    explanation: [
      'Range $=$ maximum $-$ minimum, so maximum $=$ minimum $+$ range.',
      '$12 + 37 = 49$.',
      'Check: $49 - 12 = 37$ ✓',
    ],
    alternativeExplanations: [
      { title: 'Range says nothing about the middle', steps: ['Two data sets can share a range of $37$ and look nothing alike — one clustered, one evenly spread.', 'Range uses only the two extreme values, which also makes it very sensitive to outliers.', 'That is why the SAT pairs range questions with standard deviation questions: they measure spread in genuinely different ways.'] },
    ],
    tags: ['range', 'spread'], estimatedSeconds: 55,
  },

  // ═══ UNIT 14 — Two-Variable Data, Probability, and Inference ═══
  {
    domain: 'SAT', num: 131, unit: 14, order: 1, slug: 'sat-two-way-basic-probability',
    standard: 'SAT.PSDA.4', difficulty: 1,
    prompt: 'The table shows how $200$ students commute to school. If one student is selected at random, what is the probability that the student walks? Give your answer as a decimal.',
    diagram: {
      kind: 'ascii',
      art: [
        '           | Grade 9 | Grade 10 | Total',
        '-----------+---------+----------+------',
        '  Bus      |    45   |    35    |   80',
        '  Walk     |    30   |    20    |   50',
        '  Car      |    35   |    35    |   70',
        '-----------+---------+----------+------',
        '  Total    |   110   |    90    |  200',
      ].join('\n'),
    },
    answerType: 'numeric', primaryAnswer: '0.25', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.001,
    alternativeAnswers: ['1/4', '.25'],
    hints: [
      { level: 'nudge', text: 'Probability is the favorable count over the total count.' },
      { level: 'guide', text: '$50$ students walk out of $200$ total.' },
      { level: 'reveal', text: '$\\dfrac{50}{200} = 0.25$.' },
    ],
    learningObjective: 'Read a simple probability from a two-way table.',
    topic: 'Two-way tables',
    explanation: [
      'The question puts no condition on grade, so the denominator is every student: $200$.',
      'The Walk row totals $50$.',
      '$\\dfrac{50}{200} = 0.25$.',
    ],
    alternativeExplanations: [
      { title: 'Find the denominator before the numerator', steps: ['"Selected at random" from all students means the grand total, $200$.', 'Had the question said "selected from Grade 9", the denominator would be $110$ instead.', 'Circling the denominator in the table first is the habit that makes every two-way-table question routine.'] },
    ],
    tags: ['two-way-table', 'probability'], estimatedSeconds: 55,
  },
  {
    domain: 'SAT', num: 132, unit: 14, order: 2, slug: 'sat-line-of-best-fit-predict',
    standard: 'SAT.PSDA.4', difficulty: 1,
    prompt: 'A line of best fit for a scatterplot has the equation $y = 2.4x + 11$, where $x$ is hours studied and $y$ is the score. What score does the model predict for a student who studies $5$ hours?',
    answerType: 'numeric', primaryAnswer: '23', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'Substitute $x = 5$ into the equation.' },
      { level: 'guide', text: '$y = 2.4(5) + 11$.' },
      { level: 'reveal', text: '$y = 12 + 11 = 23$.' },
    ],
    learningObjective: 'Use a line of best fit to make a prediction.',
    topic: 'Lines of best fit',
    explanation: [
      'Substitute the given input: $y = 2.4(5) + 11$.',
      '$2.4 \\times 5 = 12$, so $y = 12 + 11 = 23$.',
      'This is a *predicted* value from the model, not an observed data point.',
    ],
    alternativeExplanations: [
      { title: 'Predicted versus actual', steps: ['A question asking for the predicted value wants you to read the line.', 'A question asking for the actual value wants you to read the data point.', 'The gap between them is the residual, and asking for that gap is a standard SAT question — so always note which one is being requested.'] },
    ],
    tags: ['best-fit', 'prediction', 'scatterplot'], estimatedSeconds: 45,
  },
  {
    domain: 'SAT', num: 133, unit: 14, order: 3, slug: 'sat-residual',
    standard: 'SAT.PSDA.4', difficulty: 2,
    prompt: 'A line of best fit is $y = 3x + 8$. One data point in the scatterplot is $(6, 30)$. What is the residual for that data point?',
    answerType: 'numeric', primaryAnswer: '4', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: 'The residual is the actual value minus the predicted value.' },
      { level: 'guide', text: 'The model predicts $3(6) + 8 = 26$; the actual value is $30$.' },
      { level: 'reveal', text: '$30 - 26 = 4$.' },
    ],
    learningObjective: 'Compute a residual from a model and an observed point.',
    topic: 'Residuals',
    explanation: [
      'Predicted value: $y = 3(6) + 8 = 18 + 8 = 26$.',
      'Actual value from the data point: $30$.',
      'Residual $=$ actual $-$ predicted $= 30 - 26 = 4$. A positive residual means the point sits above the line.',
    ],
    alternativeExplanations: [
      { title: 'The sign carries meaning', steps: ['Positive residual: the actual value is above the line, so the model under-predicted.', 'Negative residual: the point is below the line, so the model over-predicted.', 'Computing predicted minus actual reverses the sign and gives $-4$ — which will be an answer choice.'] },
    ],
    tags: ['residual', 'best-fit'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 134, unit: 14, order: 4, slug: 'sat-conditional-probability',
    standard: 'SAT.PSDA.4', difficulty: 2,
    prompt: 'Using the commuting table, a student is selected at random from Grade $10$. What is the probability that this student takes the bus? Give your answer as a decimal rounded to the nearest hundredth.',
    diagram: {
      kind: 'ascii',
      art: [
        '           | Grade 9 | Grade 10 | Total',
        '-----------+---------+----------+------',
        '  Bus      |    45   |    35    |   80',
        '  Walk     |    30   |    20    |   50',
        '  Car      |    35   |    35    |   70',
        '-----------+---------+----------+------',
        '  Total    |   110   |    90    |  200',
      ].join('\n'),
    },
    answerType: 'numeric', primaryAnswer: '0.39', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.005,
    alternativeAnswers: ['7/18'],
    hints: [
      { level: 'nudge', text: '"Selected from Grade 10" restricts the pool. What is the new denominator?' },
      { level: 'guide', text: 'The Grade 10 column totals $90$, and $35$ of them take the bus.' },
      { level: 'reveal', text: '$\\dfrac{35}{90} \\approx 0.39$.' },
    ],
    learningObjective: 'Compute a conditional probability from a two-way table.',
    topic: 'Conditional probability',
    explanation: [
      'The condition "from Grade 10" restricts attention to that column, whose total is $90$.',
      'Within Grade 10, $35$ students take the bus.',
      '$\\dfrac{35}{90} = 0.3888\\ldots \\approx 0.39$.',
    ],
    alternativeExplanations: [
      { title: 'Three denominators, three different answers', steps: ['Out of all students: $\\dfrac{35}{200} = 0.175$.', 'Out of all bus riders: $\\dfrac{35}{80} = 0.4375$.', 'Out of Grade 10: $\\dfrac{35}{90} \\approx 0.39$ ✓ — same numerator every time. The phrase after "from" or "of those who" names the denominator.'] },
    ],
    tags: ['two-way-table', 'conditional-probability'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 135, unit: 14, order: 5, slug: 'sat-interpret-slope-best-fit',
    standard: 'SAT.PSDA.4', difficulty: 2,
    prompt: 'A scatterplot relates the number of years since a tree was planted, $x$, to its height in feet, $y$. The line of best fit is $y = 1.8x + 4$. What does $1.8$ represent in this model?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'The height of the tree when it was planted', correct: false },
      { id: 'B', label: 'The predicted increase in height, in feet, per year', correct: true },
      { id: 'C', label: 'The total height of the tree after one year', correct: false },
      { id: 'D', label: 'The number of years for the tree to reach $1.8$ feet', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The slope is a rate: output units per input unit.' },
      { level: 'guide', text: 'Here that is feet per year.' },
      { level: 'reveal', text: '$1.8$ is the predicted growth in feet for each additional year.' },
    ],
    learningObjective: 'Interpret the slope of a line of best fit in context.',
    topic: 'Interpreting models',
    explanation: [
      'The slope of any linear model is the change in $y$ for a one-unit change in $x$.',
      'With $y$ in feet and $x$ in years, the slope is measured in feet per year: the tree grows about $1.8$ feet each year.',
      'Choice A describes the intercept ($4$ feet at planting). Choice C would be $1.8 + 4 = 5.8$ feet.',
    ],
    alternativeExplanations: [
      { title: 'Say the units out loud', steps: ['Slope units are always "$y$-units per $x$-unit" — here, feet per year.', 'Once you have said "feet per year", only one answer choice can match.', 'This works on every interpretation question in this area, and it takes about three seconds.'] },
    ],
    tags: ['best-fit', 'interpret-slope', 'units'], estimatedSeconds: 65,
  },
  {
    domain: 'SAT', num: 136, unit: 14, order: 6, slug: 'sat-sample-generalization',
    standard: 'SAT.PSDA.4', difficulty: 2,
    prompt: 'A researcher randomly selected $200$ students from Lincoln High School and found that $62\\%$ preferred a later start time. Which conclusion is best supported?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'About $62\\%$ of all high school students nationwide prefer a later start time', correct: false },
      { id: 'B', label: 'About $62\\%$ of students at Lincoln High School prefer a later start time', correct: true },
      { id: 'C', label: 'A later start time causes students to perform better', correct: false },
      { id: 'D', label: 'Exactly $62\\%$ of students at Lincoln High School prefer a later start time', correct: false },
    ],
    primaryAnswer: 'B', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'A sample can only speak for the population it was drawn from.' },
      { level: 'guide', text: 'The sample came from one school, so the conclusion covers that school.' },
      { level: 'reveal', text: 'About $62\\%$ of Lincoln High School students — an estimate, not an exact figure.' },
    ],
    learningObjective: 'Determine the population a random sample supports conclusions about.',
    topic: 'Inference from samples',
    explanation: [
      'The students were randomly selected from Lincoln High School, so that school is the population the sample represents.',
      'Choice A over-generalizes to a population never sampled. Choice C claims causation, which requires a controlled experiment with random assignment.',
      'Choice D says "exactly", but a sample gives an estimate with uncertainty, not an exact population value. Choice B — "about", and scoped to the right population — is correct.',
    ],
    alternativeExplanations: [
      { title: 'Two questions settle every inference item', steps: ['First: who was sampled? The conclusion may not extend beyond that group.', 'Second: was there random *assignment* to treatments? Without it you cannot claim cause.', 'Random selection buys generalization; random assignment buys causation. They are different, and no study gets one for free from the other.'] },
    ],
    tags: ['inference', 'sampling', 'generalization'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 137, unit: 14, order: 7, slug: 'sat-margin-of-error',
    standard: 'SAT.PSDA.4', difficulty: 3,
    prompt: 'A poll estimates that $48\\%$ of voters support a measure, with a margin of error of $3$ percentage points. Which value of the true population percentage is NOT consistent with this result?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: '$45\\%$', correct: false },
      { id: 'B', label: '$47\\%$', correct: false },
      { id: 'C', label: '$51\\%$', correct: false },
      { id: 'D', label: '$53\\%$', correct: true },
    ],
    primaryAnswer: 'D', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The margin of error creates an interval around the estimate.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try an easy interval: an estimate of $50\\%$ with a margin of $2$ points spans $48\\%$ to $52\\%$. Build the interval first, then check which value sits outside it.' },
      { level: 'guide', text: 'The interval is $48 \\pm 3$, so from $45\\%$ to $51\\%$.' },
      { level: 'reveal', text: '$53\\%$ falls outside that interval.' },
    ],
    learningObjective: 'Build and use a margin-of-error interval.',
    topic: 'Margin of error',
    explanation: [
      'The estimate plus or minus the margin gives the plausible interval: $48 - 3 = 45$ to $48 + 3 = 51$.',
      'Choices A, B, and C all lie within $[45, 51]$ and are therefore consistent with the poll.',
      '$53\\%$ lies outside, so it is not supported.',
    ],
    alternativeExplanations: [
      { title: 'What shrinks the margin', steps: ['A larger sample narrows the margin of error; a smaller one widens it.', 'The margin reflects sampling variability only — it does not account for a biased sampling method.', 'A badly-drawn sample can have a tiny margin of error and still be completely wrong about the population.'] },
    ],
    tags: ['margin-of-error', 'inference', 'interval'], estimatedSeconds: 75,
  },
  {
    domain: 'SAT', num: 138, unit: 14, order: 8, slug: 'sat-causation-vs-correlation',
    standard: 'SAT.PSDA.4', difficulty: 3,
    prompt: 'In a study, $300$ volunteers were randomly assigned to either a new exercise program or no program. Those in the program showed significantly lower resting heart rates. Which conclusion is best supported?',
    answerType: 'multiple-choice',
    choices: [
      { id: 'A', label: 'The exercise program likely caused the lower heart rates among these volunteers', correct: true },
      { id: 'B', label: 'The exercise program lowers heart rates for all adults', correct: false },
      { id: 'C', label: 'Lower heart rates cause people to exercise more', correct: false },
      { id: 'D', label: 'No conclusion about cause can be drawn from this study', correct: false },
    ],
    primaryAnswer: 'A', acceptanceMode: 'exact',
    hints: [
      { level: 'nudge', text: 'The volunteers were *randomly assigned* to the groups. What does that permit?' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try the contrast: a survey asking who already exercises can only show an association, but randomly assigning people to exercise or not can show cause. The design decides what you may claim.' },
      { level: 'guide', text: 'Random assignment to treatments allows a causal conclusion.' },
      { level: 'reveal', text: 'But the volunteers were not randomly selected from all adults, so the conclusion stays with them.' },
    ],
    learningObjective: 'Distinguish what random assignment and random selection each justify.',
    topic: 'Experimental design',
    explanation: [
      'Random *assignment* to treatment groups controls for confounding variables, so a causal claim is justified — that is what makes this an experiment rather than an observational study.',
      'But the participants were volunteers, not a random sample of all adults, so the result cannot be generalized beyond them. That rules out choice B.',
      'Choice C reverses the direction the design established, and choice D wrongly denies that random assignment supports causation.',
    ],
    alternativeExplanations: [
      { title: 'The two-by-two that answers every one of these', steps: ['Random selection + random assignment: cause, generalizable to the whole population.', 'Random assignment only (volunteers): cause, but only for the participants — this study.', 'Random selection only (survey): generalizable, but association only, never cause. Neither: association among participants only.'] },
    ],
    tags: ['experiment', 'causation', 'random-assignment'], estimatedSeconds: 90,
  },
  {
    domain: 'SAT', num: 139, unit: 14, order: 9, slug: 'sat-two-way-percent',
    standard: 'SAT.PSDA.4', difficulty: 3,
    prompt: 'Using the commuting table, what percent of the students who take the bus are in Grade $9$? Round to the nearest whole percent.',
    diagram: {
      kind: 'ascii',
      art: [
        '           | Grade 9 | Grade 10 | Total',
        '-----------+---------+----------+------',
        '  Bus      |    45   |    35    |   80',
        '  Walk     |    30   |    20    |   50',
        '  Car      |    35   |    35    |   70',
        '-----------+---------+----------+------',
        '  Total    |   110   |    90    |  200',
      ].join('\n'),
    },
    answerType: 'numeric', primaryAnswer: '56', acceptanceMode: 'numeric-tolerance', numericTolerance: 0.6,
    hints: [
      { level: 'nudge', text: '"Of the students who take the bus" names the denominator.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try a two-by-two table: if $6$ of $10$ bus riders are in Grade 9, that is $60\\%$ — denominator $10$, the bus total. The phrase after \'of\' names the denominator.' },
      { level: 'guide', text: 'The Bus row totals $80$, and $45$ of those are in Grade 9.' },
      { level: 'reveal', text: '$\\dfrac{45}{80} = 0.5625 \\approx 56\\%$.' },
    ],
    learningObjective: 'Compute a row-conditional percentage from a two-way table.',
    topic: 'Two-way tables',
    explanation: [
      'The phrase "of the students who take the bus" restricts the pool to the Bus row, total $80$.',
      'Of those, $45$ are in Grade 9.',
      '$\\dfrac{45}{80} = 0.5625$, which rounds to $56\\%$.',
    ],
    alternativeExplanations: [
      { title: 'Row condition versus column condition', steps: ['This question conditions on a *row* (bus riders), so the row total is the denominator.', 'The earlier question conditioned on a *column* (Grade 10), so the column total was the denominator.', 'Same table, same numerator style, entirely different answers. Reading which way the condition runs is the whole skill.'] },
    ],
    tags: ['two-way-table', 'percent', 'conditional'], estimatedSeconds: 80,
  },
  {
    domain: 'SAT', num: 140, unit: 14, order: 10, slug: 'sat-two-way-multi-step',
    standard: 'SAT.PSDA.4', difficulty: 3,
    prompt: 'Using the commuting table, how many more Grade $9$ students than Grade $10$ students do NOT take the bus?',
    diagram: {
      kind: 'ascii',
      art: [
        '           | Grade 9 | Grade 10 | Total',
        '-----------+---------+----------+------',
        '  Bus      |    45   |    35    |   80',
        '  Walk     |    30   |    20    |   50',
        '  Car      |    35   |    35    |   70',
        '-----------+---------+----------+------',
        '  Total    |   110   |    90    |  200',
      ].join('\n'),
    },
    answerType: 'numeric', primaryAnswer: '10', acceptanceMode: 'normalized',
    hints: [
      { level: 'nudge', text: '"Not the bus" means walk plus car — or the column total minus the bus count.' },
      { level: 'nudge', title: '🪜 Try a simpler one', text: 'Try it small: if a column totals $20$ and $8$ of them ride the bus, then $12$ do not. Subtracting from the column total is faster than adding the other rows.' },
      { level: 'guide', text: 'Grade 9: $110 - 45 = 65$. Grade 10: $90 - 35 = 55$.' },
      { level: 'reveal', text: '$65 - 55 = 10$.' },
    ],
    learningObjective: 'Combine complement and comparison steps on a two-way table.',
    topic: 'Two-way tables',
    explanation: [
      'Grade 9 students not taking the bus: $110 - 45 = 65$ (equivalently $30 + 35$).',
      'Grade 10 students not taking the bus: $90 - 35 = 55$ (equivalently $20 + 35$).',
      'The difference is $65 - 55 = 10$.',
    ],
    alternativeExplanations: [
      { title: 'Subtracting from the total beats adding rows', steps: ['Adding $30 + 35$ works, but with four or five commute categories the complement is much faster.', 'Column total minus the excluded row gives the "not" count in one step.', 'The complement also generalizes: for probability, $P(\\text{not } A) = 1 - P(A)$ is the same idea.'] },
    ],
    tags: ['two-way-table', 'complement', 'multi-step'], estimatedSeconds: 85,
  },
];
